### ISSUE TITLE
FtpLocalExists ( difference comparison update mode) 我觉得应该应该有个模式是支持文件大小和has比较的，如果本地和服务器不一致以服务器版本为主进行更新  

### ISSUE THREAD

**Issue by JyenZhou** [robinrodricks/FluentFTP#1025]
FtpLocalExists 我觉得应该应该有个模式是支持文件大小和has比较的，如果本地和服务器不一致以服务器版本为主进行更新
FtpLocalExists I think there should be a schema that supports file size and has comparisons, if local and server do not update primarily the server version

**Comment by JyenZhou** [comment]
补充说明： 
文件名、文件大小和has比较 ，也就是差异比较更新模式

Additional notes:
File name, file size, and has comparison, also known as the difference comparison update mode

**Comment by FanDjango** [comment]
We will put this on the wish list.

**Comment by JyenZhou** [comment]
> We will put this on the wish list.

Thank you very much and look forward to it

**Comment by FanDjango** [comment]
As an additional idea: You yourself could request a hash from the remote server and compare it to a hash on the local, programatically in your application, maybe?

**Comment by robinrodricks** [comment]
@JyenZhou why not use `CompareFile()` and then `UploadFile()`. We cannot fit a million behaviours in a single API call.
