### ISSUE TITLE
Hidden folder could not be downloaded (IIS)

### ISSUE THREAD

**Issue by JyenZhou** [robinrodricks/FluentFTP#1026]
我是用的是windows11自带的iis中ftp服务器  因此映射的是本地磁盘中文件夹  有着隐藏的文件夹属性（可能是系统级）  发现该类型文件夹无法下载下来

I am using windows11 comes with the iis ftp server, so the mapping is a folder in the local disk has hidden folder properties (may be system level) found that the type of folder can not be downloaded down

![image](https://user-images.githubusercontent.com/37990159/197713729-6cb3a83e-620f-42f9-9600-0ddbef6daf6b.png)

**Comment by FanDjango** [comment]
Code example and verbose log please. Also need information: Which version of FluenFTP? What happens when you try with a different client (manually)?

**Comment by JyenZhou** [comment]
> Code example and verbose log please. Also need information: Which version of FluenFTP? What happens when you try with a different client (manually)?


FluenFTP is version 42.0.0 in nuget
No error was reported after the successful download, but I found that the target was missing after the completion of the download. I put the application program in the ftp server, so the error will be reported after the missing
It was possible to pull manually before. Now it's doing automatic upgrade for convenience

In addition, this hidden folder is also implemented in code and it is at the system level and the code is as follows
DirectoryInfo dir = new DirectoryInfo(SystemResourcesPath);
//dir.Attributes = FileAttributes.System | FileAttributes.Hidden | FileAttributes.ReadOnly;
dir.Attributes |= FileAttributes.System;
dir.Attributes |= FileAttributes.Hidden;



FluenFTP 是nuget中的42.0.0版本
下载过成功没有报错，是我发现下载完成后目标缺失，我在ftp服务器中放的是应用程序，所以缺失后会报错
 之前手动拉取是可以的  为了方便现在在做自动升级 
  另外这个隐藏文件夹也是我用代码实现的它的级别是系统级 代码如下
     DirectoryInfo dir = new DirectoryInfo(SystemResourcesPath);
            //dir.Attributes = FileAttributes.System | FileAttributes.Hidden | FileAttributes.ReadOnly;
            dir.Attributes |= FileAttributes.System;
            dir.Attributes |= FileAttributes.Hidden;

**Comment by FanDjango** [comment]
V 42.0.0, ok.

No, so sorry, I meant can I see how you are downloading using FluentFTP, which API call etc. and the log output (verbose) please.

**Comment by robinrodricks** [comment]
Closing due to unresponsive ticket. Can reopen if OP replies.
