### ISSUE TITLE
Info logger is too verbose

### ISSUE THREAD

**Issue by MihailsKuzmins** [robinrodricks/FluentFTP#1034]
With the new integration of `Microsoft.Extension.Logging` just everything is being written to the logger (all the internal calls, etc.). I think it is too verbose and info like `>AutoConnect*()` must have the info level.

Would it be possible to reconsider logging level and make the info level logging not so verbose?

![image](https://user-images.githubusercontent.com/47413092/200300997-131612ed-80aa-47f7-a880-a9360c59aca4.png)

**Comment by robinrodricks** [comment]
Cannot you use a logging filter? Or configure your logging library to filter out the type of messages you don't want?

See [Logging wiki page](https://github.com/robinrodricks/FluentFTP/wiki/Logging#api) or read [Logging in v40](https://github.com/robinrodricks/FluentFTP/wiki/v40-Migration-Guide#6-use-the-new-logging-system).

You can try using `LegacyLogger`.
