### ISSUE TITLE
Connect timeout 

### ISSUE THREAD

**Issue by yossik1977** [robinrodricks/FluentFTP#1035]
**FTP OS:** N/A

**FTP Server:** N/A

**Computer OS:** ? Windows 10

**FluentFTP Version:** ? 42.0.1

**Framework:** .NetFramework 4.8 & .Net 5.0

Different behavior of Connect method (of AsyncFtpClient class) between .NetFramework 4.8 and .Net 5.0:
In .Net 5.0 when trying to connect to a server that doesn't exist, I get a System.TimeoutException and the timeout corresponds to the Config.ConnectTimeout I set.
In .NetFramework 4.8 (using the same code as in .Net 5.0) I get a System.Net.Sockets.SocketException and the timeout is 15 seconds no matter what I put inConfig.ConnectTimeout.

**Comment by FanDjango** [comment]
I have been able to reproduce this.

**Comment by FanDjango** [comment]
I have created a PR to fix this.
