### ISSUE TITLE
Misspelling in exception

### ISSUE THREAD

**Issue by kodsu** [robinrodricks/FluentFTP#1043]
Thank you for your library.
I use it whenever I need to do some FTP operations.

I noticed a little misspelling [here](https://github.com/robinrodricks/FluentFTP/blob/44378cf527dd09ebedda7706de58bcf61d932552/FluentFTP/Client/AsyncClient/DownloadFile.cs#L112)
![image](https://user-images.githubusercontent.com/17864005/201668272-53ee39f3-5301-45c0-8501-2568ed06ebe7.png)
I think it should be `Error while creating directories`

**Comment by FanDjango** [comment]
Changed, Merged, Fix in next release
