### ISSUE TITLE
How to use FluentFTP to get the files under the specified folder

### ISSUE THREAD

**Issue by GandalfGao** [robinrodricks/FluentFTP#1079]
I have a subfolder in ftp server. How can I get folders and files in the subfolder?

Please tell me how can do it?
Thanks!

**Comment by robinrodricks** [comment]
All mentioned here - https://github.com/robinrodricks/FluentFTP/wiki/Directory-Listing

**Comment by robinrodricks** [comment]
Code sample - https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP.CSharpExamples/GetListing.cs
