### ISSUE TITLE
Extra white spaces in host name are not handled

### ISSUE THREAD

**Issue by Gurudathn** [robinrodricks/FluentFTP#1110]
Hi,

When there is extra space in the host, FluentFTP.Connect() throws error "No such host is known".
Ex:-
                FtpClient ftpClient = new FtpClient();
                ftpClient.Host = ftpInfo.Host;   // ex;- "testhost " 
                ftpClient.Credentials = new NetworkCredential(ftpInfo.UserId, ftpInfo.Password);
                ftpClient.Port = ftpInfo.Port;
Sometimes value for host comes from DB and user don't know that host is having extra space.
If Fluentftp can handle this they it would be great.
This is a Minor issue but thought of reporting it.

**Comment by FanDjango** [comment]
I think it is the API callers responsibility to ensure a valid string which is then passed internally to DNS.

Why not code: `ftpClient.Host = ftpInfo.Host.Trim(); // ex;- "testhost " -> "testgost"`

**Comment by FanDjango** [comment]
You could also use `Uri.IsWellFormedUriString()` or `Uri.TryCreate()` to be really sure.

**Comment by FanDjango** [comment]
Anyway, FluentFTP checked it also, by trying to connect to the supplied uri and it failed and told you why.

**Comment by FanDjango** [comment]
As an enhancement, we might offer to validate the given host name, but I will leave the decision to add this to @robinrodricks

**Comment by FanDjango** [comment]
I've put this on my list of things to investigate

**Comment by robinrodricks** [comment]
> Sometimes value for host comes from DB and user don't know that host is having extra space.
> If Fluentftp can handle this they it would be great.
> This is a Minor issue but thought of reporting it.

Only Indians would be lazy enough to ask third party library authors to perform their [data normalization](https://www.splunk.com/en_us/blog/learn/data-normalization.html) for them.

I am closing this issue, I don't plan on implementing it.
