### ISSUE TITLE
How to know which files could not be downloaded and why

### ISSUE THREAD

**Issue by Miquel-agp** [robinrodricks/FluentFTP#1120]
**FTP Server OS:** Unix 

**FTP Server Type:** Vsftpd 
**Client Computer OS:** Windows 

**FluentFTP Version:** 43.0.1

**Framework:** .NET 6.0

Good morning, I would like someone to be able to help me, I am creating an FTP client in C# and when downloading multiple files simultaneously asynchronously with the DownloadFiles() method, I do not know how to track the files that could not be downloaded and their error, can you please help me?

**Comment by FanDjango** [comment]
One way would be to (mis-)use legacy logging, and catch the error message(s), "Failed to download ..."

**Comment by robinrodricks** [comment]
We can support this internally and return a better result : `List<FtpResult>` which will have one object per file along with any error message or success flag. This is easy.

We already have this system for UploadDirectory and DownloadDirectory.

Would this help?

**Comment by Miquel-agp** [comment]
No acabo de entender demasiado bien lo que me propones.
Al metodo DownloadFiles() yo le paso un array  de strings, y este metodo me retorna un entero.
Es muy provable que esté haciendo algo mal, adjunto el codigo que estoy usando por si podéis ayudarme.
Muchissimas gracias de nuevo y feliz año nuevo.
```
        public static async Task DownloadFileAsync(string[]files,ProgressBar pb, string basePath= @"C:\test\ftp")
        {
            var token = new CancellationToken();
            using (var conn = new AsyncFtpClient())
            {
                conn.Host = "localhost";
                conn.Credentials = new NetworkCredential("user", "pass");
          
                await conn.Connect(token);
                Progress<FtpProgress> progress = new Progress<FtpProgress>(p =>
                {
                    if (p.Progress <0)
                    {
                      
                    }
                    else
                    {
                        pb.Value = Convert.ToInt32(p.Progress);
                    }
                });
                var Result = await conn.DownloadFiles(basePath, files, FtpLocalExists.Skip, progress: progress, token: token);
                
                var reply = conn.GetReply;
            }                
        }
```

**Comment by Miquel-agp** [comment]
> We can support this internally and return a better result : `List<FtpResult>` ([docs](https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Model/FtpResult.cs)) which will have one object per file along with any error message or success flag. This is easy.
> 
> We already have this system for UploadDirectory and DownloadDirectory.
> 
> Would this help?

List<FtpResult>  en el metodo DownloadFiles()?
Eso seria fantastico.
126 / 5.000
Resultats de traducció
Resultat de traducció
Ok, now I understand, you mean implement a List<FtpResult> return in the DownloadFiles() method?
That would be fantastic.

**Comment by robinrodricks** [comment]
Can you try this and see if it works?

[FluentFTP.44.0.0-beta1.zip](https://github.com/robinrodricks/FluentFTP/files/10329224/FluentFTP.44.0.0-beta1.zip)

- `UploadFiles` and `DownloadFiles` updated to support rules and return `List<FtpResult>`.

**Comment by Miquel-agp** [comment]
> Can you try this and see if it works?
> 
> [FluentFTP.44.0.0-beta1.zip](https://github.com/robinrodricks/FluentFTP/files/10329224/FluentFTP.44.0.0-beta1.zip)
> 
>     * `UploadFiles` and `DownloadFiles` updated to support rules and return `List<FtpResult>`. (only async)
Thank you very much for everything. I think something isn't working properly or maybe I'm not doing something right. In the attached screenshot, you can see a file that actually doesn't exist:
![imagen](https://user-images.githubusercontent.com/71352066/210183316-3bbe9365-6f40-4d9a-abb6-f8a32cde21e8.png)
However, despite not downloading anything (since the file doesn't exist), it returns a transaction without errors.
![imagen](https://user-images.githubusercontent.com/71352066/210183324-467f50db-cb1f-4a24-800e-ddf5a2e0777d.png)

I apologize for the inconvenience, I hope I'm not doing something wrong. Thank you very much.

**Comment by Miquel-agp** [comment]
From what I can see, in the case that the file doesn't exist, success = false, so we know that the files haven't been downloaded, but we can't know the reason. Despite this, this solution seems great to me. Thank you very much for everything, greetings and happy new year.

**Comment by robinrodricks** [comment]
@Miquel-agp thanks for testing, seems to be a bug. Let me try to fix it.

**Comment by robinrodricks** [comment]
Pls note you have to provide a correct local folder path and a correct remote path to the function, in order to download the file. Can you ensure it is correct? Can you paste your inputs here? Does your file exist on the server?

**Comment by Miquel-agp** [comment]
> Pls note you have to provide a correct local folder path and a correct remote path to the function, in order to download the file. Can you ensure it is correct? Can you paste your inputs here? Does your file exist on the server?

Good morning, I apologize once again for the inconvenience. The modification appears to be functioning correctly, it is just that when a file does not exist on the server, as I show in the previous screenshots, the FtpResult received for this file marks IsFailed = false despite not existing and Exception = null, making it impossible to know the reason why the file has not been downloaded.
It should be noted that isSuccess is False when the file does not exist, so the functionality is correct.
Thank you and I apologize again.

**Comment by robinrodricks** [comment]
> Thank you and I apologize again.

No problem. I will check the code later and let you know a fix.

**Comment by robinrodricks** [comment]
What happens if you call `DownloadFile` and the file does not exist? Is it better than this function `DownloadFiles`?

**Comment by Miquel-agp** [comment]
> What happens if you call `DownloadFile` and the file does not exist? Is it better than this function `DownloadFiles`? Afaik it should throw an exception if the file does not exist.

Hello again, the return value of DownloadFile is of type FtpStatus, so it only provides Failed, Success, or Skipped.
The implementation of FtpResult that you did in DownloadFiles is much more complete, but at least for me, it does not return the reason for the download failure.
Thank you!

**Comment by robinrodricks** [comment]
What happens if you call DownloadFile and the file does not exist?

**Comment by Miquel-agp** [comment]
> What happens if you call DownloadFile and the file does not exist? Please run it and try it...
> 
> > Hello again, the return value of DownloadFile is of type FtpStatus, so it only provides Failed, Success, or Skipped.
> 
> I know.

Return FtpStatus.Failed Enum.
![imagen](https://user-images.githubusercontent.com/71352066/210221424-8fc820c3-630d-405d-be4c-b2fb18f8fd89.png)

**Comment by robinrodricks** [comment]
Ok so right now since `DownloadFiles` is calling `DownloadFile`, the internal behavior is remaining the same.

**Comment by robinrodricks** [comment]
Our current behaviour if it does not exist:

- `DownloadDirectory` - returns blank list
- `DownloadFile` - returns Failed
- `DownloadFiles` - marks Failed 

All our API is not checking if something exists, but you have a point here that `DownloadFiles` and even `DownloadDirectory` should handle exists cases. I'm making a new ticket.

**Comment by robinrodricks** [comment]
https://github.com/robinrodricks/FluentFTP/issues/1121

**Comment by robinrodricks** [comment]
I am working on this, will release it in few days.

**Comment by robinrodricks** [comment]
Released!

https://www.nuget.org/packages/FluentFTP/44.0.0

 - **File Transfer**
   - New: `UploadFiles` API in `AsyncFtpClient` which takes an `IEnumerable<FileInfo>`
   - New: `UploadFiles` and `DownloadFiles` now support rules which allow filtering of uploaded/downloaded files
   - New: `UploadFiles` and `DownloadFiles` now return a `List<FtpResult>` with per-file status rather than just a count
   - New: `FtpMissingObjectException` thrown when trying to download a non-existant object
   - New: Download API `DownloadDirectory`, `DownloadFile`, `DownloadBytes`, `DownloadStream` will throw `FtpMissingObjectException` rather than silently failing
   - New: Download API `DownloadFiles` will mark non-existant files as `IsFailed` and add the `Exception` rather than silently failing

**Comment by Miquel-agp** [comment]
Thanks!!

**Comment by robinrodricks** [comment]
@Miquel-agp thanks for the idea
