### ISSUE TITLE
Support recursive listing/deletes on vsftpd

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#1151]
**FTP Server OS:** Unix
**FTP Server Type:** Vsftpd

Vsftpd sometimes supports recursion if enabled. We should take advantage of this as it would give a major performance boost.

From its [manpage](https://security.appspot.com/vsftpd/vsftpd_conf.html):

- **ls_recurse_enable** - When enabled, this setting will allow the use of "ls -R". This is a minor security risk, because a ls -R at the top level of a large site may consume a lot of resources.
Default: NO

**Comment by FanDjango** [comment]
I moved this to the Future Plans list in the WIki.
