### ISSUE TITLE
How to set different timeout for some FTP commands

### ISSUE THREAD

**Issue by Adhara3** [robinrodricks/FluentFTP#1157]
Hi,

the FTP server I'm communicating with is a custom embedded one. 
It does allow file transfer but also allows custom commands as `STATUS`.

I would like to make commands such as `STATUS` fail as fast as possible, while keeping the file transfer a bit more robust.
Is it correct to say that I should keep `ReadTimeout` small (e.g. 500ms) while increasing `DataReadTimeout` (e.g. 10000) to achieve what I need in a scenario where I share the client for both activities? From the [doc](https://github.com/robinrodricks/FluentFTP/wiki/Timeouts) page it looks like so, I just needed a confirmation.

Or is it better to have two separate clients? And what is the right timeout configuration then?

Thanks a lot
A

**Comment by robinrodricks** [comment]
Just set `Config.ReadTimeout` before calling `Execute` for your `STATUS` command and then set it back to whatever you want. It should work. 

Reason: `stream.ReadLine` is only called in 3 places for Execute, and all of them honor `Config.ReadTimeout`

![image](https://user-images.githubusercontent.com/6797866/213860941-927cc990-0bc7-4edb-9c9c-da8936f8480d.png)

**Comment by Adhara3** [comment]
Ok thanks, but then what `DataReadTimeout` is affecting? Only timeout on the socket opened for upload/download, right?

Cheers
A

**Comment by robinrodricks** [comment]
DataReadTimeout is only affecting active data connections.

**Comment by Adhara3** [comment]
Ah ok, that's interesting. So `PASV` mode is not affected at all by `DataReadTimeout`. Maybe this is something interesting to add in the doc page mentioned above.

Thanks again
A

**Comment by robinrodricks** [comment]
Done

https://github.com/robinrodricks/FluentFTP/wiki/Timeouts#how-to-execute-an-ftp-command-with-a-different-timeout

DataConnectionReadTimeout - Time to wait (in milliseconds) for the server to send data on the Active FTP data channel, before giving up. Does not affect data sent on the control channel or Passive FTP connections. Default: 15000 (15 seconds).
