### ISSUE TITLE
Do not check content of directory, when use directory transfer.

### ISSUE THREAD

**Issue by wlsqkr2** [robinrodricks/FluentFTP#1175]
**FTP Server OS:** **Unix** / Windows / Embedded

**FTP Server Type:** Vsftpd / glFTPd / BFTPd / ProFTPD / Pure-FTPd / IBM CS FTP (z/OS, OS/400) / Windows CE / Windows Server IIS / Vax / VMS / OpenVMS / Tandem / HP NonStop

**Client Computer OS:** **Windows** / Ubuntu / Debian / Linux Mint / Arch Linux

**FluentFTP Version:** 44.0.1

**Framework:** .NET 2 / 3.5 / 4 / **5** / 6 / 7 / 8 / UWP / Xamarin / Mono

<write details about your bug report / feature request here>

When transferring a directory, if the same folder exists, the contents of the folder are not checked.

**Logs :**

```

<paste VERBOSE logs here>

```

**Comment by robinrodricks** [comment]
Can you at least fill in your server type and other variables. You have not even mentioned anything required.

So what other behavior do you want? You want us to recurse into every sub directory and do a deep compare? Did you try Mirror/Update mode?

**Comment by FanDjango** [comment]
I don't understand the **exact** meaning of this sentence: _When transferring a directory, if the same folder exists, the contents of the folder are not checked._

**Comment by robinrodricks** [comment]
Closing, low quality issue.
