### ISSUE TITLE
IBM z/OS  Get JCL job output via FTP

### ISSUE THREAD

**Issue by osmansonmez** [robinrodricks/FluentFTP#1195]
**FTP Server OS:** Unix / Windows / Embedded

**FTP Server Type:** Vsftpd / glFTPd / BFTPd / ProFTPD / Pure-FTPd / IBM CS FTP (z/OS, OS/400) / Windows CE / Windows Server IIS / Vax / VMS / OpenVMS / Tandem / HP NonStop

**Client Computer OS:** Windows / Ubuntu / Debian / Linux Mint / Arch Linux

**FluentFTP Version:** 44.0.0.1

**Framework:** .NET 2 / 3.5 / 4 / 5 / 6 / 7 / 8 / UWP / Xamarin / Mono
.NET 5

We need to get JCL Job result from z/OS
I see a method OpenDataStream and if I send LIST {JobId} I can get Job Result.
I think that  if OpenDataStream can be public method we can use this easily.
 I write method like this. 

    /// <summary>
    /// Executes a command and get a stream
    /// </summary>
    /// <param name="command">The command to execute</param>
    /// <returns>The servers reply to the command</returns>
    public List<string> GetJCLResponse(string JobId)
		{
			List<string> listItems = new List<string>();
			using (var stream = OpenDataStream($"LIST {JobId} ", 0))
			{
				try
				{
					Log(FtpTraceLevel.Verbose, "+---------------------------------------+");
					{
						// GetListing will read file listings line-by-line (actually byte-by-byte)
						string buf;
						while ((buf = stream.ReadLine(Encoding)) != null)
						{
							if (buf.Length > 0)
							{
								listItems.Add(buf);
								Log(FtpTraceLevel.Verbose, "Listing:  " + buf);
							}
						}
					}

					Log(FtpTraceLevel.Verbose, "-----------------------------------------");
				}
				finally
				{
					stream.Close();
				}
			}

			return listItems;

		}

**Logs :**

```

<paste VERBOSE logs here>

```

**Comment by FanDjango** [comment]
Perhaps read this:

https://github.com/robinrodricks/FluentFTP/wiki/IBM-zOS-and-OS-400-Support#accessing-the-jes2-internal-reader-to-submit-batch-jobs-and-how-to-list-and-retrieve-job-output

**Comment by osmansonmez** [comment]
> 

FanGjango Thank you very much for quick response. İt is very helpful for us

**Comment by osmansonmez** [comment]
Thank you. I have closed issue

**Comment by osmansonmez** [comment]
@FanDjango  Thank you for support. I read this article but I think there is a problem about how can i get only one job result. 
This article is not enough for solving problem. Is is very long way for getting only one job result. 
FTP_Sess.GetListing("LIST"...
this function gets all of job results on Z/OS. I want to only one job result. I think it is very easy.  We can change GetListing method  for JCL jobs or Create new  method. If we send command LIST {JobId}  command it gives us like this result. We need to send command after LIST command. 

![image](https://user-images.githubusercontent.com/15195246/218712935-8a95c3ea-c86e-427e-b84c-b943e29cf620.png)

**Comment by FanDjango** [comment]
Looks like a small special function is needed for this. I will think about it and report back.

**Comment by FanDjango** [comment]
Ok, I did it. Works for **any type of system** (you never know if this might be needed for other exotic systems). Works for ACTIVE and PASSIVE data connections. Works for proxy connections. Making OpenDataStream public would not have given us this,

The GitHub at the moment, if you want to use it before it gets merged, is:

[find it here](https://github.com/FanDjango/FluentFTP/tree/GetCommandOutput)

Call it like this:

```cs
List<string> lines = FTP_Sess.GetCommandOutput("LIST JOB00044");
```

Output looks like this:

![image](https://user-images.githubusercontent.com/51046875/218748349-49b16435-7042-4d7f-8e3a-da3e3c73990d.png)

**Comment by osmansonmez** [comment]
> 

@FanDjango  Thank you very much. I have tested and it runs very well. Please merge to master and relase new package. It can be alpha or beta package. We can use it. Thanks again again and again

![image](https://user-images.githubusercontent.com/15195246/218758908-ca7e9c8d-360a-4916-a9b3-47dc556a35d4.png)

**Comment by robinrodricks** [comment]
Released.

https://www.nuget.org/packages/FluentFTP/45.0.0

 - New: `ExecuteMultiline` API to execute an FTP command and return multiline output
 - New: Integration with `FluentFTP.GnuTLS` NuGet package to allow for GnuTLS TLS 1.3 streams

**Comment by robinrodricks** [comment]
Thanks to @FanDjango for this awesome new API!
