### ISSUE TITLE
AsyncFtpClient.CreateDirectory fails on freshly created instance

### ISSUE THREAD

**Issue by MrRickwi** [robinrodricks/FluentFTP#1197]
Fails with NullReferenceException in file Execute.cs line 56:

LogWithPrefix(FtpTraceLevel.Warn, "Reconnect needed due to " + reconnectReason + " control connection (SslSessionLength: " + m_stream.SslSessionLength + ")");

m_stream is null for some reason. If a file has been uploaded before on the same instance of AsyncFtpClient, everything is working because the AsyncFtpClient is connected.

Replacing m_stream.SslSessionLength by m_stream?.SslSessionLength fixes the problem and the directory is properly created.

**Comment by FanDjango** [comment]
Good catch. I will fix that. Sadly, we have just had a release :-)

> m_stream is null for some reason.

Any idea why it is null? If we are connected, of course the Log... doesn't get executed and there is no failure. I will try to reproduce.

> ... and the directory is properly created

... thanks to the reconnect.

**Comment by MrRickwi** [comment]
Is there a way to connect the AsyncFtpClient? So that the reconnect is not triggered? And why does uploading a file not fail, in principle it should do the same reconnect?

**Comment by MrRickwi** [comment]
I see... Connect(), we already use it, but not in all places. Will fix that on our side, too.

**Comment by FanDjango** [comment]
Yeah, without your code I cannot really see... We fixed a reconnect happening if there was never a real connect. But you don't say what version you are using, so I can't see. If I had a log, I would see. But, sigh,....

**Comment by MrRickwi** [comment]
We are using 45.0.1, and a unit test which creates a directory fails, just because we forgot to call Connect() before using the AsyncFtpClient in that case. In 43.0.1 we used before it did not fail. We fixed the test on our side, nevertheless the reconnect should not fail in logging. Thanks for your quick response!

**Comment by FanDjango** [comment]
All is good. But that version **should** not reconnect, **if there was no** regular connect before that. At least I think that should be the case. Please confirm that: Never been connectect and do some API function, it should not "re-"connect. It can't, well, it shouldn't, important stuff would be missing that can only come from a regulare connect.

**Comment by FanDjango** [comment]
> In 43.0.1 we used before it did not fail

You mean one of **yyour** unit tests?

Hmmm. I certainly would like to identify that regression.

**Comment by FanDjango** [comment]
Ah, I have found it. There was no such log message, therfore no failure.

**Comment by FanDjango** [comment]
Anyway, 'twill be fixed...

**Comment by FanDjango** [comment]
I have checked what happens when a reconnect is triggered without you ever having been connected:

```cs
				// If we have never been connected before...
				if (reConnect && Status.ConnectCount == 0) {
					reConnect = false;
					LogWithPrefix(FtpTraceLevel.Warn, "Cannot reconnect, reverting to full connect");
				}
```
It turns into a regular connect. Works, if the client has been set up with hostname, user,........ etc.

**Comment by FanDjango** [comment]
@MrRickwi I suppose we can close this?

**Comment by MrRickwi** [comment]
Yes, we can close this. Thanks!

Von: FanDjango ***@***.***>
Gesendet: Sonntag, 19. Februar 2023 12:22
An: robinrodricks/FluentFTP ***@***.***>
Cc: Ricken, Wilfried [RTL Tech] ***@***.***>; Mention ***@***.***>
Betreff: Re: [robinrodricks/FluentFTP] AsyncFtpClient.CreateDirectory fails on freshly created instance (Issue #1197)


@MrRickwi<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMrRickwi&data=05%7C01%7C%7Cb90f714440a04ac571bc08db126b84d8%7Cefce8346592b4b6eb1c20fd07bd5e442%7C0%7C0%7C638124025224955408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CtsD3qLbL2CQRsD5%2FROdwjmi7tgXUSLnrZ6ylsRAS94%3D&reserved=0> I suppose we can close this?

-
