### ISSUE TITLE
Control connection hang after data connection close, .NET 6 OSX & Linux to dockerized Pure-FTPd

### ISSUE THREAD

**Issue by maxrunsoftware** [robinrodricks/FluentFTP#1203]
**FTP Server OS:** Unix (docker)

**FTP Server Type:** Pure-FTPd

**Client Computer OS:** OSX

**FluentFTP Version:** 45.0.4 (NuGet)

**Framework:** .NET 6

Issue initially reported later in [Issue-1156](https://github.com/robinrodricks/FluentFTP/issues/1156#issuecomment-1435413341)
GetListing hangs. Reproduction steps below.

**Logs :**
```
[Info] >         Connect(False)
[Verbose] FluentFTP 45.0.4.0
[Info] Connecting to IP #1= 172.16.46.16:2121
[Verbose] Waiting for a response
[Verbose] Response: 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response: 220-You are user number 1 of 50 allowed.
Response: 220-Local time is now 00:05. Server port: 21.
Response: 220-This is a private system - No anonymous login
Response: 220-IPv6 connections are also welcome on this server.
[Info] Response: 220 You will be disconnected after 15 minutes of inactivity. [738568.004d]
[Info] Status:   Detected FTP server: PureFTPd
[Info] Command:  AUTH TLS
[Verbose] Waiting for response to: AUTH TLS
[Info] Response: 234 AUTH TLS OK. [10ms]
[Info] FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes128, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, DiffieHellman, 0) [290ms]
[Info] Command:  USER testuser
[Verbose] Waiting for response to: USER testuser
[Info] Response: 331 User testuser OK. Password required [1ms]
[Info] Command:  PASS ***
[Verbose] Waiting for response to: PASS ***
[Info] Response: 230 OK. Current directory is / [12ms]
[Info] Command:  PBSZ 0
[Verbose] Waiting for response to: PBSZ 0
[Info] Response: 200 PBSZ=0 [1ms]
[Info] Command:  PROT P
[Verbose] Waiting for response to: PROT P
[Info] Response: 200 Data protection level set to "private" [8ms]
[Info] Command:  FEAT
[Verbose] Waiting for response to: FEAT
[Verbose] Response: 211-Extensions supported:
Response: EPRT
Response: IDLE
Response: MDTM
Response: SIZE
Response: MFMT
Response: REST STREAM
Response: MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
Response: MLSD
Response: AUTH TLS
Response: PBSZ
Response: PROT
Response: UTF8
Response: TVFS
Response: ESTA
Response: PASV
Response: EPSV
Response: SPSV
[Info] Response: 211 End. [9ms]
[Info] Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
[Info] Command:  OPTS UTF8 ON
[Verbose] Waiting for response to: OPTS UTF8 ON
[Info] Response: 200 OK, UTF-8 enabled [1ms]
[Info] Command:  SYST
[Verbose] Waiting for response to: SYST
[Info] Response: 215 UNIX Type: L8 [2ms]
[Verbose] Listing parser set to: Machine
[Info] Command:  PWD
[Verbose] Waiting for response to: PWD
[Info] Response: 257 "/" is your current location [5ms]
[Info] >         GetListing(null, Auto)
[Info] Command:  TYPE I
[Verbose] Waiting for response to: TYPE I
[Info] Response: 200 TYPE is now 8-bit binary [<1ms]
[Info] >         OpenDataStream("MLSD /", 0)
[Info] >         OpenPassiveDataStream(AutoPassive, "MLSD /", 0)
[Info] Command:  EPSV
[Verbose] Waiting for response to: EPSV
[Info] Response: 229 Extended Passive mode OK (|||21223|) [6ms]
[Info] Connecting to IP #1= 172.16.46.16:21223
[Info] Command:  MLSD /
[Verbose] Waiting for response to: MLSD /
[Info] Response: 150 Accepted data connection [3ms]
[Info] FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes128, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, DiffieHellman, 0) [28ms]
[Verbose] +---------------------------------------+
[Verbose] -----------------------------------------
[Verbose] Closing/Disposing FtpSocketStream(data connection)
[Info] >         CloseDataStream()
[Verbose] Waiting for a response
<...hangs...>
```
  
**Test Code:**
```
using FluentFTP;

public class Program
{
    private class FtpClientLogger : IFtpLogger
    {
        public void Log(FtpLogEntry entry)
        {
            Console.WriteLine($"[{entry.Severity}] {entry.Message}");
            if (entry.Exception != null) Console.WriteLine(entry.Exception);
        }
    }

    public static void Main(string[] args)
    {
        var client = new FtpClient(
            host: "172.16.46.16",
            port: 2121,
            user: "testuser",
            pass: "testPass1!",
            logger: new FtpClientLogger(),
            config: new FtpConfig
            {
                LogHost = true,
                LogUserName = true,
                LogPassword = false,
                DataConnectionReadTimeout = 1000 * 30,
                EncryptionMode = FtpEncryptionMode.Auto,
                SslBuffering = FtpsBuffering.Off,
                ValidateAnyCertificate = true,
                ConnectTimeout = 1000 * 30,
                ReadTimeout = 1000 * 30,
            }
        );

        client.Connect();

        var items = client.GetListing() ?? Array.Empty<FtpListItem>();
        Console.WriteLine($"Found {items.Length} items");
    }
}
```

**docker-compose.yaml**
```
version: "3.5"
services:
  ftps:
    container_name: ftps
    image: stilliard/pure-ftpd:latest
    restart: unless-stopped
    ports:
      - "2121:21"
      - "21200-21299:21200-21299"
    environment:
      PUBLICHOST: "172.16.46.16"
      FTP_USER_NAME: testuser
      FTP_USER_PASS: testPass1!
      FTP_USER_HOME: /home/testuser
      FTP_PASSIVE_PORTS: 21200:21299
      FTP_MAX_CLIENTS: 50
      FTP_MAX_CONNECTIONS: 50
      ADDED_FLAGS: "--tls=2 -d -d"
      TLS_USE_DSAPRAM: "true"
      TLS_CN: "localhost"
      TLS_ORG: "Test"
      TLS_C: "US"
```

**Comment by maxrunsoftware** [comment]
Issue is not present on Windows 2019 Server as client with 45.0.4 (NuGet)

Log...
```
     7 [Info]    >         Connect(False)
    23 [Verbose] FluentFTP 45.0.4.0
    39 [Info]    Connecting to IP #1= 172.16.46.16:2121
    67 [Verbose] Waiting for a response
   109 [Verbose] Response: 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response: 220-You are user number 2 of 50 allowed.
Response: 220-Local time is now 04:52. Server port: 21.
Response: 220-This is a private system - No anonymous login
Response: 220-IPv6 connections are also welcome on this server.
   109 [Info]    Response: 220 You will be disconnected after 15 minutes of inactivity. [738569.203d]
   114 [Info]    Status:   Detected FTP server: PureFTPd
   116 [Info]    Command:  AUTH TLS
   117 [Verbose] Waiting for response to: AUTH TLS
   118 [Info]    Response: 234 AUTH TLS OK. [1ms]
   191 [Info]    FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes128, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, 44550, 256) [70ms]
   192 [Info]    Command:  USER testuser
   194 [Verbose] Waiting for response to: USER testuser
   195 [Info]    Response: 331 User testuser OK. Password required [1ms]
   196 [Info]    Command:  PASS ***
   196 [Verbose] Waiting for response to: PASS ***
   216 [Info]    Response: 230 OK. Current directory is / [20ms]
   220 [Info]    Command:  PBSZ 0
   229 [Verbose] Waiting for response to: PBSZ 0
   232 [Info]    Response: 200 PBSZ=0 [2ms]
   234 [Info]    Command:  PROT P
   236 [Verbose] Waiting for response to: PROT P
   244 [Info]    Response: 200 Data protection level set to "private" [7ms]
   246 [Info]    Command:  FEAT
   246 [Verbose] Waiting for response to: FEAT
   248 [Verbose] Response: 211-Extensions supported:
Response: EPRT
Response: IDLE
Response: MDTM
Response: SIZE
Response: MFMT
Response: REST STREAM
Response: MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
Response: MLSD
Response: AUTH TLS
Response: PBSZ
Response: PROT
Response: UTF8
Response: TVFS
Response: ESTA
Response: PASV
Response: EPSV
Response: SPSV
   248 [Info]    Response: 211 End. [2ms]
   264 [Info]    Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
   264 [Info]    Command:  OPTS UTF8 ON
   265 [Verbose] Waiting for response to: OPTS UTF8 ON
   266 [Info]    Response: 200 OK, UTF-8 enabled [1ms]
   266 [Info]    Command:  SYST
   266 [Verbose] Waiting for response to: SYST
   267 [Info]    Response: 215 UNIX Type: L8 [<1ms]
   270 [Verbose] Listing parser set to: Machine
   270 [Info]    Command:  PWD
   270 [Verbose] Waiting for response to: PWD
   272 [Info]    Response: 257 "/" is your current location [1ms]
   279 [Info]    >         GetListing(null, Auto)
   284 [Info]    Command:  TYPE I
   284 [Verbose] Waiting for response to: TYPE I
   287 [Info]    Response: 200 TYPE is now 8-bit binary [2ms]
   288 [Info]    >         OpenDataStream("MLSD /", 0)
   322 [Info]    >         OpenPassiveDataStream(AutoPassive, "MLSD /", 0)
   322 [Info]    Command:  EPSV
   322 [Verbose] Waiting for response to: EPSV
   323 [Info]    Response: 229 Extended Passive mode OK (|||21279|) [1ms]
   327 [Info]    Connecting to IP #1= 172.16.46.16:21279
   328 [Info]    Command:  MLSD /
   329 [Verbose] Waiting for response to: MLSD /
   331 [Info]    Response: 150 Accepted data connection [2ms]
   336 [Info]    FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes128, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, 44550, 256) [4ms]
   336 [Verbose] +---------------------------------------+
   338 [Verbose] Listing:  type=cdir;sizd=4096;modify=20230219045151;UNIX.mode=0755;UNIX.uid=1000;UNIX.gid=0;unique=2bg29d49; .
   339 [Verbose] Listing:  type=pdir;sizd=4096;modify=20230219045151;UNIX.mode=0755;UNIX.uid=1000;UNIX.gid=0;unique=2bg29d49; ..
   339 [Verbose] Listing:  type=dir;sizd=4096;modify=20230219045136;UNIX.mode=0755;UNIX.uid=1000;UNIX.gid=1000;unique=2bg29d4f; TestDirectory
   339 [Verbose] Listing:  type=file;size=0;modify=20230219045145;UNIX.mode=0644;UNIX.uid=1000;UNIX.gid=1000;unique=2bg28c36; TestFile.txt
   347 [Verbose] -----------------------------------------
   347 [Verbose] Closing/Disposing FtpSocketStream(data connection)
   349 [Info]    >         CloseDataStream()
   350 [Verbose] Waiting for a response
   351 [Verbose] Response: 226-Options: -a -l
   351 [Info]    Response: 226 4 matches total [22ms]
   351 [Verbose] Closing/Disposing FtpSocketStream(data connection)
Found 2 items
```
[FluentFtpTesting.20230218_235400.Win2019.VsCode.zip](https://github.com/robinrodricks/FluentFTP/files/10775988/FluentFtpTesting.20230218_235400.Win2019.VsCode.zip)

**Comment by maxrunsoftware** [comment]
Issue IS present on OSX 13.2.1 as client
Logs...
```
     5 [Info]    >         Connect(False)
    28 [Verbose] FluentFTP 45.0.4.0
    76 [Info]    Connecting to IP #1= 172.16.46.16:2121
    93 [Verbose] Waiting for a response
   144 [Verbose] Response: 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response: 220-You are user number 2 of 50 allowed.
Response: 220-Local time is now 05:00. Server port: 21.
Response: 220-This is a private system - No anonymous login
Response: 220-IPv6 connections are also welcome on this server.
   145 [Info]    Response: 220 You will be disconnected after 15 minutes of inactivity. [738569.208d]
   154 [Info]    Status:   Detected FTP server: PureFTPd
   156 [Info]    Command:  AUTH TLS
   158 [Verbose] Waiting for response to: AUTH TLS
   161 [Info]    Response: 234 AUTH TLS OK. [3ms]
   292 [Info]    FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes128, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, DiffieHellman, 0) [128ms]
   293 [Info]    Command:  USER testuser
   295 [Verbose] Waiting for response to: USER testuser
   297 [Info]    Response: 331 User testuser OK. Password required [1ms]
   297 [Info]    Command:  PASS ***
   297 [Verbose] Waiting for response to: PASS ***
   313 [Info]    Response: 230 OK. Current directory is / [15ms]
   316 [Info]    Command:  PBSZ 0
   316 [Verbose] Waiting for response to: PBSZ 0
   319 [Info]    Response: 200 PBSZ=0 [2ms]
   319 [Info]    Command:  PROT P
   319 [Verbose] Waiting for response to: PROT P
   320 [Info]    Response: 200 Data protection level set to "private" [<1ms]
   320 [Info]    Command:  FEAT
   321 [Verbose] Waiting for response to: FEAT
   323 [Verbose] Response: 211-Extensions supported:
Response: EPRT
Response: IDLE
Response: MDTM
Response: SIZE
Response: MFMT
Response: REST STREAM
Response: MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
Response: MLSD
Response: AUTH TLS
Response: PBSZ
Response: PROT
Response: UTF8
Response: TVFS
Response: ESTA
Response: PASV
Response: EPSV
Response: SPSV
   323 [Info]    Response: 211 End. [2ms]
   353 [Info]    Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
   353 [Info]    Command:  OPTS UTF8 ON
   353 [Verbose] Waiting for response to: OPTS UTF8 ON
   354 [Info]    Response: 200 OK, UTF-8 enabled [1ms]
   354 [Info]    Command:  SYST
   354 [Verbose] Waiting for response to: SYST
   356 [Info]    Response: 215 UNIX Type: L8 [1ms]
   360 [Verbose] Listing parser set to: Machine
   361 [Info]    Command:  PWD
   361 [Verbose] Waiting for response to: PWD
   362 [Info]    Response: 257 "/" is your current location [1ms]
   376 [Info]    >         GetListing(null, Auto)
   383 [Info]    Command:  TYPE I
   383 [Verbose] Waiting for response to: TYPE I
   385 [Info]    Response: 200 TYPE is now 8-bit binary [2ms]
   386 [Info]    >         OpenDataStream("MLSD /", 0)
   392 [Info]    >         OpenPassiveDataStream(AutoPassive, "MLSD /", 0)
   392 [Info]    Command:  EPSV
   392 [Verbose] Waiting for response to: EPSV
   394 [Info]    Response: 229 Extended Passive mode OK (|||21275|) [2ms]
   401 [Info]    Connecting to IP #1= 172.16.46.16:21275
   403 [Info]    Command:  MLSD /
   403 [Verbose] Waiting for response to: MLSD /
   404 [Info]    Response: 150 Accepted data connection [1ms]
   417 [Info]    FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes128, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, DiffieHellman, 0) [13ms]
   417 [Verbose] +---------------------------------------+
   420 [Verbose] -----------------------------------------
   420 [Verbose] Closing/Disposing FtpSocketStream(data connection)
   427 [Info]    >         CloseDataStream()
   427 [Verbose] Waiting for a response

<...hangs...>
```

[FluentFtpTesting.20230218_233300.OSX_13_3_2.Rider.zip](https://github.com/robinrodricks/FluentFTP/files/10775994/FluentFtpTesting.20230218_233300.OSX_13_3_2.Rider.zip)

**Comment by maxrunsoftware** [comment]
Both logs above (Win+OSX) had the same directory structure...
```
/.
/..
/TestDirectory
/TestFile.txt
```
Interesting that the Windows (338-339) had a listing response but the OSX (417-420) did not.
Docker Pure-FTPd instance is not production and is only used for Unit Testing FTP code.
I just spun of the docker-compose, used FileZilla to create the TestDirectory and TestFile.txt, then ran the C# test code against it. 

If you need any more info, just let me know.

**Comment by maxrunsoftware** [comment]
Issue IS present with client on Linux (Debian) the same as OSX
```
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.0-18-amd64
      Architecture: x86-64
```

```
root@devdebian:~/FluentFtpTesting# dotnet run FluentFtpTesting.sln 
     5 [Info]    >         Connect(False)
    25 [Verbose] FluentFTP 45.0.4.0
    39 [Info]    Connecting to IP #1= 172.16.46.16:2121
    76 [Verbose] Waiting for a response
   113 [Verbose] Response: 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response: 220-You are user number 1 of 50 allowed.
Response: 220-Local time is now 05:33. Server port: 21.
Response: 220-This is a private system - No anonymous login
Response: 220-IPv6 connections are also welcome on this server.
   114 [Info]    Response: 220 You will be disconnected after 15 minutes of inactivity. [738569.232d]
   118 [Info]    Status:   Detected FTP server: PureFTPd
   119 [Info]    Command:  AUTH TLS
   121 [Verbose] Waiting for response to: AUTH TLS
   122 [Info]    Response: 234 AUTH TLS OK. [1ms]
   229 [Info]    FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (None, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, DiffieHellman, 0) [104ms]
   230 [Info]    Command:  USER testuser
   231 [Verbose] Waiting for response to: USER testuser
   234 [Info]    Response: 331 User testuser OK. Password required [3ms]
   235 [Info]    Command:  PASS ***
   235 [Verbose] Waiting for response to: PASS ***
   241 [Info]    Response: 230 OK. Current directory is / [5ms]
   243 [Info]    Command:  PBSZ 0
   243 [Verbose] Waiting for response to: PBSZ 0
   244 [Info]    Response: 200 PBSZ=0 [<1ms]
   244 [Info]    Command:  PROT P
   244 [Verbose] Waiting for response to: PROT P
   245 [Info]    Response: 200 Data protection level set to "private" [<1ms]
   246 [Info]    Command:  FEAT
   246 [Verbose] Waiting for response to: FEAT
   248 [Verbose] Response: 211-Extensions supported:
Response: EPRT
Response: IDLE
Response: MDTM
Response: SIZE
Response: MFMT
Response: REST STREAM
Response: MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
Response: MLSD
Response: AUTH TLS
Response: PBSZ
Response: PROT
Response: UTF8
Response: TVFS
Response: ESTA
Response: PASV
Response: EPSV
Response: SPSV
   248 [Info]    Response: 211 End. [1ms]
   273 [Info]    Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
   273 [Info]    Command:  OPTS UTF8 ON
   273 [Verbose] Waiting for response to: OPTS UTF8 ON
   274 [Info]    Response: 200 OK, UTF-8 enabled [1ms]
   274 [Info]    Command:  SYST
   274 [Verbose] Waiting for response to: SYST
   275 [Info]    Response: 215 UNIX Type: L8 [<1ms]
   278 [Verbose] Listing parser set to: Machine
   279 [Info]    Command:  PWD
   279 [Verbose] Waiting for response to: PWD
   281 [Info]    Response: 257 "/" is your current location [1ms]
   287 [Info]    >         GetListing(null, Auto)
   291 [Info]    Command:  TYPE I
   291 [Verbose] Waiting for response to: TYPE I
   292 [Info]    Response: 200 TYPE is now 8-bit binary [<1ms]
   293 [Info]    >         OpenDataStream("MLSD /", 0)
   298 [Info]    >         OpenPassiveDataStream(AutoPassive, "MLSD /", 0)
   298 [Info]    Command:  EPSV
   298 [Verbose] Waiting for response to: EPSV
   299 [Info]    Response: 229 Extended Passive mode OK (|||21251|) [1ms]
   303 [Info]    Connecting to IP #1= 172.16.46.16:21251
   306 [Info]    Command:  MLSD /
   306 [Verbose] Waiting for response to: MLSD /
   308 [Info]    Response: 150 Accepted data connection [1ms]
   316 [Info]    FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (None, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, DiffieHellman, 0) [7ms]
   316 [Verbose] +---------------------------------------+
   318 [Verbose] -----------------------------------------
   319 [Verbose] Closing/Disposing FtpSocketStream(data connection)
   327 [Info]    >         CloseDataStream()
   327 [Verbose] Waiting for a response

<...hangs...>
```

DotNet Version
```
root@devdebian:~/FluentFtpTesting# dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.406
 Commit:    2988897946

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.406/

global.json file:
  /root/FluentFtpTesting/global.json

Host:
  Version:      6.0.14
  Architecture: x64
  Commit:       2a90daa2cc

.NET SDKs installed:
  6.0.406 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

```

**Comment by FanDjango** [comment]
Ok. We are getting somewhere, slowly.

Let me try to sum this up:

1. Server is Pure-FTP in a docker container, **same one for all tests**.

2. OSX client and Linux client, both .NET 6, hang on GetListing.

3. Windows .NET 6, GetListing works.

4. This is tested with NuGet FluentFTP 45.0.4

Using OSX for the next steps:

GetListing uses a data connection. Could you manually upload a file into one of the server directories and program a download of that file, not a getlisting. It should also fail in some manner, I think.

Try using the new branch I made for you and confirm that it times out instead of hanging.

Do you have an alternate server you could dockerize (perhaps take one from FluentFTP, like the proftpd one) and run against that? Should also time out, perhaps.

**Comment by maxrunsoftware** [comment]
Will do, I'll try these later today. Do you prefer I just upload a zip of my results (logs and test code for each platform) or put the raw logs as a message for each platform?
For the alternate server, do you happen to have a docker-compose.yaml handy that you use? If not, no problem I can find one/build one but figured if you already had one you use to test against I would just use that.
The docker environment is not production either and is simply used for unit tests, so I can deploy whatever if you have something else specific you want me to test with.

**Comment by FanDjango** [comment]
> GetListing uses a data connection. Could you manually upload a file into one of the server directories and program a download of that file, not a getlisting. It should also fail in some manner, I think.

Just the last lines of the log showing the download

> Try using the new branch I made for you and confirm that it times out instead of hanging.

Same, just want to see how the hang times out, give it 35 seconds or enough to be sure

> alternate server

Least priority for now. Lets see the first two before you need to do anything strenuous.

**Comment by maxrunsoftware** [comment]
Tested using branch. Now I get timeout on Linux+OSX after 30 seconds. Also get another timeout on Dispose after another 30 seconds. Both GetListing and UploadFile commands timeout. Attached logs for OSX/Win/Linux for both tests and (updated) test code with branch DLL.

At first I thought this was some type of networking issue with the docker box and Passive connection, but FileZilla seems to work from OSX, so I don't think it is. Also, the Linux box I'm testing from IS the server running docker, so probably not a network issue.

[FluentFtp_Issue1203_Code.zip](https://github.com/robinrodricks/FluentFTP/files/10782226/FluentFtp_Issue1203_Code.zip)
[FluentFtp_Issue1203_Logs.zip](https://github.com/robinrodricks/FluentFTP/files/10782227/FluentFtp_Issue1203_Logs.zip)

**Comment by FanDjango** [comment]
Just a short question: Did this ever work at all under OSX/Linux in this setup? I mean, if we had a very bad problem like this with linux getlisting and file transfer (under .NET 6 in general), for example, we would have had reports?

To clarify, this setup is OSX or Linux client accessing this specific docker server. Can you try accessing some other server, not necessarily under docker, regardless of server type but using OSX or linux, of course?

**Comment by FanDjango** [comment]
> Also get another timeout on Dispose after another 30 seconds. Both GetListing and UploadFile commands timeout.

That's because of your source code: You have IDisposable for your test program run and after catching the failure and actual termination, you then call dispose, which notices we have still got an ongoing (albeit dead) control connection and tries to enter the "QUIT" command (and wait for the reply) which then goes into the next 30 second timeout wait.

Let's concentrate on the first 30 second "silence", waiting for a reply to the MLSD...

**Comment by maxrunsoftware** [comment]
I agree, if this was an "actual" issue, you would have gotten way more reports of it. I have used your library for years connecting to various systems in production environments, but I'm doing a program rewrite and decided to setup an actual Unit Test docker instance for the unit tests and that is when I noticed the issue.
Since this seems to be affecting just me, this is a very low priority issue, and does not affect anything I use for production anyways.
I'll try and track down what is going on, and let you know what I find. I really appreciate all of the help and quick responses!
If possible could you keep this issue open until I determine the cause, and just tag it as low priority? I'm working on testing via your Docker test suite and see what I can find out. 
Not sure if you did, but could you merge the timeout branch code to main? I could see it being helpful in general.

Thanks again for all of your help with everything, and I'll let you know what I find out. Sorry for all of the trouble, I was hoping it was something obvious.

**Comment by FanDjango** [comment]
Ok, standing by.

Merging the timeout branch is planned, I want to test it some more.

**Comment by maxrunsoftware** [comment]
Awesome, thank you! Quick question, for your unit/integration tests, are you using a Windows box as the client to test the FluentFTP lib against the docker instances? If so, do you know if anyone else has been able to run the unit/integration test suite successfully with a recent FluentFTP version with a non-windows client?

**Comment by FanDjango** [comment]
You are right - in my case it is a Win 10 PC hosting both the docker(s) and running the VS code in the Test Explorer

To the second question: No. Sorry.

**Comment by maxrunsoftware** [comment]
> > Also get another timeout on Dispose after another 30 seconds. Both GetListing and UploadFile commands timeout.
> 
> That's because of your source code: You have IDisposable for your test program run and after catching the failure and actual termination, you then call dispose, which notices we have still got an ongoing (albeit dead) control connection and tries to enter the "QUIT" command (and wait for the reply) which then goes into the next 30 second timeout wait.

So am I not doing the code/dispose pattern correctly in the test or was your response just an "FYI this is why you are seeing that second exception in the log"? Your explanation makes sense why I am seeing it (tries to QUIT on a dead control connection), but I just want to be sure you were not inferring that I'm using the client obj incorrectly, and if I am what the correct use/dispose pattern should be.

**Comment by FanDjango** [comment]
It is FYI...

A FluentFTP client should "survive" a dispose without undue difficulties.

Actually I have made a note for myself: The control connection is **dead** (I mean, it does not **react**). But the check for socket connectivity is **not** reporting anything abnormal, it is _connected_ still. Which is true? untrue? From whose standpoint? It is a very unclean situation. So there is no real way to decide: Do we do the "QUIT" command or do we skip it? This decision is currently made on the determination of "connected".

To systematically find out more, one would want to look at all logs, one would want to run a wireshark on both sides, maybe add debugging writeln's to the low level stream code etc.

**Comment by FanDjango** [comment]
Perhaps a socket.poll should be forced when testing for 'connected'. Let me think about that - I am happy to have a possible tester in your issue.

**Comment by FanDjango** [comment]
When testimg the Upload, did you actually check to see if the files was created on the server and contained the right data?

```
66 [Info]    FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (None, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, DiffieHellman, 0) [4ms]
     68 [Verbose] Uploaded 29 bytes
     68 [Verbose] Closing/Disposing FtpSocketStream(data connection)
     69 [Verbose] Waiting for response to: *UPLOAD*
```

**Comment by maxrunsoftware** [comment]
OK, so ready for some fun?

After some quick testing here is what I have found. Test code works with FileZilla server (Windows) and vsftpd (docker) but fails with PureFTPd (docker). This leads me to believe something isn't setup correctly with my PureFTPd docker instance, except... I can connect to it from the same computer (OSX) via FileZilla Client. This makes me think that FluentFTP isn't handling something special with how the PureFTPd server is communicating... but when running FluentFTP on a Windows client, it works. 

So far the issue seems to be the original issue in the title. FluentFTP works with 2 other server types I've tested (FileZilla Server + vsFTPd) but fails with PureFTPd, but only on OSX/Linux.

Thoughts? 

```
OSX (FileZilla Client) -> PureFTPd (docker) = success

OSX (FluentFTP) -> PureFTPd (docker) = fail
Linux (FluentFTP)-> PureFTPd (docker) = fail
Windows (FluentFTP) -> PureFTPd (docker) = success

OSX (FluentFTP) -> FileZilla Server (windows) = success
Linux (FluentFTP) -> FileZilla Server (windows) = success
Windows (FluentFTP) -> FileZilla Server (windows) = success

OSX (FluentFTP) -> vsFTPd (docker) = success
Linux (FluentFTP) -> vsFTPd (docker) = success
Windows (FluentFTP) -> vsFTPd (docker) = success
```

**Comment by maxrunsoftware** [comment]
> When testing the Upload, did you actually check to see if the files was created on the server and contained the right data?

The file was created but it was a zero byte file (no contents)

**Comment by FanDjango** [comment]
> This makes me think that FluentFTP isn't handling something special with how the PureFTPd server is communicating

Oh, until we know the exact reason, I hesitate to embrace premature conclusions.

As far as I know (but I am not sure), the low level functionality for SslStream is of course not provided by SChannel, but by a different component.

Regardless, if we want to get to the bottom of this afer your **very** good and exhaustive checks, we need something that gives us the following information:

0. Do we have a PureFTPd log, detailed of what is happening.
1. Is the control connection truly "dead"? Has it been terminated in terms of IP / TCP ? By whom? Have there been TLS Alerts?
2. On the FluentFTP side, could we add some debugging code to find out the exact state of the socket? of the encrypted connection?
3. Can you perhaps try the FluentFTP.GnuTLS option if you have time?

Can you check #0 ?

#1:
Can you run wireshark, on the client side?
Can you run you wireshark on the server side?<-- obviously not, docker, headless.

I will think about #2.

**Comment by FanDjango** [comment]
For #1/#2 I could envision a test branch, that will **ignore** the missing response on the control connection and issue a command instead, to see if it will at least answer to that... just to see what is the state of the control connection.

But, we did see that the QUIT command didn't get a response, so that idea is stupid of me. How nice it would be to see a PureFTPd log to see if the QUIT command ever arrived at the destination.

The STOR or MLSD command **did** arrive at PureFTPd, otherwise it would not have opened a data connection. After that everything goes wrong.

I see you using EPSV. There is some danger in that, when using Network bridging or whatever you are using to connect the networks to the docker container. To make sure this is not hurting, **you should test by forcing PASV** or even ACTIVE mode as a alternative test.

**Comment by FanDjango** [comment]
And forgive me if this sounds bad, but if at all possible a check to see if **not using** encryption works? As I understand it, you have full control over the PureFTPd docker configuration, so you could test that.

**Comment by FanDjango** [comment]
@maxrunsoftware The new branch has been merged into master. It will be in the next release.

Let us again note that this fixes the "infinite hangup" when connecting  - it now times out correctly.

**It does not clear up the issue of why the connect is failing**

**Comment by FanDjango** [comment]
Released

https://www.nuget.org/packages/FluentFTP/45.2.0

**Comment by robinrodricks** [comment]
Closing since seemingly fixed. If OP says its not fixed, we can reopen.
