### ISSUE TITLE
Any EncryptionMode in FluentFTP?

### ISSUE THREAD

**Issue by jt4000** [robinrodricks/FluentFTP#1204]
**Client Computer OS:** Windows

**FluentFTP Version:** 45.0.4

**Framework:** .NET 6

I need to apply encryption mode in FluentFTP's ftp.

The syntax "EncryptionMode" don't exist in .net 6.

```
var conn = new FtpClient();
conn.EncryptionMode = FtpEncryptionMode.Explicit;
```

![bbb2](https://user-images.githubusercontent.com/14993569/219936090-2e0aaee4-ef89-47e3-a466-aeb2918ca223.png)

How should I apply EncryptionMode in FluentFTP's ftp in .net6?

Thank you?

**Comment by robinrodricks** [comment]
Config.EncryptionMode

https://github.com/robinrodricks/FluentFTP/wiki/FTP-Connection#how-do-i-connect-with-ssltls--how-do-i-use-ftps
