### ISSUE TITLE
 Can't connect to server via proxy when using EPSV mode for data connection

### ISSUE THREAD

**Issue by zubo100** [robinrodricks/FluentFTP#1205]
**FTP Server OS:** Unix

**FTP Server Type:** Vsftpd / glFTPd / BFTPd / ProFTPD / Pure-FTPd / IBM CS FTP (z/OS, OS/400) / Windows CE / Windows Server IIS / Vax / VMS / OpenVMS / Tandem / HP NonStop

**Client Computer OS:** Windows 

**FluentFTP Version:** 45.1.0

**Framework:** .NET 2 / 6

GetListing, Upload or Download from the server using EPSV over HTTP Proxy. 

**Logs :**

```
HTTP/1.0 200 Connection established

Status:   Waiting for a response
Response: 220 FTP Server 1.0
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 234 AUTH TLS successful
Warning:  SSL Buffering force disabled, is .NET 5.0 and later
Status:   FTPS authentication successful, protocol = Tls12
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0,2593455.
Status:   SslStream: Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 44550, 255)
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Password required for ***
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230 User *** logged in
Command:  PBSZ 0
Status:   Waiting for response to: PBSZ 0
Response: 200 PBSZ 0 successful
Command:  PROT P
Status:   Waiting for response to: PROT P
Response: 200 Protection set to Private
Command:  FEAT
Status:   Waiting for response to: FEAT
Response: 211-Features:
Response: AUTH TLS
Response: CCC
Response: CLNT
Response: EPRT
Response: EPSV
Response: HOST
Response: LANG en-US.UTF-8*;en-US
Response: MDTM
Response: MFF modify;UNIX.group;UNIX.mode;
Response: MFMT
Response: MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.groupname*;UNIX.mode*;UNIX.owner*;UNIX.ownername*;
Response: PBSZ
Response: PROT
Response: RANG STREAM
Response: REST STREAM
Response: SIZE
Response: SSCN
Response: TVFS
Response: UTF8
Response: 211 End
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Status:   Waiting for response to: OPTS UTF8 ON
Response: 200 UTF8 set to on
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 UNIX Type: L8
Status:   Listing parser set to: Machine
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/" is the current directory

# GetListing("/", Auto)
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Type set to I

# OpenPassiveDataStream(AutoPassive, "MLSD /", 0)
Command:  EPSV
Status:   Waiting for response to: EPSV
Response: 229 Entering Extended Passive Mode (|||56696|)
Status:   Connecting to IP #1= ***:8990
Status:   Testing connectivity using Socket.Poll()...
Unhandled exception. FluentFTP.FtpException: Can't connect REDACTED_TARGET_SERVER via proxy INTERNAL_PROXY_IP.
```

I believe that it is caused by host setting in the GetEnhancedPassivePorsts Method (call in class OpenPassiveDataStream.cs, line 55). The **host** property is set from the SocketRemoteEndPoint Adress, which unfortunatelly has the IP adress of the Proxy server, not the IP of the target FTP server. As such the next connect request for the data stream (call in class OpenPassiveDataStream.cs, line 110) tries to connect to the HTTP Proxy IP using the passive port that was read from the previos response. 
Basically it tries to connect to: 
**PROXY_ADDRESS: PassivePort**, instead of
**TARGER_ADDRESS: PassivePort** 

Changing the line 44 in the class GetPassivePorts.cs from 
```host = SocketRemoteEndPoint.Address.ToString();``` to 
```host = m_host;``` solved the issue for me, but might cause problems when the target FTP server uses multiple ip`s. 

```
protected void GetEnhancedPassivePort(FtpReply reply, out string host, out int port) {
	var m = Regex.Match(reply.Message, @"\([!\|][!\|][!\|](?<port>\d+)[!\|]\)");
	if (!m.Success) {
		// In the case that ESPV is responded with a regular "Entering Passive Mode" instead, we'll try that parsing before we raise the exception
		/* Example:
		Command: EPSV
		Response: 227 Entering Passive Mode(XX, XX, XX, XX, 143, 225).
		*/

		try {
			GetPassivePort(FtpDataConnectionType.AutoPassive, reply, out host, out port);
			return;
		}
		catch {
			throw new FtpException("Failed to get the EPSV port from: " + reply.Message);
		}
	}
	// If ESPV is responded with Entering Extended Passive. The IP must remain the same.
	/* Example:
	Command: EPSV
	Response: 229 Entering Extended Passive Mode(|||10016|)

	If we set the host to ftp.host.com and ftp.host.com has multiple ip's we may end up with the wrong ip.
	Making sure that we use the same IP.
	host = m_host; 
	*/
	host = SocketRemoteEndPoint.Address.ToString();
	port = int.Parse(m.Groups["port"].Value);
}
```

Could you please take a look at this. Any help or advice would be very much appreciated. If you need any more details or logs, please just let me know.

Thank you!

**Comment by FanDjango** [comment]
Nice bug report, thanks.

It used to be: `host = m_host;` until the problem of multiple IPs for the host came up in an issue.

To fix that, this was coded:
```cs
host = SocketRemoteEndPoint.Address.ToString();
```

This was to make sure we connect to the right one, using an IPAD instead of a DNS name. Doesn't work so well for proxy, hmmm.

So far, so bad :-)

But ever since the DNS IP cache was introduced in the connect logic, we actually have a lookup-table to use for getting this IPAD instead of using ` SocketRemoteEndPoint.Address.ToString();`.

Let me look at it some more and maybe make a special branch for you to test, would you be prepared to try with that then?

**Comment by zubo100** [comment]
Happy to help ;) 

In our app I am using the oficial stable nuget package, but I have created a simple console application for testing purposes, so I could use that for the test. I noticed the DNS cache in the code before, and I think it could serve exactly for the purpose that we need. I can try it out tommorow and let you know.

**Comment by FanDjango** [comment]
OK. The branch, it's to be found --> [here](https://github.com/FanDjango/FluentFTP/tree/ProxyTest) <--

**Comment by zubo100** [comment]
Hi again! I tried our usecases with the branch you provided, but unfortunately it did not solve the issue. The connection was ok, but the directory listing failed. So:
```cs
host = m_stream.GetCachedHostAddresses(m_host)[0].ToString();
``` 
**failed**, while 
```cs
host = m_host;
```
still **works**. 

The IP address was resolved correctly. SImply said, using the IP address was failed, using the hostname was ok. I believe that this might be caused by the server itself. The target FTP server on iour case is in a data center, so I assume there might be several hostnames set to the same IP address, or a load balancer might be used. As such I think it is required that the hostname musst be used for the connection. 

I would like to propose a solution (at least partial). 
The config of the client could be extended, and define a new property, something like 
```cs
public bool ConnectUsingHostname { get; set; } = true;
``` 
that could be set when initialising the client, and checked when creating the connection
```cs
if (this.Config.ConnectUsingHostname)
{
    host = m_host;
}
else
{
    host = m_stream.GetCachedHostAddresses(m_host)[0].ToString();
}
```

**Comment by FanDjango** [comment]
Needs some more analysis, perhaps.

On the **initial** control connection **we** do a DNS query for the host and get a list of IPADs (most often a single IP, but possibly multiple). We try them one by one until we succeed to connect. We then "remember" the IPAD that we successfully connected to.

We don't want to connect to a different IPAD on opening a data connection (of which there can be many, sequentially).

So, each time we now connect, we use the "remembered" IPAD.

Question: Why is using that IPAD suddenly wrong, when it was not wrong on the first connect? Why do you need to use "host". And, think about this also: This query for host should, because of our remembering its IPAD, resolve down to the same IPAD as before.

Where is the flaw in my thinking? Can you help?

**Comment by FanDjango** [comment]
Also, in your log I am missing the
```
[Info] Connecting to IP #1= xxx.xx.xx.xx:nnnnn
```
message.

**Comment by FanDjango** [comment]
I think it is probably because of

```cs
		protected override void Connect(FtpSocketStream stream, string host, int port, FtpIpVersion ipVersions) {
			base.Connect(stream);
...
```
also doing a few things that **need** hostname instead of IPAD in the proxy override for connect.

**Comment by FanDjango** [comment]
We are getting the connect OK, but the conversation with the proxy is failing, it needs the **real** hostname.

**Comment by zubo100** [comment]
Here is the log output using the current changes:
 
```
# Connect(False)
Status:   FluentFTP 45.1.0.0
Status:   Connecting to IP #1= ***:8990
HTTP/1.0 200 Connection established

Status:   Waiting for a response
Response: 220 FTP Server 1.0 [738571,434d]
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 234 AUTH TLS successful [7ms]
Warning:  SSL Buffering force disabled, is .NET 5.0 and later
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 44550, 255) [142ms]
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Password required for *** [7ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230 User *** logged in [42ms]
Command:  PBSZ 0
Status:   Waiting for response to: PBSZ 0
Response: 200 PBSZ 0 successful [15ms]
Command:  PROT P
Status:   Waiting for response to: PROT P
Response: 200 Protection set to Private [7ms]
Command:  FEAT
Status:   Waiting for response to: FEAT
Response: 211-Features:
Response: AUTH TLS
Response: CCC
Response: CLNT
Response: EPRT
Response: EPSV
Response: HOST
Response: LANG en-US.UTF-8*;en-US
Response: MDTM
Response: MFF modify;UNIX.group;UNIX.mode;
Response: MFMT
Response: MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.groupname*;UNIX.mode*;UNIX.owner*;UNIX.ownername*;
Response: PBSZ
Response: PROT
Response: RANG STREAM
Response: REST STREAM
Response: SIZE
Response: SSCN
Response: TVFS
Response: UTF8
Response: 211 End [11ms]
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Status:   Waiting for response to: OPTS UTF8 ON
Response: 200 UTF8 set to on [7ms]
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 UNIX Type: L8 [7ms]
Status:   Listing parser set to: Machine
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/" is the current directory [7ms]

# GetListing("/", Auto)
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Type set to I [7ms]

# OpenDataStream("MLSD /", 0)

# OpenPassiveDataStream(AutoPassive, "MLSD /", 0)
Command:  EPSV
Status:   Waiting for response to: EPSV
Response: 229 Entering Extended Passive Mode (|||57056|) [7ms]
Status:   Connecting to IP #1= ***:8990
Status:   Testing connectivity using Socket.Poll()...

C:\REDACTED\SampleConsole.exe (process 40304) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```
When I debug, I get an system.IO.IOExceptin, wich is caught in class GetListing.cs line 263, (but not logged) and simply returns and empty listing. Exception details: 

```
System.IO.IOException
  HResult=0x80131620
  Message=Unable to read data from the transport connection: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat..
  Source=System.Net.Sockets
  StackTrace:
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\Users\zuber935\Downloads\FluentFTP-ProxyTest\FluentFTP-ProxyTest\FluentFTP\Streams\FtpSocketStream.cs:line 540
   at FluentFTP.FtpDataStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\Users\zuber935\Downloads\FluentFTP-ProxyTest\FluentFTP-ProxyTest\FluentFTP\Streams\FtpDataStream.cs:line 61
   at FluentFTP.FtpSocketStream.ReadLine(Encoding encoding) in C:\Users\zuber935\Downloads\FluentFTP-ProxyTest\FluentFTP-ProxyTest\FluentFTP\Streams\FtpSocketStream.cs:line 605
   at FluentFTP.Proxy.SyncProxy.FtpClientHttp11Proxy.GetProxyReply(FtpSocketStream stream) in C:\Users\zuber935\Downloads\FluentFTP-ProxyTest\FluentFTP-ProxyTest\FluentFTP\Proxy\SyncProxy\FtpClientHttp11Proxy.cs:line 89
   at FluentFTP.Proxy.SyncProxy.FtpClientHttp11Proxy.ProxyHandshake(FtpSocketStream stream) in C:\Users\zuber935\Downloads\FluentFTP-ProxyTest\FluentFTP-ProxyTest\FluentFTP\Proxy\SyncProxy\FtpClientHttp11Proxy.cs:line 73
   at FluentFTP.Proxy.SyncProxy.FtpClientHttp11Proxy.Connect(FtpSocketStream stream, String host, Int32 port, FtpIpVersion ipVersions) in C:\Users\zuber935\Downloads\FluentFTP-ProxyTest\FluentFTP-ProxyTest\FluentFTP\Proxy\SyncProxy\FtpClientHttp11Proxy.cs:line 69
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart) in C:\Users\zuber935\Downloads\FluentFTP-ProxyTest\FluentFTP-ProxyTest\FluentFTP\Client\SyncClient\OpenPassiveDataStream.cs:line 111
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart) in C:\Users\zuber935\Downloads\FluentFTP-ProxyTest\FluentFTP-ProxyTest\FluentFTP\Client\SyncClient\OpenDataStream.cs:line 55
   at FluentFTP.FtpClient.GetListingInternal(String listcmd, FtpListOption options, Boolean retry) in C:\Users\zuber935\Downloads\FluentFTP-ProxyTest\FluentFTP-ProxyTest\FluentFTP\Client\SyncClient\GetListing.cs:line 200

  This exception was originally thrown at this call stack:
    System.Net.Sockets.NetworkStream.Read(byte[], int, int)

Inner Exception 1:
SocketException: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.
```

Using 
```cs 
host = m_host;
```
works.

**Comment by FanDjango** [comment]
Yeah, it looks like the proxy code wants the hostname, the base will accept the host and get the remembered IP correctly.

**Comment by FanDjango** [comment]
This was not the case some until the connect code was re-done some months ago, so the endpoint stuff is really not needed anymore.

**Comment by FanDjango** [comment]
So we don't need the differentiation proxy/no-proxy at all. Just use the hostname.

**Comment by zubo100** [comment]
Sure, that was just a simple proposal ;)  I am not familiar with all the requirements and details of the package.
I will gladly test the changes once they are implemented.

**Comment by FanDjango** [comment]
Ok, so tomorrow I will modify the test-branch for you (and me) and we'll test it for a while.

**Comment by FanDjango** [comment]
Ok, you can pick up the above mentioned test branch again. I have updated it.

**Comment by zubo100** [comment]
Hi! I tried the last implmementation and it seems to be ok. Directory listing, Upload, all ok.

**Comment by FanDjango** [comment]
I will test some more, but by next week I will decide together with @robinrodricks

**Comment by FanDjango** [comment]
@zubo100 I have merged this, tested it some more and it will be in the next release.

**Comment by FanDjango** [comment]
Released

https://www.nuget.org/packages/FluentFTP/45.2.0
