### ISSUE TITLE
Timed out trying to connect!

### ISSUE THREAD

**Issue by jmbmp** [robinrodricks/FluentFTP#1206]
**FTP Server OS:** Windows /

**FTP Server Type:** Vsftpd / glFTPd / BFTPd / ProFTPD / Pure-FTPd / IBM CS FTP (z/OS, OS/400) / Windows CE / Windows Server IIS / Vax / VMS / OpenVMS / Tandem / HP NonStop

**Client Computer OS:** Windows 

**FluentFTP Version:** 44.0.1.0

**Framework:** .NET 4.6 

<write details about your bug report / feature request here>

Hello, how can I catch the error 'Timed out trying to connect', when the server is not operational.

**Logs :**

```

<paste VERBOSE logs here>

```

**Comment by FanDjango** [comment]
Does this situation not result in an Exception after a certain amount of time?

**Comment by jmbmp** [comment]
Si, yes, but it is not captured
            using (var ftp = new FtpClient("", "", "")) // 
            {
                ftp.Connect();
                try
                {
                }
                catch (System.TimeoutException ex)
                {
                    MessageBox.Show("Error ...! " + ex);
                }
                catch (Exception ex)
                {
                   MessageBox.Show("Error ..." + ex);
                }
			}

System.TimeoutException
  HResult=0x80131505
  Mensaje = Timed out trying to connect!
  Origen = FluentFTP
  Seguimiento de la pila:
   en FluentFTP.FtpSocketStream.Connect(String host, Int32 port, FtpIpVersion ipVersions)
   en FluentFTP.FtpClient.Connect(FtpSocketStream stream)
   en FluentFTP.FtpClient.Connect(Boolean reConnect)
   en FluentFTP.FtpClient.Connect()
   en Update.MainWindow.Button_Click(Object sender, RoutedEventArgs e) en I:\C#\Proyectos\Update\MainWindow.xaml.cs:

**Comment by FanDjango** [comment]
Put the connect inside the try?

**Comment by FanDjango** [comment]
Show your exact code, please

**Comment by FanDjango** [comment]
> ftp.Connect();
try
{
}

This is not correct.

**Comment by jmbmp** [comment]
Yes

**Comment by jmbmp** [comment]
private void Button_Click(object sender, RoutedEventArgs e)
        {
            EndTask("uprincipal.exe");

            string localDir = AppDomain.CurrentDomain.BaseDirectory;
            localDir.Substring(0, localDir.Length - 1);
            var cif = Update.ConnectDB.GetCif();
            String destino = "/ClientesUP/" + cif + "/";


            ProgressBar1.Minimum = 0;
            ProgressBar1.Maximum = 100;
            ProgressBar1.Value = 0;

            //Cree una nueva instancia de nuestro Delegado de ProgressBar que apunte al método SetValue de ProgressBar
            double value = 0;
            UpdateProgressBarDelegate updatePbDelegate = new UpdateProgressBarDelegate(ProgressBar1.SetValue);

            using (var ftp = new FtpClient("", "", "")) // 
            {
                ftp.Connect();

                try
                {
                    // 
                    Action<FtpProgress> progress = delegate (FtpProgress p)
                    {
                        if (p.Progress == 100)
                        {
                            // 
                            ProgressBar1.Value = 0;
                            label1.Text = "  " + (p.FileIndex + 1) + " / " + p.FileCount + "  " + p.RemotePath;
                            //Console.WriteLine($"{p.FileIndex}/{p.FileCount}, {(int)p.Progress} {p.TransferredBytes}, {p.TransferSpeedToString()}, {p.RemotePath}");

                        }
                        else
                        {
                            value = (int)p.Progress;
                            //    Console.WriteLine($"{p.FileIndex}/{p.FileCount}, {(int)p.Progress} {p.TransferredBytes}, {p.TransferSpeedToString()}, {p.RemotePath}");
                            Dispatcher.Invoke(updatePbDelegate,
                                 System.Windows.Threading.DispatcherPriority.Background,
                                 new object[] { ProgressBar.ValueProperty, value });
                        }
                    };

                    // 
                    var jose = ftp.DownloadDirectory(@localDir, @destino, FtpFolderSyncMode.Update, FtpLocalExists.Overwrite, FtpVerify.None, null, progress);
                    foreach (var dr in jose)
                    {
                        fichero.Add(new Fichero { Nombre = dr.Name.ToString(), Actualizado = dr.IsSuccess.ToString() });
                    }
                    lvUsers.ItemsSource = fichero;
                }
                catch (System.TimeoutException ex)
                {
                    MessageBox.Show("Error de conexion! " + ex);
                }

                catch (Exception ex)
                {
                    MessageBox.Show("Error de conexion! " + ex);
                }
            }
        }

**Comment by FanDjango** [comment]
Ok. The Timout Exception is INSIDE / it comes from the CONNECT.

try {
connect
....

**Comment by jmbmp** [comment]
returns the same error

**Comment by FanDjango** [comment]
That's very strange.

**Comment by jmbmp** [comment]
I have done the tests using my pc as an ftp server. If I use a remote ftp server and :
try {
connect
....
If it works correctly.
Thanks for your time
Greetings
