### ISSUE TITLE
The process cannot access

### ISSUE THREAD

**Issue by redsky1119** [robinrodricks/FluentFTP#1208]
**FTP Server OS:Windows

**FTP Server Type:Windows Server IIS

**Client Computer OS:Windows 

**FluentFTP Version:44.0.1

**Framework:.NET 7 

<write details about your bug report / feature request here>

**Logs :System.IO.IOException: The process cannot access the file 'D:\AERecordStreamBuffer\AERecordStreamBuf.LOG' because it is being used by another process.

```

<paste VERBOSE logs here>

```
![image](https://user-images.githubusercontent.com/37852360/220575345-1d72dbb0-b07c-4156-ac8c-194e354340cd.png)

**Comment by FanDjango** [comment]
What part of "The process cannot access the file _xyz_ because it is being used by another process." is not clear to you?

**Comment by redsky1119** [comment]
I can succeed when I use [Upload Directory]! Then use [UploadFile], is there a parameter that can upload the file being used successfully?
![image](https://user-images.githubusercontent.com/37852360/221494496-95654e54-98dd-4d94-b8d9-2f91853a4541.png)
