### ISSUE TITLE
45.x: "Error   : *TransportSetInt(...) failed: (-809933984) Unknown error "

### ISSUE THREAD

**Issue by MyKeySoftMK** [robinrodricks/FluentFTP#1218]
**FTP Server OS:** Unix 

**FTP Server Type:** ProFTPD 

**Client Computer OS:** Windows 

**FluentFTP Version:** 45.1.0

**Framework:** .NET  6 

<write details about your bug report / feature request here>
I want to download a file from the server with "FTPSClnt.DownloadFile(LocalDirectory & "\" & FileName, FtpDirectory & "/" & FileName, FtpLocalExists.Overwrite)"

I using a MSTest-Project for Unittest. The downlaod is working not 100%. Most it works - but sometimes is break up. The exeption is "Error   : *TransportSetInt(...) failed: (-809933984) Unknown error "

If I start the Test again, sometimes it works - sometimes not

2023-02-24 14:26:33.5474|SECZ21340DQ5SL|Info|System||Connection is successfull 
2023-02-24 14:26:33.5474|SECZ21340DQ5SL|Debug|System||Connection Type:Default 
2023-02-24 14:26:33.5474|SECZ21340DQ5SL|Debug|System||Internet Protocol:1 
2023-02-24 14:26:33.5474|SECZ21340DQ5SL|Debug|System||Use Encryption:True 
2023-02-24 14:26:33.5474|SECZ21340DQ5SL|Debug|System||Server:2(19) 
2023-02-24 14:26:33.5474|SECZ21340DQ5SL|Debug|System||Server System:UNIX Type: L8 
2023-02-24 14:26:33.5474|SECZ21340DQ5SL|Debug|System||Endpoints: 10.10.10.12:64417 (local) / 217.237.186.110:21 (remote) 
2023-02-24 14:26:33.5474|SECZ21340DQ5SL|Info|System||Connection to FTP is successfull 
2023-02-24 14:26:33.6835|SECZ21340DQ5SL|Fatal|System||Error   : *TransportSetInt(...) failed: (-809933984) Unknown error

**Comment by FanDjango** [comment]
I need a more complete **verbose** FluentFTP log.

Probably something wrong with the TCP connection, the socket is not in the correct status, not available etc. 

I don't understand most of your error messages in your log. 

This one I recognize: `*TransportSetInt(...) failed: (-809933984) Unknown error`

But there must be more previous...

So that is not good enough to help you.

**Comment by MyKeySoftMK** [comment]
Can you give me a small tip how i can attach my NLOG (4.7.13) to your new Logging system?

I try it with

FTPSClnt.Logger = New FtpLogAdapter(NLog.LogManager.GetLogger("System"))

**Comment by FanDjango** [comment]
I don't know, I use the legacy logger only

**Comment by MyKeySoftMK** [comment]
I have try to use your example with serilog. 



                    FTPSClnt.Config.LogToConsole = True
                    FTPSClnt.Config.LogUserName = True
                    FTPSClnt.Config.LogPassword = True
                    FTPSClnt.Config.LogHost = True
                    FTPSClnt.Config.LogDurations = True

                    FTPLOGGGER = New LoggerConfiguration()
                    With FTPLOGGGER
                        .MinimumLevel.Debug()
                        .WriteTo.File(value, rollingInterval:=RollingInterval.Day)
                    End With
                    FTPLOGGGER.CreateLogger()


                    FTPSClnt.Logger = New FtpLogAdapter(FTPLOGGGER)



But the error is:

Unable to cast object of type 'Serilog.LoggerConfiguration' to type 'Microsoft.Extensions.Logging.ILogger'.

**Comment by FanDjango** [comment]
I saw that you now have logging working. Great!

**Comment by MyKeySoftMK** [comment]
[Remote.log](https://github.com/robinrodricks/FluentFTP/files/10838014/Remote.log)

Here the log for the mentioned error ;-) (Loglevel=10)

**Comment by MyKeySoftMK** [comment]
Thats right - sometimes it works - but mostly it breaks. In the time in there i create this uploaded log i have 5 times start the logging: 1 is working - 4 are failed

**Comment by FanDjango** [comment]
Ok. Can you change logging like follows in your config for GnuTls:

...LogMessages = GnuMessage.All

**Comment by FanDjango** [comment]
Also, if I make a new version, are you able to test it directly (i.e. not from Nuget, instead build it yourself)?

**Comment by MyKeySoftMK** [comment]
> Ok. Can you change logging like follows in your config for GnuTls:
> 
> ...LogMessages = GnuMessage.All
> 
> and send log again.
> 
> I can see what is going on, but need more detail.

OK - here is the log-File with (hopefully) more information for you

[Remote.log](https://github.com/robinrodricks/FluentFTP/files/10838253/Remote.log)

**Comment by MyKeySoftMK** [comment]
> Also, if I make a new version, are you able to test it directly (i.e. not from Nuget, instead build it yourself)?

I think, that is possible. In my project are vb.net/c# projects together. I using VS2022

**Comment by FanDjango** [comment]
Ok, step by step:

Here is how I set up my log level, please do this also:

```
				ftpClient.Config.CustomStream = typeof(FluentFTP.GnuTLS.GnuTlsStream);
				ftpClient.Config.CustomStreamConfig = new FluentFTP.GnuTLS.GnuConfig();

				var typedConfig = ftpClient.Config.CustomStreamConfig as GnuConfig;
				typedConfig.LogLevel = 1;
				typedConfig.LogMessages = GnuMessage.All;
```

So log level **only** 1 for the gnutls log messages, but **GnuMessage.All** for the wrapper messages.
And what you did for FLuentFPT message, Verbose, was very good, and please send again.

**Comment by FanDjango** [comment]
It will then look more like this example excerpt:

```
Command:  PASV
Status:   Waiting for response to: PASV
Status:   GnuTLS: 1   Interop : Handshake received GNUTLS_HANDSHAKE_NEW_SESSION_TICKET
Status:   GnuTLS: 1   Interop : Handshake processed GNUTLS_HANDSHAKE_NEW_SESSION_TICKET
Status:   GnuTLS: 1   Interop : *GnuTlsSessionGetFlags(...)
Status:   GnuTLS: 1   Interop : *GnuTlsSessionGetData2(...)
Status:   GnuTLS: 1   Interop : Retrieved session data with new session ticket
Status:   GnuTLS: 1   Interop : *GnuTlsSessionSetData(...)
Status:   GnuTLS: 1   Interop : FtpGnuStream.Read repeat #1 due to GNUTLS_E_AGAIN
Response: 227 Entering Passive Mode (127,0,0,1,205,180) [6ms]
Status:   Connecting to IP #1= ***:52660
Command:  MLSD /Xilinx/14.7/ISE_DS/PlanAhead/tps/win64/jre/lib
Status:   Waiting for response to: MLSD /Xilinx/14.7/ISE_DS/PlanAhead/tps/win64/jre/lib
Response: 150 Starting data transfer. [<1ms]
Status:   GnuTLS: 1   Interop : *.ctor(...):Session
Status:   GnuTLS: 1   Interop : *GnuTlsDbSetCacheExpiration(...)
Status:   GnuTLS: 1   Interop : *GnuTlsPrioritySetDirect(...)
Status:   GnuTLS: 1   Interop : *GnuTlsDhSetPrimeBits(...)
Status:   GnuTLS: 1   Interop : *GnuTlsCredentialsSet(...)
Status:   GnuTLS: 1   Interop : *GnuTlsAlpnSetProtocols(...)
Status:   GnuTLS: 1   Interop : *GnuTlsTransportSetPtr(...)
Status:   GnuTLS: 1   Interop : *GnuTlsHandshakeSetTimeout(...)
Status:   GnuTLS: 1   Interop : Setup client certificate - currently not implemented
Status:   GnuTLS: 1   Interop : *GnuTlsHandshakeSetHookFunction(...)
```

**Comment by MyKeySoftMK** [comment]
Sorry - i didn´t know the different of "Loglevel" & "LogMessages" - here my new result 
[Remote.log](https://github.com/robinrodricks/FluentFTP/files/10838595/Remote.log)

**Comment by FanDjango** [comment]
No need for sorry. This one is perfect.

I think I have found (possible) error in the call to SetTransportInt - You are calling the Fluent library from VB, right? So there is a possible difference.

**Comment by MyKeySoftMK** [comment]
> No need for sorry. This one is perfect.
> 
> I think I have found (possible) error in the call to SetTransportInt - You are calling the Fluent library from VB, right? So there is a possible difference.

Yes - my calling code is follwing

```
    Public Function DownloadFtpFile(FtpDirectory As String, FileName As String, LocalDirectory As String) As Boolean
        Dim result As Boolean = False

        Try

            If FTPSClnt.DownloadFile(LocalDirectory & "\" & FileName, FtpDirectory & "/" & FileName, FtpLocalExists.Overwrite) = FtpStatus.Success Then
                NLOGLOGGER.Info("Successfull download file: " & FtpDirectory & "/" & FileName)
                result = True
            Else
                NLOGLOGGER.Error("Error download file:" & FtpDirectory & "/" & FileName)
            End If

        Catch ex As Exception
            NLOGLOGGER.Fatal("DownloadFtpFile abnormal ending")
            NLOGLOGGER.Fatal(ex.Message)
            NLOGLOGGER.Fatal(ex.InnerException)
        End Try

        Return result
    End Function
```

**Comment by FanDjango** [comment]
Ok, I have made a change that I hope will work or at least tell us more what is going wrong.

You can pick it up from the current master: [master](https://github.com/robinrodricks/FluentFTP.GnuTLS)

It is a separate .sln, so you should be able to build it and get the .dll from there

**Comment by MyKeySoftMK** [comment]
> Ok, I have made a change that I hope will work or at least tell us more what is going wrong.
> 
> You can pick it up from the current master: [master](https://github.com/robinrodricks/FluentFTP.GnuTLS)
> 
> It is a separate .sln, so you should be able to build it and get the .dll from there

Thank you very much for your fast help - i think it work´s now. I have tried several times the download and there was successfull

When you release the new nuget then i will relink to them

**Comment by FanDjango** [comment]
Wow. Good. Thanks for your quick re-build etc.

I will ask @robinrodricks for a quick new release.
