### ISSUE TITLE
Please add an Logging-Sample for using NLog and Fluent.Logging

### ISSUE THREAD

**Issue by MyKeySoftMK** [robinrodricks/FluentFTP#1220]
I want to try send the output from FtpClient.Logger to my NLog-Instance.

Some Descriptions not work or bring up the error that the Instance is not a ILogger-Interface

Same with the example here on the Github that use "serilog"

My investigations are that "NLog.Extensions.Logging" is the correct way. But i didn´t understand how can i use that together with Fluent.Logger

Can you/someone give a working sample how the messages from Fluent.Logging can collect in NLog (with the defined targets and rules) in a console application? c# was fine - but i use VB,NET ;-)

**Comment by MyKeySoftMK** [comment]
Imports FluentFTP
Imports FluentFTP.GnuTLS
Imports FluentFTP.GnuTLS.Enums
Imports FluentFTP.Logging

Imports NLog
Imports NLog.Extensions.Logging

Imports ILogger = Microsoft.Extensions.Logging.ILogger


    Public WriteOnly Property FTPLOG_ENABLE As String
        Set(value As String)
            If value.Length > 0 Then
                If FTPSClnt Is Nothing Then
                    FTPSClnt = New FtpClient
                End If
                Try

                    FTPSClnt.Config.LogToConsole = True
                    FTPSClnt.Config.LogUserName = True
                    FTPSClnt.Config.LogPassword = True
                    FTPSClnt.Config.LogHost = True
                    FTPSClnt.Config.LogDurations = True

                    Dim loggerprovider As NLogLoggerProvider = New NLogLoggerProvider
                    Dim ftplogger As ILogger = loggerprovider.CreateLogger(GetType(**FtpsClientFuncs**).FullName)
                    FTPSClnt.Logger = New FtpLogAdapter(ftplogger)

                Catch ex As Exception

                End Try

            Else
                FTPSClnt.Logger = Nothing
            End If
        End Set
    End Property

**Comment by FanDjango** [comment]
@MyKeySoftMK Thanks really very much for this. We will put this in the Wiki. I know nothing about VB, so this is a big help :-)

**Comment by FanDjango** [comment]
@robinrodricks This for the wiki?

**Comment by MyKeySoftMK** [comment]
> @MyKeySoftMK Thanks really very much for this. We will put this in the Wiki. I know nothing about VB, so this is a big help :-)

And the connection to NLog - i think someone else use it
