### ISSUE TITLE
The process cannot access

### ISSUE THREAD

**Issue by redsky1119** [robinrodricks/FluentFTP#1221]
**FTP Server OS:Windows

**FTP Server Type:Windows Server IIS

**Client Computer OS:Windows

**FluentFTP Version:44.0.1

**Framework:.NET 7

<write details about your bug report / feature request here>
**Logs :System.IO.IOException: The process cannot access the file 'D:\AERecordStreamBuffer\AERecordStreamBuf.LOG' because it is being used by another process.
![image](https://user-images.githubusercontent.com/37852360/221503085-422ef28e-25dd-43f4-8326-5684b574df7e.png)

*****I can succeed when I use [Upload Directory]! Then use [UploadFile], is there a parameter that can upload the file being used successfully?*****

**Comment by FanDjango** [comment]
A complete log and perhaps the source code of what you are doing might be helpful?

Are you doing a UploadDirectory, is it successful for each file, are you then doing a UploadFile for one of the files in that directory? 

Why cannot you be **much** more clear in your problem description?

Then **perhaps** I could reproduce the problem easily or not.
