### ISSUE TITLE
When/how often does the Progress report the latest info? When is the callback fired?

### ISSUE THREAD

**Issue by PureKrome** [robinrodricks/FluentFTP#1225]
**FluentFTP Version:** v38.0.0

**Framework:** .NET 6

👋🏻 G'day! I'm trying to learn how often/when the `Progress` callback is actually "fired". Is there any way to "control" the timing of the callback? Like, could I say, "Report" every 5 seconds? or every 1 second?

I'm thinking about when I have some files that are large and could taken a while to upload or download.

Is this possible?

Thank kindly mate!

**Comment by FanDjango** [comment]
Every successful socket read or write operation, typically a full buffer, a call to progress is made.

FXP transfer seem to have a config parameter where you can select an interval for reports, but normal FTP transfers do no.

I typically report the change every time the % value changes and have noticed no detrimental effect - other code paths are overwhelmingly more influential in this.

**Comment by PureKrome** [comment]
For me, this is a background worker. So the progress changes are text-logging ... not a UI "progress bar" update :(

So to keep the logs from getting "text spam", I was hoping to restrict the amount that is reported - hence why I thought I could do it every x-seconds.

You said:

> FXP transfer seem to have a config parameter where you can select an interval for reports, but normal FTP transfers do no.

er... sincere apologies, but what does this mean? Is this a _type_ of FTP connection? or a specific class that is instantiated?

**Comment by FanDjango** [comment]
https://github.com/robinrodricks/FluentFTP/wiki/FXP-Server-To-Server

I noticed that whoever wrote that, included a parameter to set the time interval where progress is called.

Seems not to have been done for normal FTP.

**Comment by FanDjango** [comment]
But I check a static old percent and compare, in my progress routine, for example. You could check for elapsed time, it makes not real difference **where** this check is made, does it, only you need 3 lines of your own code.

**Comment by PureKrome** [comment]
Hmm.. so you mean to have the Action somehow remember the 'last time' and if it's over x-seconds, then report and reset the time?

**Comment by FanDjango** [comment]
Exactly. And that is what that sort of code **inside** the library would also do. So its not a big performance difference whether you do it or the library does it - only the location of the code IMO. Also, you have more options: By elasped time, by percent change, non linear, etc.

**Comment by FanDjango** [comment]
Start a stopwatch at begin. Check the sw.elapsed each progress call. remember each elapsed and check the difference, and so on and on...

**Comment by robinrodricks** [comment]
@PureKrome  as FanDjango said, you can easily implement event throttling on your end. We give you the best possible accuracy of progress by firing the event as often as possible, and you can reduce the frequency of events by doing this:
```
lastTime = DateTime.Now;

progressEventHandler(){
  var nowTime = DateTime.Now;
  var duration = nowTime - lastTime;
   if (duration > 1000){                        // 1000 MS is 1 second, change this to make it whatever you need
       lastTime = nowTime;

       // do whatever

   }
}
```

**Comment by PureKrome** [comment]
@robinrodricks thanks for the code! I'll give this a go, next week at work
