### ISSUE TITLE
Code: 425 Message: Unable to build data connection: Operation not permitted

### ISSUE THREAD

**Issue by digisam1985** [robinrodricks/FluentFTP#1227]
**FTP Server OS:** ???

**FTP Server Type:** Vsftpd 

**Client Computer OS:** Windows 

**FluentFTP Version:** 45.2.0.0

**Framework:** .NET 4.7.2

I have problem with this connection.

On any operation i have error

`FluentFTP.Exceptions.FtpCommandException: 'Code: 425 Message: Unable to build data connection: Operation not permitted'`

```
var client = new FtpClient("ftp.gls-italy.com", item.user_ftp, item.pwd_ftp);

                // connect to the server and automatically detect working FTP settings

                client.Config.LogToConsole = true;
                client.Config.EncryptionMode = FtpEncryptionMode.Auto;
                client.Config.ValidateAnyCertificate = true;
                client.Config.SslProtocols =  SslProtocols.None;
                client.Config.EncryptionMode = FtpEncryptionMode.Explicit;

                client.Connect();

                client.DownloadFile(@"C:\temp\Cassegni280220231529.txt", "Cassegni280220231529.txt");
```

**Logs :**

```
# Connect(False)
Status:   FluentFTP 45.2.0.0
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220 ProFTPD 1.3.5e Server (ftpB) [93.62.193.42] [738579,632d]
Status:   Detected FTP server: ProFTPD
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 234 AUTH TLS successful [30ms]
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, 44550, 256) [100ms]
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Password required for *** [33ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230 User *** logged in. [60ms]
Command:  PBSZ 0
Status:   Waiting for response to: PBSZ 0
Response: 200 PBSZ 0 successful [32ms]
Command:  PROT P
Status:   Waiting for response to: PROT P
Response: 200 Protection set to Private [30ms]
Command:  FEAT
Status:   Waiting for response to: FEAT
Response: 211-Features:
Response: AUTH TLS
Response: MFF modify;UNIX.group;UNIX.mode;
Response: REST STREAM
Response: MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.mode*;UNIX.owner*;
Response: UTF8
Response: EPRT
Response: EPSV
Response: LANG zh-CN;zh-TW;bg-BG;en-US;es-ES;fr-FR;it-IT;ja-JP;ko-KR;ru-RU
Response: MDTM
Response: SSCN
Response: TVFS
Response: MFMT
Response: SIZE
Response: PROT
Response: CCC
Response: PBSZ
Response: 211 End [33ms]
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Status:   Waiting for response to: OPTS UTF8 ON
Response: 200 UTF8 set to on [29ms]
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 UNIX Type: L8 [29ms]
Status:   Listing parser set to: Machine
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/" is the current directory [28ms]

# DownloadFile("C:\temp\Cassegni280220231529.txt", "Cassegni280220231529.txt", Overwrite, None)

# OpenRead("Cassegni280220231529.txt", Binary, 0, 0)

# GetFileSize("Cassegni280220231529.txt")
Command:  SIZE Cassegni280220231529.txt
Status:   Waiting for response to: SIZE Cassegni280220231529.txt
Response: 550 SIZE not allowed in ASCII mode [28ms]
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Type set to I [31ms]
Command:  SIZE Cassegni280220231529.txt
Status:   Waiting for response to: SIZE Cassegni280220231529.txt
Response: 213 19272 [32ms]

# OpenDataStream("RETR Cassegni280220231529.txt", 0)

# OpenPassiveDataStream(AutoPassive, "RETR Cassegni280220231529.txt", 0)
Command:  EPSV
Status:   Waiting for response to: EPSV
Response: 229 Entering Extended Passive Mode (|||64917|) [30ms]
Status:   Connecting to IP #1= ***:64917
Command:  RETR Cassegni280220231529.txt
Status:   Waiting for response to: RETR Cassegni280220231529.txt
Response: 150 Opening BINARY mode data connection for Cassegni280220231529.txt (19272 bytes) [30ms]
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, 44550, 256) [49ms]
Status:   Downloaded 0 bytes
Status:   Closing/Disposing FtpSocketStream(data connection)
Status:   Waiting for response to: *DOWNLOAD*
Response: 425 Unable to build data connection: Operation not permitted [89ms]
Status:   Failed to download file.

# GetListing("/", Auto)

# OpenDataStream("MLSD /", 0)
Status:   Testing connectivity using Socket.Poll()...

# OpenPassiveDataStream(AutoPassive, "MLSD /", 0)
Command:  EPSV
Status:   Waiting for response to: EPSV
Response: 229 Entering Extended Passive Mode (|||59012|) [34ms]
Status:   Connecting to IP #1= ***:59012
Command:  MLSD /
Status:   Waiting for response to: MLSD /
Response: 150 Opening BINARY mode data connection for MLSD [29ms]
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, 44550, 256) [56ms]
+---------------------------------------+
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: MLSD /
Response: 425 Unable to build data connection: Operation not permitted [89ms]
Status:   Closing/Disposing FtpSocketStream(data connection)

```

**Comment by FanDjango** [comment]
Hi!

You wrote: `FTP Server Type: Vsftpd`.

Nope,

I can see in the log:

```
Response: 220 ProFTPD 1.3.5e Server (ftpB) [93.62.193.42] [738579,632d]
Status:   Detected FTP server: ProFTPD
```

Thanks for posting the log.

```
Response: 425 Unable to build data connection: Operation not permitted [89ms]
```

This respons is **very probably** due to proFTPd 1.3.5e requesting session resumption - interestingly enough, my proFTPd 1.3.7a **works** ok with session resume.

Also, google is your friend: https://forum.filezilla-project.org/viewtopic.php?t=51548

So, to make sure, analyze the log of proFTPD on the server for further information, test with a newer proFTPd version, and consider using FluentFTP.GnuTls as an alternative.

**Comment by FanDjango** [comment]
Reference: #1222 #1203 #1156

**Comment by digisam1985** [comment]
Hi 

if i add this code i have another error

`                client.Config.CustomStream = typeof(GnuTlsStream);
                client.Config.CustomStreamConfig = new GnuConfig()
                {
                    LogLevel = 1,

                    // sample setting to use the default security suite
                    SecuritySuite = GnuSuite.Normal,

                    // sample setting to include all TLS protocols except for TLS 1.0 and TLS 1.1
                    SecurityOptions = new List<GnuOption> {
                        new GnuOption(GnuOperator.Include, GnuCommand.Protocol_All),
                        new GnuOption(GnuOperator.Exclude, GnuCommand.Protocol_Tls10),
                        new GnuOption(GnuOperator.Exclude, GnuCommand.Protocol_Tls11),
                    },

                    // no profile required
                    SecurityProfile = GnuProfile.None,

                    // sample special flags (this is not normally required)
                    AdvancedOptions = new List<GnuAdvanced> {
                        GnuAdvanced.CompatibilityMode
                    },

                    HandshakeTimeout = 5000,
                };`

`System.BadImageFormatException: 'Tentativo di caricare un programma con un formato non corretto. (Eccezione da HRESULT: 0x8007000B)'`

**Comment by FanDjango** [comment]
x64?

**Comment by digisam1985** [comment]
yes

**Comment by FanDjango** [comment]
Must be some discrepancy between your target and in the csproj files. Google the fail message and you will see many possibilities

**Comment by digisam1985** [comment]
The libs files are for x32?

**Comment by FanDjango** [comment]
https://github.com/robinrodricks/FluentFTP/wiki/FTPS-Connection-using-GnuTLS

Currently the libraries are **for x64**. 

A number of people are using them. You must search for the cause on your side.

Also: Windows. But you wrote windows, so ok...

**Comment by FanDjango** [comment]
Did you manage to find something?

One thing that I thought of: You should use the libraries included with the Nuget package, not some libraries you picked up elsewhere - they **might** not be compatible according to their format.

**Comment by FanDjango** [comment]
I am now able to reproduce your problem, **I think**.

When using .NET Framework, you get this error. We are working on this.

**Comment by FanDjango** [comment]
So, it was a packaging problem for .NET Framework.
Version **1.0.5**, better yet version **1.0.6** fixes this for you.

**Comment by FanDjango** [comment]
FluentFTP.GnuTLS 1.0.6 is released.
