### ISSUE TITLE
Erroneous Permission exception on FtpClient.DownloadFile on Ubuntu 14.0.4

### ISSUE THREAD

**Issue by haggerty-william** [robinrodricks/FluentFTP#123]
When I try to use the DownloadFile function it throws an exception saying permission denied on the directory, however I was able to create, write, and read through the File class in the same directory.
My workaround was to create a FileStream to the same spot and use the FtpClient.Download(stream, filePath).

**Comment by hgupta9** [comment]
Maybe its permission denied on the local directory?

**Comment by haggerty-william** [comment]
FtpClient.Download(stream, filePath) worked in the same directory. I was also able to create, read and write to files using the File class.

**Comment by robinrodricks** [comment]
Not sure how to fix this.
