### ISSUE TITLE
Possible NullReferenceExceptions if the connection was not opened

### ISSUE THREAD

**Issue by yzhoholiev** [robinrodricks/FluentFTP#1231]
Possible regression introduced:
https://github.com/robinrodricks/FluentFTP/blob/02d8b9dfec3d096e851a9a7ad6054fe93efc7fc5/FluentFTP/Client/AsyncClient/Execute.cs#L57

The `m_stream` can be null here.

**Comment by FanDjango** [comment]
Apologies. Not a regression. Previous fix was incomplete. Working on it...

**Comment by FanDjango** [comment]
@yzhoholiev I invite you to check the current master, I merged a fix for this. It will then be in the next release.

**Comment by FanDjango** [comment]
Released! 46.0.2
