### ISSUE TITLE
I using async await for multi threading. also using asnyc fluentFTPClient so how to prevent it

### ISSUE THREAD

**Issue by kingsanu** [robinrodricks/FluentFTP#1237]
The WriteAsync method cannot be called when another write operation is pending.
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)

**Comment by FanDjango** [comment]
Hello. Good Morning. Please, Thank you and Goodbye. Add these words to your repertoire and you might get answers to questions easier.

Apart from that: Google is your (perhaps only) friend: https://stackoverflow.com/questions/12611861/sslstream-writeasync-the-beginwrite-method-cannot-be-called-when-another-write
