### ISSUE TITLE
FtpParser.Windows does nothing

### ISSUE THREAD

**Issue by github-aem** [robinrodricks/FluentFTP#1240]
**FTP Server OS:**   Embedded PLC

**FTP Server Type:** Whatever is run on a PLC controller.  It spits out a file listing in DOS style format.

**Client Computer OS:** Programmable logic controller.  No OS.

**FluentFTP Version:** 46.02

**Framework:** .NET  6 

So here is the problem.  When I choose to use the Windows ftp parser, it doesn't use it.  You can see that in the log.  Below is my program and the output.

(and why are code and quote markups not working in preview here?)

```cs

using FluentFTP;
using FluentFTP.Client.BaseClient;
using Microsoft.VisualBasic;
using System.Security.Authentication;

const string WorkingDir = "/FCDATA01/DATALOG/z1_temp";
const string LocalRelativeFolder = "files";

FtpConfig ftpConfig = new()
{
    SslProtocols = SslProtocols.Tls12,
    DataConnectionType = FtpDataConnectionType.AutoActive,
    ListingParser = FtpParser.Windows,
    //ListingParser = FtpParser.Custom,
    //ListingCustomParser = new(CustParser),
    ValidateAnyCertificate = true,
    LogToConsole = true,
    RetryAttempts = 3
};

AsyncFtpClient ftpClient = new("host", "user", "secret", config: ftpConfig);

await ftpClient.Connect();

Console.WriteLine("GetListing");
FtpListItem[] ftpListItems;
try
{
    ftpListItems = await ftpClient.GetListing("/", FtpListOption.Recursive | FtpListOption.SizeModify);
    foreach (var item in ftpListItems)
    {
        Console.WriteLine($"{item.Name} {item.Size} {item.Created} {item.Modified}");
    }
}
catch (Exception ex)
{
    Console.WriteLine($"{ex.HResult} {ex.Message}");
}
await ftpClient.Disconnect();

```

```
> # Connect(False)
> Status:   FluentFTP 46.0.2.0
> Status:   Connecting to IP #1= ***:21
> Status:   Waiting for a response
> Response: 220 FTP Service ready for new user. [738599.197d]
> Command:  USER ***
> Status:   Waiting for response to: USER ***
> Response: 331 User name okay, need password. [491ms]
> Command:  PASS ***
> Status:   Waiting for response to: PASS ***
> Response: 230 User logged in, proceed. [231ms]
> Command:  FEAT
> Status:   Waiting for response to: FEAT
> Response: 502 Command not implemented. [257ms]
> Status:   Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
> Command:  SYST
> Status:   Waiting for response to: SYST
> Response: 215 FC6A Series v1.81 . [498ms]
> Warning:  Cannot auto-detect listing parser for system 'Unknown', using Unix parser
> Status:   Listing parser set to: Unix
> Command:  PWD
> Status:   Waiting for response to: PWD
> Response: 257 "/" is current directory. [445ms]
> GetListing
> 
> # GetListing("/", SizeModify)
> Command:  TYPE I
> Status:   Waiting for response to: TYPE I
> Response: 200 Command successful. [257ms]
> 
> # OpenDataStreamAsync("LIST /", 0)
> 
> # OpenActiveDataStreamAsync(AutoActive, "LIST /", 0)
> Command:  EPRT |1|172.86.161.200|42343|
> Status:   Waiting for response to: EPRT |1|172.86.161.200|42343|
> Response: 502 Command not implemented. [358ms]
> Status:   Closing/Disposing FtpSocketStream(data connection)
> 
> # OpenActiveDataStreamAsync(PORT, "LIST /", 0)
> Command:  PORT 172,86,161,200,165,104
> Status:   Waiting for response to: PORT 172,86,161,200,165,104
> Response: 200 Command successful. [290ms]
> Command:  LIST /
> Status:   Waiting for response to: LIST /
> Response: 150 Opening data connection. [520ms]
> +---------------------------------------+
> Listing:  03-10-21 11:12       <DIR> System Volume Information
> Listing:  12-03-20 13:40       <DIR> FCDATA01
> -----------------------------------------
> Status:   Closing/Disposing FtpSocketStream(data connection)
> 
> # CloseDataStream()
> Status:   Waiting for response to: LIST /
> Response: 226 Transfer complete. [815ms]
> Status:   Closing/Disposing FtpSocketStream(data connection)
> Status:   Not in UNIX format
> Status:   Not in UNIX format
> Status:   Detected format Windows
> -2146233086 startIndex cannot be larger than length of string. (Parameter 'startIndex')
> Command:  QUIT
> Status:   Waiting for response to: QUIT
> Response: 221 FTP Service closing control connection. [274ms]
> Status:   Closing/Disposing FtpSocketStream(control connection)
> 
```

**Comment by FanDjango** [comment]
> When I choose to use the Windows ftp parser, it doesn't use it

Looks like that needs to be debugged/analyzed.

I do see another problem as well:

```
> Status:   Detected format Windows
> -2146233086 startIndex cannot be larger than length of string. (Parameter 'startIndex')
```

Regardless of your setting the windows parser being ignored for some reason, in the end some format of windows is actually being automatically recognized, which then fails for some unknown reason because the format is not totally according to the code of the windows parser.

So TWO things to look at.

**Comment by FanDjango** [comment]
Can you provide a sample output where there are files and not just <DIR> entries?

**Comment by FanDjango** [comment]
I have found out why this part of the problem is happening:
```
Status:   Detected format Windows
-2146233086 startIndex cannot be larger than length of string. (Parameter 'startIndex')
```
The Windows/IIS parser is using **fixed offsets** (which could be improved greatly?) to find the names in the listing lines.
Thus, `System Volume Information` becomes `lume Information` and `FCDATA01` **is too short to survive**, it causes an exception.
The format is not standard Windows/IIS, **but** it is close enough. If the parser were to be improved slightly to disregard collumn offset and use wordIndex positiong instead, it would work for all sorts of formats.

**Comment by FanDjango** [comment]
The documentation in the description of `Config.ListParser` says `If you want to override this property, make sure to do it after calling Connect.`.

This is because 'Connect()' tries to determine the parser type and very very often succeeds.

Would you please like to try that in your code instead of **before** the `Connect()`;

**Comment by github-aem** [comment]
> Can you provide a sample output where there are also files and not just `<DIR>` entries?
I looked up the company on the programable logic controller this FTP service is running on.  Their name is IDEC.

```

# OpenActiveDataStreamAsync(PORT, "LIST /FCDATA01/WEBPAGE/WEBPAGE/viewer/setting", 0)
Command:  PORT 172,86,161,200,159,22
Status:   Waiting for response to: PORT 172,86,161,200,159,22
Response: 200 Command successful. [202ms]
Command:  LIST /FCDATA01/WEBPAGE/WEBPAGE/viewer/setting
Status:   Waiting for response to: LIST /FCDATA01/WEBPAGE/WEBPAGE/viewer/setting
Response: 150 Opening data connection. [437ms]
+---------------------------------------+
Listing:  12-03-20 13:34         187 devicetypes.json
Listing:  12-03-20 13:34          56 lang.jp.txt
Listing:  12-03-20 13:34          95 lang.txt
Listing:  12-03-20 13:34          56 lang.zh.txt
Listing:  12-03-20 13:34       21225 Page1.page
Listing:  12-03-20 13:33       <DIR> image
Listing:  12-03-20 13:33       <DIR> lamp
Listing:  12-03-20 13:34       <DIR> switch
Listing:  12-03-20 13:34       <DIR> video
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()

```


I don't remember if this happened before.  I cloned the main branch of the repository and used it instead of the nuget package.    I did a listing recursively and it actually appeared to continue down the directory tree.  ie. It did was it was supposed to.  I was using the Windows parser set after the connection was established.

What started this whole thing was ftpClient.DownloadDirectory().  It will not report progress or file size in the download even though I can clearly use the custom parser I wrote to get the file sizes.  I can get the file sizes in await ftpClient.GetListing("/", FtpListOption.Recursive | FtpListOption.SizeModify).  Is it not using the custom parser to get the file size and modified times even though I specified to use it both before and after the connection was opened?  It has to be using it for something or GetListing wouldn't report correct file sizes.  When I do a await ftpClient.GetFileSize(remoteFilePath, -999) it returns -999 each time.  I don't understand how the client is finding the sizes and dates for files.  It almost appears like there is one parser for one section of the code and a different one for others.  Here is a snippet of the custom parser hack I threw together.
```

static FtpListItem CustParser(string entry, List<FtpCapability> ftpCapabilities, BaseFtpClient ftpclient)
{
    var rc = new FtpListItem();
    var u = entry.Split(" ", StringSplitOptions.RemoveEmptyEntries);

    var d = DateTime.Parse(u[0].Trim() + " " + u[1].Trim());
    rc.Created = d;
    rc.Modified = d;
    rc.RawModified = d;  // What is the difference between Raw and not Raw?
    rc.RawCreated = d;

    if (u[2].Trim() == "<DIR>")
    {
        rc.Type = FtpObjectType.Directory;
        rc.SubType = FtpObjectSubType.SubDirectory;  // Who knows if I am using this correctly
    }
    if (Information.IsNumeric(u[2]) == true)
    {
        rc.Type = FtpObjectType.File;
        rc.Size = int.Parse(u[2]);
    }
    string fname = "";
    for (int i = 3; i < u.Length; i++)
    {
        fname = string.Concat(fname, u[i], " ");
    }
    rc.Name = fname.TrimEnd();
    return rc;
}

```

**Comment by FanDjango** [comment]
> I cloned the main branch of the repository and used it instead of the nuget package. I did a listing recursively and it actually appeared to continue down the directory tree. ie. It did was it was supposed to. I was using the Windows parser set after the connection was established.

So that part is now looking good.

> What started this whole thing was ftpClient.DownloadDirectory(). It will not report progress or file size in the download even though I can clearly use the custom parser I wrote to get the file sizes. I can get the file sizes in await ftpClient.GetListing("/", FtpListOption.Recursive | FtpListOption.SizeModify). Is it not using the custom parser to get the file size and modified times even though I specified to use it both before and after the connection was opened? It has to be using it for something or ...

For this part, could you please open a separate new issue with a suitable title and concise problem documentation.

Thanks!

**Comment by FanDjango** [comment]
The Windows Parser fix will find its way into the next Nuget release.
