### ISSUE TITLE
The GetFileSize and GetFileSizeAsync functions always return 0

### ISSUE THREAD

**Issue by Legendaire** [robinrodricks/FluentFTP#1244]
**FTP Server OS:** Any

**FTP Server Type:** Any

**Client Computer OS:** Windows 

**FluentFTP Version:** 46.0.2

**Framework:** .NET 6 

The GetFileSize and GetFileSizeAsync functions always return 0.  Since the progress reporting uses these functions to determine file sizes, it can not report progress properly.  If these are too difficult to implement, can we just use the file size of the FtpResult or FtpListItem passed to the download functions?  Perhaps we add a TotalFileSize (or ExpectedFileSize) to the FtpProgress class and use that to pass the knownFileSize to DownloadFileToFileAsync?  (If the FtpProgress.WhateverTheNewPropertyIs turns out to be zero when passed to the DownloadFileToFileAsync function, then do the expensive call to GetFileSize) It would be nice to have the expected file size in the progress reports anyway.

```

		/// <summary>
		/// Perform server-specific file size fetching commands here.
		/// Return the file size in bytes.
		/// </summary>
		public virtual long GetFileSize(FtpClient client, string path) {
			return 0;
		}

		/// <summary>
		/// Perform server-specific file size fetching commands here.
		/// Return the file size in bytes.
		/// </summary>
		public virtual Task<long> GetFileSizeAsync(AsyncFtpClient client, string path, CancellationToken token) {
			return Task.FromResult(0L);
		}
```

**Comment by FanDjango** [comment]
> The GetFileSize and GetFileSizeAsync functions always return 0

A very bold statement. 

**First of all, show a log that "proves" your statement, please.**

For me, progress works fine.

**Second, show your code that corresponds to the log of the failure. Maybe you are doing something wrong**.

So **always** is not true.

Therefore, "**sometimes** might be better? 

Beyond that, the code snippet you show belongs to the `BaseClient`. Search some more for `GetFileSize` and you will see... 

```
		public virtual long GetFileSize(string path, long defaultValue = -1) {
			// verify args
			if (path.IsBlank()) {
				throw new ArgumentException("Required parameter is null or blank.", nameof(path));
			}

			path = path.GetFtpPath();

			LogFunction(nameof(GetFileSize), new object[] { path });

			// execute server-specific file size fetching logic, if any
			if (ServerHandler != null && ServerHandler.IsCustomFileSize()) {
				return ServerHandler.GetFileSize(this, path);
			}

			if (!HasFeature(FtpCapability.SIZE)) {
				return defaultValue;
			}

			var sizeReply = new FtpSizeReply();
			lock (m_lock) {
				GetFileSizeInternal(path, sizeReply, defaultValue);
			}
			return sizeReply.FileSize;
		}
```

**Comment by robinrodricks** [comment]
Add the full FTP logs. Check the logging section how to do that.

**Comment by FanDjango** [comment]
Seems to have resolved itself by itself :-)
