### ISSUE TITLE
Config.DownloadRateLimit does not affect DownloadBytes

### ISSUE THREAD

**Issue by okarpov** [robinrodricks/FluentFTP#1254]
**FTP Server OS:** Unix / Windows / Embedded

**FTP Server Type:** Vsftpd / glFTPd / BFTPd / ProFTPD / Pure-FTPd / IBM CS FTP (z/OS, OS/400) / Windows CE / Windows Server IIS / Vax / VMS / OpenVMS / Tandem / HP NonStop

**Client Computer OS:** Windows

**FluentFTP Version:** 46.0.2

**Framework:** .NET 7

Config.DownloadRateLimit does not affect DownloadBytes speed/rate. Should limit downloading speed to the set value.

**Logs :**

**Comment by FanDjango** [comment]
I have just now tested this. I can slow down the download of a huge file into byte array, it works.
