### ISSUE TITLE
Error related to PASV with data connection type set to PORT

### ISSUE THREAD

**Issue by mennowo** [robinrodricks/FluentFTP#1255]
**FTP Server OS:** 
Probably unix, maybe Windows

**FTP Server Type:** 
Unknown; it is a very old (20+ years) traffic light controller

**Client Computer OS:**
Unix (Ubuntu 22.04 LTS)

**FluentFTP Version:** 
46.0.2

**Framework:**
.NET 6

After creating an instance of `AsyncFtpClient` I use this code to set the data connection type to PORT:

    Client.Config.DataConnectionType = FtpDataConnectionType.PORT;

However, when then afterwards I call:

    var listing = await Client.GetListing();

I get an exception: 

    unexpected error: Code: 502 Message: PASV command not available|FluentFTP.Exceptions.FtpCommandException: Code: 502 Message: PASV command not available
        at FluentFTP.AsyncFtpClient.GetListingInternal(String listcmd, FtpListOption options, Boolean retry, CancellationToken token)
        at FluentFTP.AsyncFtpClient.GetListing(String path, FtpListOption options, CancellationToken token)

Am I doing this wrong? I'm happy to provide more logging if needed, but thought I'd first simply check if this method to set the data connection type to POST is correct.

**Comment by FanDjango** [comment]
Too bad you did not post the whole log - I would have like to see the result of the FEAT command and also the other stuff that FluentFTP tries to discover about the server.

Generally, I would say that if your server does not support the PASV command, you should not use it. Means: Don't use passive mode, try active mode. Old old server certainly might not support PASV, that's definitely possible. PASV is complicated and made for more sophistication.

Let's see how your server reacts to that? Full log, please.

You are not doing anything wrong. You server is telling you: 502 Message: PASV command not available.

**Comment by FanDjango** [comment]
Ah, ok - that overwrites your settting. You could set it **after** successful connect.

**Comment by FanDjango** [comment]
There are ways to make GetListing(...) work in special cases but with no further information and my crystal ball being cloudy today, I can't help on this. But yes, sometime one even needs to resort to GetNameListing.... Look at the possible settings you can add to GetListing sometime though.
