### ISSUE TITLE
When I delete folder error: don't know how to delete object type: link

### ISSUE THREAD

**Issue by gzj132** [robinrodricks/FluentFTP#1256]
**FTP Server OS:** Unix 

**FTP Server Type:** 

**Client Computer OS:** Windows 

**FluentFTP Version:45.1.0

**Framework:** .net6

![4F950876-AD2B-4F0B-97D0-98C08C13A1AC](https://github.com/robinrodricks/FluentFTP/assets/50973061/2967f6a6-338e-42c8-8b8d-a5927640724e)

**Comment by gzj132** [comment]
I have link file in my folder，What should I do, please

**Comment by robinrodricks** [comment]
Skip objects of type `Link` - check the `Type` property of the `FtpListItem`, or get the path of the link and delete that.
