### ISSUE TITLE
"Ugly hack" for BlueCoat proxy makes pasv connection fail on legitimate use in private network address ranges

### ISSUE THREAD

**Issue by acorchia** [robinrodricks/FluentFTP#1258]
**FTP Server OS:** Unix / Windows / Embedded
Linux but true for any
**FTP Server Type:** Vsftpd / glFTPd / BFTPd / ProFTPD / Pure-FTPd / IBM CS FTP (z/OS, OS/400) / Windows CE / Windows Server IIS / Vax / VMS / OpenVMS / Tandem / HP NonStop
Any
**Client Computer OS:** Windows / Ubuntu / Debian / Linux Mint / Arch Linux
Ubuntu but true for any
**FluentFTP Version:** ?

**Framework:** .NET 2 / 3.5 / 4 / 5 / 6 / 7 / 8 / UWP / Xamarin / Mono
6
<write details about your bug report / feature request here>
In GetPassivePort.cs line 75
			// Fix #409 for BlueCoat proxy connections. This code replaces the name of the proxy with the name of the FTP server and then nothing works.
			if (!IsProxy()) {
				//use host ip if server advertises a non-routable IP
				m = Regex.Match(host, @"(^10\.)|(^172\.1[6-9]\.)|(^172\.2[0-9]\.)|(^172\.3[0-1]\.)|(^192\.168\.)|(^127\.0\.0\.1)|(^0\.0\.0\.0)");

				if (m.Success) {
					host = m_host;
				}

This broke the connection of PASV as the host is not the one returned by the server !
At least enable this hack with a non-defaulted option in the config

```

**Comment by FanDjango** [comment]
Thanks for the friendly report. 

I would greatly appreciate that you provide a nicely documented example of why/how

> This broke the connection of PASV as the host is not the one returned by the server !

so that we can understand the reasoning behind your polite request:

> At least enable this hack with a non-defaulted option in the config

Maybe in between you can also provide feedback on the we did for you in GnuTLS in your other issue, never heard from you again.

**Comment by FanDjango** [comment]
So a legitimate (working correctly) proxy **inside** a (big) internal network.

Allow me to edit the title of the issue. It is an "ugly" hack.

**Comment by FanDjango** [comment]
```cs
if (!IsProxy()) {
//use host ip if server advertises a non-routable IP
m = Regex.Match(host, @"(^10.)|(^172.1[6-9].)|(^172.2[0-9].)|(^172.3[0-1].)|(^192.168.)|(^127.0.0.1)|(^0.0.0.0)");

			if (m.Success) {
				host = m_host;
			}
```
This entire sequence is "ugly". it tries to detect the "server behind NAT" situation and switches to the originally used dnsname-or-ipad. I.e. "if the server responds with a local ipad", we should come in on the original  "outside" dnsname-or-ipad.

This already caused the #409 issue, so the code then was modified to only do this on a non-proxy situation. Which of course didn't change the ugliness of this.

There is a better way, possibly, which is used throughout. Comparing the original ipads type and comparing to the advertised one, slightly more complex but better.

Let me think about it, it would be better than a config.

**Comment by acorchia** [comment]
Sorry English is not my native language. 

 

De : FanDjango ***@***.***> 
Envoyé : mercredi 10 mai 2023 18:09
À : robinrodricks/FluentFTP ***@***.***>
Cc : acorchia ***@***.***>; Author ***@***.***>
Objet : Re: [robinrodricks/FluentFTP] Hugly hack for BlueCoat proxy fail pasv connection (Issue #1258)

 

So a legitimate (working correctly) proxy inside a (big) internal network.

Allow me to edit the title of the issue. It is an "ugly" hack.

**Comment by acorchia** [comment]
Whatever the solution is, I really believe that such action should generate a log.

It’s very very complicate to debug when the ftp log say “Connecting to IP #1= ***:30671” 

The *** does not let you understand the IP rewriting.

Actually Why do you hide that IP ? 

 

Regards

Alain Corchia

 

De : FanDjango ***@***.***> 
Envoyé : mercredi 10 mai 2023 18:34
À : robinrodricks/FluentFTP ***@***.***>
Cc : acorchia ***@***.***>; Author ***@***.***>
Objet : Re: [robinrodricks/FluentFTP] "Ugly hack" for BlueCoat proxy makes pasv connection fail on legitimate use in private network address ranges (Issue #1258)

 

if (!IsProxy()) {
//use host ip if server advertises a non-routable IP
m = Regex.Match(host, @"(^10.)|(^172.1[6-9].)|(^172.2[0-9].)|(^172.3[0-1].)|(^192.168.)|(^127.0.0.1)|(^0.0.0.0)");
 
                       if (m.Success) {
                               host = m_host;
                       }

This entire sequence is "ugly". it tries to detect the "server behind NAT" situation and switches to the originally used dnsname-or-ipad. I.e. "if the server responds with a local ipad", we should come in on the original "outside" dnsname-or-ipad.

This already caused the  <https://github.com/robinrodricks/FluentFTP/issues/409> #409 issue, so the code then was modified to only do this on a non-proxy situation. Which of course didn't change the ugliness of this.

There is a better way, possibly, which is used throughout. Comparing the original ipads type and comparing to the advertised one, slightly more complex but better.

Let me think about it, it would be better than a config.

**Comment by FanDjango** [comment]
> Whatever the solution is, I really believe that such action should generate a log.

I agree with that. It will be done.

> It’s very very complicate to debug when the ftp log say “Connecting to IP [#1](https://github.com/robinrodricks/FluentFTP/pull/1)= ***:30671”
The *** does not let you understand the IP rewriting.
Actually Why do you hide that IP ?

There a config option for logging, to hide user name, to hide password, to hide ipad, in case the user wants that, making the log information more confidential. You can turn clear text on in any combination, if you wish.

I am considering possible solutions, so please be patient about the PR you submitted.

**Comment by acorchia** [comment]
Actually this is not really a proxy.
The customer has a load balancer with a front-end at .20 and 2 actual server at .19 and .18
This is more a question of redondances

Alain Corchia
________________________________

**Comment by FanDjango** [comment]
> Actually this is not really a proxy.

Yes, I corrected my text up above already. It is general problem for FTP PASV which is not solved well in the code.

Current solution makes the wrong assumption that client is coming in from outside a NAT, for example. This is true in **many** cases, but as you can see, not in all cases.

**Comment by FanDjango** [comment]
Using a config option is one popular solution, WinSCP does this for example. Give some more time to investigate other solutions to this. But the log message is of course independant, it is needed.

**Comment by FanDjango** [comment]
```
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (192,168,1,109,176,73). [12ms]
Status:   PASV advertised non-routable IPAD will be force-used (PASVUSE)
Status:   Connecting to IP #1= ***:45129
```

**Comment by FanDjango** [comment]
So thanks for reporting this. I have submitted a suitable PR to improve the PASV behaviour. 

I'd like to make sure that this is seen by @robinrodricks - he might be able to suggest a better acronym than "**PASVUSE**", which is the first one that came to my mind, before merging the PR.
