### ISSUE TITLE
How can i improve the transfer speed when moving files?

### ISSUE THREAD

**Issue by Enriquess** [robinrodricks/FluentFTP#1271]
**FTP Server OS:** Unix

**FTP Server Type:** Pure-FTPd

**Client Computer OS:** Windows 

**FluentFTP Version:** 46.0.2

**Framework:** .NET 7 

<write details about your bug report / feature request here>

In my application, I'm trying to move 400 files from one folder to another. The operation is successful, but it takes approximately 22 seconds to complete. How can I improve this time?

**Comment by FanDjango** [comment]
Compress to single file or stream, size and memory permitting, then transfer by ftp and then trigger decompress on server
