### ISSUE TITLE
Memory leak with .Net Framework 4.6.1 - Windows Server

### ISSUE THREAD

**Issue by haison8x** [robinrodricks/FluentFTP#1276]
**FTP Server OS:** Unix 

**FTP Server Type:**  Pure-FTPd 

**Client Computer OS:** Windows

**FluentFTP Version:** 46.0.2

**Framework:** 4.6.1

I wrote a source code using FluentFTP 46.0.2 to download files from FTP server continuously. It worked fine with .Net 7.0 but there was a memory leak with .Net Framework 4.6.1

Here is the source code:

`

    internal class TestFtp
    {
        private readonly Settings settings;

        internal TestFtp(Settings settings)
        {
            this.settings = settings;
        }

        public void Execute()
        {
            using (var ftpClient = CreateFtpClient())
            {
                TryDownloadFtpDirectory(ftpClient);
            }

            GC.Collect();
        }

        private void TryDownloadFtpDirectory(IFtpClient ftpClient)
        {
            if (Directory.Exists(settings.LocalFolder))
            {
                Directory.Delete(settings.LocalFolder, true);
            }

            Directory.CreateDirectory(settings.LocalFolder);
            ftpClient.DownloadDirectory(settings.LocalFolder, settings.RemoteFolder);
        }

        private FtpClient CreateFtpClient()
        {
            var client = new FtpClient(settings.Host)
            {
                Credentials = new NetworkCredential(settings.Username, settings.Password),
                Port = settings.Port
            };
            client.AutoConnect();

            return client;
        }
    }
`

`
           var controller = new TestFtp(settings);
            while (true)
            {
                controller.Execute();
                Thread.Sleep(1000);
            }
`

It worked well with .Net 7. There was no memory leak, the memory usage snapshot showed that the memory was stable, and the object count was low in the screen Managed Memory

![FluentFtp-Net7-NoMemoryLeak](https://github.com/robinrodricks/FluentFTP/assets/3090475/db1635c6-ed85-4b14-835d-43c98d9130bd)

In contrast, when I built that class with .Net Framework 4.6.1, the memory usage snapshot showed that the memory increased continuously, and the object count in the screen Managed Memory was very high. There was 15k ojbect of ExecutionContext and IPEndPoint

![FluentFtp-Net461-MemoryLeak](https://github.com/robinrodricks/FluentFTP/assets/3090475/1964f1b1-c921-4a7c-83f7-ee9ceac6ad60)

**Logs :** NA

**Comment by haison8x** [comment]
There is no memory leak when using fluentftp with .net framework 4.7.2

**Comment by FanDjango** [comment]
Try to narrow this down a little more.

Make `TryDownload` empty (use Debug target to avoid optimisation):

```cs
		private void TryDownloadFtpDirectory(IFtpClient ftpClient) {
		}
```

so that there is only the connect - disconnect happening.

Still got leak?

I have tried your code (well, similar) and can at this moment find no leak under 4.6.2.

**Comment by haison8x** [comment]
Since FluentFTP doesn't support .net framework 4.6.1 anymore, I decided to upgrade my source code to .net framework 4.7.2 and it worked well

So I will close this issue

**Comment by haison8x** [comment]
https://github.com/robinrodricks/FluentFTP/issues/1276#event-9452503421
