### ISSUE TITLE
Async UploadingBytes that can potential write corrupted data

### ISSUE THREAD

**Issue by paibrahim** [robinrodricks/FluentFTP#1278]
I noticed a few files that became corrupted when I uploaded them to a remote ftp-server.
The stream of bytes was not completely done writing to the ftp-server and therefore sometimes resulted in an incomplete file being stored at the ftp-server where the AsyncFtpClient actually responded with a FtpStatus of Success.

I believe the issue arrive because there is an await keyword missing in row 24 of OpenWrite method file which results in OpenWrite not waiting for the internal OpenWrite method and can result in file not being fully uploaded: https://github.com/robinrodricks/FluentFTP/blob/15184d37a5935b653582da23c9e551ed3d1c6a55/FluentFTP/Client/AsyncClient/OpenWrite.cs#L24

**Comment by FanDjango** [comment]
```cs
//[Obsolete("OpenWriteAsync() is obsolete, please use UploadAsync() or UploadFileAsync() instead", false)]
public virtual Task<Stream> OpenWrite(string path, FtpDataType type = FtpDataType.Binary, bool checkIfFileExists = true, CancellationToken token = default(CancellationToken)) {
		return OpenWrite(path, type, checkIfFileExists ? 0 : -1, token);
}
```

Are you calling this from your code?

**Comment by robinrodricks** [comment]
Closing since no response.
