### ISSUE TITLE
UploadStreamAsync doesn'exists

### ISSUE THREAD

**Issue by LeonardoDaLuz** [robinrodricks/FluentFTP#1279]
UploadStreamAsync doesn'exists. But in documentation says that exists:

https://github.com/robinrodricks/FluentFTP/wiki/Class-FtpClient-Upload

![image](https://github.com/robinrodricks/FluentFTP/assets/80224694/0ac01725-d90a-4fba-8e19-4c401774d7b2)

Version 46.0.2.0
.Net Core 6.0

**Comment by LeonardoDaLuz** [comment]
Really a documentation is incorrect.

And I also didn't even remember that there is an AsyncFtpClient. I'm doing things on the run today, so in my rush I ended up hitting my face against the wall.

**Comment by robinrodricks** [comment]
Done @LeonardoDaLuz, thanks for reporting.

**Comment by robinrodricks** [comment]
Deleted outdated docs that we cannot maintain.

https://github.com/robinrodricks/FluentFTP/wiki/Classes

https://github.com/robinrodricks/FluentFTP/wiki/Enums
