### ISSUE TITLE
FluentFTP.GnuTLS: 32-bit Support

### ISSUE THREAD

**Issue by idblew** [robinrodricks/FluentFTP#1280]
Thanks for a great library!

Is there an ETA for supporting 32-bit with [FluentFTP.GnuTLS](https://github.com/robinrodricks/FluentFTP.GnuTLS)?

We have a legacy system that **must** run as 32-bit due to a very old library it uses, however one FTP server we connect to throws the dreaded "SSL session resume" error which is resolved by switching to the use of GnuTLS.

**Comment by idblew** [comment]
Currently I'm using a workaround that:

- Attempts a call that opens a DATA channel (i.e. GetListing)
- Catches the FTPCommandException  and checks that the CompletionCode is "450"
- Downgrades the connection to plain FTP

Is there better way to be doing this?

**Comment by FanDjango** [comment]
@idblew
Sorry, I needed a moment to re-examine this topic.

Firstly:

> Currently I'm using a workaround that:
>
>Attempts a call that opens a DATA channel (i.e. GetListing)
>Catches the FTPCommandException and checks that the CompletionCode is "450"
>Downgrades the connection to plain FTP
>
>Is there better way to be doing this?

Well, this is already one quite ingenious way to circumvent the "dreaded SSL session resume" problem.

But this is not secure at all, as some servers might actually reject that approach - non-SSL connections would be refused.

Similarly, you might downgrade the SSL version to less than TLS 1.2 - might also be refused, as considered insecure.

> We have a legacy system that must run as 32-bit due to a very old library it uses

Well, you are not saying **on what platform**. If you are talking about linux 32 bit, maybe you and I could put together a viable solution, provided we find the right versions of the needed libraries. If we are talking about windows 32 bit - this is more involved - in this case we need to actually "produce" the 32 bit libraries from source.

> Is there an ETA for supporting 32-bit with [FluentFTP.GnuTLS](https://github.com/robinrodricks/FluentFTP.GnuTLS)?

There is currently no plan at all for supporting any kind of 32-bit GnuTLS wrapper.

This is a help-wanted subject - if you are able to invest time in testing and providing feedback, I would try to get some initial results on linux. Under windows I do not see easy progress right now.

I wonder if some more users would chime in on this?

Note that up to now we have considered 32-bit support to be "unneeded, unattractive, unreasonable, unmodern (sic) and undesirable".  Probably also "un-do-able".

**Comment by FanDjango** [comment]
I have done some more research on this topic and will move this issue over to the FLuentFTP.GnuTLS repo when I am ready to make a final statement towards this topic.
