### ISSUE TITLE
Can not get "Created" property's value which is "FtpListItem" class's property

### ISSUE THREAD

**Issue by GandalfGao** [robinrodricks/FluentFTP#1281]
**FTP Server OS: Windows

**FTP Server Type: Windows Server IIS

**Client Computer OS:** Windows

**FluentFTP Version:**46.0.2 ?

**Framework:** .NET Framework 4.8

Hi, I have a question.  I want to get the created time and modified time of files which are in ftp server. I can get modified time. but I can not get the Created time.  And throw "System.ArgumentOutOfRangeException: is not a valid Win32 FileTime"  So how to resolve the problem? Can you tell me. Thank you.
This is my code:
```
private void SetFileCreatedTimeAndModifiedTime(IEnumerable<FtpListItem> ftpListItems)
{
    try
    {
        foreach (FtpListItem item in ftpListItems)
        {
            DateTime created = item.Created;
            DateTime modified = item.Modified;

            string localFile = Path.Combine(_targetDir, item.Name);
            File.SetCreationTime(localFile, created);
            File.SetLastWriteTime(localFile, modified);
        }
    }
    catch (Exception e)
    {
        throw e;
    }
}
```

**Comment by FanDjango** [comment]
Hi Gandalf!

Need a log here, containing the results of the FEAT command and also the actual way the GetListing was performed and its output.

Modified time is not included in all file listing formats, so... without a log (sigh)... how can we know what is going on?
