### ISSUE TITLE
AsyncFtpClient + await / async blocks application in VM environment

### ISSUE THREAD

**Issue by maxsnts** [robinrodricks/FluentFTP#1284]
**FTP Server OS:** Windows

**FTP Server Type:** Windows Server IIS

**Client Computer OS:** Windows

**FluentFTP Version:** 46.0.2 

Hello. I have a WinForms applications that was working with v34. (XwRemote here on Github)
I thought i would update to 46. 
The only changes i made was change from FtpClient with Async Methods to AsyncFtpClient
Now, the app behaves as if all call are Sync. The interface locks, something that did not happen with v34.

All async call and progress was working correctly in v34, but now all call await on AsyncFtpClient block as if they were sync.
Both GetListing and DownloadFile of AsyncFtpClient are being used as in UploadFileWithProgress.cs.

Since the app worked correctly with FtpClient with Async Methods, i'm not being able to see what the problem is with the use of v46. 

Thank you

**Comment by FanDjango** [comment]
You are targeting 4.6.1. That would be my first check, as that is no longer supported and perhaps quite a few of the conditional compiles in FluentFTP will go awry.

**Comment by maxsnts** [comment]
Hi. 
I'm targeting 4.8 in these tests. That was one of the updates that i was going to do.

**Comment by FanDjango** [comment]
OK, I see.

Is it blocking on the connect? Try to narrow it down.

**Comment by maxsnts** [comment]
I tested these methods
AsyncFtpClient.Connect
AsyncFtpClient.AutoConnect
AsyncFtpClient.GetListing
AsyncFtpClient.DoanloadFile

It did not block previously with
FtpClient.GetListingAsync
FtpClient.DownloadFileAsync

Nothing else was changed (I don't develop much on this tool for lack of time)

Not saying its a problem with FluentFTP, but i since it was the only change (v34 -> v42) and it worked on v34, i am a bit confused why.

Later in the day i will try it in a separate App and see if i get the same behaviour.

Thank you

**Comment by FanDjango** [comment]
Certainly something may be broken, but I would have expected a report much earlier, as many are using async. 

> Later in the day i will try it in a separate App and see if i get the same behaviour.

That's a good approach and I am curious to see the result.

Perhaps concentrate on `FtpClient.DownloadFileAsync` first, as it is easier to create a test that runs nice and long (i.e. download a big file), to better see the blocking behaviour.

**Comment by maxsnts** [comment]
Yeap... I don't know why may app would work correctly with v34 and not with v42, but its not FluentFTP.

I tested on a empty WinForms app and it works fine.
Now i will need to hunt down the reason on XwRemote.

Thanks anyway.

**Comment by FanDjango** [comment]
When you find out more, I am curious to know what it was.

**Comment by maxsnts** [comment]
The plot thickens.
I got home and created a WinForms App EXACLY equal to the one i did previously at work.
This one blocks, the test i did at work did not.

Both are line by line the same.

```
public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private async void button1_Click(object sender, EventArgs e)
        {
            await DownloadFileAsync();
        }

        public async Task DownloadFileAsync()
        {
            var token = new CancellationToken();
            using (var ftp = new AsyncFtpClient("******", "*****", "******"))
            {
                await ftp.AutoConnect(token);

                // define the progress tracking callback
                Progress<FtpProgress> progress = new Progress<FtpProgress>(p => {
                    progressBar1.Value = (int)p.Progress;
                });

                // download a file and ensure the local directory is created
                await ftp.DownloadFile(@"C:\Users\Max\Desktop\bccsentlog.zip", "/bccsentlog.zip", FtpLocalExists.Resume, FtpVerify.None, progress, token);

            }
        }
    }
```
  
I need a fresh look at this with a bit more rest.
Will report back if something interesting is found

**Comment by maxsnts** [comment]
I remoted into the work machine and run the test again.

The only difference is this:
- Home: Its a Windows 11 Virtual Machine
- Work: its a Windows 11 Physical machine

I mostly use this on Virtual machines, with v34 it worked great, now with v46 it blocks on VMs.
It appears that v46 is very demanding from the OS on later versions.

I can0t find any other difference since i run the same test on both machines.

**Comment by maxsnts** [comment]
Something else is afoot. 
I now tested on yet another VM, ir works great.
I will take a closer look in the week end. 
This is getting weird, and i need to find a pattern.

I agree that other people would have reported this is it was something in FluentFTP so it most probable something in my setup, i just can not see what at this point.

**Comment by FanDjango** [comment]
VM No. of CPUs? or try. NET 4.6.2?

**Comment by maxsnts** [comment]
VM where i get this behaviour: 4 x i7 vCPU, 8GB RAM, SSD

I will try to debug using the code instead os the Nuget and see if i can narrow it down.

**Comment by maxsnts** [comment]
Hello

So here is what i found out.
When running the test application with Profiler/Instrumentation the problem does not manifest, that pointed me to the problem being loops that got a little more time to breath because of the profiler injection.
To test this i just added a delay to de loop

![image](https://github.com/robinrodricks/FluentFTP/assets/3869164/d51a2e4e-3ab6-4bd9-a9cf-bb4524e2669d)

Obviously this is not a good solution, it was just for testing, but it makes the problem go away.
The UI no longer locks, but the download takes longer.

The UI locks because the read (and other operations like get listings) while having an await are still running on the UI thread.
Physical machines with more horsepower deal with this, but lower CPU machines (VMs in my case) will show the UI locks.
The solution is to move the operation into another thread, away from the UI.

A simple test encapsulating the while in a Task.Run shows that the UI no longer locks.

![image](https://github.com/robinrodricks/FluentFTP/assets/3869164/f91f0d0c-1a15-4529-8cf0-03028925dc02)

Now, there are two ways to do this: Internally to FluentFTP or on the client application using FluentFTP.

It would be great to have FluentFTP do it and hide that complexity from the users, and all users would benefit from this, but it would have to be done in all methods, including connect and list. 
However this may create some problems on the "ReportProgress" since the code that runs on the app side may not be ready to be called from a different thread. (Cross thread UI updates)

Obviously who i'am i to tell you how it should be done, so i will opt for the second option and move the FluentFTP calls into another thread (away from the UI) on XwRemote code.

Thank you

**Comment by FanDjango** [comment]
Ooof.

Thanks for this evaluation.

It **does** bring up a few questions, though, which you might like to experiment on:

1. It worked previously (.NET 4.6.1, FluentFTP V 34.x.x). The changes were: New FluenFTP, new .NET. **Two changes**. Have you separated these two yet in your testing to any degree? It could be that .NET 4.8 SslStream / SChannel has changed in its requirements of the underlying system?

2. 4 x i7 vCPU VM

Might not be enough, given your overlying application. Have you tested giving this 6 or 8x i7? Of course, this does not explain why it worked before with the old version, see point 1.

I appreciate your information, but somehow the above question number leaves a stale feeling concerning what is really going wrong at this point.

Your solution of putting in the `delay(1)` (minimum realistic delay is of course 20ms, which will kill you performance wise) points to the fact that your system is thread constrained.

The really only open question is: "**What has changed from the old to the new configuration and why?**"

**Comment by maxsnts** [comment]
The delay(1) was not a solution, it was a test. 
I did not test v34 with 4.8 but i will.
As for the VM, well 4 CPUs should be enough FTP. 
Its not "thread constrained", If it can run Visual Studio 2022... it must be able to make an FTP download.

**Comment by FanDjango** [comment]
> The delay(1) was not a solution, it was a test.

Okok, sorry - I am removed by one node from this problem at the moment, I was not saying it was a solution in any way. I should have used the term "test". But I saw what you were trying to discover.

> I did not test v34 with 4.8 but i will.

And also the other combination, perhaps. Very curious to see the results here.

> As for the VM, well 4 CPUs should be enough for FTP.
Its not "thread constrained", If it can run Visual Studio 2022... it must be able to make an FTP download.

That depends. But actually, just like you, I would have expected a newer release of (_whatever_) to work better with constraints. But there is a certain feeling that constraints might be aggravating this szenario. Please, let's keep an open mind towards the actual problem.

It seems that **you can reproduce it**.  This means we can worry this problem for **weeks and weeks until we find it**, given patience and some discipline. If you are ready to keep on with this, steadily and as time permits for us both.

Let us remember: It happens only in certain environments. Why? How? Due to what? These questions are actually still open, despite your discoveries.

And I myself am absolutely clueless, by the way.

**Comment by maxsnts** [comment]
I will eventually try to port my app to .net 5+, but i will see if i can find why this is happening before that.

The Repo does not have a Tag for v34, so i will decompile it and see if i can get to some conclusion that way.

I will have 2 week vacation soon, but i doubt coding and debug will be high on the ToDo list during that time.

Thank you

**Comment by FanDjango** [comment]
Enjoy the vacation, we will pick this up after, if you are willing.

**Comment by wibblemonkey** [comment]
@FanDjango
I am evaluating this library for use in an application and I noticed this issue, which struck a chord with my observation that the `await`s in the asynchronous client implementation don't have `.ConfigureAwait(false)` appended, which is considered best practice for async calls in libraries.
Do you know if there's a specific reason for the omission?

**Comment by FanDjango** [comment]
@wibblemonkey 
I am sorry to say that I do not have sufficient C# expertise to answer your question.

My research on this, prompted by your question, shows that you definitely have a point - in that `.ConfigureAwait(false)` should be used in libraries - these methods typically not needing (better: not supposed) to preserve any GUI or whatever else context.

There are some other issues also pertaining to the completeness of the ASYNC implementation of FluenFTPs clients (missing token usage, handling of prematurely aborted tasks as well as this issue here).

> Do you know if there's a specific reason for the omission?

No, I don't **know**. But, also, I don't **believe** there actually is a specific reason at this point in time.

The approach to this, currently, would be to investigate issues such as this one here, try to fix it and grow onwards from there. So your noticing this issue: Do you also **actually have this issue**, can we test if it is resolved by, for example, `.ConfigureAwait(false)`? Perhaps @maxsnts, since he can actually reproduce a problem in a specific scenario, can collaborate.

> I am evaluating this library for use in an application

That's nice, does you evaluation **actually** get hit by an issue with a locking situation on/due to AsyncFtpCLient or are you worried that this **could be the case**, just curious. We don't get to many reports about ASYNC problems anymore, but who knows...

**Comment by maxsnts** [comment]
Hi
My life post vacation have been a bit busy.
Don't close the issue, i will try to help as soon as work allows.
Thank you

**Comment by angelru** [comment]
Hello, can this be related to my comment?
https://github.com/robinrodricks/FluentFTP/issues/1325#issuecomment-1716972548

**Comment by FanDjango** [comment]
Bump
