### ISSUE TITLE
Upload/Download error response when file name has spaces

### ISSUE THREAD

**Issue by RajasekarPR1991** [robinrodricks/FluentFTP#1295]
Using below code, I have tried to upload it to ftp server and it seems like the file has been uploaded successfully as expected, but I have getting error response as 550 - No such File 

Fluent FTP Version : 47.0.0

Code : 

```cs
var rpath = "//20230721/4629864/ORIGINAL/sample_640×426 6.bmp";
var lpath = "C:\\FileFormats\\sample_640×426 3.bmp";
using var con = new FtpClient(host, username, passwd);
con.Connect();
con.Config.LogToConsole = true;
var status = con.UploadFile(lpath, rpath, FtpRemoteExists.Overwrite,true, FtpVerify.Retry);
```

And also additionally, the file has been uploaded with replacement of space with plus sign. Not sure how it works like this. 

Do the needful as soon as possible please.

**Comment by robinrodricks** [comment]
> Do the needful as soon as possible please.

No, we are not a corporate support team and you are not paying any money for this product.

If we have time we will look into this but you have no right to demand anything.

**Comment by robinrodricks** [comment]
Add the full logs. See docs on how to do that.

**Comment by robinrodricks** [comment]
Your ticket is not clear, you cannot download the file or is the file uploaded with a different name?

**Comment by RajasekarPR1991** [comment]
@robinrodricks 

If the file name has spaces, getting 550 error as response when tried with below code 

var status = con.UploadFile(lpath, rpath, FtpRemoteExists.Overwrite,true, FtpVerify.Retry);

Error : FtpcommandException 550 : //20230721/4629864/ORIGINAL/sample_640×426: No such file

**Comment by robinrodricks** [comment]
So send a raw command using `client.Execute` and add quotes around the filename or try something. Each server has a different syntax.

**Comment by robinrodricks** [comment]
You have still not attached full logs so I cannot tell which server it is.

**Comment by FanDjango** [comment]
> XMD5 /20230721/4629973/ORIGINAL/04-test-create 2.png

The command `XMD5` needs the file in quotes or not containing blanks. Different servers will handle this correctly or not. Its that simple.
