### ISSUE TITLE
When directory with  spaces then DELETEDirectory\EMPTY Directory\GetListing is not working and throwing error

### ISSUE THREAD

**Issue by Venkatakrishna-bvk** [robinrodricks/FluentFTP#1309]
When directory contains  **empty spaces** then DELETEDirectory\EMPTY Directory\GetListing is not working and throwing error "Code:501 Message inavlid number of arguments MSD /non-prod-ftp/bvk/test/2023_Venkat Krishna Street"
Input remote Directory : "2023_Venkat Krishna Street".

I kindly request your assistance in providing a resolution for this matter.

**Comment by robinrodricks** [comment]
What does "empty spaces" mean? You mean spaces in the middle of the path?

**Comment by Venkatakrishna-bvk** [comment]
Apologies, it's my mistake.
Yes , spaces in middle of folder/Directory path. 
Input remote Directory : "/nonprodftp/bvk/**2023_Venkat Krishna Street**".

**Comment by Venkatakrishna-bvk** [comment]
@robinrodricks ,
When I used FtpListOption.ForceList, the GetFtpList function successfully retrieved details of the current directory, even when **the directory name contained spaces**. However, when attempting to enable the recursive functionality using FtpListOption.Recursive alone, it failed to handle spaces in the directory name. To address this problem, I resolved it by passing both options together as **FtpListOption.ForceList | FtpListOption.Recursive**. This combination allowed me to achieve the desired recursive functionality without any issues related to spaces in the directory name.
Kindly inform me if you believe this could  lead to any problems.

I hope sharing this solution might be helpful to others who encounter similar space-related issues when using GetFtpList, DeleteDirectory, or EmptyDirectory.

**Comment by FanDjango** [comment]
This is all very well, but it is highly dependant on the server being accessed. The usefulness of your "solution" would profit from telling us what server you are accessing.

A verbose log of your solution or at least some more information would be a good thing.

**Comment by Venkatakrishna-bvk** [comment]
using this ftp server WS_FTP PRO (IP SWITCH)
<img width="313" alt="image" src="https://github.com/robinrodricks/FluentFTP/assets/30506328/7346c949-ecf0-4daf-90a1-1e53aa22e02d">

**Comment by FanDjango** [comment]
> A verbose log of your solution or at least some more information would be a good thing.

I meant a log of the entire process, verbose. Not a printout of the exception text.

Anyway, your idea of using `FtpListOption.ForceList | FtpListOption.Recursive` is certainly ok, but there are more ways to skin a cat and I would have liked to see what **exactly** goes wrong when you do not use ForceList.

So I would still like to see a log.

**Comment by Venkatakrishna-bvk** [comment]
**LOGS: Hoping thislogs  might helpful** 

Hello, FTP!
# Connect(False)
Status:   FluentFTP 47.0.0.0(.NET 6.0)
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220 ftp.server.biz X2 WS_FTP Server 8.6.1(52152005) [738739.533d]
Status:   Detected FTP server: WSFTP
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Enter password [49ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230 User logged in [299ms]
Command:  FEAT
Status:   Waiting for response to: FEAT
Response: 211-Extensions supported
Response: SIZE
Response: XMD5
Response: XSHA1
Response: XSHA256
Response: XSHA512
Response: XQUOTA
Response: LANG EN, ES, FR, GE
Response: MDTM
Response: MLST size*;type*;perm*;create*;modify*;
Response: REST STREAM
Response: TVFS
Response: UTF8
Response: AUTH SSL;TLS-P;
Response: PBSZ
Response: PROT C;P;
Response: 211 end [45ms]
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Status:   Waiting for response to: OPTS UTF8 ON
Response: 200 Command OPTS succeed [42ms]
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 UNIX [43ms]
Status:   Listing parser set to: Machine
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/users/FTP-Server" is current directory [43ms]

# SetWorkingDirectory("/non-prod-ftp")
Command:  CWD /non-prod-ftp
Status:   Waiting for response to: CWD /non-prod-ftp
Response: 250 Command CWD succeed [146ms]
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/non-prod-ftp" is current directory [49ms]

# DirectoryExists("WebsiteTestFiles/dev/invoices-staging/bvk/20230808_007_City and state of bvk")
Command:  CWD WebsiteTestFiles/dev/invoices-staging/bvk/20230808_007_City and state of bvk
Status:   Waiting for response to: CWD WebsiteTestFiles/dev/invoices-staging/bvk/20230808_007_City and state of bvk
Response: 250 Command CWD succeed [59ms]
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/non-prod-ftp/WebsiteTestFiles/dev/invoices-staging/bvk/20230808_007_City and state of bvk" is current directory [47ms]
Command:  CWD /non-prod-ftp
Status:   Waiting for response to: CWD /non-prod-ftp
Response: 250 Command CWD succeed [48ms]
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/non-prod-ftp" is current directory [43ms]
Is DirectoryExists : True

# GetListing("WebsiteTestFiles/dev/invoices-staging/bvk/20230808_007_City and state of bvk", Auto)
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Transfer mode set to BINARY [43ms]

# OpenDataStream("MLSD /non-prod-ftp/WebsiteTestFiles/dev/invoices-staging/bvk/20230808_007_City and state of bvk", 0)

# OpenPassiveDataStream(AutoPassive, "MLSD /non-prod-ftp/WebsiteTestFiles/dev/invoices-staging/bvk/20230808_007_City and state of bvk", 0)
Command:  EPSV
Status:   Waiting for response to: EPSV
Response: 500 Unknown command EPSV [42ms]

# OpenPassiveDataStream(PASV, "MLSD /non-prod-ftp/WebsiteTestFiles/dev/invoices-staging/bvk/20230808_007_City and state of bvk", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (10,10,13,36,200,247). [46ms]
Status:   PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
Status:   Connecting to IP #1= ***:51447
Command:  MLSD /non-prod-ftp/WebsiteTestFiles/dev/invoices-staging/bvk/20230808_007_City and state of bvk
Status:   Waiting for response to: MLSD /non-prod-ftp/WebsiteTestFiles/dev/invoices-staging/bvk/20230808_007_City and state of bvk
Response: 501 Invalid number of arguments MLSD /non-prod-ftp/WebsiteTestFiles/dev/invoices-staging/bvk/20230808_007_City and state of bvk [44ms]
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Status:   Waiting for response to: QUIT
Response: 221 bye [43ms]
Status:   Closing/Disposing FtpSocketStream(control connection)
Status:   Closing/Disposing FtpSocketStream(control connection)
FTP Error: FluentFTP.Exceptions.FtpCommandException: Code: 501 Message: Invalid number of arguments MLSD /non-prod-ftp/WebsiteTestFiles/dev/invoices-staging/bvk/20230808_007_City and state of bvk
   at FluentFTP.FtpClient.GetListingInternal(String listcmd, FtpListOption options, Boolean retry)
   at FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
   at FTPService.Connect() in C:\Users\BVK11007\source\repos\FTP_Demo\FTP_Demo\FTPService.cs:line 153
bye

**Comment by FanDjango** [comment]
Anyway, with Path problems containing blanks, you should always **first** try all possible quoting options, i.e. enclosing your strings in double quotes and also you should examine the verbose log to see better what the FluentFTP client is entering to the FTP server, and also the detailed response.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango,
I am grateful for your swift reply. 
Thank you again for your great support.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango ,

I am facing issue with upload directory with spaces in directory

my code is 
```
string rootpath = @"/non-prod-ftp";

//working fine with below directory as directory with no spaces
         //string dirPath = @"\non-prod-ftp\WebsiteTestFiles\dev\invoices-staging\bvk\20230811_101_City_and_County_of_D7";

//not working with belwo directory as direcorty having spaces
	   string dirPath = @"\non-prod-ftp\WebsiteTestFiles\dev\invoices-staging\bvk\20230811_101 City and County of D7";


 using var ftpClient = new AsyncFtpClient(ftpServer, username, password);
		  ftpClient.Config.LogToConsole = true;
		  await ftpClient.Connect();
		  await ftpClient.SetWorkingDirectory(rootpath);
var ftpResult = await ftpClient.UploadDirectory(localDirPath, dirPath, mode: FtpFolderSyncMode.Update, existsMode: FtpRemoteExists.Overwrite, verifyOptions: FtpVerify.Retry).ConfigureAwait(false);
 Console.WriteLine("FTP operations completed successfully.");
		  
```

**Attached logs**
**first time execution:  Didnot throw exceptions  but showing errors** 
[upload_working.txt](https://github.com/robinrodricks/FluentFTP/files/12322475/upload_working.txt)

**second  time execution : no change in code but throwing exception .** 
[upload_notworking.txt](https://github.com/robinrodricks/FluentFTP/files/12322480/upload_notworking.txt)


**Please provide solution for the above scenerio upload directory with empty spaces.**

**Comment by FanDjango** [comment]
@Venkatakrishna-bvk This should be a new issue.

Can you open it as a new issue and call it **"UploadDirectory" calls GetListing MLSD with spaces in FilePath causing error**
