### ISSUE TITLE
UploadFile does not create the directory even if createDir is true

### ISSUE THREAD

**Issue by mushzinho** [robinrodricks/FluentFTP#132]
Hello, everyone, I would like to report some unexpected behavior while I was trying to Upload a file.
I have this configuration: client.UploadFile(@url, "/carro/cata.mp3", FtpExists.Overwrite, true);
If I use FtpExists.Overwrite it will generate an error if "carro" directory does not exists, while the expected to me, since creating the directory is true, It's the creation of "carro" directory and then the normal upload of the file or If the directory and file exist, just overwrite it.

**Comment by hgupta9** [comment]
I'm trying to solve this but I need the logs. Can you enable tracing (see the FAQ) and paste the logs here so we can check?

**Comment by mushzinho** [comment]
@hgupta9  You can reproduce this easily, just try to upload a file with that configuration

**Comment by hgupta9** [comment]
It works on my end. Upload your logs if you want any further help.

**Comment by robinrodricks** [comment]
Unless you upload your logs there is no way to debug this. Closing it until you do.
