### ISSUE TITLE
Follow .NET Standard, not obvious how to use the library.

### ISSUE THREAD

**Issue by jsgoupil** [robinrodricks/FluentFTP#1320]
Currently, I'm on version 47.1.0.

I would not expect to have to read so much documentation to make this work, nor doing 10 trials and errors to download 1 file.

Since this library is followed by a lot of people and probably the de-facto library for FTP communication, maybe it would be great if it followed .NET standard? But this is probably a bigger discussion if the authors want to do so because it would be quite the breaking change.

 * Don't have an Async / Sync class. Use the same class.
 * awaitable methods should be Async suffixed.
 * Avoid ambiguity on your methods. Doing `asyncFtpClient.DownloadBytes(url);` will pick up 2 ambiguous methods.
 * Have the `CancellationToken` on the last argument, not in the middle.
 * `out var` are usually at the end, not at the beginning.
 * Provide a parser to download quickly a full URL `ftp://username:password@host/file.png` without having to do the whole dance of parsing this `Uri` myself. This would align with `HttpClient` where you can do `httpClient.GetByteArrayAsync(requestUri)`
 * `Please call Connect() before trying to read the Capabilities!` I think you could auto connect for me.
 * `501 Message: Invalid number of parameters` I have to call the correct constructor based on my username and password situation. I shouldn't have to do that.

Something that should be 1 line ends up to be this:
```
var path = new Uri(url);
var userInfo = path.UserInfo.Split(':');
var username = userInfo.Length > 0 ? userInfo[0] : string.Empty;
var password = userInfo.Length > 1 ? userInfo[1] : string.Empty;
var ftpClient = new AsyncFtpClient(path.Host, path.Port);

// Need a different constructor call otherwise we get 501 from the server.
if (!string.IsNullOrEmpty(username) || !string.IsNullOrEmpty(password))
{
    ftpClient = new AsyncFtpClient(path.Host, username, password, path.Port);
}

await ftpClient.AutoConnect();
return await ftpClient.DownloadBytes(path.PathAndQuery, CancellationToken.None);
```

**Comment by FanDjango** [comment]
> `Please call Connect() before trying to read the Capabilities!`  ??? => I think you could auto connect for me.

I would like to have more details on how this exception came to be triggered. I am curious as to the how you are causing this to happen.

> `501 Message: Invalid number of parameters`. I have to call the correct constructor based on my username and password situation. I shouldn't have to do that.

Here also, more details on how this happens would be helpful. This 501 was a response to what command?

Why do I need to laboriously try to reproduce what I think you were doing when you have the logs available?

Given your rep, I would have expected better docs on your issues and less rant.

> Provide a parser to download quickly a full URL ftp://username:password@host/file.png without having to do the whole dance of parsing this Uri myself. This would align with HttpClient where you can do httpClient.GetByteArrayAsync(requestUri)

Sounds like a nice little new API function that could be provided. I wonder if you have not more or less written it already, so why not submit it as a PR?

**Comment by jsgoupil** [comment]
The exception about capabilities is happening when I call download without auto connect, like mentioned above.

The 501 happens if you use the username password constructor but leave them empty, like mentioned above.

I am sorry you think I'm ranting and not providing enough documentation. I believe I provided the reasons and what should happen for each point in a polite manner.

I have provided the code I wrote to support my scenario. There is nothing laborious about reproducing since I gave you everything I have. You're welcome to use it to improve your library.

**Comment by FanDjango** [comment]
Must be a language problem then. 

**Why would you download without connecting first?** It seems obvious that the processing needed to be done in order to do a download (such as interogating the servers capabilites) cannot proceed if you do not connect successfully first.

> The 501 happens if you use the username password constructor but leave them empty

Ah so. So now I must try this too, and look at the log to find out what command is failing. Thanks. I will go and try that right away.

>  like mentioned above.

I don't really see it, but if you say so.

> The 501 happens if you use the username password constructor but leave them empty

**Why would you use the username and password constructor and leave them empty**? You are supposed to provide these so that a connect can be performed, which needs to enter a userid and password physically to the ftp server, which probably complains because you are causing a "USER" command to be entered to the FTP server with no user as a parameter, which of course provokes an angry reply - 501.... - which is a failure.

If you use `HttpClient`, what happens when you use `ftp://:@host/file.png`? i.e. username and password empty?

**Comment by jsgoupil** [comment]
Ok. I wish you the best with your library.

**Comment by FanDjango** [comment]
Here is what happens when userid and password is not provided. I just set them to string.Empty as a demonstration.

If you just use the constructor with only port, you need to provide the userid and the password separately into the credentials **before** you attempt a connect.

If you want to attempt a downlload, you need to connect first.

Nuff said.

```
ftpClient = new AsyncFtpClient(path.Host, string.empty, string.empty, path.Port);
}

await ftpClient.AutoConnect();
```

```
Response: 220-FileZilla Server 0.9.60 beta
Response: 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
Response: 220 Please visit https://filezilla-project.org/ [738763,868d]
Status:   Detected FTP server: FileZilla
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 234 Using authentication type TLS [3ms]
Status:   GnuTLS: 0   FluentFTP.GnuTLS 1.0.21.0(Win32NT/.NET 6.0) / GnuTLS 3.8.0
'Test_FluentZOS_Net_6.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.21\System.Security.Cryptography.Primitives.dll'. 
Status:   FTPS authentication successful, lib = FluentFTP.GnuTLS.GnuTlsStream, cipher suite = (TLS1.2)-(ECDHE-SECP256R1)-(ECDSA-SHA256)-(AES-256-GCM) [124ms]
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 501 Syntax error [9ms]
Exception thrown: 'FluentFTP.Exceptions.FtpAuthenticationException' in FluentFTP.dll
```

**Comment by jsgoupil** [comment]
Wow, you guys went on full attack :( it's unfortunate. I thought I could help you out and provide some information about how to make your library even better than it is. I don't think my bug report was such nonsense.

I will leave you with some information so you can decide in time if you want to improve your library in the future.

* Async suffix on methods: https://learn.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap?redirectedfrom=MSDN#naming-parameters-and-return-types
* Usage of the same class rather than 2: This one, I don't have an exact document from Microsoft but it's uncommon to have 2 classes because your library is called `FtpClient`, usually people don't think to type `Async` on a constructor.
* Avoiding ambiguous calls: the unfortunate part here is that we need to add `(CancellationToken)` cast to select the correct path. I would argue that we should avoid casting in general, but choosing the correct method by casting is just unfortunate.
* CancellationToken should be the last parameter: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1068
* I have to call connect: this one is your design decision, and you guys saying you *cannot* is a strong word, where I said "you could" for the reason that I don't have to call SYN/ACK to my HTTP calls either. If auto connecting is frown upon, maybe it would be great to pass in a `FtpClientOptions` which could contain `AutoConnect`. Personally, I would prefer it to be `true`.
* Having to have an `if` in my code to pick the correct constructor is a bit annoying. In your code, you could check for the `string.IsNullOrEmpty` for the `user` or `password` or make these 2 nullable on your constructor so I can call only 1 constructor. I don't think the username is allowed to be empty on the FTP level.
