### ISSUE TITLE
About Concurrency issue in FtpClient

### ISSUE THREAD

**Issue by orcfnjmlns908** [robinrodricks/FluentFTP#1325]
**FTP Server OS:** Debian

**FTP Server Type:** Vsftpd 

**Client Computer OS:** Windows

**FluentFTP Version:** ? 47.1.0

**Framework:** .NET 6 

using FluentFTP;
using System.Collections.Generic;
using System.Threading.Tasks;

FtpClient client = new FtpClient(host, username, password);
await client.ConnectAsync();

var remotePaths = new List<string> { remotePath1, remotePath2 }; // 添加你要下载的所有远程路径
var localPaths = new List<string> { localPath1, localPath2 };    // 添加相应的本地路径

await Parallel.ForEachAsync(remotePaths, async (remotePath, cancellationToken) =>
{
    var index = remotePaths.IndexOf(remotePath);
    var localPath = localPaths[index];
    await client.DownloadFileAsync(localPath, remotePath);
});

Does it can work？

**Comment by FanDjango** [comment]
Move the
```cs
FtpClient client = new FtpClient(host, username, password);
await client.ConnectAsync();
```
down into the Parallel.FOrEach, then it should work.

**Comment by angelru** [comment]
Hello,

I comment on my case to see if it has anything to do with it. I have a class to manage our ftp using AsyncFtpClient and AutoConnect with DownloadBytes (all asynchronous).

In our api, I register this class as Scoped. When simultaneously testing calls to our API, we have received some random errors that the connection to the ftp could not be made or certain files did not exist in the ftp (if they exist).

Does it have something to do with it? Are there any undetected errors? my implementation is not correct?

**Comment by FanDjango** [comment]
@angelru 

> Does it have something to do with it?

> Are there any undetected errors?

> my implementation is not correct?

Open a new issue and provide full documentation. Do not hijcack this issue.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango , Does AsyncFtpClient supports Parallell Programming (i.e Parallel.ForEach) and 
Multiple Asynchrnous( i.e Task.WhenAll)? Could you please confirm when you are free.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango, I tried parallel Programing (ActionBlock) in .net 6  to upload files (around 2000)  with fluentftp which worked fine.

**Comment by FanDjango** [comment]
To all:

Parallel programming FluentFTP ( and FluentFTP.GnuTLS ) (aka multithreading) **works** -

### IF and only if

**Each FTP process (or thread) instantiates its own FTP-Client object.**

There are limits set by memory of the client machine, of course. Also limits as to the amount of TCP connections you can initiate on your client machine, as well as performance issues.

Such an FTP Client object can then sequentially operate against **a server**, independantly of other FTP-Client objects.

**Note:** - a server, though, might have a configured limit of concurrent connections that it cannot (or will not) exceed.

### How to program parallelism

ActionBlock, etc. are just syntactic sugar that help you set up multithreading (there are various other methods). 

The important point is that _threadstart_ will "construct" a new FTP client, which then **needs to connect**, i.e. use a connection of its own.

Conversely, what **does not work in FTP** is to **use an existing connection** (i.e. a single client) and then expect this single client to somehow **magically** do a number of parallel operations. No way that will work.

**Comment by FanDjango** [comment]
There is **one important** note on this though:

**Depending on the server type**, using "ASYNC" **and** more than one thread **with** SslStream can cause session resume problems.

Solution: Use FluentFTP.GnuTls.
