### ISSUE TITLE
Unzip file in FTP server

### ISSUE THREAD

**Issue by Venkatakrishna-bvk** [robinrodricks/FluentFTP#1344]
**FTP Server OS:** Windows

**FTP Server Type:** WSFTP Pro server

**Client Computer OS:** Windows / Linux

**FluentFTP Version:** 47.1.0

**Framework:** .NET 6

I have a few doubts about a specific task.
My requirement is to unzip files on an FTP server, especially for files with large sizes. Instead of downloading them to the local server, extracting them, and then uploading them to the target directory, I've taken a different approach. I've created a custom SITE command called "UNZIP" in the WSFTP server and configured a .ps1 script to execute the unzip operation.

The issue arises when I attempt to execute this custom command using FluentFTP, like this: ftpClient.Execute("SITE UNZIP param1 param2"). Unfortunately, I'm encountering a "Command SITE error: failed" message. However, when I try just "UNZIP param1 param2," an "unknown UNZIP command" error is displayed.

I'm seeking guidance on whether this approach is viable or if there's another approach that would work better.
Could you please guide me.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango

**Comment by FanDjango** [comment]
@Venkatakrishna-bvk 

You have created a custom `SITE` command for the WsFTP Pro server to provide an internal server side UNZIP function.

First of all, that is a **great idea !**

Certainly, `SITE UNZIP p1 p2` is the **correct** way to invoke this command.

The reply you get, "Command SITE error: failed", would be easier to diagnose if there were a detailed verbose log of the command and the response. You need to provide that. You might also need to check the log of WsFTP Pro for error messages that it provides re. this command.

There are numerous things that may be going wrong: file permissions for your .ps1 script on the server side comes to mind, for example.

Get more information, please.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango ,  Please let me know if any solution to fix below issue.

**LOGS:**
Hello, FTP!
Command:  SITE UNZIP
Status:   Waiting for response to: SITE UNZIP

```
Dispose()
Status:   Disposing FtpClient object...
Status:   Closing/Disposing FtpSocketStream(control connection)
"System.TimeoutException: The operation has timed out.\r\n   at FluentFTP.AsyncFtpClient.GetReplyAsyncInternal(CancellationToken token, String command, Boolean exhaustNoop, Int32 timeOut)\r\n   at FluentFTP.AsyncFtpClient.GetReplyAsyncInternal(CancellationToken token, String command)\r\n   at FluentFTP.AsyncFtpClient.Execute(String command, CancellationToken token)\r\n   at FTP_Demo.UnZipTest.UnZip() in D:\\BVK\\FTP_Demo\\FTP_Demo\\UnZip.cs:line 39" 
```


**Platform OS: Windows
WSFTP Server logs:**
ftp-server	SITE	UNZIP	Information	221	Informational	SITE command succeeded: UNZIP	
ftp-server	SITE	UNZIP	Network Error	0	Error	The specified executable is not a valid application for this OS platform., at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) at System.Diagnostics.Process.Start() at SSHServerAPI.Transport.FTPTransport.HandleSite(ArrayList lstArg) at SSHServerAPI.Transport.FTPTransport.ProcessCommand() at SSHServerAPI.Transport.FTPTransport.ProcessCommand(Byte[] data, Int32 nLen) at SSHServerAPI.Transport.FTPTransport._OnRecvCommand(IAsyncResult ar)

Sample implementation of UNZIP with out sending params for testing now. 
if worked without params then will try with params later.

**Code:**
```using var asyncFtpClient = new AsyncFtpClient(ftpServer, username, password);
await asyncFtpClient.Connect();
asyncFtpClient.Config.LogToConsole = true;
string siteCommand = $"SITE UNZIP";
var ftpReply = await asyncFtpClient.Execute(siteCommand, CancellationToken.None).ConfigureAwait(false); 
```


**UnzipNoParams.ps1:**
```
Expand-Archive -Path "E:\bvk\unziptest.zip" -DestinationPath "E:\bvk\" -Force
Write-Output "Successfully unzipped"
```

**Site Command configured in WSFTP server:**
Command: UNZIP
Executable: E:\unzipfolder\UnzipNoParams.ps1

**Comment by FanDjango** [comment]
This seems to indicate the nature of the problem:

> ftp-server SITE UNZIP Information 221 Informational SITE command succeeded: UNZIP
ftp-server SITE UNZIP Network Error 0 Error The specified executable is not a valid application for this OS

WsFTP will try to "execute" the specified command and I think it is expecting an ".exe" executable and not a .ps1 script (which is not an executable).

Try executing "CMD.exe -C E:\unzipfolder\UnzipNoParams.ps1".

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango, It didn't work .
Placed at Executable in Wsftp server  with  "CMD.exe -C E:\unzipfolder\UnzipNoParams.ps1" but it didn't unzip file.

**Comment by FanDjango** [comment]
> It didn't work

Well, perhaps you should first try with "innocuous" commands first, like a simple one that does something you can identify immediatly as having worked.

Try creating a custom SITE command that takes NO parameters and that will simply execute "TEST.ps1", and that should just create a file "TEST.TXT".

Practice how to get that to work and go forward from there.

I know nothing about WsFTP Server, but 

> The specified executable is not a valid application for this OS

is pretty indicative that the WsFTP Server is trying to execute the command you sent with SITE UNZIP but it is not happy with the format.

**Comment by FanDjango** [comment]
If they alway refer to "executable", I suppose you must run a "SHELL" that then takes the script as a parameter. Perhaps CMD.exe (which is MS-DOS) is not the right Shell to execute a .ps1?

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango  , Thank you very much for your assistance.
Now, It's working fine with bat file. ( powershell.exe with .ps1 path ). 
**Response: Successfully unzipped**
I will try with UNZIP including parameters now. Thank you once again.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango , In WSFTP Server , I have configured bat file with parameters.
 When I'm passing input params as  Drive path ("E:\nonprod\staging") to the Execute SITE Command with fluent ftp, It is working fine but not with VirtualPaths. What should be done to bind virtual paths in WSFTP Server instead of Drive path params. Please let me know if any idea.
