### ISSUE TITLE
UploadDirectory with FtpNavigate.Conditional causing path issue and not uploading files 

### ISSUE THREAD

**Issue by Venkatakrishna-bvk** [robinrodricks/FluentFTP#1345]
**FTP Server OS:** Windows 

**FTP Server Type:** WSFTP Server

**Client Computer OS:** Windows /Linux

**FluentFTP Version:**  48.0.0

**Framework:** .NET 6

**Logs :**

Upload directory is not working as expected.
Creating directories working fine but uploading files are failed. 
After seeing logs came to know virtual path names getting occured twice. PFA.
VirtualPath : "\\virtual-path-name" or "\virtual-path-name"  tried both ways but didn't work for upload files.
my remote path contains spaces with virtual path i.e \virtualpathname\stagingfolder\...
```
 using IAsyncFtpClient asyncFtpClient = new AsyncFtpClient(ftpServer, username, password);
 await asyncFtpClient.Connect();
 await asyncFtpClient.SetWorkingDirectory(remotePath);
 asyncFtpClient.Config.LogToConsole = true;
 asyncFtpClient.Config.Navigate = FtpNavigate.Conditional;
 var result = await asyncFtpClient.UploadDirectory(resourcesDirFullPath, remoteFullPath, mode: FtpFolderSyncMode.Update, existsMode: FtpRemoteExists.Overwrite, verifyOptions: FtpVerify.Retry, token: CancellationToken.None).ConfigureAwait(false);
 ```  
[uploaddirlogs.txt](https://github.com/robinrodricks/FluentFTP/files/12776250/uploaddirlogs.txt)

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango  , Path contains spaces so updated with Config.Navigate = FtpNavigate.Conditional;

**Comment by FanDjango** [comment]
@Venkatakrishna-bvk ...studying log file

**Comment by FanDjango** [comment]
Ok, I have identified the problem. Now proceeding with fixing it...

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango, could you please notify me once the fixed version is accessible? So that , I can integrate my work with that specific release. Thank you.

**Comment by FanDjango** [comment]
@Venkatakrishna-bvk 

Can you aid me by testing this fix if I merge? With a confirmation I can justify asking for a bugfix Nuget release.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango, 
Certainly, I will conduct testing and provide you with feedback based on the latest master branch.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango , I have conducted testing, and the path issues have been resolved. It's now functioning as expected without any issues.
Upload directory (files uploading but displaying  failing response and not supporting XMD5 command):
The upload directory was causing errors (501 Invalid number of arguments XMD5) on my WSFTP server, but when running with the upload file and upload stream are now functioning as expected. There are no errors, as confirmed by the logs.

If the upload file/upload stream is functioning correctly without errors, the upload directory should behave the same way. Unfortunately, it's not currently exhibiting the same behavior.

Could you please resolve this issue.

[uploadDir_48.0.0_fixcommitlogs.txt](https://github.com/robinrodricks/FluentFTP/files/12831411/uploadDir_48.0.0_fixcommitlogs.txt)

[uploadFile_48.0.0_fixcommitlogs.txt](https://github.com/robinrodricks/FluentFTP/files/12831413/uploadFile_48.0.0_fixcommitlogs.txt)

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango, please notify me once the fixed version is available.

**Comment by FanDjango** [comment]
@Venkatakrishna-bvk 

Please open a new issue for this "separate issue not related to it", call it **"Autonavigate feature should also work for GetCheckSum"** and include the log file there.

Meanwhile I will investigate this.

**Comment by robinrodricks** [comment]
Should I release?

**Comment by FanDjango** [comment]
48.0.1 as bugfix. I would not mind. I don't know if there won't be more coming though, Venta is quite prolific in testing this feature but prefers nugets to test with.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango , 
I have taken latest from master and tested it.
Upload directory working fine but not upload file . Attached logs for both upload directory and file. PFA. 
As upload file is failing (twice virtual paths are appended) , Could you please look into it.

[uploadDir_master_fix_checksum.txt](https://github.com/robinrodricks/FluentFTP/files/12868138/uploadDir_master_fix_checksum.txt)

[upload_file_master.txt](https://github.com/robinrodricks/FluentFTP/files/12868140/upload_file_master.txt)

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango , **Upload file issue not fixed.** 
1.If create directory true then before creating directory we are setting working directory which throws error. 
2.Path with backward slash (\) appending twice but not with forward slash('/') .
 Issue is at GetAbsolutePath(). So like upload directory which calling upload file with replacing  forward slash('/') . In the same way I'm calling GetFtpPath() first as shown in below code which might be helpful to you.

**As shown in screenshot: 45 line fixes 1st issue and 37 line fixes 2nd issue**

**Here is the solution which worked for me.**

![image](https://github.com/robinrodricks/FluentFTP/assets/30506328/102d3024-8d0c-49cd-b516-c1f609f9ef0a)

**PFA** Upload file logs- Success

[bvk_uploadfile_fix_logs.txt](https://github.com/robinrodricks/FluentFTP/files/12870375/bvk_uploadfile_fix_logs.txt)

**The above code works fine for me. So please check once.**

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango , 

**Here is the solution for directorypath with backward slash ("\\") appending twice to the path**

Method : GetAbsolutePathAsync / GetAbsolutePath

![image](https://github.com/robinrodricks/FluentFTP/assets/30506328/2031aea2-30e8-4be6-b941-156f05d9954a)

```
var normalizedParentPath = pwd;
var normalizedSubPath = path.GetFtpPath();

if (normalizedParentPath.StartsWith(normalizedSubPath, StringComparison.OrdinalIgnoreCase)) {
    path = path.GetFtpPath();
}
else {
    path = (pwd + "/" + path).GetFtpPath();
}
```

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango  , **The code mentioned above is working fine for me.**

**Comment by robinrodricks** [comment]
Released.

https://www.nuget.org/packages/FluentFTP/48.0.1

**Comment by FanDjango** [comment]
Gimme some time to consolidate and check status - we have a slight overlap on progress here now.

@Venkatakrishna-bvk I see the problem. Working on it...

**Comment by FanDjango** [comment]
Ok, 

> 1.If create directory true then before creating directory we are setting working directory which throws error.

I agree with that problem - I will fix that.

> 2.Path with backward slash () appending twice but not with forward slash('/') .

I don't understand how (at that exact code point) you are working on a path with backward slashes.

The problem is (actually: it **was**) that `Path.GetDirectoryName(temp)` will replace "/" by "\\" (thank you Microsoft) and these need to be changed back to "/".

We need to approach this step by step, as your logs and documentation are confusing (me).

Sadly, I have no server available that does not understand blanks in filepaths for some commands.

For example, I can see in your log that you are explicitly calling `FileExists("/nonprod-vp/staging/dev/invoices/bvk test city/1kbtestfile.txt")` and it uses the SIZE command. This command fails. So maybe we should also CWD AutoNavigate for that command as well.

**Comment by FanDjango** [comment]
> 2.Path with backward slash () appending twice but not with forward slash('/')

Your fix works, but you are "fixing the symptom of the error". The error happens earlier.

I need you do a single "UploadFile(...)" with **no other code** and send me the log - best to also provide the (short) source code, _be sure to use the current master, as I have tried to fix some problems that you have reported.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango ,  Upload file failed. Hoping below code, logs, screenshots, solutions might be helpful.

**Logs:**

[uploadfile_failed_logs.txt](https://github.com/robinrodricks/FluentFTP/files/12884887/uploadfile_failed_logs.txt)

**Code:**
```
    public async Task UploadFile()
    {
         remotePath = @"\NonProdVirtualPath";
         stagingPath = @"\NonProdVirtualPath\Staging\dev\invoices";
        var remoteFilePath = Path.Combine(stagingPath, @"bvk test city", "1kbtestfile.txt");

        using IAsyncFtpClient asyncFtpClient = new AsyncFtpClient(ftpServer, username, password);
        await asyncFtpClient.Connect();
        await asyncFtpClient.SetWorkingDirectory(remotePath);//
        asyncFtpClient.Config.LogToConsole = true;
        asyncFtpClient.Config.Navigate = FtpNavigate.Conditional;
        string localpath = @"D:\BackUp\FTP_Demo\FTP_Demo\Resources\20230815_101_City and bvkdownload1\1KB.txt";

        try
        {
            var ftpStatus = await asyncFtpClient.UploadFile(localpath, remoteFilePath, existsMode: FtpRemoteExists.Overwrite, createRemoteDir: true).ConfigureAwait(false);
            if (ftpStatus == FtpStatus.Success)
                await Console.Out.WriteLineAsync("upload success.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($" \n \n File {remoteFilePath} uploaded falied. {ex?.ToString()}");
        }

    }
```
**Issue occurring at GetAbsolutePathAsync method:**
Call before GetAbsolutePathAsync method , 
See remote path value

![image](https://github.com/robinrodricks/FluentFTP/assets/30506328/40accf94-8a08-4124-a948-48c34d774545)

Inside GetAbsolutePathsAsync method
![image](https://github.com/robinrodricks/FluentFTP/assets/30506328/dce5c9fa-3da2-4e59-8c52-57d1f73b2a5c)

![image](https://github.com/robinrodricks/FluentFTP/assets/30506328/315721e6-0cb6-45c7-a055-9469f5bc4702)

![image](https://github.com/robinrodricks/FluentFTP/assets/30506328/316234d1-84f4-4c9f-a429-3ca1bd66619b)

Solution: two ways can be solved 

1. One way : calling remotepath = remotepath.GetFtpPath before GetAbsolutePath method. this is just bypassing GetAbsolutePath method else if condition.
2. Second way : 

![image](https://github.com/robinrodricks/FluentFTP/assets/30506328/2cb1c556-b67c-4949-91a6-ec2c8a61616b)

**Comment by FanDjango** [comment]
Ok. Need to find out how come the "\\" are in there, in the remotePath. You can remove them in `GetAbsolutePath(...)`, I know. But where do they come from. Investigating....

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango  , Also in upload file there is another issue while create directory before calling settingworking directory .
**In line no  47 : it should be remoteDir but not remotePath as shown in screenshot.**
![image](https://github.com/robinrodricks/FluentFTP/assets/30506328/fa25b222-4cd2-41bb-bfa9-3e39cff6b27c)

**Comment by FanDjango** [comment]
I will fix that right away...

**Comment by FanDjango** [comment]
You should use

`var remoteFilePath = Path.Combine(stagingPath, @"bvk test city", "1kbtestfile.txt").Replace("\\","/");`

**Comment by FanDjango** [comment]
It could be discussed that we might need to "sanitize" paths that are input to the FluentFTP APIs, but single blackslashes are not really expected.

**Comment by Venkatakrishna-bvk** [comment]
> It could be discussed that we might need to "sanitize" paths that are input to the FluentFTP APIs, but single blackslashes are not really expected.
```
Actually i'm using single backslash('\')  with verbatim (@)
Example 1 :  stagingPath = @"\NonProdVirtualPath\Staging\dev\invoices";
Example 2 :  stagingPath = "\\NonProdVirtualPath\\Staging\\dev\\invoices";

Both examples same with verbatim(@) we get exact string . If no verbatim then single backward slash is escape character so we give two slashes \\.
```
Hoping issue is not with single slash when having verbatim (@) or double backward slashes. 

If I replace backward with forward slashes . it will work for me . 
But just letting you know  to support in library also this issues will get fixed in upload file  if you add that one line remotePath = remotePath.GetFtpPath() which replaces slashes only before calling GetAbsolutePath. 

Upload directory is working fine because remotePath.GetFtpPath() is called before calling upload file.

**Comment by FanDjango** [comment]
Yes, I know. And it can be reproduced. I get the same (incorrect) behaviour.

> If I replace backward with forward slashes . it will work for me .

Right. **So for deity's sake, correct your filename strings.**

***
**If you prefer to hard-code the directory separator character, you should use the forward slash ( / ) character. _It is the only recognized directory separator character on Unix systems_. By the way, it is the AltDirectorySeparatorChar on Windows.**

The backslash is a **valid character** for a Unix filename, and **it is not a path separator**.

Example: `/home/venkata/test/my\strange\file.text` 

The path is `/home/venkata/test`. The filename is `my\strange\file.text`.

I will not make such a code change. Code the path correctly. You need to make the transition between Windows and Unix filepaths watertight on your side.

> Upload directory is working fine because remotePath.GetFtpPath() is called before calling upload file.

Yes. It is part of the needed logic in UploadDirectory. This is not needed in UploadFile. So it is just a coincidence.

**Comment by Venkatakrishna-bvk** [comment]
> By the way:
> 
> ```
> # FileExists("/nonprod-vp/staging/dev/invoices/bvk test city/1kbtestfile.txt")
> Command:  SIZE /nonprod-vp/staging/dev/invoices/bvk test city/1kbtestfile.txt
> Status:   Waiting for response to: SIZE /nonprod-vp/staging/dev/invoices/bvk test city/1kbtestfile.txt
> Response: 550 Command SIZE failed [100ms]
> 
> # FileExists("1kbtestfile.txt")
> Command:  SIZE /nonprod-vp/staging/dev/invoices/bvk test city/1kbtestfile.txt
> Status:   Waiting for response to: SIZE /nonprod-vp/staging/dev/invoices/bvk test city/1kbtestfile.txt
> Response: 550 File /nonprod-vp/staging/dev/invoices/bvk test city/1kbtestfile.txt not found [96ms]
> ```
> 
> It seems to me, that the `SIZE` command (and possibly also `MDTM` and other commands also don't like blanks in the file names on your WSFTPd server. Can you verify?


```
                var ftpStatus = await asyncFtpClient.UploadFile(localpath, remoteFilePath, existsMode: FtpRemoteExists.Overwrite, createRemoteDir: true).ConfigureAwait(false);
```

I have tested with above mentioned code with latest master branch for   Path with spaces and without spaces.
**Upload file working fine** with latest master branch after replacing slashes.

**SIZE not found with and without spaces in path . Please view logs.**

**1. Path with spaces:** 

**1.1 Upload file without existing file**

**Logs:**
[Uploadfile_WithoutExistingFile_Logs.txt](https://github.com/robinrodricks/FluentFTP/files/12885996/Uploadfile_WithoutExistingFile_Logs.txt)

**Server Logs:**
![image](https://github.com/robinrodricks/FluentFTP/assets/30506328/a026ab9e-464c-4170-a5ce-217da9e4d9a8)


**1.2 upload file with already existing file**

**Logs:**
[Uploadfile_WithExistingFile_Logs.txt](https://github.com/robinrodricks/FluentFTP/files/12886002/Uploadfile_WithExistingFile_Logs.txt)


**Server Logs:**
![image](https://github.com/robinrodricks/FluentFTP/assets/30506328/2da512a0-666d-4aa9-a657-e063f822598b)


**2. Path without spaces**

**upload file without existing file
Logs:**

[UploadFile_withoutspaces.txt](https://github.com/robinrodricks/FluentFTP/files/12886072/UploadFile_withoutspaces.txt)

Server Logs:

![image](https://github.com/robinrodricks/FluentFTP/assets/30506328/a71f5e9f-c0d1-4582-804a-f040da61f840)

**Comment by FanDjango** [comment]
>  I am using WSFTP Server on windows OS but app runs on Linux\windows OS

Oh, I am so sorry - I forgot that, you posted it up at the top.

I think then, that WSFTP server is perhaps actually allowing the "\" and interpreting it as a directory separator. My bad. But - if FluentFTP "recognizes" it to be a Unix type server, things will not go right. 

I think some of the path / filename logic needs to be fixed up a little bit sometime.

I will look at the SIZE logs...

**Comment by FanDjango** [comment]
So can we close?

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango,Upload file is working fine.  yes we can close this ticket.
 Also please check logs once.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango , Please notify me once the fixed version is available with the latest master.

**Comment by FanDjango** [comment]
@Venkatakrishna-bvk Release 48.0.3
