### ISSUE TITLE
Autonavigate feature should also work for GetCheckSum

### ISSUE THREAD

**Issue by Venkatakrishna-bvk** [robinrodricks/FluentFTP#1348]
FTP Server OS: Windows

FTP Server Type: WSFTP Server

Client Computer OS: Windows /Linux

FluentFTP Version: 48.0.0

Framework: .NET 6

**Logs :**
Upload directory (files uploading but displaying failing response and not supporting XMD5 command):
The upload directory was causing errors (501 Invalid number of arguments XMD5) on my WSFTP server, but when running with the upload file and upload stream are now functioning as expected. There are no errors, as confirmed by the logs.

If the upload file/upload stream is functioning correctly without errors, the upload directory should behave the same way. Unfortunately, it's not currently exhibiting the same behavior.

Could you please resolve this issue.

[uploadDir_48.0.0_fixcommitlogs.txt](https://github.com/robinrodricks/FluentFTP/files/12831411/uploadDir_48.0.0_fixcommitlogs.txt)

[uploadFile_48.0.0_fixcommitlogs.txt](https://github.com/robinrodricks/FluentFTP/files/12831413/uploadFile_48.0.0_fixcommitlogs.txt)

**Comment by FanDjango** [comment]
@Venkatakrishna-bvk Please test this also before we consider releasing it as Nuget

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango, I will test  and let you know today.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango, https://github.com/robinrodricks/FluentFTP/issues/1345#issuecomment-1757340325
