### ISSUE TITLE
Regarding  Site Command with Virtual Paths

### ISSUE THREAD

**Issue by Venkatakrishna-bvk** [robinrodricks/FluentFTP#1354]
FTP Server OS: Windows

FTP Server Type: WSFTP Pro server

Client Computer OS: Windows / Linux

FluentFTP Version: 47.1.0

Framework: .NET 6

I have some questions regarding a particular task associated with the continuation of this ticket.
https://github.com/robinrodricks/FluentFTP/issues/1344#issuecomment-1741363345

In WSFTP Server, I've set up a batch file with parameters. When I provide input parameters as a drive path ("E:\nonprod\staging") to the Execute SITE Command using Fluent FTP, it works correctly with the drive path ("E:\nonprod\staging"), but not with virtual paths (\nonprodvirtualPath). What steps should be taken to associate virtual paths with SITE COMMANDs in WSFTP Server instead of using drive paths as input parameters?
I would be grateful for your input regarding this matter.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango , Please let me know if any idea about it.

**Comment by FanDjango** [comment]
Hmmm, that is a difficult question to answer for someone (me) who has no idea of how WSFTP server implements virtual paths.

I do have a suspicion though: Your "special custom" SITE command, which calls the batch file, is just a "transport" for the command text. In that SITE command -> Batch file execution sequence, WSFTP does not look at the parameters, it knows nothing about their meaning.

You could solve this problem, perhaps, by **duplicating** the virtual path definitions you have configured in WSFTP server also in the beginning lines of your batch program, using a list of IF statements like so: `IF parm2 == /nonprodvirtualpath THEN parm2 = "E:\nonprod/staging"`.

I repeat: It means **duplicating** the information about the relationship in two places.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango,
I executed a custom site command to run a PowerShell file. In this process, I receive responses of either 200 or 500 from the PowerShell file after execution which is expected . It works quickly for smaller files and returned the responses mentioned ps file, but when it comes to unzipping large files, it takes a significant amount of time and doesn't provide any response for those time-consuming operations from powershell file. I get ftpreply related to SITE command but not about unzip response from ps file. This is happening large zip file around 100 MB but not with smaller 10MB around.
Could you please let me know what might be the issue or which should be changed in fluent ftp configuration.

FleuntFTP Version : 47.1.0
code:
```
_ftpClient.Config.ReadTimeout = 60000; //increased to 60 secs from default 15 secs

```

**Comment by FanDjango** [comment]
Sigh. A log snippet would have told me the answer to **these** questions:

_What happened after the SITE command? No response? Connection lost?_

The idea of increasing the ReadTimeout is one possibility. Perhaps first: **Exactly how long do these SITE commands take?** It might be that 60 seconds is not enough.

Also, I would increase the timeout **directly before** the SITE command and then go back to the default after the SITE command.

If even the control connection is lost, perhaps you should enable NOOPs before the SITE command? I am not sure this would work, because I don't know how WsFTP server processes the SITE command, probably not, because it might be a single threaded process on the control connection thread.

Another "very dastardly trick" would be to have one SITE command starting a task (service) that will do the UNZIP, another SITE command to query if the task is completed (and get its response, say from an output file). You could then start the UNZIP and loop around using the second SITE command to check when finished.

**Comment by Venkatakrishna-bvk** [comment]
@FanDjango, Initially when i execute site command to unzip for Large Files and it failed due to site command took 35secs.  
LOGS:
[SITE_FAILED_LOG.txt](https://github.com/robinrodricks/FluentFTP/files/13031953/SITE_FAILED_LOG.txt)

I have increased ReadTimeout to 60secs  then Site command is successful as shown in below log file. 
Is there any problem if i don't switch to default  ReadTimeout and  and if i set Readtimeout to 60 secs while performing other ftp operations(upload/create dir) with same instance/object?
it would be advantageous right if i increase because to avoid errors for other long running operations?

[SITE_SUCCESS_LARGEFILESIZE_LOG.txt](https://github.com/robinrodricks/FluentFTP/files/13031954/SITE_SUCCESS_LARGEFILESIZE_LOG.txt)

For smaller files it displays messages retrieved from a powershell file response 
**such as custom message  "Success: " & 200** as shown in belowe logs but it is not showing for large files as shown in above logs

[SITE_SUCCESS_SMALLFILESIZE_LOG.txt](https://github.com/robinrodricks/FluentFTP/files/13031955/SITE_SUCCESS_SMALLFILESIZE_LOG.txt)

**Comment by FanDjango** [comment]
Thanks for the logs.

I can see that NOOP would not help, it seems the SITE command is synchronous in the WSFTP control connection.

The reason I would advise re-setting the timeout config AFTER a SITE command, is that whenever **OTHER** failures should be detected, the session would be "hanging" for a real long time before the error is reported. You really **only** want such a large timeout on actions where you **know** this is not a problem.

**Comment by Venkatakrishna-bvk** [comment]
> Sigh. A log snippet would have told me the answer to **these** questions:
> 
> _What happened after the SITE command? No response? Connection lost?_
> 
> The idea of increasing the ReadTimeout is one possibility. Perhaps first: **Exactly how long do these SITE commands take?** It might be that 60 seconds is not enough.
> 
> Also, I would increase the timeout **directly before** the SITE command and then go back to the default after the SITE command.
> 
> If even the control connection is lost, perhaps you should enable NOOPs before the SITE command? I am not sure this would work, because I don't know how WsFTP server processes the SITE command, probably not, because it might be a single threaded process on the control connection thread.
> 
> Another "very dastardly trick" would be to have one SITE command starting a task (service) that will do the UNZIP, another SITE command to query if the task is completed (and get its response, say from an output file). You could then start the UNZIP and loop around using the second SITE command to check when finished.

yes last point is valid approach to check whether task completed or not.
But after execution of powershell returns response 200  with same  site command call.
Here what to be  implemented second site command to check unzip site completed ?
Could you please provide more clearly so that i can give a try ?

**Comment by FanDjango** [comment]
Or maybe this: https://stackoverflow.com/questions/649634/how-do-i-run-a-bat-file-in-the-background-from-another-bat-file
