### ISSUE TITLE
FullName returns wrong filename

### ISSUE THREAD

**Issue by GeertVanhaute** [robinrodricks/FluentFTP#1355]
**FTP Server OS:** Unix 

**FTP Server Type:** Vsftpd 
**Client Computer OS:** Windows 

**FluentFTP Version:** 48.01

**Framework:** .NET Framework 4.8

This is the code:
(remoteFilePath is a path including a filename)

        Using ftp As New FtpClient(ftpHost, ftpUsername, ftpPassword)
            ftp.Connect()

            ftp.Config.DownloadDataType = FtpDataType.Binary
            ftp.Config.DataConnectionType = FtpDataConnectionType.PASV
            ftp.Encoding = System.Text.Encoding.UTF8
            ftp.Config.LogToConsole = True
            Dim remotePathOnly As String = Path.GetDirectoryName(remoteFilePath)
            ftp.SetWorkingDirectory(remotePathOnly)

            ' Get the listing of files in the remote directory
            Dim listing As List(Of FtpListItem) = ftp.GetListing(remoteFilePath).ToList()

            ' Delete each file
            For Each item As FtpListItem In listing
                ftp.DeleteFile(item.FullName) '(remotePathOnly & '/' & item.Name) 'item.FullName is not correct
                fileList.Add(item.Name)
            Next
        End Using

item.FullName contains remotefilename/filename (thus twice the filename)

**Logs :**

```
# SetWorkingDirectory("/isip/isi/var/out/xpl_bbn_renewal/CDC")
Command:  CWD /isip/isi/var/out/xpl_bbn_renewal/CDC
Status:   Waiting for response to: CWD /isip/isi/var/out/xpl_bbn_renewal/CDC
Response: 250 Directory successfully changed. [13ms]
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/isip/dump/out/xpl_bbn_renewal/CDC" is the current directory [14ms]

# GetListing("/isip/isi/var/out/xpl_bbn_renewal/CDC/FTP_test_321.txt", Auto)
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Switching to Binary mode. [17ms]

# OpenDataStream("LIST /isip/isi/var/out/xpl_bbn_renewal/CDC/FTP_test_321.txt", 0)

# OpenPassiveDataStream(PASV, "LIST /isip/isi/var/out/xpl_bbn_renewal/CDC/FTP_test_321.txt", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (10,61,107,205,135,91). [14ms]
Status:   PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
Status:   Connecting to IP #1= ***:34651
Command:  LIST /isip/isi/var/out/xpl_bbn_renewal/CDC/FTP_test_321.txt
Status:   Waiting for response to: LIST /isip/isi/var/out/xpl_bbn_renewal/CDC/FTP_test_321.txt
Response: 150 Here comes the directory listing. [17ms]
+---------------------------------------+
Listing:  -rw-r--r--    1 974441   974441         45 Oct 17 09:55 FTP_test_321.txt
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: LIST /isip/isi/var/out/xpl_bbn_renewal/CDC/FTP_test_321.txt
Response: 226 Directory send OK. [26ms]
Status:   Closing/Disposing FtpSocketStream(data connection)
Status:   Confirmed format Unix

# DeleteFile("/isip/isi/var/out/xpl_bbn_renewal/CDC/FTP_test_321.txt/FTP_test_321.txt")
Status:   Testing connectivity using Socket.Poll()...
Command:  DELE /isip/isi/var/out/xpl_bbn_renewal/CDC/FTP_test_321.txt/FTP_test_321.txt
Status:   Waiting for response to: DELE /isip/isi/var/out/xpl_bbn_renewal/CDC/FTP_test_321.txt/FTP_test_321.txt
Response: 550 Delete operation failed. [14ms]
Exception thrown: 'FluentFTP.Exceptions.FtpCommandException' in FluentFTP.dll
```

**Comment by FanDjango** [comment]
This is a bug and I can reproduce it.

It is because you are passing a **complete** path+filename to `GetListing(...)`.

`GetListing("/isip/isi/var/out/xpl_bbn_renewal/CDC/FTP_test_321.txt", Auto)`

Most people will use `GetListing(...)` to list a folder and not a single file.

`GetListing("/isip/isi/var/out/xpl_bbn_renewal/CDC", Auto)`

This produces a list, one item of which will contain the information for `FTP_text_321.txt`, with a correct fullname.

For now, that would be a workaround for you.
