### ISSUE TITLE
DownloadStream?

### ISSUE THREAD

**Issue by anbuzz** [robinrodricks/FluentFTP#1357]
FTP Server OS: Unix / Windows

net6.0

The problem I encountered was that when I read data from the server in a streaming manner, it did not follow the start and end I gave. Instead, it returns the data for the entire file.

using (MemoryStream memoryStream = new MemoryStream()) {
await ftp.DownloadStream(memoryStream, "/video/food.mkv", restartPosition: 0, stopPosition: 1024 * 1024 * 2);
byte[] videoData = memoryStream.ToArray();
Console.WriteLine("memoryStream:" + videoData.Length);

}

**Comment by FanDjango** [comment]
FluentFTP Version?
FluentFTP verbose log of this process?
Occurs always with any kind of file? Or only once? or only with this file?

My crystal ball is foggy.... cannot help you.

**Comment by anbuzz** [comment]
> FluentFTP Version? FluentFTP verbose log of this process? Occurs always with any kind of file? Or only once? or only with this file? File size?
> 
> My crystal ball is foggy.... cannot help you.

The latest source code open source. I'm making this modification here. I'm not sure if it's correct or if it will cause compatibility issues.
![image](https://github.com/robinrodricks/FluentFTP/assets/11937214/231c47f8-a786-4965-be56-aad6fa38a748)

**Comment by FanDjango** [comment]
Oh. What is the purpose, in your thinking, of this code change?

Normally, that is supposed to be:
```cs
						// if we reach here means EOF encountered
						// stop if we are in "read until EOF" mode
						if (offset == fileLen || readToEnd) {
							break;
						}
```

Seems like a very very destructive change. If you do not make this change, do you still have a problem?
