### ISSUE TITLE
In FileZilla Server, when the number of files in a folder exceeds 50,000, using GetListing() to obtain FtpListItem[] results in a count of 0.

### ISSUE THREAD

**Issue by luy710** [robinrodricks/FluentFTP#1359]
In FileZilla Server, when the number of files in a folder exceeds 50,000, using GetListing() to obtain FtpListItem[] results in a count of 0.

**Comment by FanDjango** [comment]
Works fine for me, for a count of 66,000, for example.

![image](https://github.com/robinrodricks/FluentFTP/assets/51046875/8201829b-1967-4cef-ae3c-e174179c00ed)

With no further details or logs, which listing command was being used, did the list succeed or did it fail midway, **how on earth** can you expect any kind of help on this?

**Comment by luy710** [comment]
The default timeout duration, the connection has timed out, this issue is resolved.
