### ISSUE TITLE
 During the process of synchronizing directories using UploadDirectory, if a directory gets deleted, an exception will be thrown immediately, causing termination.

### ISSUE THREAD

**Issue by luy710** [robinrodricks/FluentFTP#1364]
During the process of synchronizing directories using UploadDirectory, if a directory gets deleted, an exception will be thrown immediately, causing termination.

**Comment by FanDjango** [comment]
Does it?
Details? Logs? Under which circumstances?

**Comment by luy710** [comment]
Throw a File Not Found exception, it can be caught using catch.
RecordFileToUpload()
catch (FileNotFoundException e)
            {
                ftpResult.IsFailed = true;
                ftpResult.Exception = e;
                results.Add(ftpResult);
                logger.LogError($"未找到文件:{e.Message}");
            }
