### ISSUE TITLE
When there are many files in the server folder,upfiles very slow. 

### ISSUE THREAD

**Issue by luy710** [robinrodricks/FluentFTP#1367]
FileExists->GetNameListing-> OpenDataStream("NLST " + path, 0L); When there are many files in the server folder, it significantly affects the upload speed. Is there any consideration for optimization?

**Comment by FanDjango** [comment]
Make sure that MSLD is used. Check if FEAT shows MLSD is supported. Show logs of why NLST is being used for FileExists instead of NLST.

Logs!

**Comment by FanDjango** [comment]
We merged a fix for this into master. Can you give some feedback?
