### ISSUE TITLE
System.TimeoutException: Timed out trying to read data from the socket stream!

### ISSUE THREAD

**Issue by crocket01** [robinrodricks/FluentFTP#1373]
**FTP Server OS:LINUX Centos

**FTP Server Type:  vsftpd 2.0.8 or later

**Client Computer OS:Windows Server 2019 Datacenter

**FluentFTP Version:19.2.2

**Framework:** .NET 4.5 / 4.6 / 4.8

<write details about your bug report / feature request here>
FileSystemProvider.ProcessInvoice() - Error:
FluentFTP.FtpException: Error while uploading the file to the server. See InnerException for more info. ---> System.TimeoutException: Timed out trying to read data from the socket stream!
   in FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   in FluentFTP.FtpSocketStream.ReadLine(Encoding encoding)
   in FluentFTP.FtpClient.GetReply()
   in FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress)
   --- Fine della traccia dello stack dell'eccezione interna ---
   in FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress)
   in FluentFTP.FtpClient.Upload(Stream fileStream, String remotePath, FtpExists existsMode, Boolean createRemoteDir, IProgress`1 progress)

Currently fluentftp connects to ftp on port 21, without encryption.
Do you have any solution to solve the problem?
Thank you

```

<paste VERBOSE logs here>

```

**Comment by robinrodricks** [comment]
As I said in the other ticket, we will not debug old versions. Update to latest and if the issue still occurs, we will look into it.
