### ISSUE TITLE
.NET 7 - Could not load file or assembly 'FluentFTP, Version=48.0.3.0

### ISSUE THREAD

**Issue by inct-wp-001** [robinrodricks/FluentFTP#1374]
**FTP Server OS:** N/A

**FTP Server Type:** N/A

**Client Computer OS:** Windows 11

**FluentFTP Version:** 48.0.3 (Also tested all versions since 47.0)

**Framework:** .NET 7

FluentFTP is a dependency of a class library i am working on.
When i call a method that instantiates FtpClient, it explodes telling me:

`System.IO.FileNotFoundException: 'Could not load file or assembly 'FluentFTP, Version=48.0.3.0, Culture=neutral, PublicKeyToken=f4af092b1d8df44f'. The system cannot find the file specified.
`

Am i doing something wrong? Is FluentFTP incompatible with .NET 7?
I'm happy to provide any information that might help to understand how to solve this.

I've seen suggested and added the following to csproj but it didn't fix it.
```
	<ItemGroup>
		<FunctionsPreservedDependencies Include="FluentFTP.dll" />
	</ItemGroup>
```

**Logs :**

N/A

Edited to clarify the Windows version.
Edited to correct the FunctionsPreservedDependencies reference

**Comment by robinrodricks** [comment]
Add an explicit nuget reference to that version of FluentFTP and see if it solves it.

**Comment by inct-wp-001** [comment]
Do you mean this?
```
  <ItemGroup>
    <PackageReference Include="FluentFTP" Version="48.0.3" />
  </ItemGroup>

```

**Comment by robinrodricks** [comment]
Can you upload here a zip file of a project that reproduces this problem? Can be any console app with your configs.

**Comment by inct-wp-001** [comment]
Yes, I think so. Wil try to do it over the weekend and upload it here.

**Comment by robinrodricks** [comment]
I guess that solves it then?

**Comment by inct-wp-001** [comment]
Yes, it's solved.
Thanks.
