### ISSUE TITLE
Connect to active mode FTP server in docker with specific IP

### ISSUE THREAD

**Issue by tonyjonson8748** [robinrodricks/FluentFTP#1376]
**FTP Server OS:** Embedded（RT-Thread RTOS）

**FTP Server Type:** Another

**Client Computer OS:** Debian(Docker)

**FluentFTP Version:** 48.0.3

**Framework:** .NET 7(Asp.net core)

"I've encountered a problem where my FTP service does not have a passive mode, only an active mode is available. Moreover, my ASP.NET Core program needs to be deployed in Docker, and I cannot use the host network (--net=host). When I use AsyncFtpClient to retrieve the server directory list, the packet capture tool Wireshark shows that it sends PORT 172,17,0,2,230,120, which uses the internal IP of the container. Therefore, my question is, does FtpClient have any configuration class that allows setting the IP for active mode (so that I can set it to the Docker host machine’s IP, thereby mapping it into the container)?"

<img width="1386" alt="image" src="https://github.com/robinrodricks/FluentFTP/assets/149042087/93e44272-ea5e-4750-9550-8727ed3ec3c7">
<img width="1090" alt="image" src="https://github.com/robinrodricks/FluentFTP/assets/149042087/91741d8c-1118-41c5-ae34-ead6e8f305ee">

**Comment by robinrodricks** [comment]
I think this needs an enhancement to Active FTP connections.

**Comment by FanDjango** [comment]
Please correct me if I am wrong, but for the `EPRT` and `PORT` commands, the IP address that this emits is derived from `GetLocalAddress(...)`, which in turn already supports this:
```cs
			// Use resolver
			if (Config.AddressResolver != null) {
				return m_Address ?? (m_Address = Config.AddressResolver());
			}
```
by referencing the `Config` parameter
```cs
		public Func<string> AddressResolver { get; set; }

		/// <summary>
		/// Ports used for Active Data Connection.
		/// Useful when your FTP server has certain ports that are blocked or used for other purposes.
		/// </summary>
```
Use this callback by supplying a delegate function that returns simply the needed IP address to be sent out in the respective PORT command.

You can find this right in the same place in `Config`, where the desired active port range can be defined.

**Comment by tonyjonson8748** [comment]
> Please correct me if I am wrong, but for the `EPRT` and `PORT` commands, the IP address that this emits is derived from `GetLocalAddress(...)`, which in turn already supports this:
> 
> ```cs
> 			// Use resolver
> 			if (Config.AddressResolver != null) {
> 				return m_Address ?? (m_Address = Config.AddressResolver());
> 			}
> ```
> 
> by referencing the `Config` parameter
> 
> ```cs
> 		/// <summary>
> 		/// Delegate used for resolving local address, used for active data connections
> 		/// This can be used in case you're behind a router, but port forwarding is configured to forward the
> 		/// ports from your router to your internal IP. In that case, we need to send the router's IP instead of our internal IP.
> 		/// </summary>
> 		public Func<string> AddressResolver { get; set; }
> ```
> 
> Use this callback by supplying a delegate function that returns simply the needed IP address to be sent out in the respective PORT command.
> 
> You can find this right in the same place in `Config`, where the desired active port range can be defined.

This is the perfect solution to my problem. Thank you
