### ISSUE TITLE
Latest FTPClient not having many classes with the older versions

### ISSUE THREAD

**Issue by sathyajith77** [robinrodricks/FluentFTP#1383]
Am getting the below errors when updated to the latest FluentFTP (48.0.3)

- The type or namespace name 'ProxyInfo' could not be found (are you missing a using directive or an assembly reference?)	
- The type or namespace name 'FtpClientHttp11Proxy' could not be found (are you missing a using directive or an assembly reference?)
- 'FtpClient' does not contain a definition for 'DataConnectionType' and no accessible extension method 'DataConnectionType' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)
- 'FtpClient' does not contain a definition for 'DataConnectionType' and no accessible extension method 'DataConnectionType' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)
- 'FtpClient' does not contain a definition for 'TransferChunkSize' and no accessible extension method 'TransferChunkSize' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)
- 'FtpClient' does not contain a definition for 'SocketKeepAlive' and no accessible extension method 'SocketKeepAlive' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)
- 'FtpClient' does not contain a definition for 'SocketPollInterval' and no accessible extension method 'SocketPollInterval' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)
- 'FtpClient' does not contain a definition for 'SslProtocols' and no accessible extension method 'SslProtocols' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)
- 'FtpClient' does not contain a definition for 'EncryptionMode' and no accessible extension method 'EncryptionMode' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)
- 'FtpClient' does not contain a definition for 'ClientCertificates' and no accessible extension method 'ClientCertificates' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)
- 'FtpClient' does not contain a definition for 'DataConnectionEncryption' and no accessible extension method 'DataConnectionEncryption' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)
- 'FtpClient' does not contain a definition for 'SslProtocols' and no accessible extension method 'SslProtocols' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)
- 'FtpClient' does not contain a definition for 'EncryptionMode' and no accessible extension method 'EncryptionMode' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)
- 'FtpExists' does not contain a definition for 'Append'	Paperless Library	
- 'FtpExists' is obsolete: 'This enum is obsolete. Please use FtpRemoteExists instead.'	'FtpClient' does not contain a definition for 'Upload' and no accessible extension method 'Upload' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)
- 'FtpClient' does not contain a definition for 'DataConnectionEncryption' and no accessible extension method 'DataConnectionEncryption' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)	Paperless Library	C:\Users\skalyadan\Source\Repos\Paperless\Paperless\Paperless Library\FTP.cs	110	Active

**Comment by FanDjango** [comment]
Update to updated to the latest FluentFTP (48.0.3) **from**? (sigh)

But very probably you should read [this](https://github.com/robinrodricks/FluentFTP/wiki/v40-Migration-Guide)
