### ISSUE TITLE
GetWorkingProfileFromHost: Destination array was not long enough

### ISSUE THREAD

**Issue by henols02-sr** [robinrodricks/FluentFTP#1384]
**FTP Server OS:** Unix
**FTP Server Type:** Pure-FTPd 
**Client Computer OS:** Alpine Linux (mcr.microsoft.com/dotnet/aspnet:8.0-alpine)
**FluentFTP Version:** 48.0.3.0
**Framework:** .NET 8

Sometimes getting the below error when connecting:

- type: System.ArgumentException
- assembly: FluentFTP, Version=48.0.3.0, Culture=neutral, PublicKeyToken=f4af092b1d8df44f
- method: FluentFTP.Client.Modules.ConnectModule.GetWorkingProfileFromHost
- outerType: System.ArgumentException
- outerMessage: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
- outerAssembly: System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
- outerMethod: System.Array.CopyImpl
 
Stack trace:
```
[{"method":"System.Array.CopyImpl","level":0,"line":0,"assembly":"System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"}
{"method":"System.Collections.Generic.List`1.AddRange","level":1,"line":0,"assembly":"System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"}
{"method":"FluentFTP.Client.Modules.ConnectModule.GetWorkingProfileFromHost","level":2,"line":0,"assembly":"FluentFTP, Version=48.0.3.0, Culture=neutral, PublicKeyToken=f4af092b1d8df44f"}
{"method":"FluentFTP.Client.Modules.ConnectModule+<AutoDetectAsync>d__2.MoveNext","level":3,"line":0,"assembly":"FluentFTP, Version=48.0.3.0, Culture=neutral, PublicKeyToken=f4af092b1d8df44f"}]
```

It seems to happen mostly during ourhealth checks, when we connect to different folder on the same server to see that it is up. It happened twice during the captured log below once at 2023-11-25 02:49:32.131 and once at 2023-11-25 02:49:36.099. Notice different threads.

**Logs :**
Way too long to paste here. I'll try add it as a file.

**Comment by henols02-sr** [comment]
[ftplog.txt](https://github.com/robinrodricks/FluentFTP/files/13472212/ftplog.txt)

**Comment by henols02-sr** [comment]
> I don't see any exceptions in this log?

The exception is in description. I don't know how the trace/debug logging works, so I don't know why it doesn't end up there.

**Comment by FanDjango** [comment]
So it is actually happening on one of the multiple connects taking place at that time...

**Comment by henols02-sr** [comment]
> So it is actually happening on one of the multiple connects taking place at that time...

Yes.

**Comment by FanDjango** [comment]
AddRange call not thread safe at that place in the code? Difficult to see why, so perhaps could I put a lock on that, make a "special" branch and have you run that for a while to see if that fixes it? Might not be the final solution but just to confirm the reason.

**Comment by FanDjango** [comment]
Another workaround for you would be to "try" the autoconnect, catch the exception and retry, of course.

**Comment by FanDjango** [comment]
GitHub closed this due to the merge.

@henols02-sr I think I found the place where thread safety was lost and merged a fix for that. If you are able, you can pick this up in the current master or wait for when it will be released into Nuget.

**Comment by henols02-sr** [comment]
Fantastic! I will upgrade as soon as there is a new release and try it out.
