### ISSUE TITLE
Code quality: For example: NonStopParser.cs Do not ignore method results

### ISSUE THREAD

**Issue by KLuuKer** [robinrodricks/FluentFTP#1388]
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1806

Parse calls Trim but does not use the new string instance that the method returns. Pass the instance as an argument to another method, assign the instance to a variable, or remove the call if it is unnecessary.

https://github.com/robinrodricks/FluentFTP/blob/cd82d67712f8726277ce2cf88efdb91ba653f076/FluentFTP/Helpers/Parsers/NonStopParser.cs#L59C1-L60C1

maybe open your `.editorconfig` and add this to prevent this from happening in the future.
```
[*.cs]
dotnet_diagnostic.CA1806.severity = error
```

**Comment by FanDjango** [comment]
```cs
			if (values.Length > 7) {
				values[7].Trim(TrimValues);
			}
```
I think these lines can be removed. They must be leftovers from some ancient refactoring. But they don't cause any harm, so no one noticed.

**Comment by KLuuKer** [comment]
Yeah i also noticed it was harmless, but i changed some stuff in my project
so now i have a whole bunch of CAxxxx\CSxxxx errors firing because i still have the cloned master source as a project 

i usually like having a whole bunch of those analyzers turned on so i don't have to keep rechecking the same "issues"
and also makes sure nothing slips through the cracks, incase I'm to tired to review a whole bunch of code.
or when i check in my own code from some late night coding session

you might also want to consider these analyzers:
- don't rethrow exceptions `throw ex;`, just ` throw;` them (changes of stack information)
`dotnet_diagnostic.CA2200.severity = error` 

- use single char instead of string when possible like for `x.Contains('x')` (some special optimized paths can be used sometimes) 
`dotnet_diagnostic.CA1847.severity = error` 

- prefer `TryGetValue` instead of doing a contains and a separate lookup (you actually end up looking it up twice)
`dotnet_diagnostic.CA1854.severity = error` 



![image](https://github.com/robinrodricks/FluentFTP/assets/12729178/08fca034-54e2-483e-bd44-c610f14d2b25)

try double clicking the `.editorconfig` in visual studio and scroll through the whole list.
i happend to learn some stuff from looking at the reasoning included on the help pages. (like rethrowing exceptions inside a catch while just a `throw;` does the "same" thing)

actual quality
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/

just styling so all the code looks the same (helpful even with only 2 or 3 people)
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/

**Comment by FanDjango** [comment]
You are heartily encouraged to submit a number of PR's for these suggestions:

First, a PR for the .editorconfig as a suggestion.

Then subsequent PRs as per the now appearing error messages.

We don't have so much time for that currently.

And while you're at it, submit some PR's for removing unused USINGs, too ;-)

**Comment by FanDjango** [comment]
We'll pick this up when scanning for ToDo/Enhancements
