### ISSUE TITLE
Ftp EPSV download from public site fails with IOException

### ISSUE THREAD

**Issue by mtanneryd** [robinrodricks/FluentFTP#1391]
**FTP Server OS:** 

**FTP Server Type:** 

**Client Computer OS:** Windows

**FluentFTP Version:** 48.0.3

**Framework:** .NET 8 

Running the following code throws an IOException

	var host = @"ftp.cmegroup.com";
	var name = @"span/data/ecc/ecc_spanfile_20231208.xml.zip";
	var ftpClient = new FtpClient(host, "anonymous", "", 21);
	ftpClient.Config.LogToConsole = true;
	ftpClient.Config.DownloadDataType = FtpDataType.Binary;
	ftpClient.Connect();
	MemoryStream ms = new MemoryStream();
	ftpClient.DownloadStream((Stream)ms, name, 0L, (Action<FtpProgress>)null, 0L);
	ftpClient.Disconnect();
	ms.Position = 0L;
	ms.Length.Dump();

but if replacing the file ecc_spanfile_20231208.xml.zip with ecc_spanfile_20231207.xml.zip it works.

**Comment by FanDjango** [comment]
Intriguing.

**Comment by mtanneryd** [comment]
Thanks for the quick response!

Setting the connection type to PASV did indeed help. However, it does not
explain why the server manages to handle the request for
"span/data/ecc/ecc_spanfile_20231207.xml.zip" using
EPSV but not  "span/data/ecc/ecc_spanfile_20231208.xml.zip".

Thankful but still confused,
Måns

Måns Tånneryd
Tånneryd IT AB
Barrskogsvägen 19
186 53 Vallentuna
+46-705140093
https://se.linkedin.com/in/manstanneryd



Den tis 12 dec. 2023 kl 17:14 skrev FanDjango ***@***.***>:

**Comment by FanDjango** [comment]
Ok. A wireshark trace shows that the data connection terminates abruptly from the server side, and we immediately receive a 4xx message from the server on the control connection telling us he couldn't write **to his outbound** stream. So then we notice this and terminate, IOException on the socket.

When you look at the data connection using EPSV, you can see that it runs on the same IP as the actual control connection.

Using PASV, the server offers a different IP.

Now here's the rub: The server has been configured thusly to make it easier to bypass a badass firewall (with content examination) by routing the data connection differently - on an incoming listening IP that has firewall exemptions on it or even bypasses the firewall.

.zip files often contain binary sequences that trigger virus detection in content examining firewalls. In that case it should actually terminate at the same place each try, which is not the case. So it might also be a bit of a timing issue as to exactly when the firewall gets around to taking the offending connection down, and then the server suddenly cannot write anymore, which it then complains about.
