### ISSUE TITLE
[Feature] Real Time Sync

### ISSUE THREAD

**Issue by abdeldjalil-fellah** [robinrodricks/FluentFTP#1421]
- add RealTimeSync background task that synchronize a file/folder on any changes made to that file/folder (created, modified, renamed, deleted, ...)

**Comment by robinrodricks** [comment]
This is way too high level for such a library. If you want you can contribute it.

We currently have `Upload/DownloadDirectory` which supports sync modes - https://github.com/robinrodricks/FluentFTP/wiki/Directory-Transfer#what-is-the-difference-between-the-mirror-and-update-modes

And FXP (server to server) also supports the same sync modes. https://github.com/robinrodricks/FluentFTP/wiki/FXP-Server-To-Server#how-is-fxp-implemented-internally
