### ISSUE TITLE
Libs not included into CLickOnce publish app root folder

### ISSUE THREAD

**Issue by hovek** [robinrodricks/FluentFTP#1425]
**FTP Server OS:** Windows

**FTP Server Type:** FileZilla Server

**Client Computer OS:** Windows 

**FluentFTP Version:** NuGet FluentFTP.GnuTLS 1.0.25

**Framework:** .NET 8

Libs are not getting included into app root folder on ClickOnce publish, and there is no way I can include them automatically other than creating some script that will copy them on publish event, if that is even possible, or I will have to add them to the root of my project, which is ugly. Guy, why don't you make it look for libraries in Libs/Win64 where they are located and always present, instead of searching for them in the app root folder? That would also enable me to reference NuGet package in referencing project only and not in all exe projects separately. It would work more robustly, logically and it would make our lives easier.

**Comment by FanDjango** [comment]
See #1347 

Thank you for your rant. 

If you know how to achieve this, please enlighten us.

**Comment by hovek** [comment]
> See #1347
> 
> Thank you for your rant.
> 
> If you know how to achieve this, please enlighten us.

Well, based on my programming language, programmer is the one that defines where his program is look for libraries, right?

**Comment by FanDjango** [comment]
Doesn't really work that way for `#dllimport`. Very restricted search order. Read up on it.

So it boils down to placing the .dlls in the **right** folder, since you can't point to some folder of **your own** liking.

Which means you must have the right statements in place for MSBUILD csproj etc. to put them in the right place in different scenarios.

Teach me.

**Comment by FanDjango** [comment]
But I agree that this is an **open problem**, waiting to be fixed.

**Comment by hovek** [comment]
> Maybe NuGet package can be constructed differently, how he includes FluentFTP.dll, FluentFTP.GnuTLS.dll, maybe he can include other dlls also to be copied to bin root folder on build.

Maybe NuGet package can be constructed differently, how he includes FluentFTP.dll, FluentFTP.GnuTLS.dll, maybe he can include other dlls also to be copied to bin root folder on build?

**Comment by FanDjango** [comment]
Guy, too many maybe maybe for me.

**Comment by hovek** [comment]
> Guy, too many maybe maybe for me.

I am not a programmer for this app nor I have time for it, I am giving quick suggestions of path I would take. :)

**Comment by FanDjango** [comment]
It was a big MSBUILD fight to get the **foreign, non-managed** dlls to be copied in in the first place, also trying to make sure that not too many multiple copies are kept in the Nuget, to keep it small.

Ok, thank you for the suggestion.

**Comment by hovek** [comment]
> It was a big MSBUILD fight to get the **foreign, non-managed** dlls to be copied in in the first place, also trying to make sure that not too many multiple copies are kept in the Nuget, to keep it small.
> 
> Ok, thank you for the suggestion.

Another maybe:

![image](https://github.com/robinrodricks/FluentFTP/assets/5937551/807b4565-c4c7-4667-90f3-b6530d5184d6)

**Comment by FanDjango** [comment]
I just experimented with ClickOnce.

Try using ` LoadLibraryDllNamePrefix = "Libs\\Win64\\",` as config for FluentFTPGnuTls. It worked for me.

**Comment by FanDjango** [comment]
The .dlls are already in the ClickOnce folder, but under Libs\Win64. We've done out part.

**Comment by FanDjango** [comment]
If you "publish" to a folder, nothing needs to be done as the .dlls are in the same file as the .exe
If you "publish" to click once, the .dlls go to Libs/Win64. You then need to code the config as I posted.

I think the reason for the difference is the publish to click once is trying to reconcile "portable" whereas to folder is more primitive

**Comment by hovek** [comment]
> If you "publish" to a folder, nothing needs to be done as the .dlls are in the same file as the .exe If you "publish" to click once, the .dlls go to Libs/Win64. You then need to code the config as I posted.
> 
> I think the reason for the difference is the publish to click once is trying to reconcile "portable" whereas to folder is more primitive

Interesting is that ClickOnce knows to include NuGet pkg "main" dll, so my idea was to somehow include other dlls into NuGet that would behave the same and get picked up by ClickOnce, but maybe they can't.

**Comment by FanDjango** [comment]
I remember reading that VS, MSBUILD, .NET and NuGet like to differentiate beween managed dlls and unmanaged (foreign) dlls. So that is a real pain, the unmanaged typically don't get copied, deployed etc. without any special actions. And they get put in different places... you can't really rely on anything as it depends on the type of publish/deploy.

**Comment by FanDjango** [comment]
Just make sure you don't select "Produce Single File" on the publish settings - this somehow does not even copy the dlls, not even to the wrong place. They are simply missing.

**Comment by hovek** [comment]
While debugging it works, but when published it does not work, still can't find dlls and they are present in Libs/Win64. Again maybe because relative path gets screwed up?

C:\Users\hrvoj\AppData\Local\Apps\2.0\GMHH1ZGH.9RW\671MP0HQ.2A5\clan...exe_0000000000000000_0001.0009_hr-hr_9a8e43760506f3df\Libs\Win64

![image](https://github.com/robinrodricks/FluentFTP/assets/5937551/5aa69960-25c2-4549-aae0-f16327a5e9e3)

**Comment by FanDjango** [comment]
Interesting. That picture, is exactly mine and it worked.

But I was using 
```cs
                    client.Config.CustomStream = typeof(GnuTlsStream);
                    client.Config.CustomStreamConfig = new GnuConfig()
                    {
                        //SecuritySuite = GnuSuite.Normal,
                        //SecurityOptions = new List<GnuOption> {
                        //		new GnuOption(GnuOperator.Include, GnuCommand.Protocol_All),
                        //		new GnuOption(GnuOperator.Exclude, GnuCommand.Protocol_Tls10),
                        //		new GnuOption(GnuOperator.Exclude, GnuCommand.Protocol_Tls11),
                        //	},
                        //SecurityProfile = GnuProfile.None,
                        //AdvancedOptions = new List<GnuAdvanced> {
                        //		GnuAdvanced.NoExtensions,
                        //	},
                        SetALPNControlConnection = string.Empty,
                        SetALPNDataConnection = string.Empty,
                        //LoadLibraryDllNamePrefix = "D:\\temp\\",
                        LogLevel = 0,
                        LogMessages = GnuMessage.All,
                        LoadLibraryDllNamePrefix = "Libs\\Win64\\",
                    };

```
See the LoadLibraryDllNamePrefix? Thats why I did set it, because I also checked the click once install directory of my small test app.

**Comment by FanDjango** [comment]
But it still does not solve my real problem, publishing to a single executable still does not include the native dlls.

**Comment by hovek** [comment]
> Interesting. That picture, is exactly mine and it worked.
> 
> But I was using
> 
> ```cs
>                     client.Config.CustomStream = typeof(GnuTlsStream);
>                     client.Config.CustomStreamConfig = new GnuConfig()
>                     {
>                         //SecuritySuite = GnuSuite.Normal,
>                         //SecurityOptions = new List<GnuOption> {
>                         //		new GnuOption(GnuOperator.Include, GnuCommand.Protocol_All),
>                         //		new GnuOption(GnuOperator.Exclude, GnuCommand.Protocol_Tls10),
>                         //		new GnuOption(GnuOperator.Exclude, GnuCommand.Protocol_Tls11),
>                         //	},
>                         //SecurityProfile = GnuProfile.None,
>                         //AdvancedOptions = new List<GnuAdvanced> {
>                         //		GnuAdvanced.NoExtensions,
>                         //	},
>                         SetALPNControlConnection = string.Empty,
>                         SetALPNDataConnection = string.Empty,
>                         //LoadLibraryDllNamePrefix = "D:\\temp\\",
>                         LogLevel = 0,
>                         LogMessages = GnuMessage.All,
>                         LoadLibraryDllNamePrefix = "Libs\\Win64\\",
>                     };
> ```
> 
> See the LoadLibraryDllNamePrefix? Thats why I did set it, because I also checked the click once install directory of my small test app.

ClickOnce screws up, when I remove manifest file from installed folder it works, even when I return the file it still works. ClickOnce is a finicky peace of crap.

**Comment by hovek** [comment]
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: FluentFTP.GnuTLS.GnuTlsException: GnuTLS .dll load/call validation error
 ---> FluentFTP.GnuTLS.GnuTlsException: Could not load Libs\Win64\libhogweed-6.dll, (0) 
   at FluentFTP.GnuTLS.Core.GnuTls.FunctionLoader.Load(String dllPath, Boolean storePointer)
   at FluentFTP.GnuTLS.Core.GnuTls.LoadAllFunctions()
   at FluentFTP.GnuTLS.Core.GnuTls.GnuTlsCheckVersion(String reqVersion)
   at FluentFTP.GnuTLS.GnuTlsInternalStream.Validate(Boolean log)

**Comment by FanDjango** [comment]
I believe you... I found out that ClickOnce when using SingleFile will use Libs/Win64/...dlls, even though they are in the apps.publish folder. When ClickOnce is **not** doing singlefile output, it works differently.

I have been playing around with the build process of FluentFTP.GnuTLS itself, but there is nothing there that is worth changing.

I think the problem is with Click Once. I can't even cause it to copy the dlls using the ` <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>`. It simply does nothing.

**Comment by hovek** [comment]
Yea, I gave up and just moved dll links to the root of the project.

**Comment by FanDjango** [comment]
Just a quick update: I have found the solution. In the next days I will finalize it and show the way to do it in the issue #1347

**Comment by FanDjango** [comment]
@hovek It is fixed, I found a solution. Please read #1347 !
