### ISSUE TITLE
Progress should include all operations of a single file transfer

### ISSUE THREAD

**Issue by J0nathan550** [robinrodricks/FluentFTP#1441]
Hello! I ran into issue where the progress of the `DownloadDirectory` doesn't show full progress, it's only showing the progress when you downloading file, but not when it is checking if file is good or not. Here is the footage. 

https://youtu.be/1JpgldcjjEA

**Comment by alexgubanow** [comment]
Hey @J0nathan550 , you expect to see the entire folder download progress, not individual files, is that correct?

**Comment by J0nathan550** [comment]
Yes, it is just strange that it is processing through all of the files and doesn't show the progress if file was good or not, it is just show progress when it is downloading something. Good to fix.

**Comment by FanDjango** [comment]
As far as I can see, progress is not really well defined beyond "progress when down- or up-loading a file". Any operations like checking the file integrity might or might not be fully integrated into different flavors of a "progress" object. Similarly, operations involving multiple files that invoke down- and up-load of a file will primarily repeatedly feed the file progress object. For these higher level operations, one might want to have a "meta-progress" object showing the "total" progress.

Note that that kind of "progress" object would then involve retrieving information on the total volume (sizes, number of files, etc.) before commencing the actual operation. Not everyone would appreciate that overhead for such a simple thing as "doing" FTP.

I would assume that the basic API routines provided by FluentFTP would enable a user of this library to implement such high level features themselves if they are really needed.

**Comment by J0nathan550** [comment]
> As far as I can see, progress is not really well defined beyond "progress when down- or up-loading a file". Any operations like checking the file integrity might or might not be fully integrated into different flavors of a "progress" object. Similarly, operations involving multiple files that invoke down- and up-load of a file will primarily repeatedly feed the file progress object. For these higher level operations, one might want to have a "meta-progress" object showing the "total" progress.
> 
> Note that that kind of "progress" object would then involve retrieving information on the total volume (sizes, number of files, etc.) before commencing the actual operation. Not everyone would appreciate that overhead for such a simple thing as "doing" FTP.
> 
> I would assume that the basic API routines provided by FluentFTP would enable a user of this library to implement such high level features themselves if they are really needed.

Well, Progress, is a progress. It should show full progress on things that library or program is doing, in background it checks but for usual user it will be a mess, since user cannot understand what is going on with the progress. In progress in my opinion, it should += the file amount the progress passed, it will be perfect for this library.

**Comment by J0nathan550** [comment]
And unfortunately in this specific case, progress works only when library installs something, not cool.

**Comment by FanDjango** [comment]
>  progress works only when library installs something

This I do not understand. Can you explain? "installs"?

**Comment by J0nathan550** [comment]
> > progress works only when library installs something
> 
> This I do not understand. Can you explain? "installs"?

Well, downloads. When you use function like `DownloadDirectory`. It should show full progress of file checking and downloading. Right now it shows progress, I repeat, only when it installs something. 

I will try to do it myself using this repository. Later if I successed I will do pull request. 😄

**Comment by FanDjango** [comment]
You do realize that to show progress as percent, you first need to evaluate the total size or number of files that need to be up or downloaded. So effectively you need to walk the directory once to get the total, then again to do the actual up or download.

I agree that the checking part of a transfer is missing to be made part of the progress.

But for operations on multiple files, a new "super-progress" is needed.

**Comment by J0nathan550** [comment]
> You do realize that to show progress as percent, you first need to evaluate the total size or number of files that need to be up or downloaded. So effectively you need to walk the directory once to get the total, then again to do the actual up or download.
> 
> I agree that the checking part of a transfer is missing to be made part of the progress.
> 
> But for operations on multiple files, a new "super-progress" is needed.

You mean create another function? That would be nice to have "optimized progress" and "full progress" that optimized one will contain the current progress that this library has.

And new "full progress" that will show you every single thing. I would love to see that.

**Comment by FanDjango** [comment]
Yes. Let's do the following:

1. We will rename this issue here, to be: "If using checking, progress should include that"

2. We will make **another** issue, an enhancement request, "Provide a Full Progress for Multi-File Operations"

That way we can separate these two things.

**Comment by J0nathan550** [comment]
Sure! I would now call it, Feature Request.

**Comment by FanDjango** [comment]
Total agreement. But we use "Enhancement" as a label/tag.

"Full Progress" or "Total Progress" or "Overall Progress" or "Multi File Progress", we must make the naming clear.

And the current "Progress" will stay with the name "Progress", which **means** "File Progress", like it is already.

**Comment by FanDjango** [comment]
And now so that you are the author, please open "Multi-File operations should provide a overall progress" and I will label it "Enhancment". You can refer to this issue here as a cross reference.

**Comment by J0nathan550** [comment]
Done!

**Comment by FanDjango** [comment]
I have done some testing and I am actually quite happy with the current implementation of the single file progress.

**Comment by FanDjango** [comment]
See #1445 and #1447
These PR's also corrected remaining issues with single file progress reporting.
