### ISSUE TITLE
DownloadStream method ignores stopPosition

### ISSUE THREAD

**Issue by alexgubanow** [robinrodricks/FluentFTP#1444]
**FTP Server OS:**  - Windows

**FTP Server Type:** MOVEit transfer

**Client Computer OS:** Ubuntu / MacOS

**FluentFTP Version:** 49.0.1

**Framework:** .NET 7.0

DownloadStream method ignores stopPosition and keeps downloading. In same time GetFileSize() gives correct size. Same behaviour observed with progress callback and without one.
My goal is download first 5Mb of file, i can ignore rest.

**Comment by TimLCondor** [comment]
I am trying this since yesterday in every possible way but as you said, it keeps downloading the whole file for me as well:
```
var bytes = await client.DownloadBytes(path, stopPosition: sizeof(long));
Trace.WriteLine("Peaked " + bytes.Length + " bytes"); // Prints "Peaked 7689435 bytes" after a while
```
And with OpenRead, to do this manually, I get a timeout exception.

The problem here is that I only want to read the file header.

**Comment by alexgubanow** [comment]
spawning the PR right now, basically the stopPosition should match exactly the downloaded length, if we over downloaded - keeps till end. Im not sure my solution is expected fix for it, but it works.
