### ISSUE TITLE
Download with stopPosition overdownloads within last chunk, breaks progress report too

### ISSUE THREAD

**Issue by alexgubanow** [robinrodricks/FluentFTP#1446]
FTP Server OS: - Windows

FTP Server Type: MOVEit transfer

Client Computer OS: Ubuntu / MacOS

FluentFTP Version: 49.0.1

Framework: .NET 7.0

If one passes stopPosition argument to DownloadStream(), the last downloaded chunk will be 16k or 32k no matter if till stopPosition only 1 byte left. Calculated progress percentage value is off too in last step, since we overshoot. 

Behaviour observed before https://github.com/robinrodricks/FluentFTP/pull/1445 is that value just keeps growing, since stopPosition was ignored, while progress value calculated against given stopPosition.
After the fix for stopPosition, progress value is off in last few chunks, as we download by 16k or 32k blocks and may overshoot 100% point.

Sugested fix is to calculate if we can afford 16k block to download or we should take less to fit until stopPosition

**Logs :**

```
Requested first 16355 bytes, but stopPosition is broken, so keeps downloading and progress grow accordingly
Progress 100 TransferredBytes 16355
Progress 200 TransferredBytes 32710
Progress 300,3362885967594 TransferredBytes 49120
Progress 400,33628859675935 TransferredBytes 65475
Progress 500,33628859675935 TransferredBytes 81830
Progress 600,7704066034852 TransferredBytes 98256
....
Progress 13619,437480892693 TransferredBytes 2227459
Progress 13719,437480892693 TransferredBytes 2243814
Progress 13819,871598899419 TransferredBytes 2260240
Progress 13919,871598899419 TransferredBytes 2276595
Progress 14019,871598899419 TransferredBytes 2292950
Progress 14120,305716906145 TransferredBytes 2309376


Requested entire file
Progress 0,7064434728596987 TransferredBytes 16355
Progress 1,4128869457193973 TransferredBytes 32710
Progress 2,1217061074208745 TransferredBytes 49120
Progress 2,828149580280573 TransferredBytes 65475
Progress 3,534593053140272 TransferredBytes 81830
....
Progress 97,6265140696932 TransferredBytes 2260169
Progress 97,62958086801623 TransferredBytes 2260240
Progress 98,33602434087592 TransferredBytes 2276595
Progress 99,04246781373563 TransferredBytes 2292950
Progress 99,75197808491835 TransferredBytes 2309376


Requested 500Kb, stopPosition fix is applied:
Progress 3,2710000000000004 TransferredBytes 16355
Progress 6,542000000000001 TransferredBytes 32710
Progress 9,824 TransferredBytes 49120
Progress 13,095 TransferredBytes 65475
Progress 16,366 TransferredBytes 81830
....
Progress 94,9836 TransferredBytes 474918
Progress 98,2688 TransferredBytes 491344
Progress 101,5398 TransferredBytes 507699
```

**Comment by alexgubanow** [comment]
with suggested solution, the last chunk gives 100% progress value and do not overshoot the stopPosition:

```
Progress 88,4416 TransferredBytes 442208
Progress 91,7126 TransferredBytes 458563
Progress 94,9836 TransferredBytes 474918
Progress 98,2688 TransferredBytes 491344
Status:   Downloaded 500000 bytes
Progress 100 TransferredBytes 500000
```

**Comment by FanDjango** [comment]
This assessment is correct. It coincides with my take on this.

> Sugested fix is to calculate if we can afford 16k block to download or we should take less to fit until stopPosition

Exactly. The `.Read(...)` needs to be modified for the last amount needed to reach stopPosition.

But: Are you sure you know the size of the actual blocks received prior to getting close to the stopPosition?

For safeties sake, 32k before reaching the limit, you might want to revert to single byte reads? (Think jumbo frames being used on the underlying tcp connection, and note: We don't use BufferedStream on all connections).

**Comment by FanDjango** [comment]
Anyway, if you have a fix ready, let's see it on a PR. It is very worth adding.

**Comment by alexgubanow** [comment]
I have open PR, sorry haven't seen your comments...
we know exact bytes left to read, as (fileLen - offset)
based on this we can decide whatever to take full buffer or just left bytes.

**Comment by FanDjango** [comment]
Yes, you are right. What's left in our network buffers will be discarded.

**Comment by FanDjango** [comment]
Merged all of your suggested changes/additions.

> Ok. Let me sum this up:

> Most important part:
This will eliminate any "overshoot" at the end (last chunk). It is needed to make the previous commit more "complete", because although it is now honoring stopPosition, it will go too far (but it will stop).

> Also you solved the progress discrepancy for stopPosition, and the progress discrepancy for download that does not start at offfset 0.

Great work and very nice of you to submit these changes.

**Comment by alexgubanow** [comment]
Thank you, it is nice have such a fast and deep feedback. I will try to get back to this later this week and refactor it. Also would be nice to get few tests done, to prove make it solid.
Also need to verify progress of upload, if everything is working there, but i don't a test ftp server for that.
