### ISSUE TITLE
How often do you update NuGet?

### ISSUE THREAD

**Issue by J0nathan550** [robinrodricks/FluentFTP#1455]
What are dates that you release new versions of NuGet Package?

**Comment by FanDjango** [comment]
No special dates. It depends more on urgency / bug fixes / new features. And of course, if more things are in the near future pipeline. Also, current master can spend some time "stabilising", people checking it out and maybe reporting problems.

If you ask the owner real nicely, maybe XMAS will come a second time this winter?

**Comment by J0nathan550** [comment]
> No special dates. It depends more on urgency / bug fixes / new features. And of course, if more things are in the near future pipeline. Also, current master can spend some time "stabilising", people checking it out and maybe reporting problems.
> 
> If you ask the owner real nicely, maybe XMAS will come a second time this winter?

Well, would be great to see new fixes / features as soon as possible thanks for responding!
