### ISSUE TITLE
Release page and release tags are missing

### ISSUE THREAD

**Issue by alexgubanow** [robinrodricks/FluentFTP#1456]
Can you please add a release page? And tagging will carve in stone that commit, so i suggest to also  tagging each release as well.
Particularly im interested in release with PRs:
https://github.com/robinrodricks/FluentFTP/pull/1445
https://github.com/robinrodricks/FluentFTP/pull/1447

**Comment by robinrodricks** [comment]
NO. All releases are on nuget.
