### ISSUE TITLE
Request for Nuget 49.0.2

### ISSUE THREAD

**Issue by TimLCondor** [robinrodricks/FluentFTP#1457]
Thanks for this awesome project to the maintainer and all its contributors. It saves me from all the problems with Microsofts finicky FtpWebRequest implementation.

I would like to request a 49.0.2 Nuget release, especially with those fixes included from @alexgubanow 
https://github.com/robinrodricks/FluentFTP/issues/1444
https://github.com/robinrodricks/FluentFTP/issues/1446

I think those bugfixes are very important for the practical use of this library.

Thank you again
With best regards

**Comment by robinrodricks** [comment]
Will get to it soon.

**Comment by robinrodricks** [comment]
**Release notes**

  Continued improvement of NOOP daemon (important in case NOOP = true)
Messages / Logging
Improve daemon logic
Termination reliability
Handle NOOP API exceptions
Handle NOOP situations in EXECUTE API
No need for NOOP commands before a QUIT command
GETREPLY logging and handling for stale data and NOOP reactions
If QUIT is stashed and reconnect is pending, defer.
Recognize special commands / responses in all cases
Delay NOOP connectivity tests until connection fully established


·         IsStillConnected API
Clean up Connect/DisconnectInternal interface artifacts
Messages / Logging


·         IBM OS/400
Enhance detection of OS/400
Set SITE LISTFMT 1 and SITE NAMEFMT 1 on connect


·         DOWNLOADFILE(s) API (thanks J0nathan550)
Progress updated even when files skip to report increase in FileCount (for example)


·         DOWNLOADFILE(s) API (thanks alexgubanow)
Fix stopPosition not working
Fix progress calculation not correct when using stopPosition

**Comment by robinrodricks** [comment]
Released.

Thanks all for contributing.

https://www.nuget.org/packages/FluentFTP/49.0.2

**Comment by J0nathan550** [comment]
> **Release notes**
> 
> Continued improvement of NOOP daemon (important in case NOOP = true) Messages / Logging Improve daemon logic Termination reliability Handle NOOP API exceptions Handle NOOP situations in EXECUTE API No need for NOOP commands before a QUIT command GETREPLY logging and handling for stale data and NOOP reactions If QUIT is stashed and reconnect is pending, defer. Recognize special commands / responses in all cases Delay NOOP connectivity tests until connection fully established
> 
> · IsStillConnected API Clean up Connect/DisconnectInternal interface artifacts Messages / Logging
> 
> · IBM OS/400 Enhance detection of OS/400 Set SITE LISTFMT 1 and SITE NAMEFMT 1 on connect
> 
> · DOWNLOADFILE(s) API (thanks J0nathan550) Progress updated even when files skip to report increase in FileCount (for example)
> 
> · DOWNLOADFILE(s) API (thanks alexgubanow) Fix stopPosition not working Fix progress calculation not correct when using stopPosition

Library is so great that it fixed corrupted file transfer that FileZilla has for some reason😄
Check out here: [Alliance Uploader](https://github.com/J0nathan550/Alliance-Uploader)
