### ISSUE TITLE
Question about 'DownloadDirectory()'

### ISSUE THREAD

**Issue by jayhou07** [robinrodricks/FluentFTP#1458]
**FTP Server OS:** Debian 9

**FTP Server Type:** PyFtpdLib

**Client Computer OS:** Windows 10

**FluentFTP Version:** 48.0.3.0 (.NET Framework 4.6.2)

**Framework:** .NET  4 

<write details about your bug report / feature request here>
When I use  `DownloadDirectory(localTargetPath, remotePath));` , it does download remote folder but with parent path together. For example,

- The server path:  /parent0/parent1/folder
- expectation : just /folder  with content                      
- real result: /parent0/parent1/folder with content

Is this phenomen normal or I misuse the API ?

**Logs :** list some crucial parts
Verbose, info: >         DownloadDirectory("C:/Users/username/Desktop/parent1/folder\", "parent0/parent1/folder/", Update, Skip, None, "1 rules")
Verbose, info: >         DirectoryExists("parent0/parent1/folder/")
...
Verbose, info: Status:   Waiting for response to: PASV
Verbose, info: +---------------------------------------+
Verbose, info: Listing:  modify=20240123134607;perm=radfwM;size=13729;type=file;unique=801g48193a; file.txt
......
Verbose, info: -----------------------------------------
Verbose, info: >         CloseDataStream()
Verbose, info: >         DownloadServerFiles("113 files")
...
Verbose, info: >         DownloadFile("C:/Users/username/Desktop/parent1/folder\parent0\parent1\folder\file.txt", "\parent0\parent1\folder\file.txt", Skip, None)
...

```

<paste VERBOSE logs here>

```

**Comment by FanDjango** [comment]
Your "verbose" log is redacted **too** much.

I cannot see **any** of the commands that are sent to the server.

No time to try this out myself, but if the log were complete... maybe one would see more?
