### ISSUE TITLE
Error using clone function with async client

### ISSUE THREAD

**Issue by Alexyu696** [robinrodricks/FluentFTP#1460]
**FluentFTP Version:** Last

**Framework:** .NET 2 / 3.5 / 4 / 5 / 6 / 7 / 8 / UWP / Xamarin / Mono

When I use clone function to duplicate AsyncFtpClient there is a bug in implementation that generate an Invalid Cast Exception when execute any kind of async operation (list, open, delete, ...) on cloned client.

Issue is localized in files ExecuteDownloadText, GetListing, GetNameListing, OpenActiveDataStream, OpenPassiveDataStream, where you call OpenDataStreamAsync to retrieve FtpBaseStream object; when you close that object, you make call to sync Close, not to async Close (_note that implementation is missing in library_).

When you call sync Close, an internal call to CloseDataStreamInternal sync function is made, and that call invoke DisconnectInternal method of BaseFtpClient, that cast FtpClient to IFtpClient interface, but underlined object is AsyncFtpClient, that implement IAsyncFtpClient interface.

You can verify that in any async function of file OpenActiveDataStream.cs.

Best Regards

**Comment by FanDjango** [comment]
Possible duplicate: #1461

**Comment by FanDjango** [comment]
Ok, I have started looking at this, and it is more or less the same or a similar issue as #1461 - so let's get ASYNC cleaned up some more.

I will first set up something to reproduce this.

Are you sure it only happens when you **clone** a client? Or doesn't the `Close...` problem also occur on normal clients?

**Comment by FanDjango** [comment]
Ok, using the same technique as in #1461, I have fixed this issue.

Note: At some point in time, Close, Dispose and other cleanups need to be re-examined as to how well they are "fitted to async". There might still be some async operations happening somewhere that inadvertently invoke sync methods.

**Comment by FanDjango** [comment]
Until it is released, you can use the current master. I would appreciate it if you can also test this now.

**Comment by Alexyu696** [comment]
> Until it is released, you can use the current master. I would appreciate it if you can also test this now.

Ok at this moment I cannot verify implementation (other works in queue, sorry...), but as soon as possibile I upgrade version and I try new implementation.

Thanks very much! :)
