### ISSUE TITLE
System.InvalidCastException exception Thrown After File Upload Completes

### ISSUE THREAD

**Issue by MaroisConsulting** [robinrodricks/FluentFTP#1472]
**FTP Server OS:** Windows

**FTP Server Type:** 

**Client Computer OS:** Windows

**FluentFTP Version:** 49.0.2

**Framework:** .NET 4.7.2

I am new to FluentFTP. I am running a sample console app doing an async upload. When the upload completes, I see an exception:

Here is my debug output:
```
Test Started
0.249809715255957
0.499619430511915
.
.
.
99.674076387127
99.923886102383
100
100
Success
**Exception thrown: 'System.InvalidCastException' in FluentFTP.dll**
The program '[15164] MyTest.exe' has exited with code 0 (0x0).
```
**Logs :**

```

<paste VERBOSE logs here>

```

**Comment by FanDjango** [comment]
Thanks for reporting this. See #1461. Perhaps if you explicitly `client.Disconnect()` prior to disposing the client, you won't see this exception. But without seeing your source code, I cannot say.

The current master of FluentFtp on GitHub should already fix this.
