### ISSUE TITLE
Mix-up of return codes when using GetWorkingDirectory

### ISSUE THREAD

**Issue by ww898** [robinrodricks/FluentFTP#149]
I got strange behavior when trying to upload binary files to my ftp.  `EnableThreadSafeDataConnections` is `false` in my case and I did all FTP operations only in single thread. The `GetWorkingDirectory()` throw the `FluentFTP.FtpCommandException` with "550 Could not get file size." Wireshark shows that `PWD` returns previous error code from `SIZE` command:
```
...
3554	59.206258	FTP	61	Request: CWD /
3555	59.247468	FTP	91	Response: 250 Directory successfully changed.
3556	59.254597	FTP	62	Request: TYPE I
3557	59.296293	FTP	85	Response: 200 Switching to Binary mode.
3559	59.302661	FTP	XXX	Request: SIZE /abc/asd.xyz
3562	59.343603	FTP	84	Response: 550 Could not get file size.
3563	59.349279	FTP	60	Request: EPSV
3565	59.391072	FTP	103	Response: 229 Entering Extended Passive Mode (|||13061|).
3570	59.437461	FTP	XXX	Request: STOR /abc/asd.xyz
3572	59.478450	FTP	76	Response: 150 Ok to send data.
34674	76.445044	FTP	78	Response: 226 Transfer complete.
34675	76.447271	FTP	XXX	Request: SIZE /abc/asd.xyz
34677	76.487917	FTP	68	Response: 213 49143092
34678	76.487985	FTP	YYY	Request: SIZE /abc/qwe.xyz
34682	76.529395	FTP	84	Response: 550 Could not get file size.
34683	76.529455	FTP	59	Request: PWD
34685	76.571388	FTP	63	Response: 257 "/"
; FtpCommandException with 550 error was caught here during GetWorkingDirectory() call
```
Please let me know if you need more information. It's 100% reproducible in my environment.

*P.S.* Everything is good when `EnableThreadSafeDataConnections ` is `true`.

**Comment by hgupta9** [comment]
You don't need wireshark. Just enable logging. See this [FAQ entry](https://github.com/hgupta9/FluentFTP#faq_trace).

**Comment by ww898** [comment]
I probably found the bug:

**Comment by hgupta9** [comment]
Good find. Can you fix it? And please prefer using [high level API ](https://github.com/hgupta9/FluentFTP#file-transfer)where possible.

**Comment by hgupta9** [comment]
I think you have to call GetReply() like so:
```
using (var stream = (FtpDataStream) myFtpClient.OpenWrite(file))
 action(stream);
GetReply()
using (var stream = myFtpClient.OpenWrite(file))
 action(stream);
GetReply()
```

Does this work for you?

**Comment by robinrodricks** [comment]
Is this still an issue? The Dispose calls were recently fixed...
