### ISSUE TITLE
MLSD Last Modified DateTime.Kind

### ISSUE THREAD

**Issue by cedmundsNull** [robinrodricks/FluentFTP#1508]
When getting a listing with MLSD, the last modified DateTime.Kind is Unspecified.

Should it be updated to UTC?

As far as I understand, MLSD should [always return UTC times](https://datatracker.ietf.org/doc/html/rfc3659#section-2.3).

Currently, I have implemented the following workaround:

```
var listing = await client.GetListing(path);

  if (client.Config.ListingParser == FluentFTP.FtpParser.Machine)
      foreach (var item in listing)
          item.Modified = DateTime.SpecifyKind(item.Modified, DateTimeKind.Utc);
```

**Comment by FanDjango** [comment]
Good catch, I agree.

**Comment by FanDjango** [comment]
There is a nice PR now addressing this issue, so as suggested by @cedmundsNull in #1509: closing
