### ISSUE TITLE
Enhancement: Extend the built-in verification of all major file transfer methods with size comparison.

### ISSUE THREAD

**Issue by DasRaschloch** [robinrodricks/FluentFTP#1511]
**FTP Server OS:** N/A

**FTP Server Type:** N/A

**Client Computer OS:** Windows 
**FluentFTP Version:** 49.0.2 (nuget)

**Framework:** .NET 8

I don't know if there is a technical issue preventing this, but why do the major transfer methods only support hashing for verification?  Size comparison is already implemented with `CompareFile(localFile, remoteFile, FtpCompareOption.Size)`, so wouldn't it be possible to add this to the main functions as well? This would be especially helpful for `DownloadDirectory()` so that you do not have to iterate over each file in the directory manually and check if the sizes are the same.

This is obviously just an edge case, and only applies if a server doesn't support hashing, but I think it could be a nice QoL addition.

**Comment by FanDjango** [comment]
> `so wouldn't it be possible to add this to the main functions as well?`

Oh yes. Manpower? I would support and work together with you if you add this in a PR. Perhaps, as a first step - only for a **single** main function (API) - and then I would propagate this to the rest.

**Comment by FanDjango** [comment]
Note that this is especially inportant for verification of "huge" files. Don't want to uncondionally hash for verification if size differs, as this can be very costly.

**Comment by DasRaschloch** [comment]
> Oh yes. Manpower? I would support and work together with you if you add this in a PR.

Uhm, that was not what I had in mind with the suggestion, but now that you say it ...., it might be worth a try :).


So, at first glance, for checking a single up- and download of the AsyncFtpClient

wouldn't it be enough, to add:

```
var localSize = await FtpFileStream.GetFileSizeAsync(localPath, false, token);
var remoteSize = await GetFileSize(remotePath, -1, token);
if (localSize != remoteSize) {
		return false;
}
```
in line 30 of the VerifyTransfer class (Method: VerifyTransferAsync()). And to avoid confusion, rename the OnlyChecksum enumeration in FtpVerify. This way, the sizecheck would be implemented as a default check that is always performed before hashing, and the bool has a real meaning, because as of now it returns true even if hashing is not supported.

**Comment by DasRaschloch** [comment]
For the FxPMethods `TransferFile and TransferDirectory` a similar approach needs to be added to the method VerifyFXPTransferAsync in line 33:

```
	var sourceSize = await GetFileSize(sourcePath, -1, token);
	var remoteSize = await GetFileSize(remotePath, -1, token);
	if (sourceSize != remoteSize) {
		return false;
	}
```

Which would result in the same behaviour.

**Comment by DasRaschloch** [comment]
@FanDjango something along these lines #1513 .
