### ISSUE TITLE
Having issues with validating checksum of a file in upload with FileZilla 

### ISSUE THREAD

**Issue by myogendra** [robinrodricks/FluentFTP#152]
For validating checksum I am using 
"client.GetChecksum(remoteRelativePath)"
My FTP server has below capabilities
MLSD | SIZE | MDTM | REST | UTF8 | MFMT, I know that it should have XCRC for getting file hash.

So, is there any other way to get checksum, I am using FileZilla as my FTP.

Thanks for the help in advance.

**Comment by hgupta9** [comment]
It _should_ have XCRC? So does it have or not? Please see the FAQ for tracing, and paste the complete trace/debug logs here for us to analyze. Call Connect() explicitly before calling anything else. Call GetChecksum too so it will be logged.

**Comment by myogendra** [comment]
It doesn't have XCRC, 
I have done testing in my code with the below codes to check checksum and got the below outputs which I have shown you "Output".
 client.Connect();
var capabilities = client.Capabilities;  - Output -  MLSD | SIZE | MDTM | REST | UTF8 | MFMT
var hashAlgorithm = client.HashAlgorithms;  - Output - NONE
var hashCapability = client.HasFeature(FtpCapability.HASH); - Output  - false
var checkSum =  client.GetChecksum(remoteRelativePath); 
checkSum.Isvalid - Output - false

Here my FTP server is FileZilla where I can see there is no support for XCRC, so my question is do we have any other way to get checksum of a uploaded file from FileZilla server.  
I have attached my log file, please have a look into it.

[log_file.txt](https://github.com/hgupta9/FluentFTP/files/1207548/log_file.txt)

**Comment by hgupta9** [comment]
Nothing can be done on our end. Search google for "filezilla server checksum" or whatever to try to find a plugin/addon for checksum/hashing capability. Unless the server supports it, how can we do it? In the worst case, download the file using Download/DownloadFile and then run your CRC32 or whatever on the bytes.

**Comment by myogendra** [comment]
Issue with GetChecksum() method if fileName has spaces, it will not process file to compute checksum and giving syntax error. My server has XCRC support, but due to this I am not able to compute checksum.

**Comment by FanDjango** [comment]
I tested this: `GetChecksum("/home/user/te st.bin");`, a file name with a blank in it

proftpd with capability HASH (mod_digest loaded).

```
FtpHash hash = FTP_Sess.GetChecksum("/home/user/te st.bin");
```
Output is:
```
*** Verbose >         GetChecksum("/home/user/te st.bin")
*** Info Command:  OPTS HASH MD5
*** Info Response: 200 MD5
*** Info Command:  HASH /home/user/te st.bin
*** Verbose Response: 213-Computing MD5 digest
*** Info Response: 213 MD5 0-6 aa89419c1b0e521bb4428b8f887a9e53 /home/user/te st.bin
```
This issue is so stale that if you don't provide more information, I think this issue will be closed soon.

**Comment by robinrodricks** [comment]
Thank you @FanDjango for confirming.
