### ISSUE TITLE
Expection FluentFTP.Exceptions.FtpCommandException: Code: 550 Message: Command not recognized or allowed when use GetListing method

### ISSUE THREAD

**Issue by Dang507** [robinrodricks/FluentFTP#1535]
This is the first time i used Fluent to working with FTP server 
code example: 
 var conn = new FtpConnection(rbmqGetFile.FtpClientMode.FtpInfo, asyncFtpClient, _logger);

public AsyncFtpClient ConnectFtp()
{
_asyncFtpClient.Host = _ftpInfo.Host;
_asyncFtpClient.Port = _ftpInfo.Port;
_asyncFtpClient.Credentials = new NetworkCredential(_ftpInfo.UserName, _ftpInfo.Password);
_asyncFtpClient.Connect(token);
}
 var connected = conn.ConnectFtp();
 var files = await connected.GetListing(rbmqGetFile.FtpClientMode.FtpInfo.FolderPath, FtpListOption.ForceList);

when call method GetListing it worked not smooth, it's a throw Code: 550 Message: Command not recognized or allowed or code 500. 
How to resolve it? Thank you

**Comment by FanDjango** [comment]
Please include more information and also verbose log of entire session. Cannot help you otherwise. Do you think we have got a crystal ball?

**Comment by Dang507** [comment]
hi @FanDjango  I have fixed it by myself, my code has issues with async/await so in ConnectFtp method I must be use async/await probably like this. 
public async  Task<AsyncFtpClient> ConnectFtp()
{
_asyncFtpClient.Host = _ftpInfo.Host;
_asyncFtpClient.Port = _ftpInfo.Port;
_asyncFtpClient.Credentials = new NetworkCredential(_ftpInfo.UserName, _ftpInfo.Password);
 await Task.Run( () =>_asyncFtpClient.Connect(token));
}
Thank for your response. Please close this issues.
