### ISSUE TITLE
TransferDirectory function error

### ISSUE THREAD

**Issue by yunhyejoung** [robinrodricks/FluentFTP#1541]
I need your advice..
I keep waiting your advice...
Please Help me..

**FTP Server OS:**  Windows

**FTP Server Type:**  Windows Server IIS 

**Client Computer OS:** Windows 

**FluentFTP Version:** ? 49.0.2.0

**Framework:** .NET 4.7.2

501 Server cannot accept argument. but filezilla operates normally.

**Logs :**

```

# Connect(False)
Status:   FluentFTP 49.0.2.0(.NET Framework 4.7.2)
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220 Microsoft FTP Service [738987.261d]
Status:   Detected FTP server: WindowsServerIIS
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Password required [1ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230 User logged in. [5ms]
Command:  FEAT
Status:   Waiting for response to: FEAT
Response: 211-Extended features supported:
Response: AUTH TLS;TLS-C;SSL;TLS-P;
Response: PBSZ
Response: PROT C;P;
Response: CCC
Response: HOST
Response: SIZE
Response: MDTM
Response: REST STREAM
Response: 211 END [6ms]
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 Windows_NT [1ms]
Status:   Active ServerHandler is: WindowsServerIIS
Status:   Listing parser set to: Windows
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/" is current directory. [2ms]

# Connect(False)
Status:   FluentFTP 49.0.2.0(.NET Framework 4.7.2)
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220 Microsoft FTP Service [738987.261d]
Status:   Detected FTP server: WindowsServerIIS
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Password required [2ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230 User logged in. [6ms]
Command:  FEAT
Status:   Waiting for response to: FEAT
Response: 211-Extended features supported:
Response: AUTH TLS;TLS-C;SSL;TLS-P;
Response: PBSZ
Response: PROT C;P;
Response: CCC
Response: HOST
Response: SIZE
Response: MDTM
Response: REST STREAM
Response: 211 END [6ms]
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 Windows_NT [1ms]
Status:   Active ServerHandler is: WindowsServerIIS
Status:   Listing parser set to: Windows
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/" is current directory. [2ms]

# TransferDirectory("/test1/", FluentFTP.FtpClient, "/TEMP/", Update, Skip, None, null)

# DirectoryExists("/test1")
Command:  CWD /test1
Status:   Waiting for response to: CWD /test1
Response: 250 CWD command successful. [2ms]
Command:  CWD /
Status:   Waiting for response to: CWD /
Response: 250 CWD command successful. [2ms]

# DirectoryExists("/TEMP")
Command:  CWD /TEMP
Status:   Waiting for response to: CWD /TEMP
Response: 250 CWD command successful. [1ms]
Command:  CWD /
Status:   Waiting for response to: CWD /
Response: 250 CWD command successful. [5ms]

# GetListing("/test1", Auto)
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Type set to I. [6ms]

# OpenDataStream("LIST /test1", 0)

# OpenPassiveDataStream(AutoPassive, "LIST /test1", 0)
Command:  EPSV
Status:   Waiting for response to: EPSV
Response: 229 Entering Extended Passive Mode (|||60148|) [2ms]
Status:   Connecting to IP #1= ***:60148
Command:  LIST /test1
Status:   Waiting for response to: LIST /test1
Response: 125 Data connection already open; Transfer starting. [2ms]
+---------------------------------------+
Listing:  04-10-24  03:02PM              1362327 image.tif
Listing:  04-10-24  02:57PM                    5 test1.txt
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: LIST /test1
Response: 226 Transfer complete. [21ms]
Status:   Closing/Disposing FtpSocketStream(data connection)
Status:   Confirmed format Windows

# GetListing("/TEMP", Auto)
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Type set to I. [1ms]

# OpenDataStream("LIST /TEMP", 0)

# OpenPassiveDataStream(AutoPassive, "LIST /TEMP", 0)
Command:  EPSV
Status:   Waiting for response to: EPSV
Response: 229 Entering Extended Passive Mode (|||3597|) [2ms]
Status:   Connecting to IP #1= ***:3597
Command:  LIST /TEMP
Status:   Waiting for response to: LIST /TEMP
Response: 125 Data connection already open; Transfer starting. [3ms]
+---------------------------------------+
Listing:  02-26-24  02:52PM               746123 4.????.svsx
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: LIST /TEMP
Response: 226 Transfer complete. [14ms]
Status:   Closing/Disposing FtpSocketStream(data connection)
Status:   Confirmed format Windows

# GetListing("/test1", Auto)

# OpenDataStream("LIST /test1", 0)

# OpenPassiveDataStream(AutoPassive, "LIST /test1", 0)
Command:  EPSV
Status:   Waiting for response to: EPSV
Response: 229 Entering Extended Passive Mode (|||60149|) [2ms]
Status:   Connecting to IP #1= ***:60149
Command:  LIST /test1
Status:   Waiting for response to: LIST /test1
Response: 125 Data connection already open; Transfer starting. [3ms]
+---------------------------------------+
Listing:  04-10-24  03:02PM              1362327 image.tif
Listing:  04-10-24  02:57PM                    5 test1.txt
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: LIST /test1
Response: 226 Transfer complete. [12ms]
Status:   Closing/Disposing FtpSocketStream(data connection)

# GetFileSize("/test1/image.tif")
Command:  SIZE /test1/image.tif
Status:   Waiting for response to: SIZE /test1/image.tif
Response: 213 1362327 [2ms]

# GetFileSize("/test1/test1.txt")
Command:  SIZE /test1/test1.txt
Status:   Waiting for response to: SIZE /test1/test1.txt
Response: 213 5 [1ms]

# TransferServerFiles("2 files")

# TransferFile("/test1/image.tif", FluentFTP.FtpClient, "/TEMP/image.tif", Binary, False, NoCheck, None)

# FileExists("/test1/image.tif")
Command:  SIZE /test1/image.tif
Status:   Waiting for response to: SIZE /test1/image.tif
Response: 213 1362327 [<1ms]
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (12,57,200,26,14,13). [3ms]
Command:  PORT 12,57,200,26,14,13
Status:   Waiting for response to: PORT 12,57,200,26,14,13
Response: 501 Server cannot accept argument. [1ms]
Warning:  File failed to transfer: /test1/image.tif

# TransferFile("/test1/test1.txt", FluentFTP.FtpClient, "/TEMP/test1.txt", Binary, False, NoCheck, None)

# FileExists("/test1/test1.txt")
Command:  SIZE /test1/test1.txt
Status:   Waiting for response to: SIZE /test1/test1.txt
Response: 213 5 [1ms]
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (12,57,200,26,14,13). [3ms]
Command:  PORT 12,57,200,26,14,13
Status:   Waiting for response to: PORT 12,57,200,26,14,13
Response: 501 Server cannot accept argument. [2ms]
Warning:  File failed to transfer: /test1/test1.txt


```

Hello
Please Help me..            

	string host = "12.57.200.25";
            string user = "user1";
            string pass = "pw1";
            int port = 21;
            string sourcefolder = @"/test1";

            string host1 = "12.57.200.26";
            string user1 = "user2";
            string pass1 = "pw2";
            int port1 = 21;
            string dstfolder = @"/TEMP";

            var srcFTP = new FtpClient(host, user, pass, port);
            srcFTP.Config.LogToConsole = true;
            srcFTP.Connect();                        

            var dstFTP = new FtpClient(host1, user1, pass1, port1);
            dstFTP.Config.LogToConsole = true;
            dstFTP.Connect();

            var uploadResult  = srcFTP.TransferDirectory(sourcefolder, dstFTP, dstfolder, FtpFolderSyncMode.Update, FtpRemoteExists.Skip, FtpVerify.None, null, null);

**Comment by FanDjango** [comment]
OK, thanks for the report and the log.

I think the problem is due to the following:

You get: `501 Server cannot accept argument. [2ms]`.

The command was: `PORT 12,57,200,26,14,13`.

If you look at how the LIST command was done, you can see that EPSV was being used and it worked.

Currently the stream for the FXP transfers uses **only** PASV (or CPSV). It seems that your server **does not like** PASV connections - **or the routing to the IP address and Port offered by the host as response to the PASV command** is not reachable.

Compare a debug detailed logging of FileZilla, and you can probably see that both times EPSV is being used, on the LIST command, and later for the transfer.

Please read up on PASV, EPSV etc. for FTP protocol.

**Currently, FXP TransferFile only uses PASV**. It does not honour the setting of the config "AutoPassive" or any other setting, for that matter.

The LIST command that FXP transfer uses internally, on the other hand, **does** honour the setting and the FEAT response of the server, saying that it support EPSV.

I know this does not really help you to get it working right, but this is my initial analysis of the described problem. You say it works in FileZilla, can I see such a log from FileZilla?

**Comment by FanDjango** [comment]
I also suggest **also** you browse this:

https://serverfault.com/questions/842192/iis-8-5-ftp-501-server-cannot-accept-argument-in-response-to-port-command

It explains the possible problems and how you can solve them.

**Comment by yunhyejoung** [comment]
> OK, thanks for the report and the log.
> 
> I think the problem is due to the following:
> 
> You get: `501 Server cannot accept argument. [2ms]`.
> 
> The command was: `PORT 12,57,200,26,14,13`.
> 
> If you look at how the LIST command was done, you can see that EPSV was being used and it worked.
> 
> Perhaps the IP Address represented by 12,57,200,26 is not valid or reachable or something?
> 
> I will do more research as soon as I have time.



It works in FileZilla in the same environment.

**Comment by FanDjango** [comment]
I suppose a log from filezilla showing the way it works there would allow one to compare?

**Comment by yunhyejoung** [comment]
> I suppose a log from filezilla showing the way it works there would allow one to compare?

Can I just edit the EPSV part?

**Comment by FanDjango** [comment]
You mean, to make the IP secret? Yes, of course

**Comment by yunhyejoung** [comment]
> You mean, to make the IP secret? Yes, of course

Does FXP not work because of EPSV?

**Comment by FanDjango** [comment]
I have checked how FXP is supposed to work. Disregard all of my comments about EPSV.

FXP is not working because the PASV command gives `227 Entering Passive Mode (12,57,200,26,14,13)` and then `PORT 12,57,200,26,14,13` will fail with `501 Server cannot accept argument.`

**Comment by yunhyejoung** [comment]
> I have checked how FXP is supposed to work. Disregard all of my comments about EPSV.
> 
> FXP is not working because the PASV command gives `227 Entering Passive Mode (12,57,200,26,14,13)` and then `PORT 12,57,200,26,14,13` will fail with `501 Server cannot accept argument.`

So what should I do?

**Comment by FanDjango** [comment]
One possible reason is that the server does not allow FXP.

So show me a log of a FXP transfer that is working.

**Comment by yunhyejoung** [comment]
> One possible reason is that the server does not allow FXP.
> 
> So show me a log of a FXP transfer that is working.

How do you get this?
Please tell me how to get this (So show me a log of a FXP transfer that is working.)

**Comment by FanDjango** [comment]
You say, it works in FileZilla. So, show me.

**Comment by yunhyejoung** [comment]
> You say, it works in FileZilla. So, show me.


1. I will upload the FXP operation log from Filezilla.

**Comment by yunhyejoung** [comment]
> You say, it works in FileZilla. So, show me.

STEP_1 ) I copied the files from folder number 12,57,200,25 in FileZilla and then pasted them into folder number 12,57,200,26.

**Comment by FanDjango** [comment]
That is not FXP. You downloaded the files from .25 to your PC and then uploaded them to .26.

Read up on FXP. That is Client commands -> (Sever1->Server2) transfer.

What you are doing in FileZilla is Client <- Server1 and after that, Client -> Server2

You need to understand more about FXP and if **both** servers support it. Otherwise you need to code first a connect to server1, download, then a connect to server2 and upload.

**Comment by yunhyejoung** [comment]
> That is not FXP. You downloaded the files from .25 to your PC and then uploaded them to .26.
> 
> Read up on FXP. That is Client commands -> (Sever1->Server2) transfer.
> 
> What you are doing in FileZilla is Client <- Server1 and after that, Client -> Server2
> 
> You need to understand more about FXP and if **both** servers support it. Otherwise you need to code first a connect to server1, download, then a connect to server2 and upload.




What I mean by becoming Filezilla in the same environment is.....

STEP_1) I copy the file in folder 25 with the mouse in the FileZilla window.
STEP_2) In the FileZilla window, I paste the file into folder number 26 with the mouse.
