### ISSUE TITLE
Unable to upload file to FTP server (NLST command invalid with TYPE binary)

### ISSUE THREAD

**Issue by gattamanenim** [robinrodricks/FluentFTP#155]
Hi,
 I am trying to upload a file using FluentFTP upload method. but I am getting this error.
 "NLST command invalid with TYPE binary"

Any suggestions Please?

**Comment by hgupta9** [comment]
Paste the entire logs here. See the faq for tracing/logging. Which server do you have?

**Comment by gattamanenim** [comment]
Hi Gupta,

Here is the Log. This is a UNIX server

# Connect()
Status:   Connecting to XXX.XXX.XX.XX:XX
Response: 220 CONNECT:Enterprise Gateway 2.1.00. FTP Server ready...
Command:  USER XYZ
Response: 331 Password required for XYZ
Command:  PASS ***
Response: 230 User XYZlogged in. Session Id: 16762.
Command:  FEAT
Response: 500 FEAT command not understood.
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 215 UNKNOWN Type: L8 through CONNECT:Enterprise Gateway 2.1.00 CF1 B3.
Warning:  Cannot auto-detect listing parser for system 'UNKNOWN Type: L8 through CONNECT:Enterprise Gateway 2.1.00 CF1 B3.', using Unix parser

# SetWorkingDirectory("/chivpn1t/")
Command:  CWD /chivpn1t
Response: 250 CWD command successful.

# Upload("ky1_xk425846d2_170714_p5.837", Overwrite, False)

# FileExists("ky1_xk425846d2_170714_p5.837")

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/chivpn1t" is current directory.

# GetNameListing("/chivpn1t")
Command:  TYPE I
Response: 200 TYPE set to I.

# OpenPassiveDataStream(AutoPassive, "NLST /chivpn1t", 0)
Command:  EPSV
Response: 500 EPSV command not understood.

# OpenPassiveDataStream(PASV, "NLST /chivpn1t", 0)
Command:  PASV
Response: 227 PASV Entering passive mode (XXX.XXX.XX.XX:XX).
Status:   Connecting to 170.201.41.43:49163
Command:  NLST /chivpn1t
Response: 451 NLST command invalid with TYPE binary.

# CloseDataStream()

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Response: 221 Goodbye.
Status:   Disposing FtpSocketStream...

Thanks
Madhuri

**Comment by hgupta9** [comment]
What server software are you using? Never heard of "CONNECT:Enterprise Gateway" before...

**Comment by hgupta9** [comment]
Also why are you using GetNameListing()? Try using GetListing(), that may work better for your server. Apparently your server software is outdated, and does not support name listing in binary mode, only ASCII mode. Maybe you can update the server software?

**Comment by robinrodricks** [comment]
Will be reopened after you reply....
