### ISSUE TITLE
GetListing Chinese garbled characters

### ISSUE THREAD

**Issue by zhangwc1030** [robinrodricks/FluentFTP#1574]
When the GetListing() method obtains the file list, the Chinese file name will appear garbled?
ftpClient. Encoding = Encoding. UTF8;
ftpClient. Encoding = Encoding. Default;
I can't solve the problem after trying.

**Comment by zhangwc1030** [comment]
![微信图片_20240520081629](https://github.com/robinrodricks/FluentFTP/assets/29644882/eb35778e-adfe-4ae7-adfa-1378cdd3faad)

**Comment by zhangwc1030** [comment]
1.??? Chinese garbled characters "?"

**Comment by robinrodricks** [comment]
https://github.com/robinrodricks/FluentFTP/wiki/File-Transfer#how-can-i-uploaddownload-files-with-unicode-filenames-when-my-server-does-not-support-utf8
