### ISSUE TITLE
ftp.GetListing(path) 

### ISSUE THREAD

**Issue by zhangwc1030** [robinrodricks/FluentFTP#1577]
FTP When the GetListing (path) method obtains a file list, will the Chinese file name appear garbled "?"
FtpClient Encoding=Encoding UTF8;
FtpClient Encoding=Encoding Default;
Trying it doesn't solve the problem.
![微信图片_20240520081629](https://github.com/robinrodricks/FluentFTP/assets/29644882/9a69c2c2-6201-421e-981f-305fafa7b3c9)

**Comment by robinrodricks** [comment]
https://github.com/robinrodricks/FluentFTP/wiki/File-Transfer#how-can-i-uploaddownload-files-with-unicode-filenames-when-my-server-does-not-support-utf8
