### ISSUE TITLE
 using the GetListing  Error

### ISSUE THREAD

**Issue by Sharp2017** [robinrodricks/FluentFTP#1578]
When using FTP When using the GetListing method to obtain a file list, garbled characters may appear when the file title contains Chinese characters
After testing using FTP in the. net8 environment When using the GetListing method to obtain a file list, garbled characters may appear when the file title contains Chinese characters
As shown in the figure
![Error](https://github.com/robinrodricks/FluentFTP/assets/31951676/8c78d628-a142-4db4-9294-9f18d0ac1653)

Using FTP with. netFramework4.8 When using the GetListing method to obtain a file list, the file title with Chinese characters is displayed normally
As shown in the figure
![OK](https://github.com/robinrodricks/FluentFTP/assets/31951676/1e067fc5-5b5d-4822-a9d9-9c19efb6d8f7)

**Comment by Sharp2017** [comment]
Client Encoding=Encoding Default; Or client Encoding=Encoding UTF8; In. Under NET 8.0, Chinese characters are all garbled

**Comment by robinrodricks** [comment]
https://github.com/robinrodricks/FluentFTP/wiki/File-Transfer#how-can-i-uploaddownload-files-with-unicode-filenames-when-my-server-does-not-support-utf8
