### ISSUE TITLE
Code: 550 Message: Command STOR failed

### ISSUE THREAD

**Issue by bucc5062** [robinrodricks/FluentFTP#1583]
**FTP Server OS:** Unix 

**FTP Server Type:** WSFTP

**Client Computer OS:** Windows 10

**FluentFTP Version:** 50.0.1

**Framework:** .net 4.8

Starting with the simple code to test fluent:

```cs
            FtpClient client = new FtpClient(Constants.WilandHostName, Constants.WilandUserName, Constants.WilandPassword); // or set Host & Credentials
            client.AutoConnect();

            client.UploadFile($"{localPath}{fileNameToSend}", remotePath, FtpRemoteExists.Overwrite, false);
```

This FTP site is particular on how they open a folder for write permissions.  Given a remote folder, 
'/ParkSeedCompany_5919/in'

root is read only
ParkSeedCompany_5919 is read only
in is read/write

When I tested the ftp connection after getting access permissions is used Filzilla, I got a STOR error trying to go the root and the parent:
550 Permission denied

but I was able to move a file to the (in) child folder.

However, when I tried the above code, I could make the connection, but got the STOR error.

I should note that I also tried this using WINSCP and it also was failing.

So I am stuck because what I am building is a generic FTP processor for our company and while it works with other sites (their paths are all R/W I cannot get this to work in c#, I can only transfer data usign Filzilla and UI.

Not sure how that program can access the remote folders and the connection is a basic ftp connection, but somehow it has some different permissions or capability compared to Fluent or WINSCP.

The files is encoded as UTF8-BOM though I also tried UTF8

**Logs :**

```
Status:   FluentFTP 50.0.1.0(.NET Framework 4.7.2) FtpClient
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220-ftp_external X2 WS_FTP Server 8.8.5(66578859)
Response: Wiland File Transfer Server
Response: --Private Server---
Response: Files older than 7 days are subject to deletion.
Response: Unauthorized Access Prohibited. Violators Will Be Prosecuted.
Response: 220 ftp_external X2 WS_FTP Server 8.8.5(66578859) [739035.783d]
Status:   Detected FTP server: WSFTP
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Enter password [64ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230-User logged in
Response: Wiland SFTP
Response: 230 User logged in [87ms]
Command:  FEAT
Status:   Waiting for response to: FEAT
Response: 211-Extensions supported
Response: SIZE
Response: XMD5
Response: XSHA1
Response: XSHA256
Response: XSHA512
Response: XQUOTA
Response: LANG EN, ES, FR, GE
Response: MDTM
Response: MLST size*;type*;perm*;create*;modify*;
Response: REST STREAM
Response: TVFS
Response: UTF8
Response: AUTH SSL;TLS-P;
Response: PBSZ
Response: PROT C;P;
Response: 211 end [74ms]
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Status:   Waiting for response to: OPTS UTF8 ON
Response: 200 Command OPTS succeed [58ms]
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 UNIX [59ms]
Status:   Active ServerHandler is: WSFTP
Status:   Listing parser set to: Machine
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/" is current directory [58ms]

# UploadFile("C:\temp\Marketing\Wiland\PS\PS New Customers_20240530.csv", "/ParkSeedCompany_5919/in/PS New Customers_20240530.csv", Overwrite, False, None)

# FileExists("/ParkSeedCompany_5919/in/PS New Customers_20240530.csv")
Command:  SIZE /ParkSeedCompany_5919/in/PS New Customers_20240530.csv
Status:   Waiting for response to: SIZE /ParkSeedCompany_5919/in/PS New Customers_20240530.csv
Response: 550 File /ParkSeedCompany_5919/in/PS New Customers_20240530.csv not found [88ms]

# OpenWrite("/ParkSeedCompany_5919/in/PS New Customers_20240530.csv", Binary, -1, False)
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Transfer mode set to BINARY [60ms]

# OpenDataStream("STOR /ParkSeedCompany_5919/in/PS New Customers_20240530.csv", 0)

# OpenPassiveDataStream(AutoPassive, "STOR /ParkSeedCompany_5919/in/PS New Customers_20240530.csv", 0)
Command:  EPSV
Status:   Waiting for response to: EPSV
Response: 500 Unknown command EPSV [59ms]

# OpenPassiveDataStream(PASV, "STOR /ParkSeedCompany_5919/in/PS New Customers_20240530.csv", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Status:   Error encountered uploading file
Status:   IOException for file C:\temp\Marketing\Wiland\PS\PS New Customers_20240530.csv : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
Status:   Failed to upload file.
```

**Comment by FanDjango** [comment]
First, please set the config of the client to `FtpDataConnectionType.PASV` **after** the auto connect succeeds and try again, post the new log.

**Comment by bucc5062** [comment]
Yes!  That worked.   Thank you. See log below.  

I did this with setting working directory and I tried it with absolute and both worked.  Why did setting that parameter work?  It seemed like passive was the derfault.

            FtpClient client = new FtpClient(HostName, UserName, Password); // or set Host & Credentials

            client.Config.LogToConsole = true;
            client.AutoConnect();
            client.Config.DataConnectionType = FtpDataConnectionType.PASV;

            //client.SetWorkingDirectory("/ParkSeedCompany_5919/in");
            client.UploadFile(@"C:\temp\Marketing\Wiland\PS\PS New Customers_20240530.csv", "/ParkSeedCompany_5919/in/PS New Customers_20240530.csv", FtpRemoteExists.Overwrite, false);

---------------------------- Log ---------------
# AutoConnect()

# AutoDetect(CloneConnection = False, FirstOnly = True, IncludeImplicit = True, AbortOnTimeout = True, RequireEncryption = False, ProtocolPriority = [Tls11, Tls12])
Status:   Auto-Detect trying encryption mode "Auto" with "Tls11, Tls12"

# Connect(False)
Status:   FluentFTP 50.0.1.0(.NET Framework 4.7.2) FtpClient
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220-ftp_external X2 WS_FTP Server 8.8.5(11036245)
Response: Wiland File Transfer Server
Response: --Private Server---
Response: Files older than 7 days are subject to deletion.
Response: Unauthorized Access Prohibited. Violators Will Be Prosecuted.
Response: 220 ftp_external X2 WS_FTP Server 8.8.5(11036245) [739036.523d]
Status:   Detected FTP server: WSFTP
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 234 SSL enabled and waiting for negotiation [62ms]
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, 44550, 384) [270ms]
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Enter password [77ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230-User logged in
Response: Wiland SFTP
Response: 230 User logged in [125ms]
Command:  PBSZ 0
Status:   Waiting for response to: PBSZ 0
Response: 200 PBSZ=0 [58ms]
Command:  PROT P
Status:   Waiting for response to: PROT P
Response: 200 PRIVATE data channel protection level set [58ms]
Command:  FEAT
Status:   Waiting for response to: FEAT
Response: 211-Extensions supported
Response: SIZE
Response: XMD5
Response: XSHA1
Response: XSHA256
Response: XSHA512
Response: XQUOTA
Response: LANG EN, ES, FR, GE
Response: MDTM
Response: MLST size*;type*;perm*;create*;modify*;
Response: REST STREAM
Response: TVFS
Response: UTF8
Response: AUTH SSL;TLS-P;
Response: PBSZ
Response: PROT C;P;
Response: 211 end [64ms]
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Status:   Waiting for response to: OPTS UTF8 ON
Response: 200 Command OPTS succeed [59ms]
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 UNIX [58ms]
Status:   Active ServerHandler is: WSFTP
Status:   Listing parser set to: Machine
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/" is current directory [59ms]

# SetWorkingDirectory("/ParkSeedCompany_5919/in")
Command:  CWD /ParkSeedCompany_5919/in
Status:   Waiting for response to: CWD /ParkSeedCompany_5919/in
Response: 250 Command CWD succeed [74ms]

# UploadFile("C:\temp\Marketing\Wiland\PS\PSNewCustomers_20240530.csv", "PSNewCustomers_20240530.csv", Overwrite, False, None)

# FileExists("PSNewCustomers_20240530.csv")
Command:  SIZE /ParkSeedCompany_5919/in/PSNewCustomers_20240530.csv
Status:   Waiting for response to: SIZE /ParkSeedCompany_5919/in/PSNewCustomers_20240530.csv
Response: 550 File /ParkSeedCompany_5919/in/PSNewCustomers_20240530.csv not found [83ms]

# OpenWrite("PSNewCustomers_20240530.csv", Binary, -1, False)
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Transfer mode set to BINARY [60ms]

# OpenDataStream("STOR PSNewCustomers_20240530.csv", 0)

# OpenPassiveDataStream(PASV, "STOR PSNewCustomers_20240530.csv", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (209,133,36,87,195,212). [63ms]
Status:   Connecting to IP #1= ***:50132
Command:  STOR PSNewCustomers_20240530.csv
Status:   Waiting for response to: STOR PSNewCustomers_20240530.csv
Response: 150 Uploading in BINARY file PSNewCustomers_20240530.csv [59ms]
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, 44550, 384) [135ms]
Status:   Uploaded 1274915 bytes
Status:   Disposing(sync) FtpSocketStream(data connection of FtpClient)
Status:   Waiting for response to: STOR PSNewCustomers_20240530.csv
Response: 226 Transfer completed [1.279s]

**Comment by FanDjango** [comment]
> It seemed like passive was the derfault.

Actually it seems that "AutoPassive" is the default. And EPSV is thus tried first. WsFTP is a very "strange" implementation and has a number of quirks.

> And EPSV is thus tried first (quoting myself, now)

Since FEAT (see log) does **not** advertise the EPSV being available, I would wonder if we shouldn't change our code to **not try EPSV** in such a case.
