### ISSUE TITLE
cannot find the FluentFTP 47.1.0 release in github

### ISSUE THREAD

**Issue by mggch** [robinrodricks/FluentFTP#1591]
Hi everyone,

I'm using the FluentFTP 47.1.0, available as a Nuget package on the following link:
https://www.nuget.org/packages/FluentFTP/47.1.0

However, I could not find the release for the 47.1.0 in Github (the latest version I found is 20.0.0)

I would be very pleased if you can make available in Github the 47.1.0 version as it is for the 20.0.0.

Thanks

**Comment by FanDjango** [comment]
All releases are on nuget.

**Comment by robinrodricks** [comment]
Yes, and if anything is not on nuget, then it has not been released (there is no such version).
