### ISSUE TITLE
The remote certificate is invalid according to the validation procedure

### ISSUE THREAD

**Issue by jhullparkseed** [robinrodricks/FluentFTP#1600]
**FTP Server OS:** Windows 10/Server 2018
**FTP Server Type:** ???

**Client Computer OS:** Windows 

**FluentFTP Version:** 50.0.1.0

**Framework:** .NET 4.8

<write details about your bug report / feature request here>

# AutoConnect()

# AutoDetect(CloneConnection = False, FirstOnly = True, IncludeImplicit = True, AbortOnTimeout = True, RequireEncryption = False, ProtocolPriority = [Tls11, Tls12])
Status:   Auto-Detect trying encryption mode "Auto" with "Tls11, Tls12"

# Connect(False)
Status:   FluentFTP 50.0.1.0(.NET Framework 4.7.2) FtpClient
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220 pluto X2 WS_FTP Server 8.6.1(21478991) [739082.807d]
Status:   Detected FTP server: WSFTP
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 234 SSL enabled and waiting for negotiation [45ms]
Error:    FTPS Authentication failed, lib = .NET SslStream
Error:    The remote certificate is invalid according to the validation procedure.
Status:   Disposing(sync) FtpSocketStream(control connection of FtpClient)

# Disconnect()
Status:   Auto-Detect trying encryption mode "None"

# Connect(False)
Status:   FluentFTP 50.0.1.0(.NET Framework 4.7.2) FtpClient
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220 pluto X2 WS_FTP Server 8.6.1(24760178) [308ms]
Status:   Detected FTP server: WSFTP
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Non SSL connections forbidden [47ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***

# Disconnect()
Status:   Auto-Detect trying encryption mode "Implicit" with "Tls11, Tls12"

# Connect(False)
Status:   FluentFTP 50.0.1.0(.NET Framework 4.7.2) FtpClient
Status:   Connecting to IP #1= ***:990
Error:    FTPS Authentication failed, lib = .NET SslStream
**Error:    The remote certificate is invalid according to the validation procedure.**

# Disconnect()

----------------------------------------------
When I make a connection via Filezilla I always get a certificate error 
![Capture](https://github.com/user-attachments/assets/f7058fa4-d478-44c3-a269-3fd558948d9d)
and if I select yes then I complete the connection.

Is there some setting with fluent that gets me around that error.  The UID/PWD is correct, I verified that it is just the certificate error that stops the connection in fluent.

**Comment by FanDjango** [comment]
`client.Config.ValidateAnyCertificate = true;`

**Comment by jhullparkseed** [comment]
Just added thank you.  That did work.
