### ISSUE TITLE
UploadDirectory and DownloadDirectory to recursively transfer a whole folder

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#161]
Need these two methods to recursively upload a folder, by overwriting/skipping matching files on the server. 

Quick comparison checks:

1. File does exists
2. File size is different
3. File CRC mismatches - use CRC if supported for fast file contents comparison

If any of these checks fail, the file is transferred.

**Comment by NerijusD** [comment]
> Quick comparison checks:
> 1. File does exists
> 2. File size is different
> 3. File CRC mismatches - use CRC if supported for fast file contents comparison

`2. File size is different` this is not very good strategies, since file size could be the same, while data inside absolutely different.

**Comment by Hidend** [comment]
Is there any eta on this? @robinrodricks

**Comment by robinrodricks** [comment]
Released in version 30.0.0:

  - New: `UploadDirectory` and `UploadDirectoryAsync` methods to recursively upload or mirror a directory
  - New: `DownloadDirectory` and `DownloadDirectoryAsync` methods to recursively download or mirror a directory
  - New: Rule engine to filter files that should be uploaded/downloaded according to multiple user-defined rules
  - New: Predefined rules for filtering on folder name, useful for blacklisting certain system folders
  - New: Predefined rules for filtering on file name or file extensions, useful for transferring a subset of files
  - New: Predefined rules for filtering on file size, useful for filtering out very large files
  - New: Ability to determine parent/self/child directories in listing using `SubType` property of `FtpListItem`
  - Fix: Machine listings sometimes cause infinite recursion in `GetListing` when recursing into self directory
  - Change: `CreateDirectory` and `CreateDirectoryAsync` now return a flag indicating if it was created or skipped
  - Change: Use public fields instead of public properties for `FtpListItem`
  - Change: Improve performance of `CreateDirectory` by skipping the directory exists check
