### ISSUE TITLE
.NET8 configuration not enabling TLS 1.3 by default

### ISSUE THREAD

**Issue by kenkendk** [robinrodricks/FluentFTP#1623]
**FTP Server OS:** Any

**FTP Server Type:** Any

**Client Computer OS:** Any

**FluentFTP Version:** 50.1.0

**Framework:** .NET 8

The field `SslProtocols` on the `FtpConfig` class has XML documentation that says "Default value is .NET Framework defaults":
https://github.com/robinrodricks/FluentFTP/blob/a85172e8eee3b59676a9c6f5a5a2d4ea54290713/FluentFTP/Model/FtpConfig.cs#L270-L274

But as you can see it is actually using `SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls` which is not the default and is actually using deprecated values for .NET8.
Recommendation here is to use `SslProtocols.None` with comment: "Allows the operating system to choose the best protocol to use".

However, it seems FluentFTP is using `SslProtocols.None` to indicate "No encryption". 
From what I can read, it seems Windows 11 and .NET8 actually supports TLS 1.3, but the defaults in FluentFTP prevents this from being used by default.

What is the recommended approach to setting `SslProtocols` on .NET8 ?

**Comment by FanDjango** [comment]
> What is the recommended approach to setting SslProtocols on .NET8 ?

Nothing forbids you from specifying:

`client.Config.SslProtocols = SslProtocols.None`

This is passed to `ActivateEncryption` in `FtpSocketStream.cs` and would fullfill the following:

>Recommendation here is to use `SslProtocols.None`

It is in a different place where `SslProtocols.None` is misused to report back the type of connection (encrypted or not). I will change that. I will make a non-encrypted connection report back as being `SslProtocols.Unencrypted`. 

> From what I can read, it seems Windows 11 and .NET8 actually supports TLS 1.3, but the defaults in FluentFTP prevents this from being used by default.

Yes. That's right. We should perhaps make the defaults sensitive to the .NET version - trouble is, it currently **also** depends on the windows version.

Just set `client.Config.SslProtocols = SslProtocols.None` and you should be good to go. If not, give us a verbose log of the connect process and let's see what is going on.

> But as you can see it is actually using SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls which is not the default and is actually using deprecated values for .NET8.

XML text needs an update. When the initial woes of TLS1.3 emerged with nothing but trouble, we restricted the options to what worked for 99% of the users. We were inundated with WIN10+TLS1.3 problems.

**Comment by FanDjango** [comment]
Update: I have removed all "misused" references to `SslProtocols.None`. 
Now, all that is perhaps left over, is to "propose" the "best" defaults, as per the .NET version you are using. Sadly, this is currently not so easy - .NET8 is also used on Win10 and that does not support TLS1.3 in early to medium builds.

> SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls

The currently used "global" default, is IMO not really so great. If you were to use FluentFTP.GnuTLS you would get your TLS1.3 with no ado, by the way.

**Comment by kenkendk** [comment]
I was under the impression that using `SslProtocols.None` is **the** fix that will let Win10 use the old setup and others will get whatever makes sense? If so, it should be a matter of changing the default value in `FtpConfig` when building for .NET Core / Standard.

In any case, my worry was that using `None` would cause the library to drop encryption (really unfortunate naming from MS). As you have clarified, that is not the case, so I consider my questions answered, and will go with `None` as my default.

> The currently used "global" default, is IMO not really so great. If you were to use FluentFTP.GnuTLS you would get your TLS1.3 with no ado, by the way.

Yes, but then I would need to handle binaries for all supported platforms: MacOS Arm64+x64, Linux Armv7, Arm64, etc. If at all possible I prefer to use only managed code to remove those problems.
