### ISSUE TITLE
Trace per FtpClient connection

### ISSUE THREAD

**Issue by xaviergxf** [robinrodricks/FluentFTP#163]
Hi,

  Currently FtpClient is a static class. How can i use this with multiple concurrent ftp downloads across several ftp servers? What is the procedure to contribute in this repository?

Thanks,
Xavier

**Comment by hgupta9** [comment]
You mean FtpTrace is a static class? Yes you can make it dynamic I guess, but why would you need that? You don't need to trace except for debugging purposes, and if you need a production logger, you would only need errors in which case one logger should be fine. 

FAQ : https://github.com/hgupta9/FluentFTP#faq_fork

**Comment by robinrodricks** [comment]
Unless you reply why this is needed, I'm closing it. We can implement this feature provided there is a real and useful use case.
