### ISSUE TITLE
Is there a Disconnected-Event?

### ISSUE THREAD

**Issue by GeorgRottensteiner** [robinrodricks/FluentFTP#1631]
*FAQ*
The library is nice, I tried doing something like this myself but couldn't keep up with changes. I've added it to my FTP client, along with SSH.NET. 
Is there any possibility to get notified once the connection is closed remotely?

It's nice to see whether you're still connected or not.

**Comment by FanDjango** [comment]
> Is there any possibility to get notified once the connection is closed remotely?

This has been asked before. FluentFTP currently has no event mechanism implemented. You would need to implement this **using FluentFTPs** `IsStillConnected` API or **using the NOOP Daemon** with a suitably small interval in your own code.

> It's nice to see whether you're still connected or not.

Yes, I agree. Sadly, unless you yourself has closed the connection or the host has closed the connection cleanly (RST, FIN), you are in the dark.

**The only way, is to repeatedly query the connection state after sending something to the remote**. This would then timeout (no ACK etc.). Sadly, this entails suffering from a timeout delay before you know where you are at.

This is in a large part a problem of TCP, but FTP (which is an early old protocol on top of FTP) itself **could have** added some kind of _regular ping/echo_ or whatever to cater to such a desire. But alas...

**Comment by GeorgRottensteiner** [comment]
I feared as much. At least it's nothing impossible :)

Thanks!
