### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by sterenas** [robinrodricks/FluentFTP#1651]
Hi, sorry I may be lost here.  Looking for release notes for the last few versions.  Page https://github.com/robinrodricks/FluentFTP/releases seems to be well outdated.  Should I look elsewhere?
Been having lots of trouble with the async version of upload and was wondering if it got some love (actually changed to sync and no problem since then).
Thanks!

**Comment by FanDjango** [comment]
Here: https://github.com/robinrodricks/FluentFTP/blob/master/RELEASES.md
