### ISSUE TITLE
FtpCommandException: Code: 550 Message: Can't check for file existence

### ISSUE THREAD

**Issue by mattiaslundborg** [robinrodricks/FluentFTP#1658]
**FTP Server OS:** Windows

**FTP Server Type:** not sure, how can i check this?

**Client Computer OS:** Windows

**FluentFTP Version:** 51.1.0

**Framework:** .NET 8

**Trying to upload files to FTP server. Here is the flow it should follow:**
1. Create directory
2. Upload artwork
3. Upload song
4. Upload atmos song
5. Upload metadata file
6. Upload empty confirmation file

**Here are the results:**
1. It manages to create the directory
2. upload the png
3. seems to not be able to upload the song?
4. uploads the atmos song
5. crashes when uploading the metadata file:

Failed to upload file to 8721093032076/8721093032076.xml: Error while uploading the file to the server. See InnerException for more info.
 ---> FluentFTP.Exceptions.FtpCommandException: Code: 550 Message: Can't check for file existence
 
 I also want to add that this started to happen today, this flow have been working before.

**Logs :**

```

# DirectoryExists("8721093032076")
Command:  CWD 8721093032076
Status:   Waiting for response to: CWD 8721093032076
Response: 550 Can't change directory to 8721093032076: No such file or directory [30ms]

# CreateDirectory("8721093032076", True)

# DirectoryExists(".")
Status:   CreateDirectory 8721093032076
Command:  MKD 8721093032076
Status:   Waiting for response to: MKD 8721093032076
Response: 257 "8721093032076" : The directory was successfully created [29ms]

# UploadStream("8721093032076/8721093032076.png", Overwrite, False)

# FileExists("8721093032076/8721093032076.png")
Command:  SIZE /8721093032076/8721093032076.png
Status:   Waiting for response to: SIZE /8721093032076/8721093032076.png
Response: 550 Can't check for file existence [31ms]

# OpenWrite("8721093032076/8721093032076.png", Binary, -1, False)

# OpenDataStream("STOR 8721093032076/8721093032076.png", 0)

# OpenPassiveDataStream(PASV, "STOR 8721093032076/8721093032076.png", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (178,237,44,159,132,132) [32ms]
Status:   Connecting(sync) FtpClient.FtpSocketStream(data) IP #1 = ***:33924
Command:  STOR 8721093032076/8721093032076.png
Status:   Waiting for response to: STOR 8721093032076/8721093032076.png
Response: 150 Accepted data connection [31ms]
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 44550, 256) [29ms]
Status:   Uploaded 17388936 bytes, 872ms, 19 MB/s
Status:   Disposing(sync) FtpClient.FtpSocketStream(data)
Status:   Waiting for response to: STOR 8721093032076/8721093032076.png
Status:   Disposing(sync) FtpClient.FtpSocketStream(data) (redundant)
Status:   Error encountered uploading file
Status:   IOException for file  : Unable to read data from the transport connection: The connection attempt failed because the connected computer did not respond within a certain time or because the established connection to the host computer no longer works.

# UploadStream("8721093032076/8721093032076.wav", Overwrite, False)

# FileExists("8721093032076/8721093032076.wav")
Command:  SIZE /8721093032076/8721093032076.wav
Status:   Waiting for response to: SIZE /8721093032076/8721093032076.wav
Status:   Error encountered uploading file
Status:   IOException for file  : Unable to read data from the transport connection: The connection attempt failed because the connected computer did not respond within a certain time or because the established connection to the host computer no longer works.

# UploadFile("C:\Users\mypc\AppData\Local\Temp\8721093032076_atmos.wav", "8721093032076/8721093032076_atmos.wav", Overwrite, False, None)

# FileExists("8721093032076/8721093032076_atmos.wav")
Status:   Control connection has stale data(218) - prior to Execute("SIZE...")
Status:   The stale data was (length = 131):
Stale:    226-File successfully transferred
Stale:    226 1.055 seconds (measured here), 15.73 Mbytes per second
Stale:    550 Can't check for file existence
Warning:  Reconnect needed due to stale data present on control connection (SslSessionLength: 27)
Status:   Disposing(sync) FtpClient.FtpSocketStream(control) (redundant)
Status:   Command stashed: SIZE /8721093032076/8721093032076_atmos.wav

# Connect(True)
Warning:  Reconnect (Count: 2)
Status:   FluentFTP 51.1.0.0(.NET 6.0) FtpClient
Status:   Connecting(sync) FtpClient.FtpSocketStream(control) IP #1 = ***:21
Status:   Waiting for a response
Response: 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response: 220-You are user number 32 of 100 allowed.
Response: 220-Local time is now 17:42. Server port: 21.
Response: 220-This is a private system - No anonymous login
Response: 220 You will be disconnected after 15 minutes of inactivity. [54,172s]
Status:   Detected FTP server: PureFTPd
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 234 AUTH TLS OK. [31ms]
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 44550, 256) [41ms]
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 User *** OK. Password required [57ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230 OK. Current restricted directory is / [220ms]
Command:  PBSZ 0
Status:   Waiting for response to: PBSZ 0
Response: 200 PBSZ=0 [29ms]
Command:  PROT P
Status:   Waiting for response to: PROT P
Response: 200 Data protection level set to "private" [27ms]
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Status:   Waiting for response to: OPTS UTF8 ON
Response: 200 OK, UTF-8 enabled [30ms]
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 UNIX Type: L8 [28ms]
Status:   Active ServerHandler is: PureFTPd
Status:   Listing parser set to: Machine
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 TYPE is now 8-bit binary [39ms]

# SetWorkingDirectory("/")
Command:  CWD /
Status:   Waiting for response to: CWD /
Response: 250 OK. Current directory is / [30ms]

Status:   Executing stashed command

Command:  SIZE /8721093032076/8721093032076_atmos.wav
Status:   Waiting for response to: SIZE /8721093032076/8721093032076_atmos.wav
Response: 550 Can't check for file existence [29ms]

# OpenWrite("8721093032076/8721093032076_atmos.wav", Binary, -1, False)

# OpenDataStream("STOR 8721093032076/8721093032076_atmos.wav", 0)

# OpenPassiveDataStream(PASV, "STOR 8721093032076/8721093032076_atmos.wav", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (178,237,44,159,119,113) [30ms]
Status:   Connecting(sync) FtpClient.FtpSocketStream(data) IP #1 = ***:30577
Command:  STOR 8721093032076/8721093032076_atmos.wav
Status:   Waiting for response to: STOR 8721093032076/8721093032076_atmos.wav
Response: 150 Accepted data connection [29ms]
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 44550, 256) [33ms]
Status:   Uploaded 948437966 bytes, 57,71s, 15,7 MB/s
Status:   Disposing(sync) FtpClient.FtpSocketStream(data)
Status:   Waiting for response to: STOR 8721093032076/8721093032076_atmos.wav
Status:   Disposing(sync) FtpClient.FtpSocketStream(data) (redundant)
Status:   Error encountered uploading file
Status:   IOException for file C:\Users\mypc\AppData\Local\Temp\8721093032076_atmos.wav : Unable to read data from the transport connection: The connection attempt failed because the connected computer did not respond within a certain time or because the established connection to the host computer no longer works.
Status:   Failed to upload file.

# UploadStream("8721093032076/8721093032076.xml", Overwrite, False)

# FileExists("8721093032076/8721093032076.xml")
Command:  SIZE /8721093032076/8721093032076.xml
Status:   Waiting for response to: SIZE /8721093032076/8721093032076.xml
Response: 226-File successfully transferred
Response: 226 57.909 seconds (measured here), 15.62 Mbytes per second [11,306s]

# DeleteFile("8721093032076/8721093032076.xml")
Command:  DELE 8721093032076/8721093032076.xml
Status:   Waiting for response to: DELE 8721093032076/8721093032076.xml
Response: 550 Can't check for file existence [<1ms]
Status:   Error encountered uploading file

```

**Comment by FanDjango** [comment]
> FTP Server Type: not sure, how can i check this?

If you look at the connect sequence at the beginning of a log, you should see messages that can tell you this. But you have not supplied a total log. How sad...

Luckily enough (actually not lucky, but because of an automatic reconnect) there is a connect sequence later on in the log. You don't look at your own logs?

```
Status:   FluentFTP 51.1.0.0(.NET 6.0) FtpClient
Status:   Connecting(sync) FtpClient.FtpSocketStream(control) IP #1 = ***:21
Status:   Waiting for a response
Response: 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response: 220-You are user number 32 of 100 allowed.
Response: 220-Local time is now 17:42. Server port: 21.
Response: 220-This is a private system - No anonymous login
Response: 220 You will be disconnected after 15 minutes of inactivity. [54,172s]
```

> I also want to add that this started to happen today, this flow have been working before.

What has changed?

> 2. upload the png

```
Command:  STOR 8721093032076/8721093032076.png
Status:   Waiting for response to: STOR 8721093032076/8721093032076.png
Response: 150 Accepted data connection [31ms]
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 44550, 256) [29ms]
Status:   Uploaded 17388936 bytes, 872ms, 19 MB/s
Status:   Disposing(sync) FtpClient.FtpSocketStream(data)
Status:   Waiting for response to: STOR 8721093032076/8721093032076.png
Status:   Disposing(sync) FtpClient.FtpSocketStream(data) (redundant)
Status:   Error encountered uploading file
Status:   IOException for file  : Unable to read data from the transport connection: The connection attempt failed because the connected computer did not respond within a certain time or because the established connection to the host computer no longer works.
```

The png upload worked, as you can see in a later, very much delayed (? timing, timestamps in log) success response. But the server has closed the data connection after the data transfer and then things went wrong.

```
# FileExists("8721093032076/8721093032076.png")
Command:  SIZE /8721093032076/8721093032076.png
Status:   Waiting for response to: SIZE /8721093032076/8721093032076.png
Response: 550 Can't check for file existence [31ms]
```

Sequence like this are normal, it is checking if the file exists already and needs to be deleted first prior to upload.

The real problem is the very much delayed success response after the png upload, you can see how this success response is discovered as 'stale data' before the command upload of the next file:

```
# UploadFile("C:\Users\mypc\AppData\Local\Temp\8721093032076_atmos.wav", "8721093032076/8721093032076_atmos.wav", Overwrite, False, None)

# FileExists("8721093032076/8721093032076_atmos.wav")
Status:   Control connection has stale data(218) - prior to Execute("SIZE...")
Status:   The stale data was (length = 131):
Stale:    226-File successfully transferred
Stale:    226 1.055 seconds (measured here), 15.73 Mbytes per second
Stale:    550 Can't check for file existence
```

**Comment by FanDjango** [comment]
So:

1. What might have changed, if it was working before?
2. Can you prepend timestamps to the log lines so the one can see the timings on the png upload sequence?

**Comment by mattiaslundborg** [comment]
Hi! 

Thats odd, i'm not seeing that first section of the log. It only shows when it reconnects..

1. It has been working for months and just a few hours ago. Nothing new has been pushed. Can the cause be the supplier of the FTP? Unstable connection? Or is it isolated to me?

2. Yes sure, i've attached the log file from SeriLog with timestamps:
[FluentFTPLogs20241002.txt](https://github.com/user-attachments/files/17234471/FluentFTPLogs20241002.txt)

**Comment by FanDjango** [comment]
Thanks, that's great. Look:
```
2024-10-02 20:27:02.729 +02:00 [DBG] Uploaded 8795614 bytes, 982ms, 8,5 MB/s
2024-10-02 20:27:02.729 +02:00 [DBG] Disposing(sync) FtpClient.FtpSocketStream(data)
2024-10-02 20:27:02.730 +02:00 [DBG] Waiting for response to: STOR 8721093034544/8721093034544.png
2024-10-02 20:27:17.736 +02:00 [DBG] Disposing(sync) FtpClient.FtpSocketStream(data) (redundant)
2024-10-02 20:27:17.736 +02:00 [DBG] Error encountered uploading file
2024-10-02 20:27:17.736 +02:00 [DBG] IOException for file 
```
15 seconds waiting for a response to the STOR command (i.e. waiting for the 226 message) which arrives much later.

Something is dreadfully slow. 

And strange, in the new log there is
```
2024-10-02 20:27:49.790 +02:00 [INF] Command:  SIZE /8721093034544/8721093034544.png
2024-10-02 20:27:49.790 +02:00 [DBG] Waiting for response to: SIZE /8721093034544/8721093034544.png
2024-10-02 20:27:55.411 +02:00 [DBG] Response: 226-File successfully transferred
2024-10-02 20:27:55.411 +02:00 [INF] Response: 226 1.227 seconds (measured here), 6.84 Mbytes per second [5,621s]
2024-10-02 20:27:56.341 +02:00 [INF] >         UploadStream("8721093034544/8721093034544.wav", Overwrite, False)
2024-10-02 20:27:56.342 +02:00 [INF] >         FileExists("8721093034544/8721093034544.wav")
2024-10-02 20:27:56.342 +02:00 [INF] Control connection has stale data(39) - prior to Execute("SIZE...")
2024-10-02 20:27:56.342 +02:00 [DBG] The stale data was (length = 39): 
2024-10-02 20:27:56.343 +02:00 [DBG] Stale:    213 8795614
2024-10-02 20:27:56.343 +02:00 [DBG] Stale:    213 8795614
2024-10-02 20:27:56.343 +02:00 [DBG] Stale:    213 8795614
2024-10-02 20:27:56.343 +02:00 [WRN] Reconnect needed due to stale data present on control connection
2024-10-02 20:27:56.344 +02:00 [DBG] Disposing(sync) FtpClient.FtpSocketStream(control)
2024-10-02 20:27:56.344 +02:00 [INF] Command stashed: SIZE /8721093034544/8721093034544.wav
```

Look at the "extraneous" 213 nnnnnnn responses that are output. Some one doing a STAT command **during** the file transfer?

It would be important to see the initial connect in the log also, to see the FEAT response. STAT allowed? Other option suddenly active per default?

**Comment by mattiaslundborg** [comment]
Thanks FanDjango. I'm not sure how i can supply the initial connect log to you. Here is my code for the initial connect:

`        var _client = new FtpClient(ftpServer, ftpUsername, ftpPassword);
        _client.AutoConnect();
        _client.Config.LogToConsole = true;
        
        var serilogLogger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .WriteTo.File("logs/FluentFTPLogs.txt", rollingInterval: RollingInterval.Day)
            .CreateLogger();
        
        var microsoftLogger = new SerilogLoggerFactory(serilogLogger)
            .CreateLogger("FTP");
        
        _client.Logger = new FtpLogAdapter(microsoftLogger);`
        
I tried a new upload and the first rows in the log file looks like this again:

`2024-10-02 20:54:00.815 +02:00 [INF] >         DirectoryExists("8721093033608")
2024-10-02 20:54:00.829 +02:00 [INF] Command:  CWD 8721093033608
2024-10-02 20:54:00.829 +02:00 [DBG] Waiting for response to: CWD 8721093033608
2024-10-02 20:54:00.877 +02:00 [INF] Response: 550 Can't change directory to 8721093033608: No such file or directory [47ms]
2024-10-02 20:54:00.878 +02:00 [INF] >         CreateDirectory("8721093033608", True)
2024-10-02 20:54:00.879 +02:00 [INF] >         DirectoryExists(".")`

**Comment by FanDjango** [comment]
The AutoConnect should happen after the log setup.

**Comment by mattiaslundborg** [comment]
[FluentFTPLogs_Connection.txt](https://github.com/user-attachments/files/17234858/FluentFTPLogs_Connection.txt)

**Comment by mattiaslundborg** [comment]
Yes i can definitely try that, getting back soon..

**Comment by mattiaslundborg** [comment]
I did everything with UploadFile now instead, attached logfile for that.

[FluentFTPLogs20241002_UploadFile.txt](https://github.com/user-attachments/files/17235043/FluentFTPLogs20241002_UploadFile.txt)

**Comment by FanDjango** [comment]
Also, JUST for testing, consider adding
```
				client.Config.Noop = true;
				client.Config.NoopInterval = 750;
```
to switch response waiting and analysis and logging to a different mode. It wont make it work any better, but maybe I can see more.

**Comment by mattiaslundborg** [comment]
[FluentFTPLogs20241002_WithNoop.txt](https://github.com/user-attachments/files/17235092/FluentFTPLogs20241002_WithNoop.txt)

**Comment by FanDjango** [comment]
Oh, the NOOP test was very interesting. "Unknown command" ????. Tomorrow I will quickly put together a VM with pure-FTPd and check this out.

What the heck is "200 Zzz..."???? Never seen that either.

Thanks for the debug help. I'll stay on this to find out what is going on. Please: You need to check for an old log that shows how it was working, you need to check older versions of your program. Something is fishy.

**Comment by FanDjango** [comment]
> What the heck is "200 Zzz..."???? Never seen that either.

Ok, some servers reply to a NOOP command with this, when there is no transfer running. Duh. Never saw it before.

**Comment by mattiaslundborg** [comment]
Appreciate the help. Regarding older logs => i don't write FluentFTP logs to file, i only log my own to database.

However, i will also try tomorrow morning to see if i get better results then. Let keep in touch here then? 

Thanks again!

**Comment by FanDjango** [comment]
From the logs with timestamps, it looks to me like the server needs up to 60 seconds or more to store the file you upload and to generate the success reply. Further interactions after the timeout of 15 seconds fail, as the server is still "busy". 

One thing you might do is to increase the read timeout to 60 seconds (client config) and test that. Oh and for that test, remove the NOOP, that was just to see more.

**Comment by mattiaslundborg** [comment]
Hi, attached logs for this change:

        _client.Config.ReadTimeout = 60000;
        

Not getting the IOException now?
     
[FluentFTPLogs20241003.txt](https://github.com/user-attachments/files/17239865/FluentFTPLogs20241003.txt)

**Comment by FanDjango** [comment]
Ok. It's looking good now, isn't it?

Here is a thing you should do: Never issue the next API call (i.e. the second download) before you have checked the success of the previous one. In the logs, one saw that all the subsequent API calls also failed because the server was still hanging in the response to the first download. All the subsequent responses were queued behind that.

> However, its taking 12 seconds for that first image upload. While it takes 3 seconds for the song to upload (which is bigger in file), isn't that strange?

Yes, extremely so.

Remember, I wrote

> Something is dreadfully slow.

Perhaps the png is being stored "somewhere" else? Or it is being copied from a staging area to the final resting place.

Note that the server might be buffering the incoming bytes so the actual TCP send (from the viewpoint of the client) is over rather quickly, while after sending all the bytes ("uploaded nnnnn bytes") you still need to wait for the server to "226 upload successful" confirm that the upload was completed.

**Comment by FanDjango** [comment]
Also note that in your logs of last night, the responses were actually not ~12 seconds, they were more like 50 seconds or so.

**Comment by mattiaslundborg** [comment]
I'm downloading the files from Azure Blob Storage into a MemoryStream and writing that stream to client.UploadStream.

I've also implemented that i check if the file exists before continuing to the next upload. This was implemented before i sent the latest log file.

**Comment by FanDjango** [comment]
> I've also implemented that i check if the file exists before continuing to the next upload.

But remember: Only do that, if the previous API (the upload) returned a success result. If it did not, the the file exists check (which is a command to the server) will fail (also after some timeout), it will have its response queued behind the not yet received response of the upload etc. etc. etc.

But if the previous API (the upload) returned a success result, then you don't really need the file exists check, I would probably trust the success.

**The real problem** is to continue sending API calls (which result in FTP commands to the non-responsive server) if the upload response has not been received (**yet**).

**Comment by FanDjango** [comment]
@mattiaslundborg Ok, so what do we do now? Can we close this? Is it cleared up for you? I cannot explain why the server behaviour has changed - especially the long long time to confirm upload success.

**Comment by mattiaslundborg** [comment]
I guess we can close this. I will investigate more from my side. I'm satisfied with how it works right now, even though it takes longer time for the initial upload (the first file).

Thank you @FanDjango for discussing and helping me out!
