### ISSUE TITLE
Server timezone configuration

### ISSUE THREAD

**Issue by yarmoliq** [robinrodricks/FluentFTP#1680]
Currently server time zone is configured using double (hours offset). What if the server has a timezone where they switch to winter/summer time? Then the offset will be dynamic, not constant? Maybe timezone configuration should use standard dotnet functionality that can account for such cases?

**Comment by FanDjango** [comment]
As you seem to have a clear preconception of the technique and details of what should be done, could you provide details / code / PR of a possible enhancement towards this goal?

**Comment by yarmoliq** [comment]
Here is an example of using `TimeZoneInfo`:
```c#
TimeZoneInfo easternZone = TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");
DateTime currentEasternTime = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, easternZone);
```

**Comment by FanDjango** [comment]
Oh, thanks. So?

**Comment by FanDjango** [comment]
As FTP servers report times (such as file creation timestamps) in a way that is undefined in the RFCs, typically though UTC, any timezone logic in FluentFTP is actually just added value - there is no-one stopping you from converting times again yourself in those cases where you know the timezone of the server, i.e. you know the server and its locale.

If you think that there should be additional code in the current timezone logic (which is just there to help a little bit), then be so kind as to provide it and save us some work.

I do also think you might have a valid point to do automatic daylight saving time conversion as it setup for those locations that have that.

**Comment by robinrodricks** [comment]
This is a good point. We had been using an outdated means of configuring timezones using offsets.

This has been fixed in the latest release: https://www.nuget.org/packages/FluentFTP/52.0.0

Please read: https://github.com/robinrodricks/FluentFTP/wiki/Timezone-Conversion

**Comment by robinrodricks** [comment]
@yarmoliq I would request you to check the new API and report back if there are any issues.
