### ISSUE TITLE
"UserName can't be empty" should not happen in real world

### ISSUE THREAD

**Issue by Rayzbam** [robinrodricks/FluentFTP#1689]
I have an issue since updating to v52.0.0 where i can't initialize a client without username.

I can understand this check but, unfortunately, i have some FTP server where i have to connect without any username/password.
I know it's not a good practice but these FTP are managed by other companies and can't do anything about it (I think they work with IP whitelisting and don't want to handle multiple credentials for all their clients).

![image](https://github.com/user-attachments/assets/793a245b-714b-45ef-bb26-bc816ab89a3f)

Can you remove this check on AsyncFTPClient constructor ?
At least don't check the length maybe, so you can check the null value and i'll force to pass an empty string (it's maybe more clear to specifiy that i did it in purpose ?)

PS : It seems that you added the same check on password, so i'll have the same issue on it i guess .. Unfortunately

**Comment by robinrodricks** [comment]
If u want a blank user/pass, pass the value `anonymous`.

**Comment by Rayzbam** [comment]
Oh didn't know about it.
Thanks for the help.

**Comment by FanDjango** [comment]
LOL I didn't know either - until I looked at the code to see what fixing this would entail.
