### ISSUE TITLE
ClientCertificates not working in .NET Core 1.1

### ISSUE THREAD

**Issue by hung-doan** [robinrodricks/FluentFTP#171]
I got "The remote certificate is invalid according to the validation procedure." event if I define a certificate. 

I checked certificate in events "e", and my own instance of X509Certificate2, they are the same but I still see error in e.PolicyErrors. 

````

_ftpClient.EncryptionMode = FtpEncryptionMode.Explicit;
_ftpClient.SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12;
_ftpClient.SocketKeepAlive = false;

// Trust SSL Cer
_ftpClient.ClientCertificates.Add(new X509Certificate2("C:\mycert.cer"));

// Tried this aswell _ftpClient.ClientCertificates.Add(new X509Certificate("C:\mycert.cer"));

_ftpClient.ValidateCertificate += (control, e) =>
{
	e.Accept = e.PolicyErrors == SslPolicyErrors.None;

};
_ftpClient.Connect();
        
````

**Comment by hgupta9** [comment]
Can you try the example code of comparing the certificate as plain text instead?

**Comment by robinrodricks** [comment]
Please reply if you still have this issue with the latest version.
