### ISSUE TITLE
Upload() method does not have Retry implemented

### ISSUE THREAD

**Issue by rogeroliveira84** [robinrodricks/FluentFTP#177]
Looking into the code I could not find the **Retry option** for the `Upload()` method, only for the `UploadFromFile`, `DownloadFromFile`, etc.

In the `Upload `method the `UploadFileInternal `method has the `ResumeUpload ` that throws an error if can't re-connect and don't retry the `Upload `method after it?

```
while (offset < len) {
    try {
        // read a chunk of bytes from the file
        int readBytes;
            while ((readBytes = await fileData.ReadAsync(buffer, 0, buffer.Length, token)) > 0) {
            // write chunk to the FTP stream
            await upStream.WriteAsync(buffer, 0, readBytes, token);
            await upStream.FlushAsync(token);
            offset += readBytes;
    }
    } catch (IOException ex) {

        // resume if server disconnected midway, or throw if there is an exception doing that as well
        if (!ResumeUpload(remotePath, ref upStream, offset, ex)) {
            throw;
        }
    }
}
```

Am I right or I overlooked something?

Thanks :)

**Comment by hgupta9** [comment]
We'll do it as time permits. Thanks for the discovery.

**Comment by robinrodricks** [comment]
Added to the [bucket list](https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans). We will pick this up as and when we have free time. Comment on this issue if you want us to prioritize it. Thanks!

**Comment by FanDjango** [comment]
This has been done. Removing from the bucket list.

**Comment by robinrodricks** [comment]
Awesome!
