### ISSUE TITLE
Not opening the socket for active connection when downloading multiple files in sequence

### ISSUE THREAD

**Issue by artiomchi** [robinrodricks/FluentFTP#183]
So this is a strange one, but hopefully I've traced the issue correctly so far.

We just switched to FluentFTP, and our system is downloading multiple files from various locations. Almost immediately, we noticed a large influx of the following error:

> [System.InvalidOperationException]: You must call the Bind method before performing this operation.
    at System.Net.Sockets.Socket.DoBeginAccept(LazyAsyncResult asyncResult)
    at System.Net.Sockets.Socket.BeginAccept(AsyncCallback callback, Object state)
    at FluentFTP.FtpClient.OpenActiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
    at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
    at FluentFTP.FtpClient.OpenRead(String path, FtpDataType type, Int64 restart, Boolean checkIfFileExists)
    at FluentFTP.FtpClient.DownloadFileInternal(String remotePath, Stream outStream)

Tracking the code, when connecting to an active ftp server, before calling to `BeginAccept`, you're trying to open a listener for the active connection (`FtpClient_LowLevel.cs`:205). In `FtpSocketStream`:966.`Listen()` method, you're running `Bind`, but only when `IsConnected` is false (which internally checks the status of `m_socket`

Something tells me that the socket is somehow not closed/disposed and "bleeds" over to the other FtpClient.

Here's a snippet that we use to replicate the issue. So far, we're consistently getting this exception, usually on the second loop.

```csharp
FtpTrace.EnableTracing = true;
FtpTrace.AddListener(new ConsoleTraceListener());
for (int i = 0; i < 50; i++)
{
	using (var client = new FtpClient("host")
	{
		DataConnectionType = FtpDataConnectionType.PORT,
		ActivePorts = Enumerable.Range(5000, 501),
		Credentials = new NetworkCredential("login", "password"),
	})
	{
		client.Connect();

		var downloaded = client.DownloadFile(filePath, "CITC_C.xml");
	}
}
```

(I'm using `PORT` instead of `AutoActive`, because that causes a `550: PermanentNegativeCompletion from the server`, if you're wondering)

**Comment by artiomchi** [comment]
I've temporarily resolved this by setting `EnableThreadSafeDataConnections` to true, but I'd rather not have to do that

**Comment by hgupta9** [comment]
Little complicated.. I don't understand what's going on... I am not the author of the FTP stream / low level methods so I don't really know how they work. I know this library has many edge cases and bugs at run time. They are really hard to fix...

**Comment by hgupta9** [comment]
Can you specify the server & OS?

**Comment by artiomchi** [comment]
Running these tests on Windows 10 and Server 2016. The code was running in production on Server 2012 R2 / Server 2016.

Interestingly enough, when we forced the library to use different starting ports, the issue was sort of aleviated, and it was running a lot more stable, but it wasn't perfect, and didn't sound like a good solution for production use:

```csharp
ActivePorts = Enumerable.Range(5000 + i, 501),
```

**Comment by FanDjango** [comment]
This actually works now. The logic in `FtpSocketStream` has changed extensively since 2017. See also #957
