### ISSUE TITLE
Current data type not set when using EnableThreadSafeDataConnections

### ISSUE THREAD

**Issue by bgroenks96** [robinrodricks/FluentFTP#184]
`EnableThreadSafeDataConnections` causes the `SetDataType` method to only be called on the "cloned" connection the server, and not on the original. In certain cases, such as downloading zero size files, this causes `DownloadFileInternal` to throw an exception because it thinks the data type is still ASCII.

**Comment by hgupta9** [comment]
Do you need enablethreadsafe? It's an old buggy method created by the original author. Can you not just use a background worker or proper thread and create one FTP client instance on each thread? Or even one client can be accessed from multiple threads because we have implement our own locking..

**Comment by bgroenks96** [comment]
Not sure I agree that this is incorrect usage; as long as the API exists and is non-deprecated, it shouldn't cause bugs like this.

Using `EnableThreadSafeDataConnections` fixes several issues I was having with the library causing hangs while downloading/uploading files. The issue with managing my own separate client is that the worker thread is being used internally to my FTP client.

I'll take another look to see if I can avoid that, but I still think this should be fixed. I actually fixed it in my fork, if you want me to submit a PR for it.

**Comment by hgupta9** [comment]
Absolutely. Any fixes are much appreciated...
