### ISSUE TITLE
How to Download a file from ftp to another server

### ISSUE THREAD

**Issue by guicamarotto** [robinrodricks/FluentFTP#189]
I need to download a file from a FTP to a local server.

Im trying using DownloadFile, but I get the error "parameter invalid". Here's the code.

```
var file = "myfile.txt";
var dwnFile = "\\vmserver\folder\" + file;
var remotePath = "ftp://myftp.com";
FtpClient client = new FtpClient();
client.Host = remotePath;
client.Credentials = new NetworkCredential(usuario, senha);
client.Connect();
remotePath += file;
client.DownloadFile(dwnFile, remotePath, true, FtpVerify.None);
```

**Comment by artiomchi** [comment]
I've just tested it, and it seems to work perfectly fine on my side. Are you sure you're escaping the path correctly?

i.e.
```csharp
var dwnFile = @"\\vmserver\folder\" + file;
```

You could in theory open your own FileStream to the remote file, and use the other download method:
```csharp
client.Download(fileStream, remotePath);
```

Also, do you have a stack trace for the exception, and which framework are you building against?

**Comment by hgupta9** [comment]
Thank you @artiomchi for filling in for me!
