### ISSUE TITLE
GetModifiedTime sometimes returns DateTime.MinValue

### ISSUE THREAD

**Issue by SuhovDE** [robinrodricks/FluentFTP#191]
Hi,

Sometimes GetModifiedTime function returns DateTime.MinValue for random files. But with next reading later, it works correctly.

Trace doesn't contain any errors:
```
# GetModifiedTime("Filename.txt", Original)
Command:  MDTM Filename.txt
Response: 226 Successfully transferred "Filename.txt" 
Status:   Disposing FtpSocketStream...
```
What can be a reason and how to escape this issue?

Version 18.0.2.0.
When we used version 16.5 we didn't notice such issue

**Comment by hgupta9** [comment]
I'll check the code but can you specify OS and FTP server?

**Comment by SuhovDE** [comment]
Hi, Robin,

Sorry for the delay.
The command SYST returns 
`215 UNIX emulated by FileZilla`

I will also try to get more information from FTP server owner if you need it.

**Comment by robinrodricks** [comment]
Sorry for the delay.

You can see the code at 16.5 is here : https://github.com/robinrodricks/FluentFTP/blob/feea5114bdfc83fef6a5a95ce8b12629c7d5a3fe/FluentFTP/FtpClient.cs#L5018

And the code at latest version : https://github.com/robinrodricks/FluentFTP/blob/a8b967768ca02cff853f65821457055e2c097bc5/FluentFTP/Client/FtpClient_Management.cs#L2009

The behavior is exactly the same. Even the older code may return DateTime.MinValue if the command is not a success.

**Comment by SuhovDE** [comment]
Hi Robin,

I have not found any significant difference too. But the fact remains the fact, or maybe it is an incident.

In any case when we find something I will let you know.

Thank you for investigation

**Comment by robinrodricks** [comment]
I'm closing this because I don't know what to fix.
