### ISSUE TITLE
Issue with csv file uploads as a list

### ISSUE THREAD

**Issue by stufano** [robinrodricks/FluentFTP#192]
Hey all,

I am doing an upload of multiple files and they are not all making it to the FTP. I am getting an inner exception. Also in debug if I set a break point some will go and some wont. if I set no break points it always returns zero files uploaded. this is driving me crazy. I attached the trace files
[TraceFile.txt](https://github.com/hgupta9/FluentFTP/files/1322308/TraceFile.txt)

**Comment by hgupta9** [comment]
Single thread or multi threaded? You are uploading files one by one right? And which server OS and FTP software?

**Comment by stufano** [comment]
var filecounter = connectionResult.Connection.UploadFiles(fileListToProcess.ResultData as List<string>,
                                args.DestinationPath, FtpExists.Overwrite, true, FtpVerify.Retry);

The lists are created upfront and thats the call that we use to push them.

**Comment by robinrodricks** [comment]
Can't understand this one. UploadFiles simply uses UploadFile internally which should work just fine... Must look into the code...

**Comment by robinrodricks** [comment]
Please reply if you still have this issue with the latest version.
