### ISSUE TITLE
Download file further

### ISSUE THREAD

**Issue by sergeu90** [robinrodricks/FluentFTP#193]
Hellow everyone.I have the problem.When I download file from FTP server   
`var downloadFileAsync = client.DownloadFile(path, item.FullName);`

When I restart the computer I want to download file further.Can you help me, please?Any advise.

**Comment by checkdigits** [comment]
I think the answer below might give you the kind of code you're looking for:
https://github.com/hgupta9/FluentFTP/issues/39

**Comment by sergeu90** [comment]
@checkdigits  but they wrote Fixed in 16.1.0 this problem

**Comment by sergeu90** [comment]
maybe exist another path

**Comment by hgupta9** [comment]
Check the FAQ for appending to a file...

**Comment by sergeu90** [comment]
@robinrodricks  I checked but nothing found about how to download the file.

**Comment by robinrodricks** [comment]
https://github.com/robinrodricks/FluentFTP/blob/master/README.md#faq_append

**Comment by sergeu90** [comment]
@robinrodricks  thanks
