### ISSUE TITLE
Discussion about async methods

### ISSUE THREAD

**Issue by taoyouh** [robinrodricks/FluentFTP#194]
I am now writing task-based async methods on .NET Framework 4.5 and .NET Standard. The new methods I am writing are all real task-based async methods using the async networking APIs. They are not creating new threads like Task.Run do and should not cause crashing on .NET Core.

The problems I am facing: 

1. Awaiting inside lock statement is not available. Currently I removed all the locks in new methods. Shall we use Monitor.Enter instead or just say they are not thread-safe?
2. Currently most newly wrote mothods don't support CancellationToken. Where do you think is cancellation important, and how can we cancel the process without causing problems?

**Comment by robinrodricks** [comment]
Great work! Answers to your questions:

1. Don't implement locking. It's only a safety mechanism and not really needed.
2. Don't support cancellation. It's ok. 

We can release a major version (indicating breaking API changes) so users of the async methods will be warned that there are major changes. Even if there are less features than before I think it's ok. In the worst case we will make 2 async APIs. Just implement it first.

**Comment by artiomchi** [comment]
Hmm, actually, should we consider using the Cancellation token in several places?

Some operations will be relatively quick (connect, get file modified date, etc), and even there if the network is slow or timing out, a cancellation token can help.

But think about the methods that may take a long time. Downloading/uploading a large file (where we end up iterating through a stream), directory listing (a directory could have thousands of entries). A cancellation token there would be trivial to implement, and could make a big difference to some.

I wouldn't discard the usefulness of it so fast.

What do you think?

**Comment by robinrodricks** [comment]
@artiomchi I agree they are important but whats more important is implementation of "true" async methods which is needed for .NET standard also. Therefore if a little features are lost its okay and can be added later. After all async should be async.

**Comment by robinrodricks** [comment]
Closing this as new async methods have been implemented by @taoyouh. Thanks again!
