### ISSUE TITLE
How get files by date?

### ISSUE THREAD

**Issue by sergeu90** [robinrodricks/FluentFTP#201]
Hellow everyone.I want to get files by specified date. Can you help me?

**Comment by robinrodricks** [comment]
Try using GetListing to get the files/folders inside a specific directory, with the FtpListOption.Modify flag if you need accurate date/time, then sort by the Modified property, using:

      Files.OrderBy(x => x.Modified)

**Comment by sergeu90** [comment]
@robinrodricks thanks
