### ISSUE TITLE
Malformed PASV response: Type set to I

### ISSUE THREAD

**Issue by bugged84** [robinrodricks/FluentFTP#203]
What does this error mean?

Malformed PASV response: Type set to I

**Comment by artiomchi** [comment]
Are you using .net Core? This sounds like the issue that was just fixed a couple days ago in #199

**Comment by robinrodricks** [comment]
@artiomchi My internet is going to be fixed today. I will release a build on nuget with all the latest fixes and improvements... It's long overdue :(

**Comment by bugged84** [comment]
Is there a new beta package that includes the fix from #199 ?

**Comment by robinrodricks** [comment]
Can you try with the latest build : https://www.nuget.org/packages/FluentFTP/19.0.0

**Comment by bugged84** [comment]
Latest build fixes issue. Thanks.
