### ISSUE TITLE
Acces to Local Path is denied

### ISSUE THREAD

**Issue by TrevorPremium** [robinrodricks/FluentFTP#205]
Hi Robin,

I'm having a problem trying to download to local path Using " ftpClient.DownloadFile",
The error I get is:
 System.UnauthorizedAccessException: Access to the path 'C:\Users\my user' is denied. 

Regards,

Trevor Pitse.

**Comment by TrevorPremium** [comment]
OH wow! I'm sorry but I've tried already tried downloading to other folders and thought you could help.

**Comment by robinrodricks** [comment]
What input arguments are you using??

**Comment by robinrodricks** [comment]
Try downloading to another drive, sometimes C drive has tight security...

**Comment by TrevorPremium** [comment]
I was downloading to a folder on the desktop then I tried using a removable disk "G:/" but I still can't access the file system.

**Comment by TrevorPremium** [comment]
I'm using (local path, remote path) as my parameters.

**Comment by robinrodricks** [comment]
Why don't you search stackoverflow for the error that you are getting, because it's nothing to do with this lib.

**Comment by TrevorPremium** [comment]
@robinrodricks I've been searching up and down but I'll keep trying stackoverflow,
Thanks.

**Comment by robinrodricks** [comment]
Your issue is very confusing and indicates that your app does not have file
system permissions. Try writing a file with File.WriteAllText (not sure
about the name of the method, but similar) and see if that works first...

**Comment by TrevorPremium** [comment]
@robinrodricks  let me try that and see if it works.

**Comment by TrevorPremium** [comment]
@robinrodricks I used StreamWriter to create a txt file and write to it and it did work, I don't understand how Download file doesn't have the correct permissions.

**Comment by ym9288** [comment]
I have the same sence with Bro TrevorPremium,....  Still  not resolved ?

**Comment by ym9288** [comment]
problem...,, sorry  ,I used a  wrong word

**Comment by ym9288** [comment]
ahah, I got the reason,  your argument  'localPath'  with DownloadFile()    missing the last fileName block.
It must be a FullPath with filename, could not be a  directory path.

**Comment by WadeTheFade** [comment]
> ahah, I got the reason, your argument 'localPath' with DownloadFile() missing the last fileName block.
> It must be a FullPath with filename, could not be a directory path.

This is what got me. I was first testing with `DownloadFilesAsync`, then realized I needed more logging so I was going to iterate over the list myself, and changed it to `DownloadFileAsync`, not realizing the hints changed from `localDir` to `localPath`. Though even that subtle word change could still be interpreted as the same thing.

Maybe we need it to be something like `localFullPathWithFilename` for the slightly less observant :)

**Comment by robinrodricks** [comment]
Wade can you create a new issue for this please. I will work on it.
