### ISSUE TITLE
Can I download parallel files.

### ISSUE THREAD

**Issue by sergeu90** [robinrodricks/FluentFTP#206]
Hellow I have a problem I want to download two files parallel.First file 50gb and second file 10gb.
When I am running that code I am getting exception timeout
```
 task1 = Task.Run(() =>
                       {
                           DownloadFile(pathToSave, ftpListItem.FullName);
                       });
 task2 = Task.Run(() =>
                       {
                           DownloadFile(path to save, ftpListItem.FullName);
                       });
```
Can you explain me?How can I download parallel files? I tried  DownloadFileAsync but I got a timeout error too.
if use lock then exception timeout don't get
```
 lock (thisLock)
            {
                _client.DownloadFile(localPath, remotePath);
            }
```

**Comment by robinrodricks** [comment]
Make a background worker and create a FluentFTP client instance in that worker... This you can have 2 or more parellel downloads.... see #151

**Comment by sergeu90** [comment]
@robinrodricks  For each file,  Should I create FluentFTP client instance?

**Comment by robinrodricks** [comment]
For each parallel file...

**Comment by sergeu90** [comment]
Thanks
