### ISSUE TITLE
Timed out trying to read data from the socket stream!

### ISSUE THREAD

**Issue by sej69** [robinrodricks/FluentFTP#208]
I saw this posted on here a couple of times but it doesn't seem to apply to what I'm doing.

I've set up credentials on a CentOS 6 box for SFTP and can use putty's SFTP client to connect a-ok.

I then use the following code:

`                if (szUserName != string.Empty && szPassword != string.Empty)
                    oCreds = new NetworkCredential(szUserName, szPassword);
                  FtpClient client = new FtpClient(szAddress, nPort, oCreds);
                  client.Connect(); // <--- this is where I get the message / exception
`

I've verified that the Server address, username, and password are all what I used in the SFTP client.

I'm using VS2017, FluentFTP 18.0.2, Windows 10 (client), CentOS 6 (server)

Any ideas why I may be seeing this?

**Comment by robinrodricks** [comment]
Can you try with the latest build : https://www.nuget.org/packages/FluentFTP/19.0.0

**Comment by sej69** [comment]
I just changed the code to this:

`                FtpClient client = new FtpClient(szAddress);
                client.Credentials = new NetworkCredential(szUserName, szPassword);
              
                client.Connect();`

And now get a different error:  No connection could be made because the target machine actively refused it 10.1.1.254:21

I can use putty sftp to make a connection just fine...

I went back into the original code and changed the port to 21 and the same error as above showed.  I do believe that SFTP should be port 22?

**Comment by sej69** [comment]
It just occurred to me...  I don't see any reference to downloading the SSH certificate from the server...  This could be the issue?

**Comment by sej69** [comment]
It looks like you've changed the description on the library to ftps from sftp (which are very different services).  It works well as ftps.  You can close this as I think it may have been a typo in the description.

**Comment by robinrodricks** [comment]
Description? Typo? AFAIK I have always mentioned FTPS, never SFTP, as I am well aware that they are completely different protocols. Where is the typo?

**Comment by sej69** [comment]
It did say SFTP and it still comes up in NUGET when you search for SFTP…

[cid:image001.png@01D33DA0.B1EF0650]
