### ISSUE TITLE
Timeout Exception in GetReply after Write

### ISSUE THREAD

**Issue by infogulch** [robinrodricks/FluentFTP#209]
I'm calling `client.GetReply()` after I'm done writing to an opened Stream (as recommended), but this causes it to throw `System.TimeoutException: Timed out trying to read data from the socket stream!`.

The stacktrace isn't very helpful, but here's a gist of the log (partially redacted): https://gist.github.com/infogulch/ae17270a85877665bfebe30fd0c4bb5a

This is the code I'm using:

```c#
// (using FtpFile = KeyValuePair<string, Stream>;)
public void UploadMany(IEnumerable<FtpFile> ftpFiles)
{
    var buffer = new byte[32 * 1024];
    using (var client = GetNewConnection()) // creates a FtpClient instance from the environment, and calls .Connect();
        foreach (var file in ftpFiles)
        {
            using (var src = file.Value)
            using (var dest = client.OpenWrite(file.Key))
            {
                int count;
                while ((count = src.Read(buffer, 0, buffer.Length)) > 0)
                    dest.Write(buffer, 0, count);
            }
            client.GetReply();
        }
}
```

Note: I used to have issues with "Bad IP Connecting" until I enabled PASVEX mode (it is present in the log above). The Bad IP error is now gone, and the one this issue is about replaced it. (Hey at least it's uploading the file now.)

Any ideas? Critiques welcome. 😄

**Comment by robinrodricks** [comment]
Then don't call GetReply.. it's only needed if the server has sent a response, which in your case it appears it's not. If there is nothing to read, it will hang/timeout. Usually servers only serve a reply after the file has fully transferred.

Also try plain passive mode, not extended, to see if that helps.

**Comment by infogulch** [comment]
Oh so this is a server specific issue then.

**Comment by robinrodricks** [comment]
And don't forget you can use FtpTrace.Log* to control what is redacted in the log.

**Comment by infogulch** [comment]
Thanks for the tip.

I think I've found my main problem. The environment that my app (& FluentFTP) is running in has multiple outbound interfaces, and thus is connecting via different IPs during a single session causing the "Bad IP" error at random.

Can FluentFTP be configured to use a consistent interface/ip endpoint during a single FTP session? Or is there a way to specify it via the API? (.NET makes [it possible](https://msdn.microsoft.com/en-us/library/3bsb3c8f.aspx))

**Comment by infogulch** [comment]
Thanks for the tip.

I think I've found my main problem. The environment that my app (& FluentFTP) is running in has multiple outbound interfaces, and thus is connecting via different IPs during a single session causing the "Bad IP" error at random.

Can FluentFTP be configured to use a consistent interface/ip endpoint during a single FTP session? Or is there a way to specify it via the API? (.NET makes [it possible](https://msdn.microsoft.com/en-us/library/3bsb3c8f.aspx))

**Comment by infogulch** [comment]
I'm closing this now since the nature of the issue I'm encountering has changed.
