### ISSUE TITLE
FluentFTP + hangfire errors in concurrent jobs

### ISSUE THREAD

**Issue by wernerbarnard** [robinrodricks/FluentFTP#211]
Hi,

So i'm using FluentFTP with hangfire, and getting errors when 2 jobs use FTP at the same time.

Some sample code:

```
            services.AddTransient<IFtpAdapter, FtpAdapter>();
```

Using the FTP client in the hangfire job/execution like this:

```
using (var ftpClient = _ftpAdapter.Connect(connectRequest))
{

}
```

ftpAdapter.Connect:
```
_ftpClient = new FtpClient(request.Host, request.Port, request.Credentials)
{
    EnableThreadSafeDataConnections = true
}

_ftpClient.Connect();

```

On Dispose:
```
public void Dispose()
{
    _logger.LogInformation("Disposing FTP Client");

    if (_ftpClient.IsConnected)
        _ftpClient.Disconnect();

    if (!_ftpClient.IsDisposed)
        _ftpClient.Dispose();
}
```

It seems to die when the 1 job Disposes the client, and the other 1 dies when trying to do GetListing with this:
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'This FtpClient object has been disposed. It is no longer accessible.'.
```

But if it's Transient, it's not supposed to be shared, right?

FYI - all jobs works fine without these errors if run sequentially, and not concurrently.

**Comment by robinrodricks** [comment]
I don't understand. What is hangfire? And why do you need EnableThreadSafeDataConnections? It causes much slowdowns and many other issues...

**Comment by wernerbarnard** [comment]
Hi @robinrodricks 

Hangfire is referring to https://github.com/HangfireIO/Hangfire

I assumed I need it to make it thread safe, it was an attempt, but I get the same issue without it.

**Comment by robinrodricks** [comment]
First up, I don't exactly understand your config/use case, but I can say for sure that one FluentFTP client cannot be used from 2 threads at the same time. Crap will happen. Internal locking does not work for the async API, although it should work for sync API, but still I think crap will happen. Many have tried without success, so I recommend that you create a client for each job and disconnect the client at the end of the task. Can you try that?

**Comment by wernerbarnard** [comment]
Hi @robinrodricks 

That's is what i'm doing, and I expected it to work.

from my sample code about, I am creating a new client in each job (in a using statement).... but when the 1 disposes in the 1 thread, the other thread's client dies.  So either i'm doing something wrong in what i'm saying i'm doing, or there's an issue.

**Comment by wernerbarnard** [comment]
Hi @robinrodricks 

I just tried again with the latest version, and while 2 processes were running concurrently, the 2nd one died with the below error as soon as the 1st processes killed it's ftp client.

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'This FtpClient object has been disposed. It is no longer accessible.'.
   at FluentFTP.FtpClient.Connect()
   at FluentFTP.FtpClient.Execute(String command)
   at FluentFTP.FtpClient.GetModifiedTime(String path, FtpDate type)
   at FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
```

**Comment by robinrodricks** [comment]
Sorry I don't know how to help you.
