### ISSUE TITLE
How download file directly one ftp to another ftp server 

### ISSUE THREAD

**Issue by sergeu90** [robinrodricks/FluentFTP#212]
Hello everyone.I want to download file directly to another ftp.can you advise me ?

**Comment by robinrodricks** [comment]
Sorry but FXP is hard, no plans right now unless a contributor decides to work on it. You will have to go the normal route (download to client, then upload). Or maybe if you have control of one of the servers to run an app, you can run a .net core app on one of them, use FluentFTP on that box and download directly to the file system. This would effectively transfer from server to server.

**Comment by sergeu90** [comment]
@robinrodricks Thanks for the answer.

**Comment by robinrodricks** [comment]
@sergeu90  FXP is live with [FluentFTP 31.3.0](https://www.nuget.org/packages/FluentFTP/):

  - New: `TransferFile` and `TransferDirectory` methods to transfer files from server to server (thanks [n0ix](/n0ix))
  - New: FXP (File Transfer Protocol) implementation to support direct server-to-server transfers (thanks [n0ix](/n0ix))

Check it out and let us know!
