### ISSUE TITLE
Stream.Position should not be set in UploadFileInternal

### ISSUE THREAD

**Issue by ferenctoth75** [robinrodricks/FluentFTP#213]
The current UploadFileInternal() implementation sets the position in the input stream unconditionally. There are two problems with the current approach:

- Non seekable streams: the stream returned by ZipArchiveEntry.Open() is not seekable and will throw an exception upon trying. Workaround is to save the stream from the zip to a memory stream and pass that to FluentFTP. 
- Streams with the current position already set: a HTTP multipart upload is handled by a webserver and it tries to directly upload the HTTP input as stream. It will not work as the stream will be reset to the beginning of the HTTP request.

So, ideally "fileData.Position = offset;" should be moved to the end of the "case FtpExists.Append:" block. This will modify the current behavior, so the Upload methods taking Stream as parameter could have an optional bool parameter specifying if the stream is already set at the correct position.

Please consider the suggested changes. Thanks!

**Comment by robinrodricks** [comment]
What if we simply wrap the "fileData.Position = offset" line in a try/catch block to absorb the error. Would that work for you? Adding args is painful because there are like 100 different wrappers/overloads.

**Comment by ferenctoth75** [comment]
That would certainly work for streams from ZipArchive. Although it would be nicer to check fileData.CanSeek and set the position only if the stream supports it.
Regarding the HTTP stream. I believe, that you can seek on that stream (at least it did not throw an exception for me). So, it will not help there. But I understand that you don't want to change the 100 wrappers, so I'm fine the workaround for now (save the stream as MemoryStream and use that). But please keep this in mind and if you need to change the API later on for some other reasons, then please consider doing this, too. :) Thanks.

**Comment by robinrodricks** [comment]
How kind and polite :) I will fix whatever I can.

**Comment by robinrodricks** [comment]
Fixed in 19.0.1. Will be uploaded in the next nuget release.
