### ISSUE TITLE
FTPS GetFileSize return -1

### ISSUE THREAD

**Issue by sergeu90** [robinrodricks/FluentFTP#214]
I have a problem.I connect to ftps and I am getting size file, but it returns -1. Сan you advise?
My connection
```
var ftpClient = new FtpClient(_ftpSettings.Host, _ftpSettings.Credentials);
ftpClient.EncryptionMode = FtpEncryptionMode.Explicit;
ftpClient.SslProtocols = SslProtocols.Tls;
ftpClient.ValidateCertificate += new FtpSslValidation(OnValidateCertificate);
ftpClient.Connect();
```

**Comment by robinrodricks** [comment]
Can you show the logs? (see part on "tracing" in the FAQ) Maybe the server does not support this command or there is a bug...

**Comment by sergeu90** [comment]
@robinrodricks
Yes you are right server, not allowed  
Response: 502 SIZE: command not allowed.
