### ISSUE TITLE
Ftp Upload ProgressBar

### ISSUE THREAD

**Issue by amerlin** [robinrodricks/FluentFTP#216]
Hi, is possibile integrate progressbar event in upload operation? 
Thanks

**Comment by robinrodricks** [comment]
Closing this as it's a duplicate. Please add your notes into #91

**Comment by robinrodricks** [comment]
Implemented progress tracking via IProgress for Upload/Download/UploadFile/DownloadFile.
The callback will be called with a number from 0 to 100, based on the percentage of completion.

Please grab it at : https://www.nuget.org/packages/FluentFTP/19.1.0
