### ISSUE TITLE
All connections should use the same local IP

### ISSUE THREAD

**Issue by infogulch** [robinrodricks/FluentFTP#218]
I've encountered an issue while using an FTPClient where different TCP connections to the same server use multiple different outgoing IP addresses (in an environment where the server has them). ( See the end of #209. )

#### Problem
In general, if left unspecified, the operating system will choose an outgoing ip arbitrarily when opening a new network socket. This is a problem because some ftp severs disallow connecting with different IPs during the same session. (Notably, vsftpd by default.) This is rarely encountered during testing because most development systems don't have more than one available outgoing ip. 

#### Enhancement
Instead, after an FTPClient first connects, it should attempt to open all connections during that session using the same outgoing IP address / network interface. Lets call this behavior "same-ip-client". In my opinion this should be on by default and you could add an option to disable it. (I don't know why you would want to disable it, perhaps performance?) Alternatively you could keep the current behavior and add an option to turn it on.

As part of the implementation you could add an additional parameter in the API to allow specifying the exact outgoing ip in places like [FtpSocketStream.Connect](https://github.com/robinrodricks/FluentFTP/blob/b3019a96162c90075f07b71f0a6d9d058498e002/FluentFTP/Stream/FtpSocketStream.cs#L749). You could even stop at this and not implement the whole same-ip-client behavior specified above, since it would give FluentFTP users the capability to work around this issue bit more legwork on their end.

#### Conclusion
I think this would enhance the reliability of the library when interacting with other ftp implementations. I would be willing to implement this change as a pull request if it might be accepted. What are your thoughts?

**Comment by infogulch** [comment]
This is something I need so I plan to start on it next week. Any thoughts?

**Comment by robinrodricks** [comment]
No issues. I accept almost every PR. Just ensure that the default behaviour is not modified if you think there would be side effects for other users. Anyways you are adding a property so users can turn it on/off at will if it affects then.

**Comment by robinrodricks** [comment]
Can you name the property "MultipleOutgoingIPs" or "SingleOutgoingIP" or something on those lines? Add it in the main FtpClient_Connection.cs file, as well as your code for the same.

**Comment by infogulch** [comment]
Absolutely, `public bool SingleOutgoingIP` feels right to me.

**Comment by robinrodricks** [comment]
Any updates on this? Did you find it too hard to implement?

**Comment by infogulch** [comment]
No, actually I haven't been able to start yet. I don't expect it to be very hard but I probably won't be able to revisit this until the end of the month though.

Sorry I haven't posted any updates.

**Comment by robinrodricks** [comment]
I'll reopen this issue when you decide to begin the work. Good luck!
