### ISSUE TITLE
FluentFTP.FtpCommandException : APPE command not implemented.

### ISSUE THREAD

**Issue by bugged84** [robinrodricks/FluentFTP#219]
Repository examples suggest Append is supported, but I get this error. Searched repo for error but no hits. Is Append simply not yet supported?

**Comment by robinrodricks** [comment]
Afaik the APPE command is not supported. Did you not check the FTP support table in the readme? There are other ways to append, again why did you not see the FAQ on appending? It's right on top of the file....

**Comment by bugged84** [comment]
Ya, sure it is. Let's just calm down for a second and be productive. If you're referring to [this question](https://github.com/robinrodricks/FluentFTP#faq_append) way down in the middle of the readme document, then I guess I did "see the FAQ on appending." This was, in fact, the example I was referring to in my original post. Is OpenAppend not supported in favor of UploadFile?

**Comment by robinrodricks** [comment]
Both are supported. OpenAppend is low level. UploadFile is high level. What are you having trouble with? Internally OpenAppend is always used anyways.

**Comment by robinrodricks** [comment]
The exception in the title... Is that what you get from the server or from FluentFTP? And what code triggers that error?

**Comment by robinrodricks** [comment]
Since append works for hundreds of users, coz it be that your server is returning a fail code because it does not support appending? I don't think there is anything wrong with the lib because hundreds have used append including me without issues. Which is your FTP server?

**Comment by bugged84** [comment]
I'm guessing the code is coming from the server since you're not familiar with it.

**Comment by robinrodricks** [comment]
Read the FAQ on logging, and see the server's response to the FEAT command, sent at the start. If APPE is not on the list of supported commands, it means it's a server issue.
