### ISSUE TITLE
Cancle download file.

### ISSUE THREAD

**Issue by sergeu90** [robinrodricks/FluentFTP#220]
Hellow everyone.I have some problem use your library and hangfire.I have a job on the downloading file by the scheduler.When I remove job in the hangfire the downloading continues.How can I cancel downloading files?

**Comment by robinrodricks** [comment]
Just out of curiosity why did you not fill in the parameters required when making a new issue? Were you unable to see the template?

**Comment by robinrodricks** [comment]
Unless you respond with details we cannot help you.
