### ISSUE TITLE
EOF/0 bytes exception in active transmission in netcore

### ISSUE THREAD

**Issue by ralftar** [robinrodricks/FluentFTP#221]
I have to use active FTP to connect to a legacy server. It works fine in Filezilla and .NET's native FtpWebRequest. However, I am aiming for defining active data ports, thus I want to use FluentFTP.

A simple test code:

```csharp
FtpClient client = new FtpClient("10.164.2.15");
client.Port = 2121;
client.Credentials = new System.Net.NetworkCredential("***","***");
client.DataConnectionType = FtpDataConnectionType.PORT; // active
client.Connect();
client.DownloadFile("test.file", "/test.file");
client.Disconnect();

```

Yelds a EOF/0-byte receive exception:

```csharp
FluentFTP.FtpException: Error while downloading the file from the server. See InnerException for more info. ---> System.IO.IOException: Unexpected EOF for remote file /test.file [0/4418 bytes read]
   at FluentFTP.FtpClient.DownloadFileInternal(String remotePath, Stream outStream, IProgress`1 progress)
   --- End of inner exception stack trace ---
   at FluentFTP.FtpClient.DownloadFileInternal(String remotePath, Stream outStream, IProgress`1 progress)
   at FluentFTP.FtpClient.DownloadFileToFile(String localPath, String remotePath, Boolean overwrite, FtpVerify verifyOptions, IProgress`1 progress)
```
I cannot figure how this can turn out, since the data is confirmed received by FTP log, and by tracing the active data transmission in Wireshark. However it ends with a RST (teardown by FluentFTP?)

I am using .NET Core 2.0.

All help and suggestions are appreciated.

**FTP log**

```
Status:   Connecting to 10.164.2.15:2121
Response: 220 ***           FTP server ready.
Command:  USER ***
Response: 331 Password required for vendanor.
Command:  PASS ***
Response: 230 User vendanor logged in.
Command:  FEAT
Response: 211 End
Response: 211-Features supported
Response: MDTM
Response: MLST Type*;Size*;Modify*;Perm*;Unique*;
Response: REST STREAM
Response: SIZE
Response: TVFS
Status:   Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser
Command:  TYPE I
Response: 200 Type set to I.
Command:  SIZE /test.file
Response: 213 4418
Command:  TYPE A
Response: 200 Type set to A.
Command:  TYPE I
Response: 200 Type set to I.
Command:  SIZE /test.file
Response: 213 4418
Command:  PORT 10,164,100,9,197,4
Response: 200 PORT command successful.
Command:  RETR /test.file
Response: 150 Opening BINARY mode data connection for '/test.file' (4418 bytes).
Command:  QUIT
Response: 226 Transfer complete.
```

**Wireshark screenshot**

Trace of PORT 20 (dataport) that connect back to the client, shows that 4418 bytes is transmitted (1340*3 + 464), but ends with a RST.

![image](https://user-images.githubusercontent.com/1395569/31201971-f6185292-a960-11e7-89a9-64798c13544a.png)

**Comment by ralftar** [comment]
It is failing/the exception is thrown only when using FluentFTP 191.0 from nuget. When donloading the latest master (according to log it should be the same as on nuget) and using it on the very same code and environment everything works as it should.

**Comment by robinrodricks** [comment]
Wow, what detailed info provided... Can't understand how the master is working, it's the same as nuget...

**Comment by ralftar** [comment]
I must correct myself, I did disable all the target framework differentiation (CORE/ASYNC) and ran the master with default target framework (!ASYNC and !CORE). Under that circumstance this use case did turn out fine. However I need it to work under netcore,
