### ISSUE TITLE
Error new Progress with DownloadFileAsync

### ISSUE THREAD

**Issue by cpmoliveira** [robinrodricks/FluentFTP#223]
The new functionality of Progress is pretty good!
I tested it with the DownloadFile function and it's ok.
But when I used with DownloadFileAsync, a error occurred at 100% with message:

> Unexpected EOF for remote file 2017100512.grb [**107060779/106756354** bytes read]"
> FluentFTP.FtpClient.<DownloadFileInternalAsync>d__310.MoveNext()

**Comment by robinrodricks** [comment]
Thanks! I will look into it...

Just out of curiosity why did you not fill in the parameters required when making a new issue? Were you unable to see the template?

**Comment by cpmoliveira** [comment]
Sorry, it was an oversight.

**Comment by robinrodricks** [comment]
Are you still having this issue with the latest version?

https://www.nuget.org/packages/FluentFTP/19.1.1

**Comment by cpmoliveira** [comment]
No, now it's ok.
Thanks!
