### ISSUE TITLE
Problem with DownLoadFile

### ISSUE THREAD

**Issue by AmycoFr** [robinrodricks/FluentFTP#224]
**FTP OS:**  Windows 

**FTP Server:** Pure-FTPd

**Computer OS:** Windows 10

I'am writing an code with Visual Studio 2017. On the Framework 4.6.1.

This code does not work. **DownLoadFile** answers "false" and the file is not loaded to disk.
**GetListing** enumerates the files on the server and **GetFileSize** returns the correct size of the file.
thank you for your indications

`        ' Préparer le status de la réponse
        Dim Ok = False
        Status = String.Format("{0} : fichier {1} ", MyCnx.dir, namefile)

        '- 1 -- Importer le fichier demandé
        Using client As New FtpClient()
            Try
                ' Connexion au serveur
                client.Host = MyCnx.url
                client.Credentials = New Net.NetworkCredential(user, psw)

                ' Sélectionner le répertoire source sur le serveur                 
                'client.SetWorkingDirectory(MyCnx.dir)

                ' Acquérir la liste des items présents dans le répertoire Serveur
                ' et vérifier la présence du fichier demandé.
                For Each item In client.GetListing(MyCnx.dir)
                    If item.Name = namefile Then

                        Dim lgFile = client.GetFileSize(Path.Combine(MyCnx.dir, namefile))
                        Ok = client.DownloadFile(Path.Combine(MyCnx.dir, namefile), Path.Combine(dst, namefile))

                        Status += lgFile.ToString() + " octets - "
                        Status += IIf(Ok, "", "NON ") + "CHARGE."
                        Exit Try
                    End If
                Next

                ' Pas trouvé !
                Status += "ABSENT."

            Catch ex As Exception
                Status = ex.Message
                Ok = False
            Finally
                client.Disconnect()
            End Try

        End Using
`

See this link for steps : https://github.com/robinrodricks/FluentFTP#faq_trace
-->

```
<paste logs here>
```

**Comment by AmycoFr** [comment]
In addition, here is the FTP log of code execution.
[FtpTrace.txt](https://github.com/robinrodricks/FluentFTP/files/1366299/FtpTrace.txt)

**Comment by AmycoFr** [comment]
Ohhh, excuse me. I'm making a mistake. I just understood (thanks FtpTrace) that I had inverted the local and remote paths.
My code now works.
A thousand thanks for your work.

**Comment by taoyouh** [comment]
Then you can close the issue now.
