### ISSUE TITLE
Unexpected EOS in ASCII data type

### ISSUE THREAD

**Issue by taoyouh** [robinrodricks/FluentFTP#225]
**FTP OS:** Unix

**FTP Server:** ProFTPD 

**Computer OS:** Windows 10

Some FTP server convert "\n" to "\r\n" in ASCII data type. But the file size is the original one. So comparing the file size doesn't make sense in ASCII data type, and will cause unexpected end of stream problem. These issues seems to be due to this problem.
https://github.com/robinrodricks/FluentFTP/issues/223
https://github.com/robinrodricks/FluentFTP/issues/69#issuecomment-333147885

**Logs :**

```
# DownloadFileAsync("C:\Users\Zhaoquan\AppData\Local\Packages\46939f22-cc28-4788-8ae5-3f7f09696b35_955x0bhndy0qj\TempState\MPB (5).doc", "/MPB.doc", True, None)

# GetFileSize("/MPB.doc")
Command:  TYPE I
Response: 200 Type set to I
Command:  SIZE /MPB.doc
Response: 213 592896
Command:  TYPE A
Response: 200 Type set to A

# OpenReadAsync("/MPB.doc", Binary, 0)
Command:  TYPE I
Response: 200 Type set to I

# GetFileSizeAsync("/MPB.doc")
Command:  TYPE I
Response: 200 Type set to I
Command:  SIZE /MPB.doc
Response: 213 592896
Command:  TYPE A
Response: 200 Type set to A

# OpenPassiveDataStreamAsync(AutoPassive, "RETR /MPB.doc", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||9840|)
Status:   Connecting to 202.120.2.2:9840
Command:  RETR /MPB.doc
Response: 150 Opening ASCII mode data connection for /MPB.doc (592896 bytes)

Unexpected EOF for remote file /MPB.doc [594315/592896 bytes read]
```

**Comment by taoyouh** [comment]
There is a bug that ASCII mode may be used even when Binary mode is chosen. #226 should fix this problem if DownloadDataType is set to Binary.

**Comment by taoyouh** [comment]
@robinrodricks I think this problem is not fixed completely. It only works when datatype is set to binary. If datatype is ASCII, same problem occurs.

**Comment by taoyouh** [comment]
It is clear that file size is not reliable when transferring file in ASCII mode. We should just read to end of stream like when size is not available.
According to RFC 959, the server should reply 226 if the data transfer is completed and data connection is closed. Shall we check for a 226 reply at end of stream?

**Comment by robinrodricks** [comment]
@taoyouh If you can make the change I would be grateful. I understand what you mean but how to read to end? Can you do the change and send a PR, if not tell me how to read to end and I'll make it.

**Comment by taoyouh** [comment]
@robinrodricks In DownloadFileInternalAsync and DownloadFileInternal, there is a readToEnd variable. I mean set it to true when CurrentDataType is not binary.
But I have some questions. First, why cannot download file with 0 length in ASCII mode? Second, how can we know if the downloading is interrupted?
So I am thinking of the need of listening for 226.

**Comment by robinrodricks** [comment]
> First, why cannot download file with 0 length in ASCII mode? Second, how can we know if the downloading is interrupted?

Yes, even I don't understand that code. I think its an older code put in place before readToEnd, therefore we had to exit because length was unknown. But, I think in ASCII mode the EOF signal does not come from the server? I'm going to make that change and publish it in the next nuget release. Lets see if people have any problems with it.

> Second, how can we know if the downloading is interrupted?

There is some code for that, but never been tested. Search for "resume if server disconnected midway" in the code.

**Comment by taoyouh** [comment]
The resuming starts only when IOException is caught. But I think IOException does not always throw when download fails, it may just silently reaches end of stream.

**Comment by taoyouh** [comment]
Fixed in commit https://github.com/robinrodricks/FluentFTP/commit/8869a567b580c2010e76a80b60cdb68d5c1bfc6a
