### ISSUE TITLE
Help with download progress

### ISSUE THREAD

**Issue by Senemi** [robinrodricks/FluentFTP#228]
Hello,
I'm having a problem with monitoring the download progress of a file.

The previous Issues and the ReadMe state that you can track it via IProgress and sor far, after searching on google, i still don't know what that is.

I'm coding in Visual Basic, calling the FPTClient.DownloadFileAsync() Method. 
I've read that there should be an error occuring after a download is complete, when monitoring with the download async method, has this been fixed by any chance?

it'd be great if you could help me getting the download progress onto a label and progress bar.

Best regards

**Comment by Senemi** [comment]
Thanks, but i couldnt convert everything as I'm coding in Visual Basic.

First off, is x an object?
and second, it seems that I dont have the method 'IsIndeterminate' in my progressbar, although it can be found in the Microsoft documentation for Visual Basic.

This is how far I've got with 'translating' the code to Visual Basic (I've never coded in C# before)

`Public Function dlprogress(x)`
        `Dim progress As New Progress(Of Double)`
        `If Double.IsNaN(x) OrElse Double.IsInfinity(x) OrElse x > 0 Then`
            `ProgressBar1.IsIndeterminate = True`
        `Else`
            `ProgressBar1.IsIndeterminate = False`
            `ProgressBar1.Value = x`
        `End If`
        `Dim ftp As New FtpClient`
        `Await ftp.DownloadFilesAsync(localpath, remotepath, True, FluentFTP.FtpVerify.Retry, progress)`
    `End Function`

I'm having 2 errors now. 
First error is the undefined method IsIndeterminate for the progressbar and second is that Await can only be called within an Async method.. I guess it does not accept DownloadFileAsync() as Asynchronous?

I Hope we can get this to work

**Comment by robinrodricks** [comment]
Marked a to do since progress value should not be NaN or infinity...

**Comment by taoyouh** [comment]
You need to put a "Sub" or function in the constructor of Progress. x => {doSomething();} is a quick way to express a function as an expression. The VB version of my sample is:
```
        Dim progress = New Progress(Of Double)(Sub(x)
                                                   'x is the progress
                                               End Sub)
        Await client.DownloadFileAsync(localPath, remotePath, True, FluentFTP.FtpVerify.Retry, progress)
```
Also, you can define a standalone sub and pass it into the progress:
```
    Sub dlprogress(x As Double)
        'x is the progress
    End Sub
```
```
        Dim progress = New Progress(Of Double)(AddressOf dlprogress)
        Await client.DownloadFileAsync(localPath, remotePath, True, FluentFTP.FtpVerify.Retry, progress)
```

**Comment by robinrodricks** [comment]
Thank you @taoyouh for helping out..

**Comment by robinrodricks** [comment]
Latest version includes a fix that NaN and Infinity will not be sent, instead -1 will be sent.

https://www.nuget.org/packages/FluentFTP/19.1.1

**Comment by robinrodricks** [comment]
Closing this as feature is implemented in latest build.
