### ISSUE TITLE
Async download/upload not working on UWP

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#230]
Created by @CriticalCauchy on Sep 25, 2017. Moved from issue #69.

In UWP apps, I can request file/directory listings but I encountered some trouble with the asynchronous file upload/download.

I don't have a "professional" FTP server. I'm just a hobby developer so I'm currently testing with a free webspace at bplaced.com: 

- server: ccauchy.bplaced.net (144.76.167.70)
- login: ccauchy_test1 / test1

FileZilla and the file properties in Windows display a file size of 81 bytes. On the index site, however, it says 60. Maybe the upload/download fails because the server returns wrong file size values?
I will look for another FTP server and try it there.

Today, I did a lot of testing with the newest version 19.1.0. I checked the sync. and async. upload and download methods in a Windows Forms and a UWP App. (Windows client, linux ftp server)

# UPLOAD
### sync
```
client.UploadFile(@"C:\img.jpg", "/T1/img.jpg"); //works
client.Upload(ba_img, "/T1/img.jpg"); //works
```
### async
```
await client.UploadFileAsync(@"C:\img.jpg", "/T1/img_async.jpg"); //works
await client.UploadAsync(ba_img, "/T1/img_async.jpg"); //fails
```
File size complete, but image broken (cannot be displayed in browser)
```
# OpenPassiveDataStreamAsync(PASV, "STOR /T1/img_async.jpg", 0)
Command:  PASV
Response: 227 Entering Passive Mode (217,160,122,239,197,92).
Status:   Connecting to 217.160.122.239:50524
Command:  STOR /T1/img_async.jpg
Response: 150 Opening ASCII mode data connection for /T1/img_async.jpg
Response: 226 Transfer complete
Command:  QUIT
Response: 221 Goodbye.
```

## UWP
UploadFile() and UploadFileAsync() cannot be used due to restricted UWP file reading permissions.
### sync
```
client.Upload(result, "/T2/img.jpg", FtpExists.Overwrite, false); //fails
client.Upload(result, "/T2/test.txt", FtpExists.Overwrite, false);  //fails
```
--> upload function stuck after complete upload but image and text file intact

### async
`await client.UploadAsync(ba_img, "/T2/img_async.jpg"); //fails`
--> File size complete, but image broken (cannot be displayed in browser)
```
# OpenPassiveDataStreamAsync(PASV, "STOR /T2/img_async.jpg", 0)
Command:  PASV
Response: 227 Entering Passive Mode (217,160,122,239,220,178).
Status:   Connecting to ***:56498
Command:  STOR /T2/img_async.jpg
Response: 150 Opening ASCII mode data connection for /T2/img_async.jpg
Thread endings ...
```

# DOWNLOAD
### sync (windows text file 81B - binary upload)
```
client.DownloadFile(@"C:\text_binup_dl.txt", "/TEST/Download/text_binup.txt"); //works
client.Download(fileStream, "/TEST/Download/text_binup.txt"); //works
```
### sync (linux text file 60B - uploaded with FileZilla ASCII)
```
client.DownloadFile(@"C:\text_dl.txt", "/TEST/Download/text.txt"); //works
client.Download(fileStream, "/TEST/Download/text.txt"); //works
```
### async (windows text file 81B - binary upload)
```
byte[] filebytes2 = await client.DownloadAsync("/TEST/Download/text_binup.txt"); //works
await client.DownloadFileAsync(@"C:\text_binup_dl.txt", "/TEST/Download/text_binup.txt"); //works
```
### async (linux text file 60B - uploaded with FileZilla ASCII)
```
byte[] filebytes1 = await client.DownloadAsync("/TEST/Download/text.txt");
await client.DownloadFileAsync(@"C:\text_dl.txt", "/TEST/Download/text.txt");
```
--> Size mismatch due to Linux/Windows text format (line ending characters)
```
# OpenPassiveDataStreamAsync(AutoPassive, "RETR /TEST/Download/text.txt", 0)
Command:  EPSV
Response: 500 'EPSV': command unrecognized.
# OpenPassiveDataStreamAsync(PASV, "RETR /TEST/Download/text.txt", 0)
Command:  PASV
Response: 227 Entering Passive Mode (217,160,122,239,216,203).
Status:   Connecting to 217.160.122.239:55499
Command:  RETR /TEST/Download/text.txt
Response: 150 Opening ASCII mode data connection for /TEST/Download/text.txt (60 bytes)
Error: "FluentFTP.FtpException" in mscorlib.dll
```

### sync
`client.Download(outstream, "/TEST/Download/text_binup.txt"); //works`
### async (windows text file 81B - binary upload)
`byte[] filebytes = await client.DownloadAsync("/TEST/Download/text_binup.txt"); //works`
### async (linux text file 60B - uploaded with FileZilla ASCII)
`byte[] filebytes = await client.DownloadAsync("/TEST/Download/text.txt"); //fails`
```
# OpenPassiveDataStreamAsync(PASV, "RETR /TEST/Download/text.txt", 0)
Command:  PASV
Response: 227 Entering Passive Mode (217,160,122,239,218,27).
Status:   Connecting to 217.160.122.239:55835
Command:  RETR /TEST/Download/text.txt
Response: 150 Opening ASCII mode data connection for /TEST/Download/text.txt (60 bytes)
Error: "System.IO.IOException" in FluentFTP.dll
Error: "FluentFTP.FtpException" in FluentFTP.dll
Error: "FluentFTP.FtpException" in System.Private.CoreLib.ni.dll
```

**Comment by taoyouh** [comment]
This should be fixed in commit https://github.com/robinrodricks/FluentFTP/commit/8869a567b580c2010e76a80b60cdb68d5c1bfc6a . @CriticalCauchy Please try version 19.1.1 and see if problem still occurs.

**Comment by CriticalCauchy** [comment]
UWP problems are solved! Great job, thank you very much!
With the version 19.1.1, I can upload and download text and image files in sync and async mode.

**Comment by robinrodricks** [comment]
@CriticalCauchy Great to hear that!

**Comment by grahamehorner** [comment]
@robinrodricks I'm seeing this issue when using .net core 2.1; with v19.2.2
