### ISSUE TITLE
[Question] Are you able to stop/pause a download in progress

### ISSUE THREAD

**Issue by srz2** [robinrodricks/FluentFTP#232]
**FTP OS:**  Windows

**FTP Server:** Unix

**Computer OS:** Windows

Doing a download, is it currently possible to pause/stop it. What about if you are downloading multiple files?

**Comment by robinrodricks** [comment]
I think the non-async versions of the file transfer commands have a cancellation token that can be passed into it, and can be cancelled during transfer. No way to pause atm.

**Comment by davidbuckleyni** [comment]
Has this been changed any or would you recommend any library's that has the pause resume function.
