### ISSUE TITLE
Support for SSL Session Reuse

### ISSUE THREAD

**Issue by pjbgf** [robinrodricks/FluentFTP#236]
**FTP OS:** Unix 

**FTP Server:** vsftpd version 3.0.2 release 22.el7

**Computer OS:** Windows

We are currently having issues to connect to a FTPS in which the **require_ssl_reuse** is enabled at the server side. The version of the FluentFTP we are currently using is 19.1.0. Does it support that feature?

**Logs :**

```
SSL connection failed; session reuse required: see require_ssl_reuse option in vsftpd.conf man page\r\nFluentFTP.FtpCommandException: SSL connection failed; session reuse required: see require_ssl_reuse option in vsftpd.conf man page\r\n   at FluentFTP.FtpClient.CloseDataStream(FtpDataStream stream)\r\n   at FluentFTP.FtpDataStream.Close()\r\n   at FluentFTP.FtpClient.GetListing(String path, FtpListOption options)\r\n 
```

**Comment by robinrodricks** [comment]
Haven't heard of this feature as yet. Can you elaborate on how it works exactly?

**Comment by pjbgf** [comment]
The idea behind this is to use the pre-establish TLS session for future interactions. That is suppose to make an improvement in performance as well as security. Below there are two links that may explain that better. 

https://superuser.com/questions/989048/why-is-session-reuse-useful-in-ftps

This is not really defined as an feature per se on the documentation, where specified at the bottom of page 39:
https://tools.ietf.org/html/rfc5246

Let me know whether that makes any sense.

**Comment by robinrodricks** [comment]
Its a good idea but I cannot give a timeline when it may be implemented.

**Comment by pjbgf** [comment]
Would you be able to provide some guidance on the implementation so I can give it a try on it?

**Comment by robinrodricks** [comment]
Well for starters you will need to add the main code in FtpSocketStream and/or FtpDataStream. Then add properties in FtpClient_Connection (if needed) or add methods in the same class to call the methods in the steam class (if any).

**Comment by martinvonwittich** [comment]
This is also required for TLS connections to ProFTPd >= 1.3.3rc1:

http://www.proftpd.org/docs/contrib/mod_tls.html#TLSOptions

> As of ProFTPD 1.3.3rc1, mod_tls only accepts SSL/TLS data connections that reuse the SSL session of the control connection, as a security measure.

As a workaround, you can disable this requirement on the ProFTPd server side with the following setting in `/etc/proftpd/proftpd.conf`:

```
TLSOptions NoSessionReuseRequired
```

**Comment by cluetjen** [comment]
Think we've the same problem here when trying to connect to a FileZilla server where newer versions require session reuse. The initial login works fine but opening data connections fails with "System.IO.IOException : Authentication failed because the remote party has closed the transport stream.".

**Comment by robinrodricks** [comment]
Same as #347. We'll continue the convo there.
