### ISSUE TITLE
can't CreateDirectory

### ISSUE THREAD

**Issue by laoshuai** [robinrodricks/FluentFTP#237]
**FTP OS:** CentOs

**FTP Server:** Vsftpd

**Computer OS:**  win7

My ftp path: /home/myftp/
**error:**
client.CreateDirectory("/eee");
**ok:**
client.CreateDirectory(" /home/myftp/eee");
**why?**

**Comment by robinrodricks** [comment]
Maybe the FTP server is configured to disable clients modifying the root directories. If it's your server, check the config file.
