### ISSUE TITLE
[bug]How do I verify the hash/checksum of a file and retry if the checksum mismatches?

### ISSUE THREAD

**Issue by sonygod** [robinrodricks/FluentFTP#239]
there is data.zip on my ftp src folder, and this data.zip is unfinish upload data,(old version)
and then I upload the new version data.zip, and use 

    conn.UploadFile(@"E:\data2.zip", "src/data.zip", FtpExists.Append, true, FtpVerify.Delete,onProgress); 

throw error:"crc error ,not implemented“

**Comment by robinrodricks** [comment]
Can you show the server reply after the FEAT command is sent? Only if the server supports CRC will this work...

**Comment by robinrodricks** [comment]
Enable logging to see it... See the FAQ on logging

**Comment by sonygod** [comment]
I use this lib for unity .net 3.5,
I will upload small sample code here soon..
