### ISSUE TITLE
How to get progress when uploading multiple files with UploadFiles?

### ISSUE THREAD

**Issue by sonygod** [robinrodricks/FluentFTP#241]
public int UploadFiles(IEnumerable<string> localPaths, string remoteDir, FtpExists existsMode = FtpExists.Overwrite, bool createRemoteDir = true,
			FtpVerify verifyOptions = FtpVerify.None, FtpError errorHandling = FtpError.None) 

it's seem have no progress api call back?

**Comment by robinrodricks** [comment]
Yes it doesn't... I can create it but how should it work? Return:
1. An object with : files compete, total files, current file, % progress on current file?
2. A single int with number of files compete?
3. A single int with number of files compete * 100 so the progress can be shown from the same number?

**Comment by sonygod** [comment]
may be you can add some options to user let them choose which is best for use

**Comment by franzvalo1** [comment]
Any update on this?

**Comment by frliran** [comment]
Any news on the progress bar here?

**Comment by ntindle** [comment]
I think its the same as with downloading multiple files. Can we confirm?

**Comment by robinrodricks** [comment]
Added to the [bucket list](https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans). We will pick this up as and when we have free time. Comment on this issue if you want us to prioritize it. Thanks!
