### ISSUE TITLE
File.Exists("File Path"); --> this is returning false if file exists, please check

### ISSUE THREAD

**Issue by sivagatla99** [robinrodricks/FluentFTP#243]
File.Exists("File Path"); --> this is returning false if file exists, please check

**Comment by robinrodricks** [comment]
You need to use a full path, or change the directory using setworkingdirectory and then use a relative path

**Comment by robinrodricks** [comment]
Examples of full paths are "/root/dir/file.txt"

**Comment by sivagatla99** [comment]
Thanks for your replay....

Yes, I'm using full path.
If I keep like below, it's returning true
if (!client.FileExists(rootDir + fileName))

Any idea??

**Comment by robinrodricks** [comment]
Don't understand. You must use full path, or relative path. Which do you want?
