### ISSUE TITLE
How to write unit tests using Moq and FluentFTP?

### ISSUE THREAD

**Issue by martinRocks** [robinrodricks/FluentFTP#247]
This isn't a bug.  It is a change request.

I'm using FluentFTP version 19.1.2.  It is working perfectly.  However, I want to write a unit test using Moq version 4.7.145.  The test that I'm writing is for downloading a file.  In my download code, I'm calling the GetListing method.  My unit test says that I can't mock that call because it isn't virtual.  Can you add this?

Her is my code for downloading a file:
`client.Connect();

                foreach (var item in client.GetListing(Path.Combine("/", ConnectionsFtps.RemoteOutBox)))
                {
                    if (item.Type == FtpFileSystemObjectType.File)
                    {
                        client.DownloadFile(Path.Combine(path, item.Name), item.FullName);
                        client.DeleteFile(item.FullName);
                    }
                }`

Here is my unit test so far:
`var moqFtpClient = new Mock<FtpClient>();
            moqFtpClient.Setup(x => x.Connect());

            var lastModifiedTime = DateTime.Now;
            var ftpListItems = new List<FtpListItem>()
            {
                new FtpListItem(null,"file1.txt",0,false, ref lastModifiedTime),
                new FtpListItem(null,"file2.txt",0,false, ref lastModifiedTime)
            };
            moqFtpClient.Setup(x => x.GetListing(It.IsAny<string>()))
                .Returns(() => ftpListItems.ToArray());`

The error I'm getting in my unit test is:
`System.NotSupportedException: 'Invalid setup on a non-virtual (overridable in VB) member: x => x.GetListing(It.IsAny<String>())'`

**Comment by checkdigits** [comment]
I don't have an answer to your question but really a comment on your example download code..

When you download the file you don't actually check that the download succeeded and then go on to delete the file from the FTP server.  Is this intentional?  

If the download fails or only partially succeeds with the code as it stands right now you'll remove the origin file which might be undesirable behavior.  Ironically your unit test might not catch that (if you manage to solve your original question).  :)

**Comment by robinrodricks** [comment]
Yes, can you write tests against IFtpClient?

**Comment by martinRocks** [comment]
Thank you ckeckdigits.  No that isn't intentional.  That was me not thinking it though.  

If I use the interface, IFtpClient, then I get casting issues.  Maybe that is also my code.

**Comment by martinRocks** [comment]
Using the interface solves my problem, but adds a new one.  How do I mock a connection?
The last line blows up because the cast to FtpClient.  The CreatConnection method just sets up the connection and returns a FtpClient object.

`var moqFtpClient = new Mock<IFtpClient>();
            moqFtpClient.Setup(x => x.Connect());

            var lastModifiedTime = DateTime.Now;
            var ftpListItems = new List<FtpListItem>()
            {
                new FtpListItem(null,"file1.txt",0,false, ref lastModifiedTime),
                new FtpListItem(null,"file2.txt",0,false, ref lastModifiedTime)
            };
            moqFtpClient.Setup(x => x.GetListing(It.IsAny<string>()))
                .Returns(() => ftpListItems.ToArray());
            
            var job = new Mock<Job>();
            job.Setup(x => x.CreatConnection())
                .Returns((FtpClient)moqFtpClient.Object);`

**Comment by martinRocks** [comment]
I think I have a work around for my problem.  In my method that I'm testing, I have a virtual method that does the creates the connection.  I moq that an then my test works perfectly.  The only problem is I am far from 100% covered.

Here is my method that I'm testing.
`       public virtual IFtpClient CreatConnection()
        {
            ...
        }`

        `private void PullFiles(string path)
        {
            try
            {
                var client = CreatConnection();
                client.Connect();

                foreach (var item in client.GetListing(Path.Combine("/", ConnectionsFtps.RemoteOutBox)))
                {
                    if (item.Type == FtpFileSystemObjectType.File)
                    {
                        if (client.DownloadFile(Path.Combine(path, item.Name), item.FullName))
                        {
                            client.DeleteFile(item.FullName);
                        }
                    }
                }

                client.Disconnect();
                client.Dispose();
            }
            catch (Exception e)
            {
                Log.Error(e);
            }
        }`

And then my test method looks like this.
`  [Test]
        public void ExecuteTest()
        {
            var moqJobExecutionContext = new Mock<IJobExecutionContext>();

            var moqFtpClient = new Mock<IFtpClient>();
            moqFtpClient.Setup(x => x.Connect());
            moqFtpClient.Setup(x => x.DownloadFile(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<bool>(), It.IsAny<FtpVerify>(), null))
                .Returns(true);

            var lastModifiedTime = DateTime.Now;
            var ftpListItems = new List<FtpListItem>()
            {
                new FtpListItem(null,"file1.txt",0,false, ref lastModifiedTime),
                new FtpListItem(null,"file2.txt",0,false, ref lastModifiedTime)
            };
            moqFtpClient.Setup(x => x.GetListing(It.IsAny<string>()))
                .Returns(() => ftpListItems.ToArray());

            var job = new Mock<JobPullFtps>();
            job.Setup(x => x.CreatConnection())
                .Returns(() => moqFtpClient.Object);

            job.Object.Execute(moqJobExecutionContext.Object);

            moqFtpClient.Verify(x => x.DownloadFile(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<bool>(), It.IsAny<FtpVerify>(), null), Times.Exactly(2));
        }`

**Comment by robinrodricks** [comment]
Sorry I don't understand enough of mocking to help you out. If you can specify what needs to change in FluentFTP, perhaps we can make those changes. Closing it until we figure out steps needed.
