### ISSUE TITLE
DownloadFiles API freezing in .NET 3.5

### ISSUE THREAD

**Issue by sonygod** [robinrodricks/FluentFTP#249]
use DownloadFiles API  will freezing  .

I use DownloadFiles to download  more than 64 files in one folder at once, but My app was freezing..

how to improve？

environment: use .net 3.5

**Comment by robinrodricks** [comment]
Please answer basic questions, which OS, which server FTP software, etc

**Comment by sonygod** [comment]
local :windows 7 x64  .net 3.5 ,unity 5.6
server  linux ftp (which os I don't konw);


[here ](https://gist.github.com/sonygod/c912f2f76bd6d8e67c24e41ecf480c68)are my modify  code
[here  test code](https://gist.github.com/sonygod/0dcbf33a6d96673130d7004b5bff0db0)are my modify  code

and my ftp remote path folder  have more than 64 files

**Comment by robinrodricks** [comment]
So can you enable logging (see the FAQ) to tell us which server its using?

**Comment by sonygod** [comment]
Linux version 3.10.0-123.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Mon Jun 30 12:09:22 UTC 2014

**Comment by sonygod** [comment]
it's seem your donwload api use synchronization  instead asynchronous?

**Comment by robinrodricks** [comment]
There are both APIs, check the readme.
