### ISSUE TITLE
IsConnected returns true when credentials are incorrect

### ISSUE THREAD

**Issue by roeekl** [robinrodricks/FluentFTP#250]
When I'm connecting with incorrect username/password, an FtpCommandException is thrown, but after that exception, the IsConnected property returns true (because IsConnected checks if the socket has a connection to the server).

So in case your are giving incorrect username/password and ignoring the exceptions (or even connecting in asynchronous operation). you wont be able to identify whether you are connected to the server or not. 

I think that IsConnected should not rely only on the FtpSocketStream.IsConnected property, to prevent this situation.

**Comment by adempehlivan** [comment]
Hello @roeekl did you find a solution for check username and password is true ?

**Comment by PrzemyslawKlys** [comment]
Is there any action for this? `IsConnected` basically always returns true which is a bit counterintuitive. Maybe another property `IsLoggedIn` if we want to keep using `IsConnected` for connection verification?

**Comment by robinrodricks** [comment]
Implemented in 34.0.2.

**Comment by robinrodricks** [comment]
Published.

https://www.nuget.org/packages/FluentFTP/34.0.2
