### ISSUE TITLE
Throw exception when FTP over TLS is not supported

### ISSUE THREAD

**Issue by taoyouh** [robinrodricks/FluentFTP#252]
**FTP OS:** Embedded

**FTP Server:** bftpd

**Computer OS:** Windows 10

UWP build 16299 supports .NET Standard 2.0, where the library works well with FTP over TLS. The problem is in UWP build 15063 and lower, or other .NET Standard 1.4 platforms. When using the library with UWP (lower than build 16299), the library doesn't send AUTH TLS even when EncryptionMode is set to Explicit.

.NET Standard 1.4 doesn't support SslStream so this version of library doesn't support FTP over TLS. However I think there should be some errors when somebody tries to use that. Maybe NotSupportedException should be thrown when using ConnectAsync().

**Logs :**

```
# ConnectAsync()
Status:   Connecting to 192.168.1.1:21
Response: 220 bftpd 2.2.1 at 192.168.1.1 ready.
Command:  USER anonymous
Response: 230 User logged in.
Command:  FEAT
Response: 211 End
Response: 211-Extensions supported:
Response: XPWD
Response: EPRT
Response: EPSV
Response: ALLO
Response: APPE
Response: MDTM
Response: XCWD
Response: XCUP
Response: XMKD
Response: XRMD
Response: REST
Response: SIZE
Response: FEAT
Response: UTF8
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 200 UTF8 ON
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser

# GetListingAsync("/", Auto)
Command:  TYPE I
Response: 200 Transfer type changed to BINARY

# OpenPassiveDataStreamAsync(PASV, "LIST /", 0)
Command:  PASV
Response: 227 Entering Passive Mode (192,168,1,1,203,236)
Status:   Connecting to 192.168.1.1:52204
Command:  LIST /
Response: 150 BINARY data connection established.
+---------------------------------------+
Listing:  drwxrwxrwx   3 0        0        0 Jan 01  1970 shares
-----------------------------------------
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Response: 226 Directory list has been submitted.
Status:   Disposing FtpSocketStream...
Status:   Confirmed format Unix
```

**Comment by robinrodricks** [comment]
So on the .NET Standard 1.4 platform you want the library to throw a NotSupportedException?

**Comment by taoyouh** [comment]
@robinrodricks Yes, that's the behaviour I expect. Or we can disable encryption setting on .NET Standard 1.4.

**Comment by robinrodricks** [comment]
Run this code and tell me what you get on your platform

    string ver = Assembly.GetEntryAssembly()?.GetCustomAttribute<TargetFrameworkAttribute>()?.FrameworkName;

**Comment by robinrodricks** [comment]
Closing as no response given.
