### ISSUE TITLE
we can't change and getList,not work!

### ISSUE THREAD

**Issue by sonygod** [robinrodricks/FluentFTP#258]
first,set and get SetWorkingDirectory   GetListing  to "/work/
and down load files finish ,

then set and get SetWorkingDirectory  to GetListing  "/work/Folder/"
 it's not work the result of,  conn.GetListing(targetFolder, FtpListOption.ForceList | FtpListOption.Recursive)
is 0? but I have 3 files inside it!

how to get All files include folder/child folder ,

it's seem these api not work!

conn.GetListing(targetFolder, FtpListOption.ForceList | FtpListOption.Recursive);

**Comment by sonygod** [comment]
ftp=Response: 550 Failed to change directory.
UnityEngine.Debug:Log(Object)

**Comment by robinrodricks** [comment]
I'm sorry I cannot understand your question.
