### ISSUE TITLE
GetListing sometimes lists content of CWD instead of specified directory?

### ISSUE THREAD

**Issue by ExplodingCabbage** [robinrodricks/FluentFTP#263]
I have no idea how to reproduce, but this appears to be the issue being described at https://stackoverflow.com/q/41466095/1709587

**Comment by robinrodricks** [comment]
Good catch, but I'll really need both the working (FileZilla) and the FluentFTP logs to compare them and see what gives.

**Comment by ExplodingCabbage** [comment]
Yeah, it's hard to guess at what's going on without any information about what server they were using or how it was responding to requests.

**Comment by A9G-Data-Droid** [comment]
I saw this today on a non-standard FTP server hosted by an old embedded device. What I can tell is that when you ask the server to "LIST /FOLDERNAME" it just lists the folder name.  When I look at the FileZilla logs I can see that what FileZilla is doing is changing directory in to that folder and then issuing a blank LIST. This behavior is required on the set of devices I am using. Let me know if you need me to do additional testing. 

```
CWD /FOLDERNAME
LIST
```

**Comment by A9G-Data-Droid** [comment]
Here is a redacted example of the problem:

```
Status:   Connecting to 
Response: 220 FTP server ready.
Command:  USER ***
Response: 331 User name okay, need password.
Command:  PASS ***
Response: 230 User logged in, proceed.
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 502 SYST command not implemented, or not allowed.
Warning:  Cannot auto-detect listing parser for system 'Unknown', using Unix parser
Command:  TYPE A
Response: 200 TYPE Command okay.
Command:  PASV
Response: 227 Entering Passive Mode ().
Status:   Connecting to 
Command:  LIST /FOLDERNAME
Response: 150 File status okay; about to open data connection.
+---------------------------------------+
Listing:  drwxrwxrwx   1 owner    group               0 Jan 01  2000 FOLDERNAME
-----------------------------------------
Status:   Disposing FtpSocketStream...
Response: 226 Closing data connection.
Status:   Disposing FtpSocketStream...
Status:   Confirmed format Unix
Command:  QUIT
Response: 221 Goodbye.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
```

**Comment by A9G-Data-Droid** [comment]
To get the behavior I want I am using:

    client.SetWorkingDirectory(ftpPath)
    var ftpList = Await client.GetListingAsync(Nothing, FtpListOption.NoPath)

It would be nice to have a Custom Server detection that would behave this way. I would write one for my case but I don't see `GetListingAsync` as an Extendable handlers here https://github.com/robinrodricks/FluentFTP/wiki/Custom-Servers.

Is this difficult to do?

**Comment by FanDjango** [comment]
See Wiki [path problems](https://github.com/robinrodricks/FluentFTP/wiki/Troubleshooting#trouble_paths)

**Comment by A9G-Data-Droid** [comment]
Wait, the solution was to document the workaround? Why not have a custom server definition we can use when we need this behavior? Then I could just turn on the feature for servers that require it.

**Comment by FanDjango** [comment]
Ok, I see what you are saying. Let's put Extendable Server Detection on the bucket list. Is that a good next step?

**Comment by FanDjango** [comment]
@A9G-Data-Droid This is now pending being transferred to the list of planned enhancements. Then this issue will once again be closed. 

What you are requesting is already in the overall plan, so this is slightly redundant.

Referring this to the Wiki is to help those who browse these open or closed issues and need an immediate workaround to achieve their goals without waiting for enhancements.

**Comment by robinrodricks** [comment]
@A9G-Data-Droid We are planning on having this behavior done automatically, so we are in line with how filezilla handles things. It was planned for v40 but skipped due to lack of time. I'm aware of this.
