### ISSUE TITLE
Explicit connection thows exception when used from .NET 4.6.2 but it doesn't when used from .NetStandard 2.0

### ISSUE THREAD

**Issue by melenaos** [robinrodricks/FluentFTP#265]
**FTP OS:** Windows

**FTP Server:** Shared Hosting @ Fastcomet

**Computer OS:** Win 10

I have implemented a solution with three projects;
- NetStandard 2.0. It is a wrapper of FluentFTP for uploading files and testing connection settings (uses upload files function for testing) [installed nuget package 19.1.2]
- .NET Core 2.0. Web App that uses FuentFTP wrapper to test the connection settings. 
- .NET 4.6.2. Azure Web Job that uploads files to the ftp using the FluentFTP wrapper [installed nuget package 19.1.2]

I have noticed that .NET Core project can use and upload files when `EncryptionMode=FtpEncryptionMode.Explicit` but the Web Job fails with this setting (works with `FtpEncryptionMode.None`).

Web Job thows the following error (translated from Greek because my developing pc's locale is Greek);
`Unable to read data from the transfer connection An existing connection was interrupted by the remote computer.`

I removed nuget package from web job and directly linked the NetStandard 1.6 assembly from the packages folder. Then it worked both in Core and in web job.

I assume that the implementation of the net45 has a bug in the `FtpEncryptionMode.Explicit` mode.

**Comment by robinrodricks** [comment]
Good work testing this. I'll check it out.

**Comment by robinrodricks** [comment]
.NET Support reworked (soon to be removed) as of v40. Please add a note if this issue still occurs. Closing as it is not applicable.
