### ISSUE TITLE
Downloading file unable to open path

### ISSUE THREAD

**Issue by GunzForhire** [robinrodricks/FluentFTP#266]
**FTP OS:** Windows Server 2016

**FTP Server:** FileZilla
**Computer OS:Windows 10

When I do a Download file I get the error: FluentFTP.FtpException: Error while creating directories. See InnerException for more info. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\folder'.
   at System.IO.WinRTFileSystem.<CreateDirectoryAsync>d__9.MoveNext()
--- End of stack trace 

The folder exists and the path I tried to use an escaped path and replacing \ with / but it doesn't solve the problem. 

The strange thing is that the destination with the file is about 5 folders down from the C: and the error only gives back as path the first folder. Normaly the error returns the full path. Does the path get cuttof at some point or something, or am I just to stupid to see my mistake?

How I used the method: client.DownloadFile(@"C:\folder1\folder2\folder3\test.txt", ob.FullName);
client.DownloadFile("C:/folder1/folder2/folder3/test.txt", ob.FullName);

Also: My first language is not English, so excuse me for my grammar or punctuation misatkes.

**Logs :**

```
FluentFTP.FtpException: Error while creating directories. See InnerException for more info. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\folder1'.
   at System.IO.WinRTFileSystem.<CreateDirectoryAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.WinRTFileSystem.CreateDirectory(String fullPath)
   at System.IO.MultiplexingWin32WinRTFileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at FluentFTP.FtpClient.DownloadFileToFile(String localPath, String remotePath, Boolean overwrite, FtpVerify verifyOptions, IProgress`1 progress)
   --- End of inner exception stack trace ---
   at FluentFTP.FtpClient.DownloadFileToFile(String localPath, String remotePath, Boolean overwrite, FtpVerify verifyOptions, IProgress`1 progress)
   at FluentFTP.FtpClient.DownloadFile(String localPath, String remotePath, Boolean overwrite, FtpVerify verifyOptions, IProgress`1 progress)
   at FTPConnector.MainPage.<RetrieveDataAsync>d__7.MoveNext()
```

**Comment by robinrodricks** [comment]
Try downloading to a drive you have write permissions to. Maybe your app does not have security permissions to write to that folder. Or try writing to `C:\file.txt` or `D:\file.txt` and see if that works.

**Comment by robinrodricks** [comment]
Not sure how to test/fix this one. Maybe if you reply with logs and a suggested fix we can proceed with this.

**Comment by GhostCakeMaker** [comment]
FTP OS：linux

FTP Server：Windows Server 2012 R2

I also encountered this problem, and I tried a different path, but it didn't work.

This phenomenon is very rare, I download files from 70 devices, only two of them have this problem.

**Source:**
```
var ftpStatus = x.Key.DownloadFile(downloadPath, fItem.FullName, existsMode: FtpLocalExists.Append);
```
**Log:**
```
Error while creating directories. See InnerException for more info.  
 FluentFTP.FtpClient.DownloadFileToFile(String localPath, String remotePath, FtpLocalExists existsMode, FtpVerify verifyOptions, Action`1 progress, FtpProgress metaProgress)
FluentFTP.FtpClient.DownloadFile(String localPath, String remotePath, FtpLocalExists existsMode, FtpVerify verifyOptions, Action`1 progress)
```

**Comment by GhostCakeMaker** [comment]
> FTP操作系统：linux
> 
> FTP服务器：Windows Server 2012 R2
> 
> 我也遇到了这个问题，我尝试了另一条路径，但是没有用。
> 
> 这种现象非常罕见，我从70台设备下载文件，其中只有两个有此问题。
> 
> **资源：**
> 
> ```
> var ftpStatus = x.Key.DownloadFile(downloadPath, fItem.FullName, existsMode: FtpLocalExists.Append);
> ```
> 
> **日志：**
> 
> ```
> Error while creating directories. See InnerException for more info.  
>  FluentFTP.FtpClient.DownloadFileToFile(String localPath, String remotePath, FtpLocalExists existsMode, FtpVerify verifyOptions, Action`1 progress, FtpProgress metaProgress)
> FluentFTP.FtpClient.DownloadFile(String localPath, String remotePath, FtpLocalExists existsMode, FtpVerify verifyOptions, Action`1 progress)
> ```

I have found out the reason. The reason is that the name of the file I downloaded contains special characters and garbled, as shown in the figure below:
![image](https://user-images.githubusercontent.com/40969294/106542726-4fbc0800-653f-11eb-847f-f228d3247f03.png)

**Comment by GhostCakeMaker** [comment]
> > FTP操作系统：linux
> > FTP服务器：Windows Server 2012 R2
> > 我也遇到了这个问题，我尝试了另一条路径，但是没有用。
> > 这种现象非常罕见，我从70台设备下载文件，其中只有两个有此问题。
> > **资源：**
> > ```
> > var ftpStatus = x.Key.DownloadFile(downloadPath, fItem.FullName, existsMode: FtpLocalExists.Append);
> > ```
> > 
> > 
> > **日志：**
> > ```
> > Error while creating directories. See InnerException for more info.  
> >  FluentFTP.FtpClient.DownloadFileToFile(String localPath, String remotePath, FtpLocalExists existsMode, FtpVerify verifyOptions, Action`1 progress, FtpProgress metaProgress)
> > FluentFTP.FtpClient.DownloadFile(String localPath, String remotePath, FtpLocalExists existsMode, FtpVerify verifyOptions, Action`1 progress)
> > ```
> 
> I have found out the reason. The reason is that the name of the file I downloaded contains special characters and garbled, as shown in the figure below:

1!ññ_2020-11-18-08-25-19.txt
--



> ![image](https://user-images.githubusercontent.com/40969294/106542726-4fbc0800-653f-11eb-847f-f228d3247f03.png)
