### ISSUE TITLE
Connecting to wrong port doesn't throw exception or timeout

### ISSUE THREAD

**Issue by AlKau** [robinrodricks/FluentFTP#274]
**FTP OS:** (ftp://test.rebex.net)

**FTP Server:** (ftp://test.rebex.net)

**Computer OS:** Win10

**App:** UWP

Fluent FtpClient has default settings.
It can connect to ftp://test.rebex.net:21 or ftp://test.rebex.net:990 (use Task FtpClient.ConnectAsync()). 
When type wrong port like 22, 143 (I think the port should be open but not ftp) the task never ends.

p.s. I can't write logs, because I don't know how to include it in UWP

**Comment by robinrodricks** [comment]
You could save logs to a textfile. There is an option for that even in the UWP version.

**Comment by AlKau** [comment]
I added FtpTrace.LogToFile = "log_file.txt"; 
and got exception **System.UnauthorizedAccessException**: 'Access to the path 'C:\Development\FtpTest\bin\x64\Debug\AppX\log_file.txt' is denied.' on line await _client.ConnectAsync();

**Comment by robinrodricks** [comment]
Connecting reworked in v40. Please add a new issue if this still occurs. Closing for now.
