### ISSUE TITLE
GetListing without CWD

### ISSUE THREAD

**Issue by nfrankish** [robinrodricks/FluentFTP#277]
**FTP OS:** Unix 

**FTP Server:** xOS

**Computer OS:** ? Windows

Maybe more a question. I need to send a LIST command without a directory attached to it.
If i call blank or "", it gets the CWD and sends that. But i need to send it without.
Can i open the passive data stream manaully?

**Comment by robinrodricks** [comment]
Extend the FtpClient class and copy the GetDirectory() method into it, extending it. Then you can make whatever changes you want.
