### ISSUE TITLE
FtpClient does not honor CanSeek property of the Stream class

### ISSUE THREAD

**Issue by mmedic** [robinrodricks/FluentFTP#279]
**FTP OS:** Not relevant

**FTP Server:** Not relevant

**Computer OS:** Any

`UploadFileInternal` method of `FtpClient` class relies on `Stream` `Length` property and does not honor related `CanSeek` property like it does for rewinding the stream. If the stream does not support seeking, the `Length` property of the `Stream` class will throw `NotSupportedException`. One should not rely on `Stream` length to determine when writing is finished but rather when no more data can be read from the stream.

**Logs :**

Not needed.

**Comment by robinrodricks** [comment]
Thanks for this. However, unless this code crashes with an exception we prefer not to change underlying details. The code is time tested and battle hardened, and any messing around with it usually results in more side effects.
