### ISSUE TITLE
 FtpCommandException: Command NLST not implemented.

### ISSUE THREAD

**Issue by TeddyBean** [robinrodricks/FluentFTP#280]
**Computer OS:** Windows

<write details about your bug report / feature request here>

**Is there a new flag to do not use NLST-Command?**

**In FluentFtp 16.4.0 i can upload and download to the ftp-server - all right.** 

**In Version 19.1.2 same code is not working anymore. I get this error...**

FluentFTP.FtpException
  HResult=0x80131500
  Message=Error while uploading the file to the server. See InnerException for more info.
  Source=FluentFTP
  StackTrace:
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress)
   at FluentFTP.FtpClient.UploadFileFromFile(String localPath, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, FtpVerify verifyOptions, IProgress`1 progress)
   at FluentFTP.FtpClient.UploadFile(String localPath, String remotePath, FtpExists existsMode, Boolean createRemoteDir, FtpVerify verifyOptions, IProgress`1 progress)
   at Ally.Elda.EldaFtp.TestUploadEldaFile() in C:\vsproj\VIPAS\VIPAS.NET\Ally.Elda\Ftp\EldaFtp.cs:line 35
   at Ally.Elda.Unit.Test.EldaFtpTests.EldaUploadTest() in C:\vsproj\VIPAS\VIPAS.NET\Ally.Elda.Unit.Test\EldaFtpTests.cs:line 11

Inner Exception 1:
FtpCommandException: Command NLST not implemented.

this ist the test-code to upload:

public void TestUploadEldaFile() {
            using (FtpClient cl = new FtpClient()) {
                EldaConnection(cl);
                string localfile = Path.Combine(localdir, eldaUploadFileName);
                string serverfile = Path.Combine(uploadDir, eldaUploadFileName);
                cl.UploadFile(localfile, serverfile);
            }
        }

private void EldaConnection(FtpClient cl) {
            SetEldaUser();
            cl.Host = host;
            cl.EncryptionMode = FtpEncryptionMode.Explicit;
            cl.ConnectTimeout = 15000;
            cl.DataConnectionConnectTimeout = cl.ConnectTimeout;
            cl.SslProtocols = System.Security.Authentication.SslProtocols.Tls;
            cl.ValidateCertificate += OnValidateCertificate;
            cl.DataConnectionType = FtpDataConnectionType.PASV;

            X509Certificate2 cert = new X509Certificate2("elda.at.crt");
            cl.ClientCertificates.Add(cert);
            cl.Credentials = new NetworkCredential(user, pass);

            FtpTrace.AddListener(new TextWriterTraceListener(@"c:\temp\ftp.txt"));
            FtpTrace.LogUserName = false;
            FtpTrace.LogPassword = false;
            FtpTrace.LogIP = false;

            return;
        }
`

this are the implementet commands on that server
• AUTH
• CWD
• DELE
• FEAT
• HELP
• LANG
• LIST
• MODE
• PASS
• PASV
• PBSZ
• PROT
• PWD
• QUIT
• REST
• RETR
• SITE
• STAT
• STOR
• STOU
• TYPE
• USER 

here is the log...
**Logs :**
```
# UploadFile("N:\UTILITY\ELDA\ftp-test\eldatest.txt", "eldatest.txt", Overwrite, False, None)

# FileExists("eldatest.txt")

# GetWorkingDirectory()

# Connect()
Status:   Connecting to ***:21
Response: 220 ELDA-FTPS Server ready for new user.
Command:  AUTH TLS
Response: 234 Command AUTH okay; starting TLS connection.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0,2750663.
Command:  USER ***
Response: 331 User name okay, need password for 106036.
Command:  PASS ***
Response: 230 Running ELDA FTPS Version 1.3.8.2
Response: 230-User 106036 logged in.
Command:  PBSZ 0
Response: 200 Command PBSZ okay.
Command:  PROT P
Response: 200 Command PROT okay.
Command:  FEAT
Response: 211 End
Response: 211-Extensions supported
Response: SIZE
Response: MDTM
Response: REST STREAM
Response: LANG en;zh-tw;ja;is
Response: MLST Size;Modify;Type;Perm
Response: AUTH SSL
Response: AUTH TLS
Response: MODE Z
Response: UTF8
Response: TVFS
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 502 Command OPTS not implemented.
Command:  SYST
Response: 502 Command SYST not implemented.
Warning:  Cannot auto-detect listing parser for system 'UNKNOWN', using Unix parser
Command:  PWD
Response: 257 "/2787103282" is current directory.
Command:  SIZE /2787103282/eldatest.txt
Response: 502 Command SIZE not implemented.
Command:  MDTM /2787103282/eldatest.txt
Response: 502 Command MDTM not implemented.

# GetNameListing("/2787103282")
Command:  TYPE I
Response: 200 Command TYPE okay.

# OpenPassiveDataStream(PASV, "NLST /2787103282", 0)
Command:  PASV
Response: 227 Entering Passive Mode (194,153,217,66,39,38)
Status:   Connecting to ***:10022
Command:  NLST /2787103282
Response: 502 Command NLST not implemented.
Status:   Disposing FtpSocketStream...

# CloseDataStream()

```

**Comment by robinrodricks** [comment]
Change this to use : `FtpExists.NoCheck`. This way there will not be any file check and the NLST command will not be used. See if it works?

**Comment by TeddyBean** [comment]
YES! That solved this Problem. Thanks a lot.
