### ISSUE TITLE
UploadFile - client connected, no exception, no progress, returns false

### ISSUE THREAD

**Issue by troncomputers** [robinrodricks/FluentFTP#285]
FTP OS: Embedded 
FTP Server: WD Cloud with BusyBox
Computer OS: Windows 10

```csharp
FtpClient client = new FtpClient(Host);
client.Credentials = new NetworkCredential(User, Password);
client.Connect();
if (client.IsConnected)
{
    LOG.WriteInfo("Connected!");
    Progress<double> progress = new Progress<double>(x =>
    {
        LOG.WriteInfo(x.ToString() + "%");
    });

    client.RetryAttempts = 10;
    return client.UploadFile(fileName, $"/u{ftp.NIP}/{fileName}", FtpExists.Overwrite, false, FtpVerify.Retry, progress);
}
else
{
    LOG.WriteInfo("Not connected");
    return false;
}
```
I have an app for making backups of SQL Server databases and store them on the FTP server. There is one which is acting very weird. There is no exception, application is logging `Connected!` but I'm not getting any progress and `client.UploadFile()` is giving me `false`. I'm not sure if it's trying to `RetryAttempts` 10 times because I'm sending them one by one and it's quickly doing another database.

**Comment by robinrodricks** [comment]
Can you enable logging as shown in the FAQ? It will help you debug this.

**Comment by robinrodricks** [comment]
If you reply with logs and a suggested fix we can proceed with this.
