### ISSUE TITLE
Can't upload to FTP server in UWP

### ISSUE THREAD

**Issue by BullT** [robinrodricks/FluentFTP#289]
**FTP OS:** Windows 10

**FTP Server:** Pure-FTPd

**Computer OS:** Windows 10

Hi,

I can't upload a file into FTP server programaing with VS2017 a UWP.

        private void TestFTP()
        {
            FtpClient client = new FtpClient("192.168.1.10");
            client.Credentials = new NetworkCredential("upload", "---------");

            client.Connect();

            client.UploadFile(@"C:\BullT.txt", "/BullT.txt");     // ERROR

            client.Disconnect();
        }

ERROR: System.InvalidOperationException: 'Synchronous operations should not be performed on the UI thread.  Consider wrapping this method in Task.Run.'

What I have to do to olve the problem?

Thanks

**Logs :**

```
<paste logs here but DO NOT delete the lines above and below this line>
```

**Comment by robinrodricks** [comment]
Try using the async methods?

    private void TestFTP()
    {
        FtpClient client = new FtpClient("192.168.1.10");
        client.Credentials = new NetworkCredential("upload", "---------");

        client.Connect();

        await client.UploadFileAsync(@"C:\BullT.txt", "/BullT.txt");     // <<<<<

        client.Disconnect();
    }
