### ISSUE TITLE
FTPS Authentification Hanging after a RemoteCertificateChainError

### ISSUE THREAD

**Issue by noob4hire** [robinrodricks/FluentFTP#300]
**FTP OS:**  Windows Server 2008/2012

**FTP Server:** MS FTPS Server

**Computer OS:** Windows Server 2008/2012

I am trying to connect to our FTPS server from a program I wrote using FluentFTP (which I love, BTW).  But, I'm getting a RemoteCertificateChainError with the text "The revocation function was unable to check revocation because the revocation server was offline".  It gets this after what seems to be the expiration of some timeout.  Sounds like the CRL server is offline, right?  Funny thing is... If I delete a certain certificate (Entrust Root Authority - G2), it works!  Even more weird... this works from my laptop ( W10) even though the same certificate exists there!  I have spent countless hours trying to solve this and am at a loss.  It hangs on the line: "m_sslStream.AuthenticateAsClient(targethost, clientCerts, sslProtocols, true);".  But, you'll notice that it says authentication was successful even though it bombs out with a no connection error.  Thanks for your help!

**Logs :** FluentFTP Verbose: 0 :
FluentFTP Verbose: 0 : # Connect()
FluentFTP Information: 0 : Status:   Connecting to 204.124.192.97:990
   (This is where it pauses for a long time, then times out.)
FluentFTP Information: 0 : Status:   FTPS Authentication Successful
FluentFTP Verbose: 0 : Status:   Time to activate encryption: 0h 2m 6s.  Total S
econds: 126.1636514.
FluentFTP Verbose: 0 : Status:   Testing connectivity using Socket.Poll()...
FluentFTP Verbose: 0 : Status:   Disposing FtpSocketStream...

UPDATE: 5/24/18
I've been doing a certutil verification on the certificate and I can see that it is failing on trying to get to revocation related URLs.  I'm behind a firewall.  So option 1:  I would need to open the firewall for those sites.  Or option 2:  Because the FTPS site is to a sister company, I don't think the CRL is such a big issue.  As an alternative would be to not check revocation at all.  Is there a way in FluentFTP to instruct the Authentication call (line 996 of FtpSocketStream.cs: m_sslStream.AuthenticateAsClient(targethost, clientCerts, sslProtocols, true); ) to not check any revocation URLs? 
Thanks

```
<Contents of log are above>
```

**Comment by noob4hire** [comment]
After more debug, I found that the answer to the problem is in the last parameter of the AuthenticateAsClient call.  It is a Boolean that controls where revocation checking should be performed.  My suggestion to Mr. Rodricks would be to add a property that would allow FtpClient to disable revocation checking.  This is useful when behind one or many firewalls and otherwise secure areas and file transfers are with trusted FTPS server.  (In our case, a sister company and the traffic never even makes it to the cloud.)  It is a little less secure and a lot of work to open up sensitive areas to the FTP server which may be layers lower in the security hierarchy.  Therefore, it is nice to be able to disable looking for CRLs when they are not really needed. 

Thanks for listening.

**Comment by robinrodricks** [comment]
I will do this. Just remind me again tomorrow if I forget. Small changes
are easy to make.

**Comment by noob4hire** [comment]
Grate to hear from you!  I’ve already hard-coded the revocation parameter to false for my purposes.  But, I will be anxious to have this function in base-line so things won’t break next time we upgrade.  I will also try to get some time to implement your changes as soon as they become available.

Thanks again for being responsive!

Sincerely,

Dan Hadfield
SCADA/RT
Kern River Gas Transmission
801-937-6083

**Comment by noob4hire** [comment]
As you'd asked, just a reminder to implement the property to allow control of whether revocation checking is enabled...

thanks again!

**Comment by robinrodricks** [comment]
I'm sorry I'm not at my pc right now and I'm pretty sure to forget. Can you
rename this with [To Do] in the prefix of the title of the issue? Thanks..

**Comment by noob4hire** [comment]
I would be most happy to…

**Comment by noob4hire** [comment]
Done
