### ISSUE TITLE
553 Could not create file.

### ISSUE THREAD

**Issue by joshuasm** [robinrodricks/FluentFTP#301]
**FTP OS:** linux mint

**FTP Server:** Vsftpd

**Computer OS:** Windows10

Im creating a C# backup program that uploads files to a server where they then get archived.
my code for this is as follows:

`private void Upload(FileInfo file, string remoteDir) {

            // create an FTP client
            using (FtpClient ftp = new FtpClient(ip)) {

                // if you don't specify login credentials, we use the "anonymous" user account
                ftp.Credentials = new NetworkCredential("protea447", password);

                // begin connecting to the server
                ftp.Connect();
                
                var startTime = DateTime.Now.Second;

                ftp.RetryAttempts = 3;

                try {
                    var rdir = "";
                    rdir = remoteDir + "/" + file.Name;
                    Console.WriteLine(DateTime.Now.ToString() + ": Transfer of {0} Started.", file.Name);

                    ftp.UploadFile(file.FullName, rdir);
                } catch (Exception ex) {
                    Console.WriteLine(DateTime.Now.ToString() + ": ERROR: " + ex.Message);
                }
                //Console.WriteLine("fin");
                Console.WriteLine(DateTime.Now.ToString() + ": Transfer of {0} Finished and took {1} seconds to complete.", file.Name, (DateTime.Now.Second - startTime));

            }

        }`

every time I run it I get the following output on all files:
```
# Connect()
Status:   Connecting to 192.168.1.2:21
Response: 220 (vsFTPd 3.0.2)
Command:  USER protea447
Response: 331 Please specify the password.
Command:  PASS ***
Response: 230 Login successful.
Command:  FEAT
Response: 211 End
Response: 211-Features:
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: REST STREAM
Response: SIZE
Response: TVFS
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser
5/19/2018 3:21:09 PM: Transfer of aGj8GnG_460s.jpg Started.

# UploadFile("C:\Users\Pro009214\Desktop\aGj8GnG_460s.jpg", "/TerminalBackups/NewTests/Users/Pro009214/Desktop/aGj8GnG_460s.jpg", Overwrite, False, None)

# FileExists("/TerminalBackups/NewTests/Users/Pro009214/Desktop/aGj8GnG_460s.jpg")
Command:  SIZE /TerminalBackups/NewTests/Users/Pro009214/Desktop/aGj8GnG_460s.jpg
Response: 550 Could not get file size.

# OpenWrite("/TerminalBackups/NewTests/Users/Pro009214/Desktop/aGj8GnG_460s.jpg", Binary)
Command:  TYPE I
Response: 200 Switching to Binary mode.

# OpenPassiveDataStream(AutoPassive, "STOR /TerminalBackups/NewTests/Users/Pro009214/Desktop/aGj8GnG_460s.jpg", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||64816|).
Status:   Connecting to 192.168.1.2:64816
Command:  STOR /TerminalBackups/NewTests/Users/Pro009214/Desktop/aGj8GnG_460s.jpg
Response: 553 Could not create file.
Status:   Disposing FtpSocketStream...

# CloseDataStream()

# CloseDataStream()
Exception thrown: 'FluentFTP.FtpCommandException' in FluentFTP.dll
Exception thrown: 'FluentFTP.FtpException' in FluentFTP.dll

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Response: 221 Goodbye.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
```

is there something i ma doing wrong?

**Comment by robinrodricks** [comment]
We had a related fix a while ago. Please check if its fixed in the latest release?

**Comment by robinrodricks** [comment]
Please reply if you still have this issue.
