### ISSUE TITLE
How do I get the owner's name/info for a file?

### ISSUE THREAD

**Issue by stinkfox** [robinrodricks/FluentFTP#303]
As per Title, how do I extract the owner's name for a file?

**Comment by robinrodricks** [comment]
I don't think the FTP standard allows retrieving such details. If you can
do it in your favourite FTP client then it may be possible for us to
support it.

**Comment by stinkfox** [comment]
I believe Winscp is capable of displaying "Owner", programmatically, and also with its GUI.

**Comment by robinrodricks** [comment]
Unless you tell me the FTP command that does it, I can't help you. Use the FTP log and open the file info in Winscp, and see which commands execute. Heck, execute it yourself with `client.Execute()` after you find out. Good luck!
