### ISSUE TITLE
An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by pankaj-nikam** [robinrodricks/FluentFTP#305]
Hi,

I am having shared hosting with Smarter ASP. I am trying to upload a file to a FTP server using FluentFTP with the following code:

```
using (FluentFTP.FtpClient client = new FluentFTP.FtpClient(item.FtpUrl, 21, item.UserName, item.Password))
{
      client.ActivePorts = new[] { 21 };
      await client.UploadFileAsync(filePath, System.IO.Path.GetFileName(filePath));
} 
```
When I use it on my local machine it works fine, however when I use the shared hosting, it shows the error: 

> An attempt was made to access a socket in a way forbidden by its access permissions 14.141.54.43:53446

I had a word with my hosting provider which suggested me to add a firewall exception to the IP and port, however I want it to connect over just 21 port and not with the other port as I can add only 2 more firewall exceptions. Can you please guide me how to achieve this?

Thanks.

**Comment by robinrodricks** [comment]
Change the FTP mode (active, passive) and see which works for you.

**Comment by pankaj-nikam** [comment]
Thanks for the answer. I will check this and will let you know :)

**Comment by pankaj-nikam** [comment]
Hi,

I tried with the following code:

```
using (FluentFTP.FtpClient client = new FluentFTP.FtpClient(item.FtpUrl, 21, item.UserName, item.Password))
{
      client.ActivePorts = new[] { 21 };
      client.DataConnectionType = FluentFTP.FtpDataConnectionType.PASV;
      await client.UploadFileAsync(filePath, System.IO.Path.GetFileName(filePath));
}
```

And still I am getting the same error. Is that the correct way I have use for the FTP mode? If not, can you please guide me?

**Comment by pankaj-nikam** [comment]
Hi @robinrodricks can you please guide?

Thanks.

**Comment by ClanLeader** [comment]
Hi Pankaj,

Have you ask your hosting provider about this issue? I also believe the problem from your settings or Firewall. What is the error message that you see?
