### ISSUE TITLE
Any sample of .net 4.0 asyn upload & donwload files?

### ISSUE THREAD

**Issue by summy00** [robinrodricks/FluentFTP#306]
accroding to :

> Note: All methods support synchronous and asynchronous versions. Simply add the "Async" postfix to a method for async/await syntax in .NET 4.5+, or add the "Begin"/"End" prefix to a method for .NET 4.0 and below.

I can't find any API of BeginUploadFiles(), any suggestion? thanks!

**Comment by robinrodricks** [comment]
In NET 4 and UWP just use 'await client.UploadFilesAsync(...)' or whatever
API... Add Async postfix. The begin/end methods are only for .net 2 and
lower.

**Comment by summy00** [comment]
@robinrodricks 
but I found: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/index#previous-versions
async/await only work in .net 4.5+

**Comment by robinrodricks** [comment]
We dont support older platforms so much.
