### ISSUE TITLE
Any resume mechanism in FluentFTP?

### ISSUE THREAD

**Issue by summy00** [robinrodricks/FluentFTP#307]
Hi, I want to know is there any resume mechanism in uploading/downloading progress?

Thanks!

**Comment by robinrodricks** [comment]
No, there is no way to pause or resume at the moment.

You can cancel using the cancellation token but that's it.

**Comment by robinrodricks** [comment]
Some functions take a `resumeLocation` parameter, maybe try those. (DownloadFile and UploadFile, I think)

**Comment by alhami** [comment]
@robinrodricks Will the resume functionality be included? This is standard functionality for any FTP server and would bring real value to FluentFtp.

**Comment by robinrodricks** [comment]
@alhami Yes we now support resume for downloads and uploads. See the FAQ for more info.
