### ISSUE TITLE
Download with resume doesn't work as expected

### ISSUE THREAD

**Issue by pmengal** [robinrodricks/FluentFTP#309]
I'm replacing Rebex FTP with Fluent FTP. Everything was much better until I discovered that download resuming, that we use heavily, doesn't work as expected in many cases.

Files (zip archives) got corrupted after the second attempt. Second attempt occurs when the application craches during a download (or when I close the console window manually for testing purpose).

My code:

> FtpClient ftpClient = new FtpClient(host, port, username, password);
> ftpClient.Connect();
> ftpClient.DownloadFile(localFile, remoteFile, false, FtpVerify.None, new Progress<double>(x =>
>                {
>      logger.Debug($"Downloading {remoteFile}: ({x:0.##}%)";
>                }));
>ftpClient.Disconnect();

**Comment by robinrodricks** [comment]
What is download resuming? Can you elaborate?

**Comment by pmengal** [comment]
Hello @robinrodricks. Download resuming is a feature that allows an interrupted download to be resumed later, without having to download the chunk that is already present on the disk.

We were using this functionality specifically: https://www.rebex.net/ftp-ssl.net/features/file-transfer.aspx#autoresume

It just works.

About the wording, it seems that https://winscp.net/eng/docs/resume uses the generic word "transfer" to include both upload & download. http://www.dart.com/ftp-control-features.aspx uses "interrupted transfer" to quality the problem, while https://www.chilkatsoft.com/ftp-2-dotnet.asp writes about "restart".

I hope it helps.

**Comment by robinrodricks** [comment]
Thanks for defining "resuming" for me, but I think you misunderstood my intent. I was referring to this comment:

> until I discovered that download resuming, that we use heavily, doesn't work as expected in many cases.
What download resuming in FluentFTP are you talking about? Can you elaborate?

**Comment by pmengal** [comment]
This : https://github.com/robinrodricks/FluentFTP/issues/307

**Comment by n0ix** [comment]
I extented the high level api a bit. See pull Request #372  - may be it fixes your issues.

**Comment by pmengal** [comment]
@n0ix thanks that exactly what I needed.

**Comment by robinrodricks** [comment]
Resuming has improved now. Can you check the latest version and see if it works for you? If it doesn't, I'll reopen this issue.
