### ISSUE TITLE
How to connect to plain (insecure) FTP site without TLS?

### ISSUE THREAD

**Issue by Pyroseza** [robinrodricks/FluentFTP#312]
**FTP OS:** Unix

**FTP Server:** Pure-FTPd

**Computer OS:** Windows

How to connect to plain (insecure) FTP site without TLS?

I am able to connect but not able to list directory contents or transfer files using Fluent FTP.
I get a connection timeout error but I know I am connected for sure.

If I do the same in with Windows FTP I get the exact same error.

If I use quick connect in FileZilla I also get the same error.

However....

If I add the connection to FileZilla and specify "Only use plain FTP (insecure)" it works perfectly fine.

I do not have access to configure the remote server I would like to use FluentFTP to connect the same plain (insecure) way as FileZilla.

Please help.

**Comment by robinrodricks** [comment]
Set this before connecting:

`client.EncryptionMode = FtpEncryptionMode.None`

**Comment by ecatugy** [comment]
@Pyroseza  I have the same problem, were you able to solve it ?

**Comment by Pyroseza** [comment]
Hi @ecatugy unfortunately not

**Comment by izellso** [comment]
Event if FtpClient is constructed with FtpConfig `EncryptionMode = FtpEncryptionMode.None` and `SsslProtocols = SslProtocols.None` I wasn't able to connect insecurely to Ftp Server.

What worked for me, in case somebody else needs this information, was to AutoDetect for the FtpProfiles and then mutate it's Protocols and Encryption properties before connecting.

Something like this:
![image](https://user-images.githubusercontent.com/43554236/224354885-4287d777-be6e-4e43-b27c-6c100f047e1b.png)

**Comment by FanDjango** [comment]
I don't believe. I also use AutoConnect with a non-TLS server and no problems.

Please open a new issue with a verbose log, version information, server information and a snippet of your code.

I will be happy to investigate that.
