### ISSUE TITLE
client.GetListing   Unable to read data from transport connection: Remote host forced to close an existing connection

### ISSUE THREAD

**Issue by lctk** [robinrodricks/FluentFTP#319]
FTP OS: Unix

FTP Server: ftpd

An error occurred in the client.GetListing method call, unable to read data from the transport connection: The remote host forcibly closed an existing connection.

StackTrace ：
System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
    FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
    FluentFTP.FtpSocketStream.ReadLine(Encoding encoding)
    FluentFTP.FtpClient.GetReply()
    FluentFTP.FtpClient.Execute(String command)
    FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
    FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
    FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
    FluentFTP.FtpClient.GetListing(String path, FtpListOption options)

Log:
Status:   Connecting to 192.168.99.163:21
Response: 220 Hello!
Command:  USER tysd
Response: 331 OK
Command:  PASS ***
Response: 230 OK
Command:  FEAT
Response: 211 End
Response: 211-
Response: MDTM
Response: MLST Type*;Size*;Modify*;Perm*;UNIX.mode;
Response: PASV
Response: SIZE
Response: TVFS
Response: UTF8
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 200 OK
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser
Command:  TYPE I
Response: 200 OK
Command:  EPSV
Response: 502 Invalid command "EPSV"
Command:  PASV

**Comment by robinrodricks** [comment]
Your server doesnt support EPSV which is enhanced passive mode. Try using another transfer mode. Or update your outdated server.
