### ISSUE TITLE
Images get artifacts when uploading them to ftp

### ISSUE THREAD

**Issue by mikaelekstrom** [robinrodricks/FluentFTP#327]
**FTP OS:** Unix 

**FTP Server:** 

**Computer OS:** Windows

When i try to upload images to an ftp using the upload function with the binary payload it works for three of our four ftps, on the last one we get unwanted artifacts, colored lines, on the images. I have tried to force it to use binary for the upload but we still get the same issue. Also tried to run the TYPE A command before upload but that didnt work either.

Method looks like this: 
        public void UploadFile(string remotePath, byte[] data)
        {
            _ftpClient.UploadDataType = FtpDataType.Binary;
            _ftpClient.Upload(data, remotePath, FtpExists.Overwrite, true);
        }

Not sure how to fix this or why this issue occurs in the first place.

KR 
Mikael

**Comment by robinrodricks** [comment]
Can you give us the logs? Check the FAQ on how to do that..

**Comment by robinrodricks** [comment]
When you respond I will reopen this.
