### ISSUE TITLE
Why FluentFTP is slower than other tools such as FlashFXP or FileZilla

### ISSUE THREAD

**Issue by rainmanec** [robinrodricks/FluentFTP#332]
I use FluentFTP to upload twenty smal files, used 15 senconds，then I use FlashFXP or FileZilla just used 2 senconds, I watch the monitor, the time between two commands is more longer. How to improve the speed. Thanks!

`DirectoryInfo dir = new DirectoryInfo(@"C:\imgs\");`
`foreach (FileInfo f in dir.GetFiles())`
`{`
`	client.UploadFile(f.FullName, "/20180906/" + f.Name);`
`}`

**Comment by robinrodricks** [comment]
No real ways to improve the speed. It is what it is. Sorry.
