### ISSUE TITLE
Text files downloaded from OpenVMS do not have correct EOL.

### ISSUE THREAD

**Issue by sapr9x3** [robinrodricks/FluentFTP#339]
**FTP OS:** OpenVMS 8.4

**FTP Server:**  OpenVMS

**Computer OS:** Windows Server 2008 R2

I need to download source files via FTP frop an OpenVMS host.  There is a problem when I try with FluentFTP. Text files succesfully downloaded to my Windows host, but they don't have any END OF LINE symbols. The reason, I think, that on OpenVMS files really don't have EOLs. However, some ftp utilities append EOL automatically in such cases. How can I resolve this problem with FluentFTP? My code:
```
var ftpclient = new FtpClient(Host, Credential);
ftpclient.Connect();
var tmpPath = Path.GetTempFileName();
ftpclient.SetWorkingDirectory(ExtractRemoteDir(filepath));
ftpclient.DownloadDataType = FtpDataType.ASCII;
ftpclient.DownloadFile(tmpPath, ExtractFileName(filepath));           
return File.ReadAllText(tmpPath, encoding);
```

**Logs :**

```

# Connect()
Status:   Connecting to ***:21
Response: 220 mock FTP Server (Version 5.7) Ready.
Command:  USER ***
Response: 331 Username *** requires a Password
Command:  PASS ***
Response: 230 User logged in.
Command:  FEAT
Response: 211 END.
Response: 211-Extensions supported.
Response: AUTH TLS.
Response: PBSZ.
Response: PROT.
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 200 VMS OpenVMS V8.4 on node mock.
Status:   Auto-detected VMS listing parser

# SetWorkingDirectory("sys$login")
Command:  CWD sys$login
Response: 250 New default directory is SYS$SYSDEVICE:[USERS.***]
Response: 250-CWD command successful.

# DownloadFile("C:\Users\Администратор\AppData\Local\Temp\1\tmpF806.tmp", "test1.pas", True, None)

# OpenRead("test1.pas", ASCII, 0)

# OpenPassiveDataStream(AutoPassive, "RETR test1.pas", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||53763|)
Status:   Connecting to ***:53763
Command:  RETR test1.pas
Response: 150 Opening data connection for SYS$SYSDEVICE:[USERS.***]TEST1.PAS;13 (172.27.0.23,50854) (360 bytes)
Status:   Disposing FtpSocketStream...
Response: 226 Transfer complete.

```

**Comment by robinrodricks** [comment]
Have you tried with FileZilla? What does it do in this case?

Also, in what cases should EOL be appended? Modifying downloaded files sounds risky but if there is a clear spec we could implement it.

**Comment by sapr9x3** [comment]
I've tried with FileZilla. EOLs are good in auto mode and in ASCII mode. EOLs are lost in binary mode.

So, I think that issue with ASCII setting in FluentFTP.

**Comment by robinrodricks** [comment]
We added support to detect the type of server. Can you check if ServerType or ServerOS has anything we can use to detect if the server is VMS?

**Comment by sapr9x3** [comment]
Thank you for attention. I've updated to 23.0.0 and issue fixed : file have correct EOLs !

ServerOS : VMS
ServerType : OpenVMS


# Connect()
Status:   Connecting to ***:21
Response: 220 mock FTP Server (Version 5.7) Ready.
Command:  USER ***
Response: 331 Username buran requires a Password
Command:  PASS ***
Response: 230 User logged in.
Command:  FEAT
Response: 211 END.
Response: 211-Extensions supported.
Response: AUTH TLS.
Response: PBSZ.
Response: PROT.
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 200 VMS OpenVMS V8.4 on node mock.
Status:   Detected FTP server: OpenVMS
Status:   Auto-detected VMS listing parser

# SetWorkingDirectory("sys$login")
Command:  CWD sys$login
Response: 250 New default directory is SYS$SYSDEVICE:[USERS.***]
Response: 250-CWD command successful.

# DownloadFile("C:\Users\***\AppData\Local\Temp\tmp1C9E.tmp", "test1.pas", Ove
rwrite, None)

# OpenRead("test1.pas", ASCII, 0)
Command:  TYPE A
Response: 200 TYPE set to ASCII.

# OpenPassiveDataStream(AutoPassive, "RETR test1.pas", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||50757|)
Status:   Connecting to ***:50757
Command:  RETR test1.pas
Response: 150 Opening data connection for SYS$SYSDEVICE:[USERS.BURAN]TEST1.PAS;1
4 (192.168.160.102,54193) (392 bytes)
Status:   Disposing FtpSocketStream...
Response: 226 Transfer complete.
