### ISSUE TITLE
ECDSA Cipher Support

### ISSUE THREAD

**Issue by DLX23** [robinrodricks/FluentFTP#340]
it seems that ECDHE-ECDSA-AES256-SHA-256 Cipher is not supported.

Log:
# Connect()
Status:   Connecting to xxxx:xxx
Response: 220 FTPServer
Command:  AUTH TLS
Response: 234 AUTH TLS successful
Status:   Disposing FtpSocketStream...
Error:    FTPS Authentication Failed
Ausnahme ausgelöst: "System.Security.Authentication.AuthenticationException" in FluentFTP.dll

**Comment by robinrodricks** [comment]
We are not implemented SSL ourselves. We are using the .NET SslStream. Whatever it supports we support. Sorry!
