### ISSUE TITLE
client.Connect requirements

### ISSUE THREAD

**Issue by timdoke** [robinrodricks/FluentFTP#343]
**FTP OS:** Unix

**Computer OS:** Windows with .NET 4.5 and version 19.2.2.0 of the NuGet package

I have a question about how client.Connect works.  I am getting a socketException a lot when trying to do client.Connect (4 out of 5 times).  However, the code below seems to still work without using Connect.  I'm wondering when client.Connect is required, or if every function automatically connects (or connects in a different way..)

This is the client code:

            string rootUrl;
            using (FluentFTP.FtpClient client = GetClient(out rootUrl))
            {
                var files = client.GetNameListing(rootUrl);

                return files.Where(f => f.EndsWith(".zip")).ToList();

            }

        private FluentFTP.FtpClient GetClient(out string localPath)
        {
            var ftpUri = new Uri(_ftpServerName);
            
            var creds = new NetworkCredential(_ftpUsername, _ftpPassword);
            FluentFTP.FtpClient client = new FluentFTP.FtpClient(ftpUri.DnsSafeHost, creds);
            client.ConnectTimeout = 120000;
            client.SocketKeepAlive = true;
            client.UploadDataType = FtpDataType.Binary;
            client.RetryAttempts = 5;

            //no need to connect.. it connects automatically when doing stuff
            //Connect(client);
            
            localPath = ftpUri.LocalPath;

            return client;
        }

And the above works without calling Connect.  

Thanks!

**Comment by timdoke** [comment]
Here are some of the logs..

# Connect()
Status:   Connecting to ***:21

# GetNameListing("/QA2/")
Status:   Disposing FtpSocketStream...

# Connect()
Status:   Connecting to ***:21
Response: 220 EFT Server Enterprise 7.4.5.6
Command:  USER ***
Response: 331 Password required for ***.
Command:  PASS ***
Response: 230 Login OK. Proceed.
Command:  FEAT
Response: 211 END
Response: 211-Features supported:
Response: COMB target;source_list
Response: REST STREAM
Response: SIZE
Response: MDTM
Response: MFMT
Response: XCRC filename;start;end
Response: SSCN
Response: MLST Size*;Modify*;Create;Type*;Unique;Perm*;Lang;Media-Type;CharSet;
Response: MODE Z
Response: XNOP
Response: UTF8
Response: UTF-8
Response: LANG EN*
Response: CLNT
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 200 Entering UTF-8 mode.
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "NLST /QA2", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||7675|)
Status:   Connecting to ***:7675
Command:  NLST /QA2
Response: 150 Opening ASCII mode data connection for file list.

# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Response: 226 Transfer complete. 41327 bytes transferred. 41327 bps.
Status:   Disposing FtpSocketStream...

**Comment by robinrodricks** [comment]
Have you extended the class? That's unusual...

**Comment by timdoke** [comment]
I did not extend the FtpClient class.  Yes, it is odd, thus my question:)

**Comment by timdoke** [comment]
It's odd because it didn't seem like I actually had to connect to do stuff..

**Comment by robinrodricks** [comment]
Can you please try with the latest version? Lots of fixes across the board...

**Comment by robinrodricks** [comment]
When you respond I will reopen this.

**Comment by timdoke** [comment]
Since I posted this bug, I’ve moved to a different team at my job. And, the previous team has moved away from that ftp architecture to something different. I hope this was fixed with the previous mega fixes. I can’t comment on if it was fixed. Thanks @robinrodricks
