### ISSUE TITLE
Download file does not cause an exception when the connection is broken

### ISSUE THREAD

**Issue by other-2025** [robinrodricks/FluentFTP#344]
Example:

            FluentFTP.FtpClient c = new FluentFTP.FtpClient();
            c.Host = "ftp.example.com";
            c.Connect();

            try
            {
                c.DownloadFile("C:/bla.txt", "/bla.txt");
                //File download begins.
                //Suddenly the internet connection disappears.
                //There is no reaction.
            }
            catch (Exception)
            {

            }

**Comment by robinrodricks** [comment]
Oh god. We have not designed this for sudden failures of internet!

Maybe if you can propose a way to fix this we can take it ahead!
