### ISSUE TITLE
How to copy files

### ISSUE THREAD

**Issue by izanhzh** [robinrodricks/FluentFTP#345]
I did not find a way to copy the file, I want to copy a file to another remotePath
like this: ftpClient.Copy(sourceRemotePath,targetRemotePath);

**Comment by cluetjen** [comment]
Afaik there's no copy command available in FTP standard. You'll have to download and upload again. See also https://stackoverflow.com/questions/3808799/ftp-copy-a-file-to-another-place-in-same-ftp
