### ISSUE TITLE
Problem when connect using FTPS

### ISSUE THREAD

**Issue by clsaad** [robinrodricks/FluentFTP#346]
**FTP OS:** UNIX

**FTP Server:** Synchrony Gateway FTP server

**Computer OS:** WINDOWS 8.1

Hello, I'm newbie using FluentFTP (I loved it!) and I found a problem when make a connection using FTPS with client certified. Bellow my code:

    Sub TestaFTP_FluentFTP()

        FtpTrace.LogFunctions = True
        FtpTrace.LogIP = True
        FtpTrace.EnableTracing = True
        FtpTrace.AddListener(New TextWriterTraceListener("C:\temp\log_file.txt"))

        Dim oCliente As New FtpClient
        oCliente.Host = "[servername]"
        oCliente.Port = "52447"
        oCliente.ClientCertificates.Add(New X509Certificate2("C:\temp\mycert.p12", "[PASSWORD]"))
        oCliente.EncryptionMode = FtpEncryptionMode.Explicit
        oCliente.SslProtocols = SslProtocols.Tls & SslProtocols.Ssl2 & SslProtocols.Ssl3
        oCliente.DataConnectionType = FtpDataConnectionType.PASV
        oCliente.DataConnectionEncryption = True
        oCliente.PlainTextEncryption = True
        oCliente.Credentials = New NetworkCredential("anonymous", "anonymous")
        AddHandler oCliente.ValidateCertificate, New FtpSslValidation(AddressOf onValidateCertified)

        oCliente.Connect() ' the error occurrs in this line!
        Console.WriteLine("Conectado...<br/>")

        For Each oArquivosRetorno As FtpListItem In oCliente.GetListing("/retorno")
            If (oArquivosRetorno.Type = FtpFileSystemObjectType.File) Then
                Console.WriteLine(String.Format("<br/>Arquivo: {0} - Tamanho: {1} - Data: {2}", oArquivosRetorno.Name, oArquivosRetorno.Size, oArquivosRetorno.Created))
            End If
        Next

        oCliente.Disconnect()
        Console.WriteLine("Desconectado...<br/>")

    End Sub

    Sub onValidateCertified(control As FtpClient, e As FtpSslValidationEventArgs)
        ' accept any server cert 
        e.Accept = True
    End Sub

When I try to make the connection this error occurs:

Exceção Não Tratada: System.Security.Authentication.AuthenticationException: Falha a uma chamada a SSPI, consulte a exceção interna. ---> System.ComponentModel.
Win32Exception: Mensagem recebida inesperada ou formatada incorretamente
   --- Fim do rastreamento de pilha de exceções internas ---
   em System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   em System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   em System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   em System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   em System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   em System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   em System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   em System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   em System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   em System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   em System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   em System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   em System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   em FluentFTP.FtpSocketStream.ActivateEncryption(String targethost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
   em FluentFTP.FtpClient.Connect()

NOTES:
(1) To validate our connection I tried using WinSCP and work's fine;
(2) Looking in the forum I see any information SSL problem in .NET 4.5. I make a test with .NET 2.0 (console application) and .NET 4.7 (console and web application) and the same result/error;
(3) I tried to downgrade from 19.2.2 version to 19.1.4 and the same error;

Best Regards,

**Logs :**

# Connect()
Status:   Connecting to [SERVER]:52447
Response: 220 Welcome to Synchrony Gateway FTP server
Command:  AUTH TLS
Response: 234 AUTH command OK, waiting handshake
Status:   Disposing FtpSocketStream...
Error:    FTPS Authentication Failed

# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...

```
<paste logs here but DO NOT delete the lines above and below this line>
```

**Comment by clsaad** [comment]
I found the problem. The FluentFTP don't support TLS 1.0. It's possible to implement or have an workaround? The server (it's a public fundation) can't be updated.

**Comment by robinrodricks** [comment]
Interesting.. We are using .NET's SslStream to support TLS/SSL. Maybe check if that supports TLS 1.0?

**Comment by clsaad** [comment]
Hello,
The server only supports TLS 1.0.

Em qui, 17 de jan de 2019 às 03:07, Robinicks <notifications@github.com>
escreveu:

**Comment by robinrodricks** [comment]
I understood that, but I'm saying that our support for SSL comes from
SslStream so you should check that..

**Comment by robinrodricks** [comment]
We cannot support what SslStream doesn't support. If you have a solution/fix we'll reopen this thread.
