### ISSUE TITLE
verify after stream upload

### ISSUE THREAD

**Issue by JanLorenz77** [robinrodricks/FluentFTP#348]
Hi,

with UploadFile(...) I can verify with the FtpVerify-option, if the file was correct transfered. What's the best way to verify the upload with a stream? The Upload(...) has no FtpVerify-param.

regards Jan

**Comment by robinrodricks** [comment]
Did you read the [docs](https://github.com/robinrodricks/FluentFTP#file-transfer)?

> **UploadFile()** - Uploads a file from the local file system to the server. Use FtpExists.Append to append to a file. Returns true if succeeded, false if failed or file does not exist. Exceptions are thrown for critical errors. Supports very large files since it uploads data in chunks. **Optionally verifies the hash of a file & retries transfer if hash mismatches.**
