### ISSUE TITLE
GetNameList with unusual directory listing fails

### ISSUE THREAD

**Issue by hpbAndrewBender** [robinrodricks/FluentFTP#351]
**FTP OS:**  UNIX/LINIX

**FTP Server:** Apache FTP Server
**Computer OS:** Windows

when sending a path without a preceding slash, one seems to automatically added
(e.g. I was the path "mblist" but the GetFiles and GetNameList both send "/mblist")

I need the command to be "NLST mblist" as the FTP server is actually presenting a mailbox listing and not a normal directory structure.

Wireshark log of the request:
,"*.*.*.131","*.*.*.230","FTP","68","Request: NLST /mblist"

**Logs :**

**Comment by robinrodricks** [comment]
Try executing it with `client.Execute("NLST mblist")`
