### ISSUE TITLE
Upload fails without Exception

### ISSUE THREAD

**Issue by stengnath** [robinrodricks/FluentFTP#352]
**FTP OS:** Unix / Windows

**FTP Server:** UNKNOWN

**Computer OS:** Ubuntu 16.04 LTS and WINDOWS 10 Entperprise

When uploading a file to an FTP (specs unknown because external provider) the upload will success although it's not. FileZilla for example throws on the same action an error because the destination FTP has some issues. The critical thing is that the log is showing the same error Filezilla is showing (error 550). Read FluentFTP TraceLog below.
Error 550 is beeing raised by Destination FTP but there is no Exception that is beeing thrown.
So obviously there is no error that can be handled in Code.
There is no possibility to verify the File by check for existnce, becauce the Destination FTP always removes the uploaded file when successfully uploaded because the file has already been processed.
Main programm is running under Mono (Ubuntu 16.04 LTS), but the 
problem remains constant when running the exactly same code under Windows.
Tried to debug it but just when beeing at the line where something is going wrong, the FTP Server has been fixed by the Provider and everything worked fine.
So there was no way to debug it again.

**Logs :**

**Working:**
FluentFTP Verbose: 0 : # OpenPassiveDataStream(AutoPassive, "STOR /test/test.txt", 0)
FluentFTP Information: 0 : Command:  EPSV
FluentFTP Information: 0 : Response: 229 Entering Passive Mode (|||38646|)
FluentFTP Information: 0 : Status:   Connecting to XXX.XXX.XXX.XXX:38646
FluentFTP Information: 0 : Command:  STOR /test/test.txt
FluentFTP Information: 0 : Response: 150 File status okay; about to open data connection.
**FluentFTP Verbose: 0 : Status:   Disposing FtpSocketStream...
FluentFTP Information: 0 : Response: 226 Transfer complete.**
FluentFTP Information: 0 : Command:  QUIT
FluentFTP Information: 0 : Response: 221 Goodbye.
FluentFTP Verbose: 0 : Status:   Disposing FtpSocketStream...

**not Working:**
FluentFTP Verbose: 0 : # OpenPassiveDataStream(AutoPassive, "STOR /test/test.txt", 0)
FluentFTP Information: 0 : Command:  EPSV
FluentFTP Information: 0 : Response: 229 Entering Passive Mode (|||28644|)
FluentFTP Information: 0 : Status:   Connecting to XXX.XXX.XXX.XXX:28644
FluentFTP Information: 0 : Command:  STOR /test/test.txt
FluentFTP Information: 0 : Response: 150 File status okay; about to open data connection.
**FluentFTP Verbose: 0 : Status:   Disposing FtpSocketStream...
FluentFTP Information: 0 : Response: 550 Requested action not taken.**

**Comment by stengnath** [comment]
I think I could figure out the Problem.
UploadFileInternal()
{
...
	// disconnect FTP stream before exiting
	upStream.Dispose();

	// FIX : if this is not added, there appears to be "stale data" on the socket
	// listen for a success/failure reply
	if (!EnableThreadSafeDataConnections) {
		FtpReply status = GetReply();
	}
	return true;
}

Although everything worked fine till here, the FTP Server sends the reply, that the Transaction did not succeed. If I'm right, there shouldn't be returned "true". In this case the reply should be checked wether the reply-Code is 226 (Transfer Complete) or not.
If not (I dont really know all Codes that an FTP can send) , at least for 550 there should be returned "false" instead of "true"

**Comment by stengnath** [comment]
I opened a pull request. Maybe this is the/one solution.

**Comment by stengnath** [comment]
Hi robindodricks,
is there a plan to create a new version for nuget?
I already replaced the library on our System an everything works fine.

The only thing I changed is to not accept every 5** Error instead of just not accepting the 550 error.
So instead of 
`if (status.Code != null && status.Code == "550")`
I use
`if (status.Code != null && status.Code != "" && status.Code.StartsWith("5"))`
as condition.

Acording to 
[https://en.wikipedia.org/wiki/List_of_FTP_server_return_codes]
every 5** error should mean that the action did not take place.

Do you mean this is worth a new commit or do you think there could be raised some unplanned problems?

**Comment by robinrodricks** [comment]
Yes, I will be doing so soon..

**Comment by robinrodricks** [comment]
Released in [FluentFTP 19.2.3](https://www.nuget.org/packages/FluentFTP/19.2.3).  Sorry for the delayed release!

Please check if everything works fine.
