### ISSUE TITLE
Huge performance improvement for uploads

### ISSUE THREAD

**Issue by Lukazoid** [robinrodricks/FluentFTP#354]
**FTP OS:** Unix

**FTP Server:** Various

**Computer OS:** Windows Server 2008 R2

It has been observed how much slower FluentFTP uploads are compared to that of other FTP applications (https://github.com/robinrodricks/FluentFTP/issues/332), in our application, concurrent uploads were taking an hour with FluentFTP and about 6 minutes with FileZilla.

By looking at the code I have determined a major source of FluentFTP's slowdown, there is no buffering between the SSL stream and the Network Stream, this means we end up with a lot of small writes from the SSL stream to the Network Stream. Writing to a network stream is incredibly slow as this requires marshalling, by using a BufferedStream we can vastly reduce the amount of marshalling involved.

Through the use of reflection I was able to inject a BufferedStream into the correct locations, after this change our uploads now actually upload faster than FileZilla, taking 5 minutes instead of the previous hour.

Here is the code I used to achieve this:

```
private static BufferedStream InjectBufferedStream(Stream ftpDataStream, int bufferSize = 81920)
{
    Contract.Requires(ftpDataStream != null);
    Contract.Ensures(Contract.Result<BufferedStream>() != null);

    // A gross method to inject a BufferedStream between the SslStream and the NetworkStream
    // remove this if we ever update to a version of FluentFtp with this built in

    const BindingFlags privateField = BindingFlags.NonPublic | BindingFlags.Instance;

    var sslStreamField = typeof(FtpSocketStream).GetField("m_sslStream", privateField);
    var sslStateField = typeof(SslStream).GetField("_SslState", privateField);
    var sslStateInnerStreamField = sslStateField.FieldType.GetField("_InnerStream", privateField);
    var authenticatedInnerStreamField = typeof(AuthenticatedStream).GetField("_InnerStream", privateField);

    var sslStream = (SslStream)sslStreamField.GetValue(ftpDataStream);
    var sslState = sslStateField.GetValue(sslStream);

    var networkStream = (NetworkStream)authenticatedInnerStreamField.GetValue(sslStream);

    var bufferedStream = new BufferedStream(networkStream, bufferSize);
    authenticatedInnerStreamField.SetValue(sslStream, bufferedStream);
    sslStateInnerStreamField.SetValue(sslState, bufferedStream);

    return bufferedStream;
}
```

With this reflection version, the `BufferedStream` must NOT be disposed and must have `Flush` or `FlushAsync` called before the ftp data stream is disposed. This will not be required in the final merge request version.

For example:

```
using (var remoteStream = await ftpClient.OpenWriteAsync(remoteFilePath, FtpDataType.Binary).ConfigureAwait(false))
{
    var bufferedStream = InjectBufferedStream(remoteStream);

    await fileContents.CopyToAsync(remoteStream, 81920, CancellationToken.None).ConfigureAwait(false);

    await bufferedStream.FlushAsync(CancellationToken.None).ConfigureAwait(false);
}
```

I will follow this issue with a merge request to actually make this change.

**Logs :**

```
N/A
```

**Comment by Lukazoid** [comment]
I am in the process of doing this during working hours so intend to make the PR on monday.

**Comment by smetis** [comment]
is there anything need to be done to gain this performance? I use the example code on github page "client.UploadFile" but it is 20x slower than .Net built-in FtpWebRequest.

**Comment by robinrodricks** [comment]
@Lukazoid I merged your PR and its included in the latest release. Could you please check if everything is working as intended?

**Comment by smetis** [comment]
> @Lukazoid I merged your PR and its included in the latest release. Could you please check if everything is working as intended?

updates: I modify my test code to have only one instance of FtpClient that does all the files uploading (around 300 files that total in 1GB).  This speeds things up alot but still, it is around 4x-5x slower than ftpwebrequest.  Also, ftpclient is not thread safe i suppose, when i upload files using same instance of ftpclient in parallel (my own task scheduler), it crashes.
