### ISSUE TITLE
SslProtocols.None not working in .NET 4.7.2

### ISSUE THREAD

**Issue by gurukara7** [robinrodricks/FluentFTP#356]
**FTP OS:**  Windows

**Computer OS:** Windows

When trying to connect to a FTPS Server we are forced to provide the list of protocols that are accepted. This should not be the case as per .NET 4.7.2. 
In .NET 4.7.2 the choice of protocol was delegated OS and if we just select Default the OS will pick the highest and most relevant one based on the OS setting.

**WRONG**
`ftpClient.SslProtocols = Security.Authentication.SslProtocols.Tls Or Security.Authentication.SslProtocols.Tls11 Or Security.Authentication.SslProtocols.Tls12`

**Right**
`ftpClient.SslProtocols = Security.Authentication.SslProtocols.None`

Reference link [SslProtocols Enum](https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?view=netframework-4.7.2)

Can this be addressed soon please.
Thanks

**Comment by robinrodricks** [comment]
Interesting find. I'll only have to check if the fix you gave will cause any side effects.

**Comment by gurukara7** [comment]
Great to know that you are looking at it. Really appreciate that.

Also the Enums are bit messed up from the Microsoft end. They are saying the `Security.Authentication.SslProtocols.Default` will let the OS chose. 

Sorry about that have edited the original bug description.

[SslProtocols Enum](https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?view=netframework-4.7.2)

**Comment by robinrodricks** [comment]
Related to #176. 

Which solution should be done,  `conn.SslProtocols = SslProtocols.Default | SslProtocols.Tls11 | SslProtocols.Tls12`  or `None`?

**Comment by robinrodricks** [comment]
Can you please reply?

**Comment by gurukara7** [comment]
> 
> 
> Can you please reply?

It should be `Security.Authentication.SslProtocols.None`

**Comment by modmynitro** [comment]
I would appreciate it if the default, as recommended by microsoft, is changed to `Security.Authentication.SslProtocols.None`.
