### ISSUE TITLE
DirectoryExists returns false for an existing directory on MSLT server

### ISSUE THREAD

**Issue by Wojtekxor2** [robinrodricks/FluentFTP#357]
The line for a directory returns: 
250-modify=20080830164659;perm=flcdmpe;type=dir;unique=802U9C04AC;UNIX.group=1001;UNIX.mode=0755;UNIX.owner=1003; /lib"

This line is not parsed and type of the object is set to unknown.

FTP OS: ?
FTP Server: 220 ProFTPD 1.3.4a Server (DDPBYD)

**Comment by robinrodricks** [comment]
Sorry for the late reply. Can you get us the FluentFTP logs please? In particular I'm looking for the message that specifies the MSLT format.

**Comment by FanDjango** [comment]
I have run this line through the parser tests and it works fine. With no further information from the TO and no complete log, no FluentFTP version information and no reaction from the TO: closed.
