### ISSUE TITLE
IsConnected not being refreshed and timeouts not handled

### ISSUE THREAD

**Issue by Foxlider** [robinrodricks/FluentFTP#360]
**FTP OS:** Windows

**FTP Server:** FileZilla

**Computer OS:** Windows - Android

I am using the FluentFtp on a Xamarin project for Android. 

The application checks client.IsConnected everytime before doing a transfer to reconnect if needed. Although, the variable don't always get refreshed. So when the server disconnects the client for inactivity for two minutes and the application tries to do a file upload, it assumes it is connected (but is not) and tries to Upload the file and get stuck in the client.Upload. For some reason it never gets out, no timeout is handled.  
Either the client fails to refresh the IsConnected variable and/or the timeout handler is not working properly on the commands.

**Logs :**

What I got :
```
01-24 19:23:30.714 I/mono-stdout( 1589): Status:   Testing connectivity using Socket.Poll()...
01-24 19:23:36.910 I/mono-stdout( 1589): Status:   Testing connectivity using Socket.Poll()...
01-24 19:23:37.421 I/mono-stdout( 1589): # Upload("EnCours/CheckTemp000000004196.txt", Overwrite, False)
01-24 19:23:37.421 I/mono-stdout( 1589): # FileExists("EnCours/CheckTemp000000004196.txt")
01-24 19:23:37.421 I/mono-stdout( 1589): # GetWorkingDirectory()
01-24 19:23:37.421 I/mono-stdout( 1589): Command:  PWD
01-24 19:25:17.088 I/mono-stdout( 1589): ClientFtpRepository - GetFileTimeStamp : Error while uploading the file to the server. See InnerException for more info.
```

What I am supposed to get :  
```
01-24 19:37:20.604 I/mono-stdout( 2297): Status:   Testing connectivity using Socket.Poll()...
01-24 19:37:22.896 I/mono-stdout( 2297): Status:   Testing connectivity using Socket.Poll()...
01-24 19:37:23.396 I/mono-stdout( 2297): # Upload("EnCours/CheckTemp000000004196.txt", Overwrite, False)
01-24 19:37:23.396 I/mono-stdout( 2297): # FileExists("EnCours/CheckTemp000000004196.txt")
01-24 19:37:23.396 I/mono-stdout( 2297): # GetWorkingDirectory()
01-24 19:37:23.396 I/mono-stdout( 2297): Command:  PWD
01-24 19:37:23.517 I/mono-stdout( 2297): Response: 257 "/" is current directory.
01-24 19:37:23.517 I/mono-stdout( 2297): Command:  SIZE /EnCours/CheckTemp000000004196.txt
01-24 19:37:23.557 I/mono-stdout( 2297): Response: 550 File not found
01-24 19:37:23.557 I/mono-stdout( 2297): # OpenWrite("EnCours/CheckTemp000000004196.txt", Binary)
01-24 19:37:23.557 I/mono-stdout( 2297): # OpenPassiveDataStream(EPSV, "STOR EnCours/CheckTemp000000004196.txt", 0)
01-24 19:37:23.557 I/mono-stdout( 2297): Command:  EPSV
01-24 19:37:23.647 I/mono-stdout( 2297): Response: 229 Entering Extended Passive Mode (|||2162|)
01-24 19:37:23.657 I/mono-stdout( 2297): Command:  STOR EnCours/CheckTemp000000004196.txt
01-24 19:37:23.767 I/mono-stdout( 2297): Response: 150 Opening data channel for file upload to server of "/EnCours/CheckTemp000000004196.txt"
01-24 19:37:23.767 I/mono-stdout( 2297): Status:   Disposing FtpSocketStream...
01-24 19:37:23.867 I/mono-stdout( 2297): Response: 226 Successfully transferred "/EnCours/CheckTemp000000004196.txt"
```

**Comment by mennowo** [comment]
Hello,
I might have a related issue, where this line of code:
`Client.DownloadFile(localPath, remotePath, verifyOptions: FtpVerify.None);`
sometimes hangs forever, causing my application to not continue, cause the downloading job will never finish, so a new one cannot start. Would be great to hear if there is a resolution for this.
Would it help to switch to a more low-level approach and work with streams directly?
Greets, Menno

**Comment by robinrodricks** [comment]
Timeout handling: https://github.com/robinrodricks/FluentFTP/issues/262

**Comment by robinrodricks** [comment]
Fixed by WolfSpiritM in release 23. Grab the nuget package here: [FluentFTP 23](https://www.nuget.org/packages/FluentFTP/23.0.0)

Please check if this resolves your issues?

**Comment by robinrodricks** [comment]
Please reply if you still have this issue.

**Comment by mennowo** [comment]
Sorry for not replying sooner. I have not noticed any problems the past weeks, using the version from nuget. So, seems to have been fixed! Thanks!
