### ISSUE TITLE
Discard file on download if target exists (CompareFile)

### ISSUE THREAD

**Issue by lelelic** [robinrodricks/FluentFTP#361]
Hi,
on my software I have a list of files to download. How I can check if files already exists on target folder before download?
The name of file could the same but the file on ftp can be newer. I think I should compare the hash of remote file with the hash of local file and if mismatches then I download it.
Exist some option on library that does this?
Or what method I can use to do this?

**Comment by robinrodricks** [comment]
Interesting idea. We don't have a CompareFile method yet. But you can compare its hashes first and then call DownloadFile if needed.

**Comment by robinrodricks** [comment]
New `CompareFile` methods released in **32.1.0**!

See: https://github.com/robinrodricks/FluentFTP/wiki/File-Hashing#api

Get: https://www.nuget.org/packages/FluentFTP/32.1.0
