### ISSUE TITLE
Add Overload to Upload File / Down Load file to return FTPReply

### ISSUE THREAD

**Issue by brucemcmillan** [robinrodricks/FluentFTP#367]
Question ?

Would it be possible to gain access to the response in the client or on some of the methods?

For example in the situation I am working on the response to upload passes back a GUID reference that is the succesfully uploaded file ref.

In this scenario the uploaded files are instantly absorbed / moved by the server so there are never any files in the folder to check..

Response: 226 transfer complete (89754c3f-6397-fc34-046b-366d1878c009)

**Comment by robinrodricks** [comment]
It's possible. Interesting idea.

**Comment by robinrodricks** [comment]
Does it work for you in 20.0.0?

**Comment by brucemcmillan** [comment]
Hi,

Been working with it today and seems to be doing the right thing :-)  Every response is bringing back a last reply which we can look at to get the data we need,  Very useful !!

Thanks..
