### ISSUE TITLE
Connect with no username in network credentials raises exception

### ISSUE THREAD

**Issue by brucemcmillan** [robinrodricks/FluentFTP#371]
**FTP OS:**Windows

**FTP Server:** IIS  - In anonymous mode

**Computer OS:** ?
Windows 10 client

When client is created using the network credential option and the username is blank clinet raises an exception with "incorrect number of parameters"

NetworkCredential networkCredential = new NetworkCredential(UserName, Password);

client = new FtpClient(HostName, PortNo, networkCredential);

**Logs :**

```
<paste logs here but DO NOT delete the lines above and below this line>
```

**Comment by robinrodricks** [comment]
Use "anonymous" not blank

**Comment by KoalaBear84** [comment]
Sometimes the servers also not accept a blank password (if I'm correct?), and I use "password" as the password. But maybe @robinrodricks knows more about it?

**Comment by brucemcmillan** [comment]
was wondering if the connect() should return a bool or something ??? 

We were talking about auto detect of connection type too and this might be linked. ?

I can appreciate if you are using the DLL in a solution that you might check for this in the UI etc, but some i failed response that is not using the IsConnected might be helpful ?

just a thought..

**Comment by robinrodricks** [comment]
Just use "anonymous" and not a blank username or password.
