### ISSUE TITLE
Download method requires restartPosition property

### ISSUE THREAD

**Issue by Dylandoesprogramming** [robinrodricks/FluentFTP#381]
**Computer OS:**  Windows 10

An update to FluentFTP was made which changed the minimum parameters required for the Download() method on the FtpClient class.

Before this change you were able to download a file from a given FtpClient with the following syntax:
client.Download(out var byteArray, filePath);

After this change you now require a long property of"restartPosition". 
I have not been able to find any documentation on why this change was made, what this property does, or what it is expecting.

I found a summary entry for the property stating the property is looking for: "Local File Size of existing file which you want to resume". This confused me further as we are attempting to download a file, not resume an existing download.

This change has broken all calls of the Download() function we currently utilized and has required us to roll our version back to correct.

Are you able to explain what this restartPosition property is for, and how to utilize it properly?

**Comment by robinrodricks** [comment]
It's not supposed to be mandatory. Let me investigate.

**Comment by robinrodricks** [comment]
Fixed in [FluentFTP 23.1.0](https://www.nuget.org/packages/FluentFTP/23.1.0).
