### ISSUE TITLE
FluentFTP.FtpSocketStream.Dispose: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mentadev** [robinrodricks/FluentFTP#382]
**FTP OS: Windows
**Computer OS: Windows 10

No much details, random "FluentFTP.FtpSocketStream.Dispose: Object reference not set to an instance of an object" error.
I'm downloading 100.000 images from a FTP. The download is in sequence, it means one at the time and the FluentFTP rises random errors while downloading the images.
The code is quite simple:

```
using (var FTPImgsClient = new FtpClient(ImgToDownload.FTPServer, ImgToDownload.FTPPort, new System.Net.NetworkCredential(ImgToDownload.FTPUser, ImgToDownload.FTPPassword)))
{
          await FTPImgsClient.ConnectAsync(appLifetime.ApplicationStopping);
          string FullRemotePath = "my remote path";
          LocalFilePath = "my local path";
          if (!Directory.Exists(FullLocalFullPath))
                    Directory.CreateDirectory(FullLocalFullPath);

          await FTPImgsClient.DownloadFileAsync(
                    localPath: FullLocalFullPath,
                    remotePath: FullRemotePath,
                    existsMode: FtpLocalExists.Overwrite);

          if (FTPImgsClient.IsConnected)
                    await FTPImgsClient.DisconnectAsync(appLifetime.ApplicationStopping);
}
```

![image](https://user-images.githubusercontent.com/36265439/54363993-d2d1cd80-464a-11e9-9996-6e235f71bbb6.png)

**Comment by robinrodricks** [comment]
Please try this..

https://we.tl/t-SAXE1eEfzz

**Comment by robinrodricks** [comment]
Did it fix your issues?

**Comment by robinrodricks** [comment]
I'm marking this as fixed until you reply to the contrary.

**Comment by jameskimrex** [comment]
Hi, I have the same issue above while downloading files by using multiple thread. The link is not valid any more. Can you update the link.
