### ISSUE TITLE
Unable to set up passive listening socket

### ISSUE THREAD

**Issue by qtxCoding** [robinrodricks/FluentFTP#391]
When I uploaded a file using FluentFTP, I was able to make a normal connection, but when I uploaded a fourth or fifth file, I received an exception:Unable to set up passive listening socket;
I'm at my wit's end. I'm asking for your help

**Comment by robinrodricks** [comment]
Can you post your logs? See the FAQ in the readme for how to capture logs..

**Comment by robinrodricks** [comment]
This error means that is an ACL or firewall blocking the passive ports on the client side... 

When your FTP server tries to open a port for the passive mode connection, the listener on the client end doesn't respond. Make sure the client opened the appropriate ports for passive FTP. This explanation is reinforced by the fact that when the passive connection fails, the legacy PORT command is used to attempt a connection.

**Comment by qtxCoding** [comment]
Thank you for your reply. Does this question refer to the firewall on the server side or the firewall on the client side?

**Comment by qtxCoding** [comment]
Sorry, I didn't look carefully. Thank you
