### ISSUE TITLE
Use fluentftp from c++ application

### ISSUE THREAD

**Issue by robcam73** [robinrodricks/FluentFTP#393]
I would like to call fluent ftp from a cpp app in windows using /clr. Is this possible please?

**Comment by robinrodricks** [comment]
Register the assembly information of your managed DLL in the Windows registry and to create a corresponding type library, run the following command at the Visual Studio .NET command prompt:

```
RegAsm.exe ManagedDLL.dll /tlb:ManagedDLL.tlb /codebase
```

To import the type library that RegAsm.exe generates, add the following code to the CPPClient.cpp file:

```
// Import the type library.
#import "..\ManagedDLL\bin\Debug\ManagedDLL.tlb" raw_interfaces_only
```

Change the path of the type library if the path on your computer differs from this path.
To declare the namespace to use, add the following code to the CPPClient.cpp file:

```
using namespace ManagedDLL;
```

To call the managed DLL, add the following code to the

```
_tmain function:
// Initialize COM.
HRESULT hr = CoInitialize(NULL);

// Create the interface pointer.
ICalculatorPtr pICalc(__uuidof(ManagedClass));

long lResult = 0;

// Call the Add method.
pICalc->Add(5, 10, &lResult);

wprintf(L"The result is %d", lResult);

// Uninitialize COM.
CoUninitialize();
return 0;
```

From [this link](https://support.microsoft.com/en-in/help/828736/how-to-call-a-managed-dll-from-native-visual-c-code-in-visual-studio-n).

If that does'nt work try [this ](https://www.codeproject.com/Tips/695387/Calling-Csharp-NET-methods-from-unmanaged-C-Cplusp) or [this](https://www.codeproject.com/Articles/42319/Using-NET-Classes-Modules-from-Native-C).

**Comment by robcam73** [comment]
Thanks
