### ISSUE TITLE
SetModifiedTime not work

### ISSUE THREAD

**Issue by losttem** [robinrodricks/FluentFTP#394]
**FTP OS:** REHL 6.5
**FTP Server:** Vsftpd
the "MFMT" command used by SetModifiedTime() doesn't work, logtrace:  "Response: 500 Unknown command", but "MDTM" command works well, logtrace: "Response: 213 File modification time set”

is my vsftpd not configured well?

**Comment by robinrodricks** [comment]
What, MDTM changes the time? Its supposed to get the modified time, not change it. See [this](https://github.com/robinrodricks/FluentFTP#ftp-support) table for support of MDTM. Not sure how your server is using MDTM to change the modified time.

**Comment by robinrodricks** [comment]
Closing until you indicate its still an issue.
