### ISSUE TITLE
Problems with § in password

### ISSUE THREAD

**Issue by BastianBM** [robinrodricks/FluentFTP#398]
Hello,

we have a password given from a customer with a char for paragraph --> §

When we try to connect, we get the issue: login or passwort incorrect. i test it on your ftp server with the password and i have the same error. if i delete § from passwort in our programm and on our ftp-server it works. when i test the original password with filezilla it works too.

This is a sample of the password: kjvU§hhK785f4DiM

What can i do? the customer did not change the password.

thx
Bastian

**Comment by robinrodricks** [comment]
Try one of these:

https://github.com/robinrodricks/FluentFTP#faq_utf
