### ISSUE TITLE
FTPS Connection Error : No Such Host Found

### ISSUE THREAD

**Issue by sonisp** [robinrodricks/FluentFTP#400]
****FTP OS:** Not Sure , Need to Check with Vendor
**FTP Server: Not Sure , Need to Check with Vendor
**Computer OS: Windows Server 2012 R2

<write details about your bug report / feature request here>
Hi, 

We are trying to connect to FTPs with FluentFTP API.  TELNET to the IP over port 990 is working and we are able to access the Folders from FileZilla. However when we run the below code, we are getting this error at line **client.Connect();**

The Input Parameters are coming from the Config Files, basically they follow the below format.

string_PAI_FTPs_URL = "ftps://xx.xx.x.xxx"
string _PAI_FTPs_Port = "990"
string PAI_FTPs_Login = "FtpsUser"
string _PAI_FTPs_Pwd =   "FtpsPwd"

private static FtpClient ConnectFTP()
        {
            // create an FTP client
            try
            {

                FtpClient client;
                using (client = new FtpClient(_PAI_FTPs_URL, int.Parse( _PAI_FTPs_Port), PAI_FTPs_Login, _PAI_FTPs_Pwd))
                {

                    // if you don't specify login credentials, we use the "anonymous" user account
                    //client.Credentials = new NetworkCredential(PAI_FTPs_Login, _PAI_FTPs_Pwd);

                    //client.Port = Int32.Parse(_PAI_FTPs_Port);
                    client.EncryptionMode = FtpEncryptionMode.Implicit;

                    // begin connecting to the server
                    client.Connect();

                    FtpTrace.LogFunctions = false;
                    FtpTrace.AddListener(new TextWriterTraceListener("FTP_log_file.txt")
                    {
                        Filter = new EventTypeFilter(SourceLevels.Error)
                        //Filter = new EventTypeFilter(SourceLevels.All)
                    });
                }
                return client;
            }
            catch(IOException ex1)
            {
                LogEvent("Host:" + _PAI_FTPs_URL + "::\nError to Connect FTP Client :" + ex1.Message + "Source:" + ex1.StackTrace);
                return null;
            }
            catch  (FtpException ex)
            {
               
                LogEvent("Host:" + _PAI_FTPs_URL + "::\nError to Connect FTP Client :" + ex.Message + "Source:" + ex.StackTrace);
                return null;
            }
            catch(Exception ex2)
            {
                LogEvent("Host:"+ _PAI_FTPs_URL + "::\nError to Connect FTP Client :" + ex2.Message + "Source:" + ex2.StackTrace);

                return null;
            }
            
        }

**Error Message** : No such host is known
**Stack Trace :**    at System.Net.Dns.GetAddrInfo(String name)
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at FluentFTP.FtpSocketStream.Connect(String host, Int32 port, FtpIpVersion ipVersions)
   at FluentFTP.FtpClient.Connect()
   at PAI_KSM_Customs.OGAProcessXMLBAL.ConnectFTP() in C:\Users\plx_shoaib\Documents\Visual Studio 2015\Projects\PAI KSM SP2013 Project\PAI_KSM_Customs\OGAProcessXMLBAL.cs:line 74

When I move the Trace part of the Code before the "client.Connect();" line, we get the below log. 

**Logs :**
```
# Connect()

# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
```

**Comment by robinrodricks** [comment]
Can you show logs from FluentFTP and Filezilla?

**Comment by sonisp** [comment]
Hi

FluentFTP Logs are below,
# Connect()
# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream..

FileZilla, I will send tomorow once I collect the logs from the Client Location.

Thanks

**Comment by sonisp** [comment]
Hi,

FileZila **Detailed Log** below,. I have just replaced the FTP Server IP and Login Name. Hope this helps

Status:	Connecting to XX.XX.X.XXX:990...
Status:	Connection established, initializing TLS...
Status:	Verifying certificate...
Status:	TLS connection established, waiting for welcome message...
Response:	220-Welcome to Cerberus FTP Server
Response:	220 Created by Cerberus, LLC
Command:	USER TEST_USER
Response:	331 User TEST_USER, password please
Command:	PASS *********
Response:	230 Password Ok, User logged in
Command:	CLNT FileZilla
Response:	200 Command okay
Command:	OPTS UTF8 ON
Response:	200 UTF8 support on
Command:	PBSZ 0
Response:	200 PBSZ=0
Command:	PROT P
Response:	200 PROT P OK, data channel will be secured
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/" is the current directory
Status:	Directory listing of "/" successful

Thank you.

Regards,

**Comment by robinrodricks** [comment]
Replace `"ftps://xx.xx.x.xxx"` with just `"xx.xx.x.xxx"`. If you want FTPS you'll have to enable it separately, see the FAQ.
