### ISSUE TITLE
Connection timeout on .net core

### ISSUE THREAD

**Issue by radiy** [robinrodricks/FluentFTP#401]
Hello,

I am trying to diagnose some hanging that I`m seeing internaly when my apps running on .net core
and noticed that connection opening diffirent on .net core and .net framework, see links below
.net core https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Stream/FtpSocketStream.cs#L858
ConnectAsync().Wait used
on .net framework https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Stream/FtpSocketStream.cs#L862
proper timeout is used.
Why they are different? I do not see any timeout logic on core.

**Comment by AdamMcIntosh** [comment]
Ditto..am encountering the same issue

**Comment by erik-wramner** [comment]
I think we may be hitting this one as well. I could create a pull request, but most likely the full .NET solution is the way to go for CORE as well?

**Comment by radiy** [comment]
Nope, .net standard has different async socket api. I have fixed connection hang, but found that active mode is completely broken on .net core. I am still testing it and not completely sure about active mode fixes.
You can build from my fork and give it a try https://github.com/radiy/FluentFTP/commits/master.

**Comment by robinrodricks** [comment]
Good work. Hope to see a PR soon.

**Comment by radiy** [comment]
done #406
