### ISSUE TITLE
Open VMS 550 file specification syntax error

### ISSUE THREAD

**Issue by tonyhawe** [robinrodricks/FluentFTP#402]
Trying to upload a file to a third party OpenVMS ftp server I get an error:
550 file specification syntax error

Checking the logs I see the following command:
Command:  NLST SYSDEVICE:[USERS.mylogin]/SYSDEVICE:[USERS.mylogin]
Response: 550 file specification syntax error
Status:   Disposing FtpSocketStream...

Digging through the code I find the following block:
`// FIX : #380 for OpenVMS absolute paths are "SYS$SYSDEVICE:[USERS.mylogin]"
				if (ServerType == FtpServer.OpenVMS) {
					if (path.Contains("$") && path.Contains(":[") && path.Contains("]")) {
						return path;
					}
				}`
https://github.com/robinrodricks/FluentFTP/blob/09b9ed869d12868135c50899e28f65ce17d9ddaf/FluentFTP/Client/FtpClient_Connection.cs#L1845

I don't know anything about OpenVMS but the expected path format doesn't match what I am getting. 
Expected = SYS$SYSDEVICE:[USERS.mylogin]
Encountered = SYSDEVICE:[USERS.mylogin]

This is also the PWD so when it tries to add the path to the PWD it ends up with 
SYSDEVICE:[USERS.mylogin]/SYSDEVICE:[USERS.mylogin].

I got around it by removing the $ check at the start but I don't know if that is appropriate as a general solution, would it return false positives in other situation?. As I say, I don't know anything about OpenVMS, this is just the situation I encountered.

**Comment by robinrodricks** [comment]
Good find. What does ServerType report for your OS? Can you show the first few FluentFTP logs that appear if that helps us identify your server?

**Comment by robinrodricks** [comment]
Fixed in 25.0.0.

**Comment by robinrodricks** [comment]
@tonyhawe  please check if it works with the latest version, so I can close this issue.

**Comment by robinrodricks** [comment]
If you have issues reply here and I'll reopen this issue.
