### ISSUE TITLE
[FluentFTP 24] Most functions ending in Socket-related issues

### ISSUE THREAD

**Issue by erwinwolff** [robinrodricks/FluentFTP#405]
**FTP OS:** Unix

**FTP Server:** ProFTPD 

**Computer OS:** Windows 10 

Many functions result in Socket-related issues.

**Logs :**

![image](https://user-images.githubusercontent.com/602021/58767067-b331ad80-8586-11e9-80e4-bc2e8bebbb5d.png)

![image](https://user-images.githubusercontent.com/602021/58767085-d9efe400-8586-11e9-9c85-03cbf2f3165e.png)

```
<paste logs here but DO NOT delete the lines above and below this line>
```

**Comment by erwinwolff** [comment]
I am truly at a loss on what could causing this.

**Comment by erwinwolff** [comment]
I have fixed it with removing all Async methods and replaced with their Sync equivalents.  Someone should really check that Async implementation.

**Comment by robinrodricks** [comment]
Can you check with the latest version?

Also try setting `SslBuffering` to `Off` and see if it improves?

**Comment by ruben-methodos** [comment]
No, also setting `SslBuffering` to `Off ` doesn't work.

However, in my application, the client throws a FtpCommandException with an empty message, but when I remove the async methods, it works correctly.

**Comment by FanDjango** [comment]
In the course of the V40/V41 migration, ASYNC vs. SYNC should be very much improved.
