### ISSUE TITLE
client.UploadFile exception

### ISSUE THREAD

**Issue by rdcs** [robinrodricks/FluentFTP#408]
**FTP OS:** IOS - Native using Xamarin (c#)

**FTP Server:** Pure-FTPd 

**Computer OS:**  IOS 11

If you open a file to write some data, 
     handle = ftp.OpenWrite(fileName, FtpDataType.Binary,false);
   and don't close the handle before trying to do a client.UploadFile(...)   not using the handles file, the UploadFile will throw an exception.  Closing the handle before attempting to use UploadFile, will succeed.

This is for informational purposes, so the next person who runs into this doesn't have to spend 2 hours trying to figure out why the exception.  But your library is truly excellent!
If you need any additional info I can be reached at rdcs11@gmail.com
**Logs :**

```
<paste logs here but DO NOT delete the lines above and below this line>
```

**Comment by robinrodricks** [comment]
Can you please explain more? Is this a bug in the library?
