### ISSUE TITLE
Proxy bluecoat issue when Proxy IP is like 172.x.x.x 

### ISSUE THREAD

**Issue by CMIGIT** [robinrodricks/FluentFTP#409]
After 2 days of research I just found the reason of my issue.
I have to go through a Bluecoat proxy (I'm using FtpClientUserAtHostProxyBlueCoat).
The connection was ok but then nothing worked anymore (list directory, upload, download, ...).
The problem comes from my proxy that I call by its IP: 172.x.x.x.
Indeed in the "OpenPassiveDataStream" method there are these lines

	//use host ip if server advertises a non-routeable IP
	m = Regex.Match(host, @"(^10\.)|(^172\.1[6-9]\.)|(^172\\.2[0-9]\.)|(^172\.3[0-1]\.)|(^192\.168\.)|(^127\.0\.0\.1)|(^0\.0\.0\.0)");

	if (m.Success)
	{
		host = m_host;
	}

and in my case it replaces the name of my proxy by the name of the FTP server and then, nothing works.
My suggestion is to test if you are not in a proxy connection :
```
	if (!this.IsProxy()) // Update
	{
		//use host ip if server advertises a non-routeable IP
		m = Regex.Match(host, @"(^10\.)|(^172\.1[6-9]\.)|(^172\\.2[0-9]\.)|(^172\.3[0-1]\.)|(^192\.168\.)|(^127\.0\.0\.1)|(^0\.0\.0\.0)");

		if (m.Success)
		{
			host = m_host;
		}
	}
```
There is the same thing in the "OpenPassiveDataStreamAsync" method.
Is this a valid solution, or am I an exception? 
What do you think of my update?

**Comment by robinrodricks** [comment]
Fixed in 25.0.0. Please switch to the `FtpClientBlueCoatProxy` class.

**Comment by CMIGIT** [comment]
Ok I try it monday if version is published ;-)

**Comment by robinrodricks** [comment]
If you have issues reply here and I'll reopen this issue.
