### ISSUE TITLE
Regression Bug for #288? (Upload Hang with only a couple bytes left)

### ISSUE THREAD

**Issue by cw-andrews** [robinrodricks/FluentFTP#411]
@robinrodricks

I am having this exact issue on version 24.0.0 - did this fix get reverted somehow?

**Comment by robinrodricks** [comment]
Fix released in 25.0.2. Please check!

https://www.nuget.org/packages/FluentFTP/25.0.2

**Comment by cw-andrews** [comment]
@robinrodricks I have updated to 25.0.3 and it looks to have fixed our issue. 

Thank you for getting it merged and having a new version out so quick!

**Comment by robinrodricks** [comment]
Your welcome!
