### ISSUE TITLE
UploadFile progress callback issue

### ISSUE THREAD

**Issue by spgozags** [robinrodricks/FluentFTP#413]
I'm attempting to use the FTPProgress callback method to display each file's upload status with a progress bar when uploading.

However, the callback method isn't called until after the file has already been uploaded to the server.

//Using the callback method
Progress<FtpProgress> progress = new Progress<FtpProgress>(x => {...}

//calling from UploadFile like the below
ftpClient.UploadFile(@um.file_path, newFile, FtpExists.Overwrite, false, FtpVerify.None, progress);

**Comment by robinrodricks** [comment]
Good find.

**Comment by robinrodricks** [comment]
Wait, do you mean that if the file already exists, the callback is not called? That is a bug and I can fix that.

Or do you mean that the callback should be called sooner?

**Comment by robinrodricks** [comment]
Fix released in 25.0.2. Please check!

https://www.nuget.org/packages/FluentFTP/25.0.2

**Comment by spgozags** [comment]
I meant that the progress isn't updated until after the file has been uploaded.  I have 2 progress bars.  One is for the file progress, and another is for the total progress of multiple files uploaded.  Currently I'm trying to use the callback for each file's progress as it loops through my upload process.  However, the "total" progress is finishing before the file progress, because the callback isn't launching until after the upload has completed.  I'm trying to use the callback especially for large files > 3GB.  I've updated to 25.0.2 and 25.0.3, and I'm still running into the same issue.

**Comment by robinrodricks** [comment]
That's very strange. We call `progress.Report()` synchronously every chunk transferred. (based on `client.TransferChunkSize` which is usually 65KB).

Can you download the source, add FluentFTP into your project, and add a breakpoint into `FtpClient_HighLevel.cs` > `UploadFileInternal()` at around line 983... where it says `ReportProgress(...)`...

That should help you see why the progress callback is not being called...

**Comment by spgozags** [comment]
The ReportProgress() is being called for UploadFile(), However, the callback function is not.  I modified my code to use the async method UploadFileAsync(), and the callback function is working fine.

**Comment by robinrodricks** [comment]
Then it seems to be a usage issue. I'm closing this.
