### ISSUE TITLE
Request to update NuGet Feed to 25.0.4

### ISSUE THREAD

**Issue by NoelWidmer** [robinrodricks/FluentFTP#417]
Hello

We are running into a NullReferenceException in a Dispose call. It seems like you fixed the issue in this commit (note that the commit message contains a misleading version number): https://github.com/robinrodricks/FluentFTP/commit/d2bb12b32955a6d122efdfed8f82d250403fa8da

Could you update the Feed to 25.0.4?
https://www.nuget.org/packages/FluentFTP

**Comment by robinrodricks** [comment]
Sure, but still not sure if that will fix it.

**Comment by robinrodricks** [comment]
Done. Should appear soon.

**Comment by NoelWidmer** [comment]
Nice. Thank you!
You have a great response time btw. Very impressive.

**Comment by NoelWidmer** [comment]
@robinrodricks Just wanted to let you know that this fix has increased our aplication performance noticeably. Exception occurences in our ftp scanner have decreased to 0 since we updated the package (they were so high that we felt the need to get in touch with you). I recommend updating to this package for everyone. Thanks again :)

**Comment by robinrodricks** [comment]
Oh wow, great news.

>
