### ISSUE TITLE
Progress report throws Exception 

### ISSUE THREAD

**Issue by Serejka** [robinrodricks/FluentFTP#418]
**FTP OS:** unknown

**FTP Server:** unknown

**Computer OS:** Windows 8.1

Using FtpClient.UploadFile with progress throws an exception 
*Message:* "Error while uploading the file to the server. See InnerException for more info."
*InnerException:* "attempted to divide by zero in FluentFTP.FtpClient.ReportProgress(IProgress`1 progress, Int64 fileSize, Int64 position, Int64 bytesProcessed, TimeSpan elapsedtime)
   in FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress)"

Probably it happens because file is too small - size is 551 bytes, but the file is uploaded to the ftp completely. With bigger files works fine.

**Comment by robinrodricks** [comment]
Wow good find.

**Comment by Serejka** [comment]
In my case it happens in FtpClient_HighLevel.cs / FluentFtp / ReportProgress when elapsedTime.TotalSeconds equals to 0. Probably there are more

**Comment by robinrodricks** [comment]
Does this work for you?

https://we.tl/t-HmS842rq6U

**Comment by robinrodricks** [comment]
Released in 25.0.5.

https://www.nuget.org/packages/FluentFTP/25.0.5
