### ISSUE TITLE
How to delete a file with/without version

### ISSUE THREAD

**Issue by namlai000** [robinrodricks/FluentFTP#419]
**FTP OS:** Windows

**FTP Server:** OpenVMS

**Computer OS:** Windows 10 Pro

I can not delete a file with only path because i'm missing the version of the file. Is there anyway to get the version of the file (file format is like ...TXT;1) or without version and just delete the latest one?

**Comment by robinrodricks** [comment]
Whats a FTP file version? Can you check if Filezilla Client supports this and if it does, paste the logs from Filezilla?

**Comment by robinrodricks** [comment]
When you reply with some helpful info we can reopen.
