### ISSUE TITLE
Getlisting(), cant access the files in the directory

### ISSUE THREAD

**Issue by AE-AEssam** [robinrodricks/FluentFTP#427]
**FTP OS:** Unix / Windows / Embedded

I am building FTP client to access the contents of a directory, all the code goes fine but when I try to read the files names or the check if they exist I receive the message "Timed out trying to connect!"

When I use the directory.exists() it replies with true or false but when I use file.exists() it reply the same error as Getlisting(). I tried several options of listing but nothing worked !

N.B
I accessed the FTP server via different sources and downloaded all the files inside and everything was fine. 
The system type: is UNIX Type: L8 
The server type is Unknown 
The OS type is UNIX

`

    public static async Task<IActionResult> Run(HttpRequest req, ILogger log)
     {
          using (FtpClient conn = new FtpClient()) 
        {
            
            conn.Host = "ftplink";
            conn.Credentials = new NetworkCredential("username", "pass");
            conn.RetryAttempts = 5;
            conn.Connect();

            log.LogInformation(conn.GetWorkingDirectory());
            log.LogInformation(conn.DirectoryExists("/out/work").ToString());
            //log.LogInformation(conn.FileExists("/out/work/qwewe.csv").ToString()); // gives the same error
            log.LogInformation("1");
            
          
        foreach (FtpListItem item in conn.GetListing("/")) 
                {
                    log.LogInformation(item.FullName);
                }
            conn.Disconnect();
        }
    
      }
`

**Comment by robinrodricks** [comment]
Please paste the full FluentFTP logs. See the FAQ how to get logs..

**Comment by robinrodricks** [comment]
Closing until you reply.
