### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object. at FluentFTP.FtpSocketStream.Dispose(Boolean disposing)

### ISSUE THREAD

**Issue by jameskimrex** [robinrodricks/FluentFTP#432]
**FTP OS:** Windows
**Computer OS:** Windows

FluentFTP.FtpSocketStream.Dispose: Object reference not set to an instance of an object" error. 

Occasionally uncatchable exception handled while downloading/uploading files by multiple thread , and I cannot catch the nullreferenceexception by try catch. https://github.com/robinrodricks/FluentFTP/issues/382 has been closed, but instead of updating fluentftp library to the latest version, the error is still happened.
Does anyone has any idea about this?

![Capture](https://user-images.githubusercontent.com/51578170/61255109-9b1a9400-a7aa-11e9-809b-0657e035bbdb.JPG)

**Comment by robinrodricks** [comment]
Hi, this is tough to debug. Could you download the source code of this library, build a debug version and add it to your project so we can see exactly where the error occured?

**Comment by robinrodricks** [comment]
Try this please:

https://we.tl/t-eMucFqbSpi

**Comment by jameskimrex** [comment]
Thanks for your response.
I have downloaded the files you sent me. Does the files that you build with debug version? And do you want me to use dll reference in my project for debugging the issue?
I am sorry, but how can I see the error log? I cannot replicate the issue in our testing environment. It only happens in production environment. Is there any way to log the error to Nlog or something?

Kind regards,
James

**Comment by robinrodricks** [comment]
Just check the files I sent on production. The exception should not come any more.

**Comment by jameskimrex** [comment]
I am really sorry to border you, but it is the new version of fluentFTP to fix the issue?

**Comment by robinrodricks** [comment]
Yes the new version should fix the issue. Just try it on production (replace the FluentFTP DLLs)

**Comment by jameskimrex** [comment]
I really appreciate for your help.
If you have a time, can I ask you what the issue?
I just guess something wrong in handling stream.

**Comment by robinrodricks** [comment]
Some exception in Dispose method which we dont care about..

**Comment by jameskimrex** [comment]
The files that you added does not include netstandard2.0, can I use netstandard1.6 version?

**Comment by robinrodricks** [comment]
Release in 26.0.1. You can take it from nuget now.

https://www.nuget.org/packages/FluentFTP/26.0.1

**Comment by jameskimrex** [comment]
thanks for all your help 👍

**Comment by robinrodricks** [comment]
Your welcome.
