### ISSUE TITLE
Upload() verification and multiple stream upload

### ISSUE THREAD

**Issue by BeniKing99** [robinrodricks/FluentFTP#433]
Hi
can I directly verify data I uploaded from a stream with upload(), like in the uploadfile() function? And is there a funtion simelar to the uploadfiles() function but for list<stream> (Uploading multiple streams after another without the need to call upload() multiple times)?

Best Regards

**Comment by robinrodricks** [comment]
Not yet...

**Comment by robinrodricks** [comment]
Added to the [bucket list](https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans). We will pick this up as and when we have free time. Comment on this issue if you want us to prioritize it. Thanks!
