### ISSUE TITLE
Using FluentFtp from PowerShell

### ISSUE THREAD

**Issue by RayZick** [robinrodricks/FluentFTP#434]
**FTP OS:** Windows

**Computer OS:** ? Windows Server 2019

I needed to call FluentFTP from PowerShell so I wrote 5 functions that demonstrate how to send, receive, list, rename, and remove files from PowerShell. Please let me know if you are interested in my PowerShell sample code

**Comment by robinrodricks** [comment]
Ok cool send them over.

**Comment by RayZick** [comment]
Here you go

[AdvantageCS]<https://htmlsig.com/t/000001BWV0CF>
Ray Zick / Product Manager
ray.zick@advantagecs.com<mailto:ray.zick@advantagecs.com>  +1 (734) 327-3627

http://www.advantagecs.com/
[Twitter]<https://htmlsig.com/t/000001C2P908>[Facebook]<https://htmlsig.com/t/000001BY7TCS>[LinkedIn]<https://htmlsig.com/t/000001BXNHX3>[Youtube]<https://htmlsig.com/t/000001BWSDXV>
CONFIDENTIAL NOTICE: This email communication and any attachments may contain confidential and legally privileged information for the exclusive use of the designated recipients named above. Any unauthorized review, use, storage, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply mail and destroy all copies of the original message.

**Comment by robinrodricks** [comment]
I didn't get anything. If you want to send files either attach them straight to the github page (https://github.com/robinrodricks/FluentFTP/issues/434) or upload them with wetransfer and send a link.

**Comment by RayZick** [comment]
[Fluent-Functions.zip](https://github.com/robinrodricks/FluentFTP/files/3452015/Fluent-Functions.zip)

**Comment by RayZick** [comment]
This looks like it worked

**Comment by robinrodricks** [comment]
Thanks I'll check it.

**Comment by robinrodricks** [comment]
What an awesome job, thanks! I've added it to the repo...

**Comment by robinrodricks** [comment]
Also added into the FAQ - https://github.com/robinrodricks/FluentFTP#powershell
