### ISSUE TITLE
Error using proxy (bluecoat) to an FTP server other than port 21

### ISSUE THREAD

**Issue by CMIGIT** [robinrodricks/FluentFTP#435]
**Computer OS:** ? Windows

I have an error using proxy (bluecoat) to an FTP server other than port 21.
The correction is quite simple, just add the port in the method "Handshake" of "FtpClientBlueCoatProxy" (and I think it is the same to FtpClientUserAtHostProxy) : 
			// Connection USER@Host means to change user name to add host.
			Credentials.UserName = Credentials.UserName + "@" + Host;
Must be : 
			// Connection USER@Host means to change user name to add host.
			Credentials.UserName = Credentials.UserName + "@" + Host + ":" + Port;

I hope you are not on vacation to provide "quickly" this correction :-)  
Thanks in advance

Christophe

**Comment by robinrodricks** [comment]
FluentFTP Is open source. Can you make that changed, make a build, and see if it works?

**Comment by CMIGIT** [comment]
I have already done the tests on my version but I prefer, if possible, to use the packaged version ;-)

**Comment by CMIGIT** [comment]
I have some trouble compiling the entire project in my VisualStudio. Maybe I did not install everything needed.
Nevertheless, I managed to compile by excluding some code and doing my tests. That's why I prefer to indicate the changes I made in my local version.
Thank you for the work you do on this API.

**Comment by robinrodricks** [comment]
Ok good but does this only apply for bluecoat proxy or is it applicable to our other proxy classes as well?

**Comment by CMIGIT** [comment]
I think it's also valid for FtpClientUserAtHostProxy because the code is very close.

**Comment by CMIGIT** [comment]
Do you expect new items from me?
Can you tell me when you are planning a new version?
This problem is blocking for me, so I would like to know if I have to use my junk version or if you will publish a new version soon :-)
(At the moment I manually transfer the files :-\ )
Thanks in advance

**Comment by robinrodricks** [comment]
Sorry :)

Done.

https://www.nuget.org/packages/FluentFTP/27.0.1
