### ISSUE TITLE
Add cancellation token to GetObjectInfoAsync() method

### ISSUE THREAD

**Issue by RicoSuter** [robinrodricks/FluentFTP#436]
The GetObjectInfoAsync() method should also expose a cancellationToken parameter like the other parameters.

**Comment by robinrodricks** [comment]
Done as of 31.1.0. Thanks for reporting!

See https://github.com/robinrodricks/FluentFTP/blob/master/RELEASES.md#3110

**Comment by RicoSuter** [comment]
Super, thanks.
