### ISSUE TITLE
Add an unsupported directory listing.

### ISSUE THREAD

**Issue by Hidend** [robinrodricks/FluentFTP#438]
**FTP OS:** Unix / Windows / Embedded
Unix

**FTP Server:** Pure-FTPd / DrFTPD / Vsftpd / ProFTPD / Vax / VMS / OpenVMS / Tandem / HP NonStop Guardian / IBM OS400 / AS400 / Windows CE
DrFTPD 

**Computer OS:** ?
Windows

Is this feature still working?
**Easily add unsupported directory listing parsers (see the CustomParser example)**

I would like to add an unsupported directory listing (STAT -l) but it seems like there's no [FtpListItem.AddParser](https://github.com/robinrodricks/FluentFTP/blob/f48af030b565237ddd5d7c8937378884d20e1627/FluentFTP.Examples/CustomParser.cs#L17) inside [FtpListItem class](https://github.com/robinrodricks/FluentFTP/blob/9874f80c73186dcafa251ed44cd04933775a9fe1/FluentFTP/Helpers/FtpListItem.cs#L13)

**Comment by Hidend** [comment]
Oh, found it I guess:
https://github.com/robinrodricks/FluentFTP/blob/069fa184a81194d6680f6e940d371dfd16e88404/FluentFTP/Helpers/FtpListParser.cs#L259

**Comment by robinrodricks** [comment]
What parser are you trying to add?

**Comment by Hidend** [comment]
I'm only allowed to list files using STAT -l, if I execute the command with ftp.Execute("STAT -l") I get the output of all files, but if I use ftp.GetListing with any FtpListOption I just get:
No connection could be made because the target machine actively refused it

I think I will have to open another Issue for this
