### ISSUE TITLE
Support for dotnet core ILogger

### ISSUE THREAD

**Issue by Dragonsangel** [robinrodricks/FluentFTP#443]
Logging is currently done via the `FtpTrace.AddListener()` Method or hooking into the `OnLogEvent`-Event.
Are there plans to support the dotnet core [ILogger](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger?view=aspnetcore-2.2) implementation?

Currently we can hook calls to `ILogger` into the `OnLogEvent` and write the logs based on `FtpTraceLevel`, it is just an easier way if the tool uses it automatically.

**Comment by robinrodricks** [comment]
Do you have any reference code with ILogger to help out?

**Comment by Dragonsangel** [comment]
Since you have a variation of your code that is used for when compiling for dotnet core, it should be as easy as using `ILogger<FtpClient>` as a constructor parameter that will be filled via Dependency Injection.
How ILogger is configured, where it logs to etc all is handled by the dotnet core framework and the appsettings.x.json files.

One Repository that uses ILogger<T> is the HealthChecks System for dotnet core.
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.UI/Core/HostedService/HealthCheckReportCollectorHostedService.cs#L15

**Comment by robinrodricks** [comment]
Thanks. Maybe we can support a `public` or `public static ILogger<FtpClient>` inside our FtpTrace class? That way if you don't specify a logger it will use its own system, or if you specify one then it will only pass all messages to the external logger. Will that be ok?

**Comment by robinrodricks** [comment]
Implemented in v40.
