### ISSUE TITLE
Error on upload file on FTPs Mode

### ISSUE THREAD

**Issue by DPMW** [robinrodricks/FluentFTP#448]
```
# Connect()
Status:   Connecting to ***:21
Response: 220-Microsoft FTP Service
Response: 220 *** says hello.
Status:   Detected FTP server: WindowsServerIIS
Command:  AUTH TLS
Response: 234 AUTH command ok. Expecting TLS Negotiation.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0,1131518.
Command:  USER ***
Response: 331 Password required
Command:  PASS ***
Response: 230-Willkommen!
Response: 230 User logged in.
Command:  PBSZ 0
Response: 200 PBSZ command successful.
Command:  PROT P
Response: 200 PROT command successful.
Command:  FEAT
Response: 500 Command not allowed.
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 500 Command not allowed.
Warning:  Cannot auto-detect listing parser for system 'Unknown', using Unix parser

# SetWorkingDirectory("/")
Command:  CWD /
Response: 250 CWD command successful.

# UploadFile("C:\ProgramData\Dokument001.pdf", "/Dokument001.pdf", Overwrite, False, None)

# FileExists("/Dokument001.pdf")

# GetNameListing("/")
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "NLST /", 0)
Command:  EPSV
Response: 500 Command not allowed.

# OpenPassiveDataStream(PASV, "NLST /", 0)
Command:  PASV
Response: 227 Entering Passive Mode (***,195,178).
Status:   Connecting to ***:50098
Command:  NLST /
Response: 500 Command not allowed.
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Ausnahme ausgelöst: "FluentFTP.FtpCommandException" in FluentFTP.dll
Ausnahme ausgelöst: "FluentFTP.FtpException" in FluentFTP.dll
```
Error while uploading the file to the server. See InnerException for more info.
Command not allowed.

Can anybody help to resolve?

**Comment by DPMW** [comment]
Thats the code for connection

  Dim ftpClient As New FluentFTP.FtpClient
  Dim ftpProfile As New FluentFTP.FtpProfile

  With ftpProfile
      .Credentials = New NetworkCredential(_FTP_User, _FTP_Passwort)

      If _FTP_UsePassiveMode = True Then
          .DataConnection = FluentFTP.FtpDataConnectionType.AutoPassive
      Else
          .DataConnection = FluentFTP.FtpDataConnectionType.AutoActive
      End If

      .Host = _FTP_Server
      .Protocols = System.Security.Authentication.SslProtocols.Tls12
      .Encryption = FluentFTP.FtpEncryptionMode.Explicit
      .Encoding = System.Text.Encoding.ASCII
  End With

  ftpClient.ListingParser = FluentFTP.FtpParser.Windows
  ftpClient.UploadDataType = FluentFTP.FtpDataType.Binary

  ftpClient.Connect(ftpProfile)

  Try
  
      ftpClient.SetWorkingDirectory(_FTP_Path)
      bln_UploadOK = ftpClient.UploadFile(sDoc.Replace("\\", "\"), _FTP_Path & strFileToUpload)
      
  Catch ex As Exception

      cls_Log.Write(0, ex.Message, "D")

      If Not ex.InnerException Is Nothing Then
          cls_Log.Write(0, ex.InnerException.Message, "D")     
      End If
 
  End Try

**Comment by robinrodricks** [comment]
Try `client.AutoDetect()` which now supports special settings for Azure. We cannot fix anything else as Azure is very buggy.
