### ISSUE TITLE
How to delete a file larger than 1.18Gb

### ISSUE THREAD

**Issue by dhopkins1961** [robinrodricks/FluentFTP#449]
**FTP OS:**  Windows 

**FTP Server:** ???

**Computer OS:** Windows

When trying to delete a file lager than 1.18Gb, your DeleteFileAsync returns a permission error.  Pretty sure it's because of the file size.  Do you have a work around/setting that can be made to enable the delete to work?

Thanks.................... 

David Hopkins
Netacent Inc.

**Logs :**

```
<paste logs here but DO NOT delete the lines above and below this line>
```

**Comment by robinrodricks** [comment]
Its a server side issue. We do not do any checks. Delete is just one FTP command.
