### ISSUE TITLE
How to secure connection via server public certificate in FluentFTP (.cer)

### ISSUE THREAD

**Issue by PingPongSet** [robinrodricks/FluentFTP#450]
I am using FluentFTP to connect to my company's public FTP server, I was given the server's public certificate (.cer).

I want to know what security measure is required to secure the connection?

Below is currently used.
```
FtpClient client = new FtpClient(hostname, username, password); // or set Host & Credentials
client.EncryptionMode = FtpEncryptionMode.Explicit;
client.SslProtocols = SslProtocols.Tls;
client.ValidateCertificate += new FtpSslValidation(OnValidateCertificate);
client.Connect();    
void OnValidateCertificate(FtpClient control, FtpSslValidationEventArgs e) {
    // add logic to test if certificate is valid here
    e.Accept = true;
}
```

Do i need to use either method below to validate the server's certificate? 

Is method 2 securer than method 1?

In method 2, is it correct that first I save the content of the server's certificate to a file, and use it to validate against the server's certificate on subsequent requests in the future? Can this prevent man-in-the-middle attack? Is this security measure secure?

Is it correct that the server's public certificate that I was given is not required?

**Comment by PingPongSet** [comment]
The problem is that the DNS on the certificate that we received is not specified. Thus, we cannot use the client certificate method , which was initially tried before opening this ticket.

I wonder if there is another way to secure the connection.

**Comment by robinrodricks** [comment]
Then try Method 2.

**Comment by robinrodricks** [comment]
Sorry I don't know how to help you. If you find a solution feel free to post it.

**Comment by PingPongSet** [comment]
Does using method 2 without using this: https://github.com/robinrodricks/FluentFTP#faq_certs provide good security or the same security?

**Comment by FanDjango** [comment]
Look at https://github.com/robinrodricks/FluentFTP/wiki/FTP-Connection and scroll down
