### ISSUE TITLE
Index and length must refer to a location within the string. Parameter name: length

### ISSUE THREAD

**Issue by namtab1** [robinrodricks/FluentFTP#454]
Windows
OpenVMS
Win 10

Hi

We have a problem trying to upload a csv stream to vms, we could do with some help please..
Data in our csv looks like this-
Brochure,Location,Revision,Seq No,Arrival or Stay,Supplmt Day or Wk,Occup Policy,Basic Board,Rounding,Child Policy,Child Age 1,Child Age 2
SS,3476,115,1,A,D,P,SC,N,A,15,No Value

Exception occurs when ftpClient.Upload is called.

Stack Trace was-
at System.String.Substring(Int32 startIndex, Int32 length)
   at FluentFTP.FtpClient.GetAbsolutePath(String path)
   at FluentFTP.FtpClient.GetNameListing(String path)
   at FluentFTP.FtpClient.FileExists(String path)
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress)

```
# Connect()
Status:   Connecting to ***:21

Command:  USER ***
Response: 331 Username diamondrpt requires a Password
Command:  PASS ***
Response: 230 User logged in.
Command:  FEAT
Response: 502 FEAT is unimplemented.
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 200 VMS OpenVMS V8.3 on node tigger.jfasystems.co.uk.
Status:   Detected FTP server: OpenVMS
Status:   Auto-detected VMS listing parser

# Upload("TOPAS$ROOT:[000000.TUIL.YR_20.SUBLIS]", Overwrite, False)

# FileExists("TOPAS$ROOT:[000000.TUIL.YR_20.SUBLIS]")

# GetNameListing(".")
```

Many thanks

**Comment by namtab1** [comment]
I think it might be useful for you to know that we are using your library to do a directory listing from the same location and download files.

**Comment by robinrodricks** [comment]
Try https://www.nuget.org/packages/FluentFTP/27.1.1

**Comment by namtab1** [comment]
Hi

Many thanks for jumping on this soooo quickly!

Unfortunately 27.1.1 has not resolved the problem.

Log below

# Connect()
Status:   Connecting to ***:21
Response: 220 tigger.jfasystems.co.uk FTP Server (Version 5.6) Ready.
Command:  USER ***
Response: 331 Username diamondrpt requires a Password
Command:  PASS ***
Response: 230 User logged in.
Command:  FEAT
Response: 502 FEAT is unimplemented.
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 200 VMS OpenVMS V8.3 on node tigger.jfasystems.co.uk.
Status:   Detected FTP server: OpenVMS

# Upload("TOPAS$ROOT:[000000.TUIL.YR_20.SUBLIS]SSA_BZL_63703973.CSV;1", Overwrite, False)

# FileExists("TOPAS$ROOT:[000000.TUIL.YR_20.SUBLIS]SSA_BZL_63703973.CSV;1")

# GetNameListing(".")

In a separate comment I mentioned we are able to get a directory listing and download files from exactly the same vms path we are trying to upload to.  It might be relevant.

Cheers

**Comment by robinrodricks** [comment]
Try this: (zip attached)
[Release.zip](https://github.com/robinrodricks/FluentFTP/files/3609972/Release.zip)

**Comment by namtab1** [comment]
Plumbed in the dll and have a different exception.  Log says -
# Connect()
Status:   Connecting to ***:21
Response: 220 tigger.jfasystems.co.uk FTP Server (Version 5.6) Ready.
Command:  USER ***
Response: 331 Username diamondrpt requires a Password
Command:  PASS ***
Response: 230 User logged in.
Command:  FEAT
Response: 502 FEAT is unimplemented.
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 200 VMS OpenVMS V8.3 on node tigger.jfasystems.co.uk.
Status:   Detected FTP server: OpenVMS

# Upload("TOPAS$ROOT:[000000.TUIL.YR_20.SUBLIS]SSA_BZL_63703984.CSV;1", Overwrite, False)

# FileExists("TOPAS$ROOT:[000000.TUIL.YR_20.SUBLIS]SSA_BZL_63703984.CSV;1")
Status:   Testing connectivity using Socket.Poll()...
Command:  MDTM TOPAS$ROOT:[000000.TUIL.YR_20.SUBLIS]SSA_BZL_63703984.CSV;1
Response: 502 MDTM is unimplemented.

# GetNameListing(".")

# GetWorkingDirectory()
Command:  PWD
Response: 257 "TOPAS$ROOT:[DIAMONDRPT]" is current directory.
Command:  TYPE I
Response: 200 TYPE set to IMAGE.

# OpenPassiveDataStream(AutoPassive, "NLST TOPAS$ROOT:[DIAMONDRPT]/.", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||53439|)
Status:   Connecting to ***:53439
Command:  NLST TOPAS$ROOT:[DIAMONDRPT]/.
Response: 550 file specification syntax error
Status:   Disposing FtpSocketStream...

# CloseDataStream()

I'm trying some things to see if the problem is at my end now.

If you can see otherwise please let me know.

Many thanks for your help.

**Comment by namtab1** [comment]
Changed FtpExists from Overwrite to NoCheck and the csv uploaded.  Can you explain please the consequences of this?

Cheers.

**Comment by namtab1** [comment]
Please ignore my previous question.

Just to reiterate, the zip file has resolved my issue.  Huge thanks!

Will you be building it into a nuget package sometime soonish?

Cheers.

**Comment by robinrodricks** [comment]
Yeah, but any idea how you got it to work? Was it a perfect solution or did you hack it?

**Comment by namtab1** [comment]
Semi perfect, in that I "Changed FtpExists from Overwrite to NoCheck and the csv uploaded".  Overwrite is fine, we can live with that.

Thanks.

**Comment by robinrodricks** [comment]
In that case its not really fixed. Whenever you try to call `FileExists()` it will crash again.

**Comment by namtab1** [comment]
I agree, "its not really fixed" but our use case allows us the luxury of not having to check if the file already exists.  The support you've provided has been superb, thanks very much.  Would you like this left open?

**Comment by robinrodricks** [comment]
Yeah I guess... If you have time perhaps try running FileExists and give me the logs so I can debug it...

**Comment by namtab1** [comment]
OK will do.  I'll attempt to try the FileExists by the end of the week.

**Comment by robinrodricks** [comment]
I'm closing this as I think I have solved it. If you have doubts, ask and we can reopen.
