### ISSUE TITLE
Create API for parameter startpos in Upload method

### ISSUE THREAD

**Issue by TomatorCZ** [robinrodricks/FluentFTP#456]
You have API for this in` OpenPassiveDataStream()` method. 
Functionality [https://www.php.net/manual/en/function.ftp-fput.php]

Could you move it into high-level Uploading ? 

Thanks:)

**Comment by robinrodricks** [comment]
I think UploadFile has an ability to append.. see the FAQ on appending...

**Comment by TomatorCZ** [comment]
Yes, but it can only append to end of the file. I meant the optional position in the remote file to start uploading to.

**Comment by robinrodricks** [comment]
It would totally complicate high level APIs, what do you need this for if not for appending? what is your use case?

**Comment by TomatorCZ** [comment]
We make compiler Php to .Net and we try to map each function in Php to C#. I think that the main usage of this is append part of file, because original is too big, so you cut it to smaller pieces. But as you mentioned, it can be used append function instead of this. If it is too complicated, i understand it. 
Thank you

**Comment by robinrodricks** [comment]
Added to the [bucket list](https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans). We will pick this up as and when we have free time. Comment on this issue if you want us to prioritize it. Thanks!
