### ISSUE TITLE
FileStreamResult

### ISSUE THREAD

**Issue by corequestion** [robinrodricks/FluentFTP#457]
Try to return a FileStreamResult without having to buffer it into a MemoryStream as the file is close to 500mb - however, it only returns 142kb of data. 

return new FileStreamResult(await client.OpenReadAsync(filePath), "text/plain");

Saving the file locally and doing the below works

return new FileStreamResult(System.IO.File.OpenRead(filePath), "text/plain");

**Comment by robinrodricks** [comment]
OpenRead is a low level method. It will not download the entire file. You need to do that manually or use the DownloadFile API which will directly download it to disk WITHOUT keeping it in memory. FTP streams are not reliable. We have no plans to fix them. If you wish you can make fixes yourself.
