### ISSUE TITLE
Exception when use OpenRead.

### ISSUE THREAD

**Issue by zhusheping** [robinrodricks/FluentFTP#459]
**FTP OS:**  Windows

**FTP Server:** Serv-U

**Computer OS:**  win10

Once a stream is opened with OpenRead, the sequence of Responses is messed up, resulting in exceptions.And I's ok when use DownloadFile.
```
# Dispose()
Status:   Disposing FtpClient object...
Status:   There is stale data on the socket, maybe our connection timed out or you did not call GetReply(). Re-connecting...
Status:   The stale data was: 229 Entering Extended Passive Mode (|||20002|)
Status:   Disposing FtpSocketStream...
Status:   Not sending QUIT because the connection has already been closed.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
```
And my code:
```
 using (var stream = ftpClient.OpenRead("/test/xxx.xml")//1. open a stream
 {
     string content = new StreamReader(stream).ReadToEnd();
 }
 await ftpClient.DeleteFileAsync("/test/xxx.xml");//2. del a file
 await ftpClient.GetListingAsync("/test");//3. getlist. then exception throwed.
```

**Logs :**

```
# OpenPassiveDataStream(AutoPassive, "RETR /30051/29960/data.xml", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||20001|)
Status:   Connecting to 121.40.84.41:20001
Command:  RETR /30051/29960/data.xml
Response: 150 Opening BINARY mode data connection for 201908221233851.xml (1022 Bytes).
Status:   Disposing FtpSocketStream...

# DeleteFileAsync("/30051/29960\data.xml")
Command:  DELE /30051/29960/data.xml
Response: 226 Transfer complete. 1,022 bytes transferred. 1.00 KB/sec.

# GetListing("/30051/29960", Auto)
Command:  TYPE I
Response: 250 DELE command successful.
```
### Note: The last three commands responded incorrectly.

**Comment by robinrodricks** [comment]
Do you guys read?

As per the docs you gotta call **GetReply** after you're done with **OpenRead**:

Low-level API:

> **OpenRead**() - (Prefer using Download() for downloading to a Stream or byte[]) Open a stream to the specified file for reading. Returns a standard Stream. Please call **GetReply**() after you have successfully transfered the file to read the "OK" command sent by the server and prevent stale data on the socket.

**Comment by Erik1222** [comment]
That helped - thanks! Perfect if GetReply() also was added to the example: https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP.CSharpExamples/OpenRead.cs
