### ISSUE TITLE
Resue FtpClient for all requests in an app or create one per operation?

### ISSUE THREAD

**Issue by PingPongSet** [robinrodricks/FluentFTP#462]
1 Can FtpClient object be reused across all requests with thread safety or must it be created like below for each operation (what about shared between operations within a request, like Scoped)?

2 Can calling Connect() and Disconnect() be omitted when calling either DownloadAsync, OpenReadAsync() or DeleteFile() methods?

            using (FluentFTP.FtpClient client = GetFtpClient())
            {
                client.Connect();
                using (var streamReader = new StreamReader(await client.OpenReadAsync(FilePath)))
                using (var ms = new MemoryStream())
                {
                    streamReader.BaseStream.CopyTo(ms);
                    content = ms.ToArray();
                }
                client.Disconnect();
            }

            private FluentFTP.FtpClient GetFtpClient()
            {

                FluentFTP.FtpClient client = new FluentFTP.FtpClient(Host, Port, Username, Password)
                {
                    EncryptionMode = FtpEncryptionMode.Explicit,
                    SslProtocols = SslProtocols.Tls
                };

                client.SocketKeepAlive = false;

                client.ValidateCertificate += OnValidateCertificate;

                return client;
            }

Please provide doc url if available.

Thanks in advance.

**Comment by robinrodricks** [comment]
1. Better to create FTP client per operation, if you reuse across threads then it must be blocking (2 threads cannot do FTP operation with the same FTP client at the same time)

2. Why are you using OpenReadAsync? Better to call Download which will give you array of bytes.

3. Docs are in readme : https://github.com/robinrodricks/FluentFTP#api

**Comment by PingPongSet** [comment]
Thanks for your prompt reply.

Sorry for not making it clear. Can you please answer my second question on my previous comment. That is, if either Connect() or Disconnect() can be omitted.

> 
2 Can calling Connect() and Disconnect() be omitted when calling either DownloadAsync, OpenReadAsync() or DeleteFile() methods?

DownloadAsync

**Comment by robinrodricks** [comment]
No it's better to call those

**Comment by PingPongSet** [comment]
Great! .Thx.
