### ISSUE TITLE
Upload file without progress callback.

### ISSUE THREAD

**Issue by gbanana** [robinrodricks/FluentFTP#464]
Win10 64bit
I cannot get the progress callback while the file uploading, after uploaded I got list of progress.
![image](https://user-images.githubusercontent.com/577581/66457401-f0f99200-eaa2-11e9-84f6-60ebfcf52476.png)

![image](https://user-images.githubusercontent.com/577581/66457373-db846800-eaa2-11e9-9b64-9457596c7f1d.png)

**Comment by robinrodricks** [comment]
Try this and see if it works?

  - New: Progress reporting for synchronous methods `Upload`, `Download`, `UploadFile` and `DownloadFile` are now sent via delegates
  - Fix: Correctly send progress for synchronous methods and retain `IProgress` for async methods

[Release.zip](https://github.com/robinrodricks/FluentFTP/files/3715760/Release.zip)

**Comment by robinrodricks** [comment]
Hello @gbanana  can you try that release and tell me if it works? Until you test I cannot push this release

**Comment by robinrodricks** [comment]
Pushed

https://www.nuget.org/packages/FluentFTP/28.0.0
