### ISSUE TITLE
TLS session resumption on passive ... error not requiring certificate validation

### ISSUE THREAD

**Issue by vtontodonato-c** [robinrodricks/FluentFTP#465]
**FTP OS:**  Windows 
**FTP Server:** FileZillaServer
**Computer OS:**  Windows 10 - 1903

Downloadfile on TLS passive connection, the second connection (the passive download) does not fire any certificate validation and the server reject the connection.

On file zilla server I need in Server/Setting/FTP overTLS setings/ to UNCHECK
"Require TLS session resumptio non data connection when using PROT P"

THIS only starting from the last Windows OS 1903 update.

Thanks for any action you can do to avoid this security problem.

**Comment by robinrodricks** [comment]
May be related to https://github.com/robinrodricks/FluentFTP/issues/347

**Comment by TNTUP** [comment]
Guessing the culprit is KB4524100, cause I don't have it on my main computer (the update installed but I didn't reboot) but my 2 other computers has the update installed and throwing this kind of error. Using ShareX (which uses FluentFTP). Running FileZilla Server on Windows Server 2016 if that matters! Cheers

**Comment by dove** [comment]
For me it was kb4519998.  I uninstalled on the server and ftp download worked again.  Once it was reinstalled it failed again with no other changes.  Anyone got any ideas?

**Comment by Kim-SSi** [comment]
I have the same occurring on a Windows 7 host and client running FileZilla Server.
The update causing the problem is KB4519976. Uninstalling this allowed normal operation.
