### ISSUE TITLE
Invalid code generated by AutoDetect: Encoding = System.Text.UTF8Encoding+UTF8EncodingSealed

### ISSUE THREAD

**Issue by PingPongSet** [robinrodricks/FluentFTP#468]
The code below is generated via `AutoDetect()` at the bottom, but the line below is invalid.

How to fix this?

`client.Encoding = System.Text.UTF8Encoding+UTF8EncodingSealed`

```
// add this above your namespace declaration
using FluentFTP;
using System.Text;
using System.Net;
using System.Security.Authentication;

// add this to create and configure the FTP client
var client = new FtpClient();
client.Host = "xxxx";
client.Credentials = new NetworkCredential("uername", "password");
client.EncryptionMode = FtpEncryptionMode.Explicit;
client.SslProtocols = SslProtocols.None;
client.DataConnectionType = FtpDataConnectionType.PASV;
client.Encoding = System.Text.UTF8Encoding+UTF8EncodingSealed;
client.ValidateCertificate += new FtpSslValidation(delegate (FtpClient control, FtpSslValidationEventArgs e) {
	// add your logic to test if the SSL certificate is valid (see the FAQ for examples)
	e.Accept = true;
});
client.Connect();
```

> How do I auto-detect the correct connection settings?
> 
> Use this code:
> 
> FtpClient client = new FtpClient(hostname, username, password); // or set Host & Credentials
> var profiles = client.AutoDetect();
> 
> // if any profiles are found, print the code to the console
> if (profiles.Count > 0){
> 	var code = profiles[0].ToCode();
> 	Console.WriteLine(code);
> }
> 

https://github.com/robinrodricks/FluentFTP

**Comment by robinrodricks** [comment]
just keep System.Text.UTF8Encoding.
