### ISSUE TITLE
bug: Exception happens when resume upload

### ISSUE THREAD

**Issue by Wildcatii** [robinrodricks/FluentFTP#469]
File:FtpClient_HighLevelUpload.cs
Line:755 
`if (!ResumeUpload(remotePath, ref upStream, offset, ex))`

this code will execute when an IOException throw, maybe this happens when we write bytes to remote file, so we try to resume upload,this is right in business.
but, in the function ResumeUpload, focus on these lines

File:FtpClient_HighLevelUpload.cs
Line:1054
`private bool ResumeUpload(string remotePath, ref Stream upStream, long offset, IOException ex) {
    // resume if server disconnects midway (fixes #39)
    if (ex.InnerException != null) {
    var iex = ex.InnerException as SocketException;
#if CORE
    if (iex != null && (int) iex.SocketErrorCode == 10054) {
#else
    if (iex != null && iex.ErrorCode == 10054) {
#endif
        upStream.Dispose();
        upStream = OpenAppend(remotePath, UploadDataType, true);
        upStream.Position = offset;
        return true;
    }
}
return false;
}`

upStream.Position = offset;  ??  this is the problem,  the property Position throw an Exception in it's definition  "FtpDataStream".
I know the author want to resume the position of streams, the OpenAppend function has set the remote file position, and should set the same position to local file. the local file position should be decided by remote file length, not the variable offset.

**Comment by robinrodricks** [comment]
I think this has been fixed in recent versions.

If you still get this issue, respond and I will reopen this issue.
