### ISSUE TITLE
Under heavy traffic, no exception raised for incomplete.

### ISSUE THREAD

**Issue by DraconPern** [robinrodricks/FluentFTP#472]
**FTP OS:** Ubuntu 18.04

**FTP Server:** ProFTPD

**Computer OS:** Win10

When the server is very loaded, FluntFTP 20.0.0 does not raise exception when a transfer is incomplete. Using about 25 clients running in the .net threadpool.  No encryption: FtpEncryptionMode.None

client.RetryAttempts = 3;
client.TransferChunkSize = 1024;
client.UploadFile(<local>,<remote>, FtpExists.Overwrite, false, FtpVerify.Throw | FtpVerify.Retry);
client.Disconnect();

**Comment by DraconPern** [comment]
Note that UploadFile also doesn't return failure.  The result is I am always getting about 3% of incomplete uploads.

**Comment by DraconPern** [comment]
Just want to note that I saw the same issue with filezilla server (on windows), but at <1% incomplete rate. I couldn't really reproduce the problem at a consistent manner.  The server is on the local network.  Just a note if it helps, the client objects were created from a thread running in the threadpool.

**Comment by robinrodricks** [comment]
We will need to stop suppressing exceptions in UploadFileAsync.

Related: #509

**Comment by robinrodricks** [comment]
In the newest version we are not suppressing exceptions. You should get proper failure reports via FtpStatus.Failed.

**Comment by robinrodricks** [comment]
I'm marking this as fixed because significant fixes were implemented in recent releases for UploadFile and DownloadFile. If you still get this error write back and I'll reopen.
