### ISSUE TITLE
Cannot verify MD5 hash when file name contains spaces when using egnyte.com

### ISSUE THREAD

**Issue by StephenY-Titian** [robinrodricks/FluentFTP#478]
**FTP Server:** egnyte.com service

When a file name contains spaces, the egnyte.com service puts quotation marks around the [FilePath] in the "251" response even if there were no quotes in the "MD5" command.  This confuses the response parsing in the "GetMD5()" method in "FtpClient_Hash.cs", which checks "if (response.StartsWith(path))".

The spec on http://tools.ietf.org/html/draft-twine-ftpmd5-00#section-3.1 does not seem to be very clear about when quotes should be used.  But regardless, it would be good for FluentFTP to work with egnyte.com.

**Logs :**

```
Command:  MD5 /shared/import/file 1.xlsx
Response: 251 "/shared/import/file 1.xlsx" 48317576D6CA6C93641CCB06487AF457
File Verification: FAIL
```

**Comment by robinrodricks** [comment]
Fixed by @Nimelo. Go thank him!
