### ISSUE TITLE
Unable to get directories (or files) with GetListing

### ISSUE THREAD

**Issue by CurbeNL** [robinrodricks/FluentFTP#481]
I'm unable to get the directories (or even files) with GetListing:

```
                FtpClient ftpConn = new FtpClient();
                ftpConn.Host = FtpServer;
                ftpConn.Port = FtpPort;
                ftpConn.Credentials = new System.Net.NetworkCredential(Username, Password);
                ftpConn.SslProtocols = System.Security.Authentication.SslProtocols.Tls12;
                ftpConn.EncryptionMode = FtpEncryptionMode.Implicit;
                ftpConn.ValidateCertificate += new FtpSslValidation(Client_ValidateCertificate);
                ftpConn.BulkListing = false;
                //ftpConn.DataConnectionType = FtpDataConnectionType.AutoPassive;
                ftpConn.Connect();

                FtpListItem[] FtpFolders = null;

                FtpFolders = ftpConn.GetListing(Folder);
```
I'm using the latest version. Any suggestions?

**Comment by Fadelast** [comment]
Same here. GetListing returns "Authentication failed because remote party has closed the transport stream" while downloading file using FTPS.

Problem starts from the past month, maybe a Windows Update about TLS is blocking the communication ?

**Comment by robinrodricks** [comment]
Not sure, too many issues could be at play here...

**Comment by CurbeNL** [comment]
We have moved temporarily to WinSCP. 
We made no modification to the code what so ever. But I asume it's a Windows update because it still works on the production environment, but not no our development. Production is behind on updates.

**Comment by JanLorenz77** [comment]
I have the same problem. Any suggestions?

**Comment by Fadelast** [comment]
> I have the same problem. Any suggestions? With Filezilla I can connect without any problems.

We also solved using the net assembly of winscp
https://winscp.net/eng/docs/library

It support FTPS even if in the documentation is'nt specified.

**Comment by robinrodricks** [comment]
Try AutoDetect() to discover the best connection settings and see if it works then.

See https://github.com/robinrodricks/FluentFTP#faq_autodetect

**Comment by JanLorenz77** [comment]
The connect works, but unfortunately I now get another error with GetListing(..):

FluentFTP.FtpCommandException
  HResult=0x80131500
  Nachricht = Unable to build data connection: Operation not permitted
  Quelle = FluentFTP
  Stapelüberwachung:
   bei FluentFTP.FtpClient.GetListingInternal(String listcmd, FtpListOption options, Boolean retry)
   bei FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
   bei Dennree.Bibliothek.Net.RetryFtpClient.<>c__DisplayClass25_0.<GetListing>b__0() 

Is there an alternative to Getlisting()?

Filezilla has no problems with my test server.

**Comment by JanLorenz77** [comment]
Our ftp server provider has made a change to the
SSL configuration made. Now it's working.

**Comment by robinrodricks** [comment]
@JanLorenz77  What was the change?

**Comment by JanLorenz77** [comment]
My service provider said that he added the "TLSOptions NoSessionReuseRequired" option to the server configuration  and restarted the service.

**Comment by robinrodricks** [comment]
@JanLorenz77 Thanks - https://github.com/robinrodricks/FluentFTP/issues/514
