### ISSUE TITLE
client.DownloadFiles(); im to stupid to use it. Can someone pls explain it to a noob

### ISSUE THREAD

**Issue by oKait0o** [robinrodricks/FluentFTP#483]
Hello

im trying to download whole Folder but im really to stupid to use it. im really new to this....
i dont understand the ienumrator part.

thats the piece i was working on.

using FluentFTP;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Collections;
using System.Net;

namespace WindowsFormsApp2
{
    public partial class Form1 : Form
    {
        
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {

            //Connect to Server

            FtpClient client = new FtpClient("host", "login", "pass"); // or set Host & Credentials
            client.DataConnectionType = FtpDataConnectionType.EPSV;
            client.Connect();

            string localDir = "xxx";
            string remotePath = "xxxxx";
            String maindir = "/xxxxxx/";

            // Switch directory
            client.SetWorkingDirectory(maindir);

            // List files/folders from active dir
            client.GetListing("/", FtpListOption.Recursive);

            // Download files

           
            

        }

    }
}

i tried to ask a couple friends but no success either. ;(

sorry to make it as Issue Ticket but i didnt know where else to Ask.

**Comment by robinrodricks** [comment]
Ah. You'll need to call GetListing() and then get a listing of all the files and folders. Call it with Recursive option so it gets all the files deep within the folders.

Then extract just the string paths of the listing and pass that array to DownloadFiles()...

**Comment by oKait0o** [comment]
after long fight i figured it out and it works. Now i got a problem with tracking the progress.....

**Comment by robinrodricks** [comment]
You can now use Upload/DownloadDirectory methods.
