### ISSUE TITLE
How to disable ValidateCertificate from PowerShell

### ISSUE THREAD

**Issue by LazaroOnline** [robinrodricks/FluentFTP#484]
How can I disable the certificate validation when using FtpSSL from PowerShell?
I've seen that in C# it is done like this:
```cs
client.ValidateCertificate += new FtpSslValidation((FtpClient control, FtpSslValidationEventArgs e) => { e.Accept = true; });
```
But I can't find a way to do that from PowerShell.
I'm trying with something like:
```ps1
Register-ObjectEvent -inputObject $client -eventName ValidateCertificate -Action { param($control, $e) $e.Accept = $true }
```
But it doesn't work.

If only there was a boolean property on the client to deactivate the validation completely without having to write such a complicated code even for C#, it would be an awesome feature for me, something like:
```cs
client.CertificateValidation = false;
```
That would translate nicely to PowerShell like this:
```ps1
$client.CertificateValidation = $false;
```
I would appreciate any help, Thank you!

**Comment by robinrodricks** [comment]
Good idea. This is not implemented yet but I'll try to work on a fix.

**Comment by robinrodricks** [comment]
Done!

New: `ValidateAnyCertificate` property to validate any received server certificate, useful for Powershell users.

https://www.nuget.org/packages/FluentFTP/28.0.4

**Comment by LazaroOnline** [comment]
Thank you very much!
By the way, I saw that you updated the NuGet package, to the latest version 28.0.4,
but what about the github releases?
https://github.com/robinrodricks/FluentFTP/releases

and the powershell section in the repo at:
https://github.com/robinrodricks/FluentFTP/tree/master/Powershell
that contains an old version of the dll.

Is there any plan to update those too?
I'm interested because I have a script that downloads the latest version from github's releases page.
If that is no longer maintained then I'll change to search for NuGet and then extract the dll.

**Comment by robinrodricks** [comment]
Sorry, forgot about that. Updated it.

I don't use GH releases. I use nuget. And the powershell folder.
