### ISSUE TITLE
Option to return UTC times in GetListing.

### ISSUE THREAD

**Issue by cheverdyukv** [robinrodricks/FluentFTP#485]
Currently GetListing returns all times in local time because it passes DateTimeStyles.AssumeUniversal even if server correctly returns date time in UTC format.
As result I have to convert them to UTC format and I believe that can be slightly incorrect around Daylight Saving Time. It will be nice to get time in UTC format from the beginning as it is recommended way to store DateTime anyway.

**Comment by robinrodricks** [comment]
Good idea. Lets see if we can do this.

**Comment by cheverdyukv** [comment]
Thank you.

Also will be nice to know if server actually did return time in UTC instead just translating local time from server to UTC.

**Comment by robinrodricks** [comment]
I think its already implemented, please check https://github.com/robinrodricks/FluentFTP#advanced-settings

Try setting the TimeOffset to the difference between your server and your PC, and tell me if it works?

It should work for all GetListing and related calls.

**Comment by robinrodricks** [comment]
Do you know for sure if your server is returning times in UTC or do you want us to detect that?

Because if we don't know its UTC how can we convert it to local time?

**Comment by cheverdyukv** [comment]
Well ideally I would like to know if server supports UTC. I need to detect that file is changed and server does not support UTC then it will be unsupported case. But I can also check DateTime.Kind to see if this time is UTC assuming that there will be no attempt to convert non-UTC date time to UTC in your code.

**Comment by robinrodricks** [comment]
Done. Gone live with 29.0.0:

  - New: Add `TimeConversion` property to control if timestamps are converted from UTC into local time

https://www.nuget.org/packages/FluentFTP/29.0.0

**Comment by cheverdyukv** [comment]
Thank you very much. But default setting to zero is breaking change. Is it ok?

**Comment by robinrodricks** [comment]
No it's "assume universal" which is the same as what it was earlier. How is
it a breaking change?

**Comment by cheverdyukv** [comment]
Well previously without any change I got DateTime.Kind == Local. Now it is Unspecified.

**Comment by robinrodricks** [comment]
Your right. Fixed.

https://www.nuget.org/packages/FluentFTP/29.0.1

**Comment by cheverdyukv** [comment]
I checked and it works as expected. Thank you!
