### ISSUE TITLE
NewLine endings in Linux environment

### ISSUE THREAD

**Issue by copelandtech-casey** [robinrodricks/FluentFTP#486]
**FTP OS:** Windows

**FTP Server:** Windows FTP

**Computer OS:** Docker Linux any flavor

When running FluentFTP on .net Core 3.0 and 3.1, library uses the computer OS (Linux) Environment.NewLine character (\n). Microsoft FTP sends and expects to receive \r\n as the NewLine character on commands. Since the proper line endings aren’t sent and received, the connection times out waiting for the server welcome message. Code works perfectly if run on windows containers or locally on Windows 10.

I can’t seem to find anywhere to set the line ending character for the library. Is there a way or is this feature that will need to be added? I have no control over the server so I cannot configure it to accept anything other than \r\n. 

**Logs :**

No logs needed.

**Comment by robinrodricks** [comment]
Good point. Is this during GetListing or during connection itself?

**Comment by copelandtech-casey** [comment]
Any and all communication. FluentFTP gets stuck waiting for server welcome message since it never receives what it thinks is the correct format of new line. It appears it eventually times out and continues anyways but by then the server has severed the connection. 

I haven’t looked at much of the source yet and I’m making a big assumption, but I’m assuming this can be fixed by an extension method to add something along the lines of .UseSpecificLineEndings(Enum.Windows) or something along that line. 

If I get time, I’ll try to submit a pull request today with a fix. Not sure though that I have time to get the dev environment set up and follow all the guidelines for a PR. If not, I suppose I’ll make do with using the quick raw sslstream code I wrote to last night while trying to figure out what was going on until a fix can be merged.

**Comment by copelandtech-casey** [comment]
A thought just occurred. Can you check for specific types of line endings on the first message received from the server and make assumptions based on that and adjust accordingly? The first message does include \r\n so would it be illogical to assume if you receive this then you can assume the server is of a specific type and change the line endings to match?

**Comment by robinrodricks** [comment]
Maybe a good idea. However I don't want to break anything so we'll have to see how to implement this in a backwards compatible way.

**Comment by novak-as** [comment]
According to the **RFC959**:
`The FTP uses the Telnet protocol on the control connection.`

According to the **RFC318**:
`The end of a line of text shall be indicated by the character sequence Carriage Return Line Feed (CR, LF). `

Thus, a single `LF` is an invalid eol because it should be translated into `CR LF` before sending to the server. I agree that `LF` works for many ftp servers, but I can also confirm that some software works strictly to the RFC requirements.
According to this - always using `CR LF` will break nothing because this is how things are expected to work.

**Comment by novak-as** [comment]
finally got some time to check this

fluent ftp 33.0.3 running in the `mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim`

![image](https://user-images.githubusercontent.com/6292968/106136790-70b4df80-6172-11eb-9a32-fad20128d6fc.png)

i.e. `\r\n` is used as a EOL, so probably this issue could be closed? @robinrodricks

**Comment by robinrodricks** [comment]
I cannot remember the exact implementation, but I think we are switching the line ending depending on the server tech.

**Comment by robinrodricks** [comment]
Closing for now as requested. Thanks.
