### ISSUE TITLE
send file stream through http not working

### ISSUE THREAD

**Issue by MRSheikh** [robinrodricks/FluentFTP#487]
**FTP OS:** linux

**Computer OS:** windows 7 / firefox 69

i want to download large file from ftp server and send it to my client through http.
this is my code to send chunk of data but nothing happened on browser.
` byte[] buffer = new byte[1024];
                string path = "disk1/Drivers/" + GetFtpBrands(brandName) + "/" + modelName + "/" + osName + "/" +
                              file;
HttpContext.Current.Response.Clear();
                HttpContext.Current.Response.ClearContent();
                HttpContext.Current.Response.BufferOutput = true;
                HttpContext.Current.Response.ContentType = "application/octet-stream";
                HttpContext.Current.Response.AddHeader("content-disposition", "attachment;filename=\"" + file+"\"");

                FtpDataStream inputStream = (FtpDataStream) ftp.OpenRead(path,FtpDataType.Binary);

                int read = 0;
                while ((read = inputStream.Read(buffer, 0, buffer.Length)) > 0)
                {
                    HttpContext.Current.Response.OutputStream.Write(buffer, 0, read);
                    HttpContext.Current.Response.Flush(); // Sends all currently buffered output to the client.
                }
                
                inputStream.Close();
                HttpContext.Current.Response.OutputStream.Close();`

**Comment by robinrodricks** [comment]
Since this question is not related to a bug or feature within FluentFTP, its better you ask it on stackoverflow.
