### ISSUE TITLE
Cannot download file/directory with blank spaces

### ISSUE THREAD

**Issue by fefno** [robinrodricks/FluentFTP#488]
It can't download any files or folders that contain blank spaces. Error: `no such file. `. It seems to me that it splits the string in the first blank space it finds.

Some examples:
- `/site1/bin/Weblite MVC 3 v2.dll` turns to `/site1/bin/Weblite`
- `/site1/Static/Uploads/Site/CKFinder/images/Imagens antigas/1.jpg` turns to `/site1/Static/Uploads/Site/CKFinder/images/Imagens`
- `/site1/Content/Scripts/Rhino Slider/img/slider/03.jpg` turns to `/site1/Content/Scripts/Rhino`

**Comment by ken915007** [comment]
We got the same issue for download and upload when you setting retry.
it's error on XMD5 checking.

485  OpenRead("/test/Ken test.txt", ASCII, 0)
Command:  TYPE A
Response: 200 Type set to A.

OpenPassiveDataStream(PASV, "RETR /test/Ken test.txt", 0)
Command:  PASV
Status:   Connecting to 216.52.208.24:56040
Command:  RETR /test/Ken test.txt
Response: 150 Opening ASCII mode data connection for Ken test.txt (39033246 Byte
s).
Status:   Disposing FtpSocketStream...
Response: 226 Transfer complete. 39182369 bytes transferred. 13793.81 KB/sec.
Command:  XMD5 /test/Ken test.txt
Response: 550 /test/Ken: No such file.
FluentFTP.FtpCommandException: /test/Ken: No such file.
   at FluentFTP.FtpClient.GetXMD5(String path)
   at FluentFTP.FtpClient.GetChecksum(String path)
   at FluentFTP.FtpClient.VerifyTransfer(String localPath, String remotePath)
   at FluentFTP.FtpClient.DownloadFileToFile(String localPath, String remotePath
, FtpLocalExists existsMode, FtpVerify verifyOptions, Action`1 progress)
   at FluentFTP.FtpClient.DownloadFile(String localPath, String remotePath, FtpL
ocalExists existsMode, FtpVerify verifyOptions, Action`1 progress)
   at ConsoleApp3.Common.FTPClient_FluentFTP.Download(String localFilePath, Stri
ng remoteFileName, Boolean EnableSsl)
   at ConsoleApp3.Program.Main(String[] args)

**Comment by ken915007** [comment]
We got the same issue for download and upload when you setting FtpVerify.Retry.
it's error on XMD5 checking will remove character after blank space.

TraceLog:
485 OpenRead("/test/Ken test.txt", ASCII, 0)
Command: TYPE A
Response: 200 Type set to A.

OpenPassiveDataStream(PASV, "RETR /test/Ken test.txt", 0)
Command: PASV
Command: RETR /test/Ken test.txt
Response: 150 Opening ASCII mode data connection for Ken test.txt (39033246 Byte
s).
Status: Disposing FtpSocketStream...
Response: 226 Transfer complete. 39182369 bytes transferred. 13793.81 KB/sec.
Command: XMD5 /test/Ken test.txt
Response: 550 /test/Ken: No such file.
FluentFTP.FtpCommandException: /test/Ken: No such file.
at FluentFTP.FtpClient.GetXMD5(String path)
at FluentFTP.FtpClient.GetChecksum(String path)
at FluentFTP.FtpClient.VerifyTransfer(String localPath, String remotePath)
at FluentFTP.FtpClient.DownloadFileToFile(String localPath, String remotePath
, FtpLocalExists existsMode, FtpVerify verifyOptions, Action1 progress) at

**Comment by fefno** [comment]
I temporary  solved the problem using the OpenRead() instead of DownloadFile(). Like this:

`if (file.FullName.Contains(" ")`
`{`
`ftp.OpenRead(...);`
`}`
`else`
`{`
`   ftp.DownloadFile(...)`
`}`

**Comment by robinrodricks** [comment]
@fefno Can you paste your entire FluentFTP logs. Also tell us which server you are using.

**Comment by Calteo** [comment]
GetListing and SetWorkingDirectory fail as well (on a Fritz!Box).

**Comment by robinrodricks** [comment]
@fefno Can you check the FAQ on enabling FluentFTP logging and paste the entire logs right from the connection to when you run the command under test?

**Comment by Calteo** [comment]
Well if I use native ftp on the cmd then `cd some folder` of course fails
`550 some: no such file or directory`
While `cd "some folder"` succeeds (if the folder some folder really exists :-))
So you maybe just need to put the names in qoutes. Doesnt seem to hurt to do that always.

**Comment by robinrodricks** [comment]
Look, I need the entire logs, in order to code server specific functionality. How many times do I have to ask?

**Comment by fefno** [comment]
my friend, very sorry to say that, but... I understand your commitment and goodwill to create this repository for free! I respect that! But (and I'm sorry to say that again), if you don't have the patience to deal with users, just stop! No one is forcing you to correct. I created this issue just to let you know the problem I had and how did I fix it. Other people may be having the same difficulty.

**Comment by robinrodricks** [comment]
@fefno No need to get so dramatic. You said you're using Fritzbox so I needed to analyse your logs to add the functionality in the library to detect Fritzbox. This will be useful for future as well if I need to code any Fritzbox specific fixes. I'm not running out of patience and honestly I don't understand why you cannot co-operate and give me the logs.

**Comment by robinrodricks** [comment]
Until you paste the logs we cannot debug this.

**Comment by ken915007** [comment]
Could you fix my issue for download/upload when you setting FtpVerify.Retry.
it's error on XMD5 checking will remove character after blank space.
