### ISSUE TITLE
Zero size files problem with progress not being called

### ISSUE THREAD

**Issue by jasonspar** [robinrodricks/FluentFTP#489]
When downloading a file with 0 bytes, it is completed correctly and returns true from DownloadFileAsync. But the progress is never reported. The UI remains at 0% althought the operation is done. The API should call the progress reporter in this case so that the client code can update the UI. Even if no bytes are transferred, the file is created. So, technically the operation is 100% completed.

I think this loop is never entered because both offset and fileLen are 0:

while (offset < fileLen || readToEnd) {
   . . .
   ReportProgress(progress, fileLen, offset, bytesProcessed, DateTime.Now - transferStarted);
   . . .
}

**Comment by robinrodricks** [comment]
Good point.

**Comment by robinrodricks** [comment]
Done. Gone live with 29.0.0:

  - Fix: Always send progress reports after file download, even for zero-length files

https://www.nuget.org/packages/FluentFTP/29.0.0
