### ISSUE TITLE
Add ability to force use of recursive LIST in Vsftpd

### ISSUE THREAD

**Issue by ManlyMarco** [robinrodricks/FluentFTP#491]
**FTP OS:** Ubuntu

**FTP Server:** Vsftpd

**Computer OS:** Windows

Recursive list command is not used in Vsftpd even though support for it is enabled in vsftpd.conf by setting `ls_recurse_enable=YES`.

Looks like it's not possible to detect this support https://github.com/robinrodricks/FluentFTP/blob/e21a444496a5a75d500a968006600eb9eaaae465/FluentFTP/Client/FtpClient_ServerSpecific.cs#L380 but I know for sure that certain server has it and it works by changing `RecursiveList` to always return true.

The issue is that I would like to avoid using a custom build. Would it be possible to have a way to force RecursiveList to be true or otherwise override the behavior on a per-server basis?

**Comment by robinrodricks** [comment]
Good idea.

**Comment by robinrodricks** [comment]
Done! You can now set `RecursiveList` to true.

Grab https://www.nuget.org/packages/FluentFTP/28.0.3

**Comment by ManlyMarco** [comment]
Works, thank you for the fast fix!

I've actually got an idea regarding automatic detection. Why not attempt to call a recursive list command either way, and then inspect the output to figure out if recursion is supported? If the reply has directories in it but doesn't have their contents then fall back to non-recursive mode.

**Comment by robinrodricks** [comment]
Tough. Too many situations where that would fail. If there are blank folders. And plus the file listing is not bullet proof. Since there is no standard its tough to read using regex. Thanks for the suggestion tho!
