### ISSUE TITLE
I am getting "Access not allowed..." error with UploadFile() 

### ISSUE THREAD

**Issue by AnilEkmekci** [robinrodricks/FluentFTP#492]
When i am trying to upload a file, i am getting "Access not allowed. _USERNAME_ tried to violate upload privileges" error. I can't get through this :/. I can upload file via FileZilla with same credentials.
I am getting exception at UploadFile method. Can you help me?

**My code is;**
```
            FtpClient client = new FtpClient("_ServerAdress_");
            client.Credentials = new NetworkCredential("UserName", "Password");
            client.Connect();
            client.UploadFile(@"C:\Users\anil.ekmekci\Desktop\9_0_25_Test\DBUPDATE\CMas1.M80", "/9_0_25_Test/DBUPDATE/CMas1.M80");
            client.Disconnect();
```

**Comment by robinrodricks** [comment]
Please paste the full logs from FluentFTP and from Filezilla so we can compare.

**Comment by AnilEkmekci** [comment]
Hi,
I can solve the problem with comparing FluentFTP and FileZilla logs.
I set the same parameters with the FileZilla sets and it worked.
Thank you for the hint :).
