### ISSUE TITLE
Ftp Client constructor overload that accepts a System.Uri

### ISSUE THREAD

**Issue by ArthurHNL** [robinrodricks/FluentFTP#496]
**FTP OS:** Unix 

**FTP Server:** Irrelevant

**Computer OS:** Windows (development) / Docker on Kubernetes + Ubuntu (Production)

Please provide a constructor overload for the `FluentFTP.FTPClient` type that accepts a `System.Uri` instead of a string for the host and an integer for the port. Currently, I have to do this:

```csharp
Uri someUri = UriFactory.Create();
NetworkCredential credential = CredentialFactory.Create();
IFtpClient ftpClient = new FtpClient(uri.Host, uri.Port, credential);
```

This would be more convenient: 

```csharp
Uri someUri = UriFactory.Create();
NetworkCredential credential = CredentialFactory.Create();
IFtpClient ftpClient = new FtpClient(someUri, credential);
```

Ideally, the following constructors would be added to `FtpClient`:

- `FtpClient(Uri host)`
- `FtpClient(Uri host, NetworkCredential credentials)`
- `FtpClient(Uri host, string username, string password)`

Any Uri can be verified for Ftp using the following oneliner:

```csharp
bool isValid = (!(uri is null) && uri.Scheme == Uri.SchemeFtp);
```

_Edit: port is of course an integer, not a string._

**Comment by robinrodricks** [comment]
Good idea. Easy stuff.

**Comment by robinrodricks** [comment]
Done. Gone live with 29.0.0:

  - New: New constructors for `FtpClient` to support hostnames in `Uri` format

https://www.nuget.org/packages/FluentFTP/29.0.0
