### ISSUE TITLE
Target netStandard2.0

### ISSUE THREAD

**Issue by domi2120** [robinrodricks/FluentFTP#497]
Currently only netStandard 1.4 and 1.6 are targeted. Are there plans to also target netStandard 2.0 ?

**Comment by robinrodricks** [comment]
Does it make a difference?

**Comment by robinrodricks** [comment]
If/when you comment I'll reopen this thread.

**Comment by domi2120** [comment]
Apologies for the late response, the difference would likely only be fewer dependencies. I've seen in https://github.com/robinrodricks/FluentFTP/issues/502 that netStandard 2.0 will be supported in v29, which is exactly what i was looking for. Thank you.

**Comment by robinrodricks** [comment]
Great.
