### ISSUE TITLE
Suggestion: Rename FtpExists to FtpRemoteExists to make its use clear

### ISSUE THREAD

**Issue by DFEvans** [robinrodricks/FluentFTP#501]
I managed to get confused between the `FtpExists` and `FtpLocalExists` enums, spending a good few minutes trying to work out why my download wasn't overwriting - `FtpExists.Overwrite` has a different value to `FtpLocalExists.Overwrite`, but either enum was accepted without complaint or warning in a call to `DownloadFile`, despite the call signatures specifying the types (I'm surprised by that, but it's Microsoft's problem).

This sort of mistake would be less likely if the `FtpExists` enum were renamed to make it clear that it only applies to the existence of remote files, e.g. `FtpRemoteExists`.

**Comment by robinrodricks** [comment]
Which IDE are you using?

**Comment by DFEvans** [comment]
Visual Studio 2019.

**Comment by robinrodricks** [comment]
I could do that, but it would be a breaking change for everyone who has used it before. Maybe a better idea to fix the API so it triggers the correct compile time error in VS. Any attribute I can add to the enums or methods?

**Comment by robinrodricks** [comment]
Done. Gone live with 29.0.0:

  - Refactor: Rename `FtpExists` to `FtpRemoteExists` to make its usage clear

https://www.nuget.org/packages/FluentFTP/29.0.0
