### ISSUE TITLE
Support for .NET Core 3

### ISSUE THREAD

**Issue by McKabue** [robinrodricks/FluentFTP#502]
**Computer OS:** Linux Ubuntu 16.04

`System.IO.FileNotFoundException : Could not load file or assembly 'FluentFTP, Version=28.0.5.0, Culture=neutral, PublicKeyToken=f4af092b1d8df44f'. The system cannot find the file specified.`

**Comment by robinrodricks** [comment]
Version 29 supports .NET Standard 2.0. That works for ya?

**Comment by robinrodricks** [comment]
When you respond I'll reopen.
