### ISSUE TITLE
Hash method.

### ISSUE THREAD

**Issue by Evaexe117** [robinrodricks/FluentFTP#505]
**FTP OS:** Unix

**FTP Server:** Vsftpd / 

**Computer OS:**  Debian 9 - VPS

Hello
I have many error when i try to use Hash methode,
When i try to 
`Ftp.HashAlgorithms.ToString());`  -> output : None
When i try to 
`Ftp.GetHash("test.exe")); -> output : FluentFTP.FtpCommandException: 'Unknown command.'
When i try to 
`Ftp.SetHashAlgorithm(FtpHashAlgorithm.MD5);` -> output : System.NotImplementedException: 'The hash algorithm MD5 was not advertised by the server.'

So its apear i can't use any Hash methode, i use Wsftpd on a Debian 9 VPS server;
My question is how can i set Hash methode on the server in VSFTPD ?

Thanks,

**Comment by robinrodricks** [comment]
That means your server doesn't support server side hashing.

**Comment by Evaexe117** [comment]
Indead, any idea for active it ? Vsftpd is very popular, its seem impossible for this server to does not support server side hashing.

Thanks !

**Comment by robinrodricks** [comment]
Trying hashing with FileZilla, if it also fails then its a server issue. Or try using Execute() API to run raw Hashing commands on your server and check if it supports.
