### ISSUE TITLE
Can't connect to TLS ftp site

### ISSUE THREAD

**Issue by dansharpe83** [robinrodricks/FluentFTP#510]
**FTP OS:**  Windows

**FTP Server:** 

**Computer OS:** ?

i'm trying to connect to an FTP site using TLS, i had it working on winSCP but i can't seem to get it working via fluentFTP, i always get a 534 when trying to use explicit encryption. due to some new constraints we need to move away from winscp

this is my set up for testing:

` using(FtpClient client = new FtpClient(_config.CmosFtpUrl))
            {
                FtpTrace.EnableTracing = true; 
                FtpTrace.LogToFile ="log_file.txt";
                FtpTrace.LogUserName = false;   // hide FTP user names
                FtpTrace.LogPassword = false;   // hide FTP passwords
                FtpTrace.LogIP = false; 	// hide FTP server IP addresses
                client.Credentials = new System.Net.NetworkCredential("anonymous", "");
                client.ClientCertificates.Add(cert);
                client.Port = 21;
                //client.PlainTextEncryption = true;
                client.EncryptionMode = FtpEncryptionMode.Explicit;
                client.DataConnectionType = FtpDataConnectionType.AutoPassive;
                client.SslProtocols = SslProtocols.Tls12;
                client.Host = _config.CmosFtpUrl;
                // client.SslProtocols = System.Security.Authentication.SslProtocols.None;
                client.ValidateAnyCertificate = true;
                await client.ConnectAsync();
                await client.ExecuteAsync("FEAT", default);

                var directory = await client.GetWorkingDirectoryAsync();
                logger.LogInformation(directory);
            }`

i don't seem to have enough detail from the fluentFTP trace to see why its failing on the connectasync, as far as i can tell, it should be asking for a certificate from the AUTH TLS call?

**Logs :**

```
here is my log from fluentFTP:
`# ConnectAsync()
Status:   Connecting to ***:21
Response: 220 Microsoft FTP Service
Status:   Detected FTP server: WindowsServerIIS
Command:  AUTH TLS
Response: 534 Local policy on server does not allow TLS secure connections.

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Response: 221 Goodbye.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
`

if it helps here is the log i have from winSCP that works:
`. 2020-01-14 13:45:56.838 Session name: anonymous@***** (Ad-Hoc site)
. 2020-01-14 13:45:56.838 Host name: ***** (Port: 21)
. 2020-01-14 13:45:56.838 User name: anonymous (Password: No, Key file: No, Passphrase: Yes)
. 2020-01-14 13:45:56.838 Transfer Protocol: FTP
. 2020-01-14 13:45:56.838 Ping type: Dummy, Ping interval: 30 sec; Timeout: 6 sec
. 2020-01-14 13:45:56.838 Disable Nagle: No
. 2020-01-14 13:45:56.838 Proxy: None
. 2020-01-14 13:45:56.838 Send buffer: 262144
. 2020-01-14 13:45:56.838 UTF: Auto
. 2020-01-14 13:45:56.838 FTPS: Explicit TLS/SSL [Client certificate: Yes]
. 2020-01-14 13:45:56.838 FTP: Passive: Yes [Force IP: Auto]; MLSD: Auto [List all: Auto]; HOST: On
. 2020-01-14 13:45:56.838 Session reuse: Yes
. 2020-01-14 13:45:56.839 TLS/SSL versions: TLSv1.0-TLSv1.2
. 2020-01-14 13:45:56.839 Local directory: default, Remote directory: home, Update: Yes, Cache: Yes
. 2020-01-14 13:45:56.839 Cache directory changes: Yes, Permanent: Yes
. 2020-01-14 13:45:56.839 Recycle bin: Delete to: No, Overwritten to: No, Bin path: 
. 2020-01-14 13:45:56.839 Timezone offset: 0h 0m
. 2020-01-14 13:45:56.839 --------------------------------------------------------------------------
. 2020-01-14 13:45:56.856 Connecting to automated.cmosservice.co.uk ...
. 2020-01-14 13:45:56.885 Connected with automated.cmosservice.co.uk, negotiating TLS connection...
< 2020-01-14 13:45:56.904 220 Microsoft FTP Service
> 2020-01-14 13:45:56.904 HOST automated.cmosservice.co.uk
< 2020-01-14 13:45:56.922 220 Host accepted.
> 2020-01-14 13:45:56.922 AUTH TLS
< 2020-01-14 13:45:56.940 234 AUTH command ok. Expecting TLS Negotiation.
. 2020-01-14 13:45:57.175 Server asks for authentication with a client certificate.
. 2020-01-14 13:45:57.283 Verifying certificate for "" with fingerprint and 20 failures
. 2020-01-14 13:45:57.284 Certificate subject alternative name "" matches hostname
. 2020-01-14 13:45:57.345 Certificate verified against Windows certificate store
. 2020-01-14 13:45:57.345 Using TLSv1.2, cipher TLSv1/SSLv3: ECDHE-RSA-AES256-SHA384, 2048 bit RSA, ECDHE-RSA-AES256-SHA384 TLSv1.2 Kx=ECDH     Au=RSA  Enc=AES(256)  Mac=SHA384
. 2020-01-14 13:45:57.346 TLS connection established. Waiting for welcome message...
> 2020-01-14 13:45:57.346 USER anonymous
< 2020-01-14 13:45:57.363 331 Anonymous access allowed, send identity (e-mail name) as password.
. 2020-01-14 13:45:57.364 Server asked for password, but we are using certificate, and no password was specified upfront, using fake password
> 2020-01-14 13:45:57.364 PASS *********
< 2020-01-14 13:45:57.383 230 User logged in.
> 2020-01-14 13:45:57.383 SYST
. 2020-01-14 13:45:57.402 The server is probably running Windows, assuming that directory listing timestamps are affected by DST.
< 2020-01-14 13:45:57.402 215 Windows_NT`
```

**Comment by robinrodricks** [comment]
Thanks for this. Released in 29.0.2.

https://www.nuget.org/packages/FluentFTP/29.0.2

Docs: https://github.com/robinrodricks/FluentFTP#ftp-settings
