### ISSUE TITLE
FtpProgress object for Async Download in WPF App

### ISSUE THREAD

**Issue by Corbieman** [robinrodricks/FluentFTP#512]
**FTP OS:** Windows

**FTP Server:** Windows CE

**Computer OS:** Windows 10 Pro

When i'm trying to create FtpProgress object in my wpf application for async download like this:

` IProgress<FtpProgress> progress = new IProgress<FtpProgress>(x => {
                                                     // When progress in unknown, -1 will be sent
                                                     if (x.Progress < 0)
                                                     {
                                                         UpdateProgressBar.Dispatcher.BeginInvoke((Action)(() => UpdateProgressBar.IsIndeterminate = true));
                                                     }
                                                     else
                                                     {
                                                         UpdateProgressBar.Dispatcher.BeginInvoke((Action)(() => UpdateProgressBar.IsIndeterminate = false));
                                                         UpdateProgressBar.Dispatcher.BeginInvoke((Action)(() => UpdateProgressBar.Value = -1));
                                                     }
                                                 });`

I'm getting error: "Cannot create an instanace of the abstract class or interface 'IProgress<FtpProgress>

**Logs :**

```
<paste logs here but DO NOT delete the lines above and below this line>
```

**Comment by robinrodricks** [comment]
See the sample at : https://github.com/robinrodricks/FluentFTP#faq_progress

**Comment by Corbieman** [comment]
Oh didnt see you have async example there.

But im still getting error in this object:

"Cannot implicitly convert type FluentFTP.FtpProgress to double"

at this line:
`UpdateProgressBar.Value = x;`

**Comment by robinrodricks** [comment]
Look inside the FtpProgress object. All the values you need are in there.
