### ISSUE TITLE
UploadAsync uses unsupported method when provided an HttpContentStream

### ISSUE THREAD

**Issue by FotG** [robinrodricks/FluentFTP#513]
**FTP OS:** Unknown
**FTP Server:** Unknown
**Computer OS:** Unix

Application is Using .Net core 2.1.

When the call to `UploadAsync(Stream fileStream, String remotePath, FtpRemoteExists existsMode, Boolean createRemoteDir, IProgress<FtpProgress> progress, CancellationToken token)` is used with a HttpContentStream, such as a stream from Amazon S3 using the IS3Client, an exception is thrown showing an unsupported method is used on stream.

`System.AggregateException: One or more errors occurred. (Error while uploading the file to the server. See InnerException for more info.) ---> FluentFTP.FtpException: Error while uploading the file to the server. See InnerException for more info. ---> System.NotSupportedException: Specified method is not supported.
   at System.Net.Http.HttpContentStream.get_Length()
   at FluentFTP.FtpClient.UploadFileInternalAsync(Stream fileData, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token)
   --- End of inner exception stack trace ---
   at FluentFTP.FtpClient.UploadFileInternalAsync(Stream fileData, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token)
   at FluentFTP.FtpClient.UploadAsync(Stream fileStream, String remotePath, FtpRemoteExists existsMode, Boolean createRemoteDir, IProgress`1 progress, CancellationToken token)`

**Comment by robinrodricks** [comment]
We don't work with arbitrary streams. Only with ftp servers.

**Comment by FotG** [comment]
Fluent.Ftp provides a method to upload from an "arbitrary" stream. (https://github.com/robinrodricks/FluentFTP/blob/5a8629beaac98d3176e37712ef238719a1d3c469/FluentFTP/Client/IFtpClient.cs#L212) I worked around this error by copying the HttpContentStream provided by the S3 client to a MemoryStream. 

If you only support a few of the implementations of the Stream abstract class, it would be useful to either validate that the object passed in is of a supported type, and if not, throw a better exception message, or make the method signature less generic.

**Comment by robinrodricks** [comment]
As you can see your stream did not support getting the length and so it
crashed.

**Comment by graemejob** [comment]
This method would be very useful for efficiently transferring from http to ftp if it included a length parameter in one of its overloads. 
I got around the limitation by writing a wrapper stream that presents a Length value passed into it that I get from the Content-Length header of the HttpWebRequest, and just exposes the methods and properties of the baseStream for the rest, and it works a treat! 
Would be much nicer if we could just tell Upload/UploadAsync how many bytes to expect from the arbitrary stream though.

**Comment by robinrodricks** [comment]
Graeme, can you add a new issue with this suggestion please?
