### ISSUE TITLE
DeleteDirectory: Directory not empty

### ISSUE THREAD

**Issue by dylanvdmerwe** [robinrodricks/FluentFTP#517]
**FTP OS:** Unknown, third party. 

**FTP Server:** Unknown, third party. 

I upgraded from version 19.1.3 to 29.0.4 and I am having a problem deleting a directory that has folders and files in it. There is nothing in the documentation about this. Is there something I am doing wrong?

Code:
![image](https://user-images.githubusercontent.com/2852839/73545416-fd379f80-4443-11ea-92fa-0073496f1cbf.png)

Directory:
![image](https://user-images.githubusercontent.com/2852839/73545370-e5f8b200-4443-11ea-82a2-516936ef3b83.png)

**Logs :**
```
2020-01-31 07:12:36,656 | ERROR | /27-01-2020/db: Directory not empty | UploadFolderBackupFtp method in file BackupService.cs at line 335
FluentFTP.FtpCommandException: /27-01-2020/db: Directory not empty
   at FluentFTP.FtpClient.DeleteDirInternal(String path, Boolean deleteContents, FtpListOption options)
   at FluentFTP.FtpClient.DeleteDirInternal(String path, Boolean deleteContents, FtpListOption options)
   at FluentFTP.FtpClient.DeleteDirectory(String path)
   at WindowsService.Backup2.BackupService.UploadFolderBackupFtp
```

**Comment by robinrodricks** [comment]
Paste the full FTP logs here so we can debug. See https://github.com/robinrodricks/FluentFTP/wiki/Logging#how-do-i-trace-ftp-commands-for-debugging

**Comment by robinrodricks** [comment]
Paste the full FTP logs here so we can debug. See https://github.com/robinrodricks/FluentFTP/wiki/Logging#how-do-i-trace-ftp-commands-for-debugging

**Comment by robinrodricks** [comment]
Unless you reply we cannot help you.

**Comment by dylanvdmerwe** [comment]
Sorry noted. I reverted back to 19.1.3 in the end.

**Comment by robinrodricks** [comment]
If you can paste the FluentFTP logs of  19.1.3 and of the latest version, then we can compare and fix this behavior.
