### ISSUE TITLE
FtpProgress callback has null values for RemotePath and LocalPath

### ISSUE THREAD

**Issue by royben** [robinrodricks/FluentFTP#520]
The FtpProgress callback has null or zero values for all arguments except the progress of the current file, for both DownloadDirectoryAsync() and UploadDirectoryAsync()

I think it would be nice to also include the overall progress of the whole directory download/upload.

**Comment by robinrodricks** [comment]
Yes these are missing features. Good find. Will implement and let you know.

**Comment by robinrodricks** [comment]
Can you try this and see if it works?

[Release.zip](https://github.com/robinrodricks/FluentFTP/files/4169359/Release.zip)

#### 31.0.0
  - New: All progress tracking now indicates the file index within the entire task, and local & remote path of the file
  - New: `UploadDirectory` and `DownloadDirectory` now supports tracking progress of the entire task 
  - New: `UploadFiles` and `DownloadFiles` now supports tracking progress for both sync/async methods
  - Fix: `UploadDirectory` and `DownloadDirectory` methods added to the `IFtpClient` interface
  - Fix: Correctly determine file exists on servers that don't support SIZE command and return error 550
  - Fix: Support more strings to determine if file exists using SIZE command
