### ISSUE TITLE
Downloading a folder over FTP downloads all files to the root directory

### ISSUE THREAD

**Issue by sighol** [robinrodricks/FluentFTP#521]
**FTP OS:** Windows 

**FTP Server:** Windows 10 built in

**Computer OS:** Windows 10

**Version**: 30.1.0

The following code will download from `Ftp\Source` to my local `C:\` drive instead of `C:\Folder\To\Download\to`.

```csharp
using (var client = new FtpClient("ftp://localhost"))
{
    var result = client.DownloadDirectory(
        @"C:\Folder\To\Download\to", 
        @"Ftp\Source");
}
```

It looks like the error occurs while computing the local file paths here: [FtpClient_FolderDownload][Error line]

```csharp
var relativePath = remoteFile.FullName.Replace(remoteFolder, "")
    .Replace('/', Path.DirectorySeparatorChar);
var localFile = Path.Combine(localFolder, relativePath);
```

The `relativePath` that is received, starts with a leading backslash `\`.
`Path.Combine` will then ignore the `localFolder`.

I have an example on [.NETFiddle](https://dotnetfiddle.net/mRlGTy) that shows the behavior.

The values I have are:

| Variable     | Value                       |
|:-------------|:----------------------------|
| remoteFile   | `/Ftp/Source/MyPicture.JPG` |
| remoteFolder | `Ftp/Source`                |
| localFile    | `MyPicture.JPG`             |

If the FTP source I downloaded from was `\Ftp\Source` instead of `Ftp\Source`,
then the code behaves as expected.

**Logs :**

No logs.

[Error line]: https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Client/FtpClient_FolderDownload.cs#L185

**Comment by robinrodricks** [comment]
Done.

https://www.nuget.org/packages/FluentFTP/30.1.1
