### ISSUE TITLE
ftpClient.download with progress

### ISSUE THREAD

**Issue by CS06** [robinrodricks/FluentFTP#523]
Hello, I've been searching all morning trying to figure out how to download a file with progress.
I can't seem to figure out the correct value for the progress parameter.

I'm using VB.net and would like it to call a Sub named DownloadProgress

I found this code in someone else's question, but couldn't get the ftpClient.Download method to accept it.
`Dim progress = New Progress(Of Double)(AddressOf DownloadProgress)`

If someone could help me out with a quick example I'd really appreciate it!

**Comment by CS06** [comment]
I managed to figure it out.  Here's some working VB code for anyone else having trouble.

```
    Private Sub Download(Item As FtpListItem)
        Dim SaveAs As New SaveFileDialog
        With SaveAs
            .FileName = Item.Name
            .OverwritePrompt = True
        End With

        If SaveAs.ShowDialog = vbOK Then
            Dim Download As Stream = SaveAs.OpenFile
            Dim progress As New Action(Of FtpProgress)(AddressOf DownloadProgress)
            FTP.Download(Download, Item.FullName, 0, progress)
        End If
    End Sub
```

>     Public Sub DownloadProgress(FileProgress As FtpProgress)
>         ProgressBar1.Value = FileProgress.Progress
>         FileLabel.Text = "Downloading: " & FileProgress.RemotePath
>         SpeedLabel.Text = FileProgress.TransferSpeedToString
>         ETALabel.Text = FileProgress.ETA.ToString
>     End Sub

**Comment by robinrodricks** [comment]
Inspired by your issues we now have [VB examples for all methods](https://github.com/robinrodricks/FluentFTP/tree/master/FluentFTP.VBExamples)!
