### ISSUE TITLE
[net core] suspend while calling UploadFile or DownloadFile

### ISSUE THREAD

**Issue by jiabiao** [robinrodricks/FluentFTP#53]
For the .net core version, thread will be suspended about 5 minutes while uploading or downloading file.

``` cshrap
client.DownloadFile("D:\\1.txt", "1.txt");
client.UploadFile("D:\\2.txt", "/2.txt");
```
I am not sure if it's because i am behind the Microsoft ISA Server proxy, but the code works well on .net framework 4.5 . The methods which don't  use data connection work well on .net core.

I will try it again while I get home as there is no need a proxy.

**Comment by jiabiao** [comment]
Reproduce the issue at home, suspend just 5 minutes while uploading, But it's normal when use .net 4.5 .

If you can't reproduce it, i can create a test account of my FTP server for you.

**Comment by hgupta9** [comment]
Can you help fix this issue? I don't have much experience with .NET core.

**Comment by jiabiao** [comment]
I will have a try. 
I'm not familiar with FTP protocol and don't have more free time on this.  So it may take some time.

**Comment by jiabiao** [comment]
@hgupta9 
The GetReply method is called twice for .net core version.  [first](https://github.com/hgupta9/FluentFTP/blob/master/FluentFTP/FtpClient.cs#L2290) [second](
https://github.com/hgupta9/FluentFTP/blob/master/FluentFTP/FtpClient.cs#L2295)
There is no any response from the server after first call , so it suspend on the FtpSocketStream.Read method.

It should be a bug for the full framework version,  downStream.Dispose() should call FtpDataStream.Dispose(bool disposing) which will call the GetReply  method. But due to this bug, both the Dispose and Close method of FtpDataStream have never been called.

Expected call stack:
downStream.Dispose()  -> Stream.Dispose() -> FtpDataStream/FtpSocketStream/Stream.Close() (must with base.Close())-> FtpDataStream/FtpSocketStream/Stream.Dispose(bool disposing) (must with base.Dispose(disposing))

Actual call stack:
downStream.Dispose()  -> Stream.Dispose()  -> ~~FtpDataStream.Close~~(it's overwrite method,with new keyword, so will not be call)  --> FtpSocketStream.Close (**without base.Close()**, so follow methods will not be called)  --> ~~Stream.Close~~ --> ~~Dispose(bool disposing)~~

the close/dispose are very confusing, so .net core remove the close method. that is why downStream.Dispose() take effect and call the GetReply().

**Comment by hgupta9** [comment]
Great work debugging that! I'll try fixing it as soon as I have the time...

**Comment by jiabiao** [comment]
I suggest move all the code in  `override void close() `to `override void Dispose(bool disposing)` , and replace all `Close() ` to `Dispose()`.   Remove the manual call `FtpReply status = GetReply();` at [FtpClient Line 2295](https://github.com/hgupta9/FluentFTP/blob/master/FluentFTP/FtpClient.cs#L2295)

So that the .net core and full .net framework share the same code.

**Comment by hgupta9** [comment]
Can you please check if this works for you?

https://we.tl/OwKxwmInPj

**Comment by jiabiao** [comment]
download works fine.
upload file got this error:

FluentFTP.FtpException was unhandled
  HResult=-2146233088
  Message=Malformed PASV response: Switching to Binary mode.
  Source=FluentFTP
  StackTrace:
       at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
       at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
       at FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
       at FluentFTP.FtpClient.FileExists(String path, FtpListOption options)
       at FluentFTP.FtpClient.UploadFile(String localPath, String remotePath, Boolean overwrite, Boolean createRemoteDir, Boolean checkFileExistance)
       at CodePieces.FTPDemo.Run() in D:\Code\demo\netcore\CodePieces\src\CodePieces\FTPDemo.cs:line 37
       at CodePieces.Program.Main(String[] args) in D:\Code\demo\netcore\CodePieces\src\CodePieces\Program.cs:line 13
  InnerException:

**Comment by jiabiao** [comment]
I have test the latest version, this issue has been fixed.

**Comment by robinrodricks** [comment]
Excellent. Must thank @artmchi for the fix.
