### ISSUE TITLE
Auto detect Azure servers and use working settings

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#533]
**FTP OS:** Windows

**FTP Server:** IIS on Azure

Azure is wierd. Azure is unreliable. To fix it you must connect with these settings (reported by [royben](https://github.com/robinrodricks/FluentFTP/issues/71#issuecomment-582915692))

    FtpClient client = new FtpClient(host, userName, password);
    client.SslProtocols = SslProtocols.Tls;
    client.ValidateAnyCertificate = true;
    client.DataConnectionType = FtpDataConnectionType.PASV;
    client.DownloadDataType = FtpDataType.Binary;
    client.RetryAttempts = 5;
    client.SocketPollInterval = 1000;
    client.ConnectTimeout = 2000;
    client.ReadTimeout = 2000;
    client.DataConnectionConnectTimeout = 2000;
    client.DataConnectionReadTimeout = 2000;

Thus we should automatically detect Azure connections and auto conf to use those settings as default.

> It seems that all azure web apps publish profiles FTP addresses ends with:
> **ftp.azurewebsites.windows.net**

**Comment by Jehoel** [comment]
> It seems that all azure web apps publish profiles FTP addresses ends with:
ftp.azurewebsites.windows.net

This is only true for Azure App Services (f.k.a. Azure Websites) in the main Azure cloud - [there's also:](https://github.com/Azure/portaldocs/blob/master/portal-sdk/generated/portalfx-deployment-sovereign.md) which will all have different URIs.

- "Blackforest" ([Azure Germany](https://docs.microsoft.com/en-us/azure/germany/))
    * Annoyingly, [the Endpoint listings page](https://docs.microsoft.com/en-us/azure/germany/germany-developer-guide) doesn't mention App Services.
- "Mooncake" (Azure PRC)
    * Good luck finding information on this!
- "Fairfax" (Azure US Government)
    * ...and this!
- On-prem Azure, aka Azure Stack - I don't know if this includes on-prem Azure App Services, however.

I might suggest contacting Azure support to get information for this.

**Comment by robinrodricks** [comment]
Done. Released in 31.3.1

  - New: `AutoDetect` and `AutoConnect` now auto-configure for Azure FTP servers using known connection settings
  - Improve code generation of `FtpProfile` to use LoadProfile rather than setting each property individually
  - Add advanced Timeout and Socket settings to `FtpProfile` for Azure auto configuration
  - Fix: All exception classes now inherit from `FtpException`
  - All exceptions and `FtpProfile` are now serializable in .NET Framework
