### ISSUE TITLE
How use FluentFTP copy file or folder?

### ISSUE THREAD

**Issue by zuoxianwei** [robinrodricks/FluentFTP#535]
**FTP OS:** Unix / Windows / Embedded

**FTP Server:** Pure-FTPd / DrFTPD / Vsftpd / ProFTPD / Vax / VMS / OpenVMS / Tandem / HP NonStop Guardian / IBM OS400 / AS400 / Windows CE

**Computer OS:** ?

**FluentFTP Version:** ?

<write details about your bug report / feature request here>

**Logs :**

```

<paste logs here>

how use fluentFtp copy file or folder? I can't find that method in source code

**Comment by robinrodricks** [comment]
Download and then Upload.

**Comment by robinrodricks** [comment]
See https://github.com/robinrodricks/FluentFTP/issues/537
