### ISSUE TITLE
Unable to get the creation time of the file accurately

### ISSUE THREAD

**Issue by zuoxianwei** [robinrodricks/FluentFTP#536]
**FTP OS:** Unix / Windows / Embedded

**FTP Server:** Pure-FTPd / DrFTPD / Vsftpd / ProFTPD / Vax / VMS / OpenVMS / Tandem / HP NonStop Guardian / IBM OS400 / AS400 / Windows CE

**Computer OS:** ?

**FluentFTP Version:** ?

<write details about your bug report / feature request here>

**Logs :**

```

<paste logs here>

When I use the FtpClient.GetObjectInfo(fileName,false) method to get the file information, I cannot get the correct creation time.I would appreciation if you can help me!

**Comment by robinrodricks** [comment]
Creation time is not sent as per my knowledge. Only modified time is sent on FTP.

**Comment by robinrodricks** [comment]
As you can see here there is no command for getting file creation date in FTP

https://github.com/robinrodricks/FluentFTP/wiki/FTP-Support
