### ISSUE TITLE
Duplicate file or folder on the server

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#537]
We don't currently support copying a file or folder from the server to another path on the same server.

1. Upload/Download methods are the only way to do this but it creates an unwanted copy on disk.
2. Rename/Move methods don't create a copy.
3. TransferFile and TransferDirectory are when you want to transfer from one server to another.

**Proposed fix:**

New API required - **DuplicateFile** and **DuplicateDirectory** which will create a copy of a file or folder from one path to another path on the same server

**Comment by christiandiguida** [comment]
``Hi. I just want to report what I believe to be a bug inside fluentFtp. When download and upload a directory (as there is not a duplicate folder method at the moment) there is a loss of files. I am downloading and uploading a folder with 230 files and directories and after many tests i saw that I was duplicating a folder with less files. 

To resolve this, you need to download and upload a number of times with FtpFolderSyncMode.Update until you don't get the right number of files. This is the code I used to resolve the issue. I hope it can help.

`

    Public Shared Sub DuplicateDirectoryFTP(ftpClient As FtpClient, remoteDirToBeDuplicatedPath As String, localDuplicatedDirPath As String, remoteDuplicatedDirPath As String)
        Dim remoteTotalOfFilesDirToDuplicate As Integer = 0
        Dim numOfLocalFiles As Integer = 0
        Dim numOfLocalDirs As Integer = 0
        Dim localTotalDuplicatedDir As Integer = 0
        Dim remoteTotalOfFilesDuplicatedDir As Integer = 0
        Try
            Do
                remoteTotalOfFilesDirToDuplicate = ftpClient.GetListing(remoteDirToBeDuplicatedPath, FtpListOption.Recursive).Length
                ftpClient.DownloadDirectory(localDuplicatedDirPath, remoteDirToBeDuplicatedPath, FtpFolderSyncMode.Update)
                numOfLocalDirs = My.Computer.FileSystem.GetDirectories(localDuplicatedDirPath, FileIO.SearchOption.SearchAllSubDirectories).Count
                numOfLocalFiles = My.Computer.FileSystem.GetFiles(localDuplicatedDirPath, FileIO.SearchOption.SearchAllSubDirectories).Count
                localTotalDuplicatedDir = numOfLocalDirs + numOfLocalFiles
            Loop Until localTotalDuplicatedDir = remoteTotalOfFilesDirToDuplicate
            Do
                ftpClient.UploadDirectory(localDuplicatedDirPath, remoteDuplicatedDirPath, FtpFolderSyncMode.Update)
                remoteTotalOfFilesDuplicatedDir = ftpClient.GetListing(remoteDuplicatedDirPath, FtpListOption.Recursive).Length
            Loop Until localTotalDuplicatedDir = remoteTotalOfFilesDuplicatedDir
            My.Computer.FileSystem.DeleteDirectory(localDuplicatedDirPath, FileIO.UIOption.AllDialogs, FileIO.RecycleOption.SendToRecycleBin, FileIO.UICancelOption.ThrowException)
        Catch ex As Exception
            Throw ex
        End Try
    End Sub`

**Comment by robinrodricks** [comment]
Added to the [bucket list](https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans). We will pick this up as and when we have free time. Comment on this issue if you want us to prioritize it. Thanks!
