### ISSUE TITLE
UploadFile() returns the wrong value when skipping file

### ISSUE THREAD

**Issue by inside686** [robinrodricks/FluentFTP#538]
Windows
FileZilla
Windows 10
v31.3.2

When calling UploadFile() with FtpRemoteExists.Skip and the file actually exists on the Server, FtpStatus.Failed is returned instead of FtpStatus.Skipped.

**Comment by robinrodricks** [comment]
Good find!

**Comment by robinrodricks** [comment]
Can you try the latest release **32.0.0**:

https://www.nuget.org/packages/FluentFTP/32.0.0

**Comment by inside686** [comment]
Works as intended in 32.1.0

**Comment by robinrodricks** [comment]
Awesome!
