### ISSUE TITLE
TransferSpeedToString() wrong format

### ISSUE THREAD

**Issue by inside686** [robinrodricks/FluentFTP#540]
Windows
FileZilla
Windows 10
v32.1.0

FtpProgress.TransferSpeedToString() now returns value formated this way:
"45.77{0} KB/s"

Obviously the {0} should not be there.

**Comment by robinrodricks** [comment]
This community is amazing.

Fixed in 32.1.1

https://www.nuget.org/packages/FluentFTP/32.1.1
