### ISSUE TITLE
Doesn't work with Russian characters

### ISSUE THREAD

**Issue by veliev** [robinrodricks/FluentFTP#541]
When connecting to ftp, Russian characters are not read. There is no way to follow the path with Russian characters. 
Read list
upload
```
usr
???
?????????
????
??????
??????
?????
```
Can I get around this?

**Comment by robinrodricks** [comment]
Try https://github.com/robinrodricks/FluentFTP/wiki/File-Transfer#how-can-i-uploaddownload-files-with-unicode-filenames-when-my-server-does-not-support-utf8

**Comment by veliev** [comment]
> Try https://github.com/robinrodricks/FluentFTP/wiki/File-Transfer#how-can-i-uploaddownload-files-with-unicode-filenames-when-my-server-does-not-support-utf8

Wow. Thanks, this solved all my problems.
