### ISSUE TITLE
Very Low Speed Download : Compare With CuteFtp

### ISSUE THREAD

**Issue by adelhoss** [robinrodricks/FluentFTP#543]
Hello My Friends
I Use Your Very Good Library
I Tested DownloadFileAsync Method : Max My Speed Is 100 Kb/s
Please See ScreenShot From This StatusBar I Wrote My Application :
[MyApplication ScreenShot](https://www.mediafire.com/convkey/9b7b/nwc6fy28wyye98czg.jpg)
I Tested Same Server Same File With CuteFtp And Download Speed Is : 1.1 Mb/s
[CuteFtp Same Server SameFile Speed](https://www.mediafire.com/convkey/7350/hyn11t9d1fyywj7zg.jpg)
Please Help Me For Faster Download
Thx My Friends

**Comment by adelhoss** [comment]
I Tested With Internet Download Manager Speed Download is : 1.53 Mb/s 
Please See Screen Shot
[InternetDownloadManager Speed Same File Same Server](https://www.mediafire.com/convkey/6537/tyx5g0ohkon23bfzg.jpg)
Same File Same Server
I Set TransferChunkSize With This Code To 4MB :
` client.TransferChunkSize = 4194304;
`
But No Change ....

**Comment by adelhoss** [comment]
This is My Log Download :
```
#OpenReadAsync("/public_html/movies/Mad.Max.Fury.Road.2015.720p.BrRip.MkvCage.FilmZone.mkv", Binary, 0)
Command:  TYPE I
Response: 200 TYPE is now 8-bit binary
# GetFileSizeAsync("/public_html/movies/Mad.Max.Fury.Road.2015.720p.BrRip.MkvCage.FilmZone.mkv")
Command:  SIZE /public_html/movies/Mad.Max.Fury.Road.2015.720p.BrRip.MkvCage.FilmZone.mkv
Response: 213 1130065347

# OpenPassiveDataStreamAsync(AutoPassive, "RETR /public_html/movies/Mad.Max.Fury.Road.2015.720p.BrRip.MkvCage.FilmZone.mkv", 0)
Command:  EPSV
Response: 229 Extended Passive mode OK (|||61603|)
Status:   Connecting to 185.141.168.50:61603
Command:  RETR /public_html/movies/Mad.Max.Fury.Road.2015.720p.BrRip.MkvCage.FilmZone.mkv
Response: 150-Accepted data connection
Response: 150 1103579.4 kbytes to download
Status:   Disposing FtpSocketStream...

# Dispose()
Status:   Disposing FtpClient object...
Status:   Testing connectivity using Socket.Poll()...
Status:   There is stale data on the socket, maybe our connection timed out or you did not call GetReply(). Re-connecting...
Status:   The stale data was: 150 103.144 seconds (measured here), 107.97 Kbytes per second
Status:   Disposing FtpSocketStream...
Status:   Not sending QUIT because the connection has already been closed.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
```

**Comment by adelhoss** [comment]
I Set DownloadRateLimit to 4094Kb = 4Mb
But No Change ...
` client.DownloadRateLimit = 4096;
`

**Comment by robinrodricks** [comment]
This is a good point. Its been reported by many people. Not sure how to fix it, let me try something and Ill get back to you.

**Comment by adelhoss** [comment]
Thank you Friend .

**Comment by robinrodricks** [comment]
Are you using FTPS or FTP? Which connection mode? Can you paste your connection settings?

**Comment by adelhoss** [comment]
Yes I Use ConnectionType : EPSV
```
client.TransferChunkSize = 99999999;
uint itemp = client.DownloadRateLimit;
 client.DownloadRateLimit = 99999999;
client.NoopInterval = 0;
client.DataConnectionType = FtpDataConnectionType.EPSV;
```

**Comment by adelhoss** [comment]
My Poblem Is Solved 
See ScreenShot I Increase TransferChunkSize And DownloadRateLimit
[ScreenShot My Application Speed Download](https://www.mediafire.com/convkey/5797/ytsgigm5tfo89v8zg.jpg)
My Speed Is Now Up To 1.6 MB/s
Thank you .

**Comment by robinrodricks** [comment]
Can you tell the values you are using?

Try with `DownloadRateLimit = 0` that means unlimited.
