### ISSUE TITLE
Incomplete files uploaded with UploadFile API

### ISSUE THREAD

**Issue by adelhoss** [robinrodricks/FluentFTP#544]
Hello My Friend I Use Latest Version : 32.2.0
I Upload Mp4 File With Size : 4.5 MB after I Checked Only 1.5Mb Is Uploaded Why ?
Please See First ScreenShot My Code I Use UploadFileAsync Method :
[My Code Screenshot](https://www.mediafire.com/convkey/c4b2/2ey7p4ooqyda5hjzg.jpg)
above Method Return Success FtpStatus But Check Uploaded File Only Upload 1.5 Mb of File :
[ScreenShot Uploaded File Result](https://www.mediafire.com/convkey/9db6/t0p6l9hczo2dgcwzg.jpg)
Screen Shot From My File Explorer For Real Size is 4.31 MB
[Real File Size](https://www.mediafire.com/convkey/34c2/64z9oebihsg028rzg.jpg)
My Log When Upload Is :
```
# UploadFileAsync("C:\a.mp4", "/public_html/movies/a.mp4", NoCheck, False, None)
# OpenWriteAsync("/public_html/movies/a.mp4", Binary)
Status:   Testing connectivity using Socket.Poll()...
# OpenPassiveDataStreamAsync(EPSV, "STOR /public_html/movies/a.mp4", 0)
Command:  EPSV
Response: 229 Extended Passive mode OK (|||56927|)
Status:   Connecting to 185.141.168.50:56927
Command:  STOR /public_html/movies/a.mp4
Response: 150 Accepted data connection
Status:   Disposing FtpSocketStream...

```
Please Help Me My Friend
Thank you .

**Comment by adelhoss** [comment]
I Tested All Upload Muthod Such As : UploadFile , UploadFileAsync,UploadAsync
All Upload Method Only Uploaded 1.5MB Of File

**Comment by adelhoss** [comment]
I tested with async and await but no change . Any time try only 1.4 mb to 1.5 mb only uploaded . Please help me friends .

**Comment by adelhoss** [comment]
Please Help I am Waiting For Supporter ....

**Comment by robinrodricks** [comment]
Since nothing is working just trying using the stream API.

```
var fileData = ?; // open file stream
var buffer = new byte[256];
int readBytes;
using (var upStream = client.OpenWrite("<path>", FtpDataType.Binary){

	while ((readBytes = fileData.Read(buffer, 0, buffer.Length)) > 0) {
		// write chunk to the FTP stream
		upStream.Write(buffer, 0, readBytes);
		upStream.Flush();
	}
}
```

Or:
```
var fileData = ?; // open file stream
using (var upStream = client.OpenWrite("<path>", FtpDataType.Binary){

	// write full file to the FTP stream
	upStream.Write(fileData, 0, fileData.Length);
	upStream.Flush();
}
```

**Comment by robinrodricks** [comment]
I don't see any bug here.
