### ISSUE TITLE
FileExtention in the CSharpExamples should contain dot

### ISSUE THREAD

**Issue by Halomicro** [robinrodricks/FluentFTP#545]
Hi, I am a new C# guy learning from CSharpExamples, I need DownloadDirectoryWithRules in the CSharepExamples, and find out when I follow that example without adding dot in the FileExtention, such as xlsx, I couldn't get any files from my server. Until I tried 
```
Path.GetExtension("MyFile.xlsx").ToLower();
```
and it shows .xlsx, so I change rules as below to get my files finally. Pls update the content in the CSharpExamples so they won't mislead other news such as me.
```
var rules = new List<FtpRule>{
   new FtpFileExtensionRule(true, new List<string>{ ".xlsx" }),
};
```

**FTP OS:** CentOS 7.6.1810

**FTP Server:** Vsftpd 3.0.2

**Computer OS:** Windows 10 x64

**FluentFTP Version:** v32.2.0

<write details about your bug report / feature request here>

**Logs :**

```

<paste logs here>

```

**Comment by robinrodricks** [comment]
I'll do you one better. I've fixed `FtpFileExtensionRule` as it was failing to compare extensions unless they were prefixed with a dot. Now the examples are valid :)

https://www.nuget.org/packages/FluentFTP/32.2.1
