### ISSUE TITLE
Dismiss enums and favor strategies instead for FTP server specific support

### ISSUE THREAD

**Issue by Adhara3** [robinrodricks/FluentFTP#549]
Hi, 

this is not an issue, it'a refactoring proposal. The code is full of enums, especially for server type. This works but make very hard to extend fo two reasons:
* enum values cannot be injected
* code is full of ifs in different places and it is not clear what every server is supposed to differ at

My suggestion is to switch to `IServerStrategy` interface instead. This would allow standard users to work the same way (internally you identify a server the same way but you instantiate a class) but whoever has to work on a non standard server can just inject a custom `IServerStrategy` implementation. Moreover, `IServerStrategy` methods would also provide a list of things that differ from server to server.
This is not a small job and I could eventually have a look. But before even starting a branch/pull request I would like to know if you like that approach or not, just not to waste anybody's time.

Honestly a similar approach may also apply to logging, response parsers and some flags we currently pass in download/upload methods may also become part of server's strategy (but we can discuss about that). Static and enums have similar pros & cons after all.

Let me know, thanks
A

**Comment by robinrodricks** [comment]
1. I'm not sure what you want to "extend".

2. The whole library is generic, that is, it works with all servers with no differences. 
We have some server specific code in the classes named "server specific" but even that is optional, and only to support some special features and to disable some known unsupported features on a server to server basis.

3. Enum values cannot be injected - Elaborate please. Would it help if all enums had ToInt and FromInt methods that you could call? Or if all enums extended int and had specific values.

4. Code is full of ifs in different places and it is not clear what every server is supposed to differ at. - Again, cannot understand what you mean. In order to support different enum values of course we need conditions all over the place.

5. Personally I don't like unnecessary "patterns" and I try to keep away from unnecessary bloat and complexity in order to make it simple for everyone to use. Enums are not as evil as you portray. In fact they are universally understood, easy to log (just call ToString) and easy to debug. If you need more features I would be more include to extend our enum system rather than switch to strategies. Perhaps if you show a compelling example it would be better.

**Comment by Adhara3** [comment]
Hi,

thanks for the reply.

My scenario is the following: we are communicating with a custom non standard FTP server, one that basically is not recognised by your code because it does not fall in any known type. Fair enough. Many things are not working as expected and it's very hard to understand what is going wrong. (some examples: file size not supported, absolute path not supported, custom parsers, etc...) 
When I talk about "extending" I mean this: being able to provide my own server spec to FluentFTP. As of today I can't. What I mean is very similar to what you can do with custom parser.

I understand that you may be more interested in covering standard cases, I will then just send a couple of pull requests to be able to tweak the behaviour in a couple of places. 
This is a reasonable requirement, this is why I was asking before doing the job.

Thanks a lot
A

**Comment by robinrodricks** [comment]
This is interesting and weird. The FTP spec allows you to perform all
operations on any server. We don't actually need server specific code. But
to address this, perhaps I can implement the FtpServer system I was talking
about. Let me know if that would fix it for you. It would allow you to then
define a custom server class in which you can implement any server specific
functionality. And testing with your live use case we can perfect the
implementation.

**Comment by robinrodricks** [comment]
Do you need that?

**Comment by Adhara3** [comment]
Hi, 

yes we can try, but if you prefer I can just push something on a branch and then just show you.
I do not want to make you work on something not critical for you. It's pretty clear to me what you suggest.

Let me know.

Thanks
A

**Comment by robinrodricks** [comment]
Let me have a go, if it's not satisfactory then you can try.

**Comment by robinrodricks** [comment]
[FluentFTP.32.3.0.zip](https://github.com/robinrodricks/FluentFTP/files/4375462/FluentFTP.32.3.0.zip)

Have a go:

1. Create a new class extending `FluentFTP.Servers.FtpBaseServer`. For examples you can look [here](https://github.com/robinrodricks/FluentFTP/tree/master/FluentFTP/Servers/Handlers).
2. After creating your FtpClient, set `client.ServerHandler = new YourFtpServer();`
3. (For implementing custom parser I'll have to check and let you know, this is an [old example](https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP.CSharpExamples/CustomParser.cs))
4. Viola!

**Comment by robinrodricks** [comment]
Since you're not responding, I'll close this. If you need something add another issue.

Released in https://www.nuget.org/packages/FluentFTP/32.3.0

**Comment by robinrodricks** [comment]
https://github.com/robinrodricks/FluentFTP/wiki/Custom-Servers

**Comment by Adhara3** [comment]
I'm sorry @robinrodricks, I currently do not have access to my code because of the pandemic shutdown. I will have a look at your code but I won't be able to test it thoroughly for at least another week.
Sorry for that, it's really beyond me.

Thanks for now, I'll come back back to you ASAP
Take care
A

**Comment by Adhara3** [comment]
Hi,

I had a look at the code, looks promising.
I am a bit surprised that you had to keep the `FtpServer` enum and the boilerplate to switch from implementation to enum itself. Isn't that a bit risky? My points on this:

- You now have both `ServerHandler` and `ServerType`. Isn't that a bit redundant?
- What should be returned from `ToEnum()` for custom classes? The only currently usable value is Unknown, but does that make sense?
- If you want to keep the enum values for the reasons explained previously in your post (especially for utils methods like `DetectFtpServer `and `DetectFtpServerBySyst`) then I would add another enum value called `Custom` (to be used in custom Server implementations) to differentiate from `Unknown` and I would also map the `Client.ServerType` property to return `Client.ServerHandler.ToEnum()` (and remove the m_serverType field)
- I would also make sure that internally you do not rely on the enum value anymore. I checked and currently that's the case, for the future be careful because each time you end up writing `if(ServerType == xxx)` or similar then you should probably add a method on FtpBaseServer instead. Completely remove the enum would make this obvious.

For the same reasons as above, the fact that the method `FtpBaseServer.GetParser()` returns an enum value is strange. What should be used in custom server implementations with custom parsers? If you do not want to create other classes/interfaces (e.g. IParser) and transform current static parser classes into non static ones, a shortcut could be to let `GetParser()` return a `Parser` delegate (that already exists). 
The final question on parser is: how are the parsers are selected? Is it done via the `FtpListParser.Init()` using FtpOperatingSystem or via the `FtpBaseServer` implementation? And is there a relationship between Server type and operative system or are they independent? 

(I fear the fact that `FtpListParser` is half static and half non-static is the limit here)

I just want to be clear on a point. _You_ own the library and _you_ decide the design, of course. My scenario is very custom and if you decide that your lib goal is to work in known scenarios only, well that would be fair enough. Please do consider my points as suggestions to make the library extensible, i.e. to be used outside standard scenarios by injecting behavior. If you are not interested in going down this path, it's fine, I'll find another way. 

Thank you very much for your help, as I said I will be able to test this in a production environment in 10 days (hopefully). Sorry for that, pandemic is making everything hard as hell. 

Stay safe, cheers
A

**Comment by robinrodricks** [comment]
I knew about the enum/class mess but I retained the enum as I wanted to
keep these changes backward compatible. I'm not sure how many users have
already coded against the enum values so I had to retain those. In many
places I was just lazy (the DetectServer methods) and those could
definitely use some improvement. I have a policy of "release early, release
often" so changes can always be done.

For custom classes, we could have custom or for now just don't implement
the ToEnum method.

I have no issues with your suggestions. They are all good. I know the
parsing code is a total mess. There are a couple of old/legacy routines and
a couple of new ones. I could just delete the old ones since no one in
their right mind would be using those.

And yes if you are happy with this server class structure I could very well
use the same system for parsers as well. Custom parsing is not well thought
of and there is no proper way to do it atm. Some old legacy code exists but
I doubt is even working properly.

No need to get dramatic (going down another path lol), I find your
suggestions very intresting and helpful.

**Comment by Adhara3** [comment]
Hi, 

ok then let me know if I can help somehow.

I'll keep you posted with my tests anyway.

Thanks
A

**Comment by robinrodricks** [comment]
Just for my info, what is this for? Are you running a custom server at your company or is this custom hardware?

**Comment by Adhara3** [comment]
Hi, 

this is a custom hardware with embedded legacy system that originally had a custom operative system too. 
Now it's linux based but all the application stack has been ported as is. The FTP layer is among this app layers and thus is still the legacy one. There are some plans to migrate to default Linux FTP but is not an obvious step because:

1. The application logic is currently tightly coupled with FTP part
2. FTP is not only _file transfer protocol_ here, it has been used as _file system management protocol_
3. FTP protocol has been taken as a starting point. Many standard commands are not supported, custom ones has been added (e.g. if you send start/stop command on FTP the device starts or stops itself)

So, there nothing standard here. Please also consider that I have no control on hardware (i.e. server) development, I work on the client part so I have to adapt. 
From a client perspective we were currently using a .NET FWK 2 FTP Client implementation that has been tweaked here and there to make it work with the custom server. It was slow, convoluted, hard to maintain, threading nightmare. 
This is why we gave FluentFTP a try. The good news, this is working out of the box for 90% of stuff. We just had a couple of glitches here and there:

1. `SIZE` command is not supported by the server. Because of this, we were struggling with File transfer percentage & size (that I fixed with some pull requests). In my scenario (but I don't expect you to implement it, I'm just giving you the full picture of my reasoning) the `GetFileSize()` was one the the possible methods of `FtpBaseServer`. My idea of _injecting behaviour_ came from here.
2. The custom server does not work with absolute paths, thus to get file info (e.g. the size) the command `LIST root/folder/readme.txt` does not work because of the server, but `LIST readme.txt` does not work either because of FluentFTP that forces absolute path
3. File list parsing is of course custom too. We have all the regex in place and were able to inject the parser with currently available methods but, as we discussed above, there is some room for enhancement (e.g. we have 2 parsers, one for dir and one for files, but we cannot add both because only the last one is saved as custom, so we had to implement a sort of _composite delegate_ that internally manages both scenarios). It works, but in order to make it work I had to dig into FluentFTP code to see internals and this is a hint of something going wrong
4. Logging. As for parsers, we have logging working but yeah, the static logging + trace listener does not help. It works, but as you said there is room for improvement (but it works! ;) )

At the end of the day, the proposal to make Server a class is because it was helpful for me, for anybody in a similar situation but for you too if you need to add servers in the future it should be easier to identify were you need to investigate for custom behaviours.

Hope this clarifies the full scenario

Thanks
A

**Comment by Adhara3** [comment]
Hi,

a quick note. I did not give you any feedback because we are not back to work yet. The expected date is May, 22nd.

I'll keep you posted as soon as I have the chance to test it.

Cheers
A

**Comment by robinrodricks** [comment]
@Adhara3 

All your 4 points are good.

1. Okay.
2. I can add a setting to enable relative paths. It will be beta but you can help smoothen it.
3, Okay, again I can cleanup our internal parsing routines and shift it into the base class.
4. Okay, again, can be improved, suggestions welcome.

**Comment by Adhara3** [comment]
Hi,

I finally had time to try out your solution with 33.0. I followed the docs but no method in my custom server are actually called.
Maybe the bug is here, in the Connect()

```cs		
// Set a FTP server handler if a custom handler has not already been set
if (ServerHandler != null) {
    ServerHandler = FtpServerSpecificHandler.GetServerHandler(m_serverType);
}
```
should be
```cs		
// Set a FTP server handler if a custom handler has not already been set
if (ServerHandler == null) {
    ServerHandler = FtpServerSpecificHandler.GetServerHandler(m_serverType);
}
```

Thanks
A

**Comment by robinrodricks** [comment]
Thanks. Check if it works? 

[FluentFTP_33.0.1.zip](https://github.com/robinrodricks/FluentFTP/files/5406575/FluentFTP_33.0.1.zip)

**Comment by Adhara3** [comment]
Hi,

looks fine, it works as expected now.
Just as a review/suggestion on minor stuff:

1. Still a bit tricky to manage the parser: the server returns an enum value and if custom then it takes the CustomParser property on the client. It would probably be leaner if the server returned the parser directly
2. The logger with the callback is way better than before, just wondering why an Action and not an interface with methods that reflect the available logger levels

Thanks a lot, this is great job

A

**Comment by Adhara3** [comment]
> Just for my info, what is this for? Are you running a custom server at your company or is this custom hardware?

I just found out that our server ignores FEAT but responds to... HELP.... This is the kind of stuff I'm dealing with....

**Comment by robinrodricks** [comment]
1. For the parser, simply set `client.CustomParser = whatever` and it will automatically change the enum value.
2. Logging is a mess and needs to be modernized

**Comment by robinrodricks** [comment]
Released. https://www.nuget.org/packages/FluentFTP/33.0.1

We will make more improvements to handle your case. Its an interesting one.

**Comment by Adhara3** [comment]
> 1. For the parser, simply set `client.CustomParser = whatever` and it will automatically change the enum value.
Yep, nevertheless, it's in two places which is confusing

> 2. Logging is a mess and needs to be modernized
Let me know if you need some help, I would be glad to help

Cheers
A

**Comment by robinrodricks** [comment]
If you can suggest a better pattern for logging, it would be good. A way to integrate with NLog and friends without actually including a reference to it.

**Comment by Adhara3** [comment]
The easiest thing is to define

```
public interface IFluentFtpLogger
{
    void Debug(string message); //or Verbose() if you prefer
    void Info(string message);
    void Warning(string message);
    void Error(string message);
    void Error(string message, Exception ex);
}

public class NullFluentFtpLogger
{
    void Debug(string message){} //or Verbose() if you prefer
    void Info(string message){}
    void Warning(string message){}
    void Error(string message){}
    void Error(string message, Exception ex){}
}
```

Your internal default is the null, if someone injects one you use it. It's very easy for anyone to wrap a NLog, log4net or whatever logger into a `IFluentFtpLogger` and you do not have to bother about dependencies.
If you want to be nice with people, you could provide some implementations like `CompositeFluentFtpLogger` for using more than one logger or `TraceFluentFtpLogger` which basically send out on Trace (I'm just suggesting stuff that does not require external deps).

Or were you thinking about something more IoC/DI?

Cheers
A

**Comment by robinrodricks** [comment]
This is good. I'll look into this.

**Comment by robinrodricks** [comment]
Split out - https://github.com/robinrodricks/FluentFTP/issues/753
