### ISSUE TITLE
DownloadFile deletes local file on error

### ISSUE THREAD

**Issue by TomB2** [robinrodricks/FluentFTP#552]
**FTP OS:** Windows

**FTP Server:** IIS

**Computer OS:** Windows10

**FluentFTP Version:** 32.2.2.0

First of all: Great job. Its a very easy to use and powerfull library.

When calling FtpClient.DownloadFile(localFilePath, ftpFilePath) with a non-existing file in "ftpFilePath"
the function returns an error (that's OK) but it truncates existing "localFilePath".

When using "FtpLocalExists.Overwrite" (default for above call) the local file should not be touched
until transfer begins.

Steps to reproduce:
ftpClient.UploadFile(@"C:\Test\file.txt", "/someDir/file.txt");
ftpClient.DownloadFile(@"C:\Test\file.txt", "/someDir/file_no_exist.txt");

**Comment by robinrodricks** [comment]
What do you mean? it destroys your local path file to 0 kb?

And thanks for the compliments!

**Comment by TomB2** [comment]
Exactly.IMHO the local file should not be touched prior to the first byte being received from ftp.The compliments honest. Really appreciate your work. Am 24.03.20, 12:25 schrieb Robinicks <notifications@github.com>:

   
  What do you mean? it destroys your local path file to 0 kb? 
  And thanks for the compliments!

**Comment by robinrodricks** [comment]
What is the use case of this? Are you trying to preserve a local file if download failed?

**Comment by robinrodricks** [comment]
A quick fix is test for file existence on the server before downloading.

**Comment by robinrodricks** [comment]
Does this work?

[FluentFTP.32.3.0.zip](https://github.com/robinrodricks/FluentFTP/files/4388344/FluentFTP.32.3.0.zip)

**Comment by TomB2** [comment]
Would work. Thanks.

This directly raises a FileNotFoundException.

Would be great to get it as NuGet, too

You can close the issue.

 
 

Gesendet: Donnerstag, 26. März 2020 um 17:13 Uhr
Von: "Robinicks" <notifications@github.com>
An: robinrodricks/FluentFTP <FluentFTP@noreply.github.com>
Cc: TomB2 <Tom.Becker@gmx.org>, Author <author@noreply.github.com>
Betreff: Re: [robinrodricks/FluentFTP] DownloadFile deletes local file on error (#552)


 

Does this work?

FluentFTP.32.3.0.zip

**Comment by robinrodricks** [comment]
Cool.

https://www.nuget.org/packages/FluentFTP/32.3.0

**Comment by robinrodricks** [comment]
You'll need to set `client.DownloadZeroByteFiles = false` if you use a updated release.
