### ISSUE TITLE
FTPClient Failed to get list from one PC and success from another PC

### ISSUE THREAD

**Issue by SahaGoutam** [robinrodricks/FluentFTP#553]
**FTP OS:** Windows

**Computer OS:** 2008 R2

**FluentFTP Version:** 19.1.2.0

**Runtime Version :** v4.0.30319

First of all: Great job. Its a very easy to use and powerfull library.

I wrote a program on my Windows 10 PC using FluentFTP to login and download files from a FTP server and it works fine.

However, when I deployed the program on another Windows 2008 systems it can connect to the FTP server but  it is not being able to get the File List.

I tested with FileZilla on both machine and both are working fine.
FileZilla setup with the option of "Require explicit FTP over TLS".

Please suggest me, where I am wrong.

For the reference I am sending the client settings and log below.

**Client Config:**
            client.Host = host;
            client.Port = port;
            client.RetryAttempts = base.RetryCount;
            client.Credentials = new NetworkCredential(base.UserName, base.Password);
            client.EncryptionMode =FtpEncryptionMode.Explicit;
            client.SocketKeepAlive = true;
            client.DataConnectionType = FtpDataConnectionType.AutoPassive;
            client.SslProtocols = System.Security.Authentication.SslProtocols.Tls12;
            client.ValidateCertificate += ((sender, e) => { e.Accept = true; });

**Log:**
2020-03-23 16:44:04,781 - FTP Connected. 
 2020-03-23 16:44:04,781 - [----] Successfully connected to the FTP. 
 2020-03-23 16:44:04,786 - Getting file list from FTP path (/). 
 2020-03-23 16:44:04,787 - FTP working directory (/). 
 2020-03-23 16:44:05,175 - Failed to get list from FTP FluentFTP.FtpCommandException: SSL connection failed; session reuse required: see require_ssl_reuse option in vsftpd.conf man page
   at FluentFTP.FtpClient.CloseDataStream(FtpDataStream stream)
   at FluentFTP.FtpDataStream.Close()

**Comment by robinrodricks** [comment]
Wrong connection profile. Try using `client.AutoDetect()` on the target machine. See https://github.com/robinrodricks/FluentFTP/wiki/Automatic-Connection

**Comment by SahaGoutam** [comment]
Hi,

First of all: thanks for your replay.

If you see the log, where I mentioned that the FTPS is connected. But program throwing exception  when I getting the file list from FTPS.

however, I will check and let you know.

**Comment by pmathbliss** [comment]
@SahaGoutam 
I'm getting the same issue. I've tried a few different libraries. It works perfectly in Filezilla.

**Comment by robinrodricks** [comment]
Unsure how to fix this. Closing for now.
