### ISSUE TITLE
Unable to LIST in ASCII mode (451 LIST command invalid with TYPE binary.)

### ISSUE THREAD

**Issue by emirgorodov** [robinrodricks/FluentFTP#555]
**FTP OS:** Unknown

**FTP Server:** IBM Sterling B2B Integrator

**Computer OS:** Unix (Docker) / Windows

**FluentFTP Version:** 32.3.0

Server configuration doesn't allow Binary transfer mode, so I have to use ASCII (have no control over it). But all listing methods ignore specified `TransferMode`. (I suppose the reason is described in this comment: `// always get the file listing in binary to avoid character translation issues with ASCII.`)
It would be helpful to have a possibility to control such behavior, since now I see no options to override it.

**Logs :**

```
# ConnectAsync()
Status:   Connecting to xxx.xxx.xxx.xxx:xx
Response: 220 CONNECT:Enterprise Gateway 2.0.02. 37 FTP Server ready...  10:00:00  04-01-2020
Command:  USER SOMEUSER
Response: 331 Password required for SOMEUSER.
Command:  PASS ***
Response: 230 User SOMEUSER logged in. Session Id: 5001.
Command:  FEAT
Response: 500 FEAT command not understood.
Status:   Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
Command:  SYST
Response: 502 Command not implemented.
Warning:  Cannot auto-detect listing parser for system 'Unknown', using Unix parser

# SetWorkingDirectoryAsync("")

# GetListingAsync("", Auto)

# GetWorkingDirectoryAsync()
Status:   Testing connectivity using Socket.Poll()...
Command:  PWD
Response: 257 "SOMEUSER" is the current working Mailbox ID.
Command:  TYPE I
Response: 200 TYPE Command okay.

# OpenPassiveDataStreamAsync(AutoPassive, "LIST SOMEUSER", 0)
Command:  EPSV
Response: 500 EPSV command not understood.

# OpenPassiveDataStreamAsync(PASV, "LIST SOMEUSER", 0)
Command:  PASV
Response: 227 PASV Entering passive mode (xxx.xxx.xxx.xxx:xx).
Status:   Connecting to xxx.xxx.xxx.xxx:xx
Command:  LIST SOMEUSER
Response: 451 LIST command invalid with TYPE binary.
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Exception thrown: 'FluentFTP.FtpCommandException' in FluentFTP.dll
    FluentFTP.FtpCommandException: LIST command invalid with TYPE binary.\r\n   at FluentFTP.FtpClient.GetListingInternalAsync(String listcmd, FtpListOption options, Boolean retry, CancellationToken token) in ...
Command:  QUIT
Response: 221 Goodbye.
Status:   Disposing FtpSocketStream...
```

**Comment by robinrodricks** [comment]
New `client.ListingDataType`

Works for you?

Try: [FluentFTP.32.3.1.zip](https://github.com/robinrodricks/FluentFTP/files/4419454/FluentFTP.32.3.1.zip)

**Comment by emirgorodov** [comment]
Looks good! And works too. 
The only thing that makes me worry is that similar enforcing used in other methods, like `GetFileSizeInternal`. For sake of consistency it could be covered too. 
Can think of several options, like method override with `FtpDataType` argument (`OpenRead` method style) or maybe a single property that affects all that methods.
Thank you for looking into this.

**Comment by robinrodricks** [comment]
Good point but many times file size fails to get in ASCII mode so we have to switch to binary. There is no workaround there.

**Comment by robinrodricks** [comment]
Released!

https://www.nuget.org/packages/FluentFTP/32.3.1
