### ISSUE TITLE
Method  GetFilesToDownload  replace destination path error

### ISSUE THREAD

**Issue by 263613093** [robinrodricks/FluentFTP#557]
Windows 10
FluentFTP Version: 32.3.1

FluentFTP/Client/FtpClient_FolderDownload.cs
Function：GetFilesToDownload
Line:168
when remoteFile.FullName contains remoteFolder character，the relativePath will be error
Code:
`var relativePath = remoteFile.FullName.Replace(remoteFolder, "").Replace('/', Path.DirectorySeparatorChar);`

Example:
localFolder=@"D:\";
remoteFolder="/"
remoteFile.FullName is "/wwwroot/data/filename.jpg"
relativePath  is "D:\wwwrootdatafilename.jpg"
it should be "D:\wwwroo\data\filename.jpg"

or

remoteFolder="/data"
remoteFile.FullName is "/wwwroot/data/filename.jpg"
relativePath  is "D:\wwwroot\filename.jpg"
it should be "D:\wwwroot\data\filename.jpg"

**Comment by 263613093** [comment]
`var relativePath = remoteFile.FullName.Substring(remoteFolder.Length).Replace('/', Path.DirectorySeparatorChar);`

Use string.Substring to instead repalce method

**Comment by robinrodricks** [comment]
Great find, thanks.

**Comment by robinrodricks** [comment]
Does this work?

[FluentFTP.32.3.2.zip](https://github.com/robinrodricks/FluentFTP/files/4433129/FluentFTP.32.3.2.zip)

**Comment by robinrodricks** [comment]
Fixed.
