### ISSUE TITLE
LoadProfile does not exist and encoding type is wrong?

### ISSUE THREAD

**Issue by smithburger** [robinrodricks/FluentFTP#558]
FluentFTP Version: 32.3.1

Used profiles auto detect to get server ssl configuration. The resulting code from FluentFTP was invalid. As far as I can see in 32.3.1 at least there is no definition for LoadProfile. I searched the github repository and don't see it there either. I had to set each setting the normal way which is fine.

Also I think Encoding = System.Text.UTF8Encoding should be Encoding = Encoding.UTF8 in the code snippet given. 

Here is the entire code snippet given to us after running the auto detect. I am pretty raw as a programmer so if I am missing something simple I apologize. 

```
// add this above your namespace declaration
using FluentFTP;
using System.Text;
using System.Net;
using System.Security.Authentication;

// add this to create and configure the FTP client
var client = new FtpClient();
client.LoadProfile(new FtpProfile {
        Host = "xxxxxxxxxx",
        Credentials = new NetworkCredential("xxxxxx", "xxxxxx"),
        Encryption = FtpEncryptionMode.Implicit,
        Protocols = SslProtocols.None,
        DataConnection = FtpDataConnectionType.PASV,
        Encoding = System.Text.UTF8Encoding,
});
// if you want to accept any certificate then set ValidateAnyCertificate=true and delete the following event handler
client.ValidateCertificate += new FtpSslValidation(delegate (FtpClient control, FtpSslValidationEventArgs e) {
        // add your logic to test if the SSL certificate is valid (see the FAQ for examples)
        e.Accept = true;
});
client.Connect();
```

**Comment by robinrodricks** [comment]
Sorry. Exposed LoadProfile. The code should work.

https://www.nuget.org/packages/FluentFTP/32.3.2
