### ISSUE TITLE
Issue replacing path during UploadDirectory

### ISSUE THREAD

**Issue by philippjenni** [robinrodricks/FluentFTP#559]
**FTP OS:** Windows

**FTP Server:** IIS

**Computer OS:** Windows 10

**FluentFTP Version:** 32.3.2

UploadDirectory generate wrong directories during upload if remote directory not exists. The replacement of the root relative path is not correct on windows. The fix in commit #1dd960ac24d9ca037cc67bf28bb3c9d808a003fd doesn't work

**Logs :**

```
# CreateDirectory("/subdomains/dev/httpdocs/ligamgr_ssha_prod/C:/Daten/data", True)

# DirectoryExists("/subdomains/dev/httpdocs/ligamgr_ssha_prod/C:/Daten")

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/" is current directory.
Command:  CWD /subdomains/dev/httpdocs/ligamgr_ssha_prod/C:/Daten
Response: 550 The parameter is incorrect. 
Status:   Create non-existent parent directory: /subdomains/dev/httpdocs/ligamgr_ssha_prod/C:/Daten

```

**Comment by robinrodricks** [comment]
Check now:

https://www.nuget.org/packages/FluentFTP/32.3.3
