### ISSUE TITLE
The behavior of DownloadDirectory and UploadDirectory is no longer identical

### ISSUE THREAD

**Issue by philippjenni** [robinrodricks/FluentFTP#564]
In DownloadDirectory, the FtpRules should be implemented in the DeleteExtraLocalFiles method.

**Comment by robinrodricks** [comment]
Thanks for this. I'll check it out and let you know.

**Comment by robinrodricks** [comment]
Why should it?

**Comment by philippjenni** [comment]
It is incomprehensible to the user why the behavior of the methods DownlodDirectory and UploadDirectory is not identical in relation to the FtpRules. See Comment https://github.com/robinrodricks/FluentFTP/issues/561#issuecomment-612879935

**Comment by robinrodricks** [comment]
Well the way the it was designed, the rules are only run on the source. In download the rules are run on the server files. In upload the rules are run on the local files. Is that not enough? Why?

**Comment by philippjenni** [comment]
> Well the way the it was designed, the rules are only run on the source. In download the rules are run on the server files. In upload the rules are run on the local files. Is that not enough? Why?

That's right, but it's about the behavior when deleting on the opposite side if an FtpRule has been defined.

**Comment by robinrodricks** [comment]
Afaik this is not required.
