### ISSUE TITLE
How can I filter files by extension in a FTP?

### ISSUE THREAD

**Issue by irineuromanato** [robinrodricks/FluentFTP#566]
**FTP OS:** Unix / Windows 

**FTP Server:** Pure-FTPd / DrFTPD / Vsftpd / ProFTPD / Vax / VMS / OpenVMS / Tandem / HP NonStop Guardian / IBM OS400 / AS400 / Windows CE

**FluentFTP Version: LAST

I have a routine that verify files in a ftp folder and delete files, but I have 3 points that I use to verify the files;
the extension ( for example .log )
the modification date ( older than )
exception folder ( cant be in a exception folder )

Please how can i verify exception folder and extension.

thanks

**Logs :**

```

<paste logs here>

```

**Comment by 263613093** [comment]
See "FluentFTP.CSharpExamples/DownloadDirectoryWithRules.cs"

> FtpFileExtensionRule

It also be used for File，and you can customize your rules

**Comment by robinrodricks** [comment]
Thanks @263613093
