### ISSUE TITLE
AsyncWaitHandles handle leak (in .NET Framework 4.5 build)

### ISSUE THREAD

**Issue by sdiaman1** [robinrodricks/FluentFTP#568]
**FTP OS:** Windows

**FTP Server:** FileZilla

**Computer OS:** Windows

**FluentFTP Version:** 32.3.3

Hi robinrodricks -

I'm creating this issue just in case you don't see pull request https://github.com/robinrodricks/FluentFTP/pull/567.

There's a handle leak that occurs each time I call FluentFTP.FtpClient.Connect(). (I'm also calling Disconnect() and Dispose(), after each Connect().) It leaks a few hundred handles each time, and these leaked handles accumulate over time, until my app stops working. (I don't need to get a file list, or to download a file, to get this leak; I only need to Connect().)

It only leaks handles when it's able to connect to the FTP server (if the FTP server is down it won't leak handles). I tested using FileZilla FTP server, locally, with loopback IP address 127.0.0.1, and also using a remote FTP server. (Also, I ran my app (the FTP client) on two different computers, and I turned off my firewall, to make sure it wasn't interfering.) The handle leaks still occurred.

These changes seem to plug the handle leaking, or at least the big leaks; I don't know if there's some smaller ones out there that I didn't get, or if there's code that I'm not using that's also leaking.

Please review these changes and merge them into your master branch?

Thanks!

**Comment by robinrodricks** [comment]
Thank you again.

**Comment by robinrodricks** [comment]
Released in [32.4.0](https://www.nuget.org/packages/FluentFTP/32.4.0)

#### 32.4.0
  - New: `UploadDirectoryDeleteExcluded` property to control if excluded files are deleted during Upload (thanks [philippjenni](/philippjenni))
  - New: `DownloadDirectoryDeleteExcluded` property to control if excluded files are deleted during Download (thanks [philippjenni](/philippjenni))
  - Fix: Dispose AsyncWaitHandles to stop handle leak in .NET Framework 4.5 (thanks [sdiaman1](/sdiaman1))
  - Fix: Implement proper cancellation support in `UploadDirectory` (once file transfer begins it cannot be cancelled)
  - Fix: Implement proper cancellation support in `DownloadDirectory` (once file transfer begins it cannot be cancelled)
  - Fix: Implement proper cancellation support in FXP `TransferDirectory`
  - Fix: Implement proper cancellation support in recursive `GetListing`
  - Fix: Correctly resume when unexpectedEOF error received during uploading a file (thanks [mrcopperbeard](/mrcopperbeard))
  - Fix: Hide internal properties in `FtpClient` that are not meant to be exposed
  - Fix: Update `IFtpClient` with the latest set of public properties that are meant to be exposed
