### ISSUE TITLE
How to display download speed?

### ISSUE THREAD

**Issue by Simulator88** [robinrodricks/FluentFTP#575]
**FTP Server:** Pure-FTPd 

**Computer OS:**  Windows

**FluentFTP Version:**  32.4.0

Hello guys,

just a quick question. I am downloading single files async in my vb.net wpf application. I implemented the progress bar to my app which is working fine, is there any way to display the current download speed?

Thanks!

**Comment by robinrodricks** [comment]
The speed is available as a property of FtpProgress. See https://github.com/robinrodricks/FluentFTP/wiki/Class-FtpProgress

**Comment by Simulator88** [comment]
Thanks for the answer, it is sorted out now :) Amazing.
