### ISSUE TITLE
Use GetListingAsync throw an exception when listing directories

### ISSUE THREAD

**Issue by 263613093** [robinrodricks/FluentFTP#576]
**FTP OS:** Windows 

**FTP Server:**  Windows CE

**Computer OS:** Windows10

**FluentFTP Version:** 32.4.0

System.AggregateException:“ A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

**StackTrace：**
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()

**Logs :**
```
Response: 226 Transfer complete.
Status:   Disposing FtpSocketStream...
>         GetListingAsync("/wwwroot/wap/include/ckeditor/themes/default/", Size)
Command:  TYPE I
Response: 200 Type set to I.
>         OpenPassiveDataStreamAsync(AutoPassive, "LIST /wwwroot/wap/include/ckeditor/themes/default", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||33003|)
Status:   Connecting to 
>         Dispose()
Status:   Disposing FtpClient object...
Status:   Testing connectivity using Socket.Poll()...
Command:  QUIT
Response: 221 再见..
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...




```

**Comment by robinrodricks** [comment]
Try with FileZilla. If it works then paste the full FLuentFTP logs as well as filezilla logs.
