### ISSUE TITLE
FluentFTP throws 'Object reference not set to an instance of an object' when downloading a file already on disk

### ISSUE THREAD

**Issue by rubenhuisman** [robinrodricks/FluentFTP#578]
**FTP OS:** Unix / Windows / Embedded

**FTP Server:** Pure-FTPd / DrFTPD / Vsftpd / ProFTPD / Vax / VMS / OpenVMS / Tandem / HP NonStop Guardian / IBM OS400 / AS400 / Windows CE

**Computer OS:** ?
Windows
**FluentFTP Version:** ?
32.4.0
When downloading a file using the ```DownloadFileAsync``` method, it throws an ```Object reference not set to an instance of an object``` error when the file with the same name already exists on disk.

Maybe it's a lot cleaner to check if file already exists and throw an usefull error message?

**Comment by robinrodricks** [comment]
What inputs are you passing to DownloadFile? It has an option for
overwriting the file I think.

**Comment by rubenhuisman** [comment]
You are right, another case of RTFM. Thanks! Issue can be closed.
