### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by ajtruckle** [robinrodricks/FluentFTP#579]
Hi !

Thanks for making this excellent library available.

I am looking at the c# samples but don't see any implementation of error handling.

In it's basic form, what error handling does this library support for c#?

For example:

        //
        // Summary:
        //     Sets the work directory on the server
        //
        // Parameters:
        //   path:
        //     The path of the directory to change to
        public void SetWorkingDirectory(string path);

It does not return a `bool` so what is the right way to know if the path does not exist?

**Comment by robinrodricks** [comment]
Check FileExists or DirectoryExists as the main ways to check object existence.

Exceptions are only thrown for critical errors like if something crashed or failed to transfer or the server returned an error code. In all other cases we return normally.

List of special exceptions : https://github.com/robinrodricks/FluentFTP/wiki/Classes#exceptions-and-errors

**Comment by ajtruckle** [comment]
Thanks. But I am still not 100% sure. How do you test if it is connected? I could not see any samples with usage of "IsConnected".
