### ISSUE TITLE
Failing when i try to use IsConnected

### ISSUE THREAD

**Issue by ajtruckle** [robinrodricks/FluentFTP#580]
Here is some code:

        public void DisconnectFromFTP()
        {
            if(_FtpConnection != null && _FtpConnection.IsConnected)
            {
                SimpleLog.Log("Disconnected from FTP");
                _FtpConnection.Dispose();
                _FtpConnection = null;
            }
        }

        public bool IsFTPConnected()
        {
            if (_FtpConnection != null && _FtpConnection.IsConnected)
                return true;

            return false;
        }

        public bool RemoteFolderExists(string strRemoteFolder)
        {
            if (_FtpConnection != null && _FtpConnection.IsConnected)
                return _FtpConnection.DirectoryExists(strRemoteFolder);

            return false;
        }
        public string[] GetRemoteFolderList(string strFolder)
        {
            List<string> aryStrFolders = new List<string>();

            if(_FtpConnection != null && _FtpConnection.IsConnected)
            {
                string strRootFolder = Path.Combine(_FtpConnection.GetWorkingDirectory(), strFolder);

                // get a recursive listing of the files & folders in a specific folder
                foreach (FtpListItem item in _FtpConnection.GetListing(strRootFolder))
                {
                    if (item.Type == FtpFileSystemObjectType.Directory)
                    {
                       aryStrFolders.Add(item.Name);
                    }
                }

                aryStrFolders.Sort();
            }

            return aryStrFolders.ToArray();
        }

When I try the above I find that it yields no results.

If I remove all of the ` && _FtpConnection.IsConnected` from the above methods it works.

Why would this be?

I am using the version as available on 16/05/2020.

**Comment by robinrodricks** [comment]
Paste the full FluentFTP logs so I can check.

**Comment by ajtruckle** [comment]
Don't worry. You can close this. I have decided FTP is not a critical requirement for the project I am working on. But thanks for the prompt help and excellent library.
