### ISSUE TITLE
I am having problems :(

### ISSUE THREAD

**Issue by ajtruckle** [robinrodricks/FluentFTP#582]
Here is the context:

C# DLL (which include FTP Fluent). This DLL is exposed via COM for my MFC C++ project to use.

Some times when I run my application (which calls my own dll methods (which inturn call yours) work Then other times my application freezes witha  small popup window saying the server s busy (meaning my dll).

Andrew

**Comment by ajtruckle** [comment]
Update - unless it was by coincidence I rebuilt my dll in 64 bit and rebuilt my main app and this time it worked.

But when I compile my program 32 bit and use my x86 built com dll I get the server busy issue.

**Comment by robinrodricks** [comment]
Its not an issue with FluentFTP. Also its C++ usage and I cannot help you here. StackOverflow may be a better place to ask this. Sorry.
