### ISSUE TITLE
Custom parser not cleared correctly

### ISSUE THREAD

**Issue by rubenhuisman** [robinrodricks/FluentFTP#585]
**FluentFTP Version:** 32.4.1

We are using FluentFTP to read from different sources. Those sources come from a config file, each config instance has a property 'useCustomParser'.
When this property is set to ```true``` we add the custom parser as follow: 

```FtpListParser.AddParser(parser);```

When the next item in the config does not use a custom parser we remove it as follow:

```FtpListParser.RemoveParser(parser)```

The method ```RemoveParser``` does remove the custom parser from the list ```FtpListParser.m_parsers```  but it does not remove the current parser from the ```FtpListParser.m_customParser``` field,
which is set in the ```FtpListParser.AddParser``` method. Even ```FtpListParser.ClearParsers``` does not remove the current parser from the ```FtpListParser.m_customParser``` field.

This sounds like a bug to me. If you can confirm that this is not desired behaviour, i will provide a pull request to fix this.

Looking forward to your reaction, thanks!

**Comment by robinrodricks** [comment]
It's probably a bug as custom parsers have not been maintained much. You
may provide a PR. Thanks!

**Comment by robinrodricks** [comment]
Thanks!

Released in https://www.nuget.org/packages/FluentFTP/32.4.3
