### ISSUE TITLE
How to get local time file from FTP service of Linux system

### ISSUE THREAD

**Issue by GhostCakeMaker** [robinrodricks/FluentFTP#587]
**FTP OS:** Linux(CentOS 7)

**FTP Server:** Vsftpd 

**Computer OS:** Windows 10

**FluentFTP Version:** 32.4.3

I get the file from vsftpd of CentOS 7 system. The time of the file is always displayed in UTC. I try to set FtpClient.ListingCulture Property, but it has no effect. Excuse me, where can I see the time zone returned by the FTP service, or how can I set the returned file time to local time?

I have set the time zone of CentOS 7 system as the local time zone.

**Logs :**

**Comment by A9G-Data-Droid** [comment]
The timestemp on the file is the time it was created on the server, in it's own timezone. Figuring out how to convert from one server timezone to the client timezone can be very difficult. It's much better to store everything in UTC and then only do one single conversion to display it local to the user. This is handled by your own code and not by an FTP library. FTP doesn't know or care what timezone your server or client are in. It only passes the result given by the server, to the client.

**Comment by GhostCakeMaker** [comment]
Thank you for answering my question. However, I know that the time of the file is the time returned by FTP on the server, but when I connect to many servers, I don't know the time zone returned by FTP on the server. It may be UTC, or it may be the local time of other countries, which is not under my control.

All I hope is that fluent FTP can know the time zone of FTP server, and I can directly convert it to the time I need according to the time zone.

**Comment by robinrodricks** [comment]
Ftp servers don't mention their timezone.

**Comment by A9G-Data-Droid** [comment]
@GhostCakeMaker If you have permission to create files on the FTP server you can write your own function that gets the time by uploading a file, getting the timestamp, and comparing to local time. Use this offset to modify the file timestamps as needed:

https://unix.stackexchange.com/questions/25239/how-to-get-the-timezone-of-a-ftp-server

**Comment by robinrodricks** [comment]
This is now possible with 33.0.0:

- New: Reworked timezone conversion API (simply set `TimeConversion` and `TimeZone`)
 - New: Options to convert server timestamps into the format of your choice (`ServerTime`, `LocalTime` and `UTC`)
 - New: Support for conversion to local timezone in .NET core (set `LocalTimeZone`)
 - New: `GetListing` honors the time conversion settings of the active client
 - New: `GetModifiedDate` honors the time conversion settings of the active client
 - New: `SetModifiedDate` honors the time conversion settings of the active client
