### ISSUE TITLE
A call to SSPI failed, see inner exception. -> The Local Security Authority cannot be contacted 

### ISSUE THREAD

**Issue by MarkGoldring** [robinrodricks/FluentFTP#591]
**FTP OS:**  Windows

**FTP Server:** vsFTPd 3.0.3

**Computer OS:** Linux (UNIX Type: L8)

**FluentFTP Version:** 32.4.3

Hi,

I receive the following error when attempting to connect to the above mentioned FTP server. I know the FTP server only accepts TLS 1.2 connections: -

   A call to SSPI failed, see inner exception. -> The Local Security Authority cannot be contacted 

FileZila does connect, as does the Rebex  FTP/SSL component.
I have tried the Auto-Detect method but this returns 0 profiles.
I have tried combinations of settings to no avail.

Am I missing something, or is this a know limitation / issue?

Regards

Mark

**Logs :**

[FluentFTP_AutoDetect.log](https://github.com/robinrodricks/FluentFTP/files/4838576/FluentFTP_AutoDetect.log)
[FluentFTP_Connect.log](https://github.com/robinrodricks/FluentFTP/files/4838577/FluentFTP_Connect.log)
[FileZilla.log](https://github.com/robinrodricks/FluentFTP/files/4838592/FileZilla.log)

**Comment by robinrodricks** [comment]
This means the other side is using another version of TLS and you are using an older version.
Set up security attribute to TLS12 before making the connection. This is a widely known problem, as many providers start using TLS12 (e.g. paypal,amazon and so on).

```
client.EncryptionMode = FtpEncryptionMode.Explicit;
client.SslProtocols = SslProtocols.Tls12;
client.ValidateAnyCertificate = true;
```
