### ISSUE TITLE
the istream.Close() in the OpenReadExample  only called Stream.Close

### ISSUE THREAD

**Issue by yustonefish** [robinrodricks/FluentFTP#594]
I need it called FtpDataStream.Close(), so the I can use the connection to write another file.
As it only called Stream.Close(), so the  "226 Transfer complete." is still there , be regarded as the reponse of next Command.

The below is  part logs:
Info Command:  RETR /incoming/test/2020-07-07/10.txt
Info Response: 150 Opening BINARY mode data connection for 10.txt (18 Bytes).
Debug Status:   Disposing FtpSocketStream...
Debug Status:   Disposing FtpSocketStream...
Debug >         GetFileSize("/incoming/test/2020-07-07/11.txt")
Info Command:  SIZE /incoming/test/2020-07-07/11.txt
Info Response: 226 Transfer complete.

**Comment by yustonefish** [comment]
the below can work:
using (var istream = conn.OpenRead("/full/or/relative/path/to/file") as FtpDataStream) {

**Comment by robinrodricks** [comment]
You have to call GetReply after finishing with your OpenRead

**Comment by yustonefish** [comment]
would you please add it to the sample project?

**Comment by robinrodricks** [comment]
@yustonefish which sample?

**Comment by robinrodricks** [comment]
the quick start doesn't have low level methods - https://github.com/robinrodricks/FluentFTP/wiki/Quick-Start-Example

also they are not recommended. if possible try using the high level methods.
