### ISSUE TITLE
Upload files with replacement with newer ones

### ISSUE THREAD

**Issue by ghost** [robinrodricks/FluentFTP#596]
**FluentFTP Version:** 32.4.3

Hello! I need to upload the directory with the files to the FTP server, so that when downloading the old files on the FTP server will be overwritten with new local files, and those files that do not differ from the local ones remain untouched. I use the **UploadDirectoryAsync()** method. How can this be implemented?
Thank you in advance for any help

**Comment by robinrodricks** [comment]
Right now this is not supported. You can build it manually by referring to the code of UploadDirectory and then using the CompareFile method to check if the file is different between server and client.

**Comment by robinrodricks** [comment]
Added to the [bucket list](https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans). We will pick this up as and when we have free time. Comment on this issue if you want us to prioritize it. Thanks!
