### ISSUE TITLE
Question : File is empty when uploading it to FTP server

### ISSUE THREAD

**Issue by chaouanabil** [robinrodricks/FluentFTP#598]
Hello everyone,
I have a problem with fluentFtp when trying to upload a file using byte[] or file path, the file is upload succusfuly but the size od the file is 0. I m using a public FTP server (it works fine using filezella client ).
please help me to solve this problem and thanks in advance.
This is the code i m using
![image](https://user-images.githubusercontent.com/19364848/87463131-ddb6bc80-c608-11ea-9163-901f36b43e79.png).

**Comment by chaouanabil** [comment]
This issu fixed, the problem was with the ftp server not the FluentFtp api.

**Comment by vOrdonezGit** [comment]
Hi @chaouanabil, sorry for the late question, but, what the issue with the FTP? Something in the configuration? I'm having the same problem with 0 bytes files.... 

Thanks in advance

**Comment by svarga91** [comment]
I have also issue with empty file. 
@chaouanabil, could you please note about solution.

Thanks

**Comment by yogeshjoshi123** [comment]
@chaouanabil  could you please note about solution.
