### ISSUE TITLE
Download stops

### ISSUE THREAD

**Issue by CyberMist2** [robinrodricks/FluentFTP#600]
**FTP OS:** Linux

**FTP Server:** FTPS

**Computer OS:** Windows

**FluentFTP Version:** 32.4.1 

Sometimes it just doesn't want to download files.
Please see log at the very bottom of the pastebin link where it says failed to download file ..

**Logs :** https://pastebin.com/t131LWaL

**Comment by robinrodricks** [comment]
Your server is blocking you.

> Response: 426 Connection closed; aborted transfer of "/Data/Patch-H.MPQ"

**Comment by CyberMist2** [comment]
> Your server is blocking you.
> 
> > Response: 426 Connection closed; aborted transfer of "/Data/Patch-H.MPQ"

How can I solve that issue? And what can cause that? @robinrodricks
