### ISSUE TITLE
Upload Directory Mirror does not remove source nonexist directories

### ISSUE THREAD

**Issue by mmsw-git** [robinrodricks/FluentFTP#601]
**FTP OS:**  Windows 

**FTP Server:** Windows

**Computer OS:** Windows

**FluentFTP Version:** 32.4.3

Hello, 
I use your library to synchronization directories via FTP.
It works great - good work.

I have little troubles with directories, that was removed from source.
Such directories are empty on target after synchronisation, but still remain there.

Is there any solution?

Thank you very much
Miroslav

**Comment by robinrodricks** [comment]
Added to the [bucket list](https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans). We will pick this up as and when we have free time. Comment on this issue if you want us to prioritize it. Thanks!
