### ISSUE TITLE
AutoConnectAsync is actually synchronous

### ISSUE THREAD

**Issue by SapientGuardian** [robinrodricks/FluentFTP#606]
**FluentFTP Version:** 32.4.3

https://github.com/robinrodricks/FluentFTP/blob/483048c96390c61315dc397ae55707f978e20998/FluentFTP/Client/FtpClient_AutoConnection.cs#L279

`AutoConnectAsync` starts by calling the `AutoDetect` function, which utilizes the synchronous `Connect` function. There is currently no `AutoDetectAsync`, but there is a `ConnectAsync`.

**Comment by robinrodricks** [comment]
Added to the [bucket list](https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans). We will pick this up as and when we have free time. Comment on this issue if you want us to prioritize it. Thanks!
