### ISSUE TITLE
Detect connected but not logged in (when password is incorrect)

### ISSUE THREAD

**Issue by jonchengkuo** [robinrodricks/FluentFTP#607]
**FTP Server:** IBM zOS/MVS

**Computer OS:** Windows

**FluentFTP Version:** 32.4.3

When the password is incorrect, the first Connect() call results in an FtpException.  However, FtpClient.IsConnected property becomes true after that (connected but not logged in).  Is there a way to check that the login was indeed successful later so that my code will not try to do work on it.  Thank you! 

**Logs :**

```

<paste logs here>

```

**Comment by kiddailey** [comment]
Came here with the same curiosity about the proper way to do this.  Looks like I'll just share how I worked-around it.  :)

If you want to use IsConnected, you could wrap the Connect request in a try/catch, and Disconnect in the catch block.  You can use the _FtpException_ type to look for FTP 530 error (User cannot log in) in the HResult if you want to specifically handle that case.  Of course, a plain Exception would also work here:, but without the HResult:

``` c#
try
{
    await ftpClient.ConnectAsync();
}
catch (FtpException ex)
{
    // 530 = User cannot log in
    if (ex.HResult == 530)
    {
         // Login failed
    }
    
    ftpClient.Disconnect();
}
```

``` c#
try
{
    await ftpClient.ConnectAsync();
}
catch (Exception ex)
{
    ftpClient.Disconnect();
}
```

Alternatively you could just have a local isLoggedIn boolean that gets set to true only if the connection succeeds:

``` c#

var isLoggedIn = false;

try
{
    await ftpClient.ConnectAsync();
    isLoggedIn = true;
}
catch (Exception ex)
{
    Console.Write(ex.Message);
    ftpClient.Disconnect();
}
```

There are probably other ways to handle this as well, but hopefully that helps :)

**Comment by robinrodricks** [comment]
We already have `client.IsAuthenticated` to check for this situation.
