### ISSUE TITLE
Feature request: AutoExplicit encryption mode

### ISSUE THREAD

**Issue by SapientGuardian** [robinrodricks/FluentFTP#608]
**FluentFTP Version:** 32.4.3

If you don't know whether a server supports explicit encryption, but would prefer to use it available, you currently must attempt to connect with Explicit, catch the FtpSecurityNotAvailableException, change the encryption to None, and try again with a new connection.

It would be more efficient to just ignore the AUTH failure and continue the connection as unencrypted. I think the implementation for this should be pretty simple; something like this:

```
if (EncryptionMode == FtpEncryptionMode.Explicit || EncryptionMode == FtpEncryptionMode.AutoExplicit) {
				reply = await ExecuteAsync("AUTH TLS", token);
				if (!reply.Success && EncryptionMode == FtpEncryptionMode.Explicit) {
					throw new FtpSecurityNotAvailableException("AUTH TLS command failed.");
				}
				if (reply.Success)
				{
					await m_stream.ActivateEncryptionAsync(Host, m_clientCerts.Count > 0 ? m_clientCerts : null, m_SslProtocols);
				}
			}
```

**Comment by robinrodricks** [comment]
@SapientGuardian Can you try this and see if it works for you?

**Comment by SapientGuardian** [comment]
Sorry for the delayed response, it's been a busy week. I just tried it out against a server that does support SFTP, and one that does not. It works perfectly; neither threw an exception, and `client.IsEncrypted` was accurate.

Thanks!
