### ISSUE TITLE
Download/delete folders and files in specific cases

### ISSUE THREAD

**Issue by heavyflames** [robinrodricks/FluentFTP#611]
Is there a way to recursivly download folders and files and then delete them if needed?

Lets say these folder exists on the server.

2020/08/27/11/05
2020/08/27/11/10

(folders are in a date format, YYYY/MM/DD/HH/MM)

And in the 2020/08/27/11/05 folder there are a file named final.txt
I want to download the full path locally and create the folders if not exists.

The other folder, 2020/08/27/11/10 does not have a file called final.txt, so this folder I do not want to download.

And if there was a final.txt in  2020/08/27/11/10 I want to delete the folder  2020/08/27/11 aswell, and work my way backwards so to say.

The folders are dynamic so I do not know beforhand what folders will exists, So I need to start som the root folder.

**Comment by robinrodricks** [comment]
Use GetListing in non recursive mode to get a list of folders.

Use DownloadFolder or DownloadFile if you want to manually recurse through folders. DeleteFile can be used as well.

Its all custom logic, you write this in your app, you can't possibly expect an FTP library to do this.
