### ISSUE TITLE
When i use DownloadDirectory method, I want to pass only some files.

### ISSUE THREAD

**Issue by E-nan** [robinrodricks/FluentFTP#612]
**FTP OS:**  Windows

**FTP Server:** Windows

**Computer OS:** Windows

**FluentFTP Version:** 32.2.1.0

<write details about your bug report / feature request here>

**Logs :**

I want only some files pass, and another files download.
But when i use DownloadDirectory method, then all files download.
How can i only some files pass?? 

I may not have found an answer because my English is not good. Sorry

**Comment by E-nan** [comment]
If file download "A" remote folder to "B" remote folder.
"A" folder have "file1.txt", "file2.txt", "file3.txt".
But i don't want download "file2.txt".
How can i "file2.txt" file pass??

**Comment by robinrodricks** [comment]
If you want to exclude files based on their name, check out rules.

https://github.com/robinrodricks/FluentFTP/wiki/Rules#what-kinds-of-rules-are-supported-and-how-do-rules-work

Specifically, `FtpFileNameRegexRule` can be set to 'false' to exclude files of a given name.
