### ISSUE TITLE
Connect with KeyValue files and password (SFTP)

### ISSUE THREAD

**Issue by mldz** [robinrodricks/FluentFTP#614]
Hi,

First of all; thanks for FluentFTP.

I need to connect to a FTPS server using a KeyValue pair file (.ppk), username and password for the file. Didn't see an example on the https://github.com/robinrodricks/FluentFTP/wiki/FTPS-Connection page. 

Is it possible with FluentFTP?

Here is an example of FileZilla configuration:

![fptsKeyValuePair](https://user-images.githubusercontent.com/10193159/92235051-5ae90a00-eeb3-11ea-938d-36790bae602b.png)

Thanks,

Matthijs

**Comment by robinrodricks** [comment]
I'm not sure how this is implemented. If you can share more technical details perhaps we can support it.

**Comment by mldz** [comment]
I have no clue ;-) Will look into this.

**Comment by mldz** [comment]
found something here that seems to work: https://stackoverflow.com/a/59783368/369122

**Comment by robinrodricks** [comment]
We don't support SFTP which is a completely different protocol. You'll need SSH.NET for that. I think keyfiles are used for SFTP and not FTPS.
