### ISSUE TITLE
Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable.

### ISSUE THREAD

**Issue by rmalhotra85** [robinrodricks/FluentFTP#622]
**FTP OS:** ?

**FTP Server:** ?

**Computer OS:** Windows Server 2016

**FluentFTP Version:** 32.4.3

I am targeting .NET Framework 4.7.2, and am running the following code:

```
using (var ftpClient = new FtpClient() {
		Host = "ftp.box.com",
		Port = 990,
		Credentials = new NetworkCredential("username", "password"),
		EncryptionMode = FtpEncryptionMode.Implicit
	})
	{
		await ftpClient.ConnectAsync();
		await ftpClient.GetWorkingDirectoryAsync();
		await ftpClient.GetListingAsync("/Folder",FtpListOption.Recursive);
	}
```

And the exception I get is:
```
Exception Type: System.NotSupportedException
Error message: Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream. 
at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at FluentFTP.FtpSocketStream.<ActivateEncryptionAsync>d__88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at FluentFTP.FtpClient.<ConnectAsync>d__27.MoveNext()
```
Am I doing something wrong?

**Comment by robinrodricks** [comment]
Use AutoConnect() or AutoDetect() to find a working profile.

**Comment by yhqnh** [comment]
> Use AutoConnect() or AutoDetect() to find a working profile.

I also encountered this problem when calling GetListing. After modifying to AutoConnect, the direct connection failed.
根据验证过程，远程证书无效。   在 System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   在 System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   在 System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   在 System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   在 FluentFTP.FtpSocketStream.ActivateEncryption(String targethost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
   在 FluentFTP.FtpClient.Connect()
   在 FluentFTP.FtpClient.AutoConnect()
   在 eSupport.Publisher.ColorCalibrationService.ThreadFunction(Int32 index, List`1 subSourceFiles, StatisticalNumber statisticalNumber, FileAndEmailMidProcess item, Logger oLogger, ConcurrentDictionary`2 SyncFailedList, List`1 fileList)
