### ISSUE TITLE
Incorrect documentation for method UploadFile.

### ISSUE THREAD

**Issue by ZehCastro** [robinrodricks/FluentFTP#623]
https://github.com/robinrodricks/FluentFTP/blob/047778f536afb68fcccb8e6e4e7e906381557a2e/FluentFTP/Client/FtpClient_FileUpload.cs#L324

States it returns bool while the code actually returns FtpStatus.

**Comment by robinrodricks** [comment]
Fixed in 32.4.6.

**Comment by robinrodricks** [comment]
Released in [32.4.6](https://www.nuget.org/packages/FluentFTP/32.4.6)
