### ISSUE TITLE
System.Net.Security version

### ISSUE THREAD

**Issue by rszulczynski** [robinrodricks/FluentFTP#624]
FluentFtp uses System.Net.Security 4.3.0 which have known security issues.
https://www.cvedetails.com/vulnerability-list/vendor_id-26/product_id-39160/version_id-220168/year-2017/Microsoft-System.net.security-4.3.0.html
Please upgrade to 4.3.2

**Comment by robinrodricks** [comment]
Does this work?

[FluentFTP.32.4.6.zip](https://github.com/robinrodricks/FluentFTP/files/5298992/FluentFTP.32.4.6.zip)

**Comment by robinrodricks** [comment]
As I've upgraded the version, I'm marking this as fixed.

**Comment by robinrodricks** [comment]
Released in [32.4.6](https://www.nuget.org/packages/FluentFTP/32.4.6)
