### ISSUE TITLE
UploadDirectory fails for some files "Unable to read data from the transport connection"

### ISSUE THREAD

**Issue by manuelxmarquez** [robinrodricks/FluentFTP#626]
**FTP OS:** Windows

**FTP Server:** Serv-U FTP Server

**Computer OS:** Windows

**FluentFTP Version:** 32.4.5

Uploading a directory fails for only one file. Very similar behaviour to #577 which I also observed. However, this time it was failing in `VerifyTransfer`.

I wrapped that method in a try/catch and return false for IOException. The impact is minimal as on failure it will print a warning message and try again.

I have tested a fix and will submit a PR.

**Logs :**

Unable to read data from the transport connection: An attempt was made to access a socket in a way forbidden by its access permissions.
SocketException: An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by robinrodricks** [comment]
Released in [32.4.6](https://www.nuget.org/packages/FluentFTP/32.4.6)
