### ISSUE TITLE
GetModifiedTimeAsync unexpected results UTC/timezone

### ISSUE THREAD

**Issue by jorritvenema** [robinrodricks/FluentFTP#629]
**FTP OS:** Unix / Windows 

**FTP Server:** Unknown

**FluentFTP Version:** 
32.4.4 + 32.4.5 (cant test 32.4.6 because this version does not connect)

I expect GetModifiedTimeAsync to return timestamp from server, but get unexpected results:

- server time is 21:00 (GMT+2)
- my applications timezone/setting is 21:00 (GMT +2)
- GetModifiedTimeAsync returns 19:00 with default FptDate.Original

I expect to get 21:00 (local server timestamp) by default, and 19:00 (converted to UTC) if I set FtpDate.UTC.

**Comment by jorritvenema** [comment]
Ftp.Original sais "The date is whatever the server returns, with no conversion performed."

**Comment by robinrodricks** [comment]
Please try this:
[FluentFTP_33.0.0_BETA1.zip](https://github.com/robinrodricks/FluentFTP/files/5363506/FluentFTP_33.0.0_BETA1.zip)

Just set `TimeConversion` on the client. Try various options and let me know if it works for you.

What's new:
 - New: Reworked timezone conversion API (simply set `TimeConversion` and `TimeOffset` on the client)
 - New: `GetListing` honors the time conversion settings of the active client
 - New: `GetModifiedDate` honors the time conversion settings of the active client
 - New: `SetModifiedDate` honors the time conversion settings of the active client
 - New: Reworked API for Custom file listing parsers (simply set `ListingCustomParser` on the client)
 - Fix: Drop support for legacy file listing parsing routines (`FtpParser.Legacy` will no longer work)
 - Fix: Unexpected time conversion occuring in `GetModifiedTimeAsync`

**Comment by robinrodricks** [comment]
Added `FtpDate.UTC` option as per your line "I expect to get 21:00 (local server timestamp) by default, and 19:00 (converted to UTC) if I set FtpDate.UTC."

Please check: 
[FluentFTP_33.0.0_BETA2.zip](https://github.com/robinrodricks/FluentFTP/files/5363733/FluentFTP_33.0.0_BETA2.zip)

**Comment by robinrodricks** [comment]
If you have any suggestions as to the options of FtpDate please let me know before its released. If you can test them all it would be great.

**Comment by robinrodricks** [comment]
Please use this:
[FluentFTP_33.0.0_BETA3.zip](https://github.com/robinrodricks/FluentFTP/files/5364391/FluentFTP_33.0.0_BETA3.zip)

You need to set the server timezone in `ftpClient.TimeZone` and then the `TimeConversion` options should work.

**Comment by robinrodricks** [comment]
Added support for .NET Core (you can use `FtpDate.LocalTime` and set `client.LocalTimeZone`)

[FluentFTP_33.0.0_BETA4.zip](https://github.com/robinrodricks/FluentFTP/files/5364624/FluentFTP_33.0.0_BETA4.zip)

**Comment by robinrodricks** [comment]
Docs: https://github.com/robinrodricks/FluentFTP/wiki/Timezone-Conversion

**Comment by jorritvenema** [comment]
Thanks for your fast looking into this! I can succesfully set these properties, but I don't really get the results. Here it is.

Server time is 11:55 (timezone Netherlands = CET, or GMT+1 with daysavings so actually GMT+2)

with _ftpClient.TimeZone = 2_ (server = GMT+2) and _ftpClient.TimeConversion=0_ (to UTC)
=> mofified expected = **09:55**
=> modified actually = **07:55**

with ftpClient time properties set to 0 (server = utc, no conversion) it returns 09:55.

I think I am staying with 32.4.5 and do some conversion of my own based on server response.

**Comment by robinrodricks** [comment]
Released. https://www.nuget.org/packages/FluentFTP/33.0.0

Please reply if you have more issues with the latest version and I'll reopen.
