### ISSUE TITLE
The connection was terminated before a greeting could be read.

### ISSUE THREAD

**Issue by victormoj** [robinrodricks/FluentFTP#630]
**FTP OS:** Windows

**FTP Server:** WindowsServerIIS

**Computer OS:** Windows 10

**FluentFTP Version:** 32.4.6

When version 32.4.6 was updated, it no longer works.

The connection was terminated before a greeting could be read.

   at FluentFTP.FtpClient.Handshake()
   at FluentFTP.FtpClient.Connect()
   at ConsoleApp_20200921_0929_FluentFtpStackOverflowReproduce.Program.Main(String[] args) in C:\Users\XX\Downloads\ConsoleApp_20200921_0929_FluentFtpStackOverflowReproduce\ConsoleApp_20200921_0929_FluentFtpStackOverflowReproduce\Program.cs:line 43

**Logs :**

**Log with Version 32.4.6 ( Trace error attached.):**

Connect()
Status:   Connecting to ***:21

**Log with Version 32.4.5 (It works properly):**

Connect()
Status:   Connecting to ***:21
Response: 220 Microsoft FTP Service
Status:   Detected FTP server: WindowsServerIIS
Command:  USER ***
Response: 331 Password required
Command:  PASS ***
Response: 230 User logged in.
Command:  FEAT
Response: 211-Extended features supported:
Response: LANG EN*
Response: UTF8
Response: AUTH TLS;TLS-C;SSL;TLS-P;
Response: PBSZ
Response: PROT C;P;
Response: CCC
Response: HOST
Response: SIZE
Response: MDTM
Response: REST STREAM
Response: 211 END
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 OPTS UTF8 command successful - UTF8 encoding now ON.
Command:  SYST
Response: 215 Windows_NT

**Code**

![2020-10-11_12-26-02](https://user-images.githubusercontent.com/4082907/95676260-fb220500-0bbc-11eb-91e2-02c47a9e3919.jpg)
```

**Comment by robinrodricks** [comment]
Thanks for reporting this. Fixed in [32.4.7](https://www.nuget.org/packages/FluentFTP/32.4.7).
