### ISSUE TITLE
Adding ServerHandler with custom parser does not work

### ISSUE THREAD

**Issue by elkondzik** [robinrodricks/FluentFTP#635]
**FTP OS:** Unix / Windows / Embedded
Windows

**FTP Server:** Pure-FTPd / DrFTPD / Vsftpd / ProFTPD / Vax / VMS / OpenVMS / Tandem / HP NonStop Guardian / IBM OS400 / AS400 / Windows CE
IBM OS400 

**Computer OS:** Windows

**FluentFTP Version:** 33.0.1

I am trying to force using Custom ftp server handler, which uses custom parser like this:
<code>
            FtpClient = new FtpClient(FtpUri, Credentials);
            FtpClient.ServerHandler = new MvsServer();
            CustomParser.AddCustomParser(this.FtpClient);
            FtpClient.ListingParser = FtpParser.Custom;
</code>
My MvsServer class looks like this:
<code>

    public class MvsServer : FtpBaseServer
    {
        public override FtpServer ToEnum()
        {
            return FtpServer.Unknown;
        }
        public override bool IsAbsolutePath(string path)
        {
            return true; 
        }

        public override FtpParser GetParser()
        {
            return FtpParser.Custom;
        }
    }
</code>
Even though, it seems that adding custom server handler and custom list parser does not work.
It is always overwritten in FtpClient.Connect() by following methods:
DetectFtpServerBySyst and
DetectFtpOSBySyst

**Logs :**

```

**Comment by robinrodricks** [comment]
Good find! Try this: 
[FluentFTP_33.0.2.zip](https://github.com/robinrodricks/FluentFTP/files/5415590/FluentFTP_33.0.2.zip)

**Comment by elkondzik** [comment]
Yep it works :) Thank you very much and waiting for Nuget release ;)

**Comment by robinrodricks** [comment]
Great! Released. https://www.nuget.org/packages/FluentFTP/33.0.2
