### ISSUE TITLE
How do I install FluentFTP

### ISSUE THREAD

**Issue by ReneNyffenegger** [robinrodricks/FluentFTP#637]
**FTP OS:** n/a

**FTP Server:** n/a

**Computer OS:** Windows 10

**FluentFTP Version:** latest

I cannot seem to install FluentFTP as per instructions on https://www.nuget.org/packages/FluentFTP

Trying `Install-Package FluentFTP -Version 33.0.2` results in error message *Install-Package : A parameter cannot be found that matches parameter name 'version'.*

Trying `dotnet add package FluentFTP --version 33.0.2` results in error message *Could not find any project in `C:\WINDOWS\system32\`.*

`paket` is not a binary/executable that seems to be installed on my computer.

**Comment by robinrodricks** [comment]
Just download the zip folder from nuget site.

**Comment by robinrodricks** [comment]
https://www.nuget.org/api/v2/package/FluentFTP/33.0.2
