### ISSUE TITLE
Verifying Files from FTP to PC 

### ISSUE THREAD

**Issue by Louisj99** [robinrodricks/FluentFTP#639]
**FTP OS:** Windows

**Computer OS:** wins 10

**FluentFTP Version:**  Latest as of 30/10/20

Hi, I'm currently trying to verify the files on a PC are the same as the files on the FTP server. I'm trying to use checksum so that the file size doesn't matter however I am yet to come across a method on how to replace files that are existing on the PC but have been updated on the FTP. It downloads new files and deletes files on the PC that are not needed but if the same file already exists it fails to check if it has been updated and needs to be downloaded. 

this is what I am currently doing to download and try to check what is on the PC. 

    ` FtpClient client = new FtpClient("12.12.12.12");
				client.Credentials = new NetworkCredential("anonymous", "anonymous");

				
				foreach (FtpListItem item in client.GetListing("/@ExampleLocation"))
				{

			
					if (item.Type == FtpFileSystemObjectType.File)
					{

						
						FtpHash hash = client.GetChecksum(item.FullName);
					}

				} 

				client.Connect();

               // not used atm
				FtpCompareResult compareResult = client.CompareFile(@FileLocation, @"/@ExampleLocation", FtpCompareOption.Checksum);

				string fileLocation = @FileLocation;
                client.DownloadDirectory(fileLocation, @"/@ExampleLocation", FtpFolderSyncMode.Mirror, (FtpLocalExists)FtpVerify.Retry, FtpVerify.Delete);`                           

any help is appreciated, I know this might not be the place to post this but I wasn't sure where else to post it.

**Comment by robinrodricks** [comment]
So you want like a CompareDirectory method?

**Comment by robinrodricks** [comment]
Added to the [bucket list](https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans). We will pick this up as and when we have free time. Comment on this issue if you want us to prioritize it. Thanks!
