### ISSUE TITLE
How to determine if a custom parser is needed

### ISSUE THREAD

**Issue by zachmakki15** [robinrodricks/FluentFTP#659]
**FTP OS:** Unknown 

**FTP Server:** Unknown

**Computer OS:** ? Windows 10

**FluentFTP Version:** ? 33.02

This issue is not server or OS specific. I am having trouble trying to determine when to activate my custom parser. The code I am using to activate the custom parser is listed below.

`

    conn.ListingCustomParser = myCustomParser;

    conn.ListingParser = FtpParser.Custom;

    conn.GetListing(myRemotePath);
`

How should I determine if a directory listing format cannot be parsed by GetListing()? Calling GetListing() and checking its return does not work as the return is different for each unrecognized format. This makes it difficult to determine when to set the custom parser. Any recommendations on how to solve this?

**Comment by robinrodricks** [comment]
Not sure what you mean. This goes way outside the scope of the library. If you cannot determine which server you are connecting to, how can we? Anyway, if it helps, some basic server info that we read is parsed into these variables [listed here](https://github.com/robinrodricks/FluentFTP/wiki/Server-Information).

**Comment by zachmakki15** [comment]
I should of rephrased my issue better. GetListing() seems as though it is supposed to return an empty list when it cannot determine the format, it does not do this. Sometimes it is empty, other times it contains info such as:
FILE   <DIR>      (8 KB)
This is what makes it difficult to know when to activate the custom parser. I think a simple solution to this would be adding a method that simple allows the user to print the full directory listing to a file. Using that I can first get the listing in a file, then create my own preprocessor which will determine whether or not to activate the custom parser.

**Comment by robinrodricks** [comment]
The full listing can be accessed by the "raw" property on each item.

**Comment by zachmakki15** [comment]
Thank you for the prompt response. I will look into doing that. I actually considering opening a separate issue today but seems this also deals with directory listings, maybe I can just ask you for your input here.

Today when attempting to get a directory listing I ran into an error: "501 Syntax error in parameters or arguments." Below is the FTP tracing file from the connection. It's odd because the device lists that it supports MLSD but when we send the MLSD command it responds with the error.

''''
# Connect()
Status:   Connecting to ***:21
Response: 220 FTP server ready.   
Command:  USER ***
Response: 331 User name okay, need password.
Command:  PASS ***
Response: 230 User logged in, proceed.
Command:  FEAT
Response: 211-Features
Response: PROT
Response: PBSZ
Response: FEAT
Response: AUTH SSL
Response: AUTH TLS
Response: MLST type*;size*;modify*;
Response: MLSD
Response: 211 End
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 215 Quadros
Warning:  Cannot auto-detect listing parser for system 'Unknown', using Unix parser

# SetWorkingDirectory("/")
Command:  CWD /
Response: 250 CWD  requested file action okay, completed.

# DirectoryExists("/COMTRADE")

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/" is current directory.
Command:  CWD /COMTRADE
Response: 250 CWD  requested file action okay, completed.
Command:  CWD /
Response: 250 CWD  requested file action okay, completed.

# SetWorkingDirectory("/COMTRADE/")
Command:  CWD /COMTRADE
Response: 250 CWD  requested file action okay, completed.

# GetListing("/COMTRADE/", Auto)
Command:  TYPE I
Response: 200 TYPE Command okay.

# OpenPassiveDataStream(AutoPassive, "MLSD /COMTRADE", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||40319|).
Status:   Connecting to ***:40319
Command:  MLSD /COMTRADE
Response: 501 Syntax error in parameters or arguments.
Status:   Disposing FtpSocketStream...

# CloseDataStream()

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Response: 221 Goodbye.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
''''

**Comment by robinrodricks** [comment]
If it's a new issue please create a new issue. Easier for me to keep track
