### ISSUE TITLE
LIST via Execute method not work

### ISSUE THREAD

**Issue by boschiotto4** [robinrodricks/FluentFTP#660]
**FTP OS:** Unix / Windows / Embedded

**FTP Server:** Pure-FTPd / DrFTPD / Vsftpd / ProFTPD / Vax / VMS / OpenVMS / Tandem / HP NonStop Guardian / IBM OS400 / AS400 / Windows CE

**Computer OS:** ?
Win
**FluentFTP Version:** ?
Latest (2020-12-31)

I' trying to use the listing command. If I use the "GetListing" the command works.

FtpListItem[] items = client.GetListing("/data/", FtpListOption.ForceList); // Working good

If I use the same list of commands using:

FtpReply reply;
reply = client.Execute("TYPE I");
reply = client.Execute("EPSV");   // Issued but not supported in my case
reply = client.Execute("PRET LIST /data");
reply = client.Execute("PASV");
reply = client.Execute("LIST /data");  // Timeout

It not work. I get the command sequence using wireshark observing the "GetListing" command.

**Logs :**

```

00001|2021-01-02|12:43:56:4234|Verbose|>         GetListing("/data/", ForceList)
00002|2021-01-02|12:43:56:4333|Verbose|Command:  TYPE I
00003|2021-01-02|12:43:56:4652|Verbose|Response: 200 TYPE � ora 8-bit binary
00004|2021-01-02|12:43:56:4702|Verbose|>         OpenPassiveDataStream(AutoPassive, "LIST /data", 0)
00005|2021-01-02|12:43:56:4742|Verbose|Command:  EPSV
00006|2021-01-02|12:43:56:5031|Verbose|Response: 500 Comando sconosciuto
00007|2021-01-02|12:43:56:5071|Verbose|>         OpenPassiveDataStream(PASV, "LIST /data", 0)
00008|2021-01-02|12:43:56:5121|Verbose|Command:  PRET LIST /data
00009|2021-01-02|12:43:56:5420|Verbose|Response: 200 Ready to proceed
00010|2021-01-02|12:43:56:5450|Verbose|Command:  PASV
00011|2021-01-02|12:43:56:5739|Verbose|Response: 227 Entering Passive Mode (178,63,179,162,97,219)
00012|2021-01-02|12:43:56:5819|Verbose|Status:   Connecting to 178.63.179.162:25051
00013|2021-01-02|12:43:56:6108|Verbose|Command:  **LIST /data**
00014|2021-01-02|12:43:56:6428|Verbose|Response: 150 Connessione dati accettata
00015|2021-01-02|12:43:56:6468|Verbose|+---------------------------------------+
00016|2021-01-02|12:43:56:6517|Verbose|Listing:  -rw-rw-r--    1 396305     membri              0 Dec 31 13:51 I_FILE;
00017|2021-01-02|12:43:56:6557|Verbose|-----------------------------------------
00018|2021-01-02|12:43:56:6597|Verbose|Status:   Disposing FtpSocketStream...
00019|2021-01-02|12:43:56:6627|Verbose|>         CloseDataStream()
00020|2021-01-02|12:43:56:6687|Verbose|Response: 226-Options: -l
00021|2021-01-02|12:43:56:6707|Verbose|Response: 226 1 corrispondenze totali
00022|2021-01-02|12:43:56:6737|Verbose|Status:   Disposing FtpSocketStream...
00023|2021-01-02|12:43:56:6836|Verbose|Status:   Confirmed format Unix
00024|2021-01-02|12:43:56:6966|Verbose|Command:  TYPE I
00025|2021-01-02|12:43:56:7275|Verbose|Response: 200 TYPE � ora 8-bit binary
00026|2021-01-02|12:43:56:7305|Verbose|Command:  EPSV
00027|2021-01-02|12:43:56:7594|Verbose|Response: 500 Comando sconosciuto
00028|2021-01-02|12:43:56:7634|Verbose|Command:  PRET LIST /data
00029|2021-01-02|12:43:56:7934|Verbose|Response: 200 Ready to proceed
00030|2021-01-02|12:43:56:7963|Verbose|Command:  PASV
00031|2021-01-02|12:43:56:8293|Verbose|Response: 227 Entering Passive Mode (178,63,179,162,74,106)
00032|2021-01-02|12:43:56:8352|Verbose|Command:  **LIST /data**
00033|2021-01-02|12:44:11:8431|Verbose|Status:   Disposing FtpSocketStream...
00034|2021-01-02|12:44:13:9844|Verbose|Timed out trying to read data from the socket stream!

Sorry for the italian, but the code are explanatory

```

**Comment by robinrodricks** [comment]
Why are you trying to do this by Execute method? It's not designed for such things, it wont work, because listing needs another data to be opened to get the actual file listing.

Listing must be done with [GetListing](https://github.com/robinrodricks/FluentFTP/wiki/Directory-Listing), you can read the docs of the method for all [flags and stuff](https://github.com/robinrodricks/FluentFTP/wiki/Enum-FtpListOption).

**Comment by boschiotto4** [comment]
Hi robin, thanks for the response. You are right...the library is working. Simply I need something to get a file name in a folder.
To perform this operation using the "GetListing" I will perform all the indicated commands additionally to the LIST. For example I will provide the "TYPE I" command which I can provide only one time at first. I will use more data exchange than necessary. So I was thinking of use the ExecuteCommands to reduce the data exchange; but as you indicate it required more than the simple command LIST to list a folder. I don't know the relative RFC, but is it right to issue every time the whole list of commands to perform this LIST operation?
