### ISSUE TITLE
501 Syntax error in parameters or arguments.

### ISSUE THREAD

**Issue by zachmakki15** [robinrodricks/FluentFTP#662]
**FTP OS:** Unknown

**FTP Server:** Unknown

**Computer OS:** ? Windows 10

**FluentFTP Version:** ? 33.0.3

Today when attempting to get a directory listing I ran into an error: "501 Syntax error in parameters or arguments." This seems to be a device specific issue as this is the first time I have seen this error. Below is the FTP tracing file from the connection. It's odd because the device lists that it supports MLSD but when we send the MLSD command it responds with the error. I don't believe there is any issue with the library just looking for any advice on how to work around this?

```

# Connect()
Status:   Connecting to ***:21
Response: 220 FTP server ready.   
Command:  USER ***
Response: 331 User name okay, need password.
Command:  PASS ***
Response: 230 User logged in, proceed.
Command:  FEAT
Response: 211-Features
Response: PROT
Response: PBSZ
Response: FEAT
Response: AUTH SSL
Response: AUTH TLS
Response: MLST type*;size*;modify*;
Response: MLSD
Response: 211 End
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 215 Quadros
Warning:  Cannot auto-detect listing parser for system 'Unknown', using Unix parser

# SetWorkingDirectory("/")
Command:  CWD /
Response: 250 CWD  requested file action okay, completed.

# DirectoryExists("/COMTRADE")

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/" is current directory.
Command:  CWD /COMTRADE
Response: 250 CWD  requested file action okay, completed.
Command:  CWD /
Response: 250 CWD  requested file action okay, completed.

# SetWorkingDirectory("/COMTRADE/")
Command:  CWD /COMTRADE
Response: 250 CWD  requested file action okay, completed.

# GetListing("/COMTRADE/", Auto)
Command:  TYPE I
Response: 200 TYPE Command okay.

# OpenPassiveDataStream(AutoPassive, "MLSD /COMTRADE", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||40319|).
Status:   Connecting to ***:40319
Command:  MLSD /COMTRADE
Response: 501 Syntax error in parameters or arguments.
Status:   Disposing FtpSocketStream...

# CloseDataStream()

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Response: 221 Goodbye.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...


```

**Comment by hornell** [comment]
I may be misreading the RFC on this, but are you supplying just the directory name ("COMTRADE") or are you including the leading "/"? 
If you're including the "/", does it work without it?

**Comment by zachmakki15** [comment]
Thank you for the suggestion, I am currently supplying the directory name with the leading "/". I will take that out and test again. Unfortunately a user of my software is who reported this issue to me, so it may take a few days before I get the test results back. Once I get the result from that test I will post an update.

**Comment by zachmakki15** [comment]
Was able to get test results from the user today, unfortunately we tried two different methods of attempting to retrieve the directory listing and both failed. Snippets from from the tracing file produced by both tests are listed below, please let me know your thoughts. Not exactly sure how to format the logs here so my apologies if it looks sloppy.

Test with no slash:

# DirectoryExists("/COMTRADE")

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/" is the current directory
Command:  CWD /COMTRADE
Response: 250 CWD command successful
Command:  CWD /
Response: 250 CWD command successful

# SetWorkingDirectory("/COMTRADE/")
Command:  CWD /COMTRADE
Response: 250 CWD command successful

# GetListing("COMTRADE", Auto)

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/COMTRADE" is the current directory
Command:  TYPE I
Response: 200 Type set to I

# OpenPassiveDataStream(AutoPassive, "MLSD /COMTRADE/COMTRADE", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||49680|)
Status:   Connecting to ***:49680
Command:  MLSD /COMTRADE/COMTRADE
Response: 550 /COMTRADE/COMTRADE: No such file or directory
Status:   Disposing FtpSocketStream...

# CloseDataStream()


Test with empty parameter:

# DirectoryExists("/COMTRADE")

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/" is current directory.
Command:  CWD /COMTRADE
Response: 250 CWD  requested file action okay, completed.
Command:  CWD /
Response: 250 CWD  requested file action okay, completed.

# SetWorkingDirectory("/COMTRADE/")
Command:  CWD /COMTRADE
Response: 250 CWD  requested file action okay, completed.

# GetListing(null, Auto)

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/COMTRADE" is current directory.
Command:  TYPE I
Response: 200 TYPE Command okay.

# OpenPassiveDataStream(AutoPassive, "MLSD /COMTRADE", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||49680|).
Status:   Connecting to ***:49680
Command:  MLSD /COMTRADE
Response: 501 Syntax error in parameters or arguments.
Status:   Disposing FtpSocketStream...

# CloseDataStream()

**Comment by zachmakki15** [comment]
I was able to work around this by forcing the LIST command, I think this specific device had an incorrect implementation of the MLSD command, thank you for the support
