### ISSUE TITLE
FileUpload doesn't fully support non-seekable streams

### ISSUE THREAD

**Issue by novak-as** [robinrodricks/FluentFTP#668]
FluentFtp version: 33.0.3

LOC: https://github.com/novak-as/FluentFTP/blob/master/FluentFTP/Client/FtpClient_FileUpload.cs#L724

```
"FluentFTP.FtpException: Error while uploading the file to the server. See InnerException for more info.
 ---> System.NotSupportedException: Specified method is not supported.
   at System.Net.Http.HttpBaseStream.get_Length()
   at FluentFTP.FtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
   --- End of inner exception stack trace ---
   at FluentFTP.FtpClient.UploadFileInternalAsync(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress, CancellationToken token, FtpProgress metaProgress)
   at FluentFTP.FtpClient.UploadAsync(Stream fileStream, String remotePath, FtpRemoteExists existsMode, Boolean createRemoteDir, IProgress`1 progress, CancellationToken token)
  ...
```

Stream type:
```
{Name = "ContentLengthReadStream" FullName = "System.Net.Http.HttpConnection+ContentLengthReadStream"}
    Assembly: {System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a}
    AssemblyQualifiedName: "System.Net.Http.HttpConnection+ContentLengthReadStream, System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" ...
```

There is a [check](https://github.com/novak-as/FluentFTP/blob/master/FluentFTP/Client/FtpClient_FileUpload.cs#L702) for not-seekable streams, but `Length` also throws `NotSupportedException` if steam isn't seekable (https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.length?view=netcore-3.1)

**Comment by robinrodricks** [comment]
This is correct. Some users have worked around by first buffering their stream into a MemoryStream or similar and then giving it to FluentFTP. Due to technicalities, we NEED to know the length of the file otherwise we cannot transfer it.

If you think it is a bug and that its possible to support non-seekable streams, you are welcome to submit a PR.

**Comment by Jehoel** [comment]
> If you think it is a bug and that its possible to support non-seekable streams, you are welcome to submit a PR.

I blame the design of `System.IO.Stream`. I understand the .NET BCL team agrees it's poorly designed - [hence the love for the new `System.IO.Pipelines`](https://devblogs.microsoft.com/dotnet/system-io-pipelines-high-performance-io-in-net/).

I'm not really able to submit a PR, but I would propose _not_ using `Stream` directly, but instead requiring all input to be using a simple wrapper `struct` which means more cases can be handled:

```
struct StreamWithLength
{
    public static implicit operator Stream(StreamWithLength self) => self.Stream;

    // Implicit conversion for known-good Stream subclasses:
    public static implicit operator StreamWithLength(FileStream fs) => new StreamWithLength( fs );
    public static implicit operator StreamWithLength(MemoryStream ms) => new StreamWithLength( ms );

    public StreamWithLength( Stream stream, Int64 length )
    {
        this.Stream = stream ?? throw new ArgumentNullException(nameof(stream));
        this.Length = length; // TODO: Validate length?
    }

    // Specialized constructors:

    public StreamWithLength( FileStream fileStream )
        : this( stream: fileStream, length: fileStream.Length )
    {
    }

    public StreamWithLength( MemoryStream ms )
        : this( stream: ms, length: ms.Length )
    {
    }

    public Int64 Length { get; }
    public Stream Stream { get; }
}
```

As it has implicit conversion to/from `Stream` it should be a drop-in replacement.

**Comment by daviatorstorm** [comment]
Here is a good implementation of non-seekable streams. Rather then calculate progress for user you can return total sent bytes and user can do his own progress implementation.

https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet/SftpClient.cs#L2274
