### ISSUE TITLE
[Question] Pause Resume uploads and download with Fluent FTP

### ISSUE THREAD

**Issue by davidbuckleyni** [robinrodricks/FluentFTP#671]
Is their a way with Fluent FTP the way it stands to offer the ability the same as filezillia does to pause and resume uploads and downloads  to ftp.

**Comment by robinrodricks** [comment]
Most methods support resuming. Just call [UploadFile/DownloadFile](https://github.com/robinrodricks/FluentFTP/wiki/File-Transfer) again and it should automatically resume (at least that was the last supported behavior AFAIK).
