### ISSUE TITLE
GetListing using wildcard returning incorrect FullName

### ISSUE THREAD

**Issue by JORDAAAN1495** [robinrodricks/FluentFTP#672]
**FTP OS:** Unix

**FTP Server:** Pure-FTPd

**Computer OS:** Windows 10

**FluentFTP Version:** 33.0.3

When running a GetListing or GetListingAsync using a wildcard in the search path, the FullName is being returned with the wildcard instead of the full directory of the file/directory.

Code Helper:

        private static async Task<List<FtpListItem>> GetFtpErroredFiles()
        {
            using (FtpClient ftpClient = new FtpClient(FtpHostName))
            {
                ftpClient.Credentials = new System.Net.NetworkCredential(FtpUserName, FtpPassword);

                await ftpClient.ConnectAsync();

                string ftpSearchPath = $"*/live/deliveries/";

                var result = await ftpClient.GetListingAsync(ftpSearchPath);

                List<FtpListItem> ftpListItems = result.
                    Where(file => file.Type == FtpFileSystemObjectType.File && file.Name.ToLower().StartsWith(FtpSearchPrefix))
                    .ToList();

                return ftpListItems;
            };
        }

Usage:

            List<FtpListItem> ftpErroredFiles = await GetFtpErroredFiles();

            foreach (var item in ftpErroredFiles)
            {
                Console.WriteLine(item.FullName);
            }

Example Output:

![image](https://user-images.githubusercontent.com/55707640/106354716-c4970400-62eb-11eb-9fe0-9e1382dfad4f.png)

**Comment by robinrodricks** [comment]
This seems to be server specific syntax. I was not aware that wildcard search was supported. We will have to add support for it.

**Comment by JORDAAAN1495** [comment]
Hi Robin

Very strange as I tried the same code a few days later and it "magically" started working. So I assume it was an issue with our FTP server.

Works completley fine now so rather odd but like I say more than likely a local issue.

Thank you, and thanks for creating/maintaining a great project here :)

**Comment by robinrodricks** [comment]
Glad it got sorted. You are most welcome.
