### ISSUE TITLE
FTP server with duplicate files

### ISSUE THREAD

**Issue by JYouren** [robinrodricks/FluentFTP#674]
**FTP OS:** Windows

**FTP Server:** Unknown

**Computer OS:** Windows 10

**FluentFTP Version:** 33.0.3

I have a requirement where the FTP server has duplicate files, and so when downloading the files I need to give them new unique names. As the library uses filenames to reference remote files, how do I know which file I am downloading, and more to the point, how do I specify exactly which file I need.

**Logs :**

N/A

**Comment by robinrodricks** [comment]
I think this is way out of scope of a data transfer library like FluentFTP. I think you need a DB with the CRC32 codes of each file. When you want to upload/download a file you can compute its CRC32 and see if a duplicate exists, if not, then it is a new file, else, the DB will tell you the name of the current file. The schema of the duplicate-tracking table may look like:

`ID | CRC32 | FilenameOnServer`

As I said this is totally out of scope of FluentFTP but I hope that helps.
