### ISSUE TITLE
GetListing() with a filepath : problems and workarounds

### ISSUE THREAD

**Issue by cyberangel** [robinrodricks/FluentFTP#68]
Calling FtpClient.GetListing method with a file path, e.g. "/remote_folder/file.zip",
returns an instance of FtpListItem with FullName="/remote_folder/file.zip/file.zip".

**Comment by hgupta9** [comment]
What is the issue exactly? What behavior do you expect?

**Comment by cyberangel** [comment]
Hello, sorry for not responding, I forgot about it as I had to find a different solution.

Well, the issue is that the path in FullName does not exist. FullName in my example should be "/remote_folder/file.zip".

**Comment by hgupta9** [comment]
I've upgraded the GetListing() file listing parser to include OS-specific parsers. This may resolve your issue. If you are interested in helping debug this, then please use this beta build and give me feedback: 

- [FluentFTP_16.6_BETA.rar](https://we.tl/YiWHrDYJxq)

**Comment by hgupta9** [comment]
Can you try the latest nuget release and see if it still happens?

https://www.nuget.org/packages/FluentFTP/17.0.0

**Comment by cyberangel** [comment]
I'm sorry, not at the moment. I'll see if I can try it tomorrow in the evening.
I appreciate you looking into it, but since I had to develop a different solution due to the bug, it'll take me some time.

**Comment by cyberangel** [comment]
Hello. I wanted to try the new release, but nuget update encounters the error "'FluentFTP' already has a dependency defined for 'System.Runtime'."
I tried to uninstall the package and install it again, but the error occurs nonetheless.

Guess the nuget package has a problem?

**Comment by hgupta9** [comment]
I'm sorry but your nuget exe is too old. Which VS are you using? Solutions in the [FAQ](https://github.com/hgupta9/FluentFTP#troubleshooting)

**Comment by hgupta9** [comment]
Okay I've listed a new nuget version can you see if that installs ok?

https://www.nuget.org/packages/FluentFTP/17.2.0

**Comment by hgupta9** [comment]
You can try with your current nuget.exe. I changed something in the nuspec to check if it solves your `"FluentFTP' already has a dependency defined for 'System.Runtime"` problem

**Comment by cyberangel** [comment]
Thank you, version 17.2.0 updates just fine. Proceeding to test the GetListing fix.

**Comment by cyberangel** [comment]
I can confirm the bug is sadly still present.
![image](https://cloud.githubusercontent.com/assets/135760/26007301/299865be-3740-11e7-9894-aa334c39e1ec.png)

**Comment by hgupta9** [comment]
Okay I think the issue here is you are calling GetListing for a filepath, typically you must call with:

- GetListing("/Vyvoj/")

If you want info about a single file please use:

- GetObjectInfo("/Vyvoj/myfile.isdoc")

**Comment by cyberangel** [comment]
Yeah, I figured as much, BUT:
1) it makes no sense to return a path that doesn't exist
2) it doesn't throw an exception stating it doesn't support file path, only directory path
3) I specifically wrote in the original post "Calling FtpClient.GetListing method with a file path" to not leave a room for doubt and included an example

Don't get me wrong, I love this library, appreciate your dedication to this project.

**Comment by hgupta9** [comment]
I'm sorry for the weird behavior. You know we could include additional checks to see if its a dir or file, but in most cases this is hard to detect. You could pass a dir like this `/mydir` or like this `/mydir/` and dirs can contain dots like `/mydir.mywhatever/` so its not easy to detect from the path alone. We would have to use another FTP command (or multiple commands) to detect this and people are already complaining about the slow speed so the motivation to do this is low. 

Currently on the readme I have added the GetObjectInfo() just below GetListing() so hopefully future users will easily discover it. Its by design that we have different methods for dirs and files like FileExists() and DirectoryExists() or DeleteFile() and DeleteDirectory() which have wildly different code/implementation due to the crazyness of FTP protocol.

Can you try with GetObjectInfo() and if it works I'll close this issue. Thanks for understanding.

**Comment by cyberangel** [comment]
Ok, close it. I understand the performance reasons for detecting whether it's a directory or file.
Have a good day, sir. O7

**Comment by blkbltjns** [comment]
FYI I ran into this same issue and it took some time to figure out what was wrong (I figured it out after seeing this github issue). It would be nice if it would throw an exception stating to use GetObjectInfo for single file listings, or just have GetListing return a proper FtpListItem object. Not sure how to do this, but just my 2 cents as an end user of this library. Thanks!

**Comment by DosU13** [comment]
Hello, 

> Okay I think the issue here is you are calling GetListing for a filepath, typically you must call with dir path only:
> 
> * GetListing("/Vyvoj/")
> 
> If you want info about a single file please use:
> 
> * GetObjectInfo("/Vyvoj/myfile.isdoc")

How can I tell a path if it's a file or folder

**Comment by FanDjango** [comment]
Each FtpListItem from the GetListing contains a flag telling you that.

**Comment by TJR-Andel** [comment]
I ran into this same problem. In my case the path is user-configured, so I don't know in advance whether it is a file or a directory. On the FTP server I am targetting (which is not my own) GetObjectInfo fails, so the only info I can get is through GetListing.
The result I get from GetListing by using the path to a directory containing only one file, and using the path directly to the file, is the same, except in the later case as people have reported the path to the file gets mangled.

After testing around a bit I found the following:
```
bool dir1Exists = await client.DirectoryExists("<existing directory path>"); // returns true
bool dir2Exists = await client.DirectoryExists("<existing directory path>/"); // returns true
bool dir3Exists = await client.DirectoryExists("<existing directory path>/<existing filename>"); // return false
bool file1Exists = await client.FileExists("<existing directory path>"); // returns true
bool file2Exists = await client.FileExists("<existing directory path>/"); // returns true
bool file3Exists = await client.FileExists("<existing directory path>/<existing filename>"); // returns true
```
So the DirectoryExists seems to be able to detect whether it is a file or not, while FileExists is not able to detect this. In my case the overhead of calling DirectoryExists on the path is acceptable. 
Hopefully others can use this as well.

**Comment by FanDjango** [comment]
@TJR-Andel  Be nice to know, which command is actually used on the FTP control connection, for your GetListing, is it MLST, LIST or whatever. You can "force" LIST to be used, for example, even STAT. Also, what are the reported capabilites of the server (response to FEAT command)?
Why does GetObjectInfo fail? MLST not supported?
The response to GetListing may vary according to server but also according to the underlying FTP command (MSLT, LIST, NLST, etc.).
Anyway thanks for the tests - seems you found a way to differentiate.

**Comment by FanDjango** [comment]
@TJR-Andel To bad you didn't post the log

**Comment by TJR-Andel** [comment]
Something like this?

```
# AutoConnect()

# AutoDetect(True, False)

# Connect(False)
Status:   FluentFTP 46.0.2.0
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220 Microsoft FTP Service [738598,612d]
Status:   Detected FTP server: WindowsServerIIS
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 234 AUTH command ok. Expecting TLS Negotiation. [23ms]
Warning:  SSL Buffering force disabled, is .NET 5.0 and later
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 44550, 384) [96ms]
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Password required [24ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230 User logged in. [18ms]
Command:  PBSZ 0
Status:   Waiting for response to: PBSZ 0
Response: 200 PBSZ command successful. [27ms]
Command:  PROT P
Status:   Waiting for response to: PROT P
Response: 200 PROT command successful. [17ms]
Command:  FEAT
Status:   Waiting for response to: FEAT
Response: 211-Extended features supported:
Response: LANG EN*
Response: UTF8
Response: AUTH TLS;TLS-C;SSL;TLS-P;
Response: PBSZ
Response: PROT C;P;
Response: CCC
Response: HOST
Response: SIZE
Response: MDTM
Response: REST STREAM
Response: 211 END [21ms]
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Status:   Waiting for response to: OPTS UTF8 ON
Response: 200 OPTS UTF8 command successful - UTF8 encoding now ON. [20ms]
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 Windows_NT [25ms]
Status:   Listing parser set to: Windows
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/" is current directory. [25ms]

# GetListing("<directory path>", Auto)
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Type set to I. [23ms]

# OpenDataStreamAsync("LIST /<directory path>", 0)

# OpenPassiveDataStreamAsync(PASV, "LIST /<directory path>", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (212,237,249,131,123,125). [28ms]
Status:   Connecting to IP #1= ***:31613
Command:  LIST /<directory path>
Status:   Waiting for response to: LIST /<directory path>
Response: 125 Data connection already open; Transfer starting. [19ms]
Warning:  SSL Buffering force disabled, is .NET 5.0 and later
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 44550, 384) [25ms]
+---------------------------------------+
Listing:  01-12-23  01:43PM                49522 <file1>.csv
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: LIST /<directory path>
Response: 226 Transfer complete. [104ms]
Status:   Closing/Disposing FtpSocketStream(data connection)
Status:   Confirmed format Windows

# GetListing("/<directory path>/<file1>.csv", Auto)

# OpenDataStreamAsync("LIST /<directory path>/<file1>.csv", 0)

# OpenPassiveDataStreamAsync(PASV, "LIST /<directory path>/<file1>.csv", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (212,237,249,131,123,126). [22ms]
Status:   Connecting to IP #1= ***:31614
Command:  LIST /<directory path>/<file1>.csv
Status:   Waiting for response to: LIST /<directory path>/<file1>.csv
Response: 125 Data connection already open; Transfer starting. [17ms]
Warning:  SSL Buffering force disabled, is .NET 5.0 and later
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 44550, 384) [19ms]
+---------------------------------------+
Listing:  01-12-23  01:43PM                49522 <file1>.csv
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: LIST /<directory path>/<file1>.csv
Response: 226 Transfer complete. [54ms]
Status:   Closing/Disposing FtpSocketStream(data connection)
```

**Comment by FanDjango** [comment]
Yes, thanks. Nobody in this thread ever debugged this sensibly. Linux listings look different. Nobody ever posted a log, server type etc. In a linux listing we can parse that it is a directory. This is windows, so duh.

But it is interesting to see your difference in behaviour for DirectoryExists and FileExists, I will have a look at that...

**Comment by FanDjango** [comment]
@TJR-Andel 

`LIST /<directory path>`
`01-12-23  01:43PM                49522 <file1>.csv`

`LIST /<directory path>/<file1>.csv`
`01-12-23  01:43PM                49522 <file1>.csv`

And your (excellent) table of results:

```
bool dir1Exists = await client.DirectoryExists("<existing directory path>"); // returns true
bool dir2Exists = await client.DirectoryExists("<existing directory path>/"); // returns true
bool dir3Exists = await client.DirectoryExists("<existing directory path>/<existing filename>"); // return false
bool file1Exists = await client.FileExists("<existing directory path>"); // returns true
bool file2Exists = await client.FileExists("<existing directory path>/"); // returns true
bool file3Exists = await client.FileExists("<existing directory path>/<existing filename>"); // returns true
```

For each of these, one should look at the log. Actually, only post the log for the `FileExist` cases.

Why? Because:

`FileExists` will try to use the `SIZE` command, if not possible, the `MDTM` command, or finally the `NLST` command to decide if the file exists. Thus it suffers from possible misreporting by the operating system and possible wrong interpretation of your path string.

**`DirectoryExists` does its work differently**. It tries to change the working directory to the specified path string (and afterwards back to the original WD). This **should** fail if the string denotes a file or does not exist as a folder. **If you think about it, this is the reason why it works quite well**. It is delegating the question of folder existance to the underlying file system code. Nothing gets reported back and thus cannot be mangled.

Perhaps you could check for file existance by a double call:

1. Check if it is a directory
2. If it is a driectory, well then, that's that.
3. If **not** and FileExists reports true, shouldn't we assume the thing that exists is a file?

Just thinking...

**Comment by TJR-Andel** [comment]
Here are the logs for the first and last of the fielExists cases (the middle case yields the exact same log as the first case and was really only a catch-all test). As far as I can see it confirms what you described 1:1.
I ended up using the exact same approach that you also suggested by using a double call.

Anyway, here are the logs just to back up your description:
```
# FileExists("<directory path>")
Command:  SIZE /<directory path>
Status:   Waiting for response to: SIZE /<directory path>
Response: 550 Access is denied.  [12ms]
Command:  MDTM /<directory path>
Status:   Waiting for response to: MDTM /<directory path>
Response: 550 The specified path is invalid.  [12ms]

# GetNameListing("/<parent directory path>")
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Type set to I. [10ms]

# OpenDataStreamAsync("NLST /<parent directory path>", 0)

# OpenPassiveDataStreamAsync(PASV, "NLST /<parent directory path>", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (212,237,249,131,117,140). [11ms]
Status:   Connecting to IP #1= ***:30092
Command:  NLST /<parent directory path>
Status:   Waiting for response to: NLST /<parent directory path>
Response: 125 Data connection already open; Transfer starting. [17ms]
Warning:  SSL Buffering force disabled, is .NET 5.0 and later
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 44550, 384) [10ms]
+---------------------------------------+
Listing:  /<directory path>
Status:   Closing/Disposing FtpSocketStream(data connection)

# CloseDataStream()
Status:   Waiting for response to: NLST /<parent directory path>
Response: 226 Transfer complete. [46ms]
+---------------------------------------+
Status:   Closing/Disposing FtpSocketStream(data connection)

# FileExists("<directory path>/<file1>.csv")
Command:  SIZE /<directory path>/<file1>.csv
Status:   Waiting for response to: SIZE /<directory path>/<file1>.csv
Response: 213 49522 [11ms]
```

**Comment by FanDjango** [comment]
Thanks for that!

You would agree that this is now "analyzed" more or less adequately.

`DirectoryExists` works reliably.
`FileExists` works reliably, **unless it needs to resort to using** `NLST`. Why did it need to resort to `NLST`? Well, because `MDTM` and `SIZE` were not amongst the supported `FEAT`ures.

> I ended up using the exact same approach that you also suggested by using a double call.

Here is a possible idea: In the code of `FileExists`, add code to check a `DirectoryExists` as corroboration, if `NLST` needed to be used.

**Comment by FanDjango** [comment]
As to the original issue topic:
================== 

A bug was reported (ages ago) where the `.fullname` was being incorrectly set. And discussion set in about calling `GetListing` with a dirPath or a filePath.

The consensus was: **Call it with a dirPath**.

If you call it with a filePath, depending on the underlying operating system, interesting things can happen. It won't fail on all server types. But surely it is not what you wanted. 

Then someone asked: **How can I know if a path (perhaps entered by a user) is a dirPath or a filePath, to avoid surprising things happening?**

Someone also said: "Couldn't we check if it is a dirPath". IMO, yes, we should check this in case we need to use `LIST`. How to check? See above, `DirectoryExists`, you can do this yourself prior to a `GetListing`.

That question led to `DirectoryExists` vs. `FileExists` being discussed recently in this issue.

**Comment by FanDjango** [comment]
After registering the possible enhancement I have moved this to the Wiki: https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans
