### ISSUE TITLE
Unable to connect to FTPS using static method 

### ISSUE THREAD

**Issue by Apollo3zehn** [robinrodricks/FluentFTP#681]
I am trying to connect to a FTPS server with invalid certificate, so I need to skip certificate validation. I am using Powershell to run the following code:

```
$ftpClient = [FluentFtp.FtpClient]::Connect("ftps://$($userName)@$($hostName):$($port)", $false) # false = do not check certificate
```

Unfortunately, I get the error `Exception calling "Connect" with "2" argument(s): "SSL/TLS required on the control channel"`. I think this is because the static `Connect` method is not setting the `EncryptionMode` to use explicit TLS although the url begins with `ftps://...`. See here https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Client/FtpClient_Static.cs#L15.

I am also unable to instantiate `FtpClient` using its constructor and then add a callback to the `ValidateCertificate` event, because the callbacks seems to be invoked on a different thread which Powershell doesn't like. So my hopes are in the static `Connect` method.

**FTP OS:** Windows
**FTP Server:** FTPS Server
**Computer OS:** Windows 10 x64
**FluentFTP Version:** 33.0.3

**Comment by robinrodricks** [comment]
Don't use the static methods. They are old and only provided for backwards compatibility. For powershell you can use the dynamic FtpClient object, it works.
