### ISSUE TITLE
Initializing TLS Auth Hangs on .NET 5

### ISSUE THREAD

**Issue by dicksongwong** [robinrodricks/FluentFTP#682]
**FTP OS:** Unknown

**FTP Server:** hostedftp.com

**Computer OS: Windows 10 / Windows Server 2019

**FluentFTP Version:** 33.0.3

We've been using FluentFTP to connect to a hostedftp.com for a number of years but when we upgraded from .NET Framework 4.7 to .NET 5, it now hangs trying to initialize the TLS connection until it times out. I've reproduced this in a console app where the code below will work if targeting .NET Core 3.1, but fail when targeting .NET 5.  If FtpEncryptionMode is set to  None then I am able to connect.

Debugging into disassembled code, it appears it is hanging when FtpSocketStream.cs invokes SslStream.AuthenticateAsClientAsync() and within that ReceiveBlobAsync(). 

Fortunately, hostedftp.com has a demo/public ftp account that can be used to test and reproduce this.  I haven't seen this issue with other ftp servers so it could be hostedftp but at the same time, it seems odd to have a different outcome depending on the target framework.

My code is as follows:
```
            // Anonymous login
            var ftpClient = new FtpClient("ftp.hostedftp.com");
            ftpClient.OnLogEvent = (level, s) => Console.WriteLine(s);
            ftpClient.EncryptionMode = FtpEncryptionMode.Explicit;
            ftpClient.Connect();
            
            Console.WriteLine(ftpClient.ConnectionType);
            Console.WriteLine(ftpClient.IsConnected);
            ftpClient.Disconnect();
```

**Logs :**

```
>         Connect()
Status:   Connecting to 52.32.19.90:21
Response: 220 Service ready for new user.
Command:  AUTH TLS
Response: 234 Command AUTH okay; starting TLS connection.
Unhandled exception. System.AggregateException: One or more errors occurred. ( Received an unexpected EOF or 0 bytes from the transport stream.)
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at FluentFTP.FtpSocketStream.ActivateEncryption(String targethost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
   at FluentFTP.FtpClient.Connect()
   at ConsoleApp1.Program.UseFluentFtp() in C:\Users\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 45
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 19
```

**Comment by robinrodricks** [comment]
Good find! I'll test it and let you know.

**Comment by kapsiR** [comment]
I've the same problem with a TLS 1.2 only server, but I don't get an exception:
The logs:
> Response: 220-Welcome on *redacted*
> Response: 220 *redacted* - No anonymous login
> Command:  AUTH TLS
> Response: 234 AUTH TLS OK.

I'm calling `await ftpClient.ConnectAsync();` and it waits forever... (it makes no difference if I call the sync version of the method)

**Comment by belangervince** [comment]
we have the same issue

**Comment by robinrodricks** [comment]
@kapsiR Is it only with .NET 5? Should I turn off SslBuffering by default in .NET 5?

**Comment by kapsiR** [comment]
@robinrodricks Yes, that's only with .NET 5.

**Comment by kapsiR** [comment]
@robinrodricks As a workaround, yes for sure. 

I'm not familiar enough with the SslBuffering feature, so I can't really decide that for future use cases 😉

**Comment by robinrodricks** [comment]
Fixed by disabling SslBuffering in .NET 5.0. Does it work for you now?

https://www.nuget.org/packages/FluentFTP/33.1.2

**Comment by kapsiR** [comment]
Yes, I verified it by updating my .NET 5 project to v33.1.2. 👍

**Comment by robinrodricks** [comment]
Great, thank you!
