### ISSUE TITLE
Issues connection to an SFTP Server. No problem with filezilla

### ISSUE THREAD

**Issue by RHaughton** [robinrodricks/FluentFTP#687]
Hello,

I'm having issues to connect to a SFTP Server that I have 0 issues with Filezilla.

I Tried Passive mode, Settings all SSLProtocols, EncryptionMode Implicit but with no sucess.

When I don't have Encryption Mode = Implicit I get this error: "Unable to read data from the transport connection"
When I put Encription Mode = implicit I get this one: "Cannot determine the frame size or a corrupted frame was received."

I tried everything. Could anyone help me?

**Comment by EvilVir** [comment]
Could you please tell what you did to fix your issue? Facing same problem here.

**Comment by KurogamiLight3303** [comment]
I'm having the same issue

**Comment by FanDjango** [comment]
@KurogamiLight3303 SFTP is a totally different animal than FTP or FTPS.

**Comment by aravindk777** [comment]
Does this means, FluentFTP doesnt support SFTP?

**Comment by FanDjango** [comment]
FluentFTP is a fully managed FTP and FTPS client library for .NET & .NET Standard.

Do you see "SFTP" in there anywhere?
