### ISSUE TITLE
Use with Universal Windows apps?

### ISSUE THREAD

**Issue by CriticalCauchy** [robinrodricks/FluentFTP#69]
Hi,
Is it possible to use FluentFTP in conjunction with UWP (universal windows) apps?
I created a .NET Core library and added the current version of FluentFTP via NuGet. In my UWP app, I created a reference to the library build (.dll). 

I added {"imports": "netstandard1.4"} to the uwp app project.json.
When I try to create a class from the library, I receive this error:
>  Could not load file or assembly 'FluentFTP, Version=16.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. 

Is is right that I would need netstandard 1.6 for the .Net Core lib but uwp only supports 1.4?
What can I do to use this library in my UWP app?
Thanks!

**Comment by hgupta9** [comment]
I'll try to compile it for net 1.4 and/or UWP...

**Comment by hgupta9** [comment]
I've managed to compile the [latest version ](https://www.nuget.org/packages/FluentFTP/16.4.0) for .Net Standard 1.4

**Comment by ManuSchm** [comment]
Hi, I also try to use FluentFTP in my UWP project.
Thank you for your effort, unfortunately I'm still not able to use FluentFTP.
When I try to install the package following output Message is generated by VS2015:
System.Net.Security 4.3.0 provides a compile-time reference assembly for System.Net.Security on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.

**Comment by CriticalCauchy** [comment]
Thanks for your help hgupta9.
Unfortunately, I wasn't able to get it started. I mainly tested in VS15, but I also tried VS17 with the newest updates.

**Comment by hgupta9** [comment]
I'm installing the UWP tools for VS 2017 so I can test it myself. Stay tuned!

**Comment by hgupta9** [comment]
Dammit. I installed UWP tool but I can only open/use a UWP project on Windows 10. Currently my machine is Windows 7 and I don't plan on upgrading :(

**Comment by CriticalCauchy** [comment]
Yes, that's really annoying. I did the same mistake. I then installed Win10+VS on a virtual machine. It worked but it was too slow and cumbersome. For me, the best solution was to create an additional Win10 system on a separate partition.
When I find some time, I'll try again. Besides, things may change with .NET Standard 2.0.

**Comment by hgupta9** [comment]
FluentFTP is now compiled for .Net Standard 1.4 and UWP 10.
Can you check and see if it works for your project?

https://www.nuget.org/packages/FluentFTP/

**Comment by FloppyNotFound** [comment]
At least it's not working for ARM-Devices, because of System.Threading.Thread which is not available for ARM.

Is it possible to remove this dependency?

**Comment by hgupta9** [comment]
I'll try to remove the dependency on System.Threading.Thread.

**Comment by hgupta9** [comment]
Can you try the latest version from nuget - https://www.nuget.org/packages/FluentFTP/17.5.4

**Comment by FloppyNotFound** [comment]
I can install it now, but it now throws an System.PlatformNotSupportedException:

"   at FluentFTP.FtpClient.AsyncConnect.BeginInvoke(AsyncCallback callback, Object object)\r\n   at FluentFTP.FtpClient.BeginConnect(AsyncCallback callback, Object state)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)\r\n   at FluentFTP.FtpClient.<ConnectAsync>d__151.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at FluentFTPTest.MainPage.<OnNavigatedTo>d__6.MoveNext()"

But as I can see, this issue is already known (#127).

**Comment by hgupta9** [comment]
I've removed the internal locking since it causes issues with async on .NET Std 1.4 / UWP.
Can you check and see if it works for your project?

https://www.nuget.org/packages/FluentFTP/

**Comment by hgupta9** [comment]
@CriticalCauchy Can you please try with the latest?

**Comment by lainx1** [comment]
Hello everyone, im using the latest version(17.5.6) but im getting  System.PlatformNotSupportedException.
im trying to do BeginConnect.cs from FluentExamples folder.

**Comment by CriticalCauchy** [comment]
Unfortunately, I haven't been able to get it up and running. (In my UWP app, I created a reference to a .NET Core library where I had added FluentFTP 17.5.6 via NuGet.)

> Could not load file or assembly 'FluentFTP, Version=17.5.6.0, Culture=neutral, PublicKeyToken=f4af092b1d8df44f' or one of its dependencies.

**Comment by taoyouh** [comment]
18.0.2 works with UWP on desktop, if you also install System.Console from NuGet.

**Comment by artiomchi** [comment]
System.Console is now a dependency of FluentFTP, so it should work with UWP without any caveats then :)

**Comment by robinrodricks** [comment]
Excellent!

**Comment by CriticalCauchy** [comment]
That's great! The newest version works in UWP apps (directly) and when referencing to a .NET standard library from the UWP app.
I can request file/directory listings but I encountered some trouble with the asynchronous file upload/download. 
`await client.UploadFile(@"C:\img.jpg", "/TEST/img_upload.jpg");
CS1061 C# 'bool' does not contain a definition for 'GetAwaiter' and no extension method 'GetAwaiter' accepting a first argument of type 'bool' could be found (are you missing a using directive or an assembly reference?)` 
Would it help if the conditional statements were #if NET45 || CORE || WINDOWS_UWP ?

**Comment by taoyouh** [comment]
@CriticalCauchy There should be a UploadFileAsync method to use.

**Comment by taoyouh** [comment]
@CriticalCauchy Sorry, there is an UploadAsync but no UploadFileAsync. There is an DownloadFileAsync

**Comment by taoyouh** [comment]
@CriticalCauchy PR #200 should provide an UploadFileAsync method

**Comment by robinrodricks** [comment]
@CriticalCauchy Can you try with the latest build? It includes a whole new backend for .net core/standard.

https://www.nuget.org/packages/FluentFTP/19.0.0

**Comment by CriticalCauchy** [comment]
Thank you for your great efforts, robinrodricks! Unfortunately, I haven't been able to upload or download yet. 

# UPLOAD
`await client.UploadAsync(bytearray, "/TEST/text.txt");`
```
using (Stream stream = await sampleFile.OpenStreamForReadAsync())
{
      await client.UploadAsync(stream, "/TEST/text.txt");
}
```

Console log: 
```
Response: 230-Login successful, your current directory is /
Command:  FEAT
Response: 211 End.
Response: 211-Extensions supported:
Response: EPRT
Response: IDLE
Response: MDTM
Response: SIZE
Response: MFMT
Response: REST STREAM
Response: MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
Response: MLSD
Response: AUTH TLS
Response: PBSZ
Response: PROT
Response: TVFS
Response: ESTA
Response: PASV
Response: EPSV
Response: SPSV
Response: ESTP
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Auto-detected UNIX listing parser

# UploadAsync("/TEST/text.txt", Overwrite, False)

# FileExistsAsync("/TEST/text.txt")
Command:  SIZE /TEST/text.txt
Response: 213 60

# DeleteFileAsync("/TEST/text.txt")
Command:  DELE /TEST/text.txt
Response: 250 Deleted /TEST/text.txt
Response: 250-175197 Kbytes used (16%) - authorized: 1048576 Kb

# OpenWriteAsync("/TEST/text.txt", Binary)
Command:  TYPE I
Response: 200 TYPE is now 8-bit binary

# GetFileSizeAsync("/TEST/text.txt")
Command:  TYPE I
Response: 200 TYPE is now 8-bit binary
Command:  SIZE /TEST/text.txt
Response: 550 Can't check for file existence
Command:  TYPE A
Response: 200 TYPE is now ASCII

# OpenPassiveDataStreamAsync(AutoPassive, "STOR /TEST/text.txt", 0)
Command:  EPSV
Response: 500 Unknown command

# OpenPassiveDataStreamAsync(PASV, "STOR /TEST/text.txt", 0)
Command:  PASV
Response: 227 Entering Passive Mode (144,76,167,70,133,70)
Status:   Connecting to 144.76.167.70:34118
Command:  STOR /TEST/text.txt
Response: 150 Accepted data connection
```

At this point the upload procedure runs into a hang-up. FileZilla shows a (temp.) file on the server (.pureftpd-upload.59ce2acd.15.3036.4b933b93). When I stop the debugging, this file is transformed into the complete text.txt that I wanted to upload.



# DOWNLOAD
`byte[] fileba = await client.DownloadAsync("/TEST/text.txt");`

Console log:
```
# DownloadAsync("/TEST/text.txt")

# GetFileSize("/TEST/text.txt")
Command:  TYPE I
Response: 200 TYPE is now 8-bit binary
Command:  SIZE /TEST/text.txt
Response: 213 60
Command:  TYPE A
Response: 200 TYPE is now ASCII

# OpenReadAsync("/TEST/text.txt", Binary, 0)
Command:  TYPE I
Response: 200 TYPE is now 8-bit binary

# GetFileSizeAsync("/TEST/text.txt")
Command:  TYPE I
Response: 200 TYPE is now 8-bit binary
Command:  SIZE /TEST/text.txt
Response: 213 60
Command:  TYPE A
Response: 200 TYPE is now ASCII

# OpenPassiveDataStreamAsync(AutoPassive, "RETR /TEST/text.txt", 0)
Command:  EPSV
Response: 500 Unknown command

# OpenPassiveDataStreamAsync(PASV, "RETR /TEST/text.txt", 0)
Command:  PASV
Response: 227 Entering Passive Mode (144,76,167,70,141,57)
Status:   Connecting to 144.76.167.70:36153
Command:  RETR /TEST/text.txt
Response: 150 Accepted data connection
Exception: "System.IO.IOException" in FluentFTP.dll
Exception: "System.IO.IOException" in FluentFTP.dll
Exception: "FluentFTP.FtpException" in FluentFTP.dll
Exception: "FluentFTP.FtpException" in System.Private.CoreLib.ni.dll
Exception: "FluentFTP.FtpException" in System.Private.CoreLib.ni.dll
Exception: "FluentFTP.FtpException" in System.Private.CoreLib.ni.dll
Exception: "System.AggregateException" in System.Private.CoreLib.ni.dll
An exception of type "System.AggregateException" occured in System.Private.CoreLib.ni.dll and wasn't handled.
One or more errors occurred.
```

System.AggregateException occured.
  HResult=0x80131500
  Message = One or more errors occurred. (Error while downloading the file from the server. See InnerException for more info.)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at FtpClient.Views.MainPage.FtpTest()

Inner exceptions:
FtpException: Error while downloading the file from the server. See InnerException for more info.
IOException: Unexpected EOF for remote file /TEST/text.txt [81/60 bytes read]

This is how I started the test methods:
```
private void FtpTest()
{
        var t = Task.Run(() =>
                    //FtpListItems()
                    //FtpUploadAsync()
                    FtpDownloadAsync());
        t.Wait();
}
```

**Comment by taoyouh** [comment]
The uploading problem may be due to the uploader didn't close the stream correctly. As far as I know, FTP needs to close the data connection to indicate that the file has ended. 
The uploading problem seems to be obvious. The file is only 60 bytes long, but the program tries to read until 81 bytes.
By the way, I think you shouldn't Task.Run like that. You can directly use FtpDownloadAsync().Wait() or just use the synchronous version.
I will try to test them some time. But would you please test if the synchronous version Download() and Upload() have same problem?

**Comment by artiomchi** [comment]
@CriticalCauchy Could you test the same upload/download code from a .NET Core console app (and possibly .NET framework console app as well), and confirm whether this issue is UWP specific, or .NET Core in general?

Also, at least looking at the download code, something strange with the FTP server - what server are you using? Could you attach the test.txt file you're trying to download below?

It reports that the test.txt file you're sending is 60 bytes, but manages to download 81 bytes, which is caught by the code added by @bgroenks96. If not for that, the downloaded file would have more data than reported by the server.

On that note, when you download the file using FileZilla, could you show us the FileZilla extended log, as well as the file size of the downloaded file?

**Comment by artiomchi** [comment]
@taoyouh We're not sure about the upload of the file. After all, when uploading the file, the file size is picked up from the file system, so the issue may be somewhere else?

In the download stream on the other hand, yeah, the file size inconsistency is strange.

I'm wondering what does that 60/81 byte file contain, and what IS the size of said file :D

**Comment by artiomchi** [comment]
Oh for the love of all that is Holy.

I downloaded the file from the server, and it's 60 bytes in size. Linux line endings (so 1 byte per line break). Switch that to Windows format (CRLF), and it's exactly 81 bytes in size.

So when you're uploading the file to the server, it's converting the line endings on the fly!

WOW!
This needs some thinking and testing, but at least we've got some progress.. And my face hurts from the facepalms.

**Comment by CriticalCauchy** [comment]
I feel so stupid now, haha. 
So I tested the download with this test server https://test.rebex.net/ and it works fine.
`byte[] filebytes = await client.DownloadAsync("/pub/example/ConsoleClient.png");`
But if I try to download the test image (http://ccauchy.bplaced.net/TEST/TestFile/img.jpg) it throws an exception:
```
# OpenPassiveDataStreamAsync(PASV, "RETR /TEST/img.jpg", 0)
Command:  PASV
Response: 227 Entering Passive Mode (144,76,167,70,191,224)
Status:   Connecting to 144.76.167.70:49120
Command:  RETR /TEST/img.jpg
Response: 150 77.1 kbytes to download
Response: 150-Accepted data connection
Error: "System.IO.IOException" in FluentFTP.dll
```
The Windows image size is 78.927 bytes, not 77.1 kbytes ...

Ok, I think I should create my own FTP server.

**Comment by robinrodricks** [comment]
Since the basic issue of the OP (use with UWP) is solved, I'm closing this and moving the chat to #230.
