### ISSUE TITLE
Add “stopPosition” in “Download” method

### ISSUE THREAD

**Issue by Kvas007** [robinrodricks/FluentFTP#690]
Hello, please add "stop position" or "bytes count to receive" in methods "Download" and "DownloadAsync".
This will be very useful for me and maybe for someone else.
Thanks

**Comment by robinrodricks** [comment]
Added to the [bucket list](https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans). We will pick this up as and when we have free time. Comment on this issue if you want us to prioritize it. Thanks!

**Comment by lukashev-di** [comment]
Hello! Can You prioritize this enchantment please?

**Comment by Dmitry0108** [comment]
This feature could be very helpfull for us.

**Comment by robinrodricks** [comment]
@lukashev-di its now `DownloadBytes`. You still need this?

**Comment by lukashev-di** [comment]
We have a task to download very large files. We need to do this in multiple threads, splitting one large file into several parts. I think the method "DownloadStream" more suitable for this. We can use it both with FileStream and MemoryStream

**Comment by robinrodricks** [comment]
We will look into it.

**Comment by MohammadBMelhem** [comment]
Any chance to have estimation on this?
Am building an internal framework and huge files upload and download in a chunks is very needed to be in the framework, having tight estimation to deliver, next week will start adding the ftp abstraction!!

**Comment by robinrodricks** [comment]
I'll give you a beta version by today night!

**Comment by FanDjango** [comment]
@robinrodricks You beat me to it. I saw it too late yesterday evening and you have 5.5 hours on me :-)

Anyway, will you just add an overload with a new parm? I am curious to see that when it is finished.

**Comment by robinrodricks** [comment]
@FanDjango yes just low hanging fruit :)

Yes just adding a param. I hope it works tho.

**Comment by robinrodricks** [comment]
@MohammadBMelhem can you try if this works?

[FluentFTP.46.0.0-BETA1.zip](https://github.com/robinrodricks/FluentFTP/files/10882074/FluentFTP.46.0.0-BETA1.zip)

#### 46.0.0
 - New: Add `stopPosition` parameter to `DownloadBytes` and `DowloadStream` to allow partial downloads

**Comment by MohammadBMelhem** [comment]
Thanks @robinrodricks  will check it,
Actually i need the partial for download and upload,
The only reason, to avoid load a huge files on the memory, i have to deal with hundreds of ftp paths with multiple ftp/sftp/as2 … in the same application concurrently, download and upload from/to these ftp, so its very important to use chunks always to avoid memory limitations and issues.

**Comment by robinrodricks** [comment]
Published as no response for some days.

If there are any issues, file a new ticket.

https://www.nuget.org/packages/FluentFTP/46.0.0

#### 46.0.0
 - New: Add `stopPosition` parameter to `DownloadBytes` and `DowloadStream` to allow partial downloads
