### ISSUE TITLE
Add FtpAuthenticationException to the AutoConnect function

### ISSUE THREAD

**Issue by jvdvld** [robinrodricks/FluentFTP#697]
FTP OS:General
FTP Server:General
Computer OS:General
FluentFTP Version:33.0.3

Issue: When trying to AutoConnect() with invalid credentials to a FTP server it takes a considerable amount of time and 130 retrying connects before retrieving a _null_ in the returned parameter FtpProfile. 

Technical: In FtpClient_AutoConnection.cs the AutoConnect() calls the AutoDetect() function which has a loop to try to connect with the dedicated server with all different enums from encoding, encryption, protocol and dataType. Within a try and catch the Connect() function in FtpClient_Connection.cs is called and if the connection raises an error or can't connect the next combination will be used except for a SocketException and TimeoutException which both will leave the loop.

Probable solution: Add an extra 'leave the loop' return in the catch of the AutoDetect() function in FtpClient_AutoConnection.cs handling the FtpAuthenticationException raised by the Connect()=>Authenticate() function because that part of code is aware of the authentication issue and thus the problem is not in the parameter settings.
Eg: 
around line 169 in FtpClient_AutoConnection.cs
if (ex is FtpAuthenticationException)
{
        Log that the credentials are a problem
	return results;
}

**Comment by robinrodricks** [comment]
This is a good idea. I'll work on it.

**Comment by robinrodricks** [comment]
Fixed. Does it work for you?

https://www.nuget.org/packages/FluentFTP/33.1.2

**Comment by jvdvld** [comment]
Thanks for this one..
