### ISSUE TITLE
FTPTrace.LogToFile no longer works

### ISSUE THREAD

**Issue by bryancass** [robinrodricks/FluentFTP#698]
FtpTrace.LogToFile - Set this to a file path to append all FTP communication to it. Default: false.

This no longer works as of v33.1.0.

I get build error "ftptrace does not contain a definition for logtofile".

It worked OK in v33.0.3.

**Comment by robinrodricks** [comment]
Which platform are you on? .net or .net core, which version?

**Comment by robinrodricks** [comment]
It never worked on .net core.

**Comment by robinrodricks** [comment]
Added to .net framework. Please verify.

https://www.nuget.org/packages/FluentFTP/33.1.3

**Comment by bryancass** [comment]
Sorry I didn't see your response until now.., I'm using .NET Core v5.0.4.
![Untitled](https://user-images.githubusercontent.com/57223041/112739016-8bbb8a00-8f3e-11eb-8461-a367ee8e11fd.png)

**Comment by robinrodricks** [comment]
So does the latest release work or not?

**Comment by bryancass** [comment]
OK, what you did worked - it compiles now.  

I thought I was using .NET Core??

**Comment by robinrodricks** [comment]
I suppose you were using. Net framework.
