### ISSUE TITLE
Remove FtpAuthenticationException in catch of the AutoConnect function

### ISSUE THREAD

**Issue by jvdvld** [robinrodricks/FluentFTP#700]
FTP OS:General
FTP Server:General
Computer OS:General
FluentFTP Version:33.1.3

Issue: Fix #697 prevents the AutoConnect() function to loop further with other settings. While at first it was a good idea to catch the FtpAuthenticationException in case of invalid credentials causing unnecessary loops, other settings like connection-drops due to TLS or EncryptionMode are raising a FtpAuthenticationException  as well. Since the FtpAuthenticationException is catched there is no try for the next tls or encryptionmode enum with a possible good combination.
One solution to prevent a long loop with invalid credentials could be some sort of distinguish between the reply in the Authenticate() function in FtpClient_Connection.cs for 4xx codes and 5xx codes but I'm not sure about this.

**Comment by robinrodricks** [comment]
Please see what response the server sends if the auth is wrong. I don't have time currently to test this, but I would like to check if its an auth failure and hard abort.

**Comment by jvdvld** [comment]
FtpReply in case of invalid user or pass line 809 in FtpClient_Connection.cs

Invalid user/pw IIS
Code	"530"	string
ErrorMessage	"User cannot log in.; Win32 error:   The user name or password is incorrect.; Error details: An error occurred during the authentication process.; End"	string
InfoMessages	"530-User cannot log in.\n Win32 error:   The user name or password is incorrect. \n Error details: An error occurred during the authentication process."	string
Message	"End"	string
Success	false	bool
Type	PermanentNegativeCompletion	FluentFTP.FtpResponseType

Invalid user/pw Pure-FTPd
Code	"530"	string
ErrorMessage	"Login authentication failed"	string
InfoMessages	null	string
Message	"Login authentication failed"	string
Success	false	bool
Type	PermanentNegativeCompletion	FluentFTP.FtpResponseType

Invalid user/pw ProFTPD
Code	"530"	string
ErrorMessage	"Login incorrect."	string
InfoMessages	null	string
Message	"Login incorrect."	string
Success	false	bool
Type	PermanentNegativeCompletion	FluentFTP.FtpResponseType

**Comment by robinrodricks** [comment]
This is great! Thank you!

**Comment by robinrodricks** [comment]
Please check:

https://www.nuget.org/packages/FluentFTP/33.1.4

**Comment by jvdvld** [comment]
Fix does work.. Accepted :-)
