### ISSUE TITLE
Capabilities are read before assumed

### ISSUE THREAD

**Issue by jnyrup** [robinrodricks/FluentFTP#702]
**FTP OS:** Unix / Windows / Embedded

**FTP Server:** Pure-FTPd / DrFTPD / Vsftpd / ProFTPD / Vax / VMS / OpenVMS / Tandem / HP NonStop Guardian / IBM OS400 / AS400 / Windows CE

**Computer OS:** ?

**FluentFTP Version: 33.1.3

If the following lines are not executed or fails to fetch and assign capabilities
https://github.com/robinrodricks/FluentFTP/blob/0477d44c4d177052c76da9171beb805346a05143/FluentFTP/Client/FtpClient_Connection.cs#L589-L597

`HasFeature` will throw `FtpException("Please call Connect() before trying to use any other methods/properties!")`.
https://github.com/robinrodricks/FluentFTP/blob/0477d44c4d177052c76da9171beb805346a05143/FluentFTP/Client/FtpClient_Connection.cs#L600-L602

**Logs :**

```
FluentFTP.FtpException: Please call Connect() before trying to use any other methods/properties!
   at List<FtpCapability> FluentFTP.FtpClient.get_Capabilities()
   at async Task FluentFTP.FtpClient.ConnectAsync(CancellationToken token)
```

**Comment by robinrodricks** [comment]
What is the full code you are using to connect?

**Comment by robinrodricks** [comment]
Good one. Does this work?

[FluentFTP.33.1.5.zip](https://github.com/robinrodricks/FluentFTP/files/6269478/FluentFTP.33.1.5.zip)

**Comment by jnyrup** [comment]
I have only ever seen this exception once in our logs, so it will be a difficult for me to verify that the 33.1.5 dll improves the situation.
If I can see the changes, I'll be happy to give it a look.

Being an open source maintainer myself I can recommend that you create a public branch or PR with the changes.
That way more people can help scrutinizing the code.

**Comment by robinrodricks** [comment]
Pushed to nuget.

**Comment by jnyrup** [comment]
Thanks!
I'll try it out soon.
The fix seems reasonable as the FTP I'm connecting to is highly unstable and shows quite some connection issues.
