### ISSUE TITLE
Consider including Code in FtpReply Message

### ISSUE THREAD

**Issue by jnyrup** [robinrodricks/FluentFTP#704]
**FluentFTP Version:** 33.1.3

I hit a case in our logs yesterday where it seems the information included in the `FtpCommandException` could be improved.
From how I read the code, it indicates to me that the the `FtpReply` was unsuccessful, but `InfoMessages` was insufficient to generate a non-empty `ErrorMessage`. 
In that case you could consider a fallback where the `Code` property is included in the `ErrorMessage`.
I don't know enough about the correlation between `InfoMessages` and `Code` to tell if it would be duplicate information, if `Code` was always included in the `ErrorMessage`.

**Logs :**

```
FluentFTP.FtpCommandException
   at async Task FluentFTP.FtpClient.SetDataTypeNoLockAsync(FtpDataType type, CancellationToken token)
   at async Task<List<string>> FluentFTP.FtpClient.GetListingInternalAsync(string listcmd, FtpListOption options, bool retry, CancellationToken token)
   at async Task<FtpListItem[]> FluentFTP.FtpClient.GetListingAsync(string path, FtpListOption options, CancellationToken token)
```

**Comment by FanDjango** [comment]
You are saying there (probably) was a 5xx/4xx or so, but no error messages, although there might have been info messages?

**Comment by jnyrup** [comment]
This partly a question, partly a suggestion.
The case was I had an exception with no information about what was wrong, except that I can deduce that it was _some_ 4xx/5xx.
It would have been useful to have the _exact_ completion code as part of the exception message if it was available.

So I suggest we include `FtpCommandException.CompletionCode` in the exception message.

See e.g. how [here](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/ArgumentException.cs,77) how `_paramName` is included in the thrown exception message.

**Comment by FanDjango** [comment]
```
public override string [Message](https://source.dot.net/System.Private.CoreLib/R/71cfcd61786aa2d8.html)
        {
            get
            {
                [SetMessageField](https://source.dot.net/System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/ArgumentException.cs.html#88bcc0b08f1c28b8)();
 
                [string](https://source.dot.net/System.Private.CoreLib/P/8281103e6f23cb5c.html#8281103e6f23cb5c) s = [base](https://source.dot.net/System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/SystemException.cs.html#719a133d5efc4786).[Message](https://source.dot.net/System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Exception.cs.html#5fba0e16215b42a3);
                if (![string](https://source.dot.net/System.Private.CoreLib/P/8281103e6f23cb5c.html#8281103e6f23cb5c).[IsNullOrEmpty](https://source.dot.net/System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/String.cs.html#23a8597f842071f4)([_paramName](https://source.dot.net/System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/ArgumentException.cs.html#ec99d164d653f993)))
                {
                    s += " " + [SR](https://source.dot.net/System.Private.CoreLib/P/b31ecb5e5b3556b0.html#b31ecb5e5b3556b0).[Format](https://source.dot.net/System.Private.CoreLib/src/libraries/Common/src/System/SR.cs.html#d37ecbff1254374f)([SR](https://source.dot.net/System.Private.CoreLib/P/b31ecb5e5b3556b0.html#b31ecb5e5b3556b0).[Arg_ParamName_Name](https://source.dot.net/System.Private.CoreLib/artifacts/obj/coreclr/System.Private.CoreLib/x64/Debug/System.SR.cs.html#da90751cfff81538), [_paramName](https://source.dot.net/System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/ArgumentException.cs.html#ec99d164d653f993));
                }
 
                return s;
            }
        }
```
I grok it, thx. Only problem is, I suppose I must mock such a thing happening in order to test it. I **do** myself remember having seen an instance of this happening when coding my little application, in the beginning, when things were flaky, but for the life of my I cannot remember the circumstances and the command that provoked it.

**Comment by FanDjango** [comment]
> See e.g. how [here](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/ArgumentException.cs,77) how _paramName is included in the thrown exception message.

Cannot do it that way. `_message` is not accessible at this level.

But would not this here be a real nice quicky:
```
		public FtpCommandException(string code, string message)
			: base(code + " " + message) {
			CompletionCode = code;
		}
```

**Comment by jnyrup** [comment]
It can be done by adding this to `FtpCommandException`
```cs
public override string Message => $"Command threw {CompletionCode} with message: {base.Message}";
```

```cs
[Fact]
public void FtpCommandException_includes_CompletionCode_in_message() {

	Action act = () => throw new FtpCommandException("501", "MyErrorMessage");

	var exception = Assert.Throws<FtpCommandException>(act);
	Assert.Contains("501", exception.ToString());
	Assert.Contains("MyErrorMessage", exception.ToString());
}
```

**Comment by FanDjango** [comment]
I didn't know that you can do that with a property. I mean I forgot you can initialize a property that only has a getter. This should be your PR.

Suggestion:
`$"Code: {CompletionCode} Message: {base.Message}"`

**Comment by FanDjango** [comment]
I have experimented now with something on the follwing lines, making it conditional:
```
		/// <summary>
		/// Gets the message string associated with the response
		/// </summary>
		public string Mesg {
			get => _mesg;
			private set {
				if (value.IsBlank()) {
					_mesg = CompletionCode;
				}
				else {
					_mesg = value;
				}
			} 
		}
```
```
public override string Message => $"{Mesg}";
```
but I believe your approach is better: A constant format that stays the same.
