### ISSUE TITLE
Missing null checks of CompletionCode?

### ISSUE THREAD

**Issue by jnyrup** [robinrodricks/FluentFTP#705]
**FluentFTP Version:** master

Looking at the source code it seems that `CompletionCode` is everywhere but two places null checked.
I couldn't immediately see a reason why they _couldn't_ be null, so I wanted to double check with you.
If they cannot be null, it could be nice with a comment stating the reason for that.

https://github.com/robinrodricks/FluentFTP/blob/1583fe6d1992ca99a30687643f8991302b639d45/FluentFTP/Client/FtpClient_Listing.cs#L1277-L1282

https://github.com/robinrodricks/FluentFTP/blob/1583fe6d1992ca99a30687643f8991302b639d45/FluentFTP/Client/FtpClient_Listing.cs#L1376-L1381

**Comment by robinrodricks** [comment]
I haven't memorized all the places that create FtpCommandException or whatever type has CompletionCode.

If you could check it, it would be great, or I'll do it later and get back to you.

**Comment by jnyrup** [comment]
`CompletionCode` is a property on `FtpCommandException`.
`CompletionCode` is everywhere is the source constructed from `FtpReply.Code`.
`FtpReply.Code` is null checked 10 places in the source.

Looking at the source here a case that _might_ produce a `FtpReply` with `Code == null`.
```
FtpClient.Authenticate
  Execute
    GetReply
      DecodeStringToReply <-- this might not be called if m_stream.ReadLine returns snull
        reply.Code = m.Groups["code"].Value <-- this is not called if m.Success is false

  throw new FtpAuthenticationException(reply); <-- constructs an FtpCommandException with a null CompletionCode
```

You could search for the pattern `Code[\[\.]` and check if `FtpReply.Code` or `FtpCommandException.CompletionCode` have necessary null checks.

**Comment by robinrodricks** [comment]
Done. Added null checks to the 2 locations they were missing.

**Comment by robinrodricks** [comment]
Published.

https://www.nuget.org/packages/FluentFTP/34.0.2
