### ISSUE TITLE
LastReply is not set when using async methods

### ISSUE THREAD

**Issue by udda** [robinrodricks/FluentFTP#707]
**FTP OS:** Any

**FTP Server:** Any

**Computer OS:** Windows 10

**FluentFTP Version:** 33.1.5

Hello, I noticed that when using `FtpClient.UploadAsync`, LastReply property is always null.
When using `FtpClient.Upload`, the property is correctly set.

Looking at the source, seems that the following line, found in GetReply, is missing in GetReplyAsync:

```
LastReply = reply;
```

**Comment by robinrodricks** [comment]
Good find!

**Comment by robinrodricks** [comment]
Done. Please check.

https://www.nuget.org/packages/FluentFTP/33.1.7
