### ISSUE TITLE
'Safe Handle has been closed' if trying to connect

### ISSUE THREAD

**Issue by Mad-Max-27** [robinrodricks/FluentFTP#708]
**FTP OS:** Fritz!Box 7490; Fritz!OS 7.21

**Computer OS:** Windows 8.1; Visual Studio 16.9.3; .NET5.0 

**FluentFTP Version:** 33.1.5

I use the following code (part of a static class) for the connection with my FTP-server (FritzBox 7490)
 
           public static bool Connect()                                                           
           {                                                                      
                FTPConnection.Host = FTPZugang.Server;                      
                FTPConnection.Port = FTPZugang.Port;

                FTPConnection.Credentials.UserName = FTPZugang.Konto;
                FTPConnection.Credentials.Password = FTPZugang.Passwort;

                FTPConnection.EncryptionMode = FtpEncryptionMode.Explicit;
                FTPConnection.SslProtocols = System.Security.Authentication.SslProtocols.Tls12;
                FTPConnection.ValidateCertificate += new FtpSslValidation(delegate (FtpClient c, FtpSslValidationEventArgs f)
                {
                    if (f.Certificate.GetRawCertDataString() == FTPZugang.Zertifikat)              
                    {
                        f.Accept = true;
                    }
                    else                                                                          
                    {
                        MessageBox.Show("Error", "Fehler", MessageBoxButtons.OK, MessageBoxIcon.Error);

                         f.Accept = false;
                    }  
                });

                try
                {
                    FTPConnection.Connect();                               
                    FTPConnection.RecursiveList = false;                   

                    return true;
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                    
                     ...
                    
Until FluentFTP v33.0.3 this works without problems (with NETFramework 4.8 and NET5.0). But with v33.1.0 or v33.1.5 it is not possible to establish a connection. The command FTPConnection.Connect() leads to the exception "Safe handle has been closed. Object name: 'SafeHandle'." Does anybody have an idea what causes this problem with the current version of FluentFTP? Many thanks in advance!               

**Logs :**

# Connect()
Status:   Connecting to ***:18187
Response: 220 FRITZ!Box7490 FTP server ready.
Command:  AUTH TLS
Response: 234 Authentication method accepted
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 1s.  Total Seconds: 1,1625102.
Command:  USER ***
Command:  QUIT
Warning:  FtpClient.Disconnect(): Exception caught and discarded while closing control connection: System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
   at FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpSocketStream.ReadLine(Encoding encoding)
   at FluentFTP.FtpClient.GetReply()
   at FluentFTP.FtpClient.Execute(String command)
   at FluentFTP.FtpClient.Disconnect()
Status:   Disposing FtpSocketStream...

**Comment by ajardin44** [comment]
I have the same problem. With older version (before 33.1) on .NET 5, or with 33.1.5 and .Net 3.1, that's work, but in 33.1.5 and NET 5, I have this error 'Safe Handle has been closed' on almost all commands.
I can connect on my FTP with ConnectAsync (not Connect)
Example : 
```C#
using (var ftp = new FluentFTP.FtpClient(FTP_HOST, FTP_PORT, FTP_USER, FTP_PWD))
{
	ftp.ValidateAnyCertificate = true;
	ftp.EncryptionMode = FluentFTP.FtpEncryptionMode.Explicit;
	ftp.SslProtocols = System.Security.Authentication.SslProtocols.Tls;
	ftp.DataConnectionType = FluentFTP.FtpDataConnectionType.AutoPassive;
	ftp.DataConnectionEncryption = true;
	ftp.Encoding = Encoding.UTF8;
	await ftp.ConnectAsync(token);
}
```
But after I have this error with DownloadFileAsync, GetListingAsync, SetWorkingDirectoryAsync, ...
Only UploadFileAsync work for me.

Example of error on GetListingAsync
```text
OpenPassiveDataStreamAsync(AutoPassive,  "LIST /XXX/XXX", 0)
Command:  EPSV
Response: 229 Entering extended passive mode (|||16383|)
Status:   Connecting to XXX.XXX.XXX.XXX:16383
Command:  LIST /XXX/XXX
Response: 150 File Status OK.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0,0081091.
+---------------------------------------+
Listing:  -rw-------   1  freebox  freebox 45371172 Apr 12 17:30 Fichier1.zip
Listing:  drwxr-xr-x  11  freebox  freebox     4096 Apr 09 16:36 ..
Listing:  -rw-------   1  freebox  freebox  2272715 Apr 12 18:13 Fichier2.zip
Listing:  -rw-------   1  freebox  freebox   916150 Apr 10 08:59 Fichier3.zip
Listing:  -rw-------   1  freebox  freebox 44891089 Apr 09 17:14 Fichier4.zip
-----------------------------------------
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Status:   Disposing FtpSocketStream...

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Warning:  FtpClient.Disconnect(): Exception caught and discarded while closing control connection: System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at FluentFTP.FtpSocketStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpSocketStream.ReadLine(Encoding encoding)
   at FluentFTP.FtpClient.GetReply()
   at FluentFTP.FtpClient.Execute(String command)
   at FluentFTP.FtpClient.Disconnect()
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
```

It's the same error of above

**Comment by ajardin44** [comment]
Error is in FtpStreamSocket.cs at line 473
Change
```C#
#if CORE
   return BaseStream.Read(buffer, offset, count);
#else
```
To
```C#
#if CORE ||NET5_0
   return BaseStream.Read(buffer, offset, count);
#else
```
and all works !

**Comment by robinrodricks** [comment]
Thanks @ajardin44 that helped. I'm now using all .net core functionality in .net 5 builds. Please check if it works:

[FluentFTP.33.1.6.zip](https://github.com/robinrodricks/FluentFTP/files/6302891/FluentFTP.33.1.6.zip)

**Comment by ajardin44** [comment]
@robinrodricks I tested net5 and netstandard2.1 version and it's works :)

**Comment by robinrodricks** [comment]
Great, I'll release to nuget!

**Comment by robinrodricks** [comment]
https://www.nuget.org/packages/FluentFTP/33.1.6

**Comment by Mad-Max-27** [comment]
Many thanks for the quick support! A first test with v33.1.6 during lunch break worked without any problems ... ;-)
