### ISSUE TITLE
FtpTrace.LogToConsole allways on

### ISSUE THREAD

**Issue by karlo1** [robinrodricks/FluentFTP#709]
**FTP OS:**  Windows

**FTP Server:** All

**Computer OS:** Win10

**FluentFTP Version:** 33.1.6

FluentFTP.FtpTrace.LogToConsole = False     'geht leider nicht
FluentFTP.FtpTrace.LogFunctions = False     'geht ? Auch nicht

The Log to console (Debug.Write)  is allways on.....

**Comment by robinrodricks** [comment]
I'll check it out..

**Comment by robinrodricks** [comment]
I cannot find a bug 

See https://github.com/robinrodricks/FluentFTP/blob/01131bbd99a3c4dbb0f4dbf0281c4784c9eb3406/FluentFTP/Helpers/FtpTrace.cs#L186
