### ISSUE TITLE
OpenAppend - You cannot modify the position of a FtpDataStream.

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#711]
Same problem with FileZilla. FluentFTP version 33.1.6. 

I'm taking my code from this example
`                using (Stream ostream = conn.OpenAppend("/full/or/relative/path/to/file")) {
                    try {
                        ostream.Position = ostream.Length;
                        var sr = new StreamWriter(ostream);
                        sr.WriteLine(...);
                    }
                    finally {
                        ostream.Close();
                    }
                }`
 given here https://github.com/robinrodricks/FluentFTP/issues/52

System.InvalidOperationException
  HResult=0x80131509
  Message=You cannot modify the position of a FtpDataStream. This property is updated as data is read or written to the stream.
  Source=FluentFTP
  StackTrace:
   at FluentFTP.FtpDataStream.set_Position(Int64 value)
   at VWUK.Utils.FtpService.FtpService.AppendMode(FtpClient ftp, String path, String data) in

_Originally posted by @hrafnkel in https://github.com/robinrodricks/FluentFTP/issues/283#issuecomment-823149168_

**Comment by robinrodricks** [comment]
Please use the new append API - `UploadFile(.... FtpExists.Append)` - if it does not work, tell me and I'll document it better

**Comment by hrafnkel** [comment]
I have tried UploadFile with Append. Creation works fine, but it does not append to a pre-existing file.

`        private FtpStatus AppendMode(FtpClient ftp, string path, string data)
        {
            ftp.UploadDataType = FtpDataType.ASCII;

            // make a local temp file
            string fileName = "tempFile";
            File.AppendAllText(fileName, data);
            
            // upload file
            FtpStatus status = ftp.UploadFile(fileName,path,FtpRemoteExists.Append, false);

            // delete temp file
            File.Delete(fileName);

            return status;
        }`

**Comment by hrafnkel** [comment]
Additional. The debug log

`
Fred: Debug: >         Connect()
Fred: Information: Status:   Connecting to fd1a:d1b0:320a:7777::a02:15f:21
Fred: Debug: Response: 220-FileZilla Server 0.9.60 beta
Response: 220-written by Tim Kosse (tim.kosse@filezilla-project.org)
Fred: Information: Response: 220 Please visit https://filezilla-project.org/
Fred: Information: Status:   Detected FTP server: FileZilla
Fred: Information: Command:  AUTH TLS
Fred: Information: Response: 234 Using authentication type TLS
Fred: Information: Status:   FTPS Authentication Successful
Fred: Debug: Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1159128.
Fred: Information: Command:  USER sabalmsftp
Fred: Information: Response: 331 Password required for sabalmsftp
Fred: Information: Command:  PASS ***
Fred: Information: Response: 230 Logged on
Fred: Information: Command:  PBSZ 0
Fred: Information: Response: 200 PBSZ=0
Fred: Information: Command:  PROT P
Fred: Information: Response: 200 Protection level set to P
Fred: Information: Command:  FEAT
Fred: Debug: Response: 211-Features:
Response: MDTM
Response: REST STREAM
Response: SIZE
Response: MLST type*;size*;modify*;
Response: MLSD
Response: AUTH SSL
Response: AUTH TLS
Response: PROT
Response: PBSZ
Response: UTF8
Response: CLNT
Response: MFMT
Response: EPSV
Response: EPRT
Fred: Information: Response: 211 End
Fred: Information: Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Fred: Information: Command:  OPTS UTF8 ON
Fred: Information: Response: 202 UTF8 mode is always enabled. No need to send this command.
Fred: Information: Command:  SYST
Fred: Information: Response: 215 UNIX emulated by FileZilla
Fred: Debug: >         GetFileSize("/FTPTestHarness.csv")
Fred: Information: Command:  SIZE /FTPTestHarness.csv
Fred: Information: Response: 213 366
Fred: Debug: >         FileExists("/FTPTestHarness.csv")
Fred: Information: Command:  SIZE /FTPTestHarness.csv
Fred: Information: Response: 213 366
Fred: Information: Creating new file
Fred: Debug: >         UploadFile("tempFile", "/FTPTestHarness.csv", Append, False, None)
Fred: Debug: >         FileExists("/FTPTestHarness.csv")
Fred: Information: Command:  SIZE /FTPTestHarness.csv
Fred: Information: Response: 213 366
Fred: Debug: >         GetFileSize("/FTPTestHarness.csv")
Fred: Information: Command:  SIZE /FTPTestHarness.csv
Fred: Information: Response: 213 366
Fred: Debug: >         OpenAppend("/FTPTestHarness.csv", ASCII)
Fred: Information: Command:  TYPE A
Fred: Information: Response: 200 Type set to A
Fred: Debug: >         OpenPassiveDataStream(EPSV, "APPE /FTPTestHarness.csv", 0)
Fred: Information: Command:  EPSV
Fred: Information: Response: 229 Entering Extended Passive Mode (|||65261|)
Fred: Information: Status:   Connecting to fd1a:d1b0:320a:7777::a02:15f:65261
Fred: Information: Command:  APPE /FTPTestHarness.csv
Fred: Information: Response: 150 Opening data channel for file upload to server of "/FTPTestHarness.csv", restarting at offset 366
Fred: Information: Status:   FTPS Authentication Successful
Fred: Debug: Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.071649.
Fred: Debug: Status:   Disposing FtpSocketStream...
Fred: Information: Response: 226 Successfully transferred "/FTPTestHarness.csv"
`

**Comment by aaa930811** [comment]
I'm having the same problem

**Comment by nkev** [comment]
I'm having the same problem too.

**Comment by FanDjango** [comment]
I think everone has seen this by now - it will be mentioned in the FAQ section at some point in time,
