### ISSUE TITLE
PASV DownloadFile Issues on Specific port 5060

### ISSUE THREAD

**Issue by Waz-Cpt** [robinrodricks/FluentFTP#712]
**FTP OS:** Unix

**FTP Server:** X2 WS_FTP Server 8.5.0(24135676)

**Computer OS:** Windows 10 Pro x64 build 19042.928 version 20H2

**FluentFTP Version:** 33.1.6

On some networks with Firewalls the port 5060 is restricted for certain use, when FluentFTP downloads files it uses rolling ports for each file. If you downloading a large number of files the download fails whenever it cycles back to port 5060. Typically Port 5060 is an unencrypted port used for SIP protocols. How does one stop FluentFTP from using this port.

**Logs :**

```
# Connect()
Status:   Connecting to **.***.**.***:990
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 1s.  Total Seconds: 1.2751648.
Response: 220 ftps.*******.com X2 WS_FTP Server 8.5.0(24135676)
Command:  USER ****
Response: 331 Enter password
Command:  PASS ***
Response: 230-User logged in
Response: Welcome to UL SFTP
Response: 230 User logged in
Command:  PBSZ 0
Response: 200 PBSZ=0
Command:  PROT P
Response: 200 PRIVATE data channel protection level set
Command:  FEAT
Response: 211-Extensions supported
Response: SIZE
Response: XMD5
Response: XSHA1
Response: XSHA256
Response: XSHA512
Response: XQUOTA
Response: LANG EN, ES, FR, GE
Response: MDTM
Response: MLST size*;type*;perm*;create*;modify*;
Response: REST STREAM
Response: TVFS
Response: UTF8
Response: AUTH SSL;TLS-P;
Response: PBSZ
Response: PROT C;P;
Response: 211 end
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 200 Command OPTS succeed
Command:  SYST
Response: 215 UNIX

# SetWorkingDirectory("/Interfaces/Prod/ProductExport/ExportFiles/")
Command:  CWD /Interfaces/Prod/ProductExport/ExportFiles
Response: 250 Command CWD succeed

# GetListing(null, Auto)

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/Interfaces/Prod/ProductExport/ExportFiles" is current directory
Command:  TYPE I
Response: 200 Transfer mode set to BINARY

# OpenPassiveDataStream(AutoPassive, "MLSD /Interfaces/Prod/ProductExport/ExportFiles", 0)
Command:  EPSV
Response: 500 Unknown command EPSV

# OpenPassiveDataStream(PASV, "MLSD /Interfaces/Prod/ProductExport/ExportFiles", 0)
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,23,90).
Status:   Connecting to ##.###.##.###:5978
Command:  MLSD /Interfaces/Prod/ProductExport/ExportFiles
Response: 150 Transferring directory
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.6692282.
+---------------------------------------+
Listing:  size=0;type=cdir;create=20200310020904;modify=20210421142445; .
Listing:  size=0;type=pdir;create=20151225104640;modify=20201109094306; ..

Downloading file: I_ATTRIBUTES_L310.1025_EGHS_AR_01112021072521.xlsx to folder: C:\*****2PDF\GHS EXCEL FILES\L310.1025\

# DownloadFile("C:\*****2PDF\GHS EXCEL FILES\L310.1025\L310.1025_EGHS_AR_01112021072521.xlsx", "I_ATTRIBUTES_L310.1025_EGHS_AR_01112021072521.xlsx", Overwrite, None)

# OpenRead("I_ATTRIBUTES_L310.1025_EGHS_AR_01112021072521.xlsx", Binary, 0)

# OpenPassiveDataStream(AutoPassive, "RETR I_ATTRIBUTES_L310.1025_EGHS_AR_01112021072521.xlsx", 0)
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,196).
Status:   Connecting to ##.###.##.###:5060
Command:  RETR I_ATTRIBUTES_L310.1025_EGHS_AR_01112021072521.xlsx
Response: 150 Downloading in BINARY file I_ATTRIBUTES_L310.1025_EGHS_AR_01112021072521.xlsx (2539)
The thread 0x8a0 has exited with code 0 (0x0).
Status:   IOException for file C:\*****2PDF\GHS EXCEL FILES\L310.1025\L310.1025_EGHS_AR_01112021072521.xlsx : Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Status:   Failed to download file.
Downloading file: I_ATTRIBUTES_L310.1025_EGHS_BE_01112021072521.xlsx to folder: C:\*****2PDF\GHS EXCEL FILES\L310.1025\

# DownloadFile("C:\*****2PDF\GHS EXCEL FILES\L310.1025\L310.1025_EGHS_BE_01112021072521.xlsx", "I_ATTRIBUTES_L310.1025_EGHS_BE_01112021072521.xlsx", Overwrite, None)

# OpenRead("I_ATTRIBUTES_L310.1025_EGHS_BE_01112021072521.xlsx", Binary, 0)
Status:   Testing connectivity using Socket.Poll()...

# OpenPassiveDataStream(AutoPassive, "RETR I_ATTRIBUTES_L310.1025_EGHS_BE_01112021072521.xlsx", 0)
Command:  PASV
Response: 503 Command PASV not accepted during Transferring
Exception thrown: 'FluentFTP.FtpException' in FluentFTP.dll
An exception of type 'FluentFTP.FtpException' occurred in FluentFTP.dll but was not handled in user code
Error while downloading the file from the server. See InnerException for more info.

'WERCStoPDF.exe' (CLR v4.0.30319: WERCStoPDF.exe): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.Desktop.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

```

**Comment by Waz-Cpt** [comment]
Is there any possible work around that I may be able to do in the mean time?

**Comment by robinrodricks** [comment]
I checked the code in detail, the FTP server specifies the port to be used for Passive/EPSV connections. `Response: 227 Entering Passive Mode (66,193,82,252,19,196).` contains the port number which translates into port `5060`. Maybe you can setup your FTP server to prevent it from using the ports you don't want to use. Well I'll try to make a change that will simply keep cycling ports, no idea how it may affect the server but I'll try.

**Comment by Waz-Cpt** [comment]
Hello Robin,

I do not have access the the settings of the FTP server. But if the issue
is the server then I will speak to the guys that maintain the server.

Perhaps there is a simple way to get your code to skip and retry on the
next port if it attempts to download on port 5060.

Thank you so much for the response.

Regards

Warwick

**Comment by robinrodricks** [comment]
Try this.

[FluentFTP.33.2.0.zip](https://github.com/robinrodricks/FluentFTP/files/6398645/FluentFTP.33.2.0.zip)

2 new properties - PassivePorts and PassiveMaxAttempts. Set PassivePorts  to a list of the whitelisted (allowed) ports. And then call Connect.

**Comment by Waz-Cpt** [comment]
Hello Robin,

I will try it now.

Regards

Warwick

**Comment by Waz-Cpt** [comment]
Hello Robin,

# Connect()
Status:   Connecting to 66.193.82.252:990
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.5043138.
Response: 220 ftps.thewercs.com X2 WS_FTP Server 8.5.0(88966137)
Status:   Detected FTP server: WSFTPServer
Command:  USER nutec
Response: 331 Enter password
Command:  PASS ***
Response: 230-User logged in
Response: Welcome to UL SFTP
Response: 230 User logged in
Command:  PBSZ 0
Response: 200 PBSZ=0
Command:  PROT P
Response: 200 PRIVATE data channel protection level set
Command:  FEAT
Response: 211-Extensions supported
Response: SIZE
Response: XMD5
Response: XSHA1
Response: XSHA256
Response: XSHA512
Response: XQUOTA
Response: LANG EN, ES, FR, GE
Response: MDTM
Response: MLST size*;type*;perm*;create*;modify*;
Response: REST STREAM
Response: TVFS
Response: UTF8
Response: AUTH SSL;TLS-P;
Response: PBSZ
Response: PROT C;P;
Response: 211 end
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 200 Command OPTS succeed
Command:  SYST
Response: 215 UNIX

# SetWorkingDirectory("/Interfaces/Prod/ProductExport/ExportFiles/")
Command:  CWD /Interfaces/Prod/ProductExport/ExportFiles
Response: 250 Command CWD succeed

# GetListing(null, Auto)

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/Interfaces/Prod/ProductExport/ExportFiles" is current directory
Command:  TYPE I
Response: 200 Transfer mode set to BINARY

# OpenPassiveDataStream(AutoPassive, "MLSD /Interfaces/Prod/ProductExport/ExportFiles", 0)
Command:  EPSV
Response: 500 Unknown command EPSV

# OpenPassiveDataStream(PASV, "MLSD /Interfaces/Prod/ProductExport/ExportFiles", 0)
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,189).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,191).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,192).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,193).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,194).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,195).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,197).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,198).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,199).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,200).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,201).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,202).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,203).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,204).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,205).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,206).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,207).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,208).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,209).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,210).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,211).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,212).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,213).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,214).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,215).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,216).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,217).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,218).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,219).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,220).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,221).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,222).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,223).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,224).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,225).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,226).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,227).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,228).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,229).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,230).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,231).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,232).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,233).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,234).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,235).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,236).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,237).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,238).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,239).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,240).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,241).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,242).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,243).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,244).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,245).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,246).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,247).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,248).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,249).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,250).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,251).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,252).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,253).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,254).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,19,255).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,0).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,1).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,2).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,3).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,4).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,5).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,6).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,7).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,8).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,9).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,10).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,11).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,12).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,13).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,14).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,15).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,16).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,17).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,18).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,19).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,20).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,21).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,22).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,23).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,24).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,25).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,26).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,27).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,28).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,29).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,30).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,31).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,32).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,33).
Command:  PASV
Response: 227 Entering Passive Mode (66,193,82,252,20,34).
Exception thrown: 'FluentFTP.FtpException' in FluentFTP.dll
An exception of type 'FluentFTP.FtpException' occurred in FluentFTP.dll but was not handled in user code
Could not find a suitable port for PASV/EPSV Data Connection after trying 100 times.

'WERCStoPDF.exe' (CLR v4.0.30319: WERCStoPDF.exe): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.Desktop.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[588] WERCStoPDF.exe' has exited with code -1 (0xffffffff).

tried to add the following to my code:
ftpClient.PassivePorts = new int[] { 5500, 5501, 5502, 5503, 5504, 5505, 5506};

**Comment by robinrodricks** [comment]
I'm sorry this was clearly the wrong design. Try this.

[FluentFTP.33.2.0.zip](https://github.com/robinrodricks/FluentFTP/files/6399176/FluentFTP.33.2.0.zip)

Set `PassiveBlockedPorts` only to the ports you DON'T want.

**Comment by Waz-Cpt** [comment]
Hello Robin,

This works like a treat.

I need to try find a way to download successfully in parallel as it does take a long time to download over a 1000 files.

regards

Warwick

**Comment by robinrodricks** [comment]
Published.

https://www.nuget.org/packages/FluentFTP/33.2.0

**Comment by Waz-Cpt** [comment]
thank you.
Warwick Davison

+27 83 326 0774
Sent Via Gmail
