### ISSUE TITLE
Missing capability to bind to a specific local interface

### ISSUE THREAD

**Issue by daviddenis-stx** [robinrodricks/FluentFTP#713]
Hello,

It's more a RFE than an issue.

The idea would be to be able to use one of the many local public IP addresses one can have (say bare metal server with several publicly routable IP addresses, either/both v4 or v6) as source address to connect to remote FTP hosts. Meaning that those FTP hosts would see you coming from the interface you choose (instead of the interface holding the default route that is selected when you create a Socket). 

The only thing required in order to achieving that is calling the Bind() method before connecting (the very same way you would do before a Listen() on server side)

For example lftp has parameters for that (see http://manpages.org/lftp)
- ftp:port-ipv4/6
- net:socket-bind-ipv4/6

I have quickly prototyped a change doing just that here:
- https://github.com/daviddenis-stx/FluentFTP/commit/6075f6266456a73979c1a329cc2e62f300cf74e9

Tested on a local proftpd server. Directory listings and downloads seem to work fine (not tested active mode though)

Maybe you would want to consider such a functionality for future releases.

Best

**Comment by robinrodricks** [comment]
It looks good, can you submit a PR?

We already have `client.AddressResolver` which helps to resolve the local address. Is your change related or completely different to that?

**Comment by daviddenis-stx** [comment]
Hello Robin,

Didn’t see about the DNS part already present. I had to use this to test on my side, it seems that if you have IPv6 addresses (ex: a few Zerotier networks) and your default route only has Ipv4 (most of us) asking .NET about you own IP addresses will omit those. Not sure why really.
The patch I made is probably not PR ready (though, I made my own nuget with it and it’s running production, seems to work correctly on two servers each of them having 3 different public IPv4 addresses).

I probably would need to at least remove that part. Also on my setup I modified csprojs to be able to build as the very old net20 and such I can’t build those anymore 😊

Let me know what would make your community happy and I’ll make the PR 😊

D

**Comment by robinrodricks** [comment]
Create a PR with whatever new code changes you have done. If there is any
change in the default behaviour that might affect other users just let me
know and I'll review it.

I don't think I need the changes in csproj within the PR, because you can
use conditional compiling to target certain platforms, like "#if CORE" to
only complete the code on .net core, etc. We have constants for all
platforms and groups.

Thanks.

**Comment by daviddenis-stx** [comment]
Hello again 😊

Tell you what, I’ll make a PR containing only *.cs and we’ll see if the SF manages to build/test it 😊

D

**Comment by robinrodricks** [comment]
Thanks for the PR, will you get some time to address my questions?

**Comment by daviddenis-stx** [comment]
Sorry, quite busy, let me check.

**Comment by robinrodricks** [comment]
Released.

https://www.nuget.org/packages/FluentFTP/34.0.0
