### ISSUE TITLE
Is FluentFTP thread safe?

### ISSUE THREAD

**Issue by Adhara3** [robinrodricks/FluentFTP#714]
I couldn't find anything in the faq, so I'm asking this explicitly.

I have an application with N threads, some of which require access to FTP. The access type is mainly _periodic_ meaning that every 1 sec I need to send a specific command (always from the same thread), or every 10 sec I need to check files for new downloads (from another thread).
Which is the suggested way to do?

1. One client fo all
2. One client per thread
3. One client per request

About option 3, I had a look at the code and I think this should be avoided because the `Dispose()` seems quite expensive, I just wanted a confirmation that a Client left unused for  some time can be safely reused or if it's safer to Dispose it and create a new one.

Thanks a lot
A

PS Side note: the FTP server I'm running against is not _only_ a FTP server, but does much more, think about it as a sort of _REST API done via FTP_ ( ! ) with custom commands etc. As you can guess, it's not a standard server in any way. It's not my code, don't blame me for that...

**Comment by robinrodricks** [comment]
One client per thread. Cannot use one client across multiple threads. One
client per request seems nice in theory but you may run out of ports or the
server may block so many new requests.

**Comment by Adhara3** [comment]
Thanks a lot!

A

**Comment by zamgill** [comment]
How would you set it up as one client per thread? Would you set it up as a singleton?

**Comment by FanDjango** [comment]
> Would you set it up as a singleton?

No. You need a separate entity (client) for each thread, with its own resources et al. Some additional problems: Some servers might not accept multiple (concurrent) logins by the same user. You can image the difficulties?

**Comment by proviste** [comment]
> How would you set it up as one client per thread? Would you set it up as a singleton?

@zamgill 

You can leverage the "LifeScope" or "LifeStyle" capabilities of your Dependency Injection library to get a new FluentFTP client per thread
