### ISSUE TITLE
Minor parsing issue regarding File Exists

### ISSUE THREAD

**Issue by EdWinchester** [robinrodricks/FluentFTP#715]
Version 33.1.7.

Is it possible for you to add 

"file doesnot exist", 

to the  string[] fileNotFound in the FtpServerStrings located in the file FtpServerStrings.cs  ?

I have a server making that responds and if I change the source myself, so the FileExists function returns the correct answer again.

But would prefer pulling newer versions from github or nuget instead of having to add this line myself on future updates. 

Thank you

Best Regards
Jakob

**Comment by robinrodricks** [comment]
Done. Released.

https://www.nuget.org/packages/FluentFTP/33.1.8

**Comment by EdWinchester** [comment]
Thx!

**Comment by EdWinchester** [comment]
It works perfectly, Thank you very much for the speedy update!
