### ISSUE TITLE
Problem DownloadDirectory with SYST VOS

### ISSUE THREAD

**Issue by tn76** [robinrodricks/FluentFTP#720]
**FTP OS:** Stratus VOS

**FTP Server:** VSeries

**Computer OS:** Windows10

**FluentFTP Version:** last version

the remote folder seems to be duplicated 3 times 

%fra_tpo#m1_d03>env>tms>pgm>log/%fra_tpo#m1_d03>env>tms>pgm>log/%fra_tpo#m1_d03>env>tms>pgm>log No such file or directory. 

**Logs :**

```

[log_file_06-05-2021.txt](https://github.com/robinrodricks/FluentFTP/files/6433907/log_file_06-05-2021.txt)

```

**Comment by tn76** [comment]
Connection and SetWorkingDirectory are OK

Here is my code VB.net : 

Using ftpC As New FtpClient

ftpC.Host = My.Resources.S88FtpIP
ftpC.Port = CInt(My.Resources.S88FtpPort)
ftpC.Credentials = New NetworkCredential(My.Resources.S88FtpUser, My.Resources.S88FtpPwd)
ftpC.Connect()

ftpC.SetWorkingDirectory(My.Resources.S88LogDirectory)

ftpC.DownloadDirectory(My.Resources.LocalLogDirectory, ftpC.GetWorkingDirectory)

End Using

**Comment by robinrodricks** [comment]
The paths are not understood. What kind of wierd server is this?

`%fra_tpo#m1_d03>env>tms>pgm>log`

**Comment by tn76** [comment]
Hello,

This is a Stratus V Series ftServer 4400 System

For your information SetWorkingDirectory(%fra_tpo#m1_d03>env>tms>pgm>log) and GetListing(…) are OK
So I have managed a work around with those 2 functions

The problem is with DownloadDirectory(…)

Cordialement

Jérôme GUILLEMETTE


De : Robin Rodricks ***@***.***
Envoyé : vendredi 7 mai 2021 19:55
À : robinrodricks/FluentFTP ***@***.***>
Cc : Jérôme Guillemette ***@***.***>; Author ***@***.***>
Objet : Re: [robinrodricks/FluentFTP] Problem DownloadDirectory with SYST VOS (#720)


The paths are not understood. What kind of wierd server is this?

%fra_tpo#m1_d03>env>tms>pgm>log

**Comment by robinrodricks** [comment]
Can you please share the FluentFTP logs especially at the time of connecting to the server, so I can detect this server and then understand the path characters (`>` instead of `/`)

**Comment by tn76** [comment]
Here is the log file I have joined when I have opened the issue.
Is it enough ?


# Connect()
Status:   Connecting to ***:21
Response: 220 4612tpo FTP server (FTP 1.0 for Stratus STCP) ready. (Compatible with OS TCP/IP)
Command:  USER ***
Response: 331 Password required for ftp_info.
Command:  PASS ***
Response: 230 User ftp_info.SysAdmin logged in.
Command:  FEAT
Response: 500 Command not understood.
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 215 VOS
Warning:  Cannot auto-detect listing parser for system 'Unknown', using Unix parser

# SetWorkingDirectory("%fra_tpo#m1_d03>env>tms>pgm>log")
Command:  CWD %fra_tpo#m1_d03>env>tms>pgm>log
Response: 250 CWD command successful.

# GetWorkingDirectory()
Command:  PWD
Response: 257 "%fra_tpo#m1_d03>env>tms>pgm>log" is current directory.

# DownloadDirectory("C:\S88CamcoReport\", "%fra_tpo#m1_d03>env>tms>pgm>log", Update, Skip, None, null)

# DirectoryExists("%fra_tpo#m1_d03>env>tms>pgm>log/")

# GetWorkingDirectory()
Command:  PWD
Response: 257 "%fra_tpo#m1_d03>env>tms>pgm>log" is current directory.
Command:  CWD %fra_tpo#m1_d03>env>tms>pgm>log
Response: 250 CWD command successful.
Command:  CWD %fra_tpo#m1_d03>env>tms>pgm>log
Response: 250 CWD command successful.

# GetWorkingDirectory()
Command:  PWD
Response: 257 "%fra_tpo#m1_d03>env>tms>pgm>log" is current directory.

# GetListing("%fra_tpo#m1_d03>env>tms>pgm>log/%fra_tpo#m1_d03>env>tms>pgm>log/", Size)

# GetWorkingDirectory()
Command:  PWD
Response: 257 "%fra_tpo#m1_d03>env>tms>pgm>log" is current directory.
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "LIST %fra_tpo#m1_d03>env>tms>pgm>log/%fra_tpo#m1_d03>env>tms>pgm>log/%fra_tpo#m1_d03>env>tms>pgm>log", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||60004|)
Status:   Connecting to ***:60004
Command:  LIST %fra_tpo#m1_d03>env>tms>pgm>log/%fra_tpo#m1_d03>env>tms>pgm>log/%fra_tpo#m1_d03>env>tms>pgm>log
Response: 550 LIST: %fra_tpo#m1_d03>env>tms>pgm>log/%fra_tpo#m1_d03>env>tms>pgm>log/%fra_tpo#m1_d03>env>tms>pgm>log No such file or directory.
Status:   Disposing FtpSocketStream...

# CloseDataStream()

# DownloadServerFiles("0 files")

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Response: 221 Goodbye.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...

Cordialement

Jérôme GUILLEMETTE

De : Robin Rodricks ***@***.***
Envoyé : mardi 18 mai 2021 09:32
À : robinrodricks/FluentFTP ***@***.***>
Cc : Jérôme Guillemette ***@***.***>; Author ***@***.***>
Objet : Re: [robinrodricks/FluentFTP] Problem DownloadDirectory with SYST VOS (#720)


Can you please share the FluentFTP logs especially at the time of connecting to the server, so I can detect this server and then understand the path characters (> instead of /)

**Comment by robinrodricks** [comment]
Great, thanks.

**Comment by FanDjango** [comment]
Perhaps someone can use the mechanism for custom parsers and other custom handlers to support Stratus VOS VSeries FTP server. The filepath/filename paradigms are strange, so therefore it needs someone who has experience on this system.
