### ISSUE TITLE
Incorrect directory listing on "Failed to connect to host" exception

### ISSUE THREAD

**Issue by pdavis86** [robinrodricks/FluentFTP#723]
**FTP OS:** Windows

**FTP Server:** Azure Web App

**Computer OS:** Windows

**FluentFTP Version:** 34.0.0

When running a lot of operations I have found that sometimes the connection drops so a new IOException("Failed to connect to host.") is thrown on line 919 of FtpSocketStream.cs. That exception is then caught and ignored by line 608 of FtpClient_Listing.cs with the comment "// suppress all other types of exceptions". The result is that there is a silent failure and FluentFTP incorrectly returns that the directory contains no files.

**Comment by jsantos74** [comment]
I have the same problem...

**Comment by pdavis86** [comment]
Looks like the change had decreased the frequency of the issue but I am still sometimes seeing empty enumerable on calling GetListing() but a second attempt does retrieve the listing

**Comment by FanDjango** [comment]
I would like to refer this to #1030 - because of "When running a lot of operations". Let me close this and please follow the #1030 issue, please.
