### ISSUE TITLE
About some options, microcontrollers, esp32.

### ISSUE THREAD

**Issue by Yuxekova** [robinrodricks/FluentFTP#725]
**FTP OS:** FreeRTOS

**FTP Server:** Esp32 Microcontroller

**Computer OS:** Windows 10

**FluentFTP Version:**  20.0.0 

Hi, i'm new to FTP,  i found this package for FTP. I am working at local network, i got a esp32 microcontroller on server side of ftp-uses FreeRTOS, able to socket programming using lwIP ). I am able to upload files to server using FileZilla only using options given pictures below. How do i use these options using FluentFTP ? ( Thanks for package, sorry for bad English). 

https://imgur.com/Dmm33JI
https://imgur.com/jp2N0M2
https://imgur.com/y7Dmt3l
https://imgur.com/SeLUPHn

**Comment by robinrodricks** [comment]
Just set the Host and the Credentials. All others keep default.
