### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by Avallex** [robinrodricks/FluentFTP#728]
**FTP OS:** Windows

**FTP Server:** FileZilla

**Computer OS:** Windows

**FluentFTP Version:** v34.0.0

__Unexpected EOF when uploading file to remote machine.__

" System.Net.Security:  Received an unexpected EOF or 0 bytes from the transport stream."

Getting that ^ error when uploading a file to server, entire console output is included in pastebin link.

Not sure if I am doing something wrong, the same file is being uploaded to several machines but this only seems to happen on  a few.

Thanks!

**Logs :**
https://pastebin.com/VSCYBmQj

**Comment by Avallex** [comment]
The actual error on FileZilla shows a TLS session resumption error

```
(000036)04/06/2021 10:08:37 - service (192.168.2.126)> 200 Type set to I
(000036)04/06/2021 10:08:37 - service (192.168.2.126)> EPSV
(000036)04/06/2021 10:08:37 - service (192.168.2.126)> 229 Entering Extended Passive Mode (|||50095|)
(000036)04/06/2021 10:08:37 - service (192.168.2.126)> STOR /JJW2021.deskthemepack
(000036)04/06/2021 10:08:37 - service (192.168.2.126)> 150 Opening data channel for file upload to server of "/JJW2021.deskthemepack"
(000036)04/06/2021 10:08:37 - service (192.168.2.126)> 450 TLS session of data connection has not resumed or the session does not match the control connection
```

**Comment by Avallex** [comment]
Well looks like this relates to #311 this may have nothing to do with unexpected EOF after all.

**Comment by robinrodricks** [comment]
Seems that way to me too.
