### ISSUE TITLE
Suggestion: Support IAsyncEnumerable for GetListingAsync

### ISSUE THREAD

**Issue by Khitiara** [robinrodricks/FluentFTP#730]
**FTP OS:** All

**FTP Server:** All

**Computer OS:** Windows

**FluentFTP Version:** 34.0.0

Add support for [IAsyncEnumerable](https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8) to the `GetListingAsync()` method on `FtpClient`, allowing `FtpListItem`s to be processed as they are received and parsed, rather than the current behavior which waits to receive all items before returning. For large (especially recursive) listing returns this can save allocating a sufficiently large array to store all list items and seems to fit in with the intended purpose of `IAsyncEnumerable` in any case.

**Comment by Khitiara** [comment]
In addition this may be applicable to `DownloadDirectoryAsync`

**Comment by Khitiara** [comment]
Closing because im dumb and didnt notice that that literally exists lol

**Comment by robinrodricks** [comment]
Good point. The code exists but is disabled because it was pulling in an
additional dependency from nuget (I think linq.async or something like
that) which was breathing many users' build. Therefore I was forced to
disable it.
