### ISSUE TITLE
Root folder files fail to download when a folder rule exists to exclude subfolders and a subfolder exists with the same name as the root folder

### ISSUE THREAD

**Issue by mikehowell** [robinrodricks/FluentFTP#737]
**FTP OS:** Windows

**FTP Server:** FileZilla

**Computer OS:** Windows

**FluentFTP Version:** 33.0.3 (although I've upgraded the NuGet package to the latest version - 34.0.0 and still observe this behaviour).

We use FluentFTP to download directories from a number of sources.  In most cases, we only care about the files in the root folder of the ftp server and in a subset of cases, only certain files in the root folder.  This was one of the drivers for using the _DownloadDirectory_ method as we can easily add rules to exclude files we don't want to download.  To ensure that we don't download subfolders, we use a rule that excludes subfolders like this:

```
//exclude subfolders from the download with a rule
var subfolders = _ftpClient.GetListing(_directories.RemotePath)
    .Where(x => x.Type == FtpFileSystemObjectType.Directory)
    .Select(x => x.Name)
    .ToList();

_rules.Rules.Add(new FtpFolderNameRule(false, subfolders));
```
This has been working well, however, when there is a subfolder with the same name as the root folder, adding the subfolder rule results in the files in the root folder being skipped too.

For example, if the remote directory is **/ftpServer/ftpFolder** and within the root folder there is a folder called **ftpFolder**, then the above rule results in no files downloaded from the root directory.

This isn't the behaviour we were expecting.  Should we be using the _DownloadFile_ method instead?

As a workaround we check if a subfolder matches the root folder name, if so we don't add that folder to the subfolders rule but then do a recursive directory listing and also exclude all files not in the root folder.  A side affect of this is that the subfolder with the name that matches the root folder is downloaded but not it's contents.

```
//if a subfolder exists with the same name as the root folder
if (directoryListing.Any(x => x.Type == FtpFileSystemObjectType.Directory && _directories.RemotePath.EndsWith($"{x.Name}/")))
{
    //exclude all subfolders except the one that matches the root folder 
    subfolders = directoryListing
        .Where(x => x.Type == FtpFileSystemObjectType.Directory 
                && !_directories.RemotePath.EndsWith($"{x.Name}/"))
        .Select(x => x.Name)
        .ToList();

    var directoryListingRecursive = _ftpClient.GetListing(_directories.RemotePath, FtpListOption.Recursive);
    
    //exclude all files in subfolders
    //this will prevent files in the subfolder whose name matches the root from downloading
    filesInSubfolders = directoryListingRecursive
        .Where(x => x.Type == FtpFileSystemObjectType.File 
                && x.FullName != $@"{_directories.RemotePath}{x.Name}")
        .Select(x => x.Name)
        .ToList();
}
else
{
    //exclude subfolders from the download with a rule
    subfolders = directoryListing
        .Where(x => x.Type == FtpFileSystemObjectType.Directory)
        .Select(x => x.Name)
        .ToList();                        
}

_rules.Rules.Add(new FtpFileNameRule(false, filesInSubfolders));
_rules.Rules.Add(new FtpFolderNameRule(false, subfolders));
```

**Logs :**

Please let me know if logs would be useful for this issue and I will attempt to generate them.

Please note that the FTP OS, FTP Server and Computer OS listed are ones where I've created my own VM and recreated this issue.  I expect we'd have a range of different combinations across our customer base.

**Comment by robinrodricks** [comment]
This is great. Let me see what I can do to help with this use case. You
just want to download one directory without recursion am I right?

**Comment by mikehowell** [comment]
Hi Robin, yes, I guess that's an accurate summary - we want to download one directory without the recursion.  I've attached an annotated image from FileZilla which will hopefully make it a bit clearer

![FileZillaFolderAndFilesExample](https://user-images.githubusercontent.com/8772905/125545607-b6239c80-1501-4ac6-a5aa-47e92b05b99c.png)

**Comment by robinrodricks** [comment]
Released.

https://www.nuget.org/packages/FluentFTP/35.0.0

**Comment by robinrodricks** [comment]
Hi @mikehowell, can you try the latest build from nuget and tell me if it resolves your issue? I need feedback on this please.

You need to set `startSegment = 1` when constructing your `FtpFolderNameRule`.
