### ISSUE TITLE
Open with  plain FTP (insecure)

### ISSUE THREAD

**Issue by ecatugy** [robinrodricks/FluentFTP#742]
Computer OS: Windows Server

**FluentFTP Version:** 34.0.1.0

I can't open a connection only use plain FTP (insecure), I used all different types of configuration of FtpClient, but none worked.

```

**Comment by robinrodricks** [comment]
Try using the AutoConnect or AutoDetect API. If all of those fail means we cannot connect to your server.

And also try with FileZilla Client.
