### ISSUE TITLE
FileExists returns false when file exists

### ISSUE THREAD

**Issue by qa-alistair** [robinrodricks/FluentFTP#745]
**FTP OS:** Windows

**FTP Server:** Microsoft FTP Service (Version 5.0).

**Computer OS:** Windows_NT version 5.0

**FluentFTP Version:** 27.1.1

Given I call the FileExists() function, when the file does exist at the server, then the function returns false.

In the log entries below I have replaced some information with * (over and above what was already replaced).

```


# Connect()
Status:   Connecting to ***:21
Response: 220 ************ Microsoft FTP Service (Version 5.0).
Status:   Detected FTP server: WindowsServerIIS
Command:  USER ***
Response: 331 Password required for ***.
Command:  PASS ***
Response: 230 User *** logged in.
Command:  FEAT
Response: 500 'FEAT': command not understood
Status:   Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
Command:  SYST
Response: 215 Windows_NT version 5.0

# FileExists("/***/send/J35S1_23072021.M8.csv")

# GetNameListing("/***/send")
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "NLST /***/send", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||7315|)
Status:   Connecting to ***:7315
Command:  NLST /***/send
Response: 125 Data connection already open; Transfer starting.
Status:   Disposing FtpSocketStream...

# CloseDataStream()
Response: 226 Transfer complete.
Status:   Disposing FtpSocketStream...

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Response: 221  
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...

```

**Comment by qa-alistair** [comment]
I note from the logs that GetNameListing() is used..

When I use this in code, I can see the issue with the returned listing entries:

![image](https://user-images.githubusercontent.com/85484759/127659295-3369839b-df98-412f-bc92-d0ce38f7c861.png)

i.e. the "\\" in the path where I expect to see "/".

Have I missed something here? I am not sure why the listing would return in this format.

**Comment by qa-alistair** [comment]
As a workaround for now I have this:

**Notes**

- **_relativePath_** parameter is passed in the format "directory1/directory2/filename.extension"
- File listing entries are returned from GetNameListing() as "directory1/directory2\\\filename.extension"

`		public bool FileExists(string relativePath)
		{

			using (var conn = new FtpClient(_hostAddress, _username, _password))
			{
				conn.Connect();

				string directoryPath = Path.GetDirectoryName(relativePath).Replace("\\", "/");
				string filename = relativePath
					.Replace(directoryPath, "")
					.Replace("/", "");

				string[] a = conn.GetNameListing(directoryPath);


				for (int i = 0; i < a.Length; i++)
				{
					string serverFilename = a[i]
						.Replace(directoryPath, "")
						.Replace("\\", "");

					if (serverFilename.ToUpper() == filename.ToUpper())
					{
						return true;
					}
				}

				return false;
			}
		}`

**Comment by robinrodricks** [comment]
This is a good solution, let me see if I can integrate it so it works with other types of servers as well.

**Comment by robinrodricks** [comment]
I have fixed this in another way. Can you check if it works for you?

[FluentFTP.34.0.2_BETA1.zip](https://github.com/robinrodricks/FluentFTP/files/6911146/FluentFTP.34.0.2_BETA1.zip)

**Comment by robinrodricks** [comment]
Published.

https://www.nuget.org/packages/FluentFTP/34.0.2

**Comment by qa-alistair** [comment]
@robinrodricks Thank you. I will check out the fix and verify when I have a moment.

**Comment by qa-alistair** [comment]
@robinrodricks Sorry but I can see the same issue occurring in version 34.0.2

**Comment by robinrodricks** [comment]
Released.

https://www.nuget.org/packages/FluentFTP/35.0.0

**Comment by qa-alistair** [comment]
> @qa-alistair Can you check this build please?
> 
> [FluentFTP.34.1.0_BETA3.zip](https://github.com/robinrodricks/FluentFTP/files/7067083/FluentFTP.34.1.0_BETA3.zip)

Thanks @robinrodricks - Yes, I can confirm this one works fine.

**Comment by robinrodricks** [comment]
Great!
