### ISSUE TITLE
ftp Resume

### ISSUE THREAD

**Issue by hjs-wcl** [robinrodricks/FluentFTP#759]
if (fileData.CanSeek && existsMode == FtpRemoteExists.Resume)
        throw new ArgumentException("You have requested resuming file upload with FtpRemoteExists.AppendResume, but the local file stream cannot be seeked. Use another type of Stream or another existsMode.", nameof (fileData));
      

fileData.CanSeek is True
so throw exception..............................

**Comment by robinrodricks** [comment]
Ah yes good one, will fix it.

**Comment by robinrodricks** [comment]
Fixed and released.

https://www.nuget.org/packages/FluentFTP/35.0.5

Thanks for reporting!
