### ISSUE TITLE
Error EPSV failed download

### ISSUE THREAD

**Issue by marvado33** [robinrodricks/FluentFTP#760]
** Computer OS: **?

Windows 10

** FluentFTP version: **?

version: 35.0.4

<enter details about your bug report / feature request here>

I am making a connection to download three files, the first file is always downloading, but the second and third download sometimes and the only message that allows me to see the server is the one that I have attached below. The solution I have managed is to connect three times in a row and force three connections and not one like before. Do you know if I may be missing a parameter?

** Records: **

"response": "Could not get EPSV port of: 71121"

**Comment by robinrodricks** [comment]
Then try using PASV or use `client.AutoConnect()` with the latest FluentFTP version.
