### ISSUE TITLE
Multiline FEAT response.

### ISSUE THREAD

**Issue by b0urb4k1** [robinrodricks/FluentFTP#766]
**FTP Server:** ProFTPD

**FluentFTP Version:** 35.0.5

ProFTPD implements MultilineRFC2228 by default, thus the respsonse of the FEAT request has multiple lines starting with 211-

```
211-Features:\n211-AUTH TLS\n211-CCC\n211-CLNT\n211-EPRT\n211-EPSV\n211-HOST\n211-LANG en-GB.UTF-8*\n211-MDTM\n211-MFF modify;UNIX.group;UNIX.mode;\n211-MFMT\n211-MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.groupname*;UNIX.mode*;UNIX.owner*;UNIX.ownername*;\n211-PBSZ\n211-PROT\n211-REST STREAM\n211-SIZE\n211-SSCN\n211-TVFS\n211-UTF8\n
```

It would be nice if FluentFTP would be able to parse repsonses according to MultilineRCF2228

**Comment by robinrodricks** [comment]
Released thanks to a PR by @FanDjango 

https://www.nuget.org/packages/FluentFTP/37.0.1
