### ISSUE TITLE
What is the equivalent of PlainTextEncryption for .net core ?

### ISSUE THREAD

**Issue by za3zilla** [robinrodricks/FluentFTP#791]
I migrated my project from .net 4.7.2 to .net 5 and I was faced with the fact that with .netCore, FluentFTP.FtpClient does not handle CCC command (aka PlainTextEncrption bool) and obviously the connexion to our FTPS servers are no longer working.

Is there an equivalent for said configuration on .netCore or is it yet to be implemented ?

thank you for your help :)

**Comment by robinrodricks** [comment]
It is not currently supported on .NET core, due to some internal stream handling logic missing from the .NET core framework compared to .NET framework.
