### ISSUE TITLE
How to upload posted IFormFile to ftp?

### ISSUE THREAD

**Issue by mohammadsafavi** [robinrodricks/FluentFTP#809]
**FTP OS:** Unix / Windows / Embedded

**FTP Server:** Pure-FTPd / DrFTPD / Vsftpd / ProFTPD / Vax / VMS / OpenVMS / Tandem / HP NonStop Guardian / IBM OS400 / AS400 / Windows CE

**Computer OS:** ?

**FluentFTP Version:** ?

<write details about your bug report / feature request here>

**Logs :**

```

<paste logs here>

```

**Comment by mohammadsafavi** [comment]
I found it.
`  public static void UploadFile(IFormFile formFile)
        {
            using (var ftp = new FtpClient(FtpAddress, UserName, Password))
            {
                ftp.Connect();

                // define the progress tracking callback
                Action<FtpProgress> progress = delegate (FtpProgress p)
                {
                    if (p.Progress == 1)
                    {
                        // all done!
                    }
                    else
                    {
                        // percent done = (p.Progress * 100)
                    }
                };

                // upload a file with progress tracking
                //ftp.UploadFile(formFile, "/public_html/temp/README.md", FtpRemoteExists.Overwrite, false, FtpVerify.None, progress);
                ftp.Upload(formFile.NewFile().Content, "/" + formFile.FileName, FtpRemoteExists.Overwrite, false, progress);

            }`

**Comment by uzeyir06** [comment]
`await client.UploadStream(file.OpenReadStream(), eklenecek, FtpRemoteExists.Overwrite, true);`

Bu sorununu çözer.
