### ISSUE TITLE
Do you support SOCKS5 proxies?

### ISSUE THREAD

**Issue by pwallner** [robinrodricks/FluentFTP#82]
is working with socks5?

I used this code, but it doesn't work
```
Dim fluproxy As FluentFTP.Proxy.ProxyInfo = New FluentFTP.Proxy.ProxyInfo
            fluproxy.Host = "127.0.0.1"
            fluproxy.Port = 3000
            fluproxy.Credentials = New NetworkCredential("", "")

            Dim client22 = New FluentFTP.Proxy.FtpClientUserAtHostProxy(fluproxy) ' FtpClient()
            client22.Host = "192.168.0.246"
            client22.Port = 21
            'client22.SslProtocols = System.Security.Authentication.SslProtocols.Tls12
            'if you don't specify login credentials, we use the "anonymous" user account
            client22.Credentials = New NetworkCredential("xxx", "yyyy")


            'begin connecting to the server
            client22.Connect()
```

without proxy everything is working...

**Comment by hgupta9** [comment]
I don't think SOCKS proxy support has been implemented. Only HTTP 1.1 and User@Host AFAIK. Maybe the authors of the proxy can confirm otherwise. @Zoltan666 @elmar69 @L3Z4

I suggest using [EDT FTP](http://enterprisedt.com/products/edtftpnet/) as it has support for SOCKS proxy, but NOT in free version. As per [docs](http://enterprisedt.com/products/edtftpnet/doc/manual/index.html):

> Proxy support is not included in edtFTPnet/Free.

**Comment by pwallner** [comment]
I found [this](https://github.com/poma/ProxySocket), maybe it helps?? I can connect via Socks5. But with this, I'm far away from any ftp solution...

**Comment by pwallner** [comment]
And [here](https://github.com/bentonstark/starksoft-aspen) I found this which works, but I wish if you can implement this...

[Here](http://stackoverflow.com/questions/73544/ftp-client-class-for-net) I found the code for starksoft ftp:
```
Socks4ProxyClient socks = new Socks4ProxyClient("socksproxyhost",1010);
FtpClient ftp = new FtpClient("ftpshost",2010,FtpSecurityProtocol.Tls1Explicit);
ftp.Proxy = socks;
ftp.Open("userid", "******");
ftp.PutFile(@"C:\519ec30a-ae15-4bd5-8bcd-94ef3ca49165.xml");
Console.WriteLine(ftp.GetDirListAsText());
ftp.Close();
```

**Comment by gyma11** [comment]
Any updates here? Did anyone manage to get it running with a SOCKS5 proxy?

**Comment by robinrodricks** [comment]
Nope, but you can help. Find a SOCKS5 library that can be used with C# as a starting point.

**Comment by robinrodricks** [comment]
@pwallner @gyma11 Are you guys able to help me test this feature if I develop it?

Some libraries that I might integrate with:

- https://github.com/GreatFireWall/Socklient
- https://github.com/TheSuunny/Yove.Proxy
- https://github.com/MihaZupan/HttpToSocks5Proxy
- https://github.com/extremecodetv/SocksSharp
- https://github.com/AeonLucid/Socks5Wrap.NET/tree/master/Socks5Wrap

**Comment by pwallner** [comment]
Sure, I will help!! Thx in advance

**Comment by gyma11** [comment]
> @pwallner @gyma11 Are you guys able to help me test this feature if I develop it?
> 
> Some libraries that I might integrate with:
> 
> * https://github.com/GreatFireWall/Socklient
> * https://github.com/TheSuunny/Yove.Proxy
> * https://github.com/MihaZupan/HttpToSocks5Proxy
> * https://github.com/extremecodetv/SocksSharp
> * https://github.com/AeonLucid/Socks5Wrap.NET/tree/master/Socks5Wrap

In the meantime we have switched to another library. But yes, if you would implement this, I'm happy to help you by testing it.

**Comment by robinrodricks** [comment]
To start with, can you review the list of libraries I sent and help me
narrow down the list?

Perhaps tell me which features you are looking for in a socks proxy, or
which version of socks you need?

**Comment by ken915007** [comment]
we need SOCKS5 proxies, please provide.

**Comment by bjth** [comment]
@robinrodricks Is there a contributions guideline for changes like these? I've just about finished implementing the basics for this on our private fork. Would you be interested in a PR?

**Comment by robinrodricks** [comment]
@bjth  Always interested in PRs, I can always add comments to it if any changes are needed.

**Comment by robinrodricks** [comment]
Happy to announce thaht SOCKS5 proxies are now supported in FluentFTP 35! 

Released in this version:
https://www.nuget.org/packages/FluentFTP/35.2.0

Help:
https://github.com/robinrodricks/FluentFTP/wiki/FTPS-Proxies#faq_loginsocksproxy

All credits go to [bjth](https://github.com/bjth).
