### ISSUE TITLE
Remove System.Net.Primitives reference for .Net Framework v4.5 build

### ISSUE THREAD

**Issue by FootStark** [robinrodricks/FluentFTP#828]
**Computer OS:** Win10 / .NET Framework 4.7

**FluentFTP Version:** 35.2. +

<write details about your bug report / feature request here>

Since FluentFTP 35.2. + (nuget) the package for .NET Framework v4.5 includes a dependency to `System.Net.Primitives >=4.3.0`. This breaks .NET Framework code using it. It would be great if the reference could be removed.

**Comment by robinrodricks** [comment]
Can you try this and see if it works?

https://www.nuget.org/packages/FluentFTP/37.0.0
