### ISSUE TITLE
FtpTrace.LogToConsole ignored?

### ISSUE THREAD

**Issue by midget35** [robinrodricks/FluentFTP#829]
How do I stop the client from filling my Console with verbose information?

I've tried all the below in every combination :(

            FtpTrace.LogToFile = null;
            FtpTrace.LogFunctions = false;
            FtpTrace.AddListener(new TextWriterTraceListener("log_file.txt") {
                Filter = new EventTypeFilter(SourceLevels.Error)
            });
            FtpTrace.LogToConsole = false;

**Comment by robinrodricks** [comment]
Show the logs and specify what part you find verbose?

**Comment by robinrodricks** [comment]
LogToConsole is honored at this line - https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Helpers/FtpTrace.cs#L189

**Comment by midget35** [comment]
Thank you very much. I needed to set the constant EnableTracing to false. Thank you for your great work on this library.

**Comment by robinrodricks** [comment]
You are most welcome.
