### ISSUE TITLE
IO Exeption when doing GetListing

### ISSUE THREAD

**Issue by DickGerritHof** [robinrodricks/FluentFTP#830]
**Computer OS:** Windows 10 x86

**FluentFTP Version:** 20.0.0
Hi Robin,

I am getting a IO Exeption when doing a GetListing when I am connected to the server. 
I have placed this in a click event from a button

            using (var client = new FtpClient(Profile.ServerAddress, Profile.UserName, Profile.Password))
            {
                client.EncryptionMode = FtpEncryptionMode.Explicit;
                client.SslProtocols = SslProtocols.Tls12;

                client.Connect();
                
                try
                {
                    foreach (FtpListItem item in client.GetListing(Profile.RemoteFolder,FtpListOption.Recursive))
                    {
                        switch (item.Type)
                        {
                            case FtpFileSystemObjectType.Directory:
                                Console.WriteLine("Directory!  " + item.FullName);
                                Console.WriteLine("Modified date:  " + client.GetModifiedTime(item.FullName));
                                break;
                            case FtpFileSystemObjectType.File:
                                Console.WriteLine("File!  " + item.FullName);
                                Console.WriteLine("File size:  " + client.GetFileSize(item.FullName));
                                Console.WriteLine("Modified date:  " + client.GetModifiedTime(item.FullName));
                                Console.WriteLine("Chmod:  " + client.GetChmod(item.FullName));
                                break;
                            case FtpFileSystemObjectType.Link:
                                break;

                        }
                    }
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message, "Test Get listing", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
                client.Disconnect();
            } 

What am I doing wrong I know I have a good connection because I can read all certificate details

**Logs :**

```

# Connect()
# Connect()
Status:   Connecting to ***.***.***.***:21
Response: 220-::: Welcome :::
Response: 220-All Unauthorized access is prohibited by Dutch Law.
Response: 220-All connections are logged.
Response: 220-::: Welcome :::
Response: 220-All Unauthorized access is prohibited by Dutch Law.
Response: 220-All connections are logged.
Response: 220 Any offence shall be prosecuted to the full extent of the law.
Response: 220 Any offence shall be prosecuted to the full extent of the law.
Command:  AUTH TLS
Command:  AUTH TLS
Response: 234 Using authentication type TLS
Response: 234 Using authentication type TLS
Status:   FTPS Authentication Successful
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.0810011.
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.0810011.
Command:  USER ***
Command:  ***
Response: 331 Password required for ***
Response: 331 Password required for ***
Command:  PASS ***
Command:  PASS ***
Response: 230 Logged on
Response: 230 Logged on
Command:  PBSZ 0
Command:  PBSZ 0
Response: 200 PBSZ=0
Response: 200 PBSZ=0
Command:  PROT P
Command:  PROT P
Response: 200 Protection level set to P
Response: 200 Protection level set to P
Command:  FEAT
Command:  FEAT
Response: 211-Features:
Response: MDTM
Response: REST STREAM
Response: SIZE
Response: MLST type*;size*;modify*;
Response: MLSD
Response: AUTH SSL
Response: AUTH TLS
Response: PROT
Response: PBSZ
Response: UTF8
Response: CLNT
Response: MFMT
Response: EPSV
Response: EPRT
Response: 211-Features:
Response: MDTM
Response: REST STREAM
Response: SIZE
Response: MLST type*;size*;modify*;
Response: MLSD
Response: AUTH SSL
Response: AUTH TLS
Response: PROT
Response: PBSZ
Response: UTF8
Response: CLNT
Response: MFMT
Response: EPSV
Response: EPRT
Response: 211 End
Response: 211 End
Status:   Text encoding: System.Text.UTF8Encoding
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Command:  OPTS UTF8 ON
Response: 202 UTF8 mode is always enabled. No need to send this command.
Response: 202 UTF8 mode is always enabled. No need to send this command.
Command:  SYST
Command:  SYST
Response: 215 UNIX emulated by FileZilla
Response: 215 UNIX emulated by FileZilla
Status:   Listing parser set to: Machine
Status:   Listing parser set to: Machine


# GetListing("/", Auto)
# GetListing("/", Auto)
Command:  TYPE I
Command:  TYPE I
Response: 200 Type set to I
Response: 200 Type set to I


# OpenPassiveDataStream(AutoPassive, "MLSD /", 0)
# OpenPassiveDataStream(AutoPassive, "MLSD /", 0)
Command:  EPSV
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||5906|)
Response: 229 Entering Extended Passive Mode (|||5906|)
Status:   Connecting to ***.***.***.***:5906
Status:   Connecting to ***.***.***.***:5906
Command:  MLSD /
Command:  MLSD /
Response: 150 Opening data channel for directory listing of "/"
Response: 150 Opening data channel for directory listing of "/"
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.IO.IOException' in FluentFTP.dll
Status:   There is stale data on the socket, maybe our connection timed out or you did not call GetReply(). Re-connecting...
Status:   There is stale data on the socket, maybe our connection timed out or you did not call GetReply(). Re-connecting...
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
Status:   Not sending QUIT because the connection has already been closed.
Status:   Not sending QUIT because the connection has already been closed.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...


# Dispose()
# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
The thread 0x1ff8 has exited with code 0 (0x0).
The thread 0x6024 has exited with code 0 (0x0).
```

**Comment by FanDjango** [comment]
Ok, let me try to see if we can find out what is going on here:

1. Issue is very old. Is this still of interest?
2. The message `Status:   There is stale data on the socket, maybe our connection timed out or you did not call GetReply(). Re-connecting...` tells me, we could get a more informative error message even with the contents of the stale data, if one would test this with a current version of FluentFTP and not the very old V20.

If there is no response, let's close this in a week or so.

**Comment by wallksharp** [comment]
Hi @FanDjango 

I met this issue on FluentFTP V35 and the latest V42 today.

My code with V42:

```csharp
FtpConfig config = new FtpConfig();

config.EncryptionMode = FtpEncryptionMode.Explicit;
config.SslProtocols = SslProtocols.Tls12; // I'm sure the server only supports TLS v1.2
config.DataConnectionType = FtpDataConnectionType.AutoPassive; // I also tried EPSV and PASV.
client = new FtpClient(ip, username, password, port, config, _loggerFluentFTP);
client.ValidateCertificate += new FtpSslValidation(OnValidateCertificate);
client.Connect();
FileInfo fi = new FileInfo(remotePath); // remotePath starts with '/'
if (!client.DirectoryExists(fi.DirectoryName))
{
    client.CreateDirectory(fi.DirectoryName);
}
client.SetWorkingDirectory(fi.DirectoryName);
client.UploadFile(localPath, fi.Name, FtpRemoteExists.Override, true, progress: progress);
```

The exception:

```log
System.AggregateException: One or more errors occurred. (Authentication failed because the remote party has closed the transport stream.)
 ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__64_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at FluentFTP.FtpSocketStream.ActivateEncryption(String targethost, X509CertificateCollection clientCerts, SslProtocols sslProtocols, Boolean isControlConnection)
   at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   at FluentFTP.FtpClient.OpenWrite(String path, FtpDataType type, Int64 fileLen)
   at FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String localPath, String remotePath, Boolean createRemoteDir, FtpRemoteExists existsMode, Boolean fileExists, Boolean fileExistsKnown, Action`1 progress, FtpProgress metaProgress)
```
FluentFTP V42 logs:

2022-11-02 06:04:07.1608|INFO|FluentFTP|>         OpenWrite("file2upload.mp4", Binary)
2022-11-02 06:04:07.1608|INFO|FluentFTP|Command:  TYPE I
2022-11-02 06:04:07.4196|INFO|FluentFTP|Response: 200 Type set to I
2022-11-02 06:04:07.4231|INFO|FluentFTP|>         OpenPassiveDataStream(PASV, "STOR file2upload.mp4", 0)
2022-11-02 06:04:07.4231|INFO|FluentFTP|Command:  PASV
2022-11-02 06:04:07.6827|INFO|FluentFTP|Response: 227 Entering Passive Mode (172,27,97,48,196,117)
2022-11-02 06:04:07.6827|INFO|FluentFTP|Status:   Connecting to ***:50293
2022-11-02 06:04:07.9555|INFO|FluentFTP|Command:  STOR file2upload.mp4
2022-11-02 06:04:08.2266|INFO|FluentFTP|Response: 150 Opening data channel for file upload to server of "/file2upload.mp4"
2022-11-02 06:04:08.8289|INFO|FluentFTP|Status:   Socket has stale data - prior to command execution
2022-11-02 06:04:08.8289|INFO|FluentFTP|Status:   Closing stream because of stale data
2022-11-02 06:04:08.8289|INFO|FluentFTP|Status:   Not sending QUIT because the connection has already been closed.
2022-11-02 06:04:08.8289|INFO|FluentFTP|>         Dispose()

FileZila and WinSCP worked well. FileZila log:

```log
Status: Initializing TLS...
Status: Verifying certificate...
Status: TLS connection established.
Command:    USER alkofiya
Response:   331 Password required for alkofiya
Command:    PASS ********
Response:   230 Logged on
Command:    PBSZ 0
Response:   200 PBSZ=0
Command:    PROT P
Response:   200 Protection level set to P
Status: Logged in
Status: Starting upload of D:\el.repository\el.videos\file2upload.mp4
Command:    CWD /
Response:   250 CWD successful. "/test" is current directory.
Command:    PWD
Response:   257 "/test" is current directory.
Command:    TYPE I
Response:   200 Type set to I
Command:    PASV
Response:   227 Entering Passive Mode (172,27,97,48,196,109)
Status: Server sent passive reply with unroutable address. Using server address instead.
Command:    STOR file2upload.mp4
Response:   150 Opening data channel for file upload to server of "/test/file2upload.mp4"
Response:   226 Successfully transferred "/test/file2upload.mp4"
Status: File transfer successful, transferred 19,043,409 bytes in 42 seconds
Status: Retrieving directory listing of "/test"...
Command:    PASV
Response:   227 Entering Passive Mode (172,27,97,48,196,73)
Status: Server sent passive reply with unroutable address. Using server address instead.
Command:    MLSD
Response:   150 Opening data channel for directory listing of "/test"
Response:   226 Successfully transferred "/test"
Status: Directory listing of "/test" successful
```

**Comment by FanDjango** [comment]
@wallksharp Hi,
can you provide the V42 log as VERBOSE for more diagnosis? FluentFTP V42 logs are only INFO.
Can you also open this as a **new** issue?

**Comment by wallksharp** [comment]
@FanDjango Hi,
Sorry, I forgot to set the log level. Here is that:
```log
2022-11-03 01:35:28.4133|INFO|FluentFTP|Command:  STOR testFile2Upload.mp4
2022-11-03 01:35:28.4133|DEBUG|FluentFTP|Status:   Waiting for response to: STOR testFile2Upload.mp4
2022-11-03 01:35:28.7031|INFO|FluentFTP|Response: 150 Opening data channel for file upload to server of "testFile2Upload.mp4"
2022-11-03 01:35:29.2651|INFO|FluentFTP|Status:   Socket has stale data - prior to command execution
2022-11-03 01:35:29.2651|DEBUG|FluentFTP|Status:   The stale data was: 
2022-11-03 01:35:29.2651|DEBUG|FluentFTP|Stale:    450 TLS session of data connection has not resumed or the session does not match the control connection
2022-11-03 01:35:29.2651|INFO|FluentFTP|Status:   Closing stream because of stale data
2022-11-03 01:35:29.2651|DEBUG|FluentFTP|Status:   Disposing FtpSocketStream...
2022-11-03 01:35:29.2651|INFO|FluentFTP|Status:   Not sending QUIT because the connection has already been closed.
2022-11-03 01:35:29.2651|DEBUG|FluentFTP|Status:   Disposing FtpSocketStream...
2022-11-03 01:35:29.2651|INFO|FluentFTP|>         Dispose()
2022-11-03 01:35:29.2651|DEBUG|FluentFTP|Status:   Disposing FtpClient object...
2022-11-03 01:35:29.2651|DEBUG|FluentFTP|Status:   Disposing FtpSocketStream...
```

PASVEX did not work as well.

I saw `Server sent passive reply with unroutable address. Using server address instead.` in FileZilla log too. And I saw it on another FTP server which I can use FluentFTP to upload files to. This doesn't seem to be a problem. You want an issue to discuss/address?

**Comment by FanDjango** [comment]
> This doesn't seem to be a problem

Yes, I checked and FluentFTP handles the cases of local unroutable addresses correctly for `PASV` etc.

> 450 TLS session of data connection has not resumed or the session does not match the control connection

So **your** problem  is a "Session Resume" problem, like all the others.

The original poster **did not** respond, we don't know the server type he connected to etc. I can deduce that is FileZilla, but the welcome message does not show the version.

He is not responding, so I was hoping to close the issue, as newer versions of FluentFTP produce better diagnostics in the log.

Now you have "hijacked" this, and I need to deduce from your text, it is filezilla. But once again the log is not telling me the filezilla version. You have removed the connection sequence.

> FileZila and WinSCP worked well. _FileZila log_:

That is the only sentence you wrote, where I must deduce, AHA! It is FileZilla.

The **complete** logs tell us so much, why must users always make excerpts? I don't see the capabilites, the welcome message and so on. And you have nowhere in the text stated what version of filezilla it may be.

With V42.1, once it is released, there will be no IO Exception. Instead, the failing AUTH will give an exception and you will immediately see the 450 error message.

**Comment by wallksharp** [comment]
Thanks @FanDjango 
My FTP server I is FileZilla Server 0.96. And the issue I met seems to be a bug of FileZilla Server (GunSSL).

Related:
https://forum.filezilla-project.org/viewtopic.php?style=246&f=6&t=54333
https://gitlab.com/gnutls/gnutls/-/issues/1303

**Comment by FanDjango** [comment]
@wallksharp Thanks for those links. And thanks for confirming my suspicions. Sadly, using .NET / SslStream / SChannel I have not yet found any possible workaround.

**Comment by FanDjango** [comment]
There is now a workaround. I wrote a GnuTLS wrapper for FluentFTP. https://github.com/robinrodricks/FluentFTP/wiki/FTPS-Connection-using-GnuTLS

Try that if this is stll an issue for you.
