### ISSUE TITLE
Can't get exception

### ISSUE THREAD

**Issue by Betadash** [robinrodricks/FluentFTP#831]
I'm trying to get exception for file download but even if can't download file it's not giving any exception.

**Comment by robinrodricks** [comment]
Show your code, show your logs.

**Comment by Betadash** [comment]
`try{
                    conn.DataConnectionType = FtpDataConnectionType.PORT;
                    conn.Port = 21;
                    conn.EncryptionMode = FtpEncryptionMode.None;
                    conn.Connect();
                    //conn.Dispose();
}
                catch (Exception ex)
                {}`
in that code there is no any problem if i close FTP it's giving an exception
but in this code
`try
                    {
                        await conn.DownloadFileAsync(temppath + @"\mods.zip", "/mods.zip", FtpLocalExists.Resume, FtpVerify.None);}
catch{}`
it's not giving any error even that FtpStatus is set to Failed

**Comment by robinrodricks** [comment]
We need the FluentFTP logs.

Try using AutoConnect rather than manually specifying options. PORT is really old I think.
