### ISSUE TITLE
Unexpected download "success" when internet cuts out

### ISSUE THREAD

**Issue by UnTimed** [robinrodricks/FluentFTP#845]
**FluentFTP Version:** 37.0.0

I'm using the method "DownloadFile" to download a file over FTP. It is working just fine in the usual situations so I'm trying a few odd cases. To know whether or not the download finished properly, I'm checking the "FtpStatus" object returned by the method, as indicated in the documentation of the method.

The issue comes when the download starts correctly but the internet cuts out in the middle of it. When this happens and the timeout is reached (in my case, I set it to 60 seconds) the method returns "FtpStatus.Success" just like if the download finished properly. The downloaded file is obviously not complete when checking its size and contents. This returned value is consistent no matter the amount of attempts, the target file or the target server.

Is this intended behaviour? If it's the case, am I missing the proper way to check if the download finished successfully? I cannot do a checksum as the server I'm connecting to doesn't support it, and I need to know whether the download finished correctly to log any incident properly.

**Comment by FanDjango** [comment]
I have just tried to reproduce this. I get an I/O Exception and "Failed" status. I don't even get a timeout. But I am simulating it by deactivating the network adapter during the transfer. Maybe that differs?

Your code? log?

**Comment by UnTimed** [comment]
> I have just tried to reproduce this. I get an I/O Exception and "Failed" status. I don't even get a timeout. But I am simulating it by deactivating the network adapter during the transfer. Maybe that differs?
> 
> Your code? log?

I simulate this by unplugging my internet cable from my computer. I mentioned the timeout because the waiting duration seems to be exactly that of the timeout I selected, but there's no log message explicitely saying it hits the timeout. I'll play around with this value to make sure that it is what's happening.

As for the code, here's what the problematic section looks like : 

``` 
using (FtpClient client = new FtpClient(hostname, 990, username, password))
            {
                try
                {
                    client.ValidateCertificate += VerifCertificat; // Manually checking the certificate, no issue happening there.
                    client.DataConnectionReadTimeout = 60000;
                    client.DataConnectionConnectTimeout = 30000;
                    client.RetryAttempts = 5;
                    client.EncryptionMode = FtpEncryptionMode.Implicit;

                    client.Connect();

                    if (!client.IsConnected)
                    {
                        // Setting values for logs.
                    }

                    Directory.CreateDirectory(fileDestinationPath);

                    var status = client.DownloadFile(cheminDestinationLocal, cheminFichierCible);
                    if (status != FtpStatus.Success)
                    {
                        // Setting values for logs.
                    }

                }
                catch (Exception ex)
                {
                    // Logging the exception.
                }
                finally
                {
                    if (client.IsConnected)
                    {
                        client.Disconnect();
                    }
                }
            }
```

You'll find the logs [here](https://github.com/robinrodricks/FluentFTP/files/8066854/log.txt).

**Comment by FanDjango** [comment]
I duplicated your code, set the filenames, credentials, host and port. I removed the `CreateDirectory` and used `OverWrite` on the download. Only one other difference: I need to use `AutoConnect`, otherwise I cannot establish the connection. Then I pull the cable during the 3GB download. I then get (after the long timeout): I/O Exception and status is "Failed", the `try` does not `catch` anything.

So where is any possibility for a difference? The `AutoConnect` maybe?

One other thing I **do** notice: The `Disconnect` is very unclean in this case, as it tries to issue `QUIT` (which it shouldn't, really), causing a number of stacked exceptions.

**Comment by UnTimed** [comment]
I cannot seem to be able to make `AutoConnect` work with the current code. I get the following logs : 

```
# AutoConnect()

# AutoDetect(True, False)

# Connect()
Status:   Connecting to ***:990
Status:   Disposing FtpSocketStream...

# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
```

I do not believe the server to be at fault here, since I can connect to it and interact with it just fine using other pieces of software. I do find it weird that using the `Connect` method lets me connect and download the file just fine, whereas the `AutoConnect` method fails.

I've looked through the `DownloadFile` method as well (in `FtpClient_FileDownload.cs`) and I'm stumped. The only way I found of getting the `DownloadFileInternal` method to return true when there is no internet connection would be if the program reached the "try/catch" statement at line 809, but to reach that statement it would have to exit the "while" statement at line 707 without throwing any exception. Meaning the `Read` method called at line 715 would need to return 0 instead of throwing an exception. We would also need the `readToEnd` variable (initialized at line 684) to be set to `true`, meaning the `GetFileSize` method called beforehand would have returned 0.

Sorry if that was a bit of a messy train of thought, but do you know if there's any chance of this happening?

**Comment by FanDjango** [comment]
`Connect` vs. `AutoConnect` : For me it is the other way around. Could you remove all `try` blocks in **your** code, just to see the native failures. Won't solve anything, but... let's clean up some more: remove all timeouts, retries etc. and I will do the same. Meanwhile I will try to find out why I cannot `Connect` and look at the code just like you did (`DownloadFile`).

**Comment by FanDjango** [comment]
Ok, I can connect now with `Connect(...)`. But I need to use `FtpEncryptionMode.Explicit;`.

I still cannot reproduce your problem. Here is my log and my code:

( I pull the cable during the RETR, there is a wait before the exception comes. There is another wait after the QUIT, which fails).

```
		static void My_845_Test()
		{
			string fileDestinationPath = @"D:\temp\test.bin";
			string targetFilePath = @"test.bin";

			void progress(FtpProgress p)
			{
				Console.WriteLine(p.Progress.ToString() + "% complete");
				Console.SetCursorPosition(0, Console.CursorTop - 1);
			}

			using (FtpClient client = new FtpClient("ftps", 21, "user", "pass"))
			{
				//try
				//{
				client.OnLogEvent = FTPLogEvent;
					client.ValidateCertificate += OnValidateCertificate; // Manually checking the certificate, no issue happening there.
					//client.DataConnectionReadTimeout = 60000;
					//client.DataConnectionConnectTimeout = 30000;
					//client.RetryAttempts = 5;
					client.EncryptionMode = FtpEncryptionMode.Explicit;
					client.ValidateAnyCertificate = true;

				client.Connect();

					if (!client.IsConnected)
					{
						// Setting values for logs.
					}

					// Directory.CreateDirectory(fileDestinationPath);

					var status = client.DownloadFile(fileDestinationPath, targetFilePath, FtpLocalExists.Overwrite, FtpVerify.None, progress);
					if (status != FtpStatus.Success)
					{
						// Setting values for logs.
					}

				//}
				//catch (Exception ex)
				//{
					// Logging the exception.
				//}
				//finally
				//{
					if (client.IsConnected)
					{
						client.Disconnect();
					}
				//}
			}
		}
```

```
>         Connect()
Status:   Connecting to xxx:21
Response: 220 (vsFTPd 3.0.3)
Status:   Detected FTP server: VsFTPd
Command:  AUTH TLS
Response: 234 Proceed with negotiation.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0,104923.
Command:  USER user
Response: 331 Please specify the password.
Command:  PASS ***
Response: 230 Login successful.
Command:  PBSZ 0
Response: 200 PBSZ set to 0.
Command:  PROT P
Response: 200 PROT now Private.
Command:  FEAT
Response: 211-Features:
Response: AUTH TLS
Response: EPRT
Response: EPSV
Response: MDTM
Response: PASV
Response: PBSZ
Response: PROT
Response: REST STREAM
Response: SIZE
Response: TVFS
Response: 211 End
Status:   Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Listing parser set to: Unix
>         DownloadFile("D:\temp\test.bin", "test.bin", Overwrite, None)
>         GetFileSize("test.bin")
Command:  SIZE test.bin
Response: 213 2147483648
>         OpenRead("test.bin", Binary, 0, 2147483648)
Command:  TYPE I
Response: 200 Switching to Binary mode.
>         OpenPassiveDataStream(AutoPassive, "RETR test.bin", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||25479|)
Status:   Connecting to xxx:25479
Command:  RETR test.bin
Response: 150 Opening BINARY mode data connection for test.bin (2147483648 bytes).
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0,0025146.
Status:   Disposing FtpSocketStream...
Status:   IOException for file D:\temp\test.bin : Unable to read data from the transport connection: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat..
Status:   Failed to download file.
Status:   Testing connectivity using Socket.Poll()...
Command:  QUIT
Warning:  FtpClient.Disconnect(): Exception caught and discarded while closing control connection: System.IO.IOException: Unable to read data from the transport connection: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat..
 ---> System.Net.Sockets.SocketException (10060): Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
....
....
....
Status:   Disposing FtpSocketStream...
>         Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
```

**Comment by UnTimed** [comment]
I tried changing to `FtpEncryptionMode.Explicit` but couldn't connect with either methods. Back to the original settings, removing all try/catch statements, retries and such shows that there isn't any exception being raised. Using a breakpoint the same way also confirms that the returned status is "Success". 

At this point I'm seriously considering the server itself to be the issue here, or at least the way I'm connecting to it. It's very weird that this kind of issue never happened with the previous tool though.

**Comment by FanDjango** [comment]
It means that either no exceptions are raised in `DownloadFileInternal` or that one **is** but it is being handled incorrectly. Breakpoints in there are the next thing, I suppose.

**Comment by UnTimed** [comment]
It seems like when no progress method is given, the file length is never obtained. This makes it so that the `readToEnd` is set to `true`, which was one of the main components of the situation I thought about earlier.

This means that if the `Read` method called line 715 (`while ((readBytes = downStream.Read(buffer, 0, buffer.Length)) > 0)`) returns 0, or -1, or anything like that, we will break out of the while statement from line 707. According to comments following this statement, this is only supposed to happen when EOF is reached, which then explains that the program believes at that point that the download was finished properly.

**Comment by FanDjango** [comment]
This is great. How shall we proceed?

**Comment by FanDjango** [comment]
I suppose we could check, if when zero bytes are returned, are we still connected. If not, BOOM.

**Comment by UnTimed** [comment]
> I suppose we could check, if when zero bytes are returned, are we still connected. If not, BOOM.

That sounds like a good way to fix that issue.

**Comment by FanDjango** [comment]
Who will do it?

**Comment by FanDjango** [comment]
Look at this part:

```
						// if we reach here means EOF encountered
						// stop if we are in "read until EOF" mode
						if (readToEnd || offset == fileLen) {
							break;
						}

						// zero return value (with no Exception) indicates EOS; so we should fail here and attempt to resume
						throw new IOException($"Unexpected EOF for remote file {remotePath} [{offset}/{fileLen} bytes read]");

```

It just needs a "small tweak", the if statement. The "BOOM" is already there.

**Comment by FanDjango** [comment]
I am testing right now, and even without progress (i.e. `readToEnd: true`, veryfied by breakpoint), it gets "catched" as expected by the catch at line 774.

```
					catch (IOException ex) {

						// resume if server disconnected midway, or throw if there is an exception doing that as well
						if (!ResumeDownload(remotePath, ref downStream, offset, ex)) {
							sw.Stop();
							throw;
						}
					}
```

Why not in your version?

**Comment by UnTimed** [comment]
> I am testing right now, and even without progress (i.e. `readToEnd: true`, veryfied by breakpoint), it gets "catched" as expected by the catch at line 774.
> 
> ```
> 					catch (IOException ex) {
> 
> 						// resume if server disconnected midway, or throw if there is an exception doing that as well
> 						if (!ResumeDownload(remotePath, ref downStream, offset, ex)) {
> 							sw.Stop();
> 							throw;
> 						}
> 					}
> ```
> 
> Why not in your version?

Good question. What method throws this exception on your end? The `Read` ?

**Comment by FanDjango** [comment]
One more topic: I changed the readToEnd logic some month(s) ago.

```
				// if the server has not provided a length for this file or
				// if the mode is ASCII or
				// if the server is IBM z/OS
				// we read until EOF instead of reading a specific number of bytes
				var readToEnd = (fileLen <= 0) || 
								(DownloadDataType == FtpDataType.ASCII) || 
								(ServerType == FtpServer.IBMzOSFTP);
```
This might actually even be my fault. The only problem is, your symptoms don't show up for me. I have no SIZE command being done, then readToEnd is true, and then I get the I/O Exception for the Read. I will do some research on the code prior to the change by using github blame. Please stand by...

**Comment by UnTimed** [comment]
> One more topic: I changed the readToEnd logic some month(s) ago.
> 
> ```
> 				// if the server has not provided a length for this file or
> 				// if the mode is ASCII or
> 				// if the server is IBM z/OS
> 				// we read until EOF instead of reading a specific number of bytes
> 				var readToEnd = (fileLen <= 0) || 
> 								(DownloadDataType == FtpDataType.ASCII) || 
> 								(ServerType == FtpServer.IBMzOSFTP);
> ```
> 
> This might actually even be my fault. The only problem is, your symptoms don't show up for me. I have no SIZE command being done, then readToEnd is true, and then I get the I/O Exception for the Read. I will do some research on the code prior to the change by using github blame. Please stand by...

Sounds good. I'll doublecheck on my side to make sure my install is correct. Don't have any more time today though, I'll check in again tomorrow morning.

**Comment by FanDjango** [comment]
Me, tomorrow afternoon

**Comment by FanDjango** [comment]
I had some more time to look at this. The recent PRs are ok and not at fault.

`fileLen` is needed in `DownloadFileInternal()` only if `progress` is requested and needs to be calculated. Otherwise, `OpenRead()` will decide wether to determine fileLen for itself or to use the value passed by its caller.

We need to determine _why_ **your** `while` loop is terminating because `readBytes = downStream.Read(buffer, 0, buffer.Length)` returns 0 instead of an exception happening.

I get the exception.

I would like you to test what happens when you deactivate the network adapter during the download instead of pulling the cable. I get an I/O exception immediately, no timeout wait. Please confirm that at least that works with and without `progress`.

The fact that `progress` yes/no influences this behaviour, needs to be investigated. Although, I need to remind: on your system, not on mine.

Let's continue, we will find it eventually.

**Comment by FanDjango** [comment]
Interesting. I am still thinking about the difference in behaviour of the `Read(...)` funcion between your and my program. One possible difference could be the targeted framework. Maybe they updated the behaviour to recognize the failure (or vice versa)

My test rig is a console application targeting .NET 5.0. What's yours?

And yes, one needs to think about a possible solution - and there are legitimate reasons for a `fileLen` to not be available, not just "do not need progress". It is an edge case, but let's see if there is a "universal" solution.

**Comment by FanDjango** [comment]
Can you, in your environment, put the following code behind the `while` loop, thereby making the end check a little more detailed:

Instead of:
```
						// if we reach here means EOF encountered
						// stop if we are in "read until EOF" mode
						if (readToEnd || offset == fileLen) {
							break;
						}
```
please put:
```
						if (offset >= fileLen) {
						    // We have the entire file
							break;
						}

						if (readToEnd) {
							// We MIGHT have the entire file
							// If we are still connected, then we do, otherwise we very
							// most probably do NOT
							if (IsConnected) {
								break;
							}
						}
```

**Comment by FanDjango** [comment]
Or if you prefer, less verbose:

```
						// if we reach here means EOF encountered
						// stop if we are in "read until EOF" mode
						if ((readToEnd && IsConnected) || offset == fileLen) {
							break;
						}
```

**Comment by UnTimed** [comment]
> Interesting. I am still thinking about the difference in behaviour of the `Read(...)` funcion between your and my program. One possible difference could be the targeted framework. Maybe they updated the behaviour to recognize the failure (or vice versa)
> 
> My test rig is a console application targeting .NET 5.0. What's yours?

Oh that might actually be the big difference here, I'm running a console application targetting .NET 4.8.

> And yes, one needs to think about a possible solution - and there are legitimate reasons for a `fileLen` to not be available, not just "do not need progress". It is an edge case, but let's see if there is a "universal" solution.

Agreed. The first solution that comes to my mind when it comes to the case where the `Read` method throws a timeout exception would be to set a bool to "remember" that the timeout happened, then when we reach the `GetReply` and we catch the other timeout exception, we check that bool. This way we can know whether the timeout on `GetReply` should be ignored (as it currently is) or if we should return false.

**Comment by UnTimed** [comment]
> Can you, in your environment, put the following code behind the `while` loop, thereby making the end check a little more detailed

I haven't managed to reproduce the issue where the `Read` method returns 0 since the time I recompiled my install of FluentFTP. No idea what triggered it but since currently I'm getting an exception, this part of the code is skipped altogether.

**Comment by FanDjango** [comment]
Change that in the following fashion, maybe? Should help, I think.

```
					catch (TimeoutException ex) {

						// fix: attempting to download data after we reached the end of the stream
						// often throws a timeout exception, so we silently absorb that here
						if (offset >= fileLen && !readToEnd) {
							break;
						}
						else {
							sw.Stop();
							throw;
						}
```

**Comment by UnTimed** [comment]
Yeah I think that will fix it actually.

**Comment by robinrodricks** [comment]
Released.
https://www.nuget.org/packages/FluentFTP/37.0.2
