### ISSUE TITLE
DownloadAsync with optional parameters

### ISSUE THREAD

**Issue by YipingRuan** [robinrodricks/FluentFTP#860]
**FluentFTP Version:** 37.0.2.0

What should be the correct way to use `DownloadAsync`？

https://github.com/robinrodricks/FluentFTP/blob/80e350bccd8adf0cad905fe9407d2c27a1841e97/FluentFTP/Client/FtpClient_FileDownload.cs#L624
https://github.com/robinrodricks/FluentFTP/blob/80e350bccd8adf0cad905fe9407d2c27a1841e97/FluentFTP/Client/FtpClient_FileDownload.cs#L649

Both methods has 1 string parameter and the rest are optional, so it is ambiguous, any chance I can simply use the below?
```c#
var file = await coon.DownloadAsync("xxxxx");
```
![image](https://user-images.githubusercontent.com/5492274/160322102-df5e4582-dbf6-4307-93a4-08e849e0ced1.png)

Thank you!

**Comment by robinrodricks** [comment]
For now you can just use `DownloadAsync("xxxxx", 0)`

**Comment by pri-kise** [comment]
I was looking for this issue, since I got a similiar warning for DownloadBytes.
https://github.com/robinrodricks/FluentFTP/blob/07c890c4af1bc01102402f01141fa174c12e1afa/FluentFTP/Client/AsyncClient/DownloadBytes.cs#L27C29-L27C42
