### ISSUE TITLE
Feature Request: Return Stream api's

### ISSUE THREAD

**Issue by jjxtra** [robinrodricks/FluentFTP#863]
Provide api overloads that return the Stream object directly so it can be wrapped with StreamReader or other processing without having to fill a stream or file first.

**Comment by robinrodricks** [comment]
@jjxtra  why not use the OpenRead/OpenWrite APIs, they directly provide the `Steam`.

**Comment by robinrodricks** [comment]
Return the stream object of what? We already have low level methods, check
out OpenRead et al
