### ISSUE TITLE
FtpRemoteExists resume mode does not work correctly.

### ISSUE THREAD

**Issue by VahidAssadi** [robinrodricks/FluentFTP#866]
Hi
I'm using FluentFtp version (37.0.2) in my project. Currently I'm using UploadDirectory method for uploading and syncing local folders with server but I have an issue when I use FtpRemoteExists  in resume mode for uploadimg modified files for examples a docx or xlsx file, actually it doesnt work properly and I have to use overwrite mode temporary for this issue.
I would be grateful if you could help me

**Comment by robinrodricks** [comment]
Can you provide more details? Also attach the logs and pinpoint where it is going wrong for you. Such a generic question, we cannot help you with.
