### ISSUE TITLE
Make IAsyncEnumerable API available in UWP application 

### ISSUE THREAD

**Issue by zhuxb711** [robinrodricks/FluentFTP#868]
Condition: "ASYNCPLUS" is invalid if platform is UWP which leads IAsyncEnumerable API was disabled in UWP application.
UWP is actually support IAsyncEnumerable but its "TargetPlatform" is not netstandard2.0/netstandard2.1/net50

**Comment by robinrodricks** [comment]
It was causing issues for some people so it was disabled by default. If you want it, you have to enable it in the code and compile from source.

**Comment by zhuxb711** [comment]
Got it, thanks
