### ISSUE TITLE
ConnectTimeout not working for ConnectAsync

### ISSUE THREAD

**Issue by RichardVerzijl** [robinrodricks/FluentFTP#869]
**FTP OS:** Windows

**Computer OS:** Windows 10 21H2

**FluentFTP Version:** 37.0.0

Target framework: .NET Framework 4.7.2

When calling ConnectAsync() and the host doesn't exist it takes 21 seconds before there is a timeout.
Below is the code I use.
 ```
using (var conn = new FtpClient())
{
    conn.Host = "192.168.0.14";
    conn.Credentials = new NetworkCredential("ftptest", "ftptest");
    conn.ConnectTimeout = 5000;
    await conn.ConnectAsync();
}
```
When calling Connect() the timeout works fine.

**Logs :**

```

# ConnectAsync()
# ConnectAsync()
Status:   Connecting to 192.168.0.14:21
Status:   Connecting to 192.168.0.14:21
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll


# Dispose()
# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...

```

**Comment by robinrodricks** [comment]
Thanks for reporting this.

**Comment by Wufus** [comment]
**FTP OS:** Windows 10 21H2

**FluentFTP Version:** 32.4.4

**Target framework:** .Net Core 2.x (UWP)
```
FtpClient ftp = new FtpClient("ftp://" + ip + "/");
ftp.Credentials = new NetworkCredential(Login, Password);
ftp.DataConnectionType = FtpDataConnectionType.PASVEX;
ftp.ConnectTimeout = 2500;
await ftp.ConnectAsync();
```
I measured that it takes ~20 seconds to time out.

**Comment by robinrodricks** [comment]
Can you try this @Wufus.

[Release.zip](https://github.com/robinrodricks/FluentFTP/files/9226421/Release.zip)

[I added tests](https://github.com/robinrodricks/FluentFTP/commit/a1ce2c470901b3458b8944737569e9ab8d2cdd53) and it worked for me. If you want you can try the same tests and see, its under `ConnectionTests > ConnectTimeoutAsync`.

**Comment by robinrodricks** [comment]
Released.
https://www.nuget.org/packages/FluentFTP/39.0.1

I'm closing this ticket as my unit tests are passing.

If you still have this issue, make a new ticket.
