### ISSUE TITLE
Error while connecting to SOCKS Proxy

### ISSUE THREAD

**Issue by fire-lizard** [robinrodricks/FluentFTP#877]
**FTP OS:** Windows

**FTP Server:** Globalscape EFT

**Computer OS:** Windows

**FluentFTP Version:** 37.0.5

When I try to connect to SOCKS Proxy as described here: https://github.com/robinrodricks/FluentFTP/wiki/FTPS-Proxies
I getting the following error:
SocksProxyException: Invalid Auth Type Declared, see inner exception for details. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values

**Logs :**

```

# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...

# Connect()
Status:   Connecting to ***:1080
Status:   Disposing FtpSocketStream...


```

**Comment by robinrodricks** [comment]
Add detailed logs please

**Comment by fire-lizard** [comment]
Thank you for your reply
I have found out that I am trying to connect to SOCKS**4** proxy which is not supported in your library. To help you with development, I have created 4 classes: FtpClientSocks4Proxy, FtpClientSocks4aProxy, Socks4Proxy, Socks4aProxy (for SOCKS4 and SOCKS4a proxy servers) but it seems I cannot push to make a branch in your repo.
If you interested, I can send those 4 small files to you so you can improve your library.

**Comment by robinrodricks** [comment]
Yes @fire-lizard , please send those files to me. You cannot push to a branch in my repo, but you can fork this and push it into your own copy of it. Please click the "FORK" button on the top-right of this page, then you will get a copy of FluentFTP repo, then you can push the changes there. Looking forward to it!

**Comment by robinrodricks** [comment]
Thank you very much!

**Comment by fire-lizard** [comment]
Library now connects to FTP through SOCKS4 / SOCKS4a proxy servers. Closing the issue.

**Comment by robinrodricks** [comment]
Awesome!
