### ISSUE TITLE
How to get the FTP Server Error Codes when an exception occured?

### ISSUE THREAD

**Issue by bodoDeeWhy** [robinrodricks/FluentFTP#878]
When invoking FTPClient.Connect I want to get the FTP server error code. For example with bad Credentials for the connection. But I cant see any property that will return the server error code or any exception  that will signal a credential error.

**FTP OS:** Unix / Windows / Embedded

**FTP Server:** Pure-FTPd / DrFTPD / Vsftpd / ProFTPD / Vax / VMS / OpenVMS / Tandem / HP NonStop Guardian / IBM OS400 / AS400 / Windows CE

**Computer OS:** ?

**FluentFTP Version:** ?

<write details about your bug report / feature request here>

**Logs :**

```

<paste logs here>

```

**Comment by robinrodricks** [comment]
Please add logs so we can see what is going on.

**Comment by bodoDeeWhy** [comment]
I have basically worked it out. I need to cast exceptions to SocketException and FTPCommandException as per the code below.
I cant get the server code explicitly.
 Try
                    .Connect()
                    _FTPClient = oFTPClient
                    RaiseEvent Ev_FTP_HostConnected(myURI.Host)
                Catch ex As Exception
                    Select Case ex.GetType.Name
                        Case "SocketException"
                            Dim myEx As System.Net.Sockets.SocketException = CType(ex, System.Net.Sockets.SocketException)
                            If myEx.ErrorCode = 11001 Then
                                errMessage = "Failed To connect - host not found! "
                                RaiseEvent Ev_FTP_HostNotFound(errMessage)
                                Throw New FTP_HostNotFound_Exception(errMessage)
                            Else
                                errMessage = "Failed to connect! ErrorCode = " & myEx.ErrorCode.ToString & " " & ex.Message
                                RaiseEvent Ev_FTP_HostNotConnected(errMessage)
                                Throw New FTP_HostNotConnected_Exception(errMessage)
                            End If
                        Case "FtpCommandException"
                            Dim myEx As FtpCommandException = CType(ex, FtpCommandException)
                            If myEx.CompletionCode = "530" Then
                                errMessage = "Failed To connect! User's credentials bad! "
                                RaiseEvent Ev_FTP_BadHostCredentials(errMessage)
                                Throw New FTP_BadHostCredentials_Exception(errMessage)
                            Else
                                errMessage = "Failed to connect! CompletionCode = " & myEx.CompletionCode.ToString & " " & ex.Message
                                RaiseEvent Ev_FTP_HostNotConnected(errMessage)
                                Throw New FTP_HostNotConnected_Exception(errMessage)
                            End If
                        Case Else
                    End Select

**Comment by robinrodricks** [comment]
Please close this ticket if it is resolved.

As you said you can fetch `FtpCommandException.CompletionCode` to get the server error code.
