### ISSUE TITLE
Cannot connect to Azure FTP

### ISSUE THREAD

**Issue by PeteJobi** [robinrodricks/FluentFTP#880]
**FTP OS:** Windows

**FTP Server:** Can't say

**Computer OS:** Windows 11

**FluentFTP Version:** 37.0.5

I am not able to connect to Azure FTP using FluentFTP. Below is my code.
```
FtpClient client = new("waws-prod-my-ftp.ftp.azurewebsites.windows.net", "username", "password");
await client.AutoConnectAsync();
```

I get the below error:
```
System.ArgumentException: Required parameter is null or blank. (Parameter 'profile.Host')
   at FluentFTP.FtpClient.LoadProfile(FtpProfile profile)
   at FluentFTP.FtpClient.AutoConnectAsync(CancellationToken token)
```

Digging through the source code led me to this snippet:
```
//
// Summary:
//     Return a known working connection profile from the host/port combination.
public static FtpProfile GetWorkingProfileFromHost(string Host, int Port)
{
    if (Host.IndexOf("ftp.azurewebsites.windows.net", StringComparison.OrdinalIgnoreCase) > -1)
    {
        return new FtpProfile
        {
            Protocols = SslProtocols.Tls,
            DataConnection = FtpDataConnectionType.PASV,
            RetryAttempts = 5,
            SocketPollInterval = 1000,
            Timeout = 2000
        };
    }

    return null;
}
```
.....which in turn led me to #533. So I tried the below:
```
FtpClient client = new("waws-prod-my-ftp.ftp.azurewebsites.windows.net", "username", "password");
client.SslProtocols = System.Security.Authentication.SslProtocols.Tls;
client.ValidateAnyCertificate = true;
client.DataConnectionType = FtpDataConnectionType.PASV;
client.DownloadDataType = FtpDataType.Binary;
client.RetryAttempts = 5;
client.SocketPollInterval = 1000;
client.ConnectTimeout = 2000;
client.ReadTimeout = 2000;
client.DataConnectionConnectTimeout = 2000;
client.DataConnectionReadTimeout = 2000;
await client.ConnectAsync();
```
...but I get a different error:
```
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at FluentFTP.FtpSocketStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token)
   at FluentFTP.FtpSocketStream.ReadLineAsync(Encoding encoding, CancellationToken token)
   at FluentFTP.FtpClient.GetReplyAsync(CancellationToken token)
   at FluentFTP.FtpClient.ExecuteAsync(String command, CancellationToken token)
   at FluentFTP.FtpClient.AuthenticateAsync(String userName, String password, String account, CancellationToken token)
   at FluentFTP.FtpClient.AuthenticateAsync(CancellationToken token)
   at FluentFTP.FtpClient.ConnectAsync(CancellationToken token)
```

**Logs :**

```

# ConnectAsync()
Status:   Connecting to ***:21
Response: 220 Microsoft FTP Service
Status:   Detected FTP server: WindowsServerIIS
Command:  USER ***
Response: 331 Password required
Command:  PASS ***

```
Logs seems to be saying password isn't present, but I'm definitely putting the password in the constructor.

Any ideas?

**Comment by hermanussen** [comment]
I'm running into the same issue. But, weirdly, it appears to be working for one connection and not the other (all Azure FTP connections).

I've double-checked the connection settings and credentials and also verified that it works with a GUI ftp client.

Could this be an encoding issue with the connection settings or maybe a differently configured Azure FTP endpoint?

I tested with these versions and got the same result: 37.0.4, 37.0.5 and 39.0.1.

To (attempt to) reproduce, save the following as a file called `test.csx`, change the values marked with < > and run `dotnet script ./test.csx`.
```csharp
#r "nuget: FluentFTP, 39.0.1"

using FluentFTP;
using System.IO;

FtpClient client = new FtpClient(
	new Uri("ftps://<something>.ftp.azurewebsites.windows.net:21"),
	new System.Net.NetworkCredential(
		"<username>",
		"<pasword>")
	);

// The following results in "System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host"
await client.ConnectAsync();

System.Console.WriteLine("This point is not reached, because the error occurs before...");
```

**Comment by robinrodricks** [comment]
@hermanussen Check out https://github.com/robinrodricks/FluentFTP/issues/901

**Comment by hermanussen** [comment]
@robinrodricks 
Not sure if that's applicable, because:
- I'm using AutoConnectAsync, but ConnectAsync (unsure about the actual difference)
- It says it's a regression from 39.0.1, but I also tested with much earlier versions (as mentioned above)

Anyway, I'll try and see if I can get it to work with the [FluentFTP.39.1.0-BETA1.zip](https://github.com/robinrodricks/FluentFTP/files/9265848/FluentFTP.39.1.0-BETA1.zip) version as mentioned there. I'm struggling a bit with getting that to work in my csx script without nuget.

**Comment by IGx89** [comment]
@PeteJobi: Per debugging in #901, I'm fairly certain AutoConnectAsync has been broken for Azure. If you use 39.1.0-BETA1 above (or wait for a non-beta release), there's a good chance it'll fix your issue.

@hermanussen: if you use both 39.1.0-BETA1 and AutoConnectAsync, that likely will fix your issue too.

If you want to use Connect instead, the following should work in any version:
```
await ftpClient.ConnectAsync(new FtpProfile
{
    Host = ftpHost,
    Credentials = new System.Net.NetworkCredential(ftpUser, ftpPassword),
    Encryption = FtpEncryptionMode.Implicit,
    Encoding = System.Text.Encoding.UTF8,
    Protocols = SslProtocols.Tls12,
    DataConnection = FtpDataConnectionType.PASV,
    RetryAttempts = 5,
    SocketPollInterval = 1000,
    Timeout = 2000,
});
```
 If your app service was set to "FTPS Only" (in Configuration/General Settings), that makes Encryption = Implicit and Protocols = Tls12 both required.

**Comment by robinrodricks** [comment]
Please try the latest release `AutoConnect/Async` @hermanussen

**Comment by hermanussen** [comment]
> Please try the latest release `AutoConnect/Async` @hermanussen

I tried it. It solves the problem for me. Thanks!

**Comment by robinrodricks** [comment]
Amazing, thanks for the response @hermanussen !

**Comment by PeteJobi** [comment]
Works for me as well. Thanks for fixing, @robinrodricks. Thanks for your help, @hermanussen.

**Comment by robinrodricks** [comment]
Fantastic!
