### ISSUE TITLE
Upload File Async

### ISSUE THREAD

**Issue by Hoenscher** [robinrodricks/FluentFTP#882]
**FTP OS:** Android 11

**Computer OS:*Windows 10* ?

**FluentFTP Version:*37.0.5* ?

<   var test1 = await client.UploadFileAsync( pathAndFilename, "/test.bin", FtpRemoteExists.Overwrite, true, FtpVerify.None, null, cts.Token );

After all bytes are send the server don't send a responce. 
After I cancel the app the server sends
226 Successfully tranfered "/test.bin"

I think there is missing a close (Stream File ).
>

**Comment by robinrodricks** [comment]
Can you test with an older version of FluentFTP to see if this is a new issue?

**Comment by robinrodricks** [comment]
Also add the logs please.

**Comment by Hoenscher** [comment]
Ok. I tested this with Version 36.1.0
Everythink works fine.

**Comment by robinrodricks** [comment]
Hi, can you please check if this resolves your issue.
[Release.zip](https://github.com/robinrodricks/FluentFTP/files/9082611/Release.zip)

**Comment by Hoenscher** [comment]
The last Version that works fine is 37.0.2

Version 37.0.3 don't work

What i have done next is:
I copied all new files from you in the directorie 37.0.2/lib
The last Version which works and installed in my project.
Rebuild the hole project and test.
This also don't work.
Sorry.

**Comment by Hoenscher** [comment]
Logfile with new dll from you
[log_file.txt](https://github.com/robinrodricks/FluentFTP/files/9083139/log_file.txt)

**Comment by robinrodricks** [comment]
@Hoenscher  just check in the new `FtpClient` are you getting this property, `client.DisconnectWithShutdown`, then it means you have the latest version.

**Comment by robinrodricks** [comment]
Please try this?

[FluentFTP.37.0.6-BETA2.zip](https://github.com/robinrodricks/FluentFTP/files/9083182/FluentFTP.37.0.6-BETA2.zip)

**Comment by robinrodricks** [comment]
Thanks for reporting this high priority issue.

**Comment by robinrodricks** [comment]
Please use:

https://www.nuget.org/packages/FluentFTP/37.0.6

**Comment by Hoenscher** [comment]
my last log file
[log_file.txt](https://github.com/robinrodricks/FluentFTP/files/9083246/log_file.txt)
