### ISSUE TITLE
FTPS / TLS1.3 ConnectAsync hangs in .NET6

### ISSUE THREAD

**Issue by xfischer** [robinrodricks/FluentFTP#889]
**FTP OS:** Windows

**FTP Server:** Pure-FTPd

**Computer OS:** Win 10

**FluentFTP Version:** 37.1.0 / net6.0

Same issue as #682, connection hangs after receiving 234 reply. (TLS 1.3).
If I set `SslBuffering = FtpsBuffering.Off;` it works

**Logs :**

```

[Verbose] >         AutoConnectAsync()
[Verbose] >         AutoDetectAsync(True, False)
[Verbose] >         ConnectAsync()
[Info] Status:   Connecting to [redacted]:21
[Verbose] Response: 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response: 220-You are user number 1 of 50 allowed.
Response: 220-Local time is now 17:07. Server port: 21.
Response: 220-This is a private system - No anonymous login
Response: 220-IPv6 connections are also welcome on this server.
[Info] Response: 220 You will be disconnected after 15 minutes of inactivity.
[Info] Status:   Detected FTP server: PureFTPd
[Info] Command:  AUTH TLS
[Info] Response: 234 AUTH TLS OK.

[infinity is long, mostly at the end]

```

**Comment by xfischer** [comment]
And thanks for this library, the only one I'm confident using out there !

**Comment by robinrodricks** [comment]
You are very welcome!

It should have been disabled by default in NET 6, as it is disabled in NET 5. I will make a new release.

https://www.nuget.org/packages/FluentFTP/37.1.1

**Comment by xfischer** [comment]
Tested with 37.1.1 and now works OK. Thanks for the quick answer and the nuget release :)
