### ISSUE TITLE
FtpTrace.LogPrefix = true|false not in v37.1?

### ISSUE THREAD

**Issue by Mudoch** [robinrodricks/FluentFTP#891]
**FTP OS:** Windows

**FTP Server:** Filezilla

**Computer OS:** ?

**FluentFTP Version:** 37.1

Wanted to use the FtpTrace.LogPrefix, guessing it's been deprecated? Can you confirm?

**Comment by robinrodricks** [comment]
We don't have it for the .NET core builds, but we can add it. Do you need it?

**Comment by Mudoch** [comment]
Not yet work it out withoutSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Robin Rodricks ***@***.***> Date: 7/19/22  7:46 AM  (GMT-05:00) To: robinrodricks/FluentFTP ***@***.***> Cc: Mudoch ***@***.***>, Author ***@***.***> Subject: Re: [robinrodricks/FluentFTP] FtpTrace.LogPrefix = true|false not in v37.1? (Issue #891) 
We don't have it for the .NET core builds, but we can add it. Do you need it?
