### ISSUE TITLE
FtpTrace.LogToFile not working in .NET 6?

### ISSUE THREAD

**Issue by MikeYeager** [robinrodricks/FluentFTP#892]
**FTP OS:** Windows 11

**FTP Server:** Bitvise

**Computer OS:** Windows 11

**FluentFTP Version:** 37.1.0

      FtpTrace.LogToFile = "C:\\Temp\\RDNG-FTP.Log";
      FtpTrace.LogUserName = false;
      FtpTrace.LogPassword = false;
      FtpTrace.LogIP = true;

**Logs :**

Well, that's kind of the problem. No log file is produced whether I use a full path or just a file name. No errors are encountered. Any leads on how to troubleshoot this? The above code runs on startup, but no file is ever produced.

Thanks,
Mike
```

<n/a>

```

**Comment by robinrodricks** [comment]
It should, its enabled in NET 6. 

https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Helpers/FtpTrace.cs#L193

**Comment by robinrodricks** [comment]
`FtpTrace.EnableTracing` should be true. Apart from that its automatic really, it should work.

**Comment by robinrodricks** [comment]
First try `LogToConsole = true` and see if it works.

**Comment by MikeYeager** [comment]
Apparently, the project was using a combination of FluentFtp and SSH.NET to send files with SFTP. It appears that this is what caused the original issue and it's not too far a stretch to think it may have caused the logging issues as well. I'm going to go ahead and close this as removing the SSH.NET library seems to have fixed the original issue and it's no longer necessary to turn on tracing. Thank you and sorry for the run-around.

**Comment by robinrodricks** [comment]
No problem.
