### ISSUE TITLE
Download File always -1 on Progress

### ISSUE THREAD

**Issue by Maverick1983** [robinrodricks/FluentFTP#896]
**FTP OS:** Windows

**FTP Server:** https://github.com/drftpd-ng/drftpd

**Computer OS:** Windows 11

**FluentFTP Version:** 1.0.0.0

I can't DownloadFile. I always have -1 on progress. The server is FTPS TLS Explicit with PRET and PASV

**Logs :**

**Comment by robinrodricks** [comment]
I need the FTP logs to debug anything.
