### ISSUE TITLE
How do I upload from a stream?

### ISSUE THREAD

**Issue by DavidLindon** [robinrodricks/FluentFTP#899]
**FTP OS:** Windows

**FTP Server:** N/A

**Computer OS:** Win 10

**FluentFTP Version:** N/A

I would like to request the feature to upload straight from a MemoryStream as I am creating a file in memory, I would like to avoid having to write it to disk in order to upload

**Comment by robinrodricks** [comment]
UploadStream?

**Comment by robinrodricks** [comment]
Also its literally the first point given here - https://github.com/robinrodricks/FluentFTP/wiki/File-Transfer#api

**Comment by DavidLindon** [comment]
Hi Rob,

Thanks. Yes it wasn't obvious, the quick start (https://github.com/robinrodricks/FluentFTP/wiki/Quick-Start-Example) appears to show all the methods available but nothing referring to a stream. Also UploadStream is not on the methods wiki - https://github.com/robinrodricks/FluentFTP/wiki/Methods . Adding it to the list of available method should make it much easier to find. Keep up the good work!

**Comment by robinrodricks** [comment]
Thanks @DavidLindon , I'll update the docs.

**Comment by robinrodricks** [comment]
Updated https://github.com/robinrodricks/FluentFTP/wiki/Methods
