### ISSUE TITLE
Cancel transfer

### ISSUE THREAD

**Issue by tobiasps** [robinrodricks/FluentFTP#90]
It would be great to include the ability to cancel a transfer. This could be implemented as a event that is triggered by client.Cancel();

In FtpClient class:
```
public event Action CancelEvent;

public void Cancel()
{
	CancelEvent?.Invoke();
}
```

And then in UploadFile/DownloadFile:
```
bool cancel = false;

CancelEvent += () => { 
	cancel = true; 
};
```

And breaking the while loops if cancel is true and return !cancel. 
I'll be happy to branch and implement this if you like the idea.

**Comment by hgupta9** [comment]
Sure, its a good idea. Feel free to fork and add your improvements. Ideally submit one change per PR so we can discuss each feature separately.

**Comment by jblacker** [comment]
@tobiasps I started implementing use of cancellation when running async using `CancellationToken`s.  It's currently is available within `UpdateFile()`, `UploadFiles()`, `DownloadFile()`, `DownloadFiles()`

**Comment by hgupta9** [comment]
@jblacker Great to hear that. Can't wait.

**Comment by hgupta9** [comment]
@jblacker Can you re-fork my version since I've just made significant changes to FtpClient and the async methods as well.

**Comment by LordMike** [comment]
Quick comment: Usually in .NET we use `CancellationTokens` for cancelling stuff. So you would have overloads for each (a)sync method that can be cancelled, with a parameter for a `CancellationToken` (defaulting to `CancellationToken.None`)

**Comment by jblacker** [comment]
Sorry I've dropped the ball on this.  I've changed jobs and been insanely busy recently.  Since this is still open I'd be happy to update my fork and see how it can be merged back into the current code base.  Expect a PR by next week hopefully.

**Comment by robinrodricks** [comment]
Great that you're back! Excited for the PR....

**Comment by jblacker** [comment]
Wait I just saw a few commits that implement this already.  I haven't gone through everything yet, but is this still actually open?

**Comment by robinrodricks** [comment]
Yes cancellation is implemented for some methods. You will see a
cancellation token for the ones that do, I think.

**Comment by robinrodricks** [comment]
We now support `CancellationToken` on all async methods since v23! It works on .NET fx and .NET core.
