### ISSUE TITLE
Inconsistent implementations of GetListing for z/OS

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#909]
Hi @FanDjango, 

I noticed this difference in behavior. Please tell me which one is correct.

A: GetListing
```
			// Only disable the GetAbsolutePath(path) if z/OS
			// Note: "TEST.TST" is a "path" that does not start with a slash
			// This could be a unix file on z/OS OR a classic CWD relative dataset
			// Both of these work with the z/OS FTP server LIST command
			if (ServerType != FtpServer.IBMzOSFTP || path == null || path.StartsWith("/"))
			{
				// calc the absolute filepath
				path = GetAbsolutePath(path);
			}
```
B: GetListingAsync
```
			// calc path to request
			path = await GetAbsolutePathAsync(path, token);
```

**Comment by FanDjango** [comment]
>Topic 6
>Problem: We have [2 implementations of each function], This causes bloat, **mistakes/mismatches** in the implementation, and weird behavior.

Yep, you found one and it is **my** mistake/mismatch**. Sorry about that.

Version "**A**" is the right one. I simply _forgot_ to duplicate the code for async.

I suppose you would like to have a PR?

**Comment by robinrodricks** [comment]
No worries I'll do it now.

**Comment by robinrodricks** [comment]
Released

https://www.nuget.org/packages/FluentFTP/39.2.1

**Comment by FanDjango** [comment]
Nice change (moving the server specific logic), I like it. I have tested it (sync) and confirm still works.

**Comment by robinrodricks** [comment]
Fantastic, thanks for testing it!
