### ISSUE TITLE
Progress for uploads/downloads

### ISSUE THREAD

**Issue by tobiasps** [robinrodricks/FluentFTP#91]
I think it it would be great to implement a way to get progress of a transfer or maybe just include an example of how to do this.

In my project I'm using a stream wrapper class (https://gist.github.com/robinrodricks/979c8db5c93a236da34e9fc2507699dd) that emits events on read/write/seek on the stream.

Uploading then becomes this:
```
FileStream fs = fileInf.OpenRead();
ProgressStream pStream = new ProgressStream(fs);

pStream.BytesRead += (sender, args) => { 
	// logic for updating progress bar using args.StreamPosition and args.StreamLength
};

transferResult = client.UploadFile(pStream, remoteFileName);
```

**Comment by hgupta9** [comment]
Sure, its a good idea. Can you fork and add this system into UploadFileInternal / DownloadFileInternal?

**Comment by jblacker** [comment]
What do you think about passing `IProgress<T>` objects?  The callback in them uses a captured context so you can safely use them in UIs.

**Comment by pbindy** [comment]
Would be great to have this feature

**Comment by hgupta9** [comment]
@jblacker Never heard of those. Could you share more details of the implementation?

**Comment by jblacker** [comment]
@hgupta9 Sure!  It's actually part of the .NET Framework's standard library (including .NET Core/Standard) starting in version 4.5 and both the interface and implementation are part of the main `System` namespace.

The beautiful part of the `Progress<T>` class is that if you set the callback it uses in the constructor it uses the [`SynchronizationContext`](https://msdn.microsoft.com/magazine/gg598924.aspx) of where it was built for where the callback runs meaning it's safe to use on UI threads.

.NET Framework (4.5+)
Interface:  [`IProgress<T>`](https://msdn.microsoft.com/en-us/library/hh138298(v=vs.110).aspx)
Concrete: [`Progress<T>`](https://msdn.microsoft.com/en-us/library/hh193692(v=vs.110).aspx)

.NET Framework (Core/Standard)
Interface:  [`IProgress<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.iprogress-1?view=netstandard-2.0)
Concrete: [`Progress<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.progress-1?view=netstandard-2.0)

Here's some information about how to use it:

- .NET Blog: [Async in 4.5: Enabling Progress & Cancellation in Async APIs](https://blogs.msdn.microsoft.com/dotnet/2012/06/06/async-in-4-5-enabling-progress-and-cancellation-in-async-apis/)
- Stephen Clery's Blog:  [Reporting Progress From Async Tasks](https://blog.stephencleary.com/2012/02/reporting-progress-from-async-tasks.html)

**Comment by hgupta9** [comment]
Sounds cool. Are you going to do it or do you want me to try? I must mention I'm totally out of depth. If you want me to do it you could share like the minimal code sample that I need to use and I'll insert that everywhere.

**Comment by hgupta9** [comment]
I understood how it works. Working on it.

**Comment by jblacker** [comment]
@hgupta9  Awesome.  Let me know if you need any assistance with it.

**Comment by wernerbarnard** [comment]
Is there an ETA for this enhancement?  Would be amazing!

**Comment by longlostbro** [comment]
whats the status on this feature?

**Comment by tarockx** [comment]
Any news on this, or workarounds to implement it?

I was trying to use the suggestion in the first post, but I don't exactly know how to implement the "ProgressStream" and the link in the OP is dead. Any hints?

**Comment by robinrodricks** [comment]
@tarockx You can get ProgressStream at this link : https://gist.github.com/robinrodricks/979c8db5c93a236da34e9fc2507699dd

I got it from the OP's link at the internet archive (archive.org).

**Comment by robinrodricks** [comment]
Implemented progress tracking via IProgress for Upload/Download/UploadFile/DownloadFile.
The callback will be called with a number from 0 to 100, based on the percentage of completion.

Please grab it at : https://www.nuget.org/packages/FluentFTP/19.1.0

**Comment by robinrodricks** [comment]
Closing this issue since initial implementation has been done. Open a new issue if there are problems with progress tracking.

**Comment by gbanana** [comment]
I cannot get the progress callback when the file uploading, after uploaded I got list of progress.

**Comment by gbanana** [comment]
![image](https://user-images.githubusercontent.com/577581/66448998-17f59b00-ea86-11e9-8841-03d1048da299.png)

**Comment by gbanana** [comment]
I cannot get the progress callback while the file uploading, after uploaded I got list of progress.

![image](https://user-images.githubusercontent.com/577581/66457051-facec580-eaa1-11e9-9ecf-d6a0908cab9a.png)
![image](https://user-images.githubusercontent.com/577581/66457124-294ca080-eaa2-11e9-9df3-ea8cf6f361c1.png)

**Comment by robinrodricks** [comment]
@gbanana This has been fixed.
