### ISSUE TITLE
Add property in FtpClient class to retrieve the selected SslProtocol

### ISSUE THREAD

**Issue by JosHuybrighs** [robinrodricks/FluentFTP#916]
**FTP OS:** All

**FTP Server:** All

**Computer OS:** All

**FluentFTP Version:** Future release

**Framework:** All

Could it be possible for one of the next updates of FluentFTP to have the possibility to retrieve the selected/negotiated Ssl/Tls version?

I did it myself by adding the FluentFtp source code project to my solution. It is quite easy. The following files need to be expanded with a simple property:

In `FtpClientProperties.cs`
```
/// <summary>
/// The negotiated SSL/TLS version
/// </summary>
public SslProtocols SelectedSslProtocol
{
	get { return m_stream != null ? m_stream.SelectedSslProtocol : SslProtocols.None; }
}

```

In `FtpSocketStream.cs`
```
/// <summary>
/// The negotiated SSL/TLS version
/// </summary>
public SslProtocols SelectedSslProtocol
{
	get { return IsEncrypted ? m_sslStream.SslProtocol : SslProtocols.None; }
}

```

I would like to have this to inform the user about which protocol has been negotiated.

**Comment by FanDjango** [comment]
I would also use this.

**Comment by robinrodricks** [comment]
Good idea!

**Comment by robinrodricks** [comment]
#### 39.4.0
 - New: Add `SslProtocolActive` property to retrieve the negotiated SSL/TLS protocol version

**Comment by FanDjango** [comment]
@marcwaz You are right. It disappeared by mistake after df7ac2c.

**Comment by FanDjango** [comment]
I have no explanation as to why it was removed. I have brought it back and committed this to the current master. It will be back in the next release.

**Comment by marcwaz** [comment]
good. it should be tested, to ensure that it works.

**Comment by marcwaz** [comment]
Could you just send me a sample of code in order to show me how to do a call of SslProtoclActive property after a ".connect" on a new FtpClient ?

**Comment by FanDjango** [comment]
'''cs
				client.Connect();
				Console.WriteLine("Selected SSL Version/Protocol " + client.SslProtocolActive);
```

Result:

```
Selected SSL Version/Protocol Tls12
```

using the current _master_ on GitHub.

**Comment by FanDjango** [comment]
Actually more even:
```cs
				client.Connect();
				Console.WriteLine("Selected SSL Version/Protocol " + client.SslProtocolActive);
				Console.WriteLine("Selected SSL Ciphersuite " + client.SslCipherSuiteActive);
```
Result:
```
Selected SSL Version/Protocol Tls12
Selected SSL Ciphersuite Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, 44550, 255)
```

**Comment by marcwaz** [comment]
I don't know when the next version of FluentFTP (v52.1?) will be released. 

Is it possible to push a beta nuget ? 

I need the FluentFTP .net472 framework dll (compile in release mode) in order to do the tests. 

I don't have the necessary environnement in order to compile the master FluentFTP sources.
 
thanks

**Comment by FanDjango** [comment]
Making a new (interim) release is solely at @robinrodricks discretion.
