### ISSUE TITLE
Use transfer compression (ZLIB) to improve speeds

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#93]
The MODE Z command allows for ZLIB transfer compression of file listings and upload/download. Use this to reduce the data transfered and increase the speed of transfer. This command has been already adopted by many popular FTP servers.

Resulting savings due to the compression:

- Text files : ~15-20% of original size
- HTML files : ~25-30% of original size
- Audio/video : ~90-95% of original size

**Comment by jblacker** [comment]
I think it would be awesome if we used this default upon detecting the feature is available.

**Comment by nvivo** [comment]
Was looking for this. Any idea when it will come out?

**Comment by hgupta9** [comment]
@nvivo Why do you need this?

**Comment by nvivo** [comment]
I use this lib as part of a deployment tool, and I frequently need to send new files to dozens of servers over the internet. The average compression for my files on fastest zip compression is around 37% of the original size, so  it would help me make these deploys faster.

**Comment by robinrodricks** [comment]
Added to the [bucket list](https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans). We will pick this up as and when we have free time. Comment on this issue if you want us to prioritize it. Thanks!
