### ISSUE TITLE
UploadFile fails, but I would like to know the reason (or error code)

### ISSUE THREAD

**Issue by gregor-tusar-sowa** [robinrodricks/FluentFTP#934]
**FTP OS:** Ubuntu - Docker

**FTP Server:** unknown

**Computer OS:** Ubuntu

**FluentFTP Version:** 39.1.0

**Framework:** .NET 6

I try to upload a file to a remote FTP server. The upload sometimes succeeds sometimes fails. I get a `FtpStatus.Failed` result from `UploadFile` method. I would like to know the reason why the upload failed. How to get the reason of the failure?

Method call: 
`var status = s_client.UploadFile(file.FullName, $"{s_dstFolder}/{file.Name}", FtpRemoteExists.Overwrite, true, FtpVerify.Retry);`

This is done in a cron job that runs in three docker containers at roughly the same time each day with the same credentials to a single FTP server, using just a different folder. This might be the reason, but I would like to know the exact reason.

**Comment by FanDjango** [comment]
Are you catching the log messages somewhere?

**Comment by gregor-tusar-sowa** [comment]
I now added OnLogEvent method to log the messages and will come back with results soon. Thanks.

**Comment by gregor-tusar-sowa** [comment]
Unfortunatelly also this additional logging does not help too much...
These are the messages that are written by `OnLogEvent` method.
<img width="655" alt="image" src="https://user-images.githubusercontent.com/80673797/187366131-455494d0-9342-4072-8a3f-94baa87e4a01.png">

**Comment by gregor-tusar-sowa** [comment]
I now added 30s timeout to all possible timeouts and I will see.
```
ConnectTimeout
DataConnectionConnectTimeout
DataConnectionReadTimeout
ReadTimeout
```
Why does it not throw timeout exception? Would `FtpVerify.Throw` throw an exception in that case or not?

```
var status = s_client.UploadFile(file.FullName, $"{s_dstFolder}/{file.Name}", FtpRemoteExists.Overwrite, true, FtpVerify.Retry | FtpVerify.Throw);
```

**Comment by gregor-tusar-sowa** [comment]
I forgot to disconnect client after the uploads. 
I'm sorry to bother you.

**Comment by FanDjango** [comment]
> I forgot to disconnect the client after the uploads. 

That may be the case. But with the right logging  you would be pointed to that reason directly.
