### ISSUE TITLE
Documentation Bug - broken "just one" link, for external dependencies

### ISSUE THREAD

**Issue by PracticalCode** [robinrodricks/FluentFTP#942]
On your project home page:   https://github.com/robinrodricks/FluentFTP

You have the following sentence:

- It is written entirely in C#, with [just one](https://github.com/robinrodricks/FluentFTP/blob/master/Microsoft.Extensions.Logging.Abstractions) external dependencies.

... containing the link:

- https://github.com/robinrodricks/FluentFTP/blob/master/Microsoft.Extensions.Logging.Abstractions

... which is broken:

- The 'robinrodricks/FluentFTP' repository doesn't contain the 'Microsoft.Extensions.Logging.Abstractions' path in 'master'.

... my guess is you still have the dependency, but have a doc dynamic link that somehow did build properly?

**Comment by robinrodricks** [comment]
Thanks, fixed.
