### ISSUE TITLE
GetListing() returns items from server root "/" ??

### ISSUE THREAD

**Issue by merlepittman** [robinrodricks/FluentFTP#943]
This may not be a FluentFTP issue, but an issue I am having and I'm not sure where else to get help.

I'm connecting to a ftp server, and I know that it is setting my assigned ftp directory on the server as the root ftp directory (/ftp_files).  
GetWorkingDirectory() returns "/" which is the "/ftp_files" directory on the server.
I can verify this by setting the working directory to a subdirectory of "/ftp_files" and it does work. 

The issue is GetListing() or GetNameListing() will return all the directories from the root directory of the server and not the assigned root directory for the ftp server (/ftp_files)?

When I connect to my ftp server with other clients (such as Filezila) it works as expected and lists the subdirectories and files under "/ftp_files" as the root ftp directory.

I know that a properly secured FTP server this shouldn't be possible, but this is just an ftp server running on an embedded system for data offload and no security concerns so it is wide open.

What am I missing here?

**Comment by FanDjango** [comment]
Can you get a verbose log of the GetWorkingDirectory and the subsequent GetListing?

Can you try to do "the same sequence" of real commands manually with a command line FTP client going to that server?

Need more info/input

**Comment by merlepittman** [comment]
Sorry, not really sure how to do that.  Will look into it.  
Like I said, I'm running a limited FTPD on uclinux so capabilities are limited.  Even attempting to download a file I get an error?  However, it works with Filezilla and my same app works on other FTP servers??

**Comment by FanDjango** [comment]
> Even attempting to download a file I get an error?

Interesting. Normally I would ask "What error?" Is the effort to describe the error in any way possible too much to ask?

You have not provided any information: No version of FluentFTP, no log of FluentFTP connect and getlisting, no trace.

The only statement that I see, is "it works with FileZilla". You could also provide the FileZilla log of the case where it works, as a comparison.

**Comment by merlepittman** [comment]
Hello,

I have a text file attached which is the verbose log output to console by FluentFTP.  You can see initially where it lists the directories off the root(/) when they should be listing items only in the /sdcard directory.  This works properly in Filezilla as I mentioned.

Further down you can also see where I tried uploading a file and it fails with a 553 code?  Again this works just fine with FileZilla.  And my app can do this just fine with other FTP servers so I'm not quite sure what the issue is??

I have Fluent set to ASCII uploads/downloads, Passive mode, no encryption, etc.

ftpLocal.Config.UploadDataType = FtpDataType.ASCII;
ftpLocal.Config.DataConnectionEncryption = false;
ftpLocal.Config.DataConnectionType = FtpDataConnectionType.AutoPassive;
ftpLocal.Config.DownloadDataType = FtpDataType.ASCII;
ftpLocal.Config.EncryptionMode = FtpEncryptionMode.None;
ftpLocal.Config.LogToConsole = true;

Since my app works with other servers, there is obviously something strange with the FTP server config/operation.  I'm using anonymous login with both my app and FileZilla but only FileZilla works?

[FluentLog.txt](https://github.com/robinrodricks/FluentFTP/files/9537924/FluentLog.txt)

Thanks.

**Comment by FanDjango** [comment]
Thanks, I am looking at it

**Comment by FanDjango** [comment]
Ok, so FluentFTP is using the LIST command. You can use FileZilla and in the settings activate logging to a file. Restart FileZilla and do the same. Please post here...

**Comment by FanDjango** [comment]
I suppose you are logging into this server as root? Not a problem, just want to know.

**Comment by FanDjango** [comment]
You spoke of `/ftp_files` and now we are working with `/sdcard`?

**Comment by merlepittman** [comment]
Yes.  I've tried using root, anonymous and just black user.

**Comment by merlepittman** [comment]
Sorry, that was typo from another system.  /sdcard is the directory the ftp
server is configured to use.

**Comment by merlepittman** [comment]
I mean blank user.

**Comment by FanDjango** [comment]
Ok, so it's really interesting to see the difference to FileZilla. It's easy to turn on the logging in the settings, so go for it and we can analyze.

**Comment by merlepittman** [comment]
I've done more testing which has shed a little light on what's happening, but it seems quite bizarre to me.  It appears that the reason my uploads and downloads are failing is because the path I'm using is wrong?

When I login with FileZilla, it returns the root FTP directory "/" as the subdirectories of "/sdcard" which is correct.  So upon connecting, when FileZilla does a PWD it returns "/" and when it does a LIST of "/" it gets back the subdirectories of "/sdcard" which are "cfg", "data" and "logs".  This is the expected behavior.  However, when my app connects, and does a PWD it get "/" back from the ftp server, but when it does a LIST of "/" it gets the subdirectories from the root directory of the physical server (ie. "bin", "dev", "etc", "sbin",.....)??  So when I drill down through subdirectories of /sdcard, it was becoming part of the file path.  So if I tried to upload a file to the "data" directory for example, the path being used was "/sdcard/data/new_file.txt" and this was failing, because it is not recognized since the the path should be just "/data/new_file.txt".  This was causing the failure.  So if I remove "/sdcard" from the beginning of the path, uploads work just fine.

So in one instance (doing a LIST), it uses "/" as he root of the physical server, but when doing a file operation, using "/" is the FTP server root or the "/sdcard" directory of the physical server?  What am I missing here?

**Comment by FanDjango** [comment]
Lemme catch up with you. Studying this too right now...

**Comment by FanDjango** [comment]
I have some theories and things for you to check:

1.
FileZilla does a `LIST`. your APP does a `LIST /` in all cases where it needs to list the files.

That's the difference.

I believe this little server honors the path on a LIST command, although **it shouldn't**.

So if you want to do a listing, you should do the following:

```
client.GetListing("", FtpListOption.NoPath)
```

**Comment by FanDjango** [comment]
2. Sadly, an Upload will want to do a listing of its own in normal cases, which causes the same problem again, as that list command will once again include a path.

If you set `FtpRemoteExists.NoCheck` on the upload call, no such list command will be issued. Check if that helps for uploads, please.

**Comment by merlepittman** [comment]
ok great.   I did notice the difference between the initial LIST commands
but didn't know it would make a difference.

So when I try your suggestion, it does work and my initial LIST does return
the contents of the /sdcard as the FTP server root as it should.  However,
when I try to list any subdirectory, I still need to prefix the path with
"/sdcard" or the server says the directory doesn't exist?  For instance,
after the initial LIST or root, it returns the FTP subdirectories "cfg",
"data" and "logs".  However, if I try to do a LIST on one of these
subdirectories, ie.  "LIST /cfg" it says the directory does not exist.  I
have to prefix it with "/sdcard/ (ie.  "LIST /sdcard/cfg") to get it to
work?

Do I need to set the working directory each time I try to access a
subdirectory or something?

**Comment by FanDjango** [comment]
Yes, you need to `SetWorkingDirectory` to navigate the tree

**Comment by merlepittman** [comment]
OK thanks very much.  I'll give that a try.

**Comment by robinrodricks** [comment]
> For me it is interesting to see that this sort of manual navigation technique is safer when considering broken servers.

Always. We need to auto SetWorkingDirectory internally, an item that came up with the v40 proposal. In fact its what FileZilla does _by default_. We should do the same imo.

**Comment by FanDjango** [comment]
See Wiki [path problems](https://github.com/robinrodricks/FluentFTP/wiki/Troubleshooting#trouble_paths)
