### ISSUE TITLE
40.0.0 - error

### ISSUE THREAD

**Issue by mrdude2478** [robinrodricks/FluentFTP#945]
In visual studio 2022 in the nuget package 40.0.0, I am getting this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'FtpClient' does not contain a definition for 'ConnectTimeout' and no accessible extension method 'ConnectTimeout' accepting a first argument of type 'FtpClient' could be found (are you missing a using directive or an assembly reference?)	IPS_Patch_Creator	C:\Users\MrDude\source\repos\IPS-Patch-Creator\IPS_Patch_Creator\Main.cs	6113	N/A

If I downgrade back to 39.4.0, eveything is working again with no build errors. Did you do something to affect "ConnectTimeout"?

**Comment by FanDjango** [comment]
API changed for V40

Use `Config.ConnectTimeout`

**Comment by robinrodricks** [comment]
Thanks @FanDjango  for replying.

**Comment by robinrodricks** [comment]
@mrdude2478  it is mentioned in the nuget description to look at that guide. Also we have mentioned ALL the changes in the nuget description.

https://www.nuget.org/packages/FluentFTP

**Comment by mrdude2478** [comment]
Thanks for the replies. I'll have a look at all the changes.
