### ISSUE TITLE
GetListing returns wrong name

### ISSUE THREAD

**Issue by noxe** [robinrodricks/FluentFTP#946]
**FTP OS:** OS/400 is the remote operating system.

**FTP Server:** IBMOS400FTP

**Computer OS:** Windows 10

**FluentFTP Version:** 40.0.0

**Framework:** .NET 6

Hi - we have a problem with an specific FTP Server. When we do an GetListing("remote directory) - the resulting file names contains the directory name - and so an download fails because the directory name is wrong (doubled)

Here the ftp server contains an directory "download" - the GetListing shows correctly all files - but the Name contains the directory name - and the FullName shows the wrong directory because "download" is now 2 times in the path?

![image](https://user-images.githubusercontent.com/158478/189680813-3e00c254-ae52-46ef-91b6-32372385569e.png)

Filezilla:

![image](https://user-images.githubusercontent.com/158478/189680641-267ddecb-8188-4671-90af-d84d8d795459.png)

**Logs :**

```

# AutoConnect()

# AutoDetect(True, False)

# Connect()
Status:   Connecting to ***:21
Response: 220-QTCP at holter.ad.holter.at.
Response: 220 Connection will close if idle more than 5 minutes.
Status:   Detected FTP server: IBMOS400FTP
Command:  AUTH TLS
Response: 431 Requested security mechanism not available at this time.
Command:  USER ***
Response: 331 Enter password.
Command:  PASS ***
Response: 230 *** logged on.
Command:  FEAT
Response: 211-Feature listing follows:
Response: AUTH TLS
Response: AUTH GSS
Response: CCC
Response: PBSZ
Response: PROT
Response: ADAT
Response: ENC
Response: MIC
Response: CONF
Response: 211 End of feature listing.
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 501 OPTS unsuccessful; specified subcommand not recognized.
Command:  SYST
Response: 215  OS/400 is the remote operating system. The TCP/IP version is "V7R4M0".
Status:   Listing parser set to: IBMOS400

# GetListing("download", Auto)
Command:  PWD
Response: 257 "/kundenftp/KU0021235" is current directory.
Command:  TYPE I
Response: 200 Representation type is binary IMAGE.

# OpenPassiveDataStream(PASV, "LIST /kundenftp/KU0021235/download", 0)
Command:  PASV
Response: 227 Entering passive mode (212,183,28,50,158,96).
Status:   Connecting to ***:40544
Command:  LIST /kundenftp/KU0021235/download
Response: 125 List started.
+---------------------------------------+
Listing:  MARKUSP          8192 16.03.30 09:00:51 *DIR       download/datanorm/
Listing:  SICHERN          2865 22.09.01 04:36:04 *STMF      download/B0220831.013
Listing:  SICHERN           504 22.09.02 04:37:50 *STMF      download/B0220902.001
Listing:  SICHERN           320 22.09.02 04:37:50 *STMF      download/B0220902.002

```

**Comment by FanDjango** [comment]
I see what's going wrong. I will investigate.

**Comment by noxe** [comment]
thank you ✌️

**Comment by FanDjango** [comment]
Ok. I have got some observations and questions, after doing some research.

1. Does this work with a FluentFTP version prior to V.40?

2. It seems to me, that by listing a directory, the output `download/B0220831.013` is taken as a filename and appended to the listing path, giving a double `downloads`. This means that as a "quick" fix you could `SetWorkingDirectory` to `download` and then `GetListing("", FtpListOption.NoPath)`. Does this work for you?

**Comment by noxe** [comment]
Hi - no - it is the same also prior V.40 - we simply updated to V.40 today to test if it is already fixed probably.

2) yes - that seems to work as workaround.

3) sorry - i dont not fully understand your suggestion :)

we currently have this problem only with one specific ftp server - most other do not have this problem?

**Comment by FanDjango** [comment]
Thanks for your answer.

1. **Good**, I was worried that something had broken in the transition to V40.

2. If that "quick" fix works, as you say, then: I can see where the problem lies. Please use that approach for the time being. Can this problem then be considered as being **solved**?

3. Number three was created by the text editor by mistake. It was a continuation of number 2. I was trying to say: In the code, the case that you reported as an **issue** is not catered for. It never worked. So, for now, please use the quick fix as described in Number 2.

That being said: One could consider this scenario, that you discovered, to be a needed "enhancement" to the way OS400 FTP servers are handled.

**Comment by FanDjango** [comment]
> most other do not have this problem?

I do not know. Maybe they are all using the CWD - GetListing with NoPath method?

**Comment by noxe** [comment]
> I do not know. Maybe they are all using the CWD - GetListing with NoPath method?

no - i meant we serve many different ftp server - to be more specific - our customers specify many different ftp server - we always use the same code - but only this specific server has this problem.

all other we have seen so far work perfect with the original code?

**Comment by FanDjango** [comment]
Ok. I understand.

To make this "same same" code work for OS400 the server specific handler for IBMZOS400 needs to be "enhanced" to accept this szenario you reported.

So from a develpment standpoint:

1. YOU check for this specific server in your code and take a separate code path
2. YOU check `fullname` for slashes and take only the filename
3. FluentFTP fixes this problem and you don't need to change your code

If you help me in testing any changes, maybe 3. is possible.

**Comment by noxe** [comment]
ok - fully understand and many thanks for your fast help and replies! have to say this library is really amazing!

we can for sure do 1 and 2 - but i can also help of course for 3 - we test any changes with this specific server!

thank you 🤝

**Comment by FanDjango** [comment]
@robinrodricks As a first step could you put this on the **todo** list? With the help of @noxe I think this can be done within a sensible timeframe

**Comment by robinrodricks** [comment]
Thanks for handling this @FanDjango , added.

**Comment by FanDjango** [comment]
@noxe  I am worried that perhaps many users have encountered this flaw in the IBMOS400 server handler and have already "programmed around it". I assume that **you also** have somehow been _living with this_ until finally reporting it? Or have you just recently discovered this?

So a fix would cause some consternation among users that would then need to change their code. I believe it would be best to fix the problem but would like the owner @robinrodricks to chime in on this.

**Comment by FanDjango** [comment]
@noxe 
Can you use a `SITE` command to interrogate the current LISTFMT and NAMEFMT settings on that FTP server?

See [this](https://www.ibm.com/docs/en/i/7.2?topic=ssw_ibm_i_72/rzaiq/rzaiqsitet.htm)

**Comment by noxe** [comment]
> 



> I am worried that perhaps many users have encountered this flaw in the IBMOS400 server handler and have already "programmed around it". I assume that **you also** have somehow been _living with this_ until finally reporting it? Or have you just recently discovered this?

Hi - no - we did not. we used ftpwebrequest for years - and we switched to fluentftp just recently. we rolled out an update now to our customers and got some bug reports back - one of this was this one :)

**Comment by noxe** [comment]
> Can you use a `SITE` command to interrogate the current LISTFMT and NAMEFMT settings on that FTP server?

Hi - i hope i have done this correctly - i used filezilla and send a custom command:

Befehl:	SITE LISTFMT
Antwort:	250 Directory listing format (LISTFMT) option set to 0.
Befehl:	SITE NAMEFMT
Antwort:	250  Now using naming format "1".

**Comment by FanDjango** [comment]
@noxe When you have some time, could you use the `SITE` command as above and set LISTFMT to 1, then do the GetListing in your programm?

i.e. use `client.Execute("SITE LISTFMT 1"))` prior to your `client.GetListing(...)`

I would like to see the difference.

**Comment by noxe** [comment]
@FanDjango - hey - yes indeed - this makes an difference - after that the Name and FullName are correctly.

**Comment by FanDjango** [comment]
@noxe I would therefore recommend you use that as the best solution:

Something like this:

Pseudocode:
```
if (client.Servertype is OS400) client.Execute(.....)
in front of GetListing
```
This code will then work for all your users.

**Comment by noxe** [comment]
ok - thank you very much for your infos and help!

**Comment by FanDjango** [comment]
Ok, I have updated the Wiki to mention `SITE LISTFMT 1` as a possible workaround. Please feel free to issue again if you need more.
