### ISSUE TITLE
Is it possible to delete all files from a directory in one command? (empty a directory)

### ISSUE THREAD

**Issue by wertzui** [robinrodricks/FluentFTP#950]
**FTP OS:** Unix / Windows

**FTP Server:** Multiple and unknown

**Computer OS:** Linux

**FluentFTP Version:** 40.0.0

**Framework:** .NET 6

I need to delete all files in a directory on the server, but not the directory itself.
Is that possible with one command, or do I first need to call `GetListing()` and then `DeleteFile()` for all files?

**Comment by robinrodricks** [comment]
Can you try DeleteDirectory and then CreateDirectory.

DeleteDirectory has in-built recursion.

**Comment by wertzui** [comment]
That would also delete the folder. I need to keep the folder, because often the folder (or one file in it) is in use by another application.
Because of that I need some kind of "best effort" attempt to delete all files in one folder.

**Comment by FanDjango** [comment]
Ok, I did some more research. Some servers have actually got specialized RMDIR commands, like for example proftpd. And these are known to FluentFTP -

Here is the current list of such servers: Serv-U, proftpd.

In all other cases, FluentFTPs `DeleteDirectory(...)` will use its own `GetListing(...)...delete-loop`.

So, to make this work for you, all we need to do is make an option to `DeleteDirectory(...)` to leave the final directory intact.

**Comment by FanDjango** [comment]
..which I have done. There is PR out there now and once it is merged, you can do this:

New function overload to allow users of DeleteDirectory to optionally make this function leave the top level directory intact.

Using this will prevent use of any highly optimised server side RMDIR functionality on the uppermost level, but that's the price.

Usage:

		/// <summary>
		/// Deletes the specified directory and all its contents.
		/// </summary>
		/// <param name="path">The full or relative path of the directory to delete</param>
		/// <param name="options">Useful to delete hidden files or dot-files.</param>
		/// <param name="deleteFinalDir">Delete the top level dir too</param>
		public void DeleteDirectory(string path, FtpListOption options, bool deleteFinalDir = true)

**Comment by FanDjango** [comment]
@wertzui See the above amended usage for `EmptyDirectory(...)`. It has been merged and you could use it from now by getting the master branch down from GitHub.

Since some other things also cooking right now, a Nuget release is not immediately scheduled.
