### ISSUE TITLE
Add support for integration tests against Fubar Server

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#955]
https://github.com/FubarDevelopment/FtpServer could be an interesting server to test against as it does not even need Docker.

**Comment by robinrodricks** [comment]
Added to the [bucket list](https://github.com/robinrodricks/FluentFTP/wiki/Future-Plans). We will pick this up as and when we have free time. Comment on this issue if you want us to prioritize it. Thanks!

**Comment by FanDjango** [comment]
Might want to look at this sometime too: https://github.com/mooware/mooftpserv
