### ISSUE TITLE
Annoying NullReferenceException in DownloadStream for non-existent file

### ISSUE THREAD

**Issue by dittodhole** [robinrodricks/FluentFTP#961]
Hi there,

when debugging an application, which utilizes FluentFtp for ftp communication, it breaks due to some internal NullReferenceException when trying to download some non-existent file:

> System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=FluentFTP
  StackTrace:
   at FluentFTP.AsyncFtpClient.<DownloadFileInternalAsync>d__26.MoveNext()

Is there any chance to avoid this, so we do not have to uncheck NullReferenceException in "Exception Settings"?

Best
Andreas

**Comment by FanDjango** [comment]
Perhaps some sample code? A log excerpt showing what you are doing and which API call is called with which parms? We have a crystal ball but it is rather cloudy at the moment :-)

**Comment by FanDjango** [comment]
@jnyrup Good catch. I should have read this more carefully:
> when trying to download some non-existent file:
