### ISSUE TITLE
Credentials.Domain not used

### ISSUE THREAD

**Issue by hedandan1989** [robinrodricks/FluentFTP#965]
**FTP OS:**  Windows 

**FTP Server:**  QNAP NAS

**Computer OS:** Windows 10

**FluentFTP Version:** 40.0.0

**Framework:** .NET 6
`_ftpClient.Credentials = new NetworkCredential(userName, password, "domain.com");`

throw FtpAuthenticationException,but

`_ftpClient.Credentials = new NetworkCredential("userName@domain.com", password);`

`_ftpClient.Credentials = new NetworkCredential("domain\userName", password);`

can login

**Logs :**
FluentFTP.FtpAuthenticationException
  HResult=0x80131500
  Message=Login incorrect.
  Source=FluentFTP
  StackTrace:
   在 FluentFTP.AsyncFtpClient.<Authenticate>d__1.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 FluentFTP.AsyncFtpClient.<Authenticate>d__0.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 FluentFTP.AsyncFtpClient.<Connect>d__8.MoveNext()
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 HUASIN.Helpers.FluentFTP.FluentFTPHelper.<ConnectAsync>d__23.MoveNext() 在 C:\TFS\HUASIN.Helpers\HUASIN.Helpers\HUASIN.Helpers\FluentFTP\FluentFTPHelper.cs 中: 第 112 行

  此异常最初是在此调用堆栈中引发的: 
    FluentFTP.AsyncFtpClient.Authenticate(string, string, string, System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    FluentFTP.AsyncFtpClient.Authenticate(System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    FluentFTP.AsyncFtpClient.Connect(System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    ...
    [调用堆栈已截断]
```

**Comment by FanDjango** [comment]
Your server needs the `USER` command to be in one of the following formats:
```
USER userName@domain.com
or
USER domain\userName
```
This value comes from the `username` parameter of the credentials.

The domain value is only used if the server replies "332 Need account for login", then this parameters value will be plugged in to an `ACCT domain` command.
