### ISSUE TITLE
More forwarding of CancellationToken

### ISSUE THREAD

**Issue by jnyrup** [robinrodricks/FluentFTP#973]
These non-private methods do not take a `CancellationToken` but call a method that does take a `CancellationToken`.

* `AsyncFtpClient.PurgeSuccessfulUploadsAsync` -> `DeleteFile`
* `AsyncFtpClient.ResumeDownloadAsync` -> `OpenRead`
* `AsyncFtpClient.ResumeUploadAsync` -> `OpenAppend`
* `AsyncFtpClient.GetFilesToTransfer` -> `GetFileSize`
* `FtpSocketStream.ActivateEncryptionAsync` -> `AuthenticateAsClientAsync`
* `FtpSocketStream.AcceptAsync` -> `Socket.AcceptAsync`

I'd be happy to make a PR with the necessary code changes, but I have a question about how to handle potentially breaking changes in FluentFTP.

Take for example `AsyncFtpClient.PurgeSuccessfulUploadsAsync(IEnumerable<string> remotePaths)`.
I see two different ways to add support for `CancellationToken`s.

1)
_Change_ the method signature by adding an optional `CancellationToken` parameter. 
This is a _binary_ breaking change as one cannot simply _replace_ `FluentFTP.dll` as the method signature has changed.
This is not a _source_ breaking change as one can _recompile_ against FluentFTP without changing any code.
```cs
protected async Task PurgeSuccessfulUploadsAsync(IEnumerable<string> remotePaths, CancellationToken cancellationToken = default) {
	foreach (var remotePath in remotePaths) {
		await DeleteFile(remotePath, cancellationToken);
	}
}
```

2)
_Add_ an overload that takes an optional `CancellationToken`.
This is neither a binary nor a source breaking change, but now we have two overloads.
```cs
protected Task PurgeSuccessfulUploadsAsync(IEnumerable<string> remotePaths) =>
	PurgeSuccessfulUploadsAsync(remotePaths, CancellationToken.None);

protected async Task PurgeSuccessfulUploadsAsync(IEnumerable<string> remotePaths, CancellationToken cancellationToken = default) {
	foreach (var remotePath in remotePaths) {
		await DeleteFile(remotePath, cancellationToken);
	}
}
```

Essentially this boils down to how strictly FluentFTP follows [Semantic Versioning](https://semver.org/).

**Comment by robinrodricks** [comment]
I liberally increment the major version - only non-major features and non-breaking changes increment the feature version, otherwise I always increment the major.

We will release this as part of v41, no issues.

**Comment by jnyrup** [comment]
I take that as a sign that you're alright with option 1)?
