### ISSUE TITLE
What should be the default behavior of DeleteDirectory?

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#98]
Since 17.2 DeleteDirectory() uses these options as default : `ForceList | Recursive`. This means that a LIST command is used (OS specific directory listings) and we attempt to get recursive listings in one command. This is faster than using machine listings (MLSD command) since we don't have to get one listing per sub directory. The only caveats are:

- Slightly less reliable parsing using OS-specific parsers 
- Not all servers support the "recursive" flag. In this case a "directory not empty" error will be sent.

So what should be the default behavior? Use machine listings even though they are slower? Or keep the present config? Or perhaps auto catch the "directory not empty" error and then repeat the command with machine listings?

**Comment by hgupta9** [comment]
Or maybe instead of the FtpListOption which is confusing in this context we could have:

- `enum FtpDeleteOption`
  - `None` - the default mode. uses LIST command to discover files in folder.
  - `Machine` - use machine listings (MLSD command) to discover files in folder.
  - `Hidden` - find hidden/dot-files files as well

**Comment by jblacker** [comment]
Personally I like the idea of using the most common supported method as the default.  If most servers support LIST & Recursive, and you'd say that the OS-specific parsers are reliable enough, then let's use that method as default.   As long as you have options to modify the default behavior for special cases and the  method handles the edge cases properly it should be fine.

**Comment by robinrodricks** [comment]
Closing since no issues regarding this have come up.
