### ISSUE TITLE
FtpCommandException: Code: 550 Message:  Unable to find file

### ISSUE THREAD

**Issue by noxe** [robinrodricks/FluentFTP#994]
**FTP OS:** OS/400

**FTP Server:**  IBMOS400FTP

**Computer OS:** Windows 11

**FluentFTP Version:** 40 / 41

**Framework:** .NET 6

Hi - it seems there is an problem when an FTP Server contains files which contains whitespaces. See screenshot:

![image](https://user-images.githubusercontent.com/158478/193844106-ec62ce04-2af5-41e9-9f4e-d8ef86504864.png)

Donwloading the files results in an exception, while the real problem is that the ListItem does not contain the correct name, see screen:

![image](https://user-images.githubusercontent.com/158478/193844464-0f67dff7-4868-4ec3-8658-a6666b477655.png)

var listing = client.GetListing();
        var listItem = listing.FirstOrDefault(l => l.Name.StartsWith("B0001417017"));   // but real name is B0001417017 J
        if (listItem != null)
        {
            client.DownloadBytes(out byte[] data, listItem.Name);

FtpCommandException: Code: 550 Message:  Unable to find file /kundenftp/ku0021250/download/B0001417017

**Logs :**

# AutoConnect()

# AutoDetect(True, False)

# Connect()
Status:   Connecting to ***:21
Response: 220-QTCP at holter.ad.holter.at.
Response: 220 Connection will close if idle more than 5 minutes.
Status:   Detected FTP server: IBMOS400FTP
Command:  AUTH TLS
Response: 431 Requested security mechanism not available at this time.
Command:  USER ***
Response: 331 Enter password.
Command:  PASS ***
Response: 230 KU0021250 logged on.
Command:  FEAT
Response: 211-Feature listing follows:
Response: AUTH TLS
Response: AUTH GSS
Response: CCC
Response: PBSZ
Response: PROT
Response: ADAT
Response: ENC
Response: MIC
Response: CONF
Response: 211 End of feature listing.
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 501 OPTS unsuccessful; specified subcommand not recognized.
Command:  SYST
Response: 215  OS/400 is the remote operating system. The TCP/IP version is "V7R4M0".
Status:   Listing parser set to: IBMOS400

# SetWorkingDirectory("/kundenftp/ku0021250/download")
Command:  CWD /kundenftp/ku0021250/download
Response: 250 "/kundenftp/ku0021250/download" is current directory.

# GetListing(null, Auto)
Command:  PWD
Response: 257 "/kundenftp/ku0021250/download" is current directory.
Command:  TYPE I
Response: 200 Representation type is binary IMAGE.

# OpenPassiveDataStream(PASV, "LIST /kundenftp/ku0021250/download", 0)
Command:  PASV
Response: 227 Entering passive mode (212,183,28,50,77,81).
Status:   Connecting to ***:19793
Command:  LIST /kundenftp/ku0021250/download
Response: 125 List started.
+---------------------------------------+
Listing:  MARKUSP          8192 22.10.03 20:24:41 *DIR       datanorm/
Listing:  SICHERN           319 22.09.20 17:00:58 *STMF      B0220920.001
Listing:  SICHERN           319 22.09.20 17:08:41 *STMF      B0220920.002
Listing:  SICHERN           319 22.09.21 04:37:36 *STMF      B0220921.001
Listing:  SICHERN           319 22.09.21 04:37:36 *STMF      B0220921.002
Listing:  SICHERN           319 22.09.21 04:37:37 *STMF      B0220921.003
Listing:  SICHERN           319 22.09.21 04:37:37 *STMF      B0220921.004
Listing:  SICHERN           461 22.09.21 11:21:11 *STMF      B0220921.005
Listing:  SICHERN           502 22.09.21 11:56:49 *STMF      B0220921.006
Listing:  SICHERN           685 22.09.21 16:16:18 *STMF      B0220921.007
Listing:  SICHERN           502 22.09.22 04:37:04 *STMF      B0220922.001
Listing:  SICHERN           319 22.09.22 04:37:05 *STMF      B0220922.002
Listing:  SICHERN           461 22.09.22 04:56:42 *STMF      B0220922.003
Listing:  SICHERN           318 22.09.22 07:41:14 *STMF      B0220922.004
Listing:  SICHERN           460 22.09.22 07:41:15 *STMF      B0220922.005
Listing:  SICHERN           649 22.09.22 09:15:42 *STMF      B0220922.006
Listing:  SICHERN           318 22.10.04 14:11:30 *STMF      B0221004.018
Listing:  CHRISTOPHJ       1239 22.09.22 17:32:36 *STMF      B0001386562
Listing:  SICHERN           649 22.09.23 04:40:10 *STMF      B0220923.001
Listing:  SICHERN           319 22.09.23 09:59:56 *STMF      B0220923.002
Listing:  SICHERN           319 22.09.23 14:18:47 *STMF      B0220923.003
Listing:  SICHERN           318 22.09.26 04:33:47 *STMF      B0220926.001
Listing:  SICHERN           319 22.09.26 04:33:47 *STMF      B0220926.002
Listing:  SICHERN           319 22.09.26 04:33:47 *STMF      B0220926.003
Listing:  PIERRED          3815 22.09.26 10:08:34 *STMF      B0001417017 J
Listing:  SICHERN           321 22.09.26 13:31:10 *STMF      B0220926.004
Listing:  MAVE             6204 22.09.27 17:05:58 *STMF      B0001408836

**Comment by FanDjango** [comment]
@noxe Send me an email at ms@ansynova.com

**Comment by FanDjango** [comment]
I sent you what to do...

**Comment by noxe** [comment]
sorry - dont understand - what do you mean?

**Comment by noxe** [comment]
ah sorry - you mean the "  client.Execute("SITE LISTFMT 1");"

i did not thought about that this would be the same issue - because the other one was about the directory name.

just testet it - and using SITE LISTFMT seems to work also here!

**Comment by FanDjango** [comment]
You should have gotten an email with my email contact info

**Comment by FanDjango** [comment]
@noxe ms@ansynova.com
